import type { WalletLocale } from "../i18n/i18n";

const EN={open:"Smart Account & Capital",title:"Smart Account & Capital",smart:"SMART ACCOUNT / SPONSORSHIP",capital:"CAPITAL REVIEW",unavailable:"Unavailable until verified runtime evidence is supplied",ready:"Verified for this public Testnet snapshot",missing:"No verified review supplied",exit:"Immediate exit",revoke:"Revoke",nonGuarantee:"Yield, price and peg are not guaranteed.",ai:"AI may explain this evidence but cannot sign, change parameters or execute."} as const;
type Key=keyof typeof EN;
const COPY:Record<WalletLocale,Record<Key,string>>={
  en:EN,
  "zh-Hans":{open:"智能账户与资本",title:"智能账户与资本",smart:"智能账户 / 赞助",capital:"资本审阅",unavailable:"在提供经验证的运行时证据前不可用",ready:"此公开测试网快照已验证",missing:"未提供经验证的审阅",exit:"立即退出",revoke:"撤销",nonGuarantee:"收益、价格和锚定均不保证。",ai:"AI 只能解释证据，不能签名、修改参数或执行。"},
  "zh-Hant":{open:"智能帳戶與資本",title:"智能帳戶與資本",smart:"智能帳戶 / 贊助",capital:"資本審閱",unavailable:"在提供已驗證的執行階段證據前不可用",ready:"此公開測試網快照已驗證",missing:"未提供已驗證的審閱",exit:"立即退出",revoke:"撤銷",nonGuarantee:"收益、價格和錨定均不保證。",ai:"AI 只能解釋證據，不能簽署、修改參數或執行。"},
  ja:{open:"スマートアカウントと資本",title:"スマートアカウントと資本",smart:"スマートアカウント / スポンサー",capital:"資本レビュー",unavailable:"検証済み実行時証拠が提供されるまで利用不可",ready:"この公開テストネットのスナップショットは検証済み",missing:"検証済みレビューなし",exit:"即時終了",revoke:"取り消す",nonGuarantee:"利回り、価格、ペッグは保証されません。",ai:"AI は証拠を説明できますが、署名、パラメータ変更、実行はできません。"},
  ko:{open:"스마트 계정 및 자본",title:"스마트 계정 및 자본",smart:"스마트 계정 / 후원",capital:"자본 검토",unavailable:"검증된 런타임 증거가 제공될 때까지 사용할 수 없음",ready:"이 공개 테스트넷 스냅샷이 검증됨",missing:"검증된 검토 없음",exit:"즉시 종료",revoke:"철회",nonGuarantee:"수익률, 가격 및 페그는 보장되지 않습니다.",ai:"AI는 증거만 설명하며 서명, 매개변수 변경 또는 실행을 할 수 없습니다."},
  es:{open:"Cuenta inteligente y capital",title:"Cuenta inteligente y capital",smart:"CUENTA INTELIGENTE / PATROCINIO",capital:"REVISIÓN DE CAPITAL",unavailable:"No disponible hasta recibir evidencia verificada",ready:"Instantánea pública de Testnet verificada",missing:"Sin revisión verificada",exit:"Salida inmediata",revoke:"Revocar",nonGuarantee:"El rendimiento, el precio y la paridad no están garantizados.",ai:"La IA puede explicar la evidencia, pero no firmar, cambiar parámetros ni ejecutar."},
  fr:{open:"Compte intelligent et capital",title:"Compte intelligent et capital",smart:"COMPTE INTELLIGENT / PARRAINAGE",capital:"EXAMEN DU CAPITAL",unavailable:"Indisponible sans preuve d’exécution vérifiée",ready:"Instantané Testnet public vérifié",missing:"Aucun examen vérifié",exit:"Sortie immédiate",revoke:"Révoquer",nonGuarantee:"Le rendement, le prix et l’ancrage ne sont pas garantis.",ai:"L’IA peut expliquer les preuves, sans signer, modifier les paramètres ni exécuter."},
  de:{open:"Smart Account & Kapital",title:"Smart Account & Kapital",smart:"SMART ACCOUNT / SPONSORING",capital:"KAPITALPRÜFUNG",unavailable:"Bis zu verifizierten Laufzeitnachweisen nicht verfügbar",ready:"Öffentlicher Testnet-Snapshot verifiziert",missing:"Keine verifizierte Prüfung",exit:"Sofortiger Ausstieg",revoke:"Widerrufen",nonGuarantee:"Rendite, Preis und Bindung sind nicht garantiert.",ai:"KI darf Nachweise erklären, aber nicht signieren, Parameter ändern oder ausführen."},
  pt:{open:"Conta inteligente e capital",title:"Conta inteligente e capital",smart:"CONTA INTELIGENTE / PATROCÍNIO",capital:"REVISÃO DE CAPITAL",unavailable:"Indisponível até haver evidência verificada",ready:"Snapshot público da Testnet verificado",missing:"Sem revisão verificada",exit:"Saída imediata",revoke:"Revogar",nonGuarantee:"Rendimento, preço e paridade não são garantidos.",ai:"A IA pode explicar evidências, mas não assinar, alterar parâmetros ou executar."},
  ru:{open:"Смарт-аккаунт и капитал",title:"Смарт-аккаунт и капитал",smart:"СМАРТ-АККАУНТ / СПОНСОРСТВО",capital:"ПРОВЕРКА КАПИТАЛА",unavailable:"Недоступно без проверенных данных среды",ready:"Публичный снимок Testnet проверен",missing:"Нет проверенного обзора",exit:"Немедленный выход",revoke:"Отозвать",nonGuarantee:"Доходность, цена и привязка не гарантируются.",ai:"ИИ может объяснять данные, но не подписывать, менять параметры или выполнять."},
  ar:{open:"الحساب الذكي ورأس المال",title:"الحساب الذكي ورأس المال",smart:"الحساب الذكي / الرعاية",capital:"مراجعة رأس المال",unavailable:"غير متاح حتى تقديم دليل تشغيل موثّق",ready:"تم التحقق من لقطة شبكة الاختبار العامة",missing:"لا توجد مراجعة موثّقة",exit:"خروج فوري",revoke:"إلغاء",nonGuarantee:"العائد والسعر والربط غير مضمونة.",ai:"يمكن للذكاء الاصطناعي شرح الدليل، ولا يمكنه التوقيع أو تغيير المعلمات أو التنفيذ."},
  id:{open:"Smart Account & modal",title:"Smart Account & modal",smart:"SMART ACCOUNT / SPONSOR",capital:"TINJAUAN MODAL",unavailable:"Tidak tersedia hingga bukti runtime terverifikasi diberikan",ready:"Snapshot Testnet publik terverifikasi",missing:"Tidak ada tinjauan terverifikasi",exit:"Keluar segera",revoke:"Cabut",nonGuarantee:"Imbal hasil, harga, dan patokan tidak dijamin.",ai:"AI boleh menjelaskan bukti, tetapi tidak dapat menandatangani, mengubah parameter, atau mengeksekusi."},
};
export function controlCopy(locale:WalletLocale,key:Key):string{return COPY[locale][key]}
