import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";
import { CanonicalWalletGatewayAdapter,createGatewayChallenge,createProductSessionProof,httpBodyDigest,parseAuthorizationRequest,signAuthorization,signGatewayChallenge,WalletAuthError } from "../src/index.js";
import {ACCOUNT_SECRET,NOW,PRODUCT_DEVICE_SECRET,REGISTRY,request} from "./fixtures.mjs";

function approvedRegistry(){const value=JSON.parse(readFileSync(new URL("../central-registry.json",import.meta.url),"utf8"));for(const product of value.products){product.schemaVersion=4;product.webOrigins=[]}const social=value.products.find(product=>product.productId==="social");social.reviewState="approved";social.enabled=true;social.webOrigins=["https://social.ynxweb4.com"];return value}
function completion(){const authorizationRequest=parseAuthorizationRequest(request(),{now:NOW,registry:REGISTRY});const walletApproval=signAuthorization(authorizationRequest,{accountSecret:ACCOUNT_SECRET,issuedAt:NOW.toISOString()});const challenge=createGatewayChallenge(walletApproval,{challenge:"gateway_challenge_abcdefghijklmnop",expiresAt:"2026-07-15T12:03:00.000Z"},NOW);return{authorizationRequest,walletApproval,gatewayCompletion:signGatewayChallenge(challenge,PRODUCT_DEVICE_SECRET)}}
function proof(session,path="/v1/wallet/sessions/introspect",body="{}",nonce="proof_nonce_abcdefghijklmnopqrstu"){return createProductSessionProof(session,{method:"POST",path,bodyDigest:httpBodyDigest(body),nonce,issuedAt:"2026-07-15T12:00:00.000Z",expiresAt:"2026-07-15T12:00:30.000Z"},PRODUCT_DEVICE_SECRET)}
function context(session, path="/v1/wallet/sessions/introspect", body="{}", method="POST"){return{method,path,bodyDigest:httpBodyDigest(body),origin:session.origin}}

test("server-selected approved registry completes a canonical Product Session",()=>{const gateway=new CanonicalWalletGatewayAdapter(approvedRegistry());const session=gateway.complete(completion(),NOW);assert.equal(session.productClientId,"ynx-social-v1");assert.equal(gateway.snapshot().sessionStore.sessions.length,1)});
test("disabled registry fails closed and caller cannot inject a permissive registry",()=>{const disabled=JSON.parse(readFileSync(new URL("../central-registry.json",import.meta.url),"utf8")),gateway=new CanonicalWalletGatewayAdapter(disabled);assert.throws(()=>gateway.complete(completion(),NOW),code("REGISTRY_DISABLED"));assert.throws(()=>gateway.complete({...completion(),registryEntry:{}},NOW),code("UNKNOWN_OR_MISSING_FIELD"))});
test("P-256 sender-constrained introspection binds method, path, body and origin and consumes proof",()=>{const gateway=new CanonicalWalletGatewayAdapter(approvedRegistry()),session=gateway.complete(completion(),NOW),body="{}",signed=proof(session);const result=gateway.introspect({proof:signed,requiredScopes:["account:read"]},context(session),NOW);assert.equal(result.active,true);assert.throws(()=>gateway.introspect({proof:signed,requiredScopes:["account:read"]},context(session),NOW),code("REPLAY"))});
test("fault/fuzz: wrong HTTP binding, origin, device and unknown fields fail closed",()=>{const gateway=new CanonicalWalletGatewayAdapter(approvedRegistry()),session=gateway.complete(completion(),NOW),signed=proof(session);for(const requestContext of [context(session,"/v1/wallet/sessions/introspect","{}","GET"),context(session,"/v1/wallet/sessions/revoke"),context(session,"/v1/wallet/sessions/introspect","tampered"),{...context(session),origin:"https://attacker.ynx.invalid"}])assert.throws(()=>gateway.introspect({proof:signed,requiredScopes:["account:read"]},requestContext,NOW),code("HTTP_BINDING_MISMATCH"));assert.throws(()=>gateway.introspect({proof:{...signed,extra:true},requiredScopes:["account:read"]},context(session),NOW),code("UNKNOWN_OR_MISSING_FIELD"))});
test("canonical proof rejects pre-session timestamps and ambiguous encoded paths",()=>{const gateway=new CanonicalWalletGatewayAdapter(approvedRegistry()),session=gateway.complete(completion(),NOW);assert.throws(()=>createProductSessionProof(session,{method:"POST",path:"/v1/wallet/%73essions/introspect",bodyDigest:httpBodyDigest("{}"),nonce:"encoded_path_nonce_abcdefghijklmnop",issuedAt:"2026-07-15T12:00:00.000Z",expiresAt:"2026-07-15T12:00:30.000Z"},PRODUCT_DEVICE_SECRET),code("INVALID_FIELD"));const signed=createProductSessionProof(session,{method:"POST",path:"/v1/wallet/sessions/introspect",bodyDigest:httpBodyDigest("{}"),nonce:"old_timestamp_nonce_abcdefghijklmnop",issuedAt:"2026-07-15T11:59:59.000Z",expiresAt:"2026-07-15T12:00:30.000Z"},PRODUCT_DEVICE_SECRET);assert.throws(()=>gateway.introspect({proof:signed,requiredScopes:["account:read"]},context(session),NOW),code("INVALID_TIME"))});
test("session revoke requires a separate path-bound proof and survives restart",()=>{const registry=approvedRegistry(),gateway=new CanonicalWalletGatewayAdapter(registry),session=gateway.complete(completion(),NOW),signed=proof(session,"/v1/wallet/sessions/revoke","{}","revoke_nonce_abcdefghijklmnopqrstuvwxyz12");gateway.revokeSession({proof:signed},context(session,"/v1/wallet/sessions/revoke"),NOW);const restarted=new CanonicalWalletGatewayAdapter(registry,gateway.snapshot()),fresh=proof(session,"/v1/wallet/sessions/introspect","{}","fresh_nonce_abcdefghijklmnopqrstuvwxyz123");assert.throws(()=>restarted.introspect({proof:fresh,requiredScopes:["account:read"]},context(session),NOW),code("REVOKED"))});
test("property/soak: 2,000 unique proofs retain sorted replay state and reject reuse",()=>{const registry=approvedRegistry(),gateway=new CanonicalWalletGatewayAdapter(registry),session=gateway.complete(completion(),NOW);for(let index=0;index<2000;index+=1){const nonce=`proof_${index.toString().padStart(8,"0")}_abcdefghijklmnopqr`,signed=proof(session,"/v1/wallet/sessions/introspect","{}",nonce);gateway.introspect({proof:signed,requiredScopes:["account:read"]},context(session),NOW)}const snapshot=gateway.snapshot();assert.equal(snapshot.consumedProductProofs.length,2000);assert.deepEqual([...snapshot.consumedProductProofs].sort(),snapshot.consumedProductProofs)});
test("published origin-bound Product Session HTTP proof vector remains deterministic",()=>{const vector=JSON.parse(readFileSync(new URL("../testdata/product-session-http-proof-v2.json",import.meta.url),"utf8")),gateway=new CanonicalWalletGatewayAdapter(approvedRegistry()),session=gateway.complete(completion(),NOW),signed=createProductSessionProof(session,vector.input,PRODUCT_DEVICE_SECRET);assert.deepEqual(session,vector.session);assert.deepEqual(signed,vector.proof)});
function code(expected){return error=>error instanceof WalletAuthError&&error.code===expected}
