import assert from "node:assert/strict";
import { performance } from "node:perf_hooks";
import { test } from "node:test";
import { assertSignedIntentActive, createSignedIntent, exportSignedIntent, parseSignedIntent, signedIntentDigest, WalletAuthError, walletIdentity } from "../src/index.js";

const SECRET=`${"00".repeat(31)}01`, ACCOUNT=walletIdentity(SECRET).account, NOW=new Date("2026-07-22T12:00:00.000Z"), PARAMETERS="44".repeat(32);
function input(overrides={}){return {accountSecret:SECRET,schemaVersion:1,intentId:"intent-user-op-001",sessionBinding:"11".repeat(32),productClientId:"ynx-pay-v1",bundleId:"com.ynxweb4.pay",account:ACCOUNT,action:"user-operation",parametersDigest:PARAMETERS,evidence:{sourceClass:"ynx-authoritative",source:"https://gateway.ynxweb4.com/evidence/operations/001",asOf:"2026-07-22T11:59:00.000Z",version:"1",status:"available",digest:"55".repeat(32),confidenceBps:10000,coverage:"Exact operation simulation and sponsor policy response."},trust:{issuer:"https://gateway.ynxweb4.com/",policy:"https://gateway.ynxweb4.com/policies/transaction-v1",decision:"allow",reasons:["exact-session-binding","simulation-passed"]},approval:{actor:"human",mode:"biometric",reviewedDigest:PARAMETERS},ai:{used:true,role:"explain-only",provider:"YNX AI Gateway",model:"bounded-security-review",outputDigest:"66".repeat(32)},nonce:"intent_nonce_abcdefghijklmnopqrst",issuedAt:"2026-07-22T11:59:30.000Z",expiresAt:"2026-07-22T12:04:30.000Z",...overrides}}
function context(overrides={}){return {sessionBinding:"11".repeat(32),productClientId:"ynx-pay-v1",bundleId:"com.ynxweb4.pay",account:ACCOUNT,action:"user-operation",parametersDigest:PARAMETERS,revokedIntentDigests:[],...overrides}}

test("Signed Intent binds Product Session, parameters, Evidence, Trust and human approval",()=>{const intent=createSignedIntent(input());assert.equal(assertSignedIntentActive(intent,context(),NOW).account,ACCOUNT);assert.equal(JSON.parse(exportSignedIntent(intent)).signature,intent.signature);});
test("AI boundary is explain-only and cannot become the approving actor",()=>{assert.throws(()=>createSignedIntent(input({approval:{actor:"ai",mode:"biometric",reviewedDigest:PARAMETERS}})),code("INVALID_FIELD"));assert.throws(()=>createSignedIntent(input({ai:{used:true,role:"none",provider:"x",model:"y",outputDigest:"66".repeat(32)}})),code("AI_BOUNDARY"));});
test("property: every session/product/account/action/parameter substitution fails closed",()=>{const intent=createSignedIntent(input());for(const mutation of [{sessionBinding:"22".repeat(32)},{productClientId:"ynx-social-v1"},{bundleId:"com.ynx.social"},{account:walletIdentity(`${"00".repeat(31)}02`).account},{action:"native-transfer"},{parametersDigest:"77".repeat(32)}])assert.throws(()=>assertSignedIntentActive(intent,context(mutation),NOW),code("INTENT_BINDING_MISMATCH"));});
test("fuzz/fault: unknown fields, signature tamper, expiry and revoke fail closed",()=>{const intent=createSignedIntent(input());assert.throws(()=>parseSignedIntent({...intent,extra:true}),code("UNKNOWN_OR_MISSING_FIELD"));assert.throws(()=>parseSignedIntent({...intent,signature:`${intent.signature.slice(0,-2)}00`}),code("INVALID_INTENT_SIGNATURE"));assert.throws(()=>assertSignedIntentActive(intent,context(),new Date("2026-07-22T12:04:30.000Z")),code("EXPIRED"));assert.throws(()=>assertSignedIntentActive(intent,context({revokedIntentDigests:[signedIntentDigest(intent)]}),NOW),code("REVOKED"));});
test("soak/benchmark: 2,000 signed exports verify deterministically",()=>{const intent=createSignedIntent(input()),started=performance.now();for(let i=0;i<2000;i+=1)assert.equal(parseSignedIntent(JSON.parse(exportSignedIntent(intent))).signature,intent.signature);const elapsed=performance.now()-started;assert.ok(2000/(elapsed/1000)>60,`verification throughput was ${(2000/(elapsed/1000)).toFixed(1)} intents/s`);});
function code(expected){return error=>error instanceof WalletAuthError&&error.code===expected}
