import test from 'node:test';import assert from 'node:assert/strict';
import {createServer} from 'node:http';import {mkdtempSync,readFileSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {randomBytes,generateKeyPairSync,sign} from 'node:crypto';import {p256} from '@noble/curves/nist.js';
import {ProductSessionGatewayNodeHost} from '../src/product-session-gateway-node-host.js';
import {createProductSessionRequest,signProductSessionApproval,signProductSessionChallenge} from '../src/product-session-v2.js';
import {createProductSessionProofV2} from '../src/product-session-proof-v2.js';import {encodeProductSessionGatewayProofHeaderV2} from '../src/product-session-gateway-client.js';
import {canonicalJSON} from '../src/canonical.js';import {httpBodyDigest} from '../src/session-proof.js';import {backendBodyDigest} from '../src/central-browser-backend-auth.js';import {parsePrivateBusinessRegistrations} from '../src/product-session-registry.js';
const registry=JSON.parse(readFileSync(new URL('../product-session-registry.json',import.meta.url))),token=()=>randomBytes(32).toString('base64url'),issuer='https://wallet-auth.ynxweb4.com',path='/v2/browser-sessions/product-revalidate';
async function fixture(productId='music',platform='android',enabled=true){
 const product=registry.products.find(p=>p.productId===productId),scopes=productId==='music'?['music.library']:productId==='shop'?['account:read','shop:seller:operate']:productId==='pay-merchant'?['account:read','merchant:session:create']:['account:read'],registration={productId,platform,keyId:'qa',allowedScopes:scopes},entry=parsePrivateBusinessRegistrations(registry,[registration])[0];
 const directory=mkdtempSync(join(tmpdir(),'ynx-private-business-')),key=generateKeyPairSync('ed25519'),device=new Uint8Array(32).fill(3),secret=Buffer.from(device).toString('base64url');let now=new Date();
 const config={statePath:join(directory,'state'),now:()=>now,tokenFactory:token,centralBrowser:true,privateBusinessRevalidation:enabled,...(enabled?{privateBackendRegistrations:[registration]}:{}),centralBackend:{backendClients:[{clientId:entry.backendClientId,keyId:'qa',publicKey:key.publicKey.export({format:'pem',type:'spki'})}],familySealKey:randomBytes(32)}};
 const host=new ProductSessionGatewayNodeHost(registry,config),server=createServer(host.handler());await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const url=`http://127.0.0.1:${server.address().port}`;
 async function call(route,body,headers={}){const r=await fetch(url+route,{method:'POST',headers:{'content-type':'application/json',...headers},body:canonicalJSON(body),signal:AbortSignal.timeout(5000)});return{status:r.status,body:await r.json()};}
 const request=createProductSessionRequest(registry,{productId,platform,deviceId:token(),deviceKey:Buffer.from(p256.getPublicKey(device,true)).toString('base64url'),scopes:scopes,purpose:'Explicit private product approval',nonce:token(),state:token()},now),approval=signProductSessionApproval(registry,request,{accountSecret:'1'.padStart(64,'0'),scopes:request.scopes,expiresAt:request.expiresAt},now);
 const headers={'x-request-id':'req_'+token(),...(platform==='web'?{origin:product.webOrigin}:{})};const challenge=await call('/v2/product-sessions/challenge',{request,approval},headers);assert.equal(challenge.status,200);const complete=await call('/v2/product-sessions/complete',{request,approval,completion:signProductSessionChallenge(challenge.body.result,secret)},{...headers,'x-request-id':'req_'+token()});assert.equal(complete.status,200);const session=complete.body.result,input={clientId:entry.backendClientId,session,requiredScopes:scopes};
 function backend(body,patch={}){const unsigned={version:1,issuer,audience:issuer+'/v2/browser-sessions',clientId:body.clientId,keyId:'qa',method:'POST',path,bodySha256:backendBodyDigest(body),issuedAt:now.toISOString(),nonce:token(),...patch};return{'x-ynx-backend-proof':Buffer.from(canonicalJSON({...unsigned,signature:sign(null,Buffer.from(canonicalJSON(unsigned)),key.privateKey).toString('base64url')})).toString('base64url')};}
 const deviceHeaders=(route,body)=>({'x-request-id':'req_'+token(),...(platform==='web'?{origin:product.webOrigin}:{}),'x-ynx-product-session-proof-v2':encodeProductSessionGatewayProofHeaderV2(createProductSessionProofV2(session,{method:'POST',path:route,bodyDigest:httpBodyDigest(canonicalJSON(body)),nonce:token(),issuedAt:now.toISOString(),expiresAt:new Date(Math.min(+now+30000,Date.parse(session.expiresAt))).toISOString()},secret))});
 return{input,session,config,backend,call,host,deviceHeaders,advance(ms){now=new Date(+now+ms)},close:async()=>{await new Promise(resolve=>server.close(resolve));rmSync(directory,{recursive:true,force:true})}};
}
for(const [product,platform] of [['music','android'],['music','ios'],['card','web'],['pay-merchant','web'],['shop','web']])test(`actual ${product}/${platform} private role revalidates exact original authorization without identity consent`,async()=>{const f=await fixture(product,platform);try{
 const before=canonicalJSON(f.host.snapshot());const result=await f.call(path,f.input,f.backend(f.input));assert.equal(result.status,200);assert.deepEqual(result.body.session,f.session);assert.equal(canonicalJSON(f.host.snapshot()),before);
 const same=f.backend(f.input);assert.equal((await f.call(path,f.input,same)).status,200);assert.equal((await f.call(path,f.input,same)).body.error.code,'SSO_BACKEND_AUTH_REPLAY');
 for(const patch of [{platform:'windows'},{origin:'https://social.ynxweb4.com'},{callback:'ynx-social://com.ynx.social'},{clientId:'ynx-social-v1'},{account:'other'},{deviceId:token()}]){const changed={...f.input,session:{...f.session,...patch}};assert.notEqual((await f.call(path,changed,f.backend(changed))).status,200);}
 const widened={...f.input,requiredScopes:[product==='music'?'music.creator':product==='shop'?'shop:orders:write':product==='pay-merchant'?'merchant:refunds:write':'card:application:write']};assert.notEqual((await f.call(path,widened,f.backend(widened))).status,200);
 for(const patch of [{keyId:'wrong'},{method:'GET'},{path:'/v2/browser-sessions/token'}])assert.notEqual((await f.call(path,f.input,f.backend(f.input,patch))).status,200);
 const identity={clientId:f.input.clientId,origin:f.session.origin,redirectUri:f.session.callback,state:token(),codeChallenge:token(),codeChallengeMethod:'S256'};assert.notEqual((await f.call('/v2/browser-sessions/bootstrap',identity)).status,200);
 const route='/v2/product-sessions/revoke';assert.equal((await f.call(route,{},f.deviceHeaders(route,{}))).status,200);assert.equal((await f.call(path,f.input,f.backend(f.input))).body.error.code,'SESSION_REVOKED');
}finally{await f.close()}});
test('private backend disabled by default despite a provisioned public key',async()=>{const f=await fixture('music','android',false);try{assert.equal((await f.call(path,f.input,f.backend(f.input))).body.error.code,'SSO_CLIENT_MISMATCH');}finally{await f.close()}});
test('private role startup requires exact registration, operator key and bounded scopes',async()=>{const f=await fixture();try{
 assert.throws(()=>new ProductSessionGatewayNodeHost(registry,{...f.config,centralBackend:{...f.config.centralBackend,backendClients:[]}}));
 for(const registration of [{productId:'music',platform:'web',keyId:'qa',allowedScopes:['music.library']},{productId:'music',platform:'android',keyId:'qa',allowedScopes:['identity:read']},{productId:'social',platform:'android',keyId:'qa',allowedScopes:['music.library']},{productId:'merchant-console',platform:'web',keyId:'qa',allowedScopes:['account:read']}])assert.throws(()=>parsePrivateBusinessRegistrations(registry,[registration]));
 assert.throws(()=>parsePrivateBusinessRegistrations(registry,[f.config.privateBackendRegistrations[0],f.config.privateBackendRegistrations[0]]));
 assert.throws(()=>new ProductSessionGatewayNodeHost(registry,{...f.config,privateBusinessRevalidation:false}));
}finally{await f.close()}});
