package com.ynxweb4.mail;

import android.app.*;import android.content.*;import android.graphics.Color;import android.net.*;import android.os.*;import android.provider.Settings;import android.security.keystore.*;import android.view.*;import android.widget.*;
import androidx.appcompat.app.AppCompatActivity;import androidx.core.os.LocaleListCompat;import androidx.appcompat.app.AppCompatDelegate;
import org.json.*;import java.math.BigInteger;import java.nio.charset.StandardCharsets;import java.security.*;import java.security.interfaces.ECPublicKey;import java.text.*;import java.time.*;import java.time.format.DateTimeFormatter;import java.util.*;

public final class MainActivity extends AppCompatActivity {
  static final String BLUE="#002FA7", CLIENT="ynx-mail-v1", BUNDLE="com.ynxweb4.mail", CALLBACK="ynxmail://wallet-auth/callback";
  final String[] locales={"system","en","zh-Hans","zh-Hant","ja","ko","es","fr","de","pt","ru","ar","id"};
  SharedPreferences prefs; LinearLayout body; TextView status;
  public void onCreate(Bundle state){super.onCreate(state);prefs=getSharedPreferences("ynx_mail",MODE_PRIVATE);applySavedLocale();render();handleCallback(getIntent());}
  protected void onNewIntent(Intent i){super.onNewIntent(i);handleCallback(i);}
  void render(){ScrollView scroll=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(20),dp(18),dp(20),dp(28));scroll.addView(root);setContentView(scroll);
    TextView brand=text("YNX / MAIL",14,true);brand.setTextColor(Color.parseColor(BLUE));root.addView(brand);root.addView(text(getString(R.string.inbox),34,true));root.addView(text(DateFormat.getDateTimeInstance(DateFormat.MEDIUM,DateFormat.SHORT).format(new Date()),13,false));
    status=text(network()?getString(R.string.empty):getString(R.string.offline),14,false);status.setPadding(0,dp(8),0,dp(12));root.addView(status);
    Spinner lang=new Spinner(this);ArrayAdapter<String>a=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,locales);lang.setAdapter(a);lang.setSelection(Math.max(0,Arrays.asList(locales).indexOf(prefs.getString("locale","system"))));lang.setContentDescription("Language / 语言");lang.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?>p){}public void onItemSelected(android.widget.AdapterView<?>p,View v,int pos,long id){String n=locales[pos];if(!n.equals(prefs.getString("locale","system"))){prefs.edit().putString("locale",n).apply();applySavedLocale();recreate();}}});root.addView(lang);
    EditText search=input(getString(R.string.search));search.setContentDescription(getString(R.string.search));root.addView(search);
    LinearLayout actions=new LinearLayout(this);actions.setOrientation(LinearLayout.HORIZONTAL);actions.addView(button(getString(R.string.compose),v->compose()));actions.addView(button(getString(R.string.sign_in),v->wallet(false)));root.addView(actions);
    body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);root.addView(body);showMailbox();
    root.addView(section(getString(R.string.ai)));root.addView(text(getString(R.string.privacy),14,false));Spinner aiLang=new Spinner(this);aiLang.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,Arrays.copyOfRange(locales,1,locales.length)));aiLang.setSelection(Math.max(0,prefs.getInt("ai_lang",0)));aiLang.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?>p){}public void onItemSelected(android.widget.AdapterView<?>p,View v,int pos,long id){prefs.edit().putInt("ai_lang",pos).apply();}});aiLang.setContentDescription(getString(R.string.ai_language));root.addView(aiLang);
    root.addView(button(getString(R.string.approve),v->new AlertDialog.Builder(this).setTitle(getString(R.string.ai)).setMessage(getString(R.string.privacy)+"\n\n"+getString(R.string.unavailable)).setNegativeButton(android.R.string.cancel,null).setPositiveButton(getString(R.string.approve),(d,w)->status.setText(getString(R.string.unavailable))).show()));
    root.addView(section(getString(R.string.security)));root.addView(text(getString(R.string.security),13,false));root.addView(button(getString(R.string.recover),v->wallet(true)));
  }
  void showMailbox(){body.removeAllViews();String draft=prefs.getString("draft_body","");if(!draft.isEmpty()){body.addView(section(getString(R.string.drafts)));body.addView(text(draft,16,false));body.addView(text(getString(R.string.delivery_failure),13,false));body.addView(button(getString(R.string.retry),v->status.setText(network()?getString(R.string.unavailable):getString(R.string.offline))));}body.addView(section(getString(R.string.inbox)));body.addView(text(getString(R.string.empty),18,false));TextView folders=text(getString(R.string.archive)+"   •   "+getString(R.string.spam),14,true);folders.setContentDescription(getString(R.string.a11y_nav));body.addView(folders);body.addView(section(getString(R.string.thread)));LinearLayout row=new LinearLayout(this);row.addView(button(getString(R.string.block_sender),v->status.setText(getString(R.string.unavailable))));row.addView(button(getString(R.string.report_trust),v->status.setText(getString(R.string.unavailable))));body.addView(row);body.addView(button(getString(R.string.appeal),v->status.setText(getString(R.string.unavailable))));}
  void compose(){LinearLayout form=new LinearLayout(this);form.setPadding(dp(16),0,dp(16),0);form.setOrientation(LinearLayout.VERTICAL);EditText to=input("@recipient");EditText subject=input("Subject");EditText msg=input("Message");msg.setMinLines(5);msg.setText(prefs.getString("draft_body",""));form.addView(to);form.addView(subject);form.addView(msg);form.addView(text(getString(R.string.attachment),12,false));new AlertDialog.Builder(this).setTitle(getString(R.string.compose)).setView(form).setNegativeButton(android.R.string.cancel,(d,w)->{prefs.edit().putString("draft_body",msg.getText().toString()).apply();showMailbox();}).setPositiveButton(getString(R.string.send_preview),(d,w)->{prefs.edit().putString("draft_body",msg.getText().toString()).apply();status.setText(network()?getString(R.string.unavailable):getString(R.string.offline));showMailbox();}).show();}
  void wallet(boolean recovery){try{JSONObject q=new JSONObject();DateTimeFormatter fmt=DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'").withZone(ZoneOffset.UTC);String now=fmt.format(Instant.now());String exp=fmt.format(Instant.now().plusSeconds(300));q.put("version","1");q.put("nonce",nonce());q.put("chainId","ynx_6423-1");q.put("requestingProduct","mail");q.put("productClientId",CLIENT);q.put("bundleId",BUNDLE);q.put("productDeviceAlgorithm","p256-sha256");q.put("productDeviceKey",deviceKey());q.put("callback",CALLBACK);JSONArray scopes=new JSONArray();scopes.put(recovery?"mail:recover":"mail:account");q.put("scopes",scopes);q.put("purpose",recovery?"Recover YNX Mail on this device":"Sign in to YNX Mail on this device");q.put("issuedAt",now);q.put("expiresAt",exp);getSharedPreferences("ynx_mail",MODE_PRIVATE).edit().putString("pending_request",canonical(q)).apply();String encoded=Base64.getUrlEncoder().withoutPadding().encodeToString(canonical(q).getBytes(StandardCharsets.UTF_8));startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("ynxwallet://authorize?request="+encoded)));}catch(Exception e){status.setText(getString(R.string.unavailable)+": "+e.getClass().getSimpleName());}}
  void handleCallback(Intent i){if(i==null||i.getData()==null)return;try{Uri u=i.getData();if(!"ynxmail".equals(u.getScheme())||!"wallet-auth".equals(u.getHost())||!"/callback".equals(u.getPath())||u.getFragment()!=null||!u.getQueryParameterNames().equals(Collections.singleton("response")))throw new SecurityException();String encoded=u.getQueryParameter("response"),pending=prefs.getString("pending_request",null);if(encoded==null||pending==null)throw new SecurityException();JSONObject response=new JSONObject(new String(Base64.getUrlDecoder().decode(encoded),StandardCharsets.UTF_8)),request=new JSONObject(pending);for(String k:Arrays.asList("version","nonce","chainId","requestingProduct","productClientId","bundleId","productDeviceAlgorithm","productDeviceKey","callback","purpose"))if(!request.getString(k).equals(response.getString(k)))throw new SecurityException();if(!request.getJSONArray("scopes").toString().equals(response.getJSONArray("scopes").toString()))throw new SecurityException();String nonce=response.getString("nonce");if(prefs.getBoolean("consumed."+nonce,false))throw new SecurityException();String expected=hex(MessageDigest.getInstance("SHA-256").digest(("YNX_WALLET_AUTH_REQUEST_V1\n"+canonical(request)).getBytes(StandardCharsets.UTF_8)));if(!expected.equals(response.getString("requestDigest")))throw new SecurityException();prefs.edit().putBoolean("consumed."+nonce,true).putString("wallet_response",canonical(response)).apply();status.setText(getString(R.string.unavailable));}catch(Exception e){status.setText(getString(R.string.security));}}
  String hex(byte[]v){StringBuilder b=new StringBuilder();for(byte x:v)b.append(String.format("%02x",x));return b.toString();}
  String canonical(Object v)throws JSONException{if(v==JSONObject.NULL)return "null";if(v instanceof String)return JSONObject.quote((String)v);if(v instanceof JSONArray){JSONArray a=(JSONArray)v;StringBuilder b=new StringBuilder("[");for(int i=0;i<a.length();i++){if(i>0)b.append(",");b.append(canonical(a.get(i)));}return b.append("]").toString();}if(v instanceof JSONObject){JSONObject o=(JSONObject)v;ArrayList<String>k=new ArrayList<>();o.keys().forEachRemaining(k::add);Collections.sort(k);StringBuilder b=new StringBuilder("{");for(int i=0;i<k.size();i++){if(i>0)b.append(",");b.append(JSONObject.quote(k.get(i))).append(":").append(canonical(o.get(k.get(i))));}return b.append("}").toString();}return String.valueOf(v);}
  String deviceKey()throws Exception{KeyStore ks=KeyStore.getInstance("AndroidKeyStore");ks.load(null);if(!ks.containsAlias("ynx_mail_product_device")){KeyPairGenerator g=KeyPairGenerator.getInstance(KeyProperties.KEY_ALGORITHM_EC,"AndroidKeyStore");g.initialize(new KeyGenParameterSpec.Builder("ynx_mail_product_device",KeyProperties.PURPOSE_SIGN|KeyProperties.PURPOSE_VERIFY).setDigests(KeyProperties.DIGEST_SHA256).setAlgorithmParameterSpec(new java.security.spec.ECGenParameterSpec("secp256r1")).build());g.generateKeyPair();}ECPublicKey p=(ECPublicKey)ks.getCertificate("ynx_mail_product_device").getPublicKey();byte[]x=fixed(p.getW().getAffineX());byte[]out=new byte[33];out[0]=(byte)(p.getW().getAffineY().testBit(0)?3:2);System.arraycopy(x,0,out,1,32);return Base64.getUrlEncoder().withoutPadding().encodeToString(out);}
  byte[] fixed(BigInteger n){byte[]b=n.toByteArray(),o=new byte[32];System.arraycopy(b,Math.max(0,b.length-32),o,Math.max(0,32-b.length),Math.min(32,b.length));return o;}String nonce(){byte[]b=new byte[32];new SecureRandom().nextBytes(b);return Base64.getUrlEncoder().withoutPadding().encodeToString(b);}
  void applySavedLocale(){String l=prefs==null?"system":prefs.getString("locale","system");AppCompatDelegate.setApplicationLocales("system".equals(l)?LocaleListCompat.getEmptyLocaleList():LocaleListCompat.forLanguageTags(l));}
  boolean network(){android.net.ConnectivityManager c=(android.net.ConnectivityManager)getSystemService(CONNECTIVITY_SERVICE);Network n=c.getActiveNetwork();NetworkCapabilities x=n==null?null:c.getNetworkCapabilities(n);return x!=null&&x.hasCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET);}
  TextView text(String s,int z,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(Color.parseColor("#101828"));v.setTypeface(null,bold?1:0);v.setPadding(0,dp(5),0,dp(5));return v;}TextView section(String s){TextView v=text(s,20,true);v.setPadding(0,dp(22),0,dp(8));return v;}EditText input(String hint){EditText e=new EditText(this);e.setHint(hint);e.setSingleLine(false);return e;}Button button(String s,View.OnClickListener l){Button b=new Button(this);b.setText(s);b.setOnClickListener(l);b.setAllCaps(false);return b;}int dp(int n){return(int)(n*getResources().getDisplayMetrics().density);}
}
