global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/ynx-alerts.yml

scrape_configs:
  - job_name: ynx-chaind
    metrics_path: /metrics
    static_configs:
      - targets:
          - ynx-chaind:6420
        labels:
          network: ynx-testnet
          service: ynx-chaind
  - job_name: ynx-indexerd
    metrics_path: /metrics
    static_configs:
      - targets:
          - ynx-indexerd:6426
        labels:
          network: ynx-testnet
          service: ynx-indexerd
  - job_name: ynx-explorerd
    metrics_path: /metrics
    static_configs:
      - targets:
          - ynx-explorerd:6427
        labels:
          network: ynx-testnet
          service: ynx-explorerd
  - job_name: ynx-faucetd
    metrics_path: /metrics
    static_configs:
      - targets:
          - ynx-faucetd:6428
        labels:
          network: ynx-testnet
          service: ynx-faucetd
