import assert from "node:assert/strict";
import { access, readFile } from "node:fs/promises";

const config=JSON.parse(await readFile(new URL("../app.json",import.meta.url),"utf8")).expo;
const source=await readFile(new URL("../App.tsx",import.meta.url),"utf8");
const i18n=await readFile(new URL("../src/i18n/i18n.ts",import.meta.url),"utf8");
const audit=await readFile(new URL("../src/protocol/authorizationAudit.ts",import.meta.url),"utf8");
const nonceReplayStore=await readFile(new URL("../src/protocol/replayStore.ts",import.meta.url),"utf8");
const authorizationCallbackStore=await readFile(new URL("../src/protocol/authorizationCallbackStore.ts",import.meta.url),"utf8");
const actionReplayStore=await readFile(new URL("../src/protocol/actionReplayStore.ts",import.meta.url),"utf8");
const actionCallbackStore=await readFile(new URL("../src/protocol/actionCallbackStore.ts",import.meta.url),"utf8");
const controls=await readFile(new URL("../src/control/controlSurface.ts",import.meta.url),"utf8");
const controlCopy=await readFile(new URL("../src/control/controlCopy.ts",import.meta.url),"utf8");
const androidGradle=await readFile(new URL("../android/app/build.gradle",import.meta.url),"utf8");
const androidActivity=await readFile(new URL("../android/app/src/main/java/com/ynxweb4/wallet/MainActivity.kt",import.meta.url),"utf8");
const androidManifest=await readFile(new URL("../android/app/src/main/AndroidManifest.xml",import.meta.url),"utf8");
const androidApplication=await readFile(new URL("../android/app/src/main/java/com/ynxweb4/wallet/MainApplication.kt",import.meta.url),"utf8");
const exactCallbackModule=await readFile(new URL("../android/app/src/main/java/com/ynxweb4/wallet/ExactCallbackModule.kt",import.meta.url),"utf8");
const exactCallbackPackage=await readFile(new URL("../android/app/src/main/java/com/ynxweb4/wallet/ExactCallbackPackage.kt",import.meta.url),"utf8");
const secureStorage=await readFile(new URL("../src/storage/secureStorage.ts",import.meta.url),"utf8");
const walletRepository=await readFile(new URL("../src/storage/walletRepository.ts",import.meta.url),"utf8");
const onboardingState=await readFile(new URL("../src/state/onboardingState.ts",import.meta.url),"utf8");
const localAuthorization=await readFile(new URL("../src/security/localAuthorization.ts",import.meta.url),"utf8");
const localAuthorizationPolicy=await readFile(new URL("../src/security/localAuthorizationPolicy.ts",import.meta.url),"utf8");
const localAuthorizationAttemptPolicy=await readFile(new URL("../src/security/localAuthorizationAttemptPolicy.ts",import.meta.url),"utf8");
const recoveryKeyGenerationPolicy=await readFile(new URL("../src/security/recoveryKeyGenerationPolicy.ts",import.meta.url),"utf8");
const recoveryDisplayPrivacyPolicy=await readFile(new URL("../src/security/recoveryDisplayPrivacyPolicy.ts",import.meta.url),"utf8");
const recoveryRevealPolicy=await readFile(new URL("../src/security/recoveryRevealPolicy.ts",import.meta.url),"utf8");
const storageResetLifecyclePolicy=await readFile(new URL("../src/security/storageResetLifecyclePolicy.ts",import.meta.url),"utf8");
const authorizationLifecyclePolicy=await readFile(new URL("../src/security/authorizationLifecyclePolicy.ts",import.meta.url),"utf8");
const callbackHandoffPolicy=await readFile(new URL("../src/security/callbackHandoffPolicy.ts",import.meta.url),"utf8");
const authorizationCallbackHandoffPolicy=await readFile(new URL("../src/security/authorizationCallbackHandoffPolicy.ts",import.meta.url),"utf8");
const actionCallbackHandoffPolicy=await readFile(new URL("../src/security/actionCallbackHandoffPolicy.ts",import.meta.url),"utf8");
const registeredCallbackHandoffPolicy=await readFile(new URL("../src/security/registeredCallbackHandoffPolicy.ts",import.meta.url),"utf8");
const foregroundDeepLinkPolicy=await readFile(new URL("../src/security/foregroundDeepLinkPolicy.ts",import.meta.url),"utf8");
const sensitiveOperationPolicy=await readFile(new URL("../src/security/sensitiveOperationPolicy.ts",import.meta.url),"utf8");
const startupDeepLinkPolicy=await readFile(new URL("../src/security/startupDeepLinkPolicy.ts",import.meta.url),"utf8");
const walletOpenLinkPolicy=await readFile(new URL("../src/security/walletOpenLinkPolicy.ts",import.meta.url),"utf8");
const unlockPolicy=await readFile(new URL("../src/security/unlockPolicy.ts",import.meta.url),"utf8");
const lockState=await readFile(new URL("../src/state/lockState.ts",import.meta.url),"utf8");
const clipboardPrivacy=await readFile(new URL("../src/security/clipboardPrivacy.ts",import.meta.url),"utf8");
const signingPlugin=await readFile(new URL("../plugins/withYnxAndroidReleaseSigning.js",import.meta.url),"utf8");
const androidQaBuild=await readFile(new URL("./build-disposable-android-qa-release.sh",import.meta.url),"utf8");
const androidQaVerify=await readFile(new URL("./verify-android-api36-qa-receipt.mjs",import.meta.url),"utf8");
const actionDeepLinkParsers=await Promise.all(["exchange-action.js","developer-deployment.js","dex-action.js","quant-action.js"].map((file)=>readFile(new URL(`../../../packages/wallet-auth/src/${file}`,import.meta.url),"utf8")));
const canonicalDeepLink=await readFile(new URL("../../../packages/wallet-auth/src/deep-link.js",import.meta.url),"utf8");
const walletAuthCrypto=await readFile(new URL("../../../packages/wallet-auth/src/crypto.js",import.meta.url),"utf8");
const walletAuthSecretSigning=await Promise.all(["exchange-action.js","quant-action.js","intent.js","native-transfer.js","developer-deployment.js","dex-action.js"].map(file=>readFile(new URL(`../../../packages/wallet-auth/src/${file}`,import.meta.url),"utf8")));
assert.equal(config.name,"YNX Wallet");
assert.equal(config.version,"1.0.1");
assert.equal(config.scheme,"ynxwallet");
assert.equal(config.android.package,"com.ynxweb4.wallet");
assert.equal(config.ios.bundleIdentifier,"com.ynxweb4.wallet");
assert.equal(config.extra.nativeChainId,"ynx_6423-1");
assert.equal(config.extra.evmChainId,6423);
assert.equal(config.extra.nativeAsset,"YNXT");
assert.equal(config.extra.internalAcceptanceShell,false);
assert.equal(config.userInterfaceStyle,"automatic");
assert.equal(config.android.intentFilters[0].data[0].host,"authorize");
assert.equal(config.android.intentFilters[0].data[1].host,"action");
assert.equal(config.android.intentFilters[0].data[2].host,"open");
assert.equal(source.includes("if(isExactWalletOpenLink(url))"),true,"Wallet must route the safe launcher through its byte-exact policy");
assert.equal(walletOpenLinkPolicy.includes('url==="ynxwallet://open"'),true,"Wallet must support only the exact safe launcher without treating ambiguous URL variants as open");
assert.ok(source.includes("appStateRef.current=next"),"deep-link foreground admission must track AppState changes synchronously");
assert.ok(source.includes("foregroundGate.receive(url,appStateRef.current)"),"every runtime and startup deep link must enter the foreground lifecycle gate");
assert.ok(source.includes("foregroundDeepLinkGateRef.current?.stateChanged(next)"),"queued Android intents must be released only by a synchronous active AppState transition");
for(const required of ['if(state==="active")','state!=="inactive"&&state!=="background"','this.pending!==null','this.ambiguous=true','state!=="active"','this.handle(pending)'])assert.ok(foregroundDeepLinkPolicy.includes(required),`foreground deep-link gate must fail closed through ${required}`);
for(const required of ["!current.active","attempt.generation!==current.generation","attempt.binding!==current.binding"])assert.ok(sensitiveOperationPolicy.includes(required),`sensitive operation policy must enforce ${required}`);
for(const required of ["class ExclusiveAttemptGate","if(this.active)return null","deleteAttemptGate.current.tryBegin()",'disabled={busy||confirm!==account.label}'])assert.ok(`${sensitiveOperationPolicy}\n${source}`.includes(required),`destructive account removal must prevent synchronous attempt reentry through ${required}`);
assert.ok((source.match(/attemptGate\.current\.tryBegin\(\)/g)??[]).length===6,"authorization approve/reject and all four action callback Modals must synchronously reject attempt reentry");
for(const required of ["sendAttemptGate.current.tryBegin()","saveAttemptGate.current.tryBegin()","revokeAttemptGate.current.tryBegin()",'disabled={revokeBusy}'])assert.ok(source.includes(required),`transfer, secure onboarding save and approval revoke must synchronously reject reentry through ${required}`);
for(const boundary of ["transaction-sign","recovery-view","account-import","account-delete"])assert.ok(source.includes(`authorizeLocalKeyUse("${boundary}")`),`Wallet must retain biometric purpose ${boundary}`);
assert.ok(source.includes('authorizeLocalKeyUse("wallet-reset")'),"unreadable Wallet reset must require strong local biometric authorization");
for(const required of ['autoComplete={secure?"off":undefined}','importantForAutofill={secure?"noExcludeDescendants":"auto"}','textContentType={secure?"none":undefined}','spellCheck={!secure}'])assert.ok(source.includes(required),`secure recovery-key input must exclude Android Autofill and text learning through ${required}`);
for(const required of ["attempt.epoch!==current.epoch",'current.appState!=="active"',"!current.privacyReady","current.manifestPresent||!current.storageErrorPresent"])assert.ok(storageResetLifecyclePolicy.includes(required),`unreadable Wallet reset must fail closed through ${required}`);
for(const required of ["const attempt={epoch:unlockEpochRef.current}","privacyReady:privacyStateRef.current.ready","assertStorageResetActive(attempt"])assert.ok(source.includes(required),`in-flight Wallet reset must retain exact privacy/lock epoch through ${required}`);
assert.equal((source.match(/storageAttemptGate\.current\.tryBegin\(\)/g)??[]).length,2,"Wallet reconstruction/retry and destructive reset must share one synchronous attempt gate");
assert.ok(source.includes("await repository.resetCorruptStorage(assertActive);await reconstruct()"),"destructive reset must reconstruct storage while retaining the shared attempt gate");
assert.ok((source.match(/useSensitiveOperationGuard\(/g)??[]).length>=6,"send, recovery, onboarding, delete, revoke and the guard implementation must share lifecycle invalidation");
for(const required of ["repository.addAccount(onboardingAccountInput(saving,new Date().toISOString()),()=>sensitiveGuard.verify(attempt))","repository.renameAccount(account.account,label.trim(),()=>sensitiveGuard.verify(attempt))","repository.deleteAccount(account.account,()=>sensitiveGuard.verify(attempt))","authorizationAudit.revoke(record.requestDigest,new Date().toISOString(),()=>sensitiveGuard.verify(attempt))","sensitiveGuard.verify(attempt);const result=await client.broadcast"])assert.ok(source.includes(required),`sensitive mutations must verify lifecycle at ${required}`);
for(const required of ["private pending:Promise<void>=Promise.resolve()","return this.enqueue(()=>this.appendExclusive","return this.enqueue(()=>this.revokeExclusive","this.pending=result.then(()=>undefined,()=>undefined)"])assert.ok(audit.includes(required),`authorization audit mutations must serialize through ${required}`);
for(const required of ["assertDecisionTransition(records,digest,action,account)",'action==="intent-approved"||action==="request-rejected"',"Wallet authorization request is already decided","Wallet authorization callback was already returned","Wallet authorization callback account differs from its approval intent"])assert.ok(audit.includes(required),`authorization decision audit must linearize approve/reject through ${required}`);
for(const required of ["assertActive:()=>void=()=>{}","assertActive();","await this.storage.setItem("])assert.ok(nonceReplayStore.includes(required),`authorization replay consumption must revalidate lifecycle at the storage linearization point through ${required}`);
assert.equal(source.includes("new PersistentNonceStore"),false,"canonical authorization runtime must not consume a legacy nonce before a recoverable callback is staged");
for(const required of ['STORE_KEY="ynx.wallet.authorization-callbacks.v2"','LEGACY_NONCE_KEY="ynx.wallet.auth-nonces.v1"','const responseURL=await createResponse()','assertActive();assertBinding(bound,now())','state:"pending" as const','state:"delivered" as const,responseURL:null','records.some(item=>item.nonce===bound.nonce)','legacyNonces.has(bound.nonce)','discardExpired'])assert.ok(authorizationCallbackStore.includes(required),`authorization callback persistence must fail closed through ${required}`);
assert.ok(source.includes("authorizationCallbacks.discardExpired(new Date())"),"Wallet reconstruction must clear expired authorization callback payloads while retaining replay state");
assert.equal((source.match(/await completePersistentActionCallbackHandoff\(actionCallbacks,/g)??[]).length,4,"all four signed action callbacks must use the persistent handoff state machine");
for(const required of ["append(request:AuthorizationRequest", "assertActive:()=>void=()=>{}", "assertActive();\n    await this.save([...records,record])"])assert.ok(audit.includes(required),`authorization audit decisions must revalidate lifecycle at the storage linearization point through ${required}`);
for(const required of ["store.prepare(request,account,createResponse,now,assertActive)","await ensureApprovalIntent();assertActive();await openCallback(responseURL)","await ensureReturnedAudit();await store.complete(request,responseURL);complete();"])assert.ok(authorizationCallbackHandoffPolicy.includes(required),`recoverable authorization callback handoff must enforce ${required}`);
for(const required of ["store.reject(request,account,now,assertActive)","await ensureRejectedAudit();complete()"] )assert.ok(authorizationCallbackHandoffPolicy.includes(required),`explicit authorization rejection must enforce ${required}`);
assert.ok(source.includes("completePersistentAuthorizationCallbackHandoff(authorizationCallbacks,activeRequest,selected.account"),"canonical authorization callback must use the persistent restart-safe handoff state machine");
assert.ok(source.includes('authorizationAudit.ensure(activeRequest,{action:"intent-approved"')&&source.includes('authorizationAudit.ensure(activeRequest,{action:"approval-returned"'),"authorization recovery must idempotently restore its exact approval audit transitions");
assert.ok(source.includes("rejectPersistentAuthorizationRequest(authorizationCallbacks,request,selected.account")&&source.includes('authorizationAudit.ensure(request,{action:"request-rejected"'),"explicit rejection must atomically clear pending delivery before an idempotent rejection audit");
for(const required of ["const responseURL=await store.prepare","assertBeforeHandoff();","await openCallback(responseURL);","await store.complete(binding.key,responseURL);","complete();"])assert.ok(actionCallbackHandoffPolicy.includes(required),`action callback handoff must enforce ${required}`);
assert.equal((source.match(/openRegisteredCallback\(/g)??[]).length,6,"all five signed callback flows and their helper must use registered callback handoff");
assert.equal((source.match(/Linking\.openURL\(/g)??[]).length,1,"signed callbacks must never bypass the registered callback helper");
for(const required of ['callback.toString()!==registeredCallback','keys.length===1&&keys[0]==="response"','url!==`${registeredCallback}?response=${response}`','platform==="android"&&callback.protocol!=="https:"','if(!exactAndroidBridge)','await exactAndroidBridge(url,bundleId)','await fallback(url)'])assert.ok(registeredCallbackHandoffPolicy.includes(required),`registered callback handoff must fail closed through ${required}`);
for(const required of ['Intent(Intent.ACTION_VIEW, uri)','setPackage(packageName)','Intent.CATEGORY_BROWSABLE','Intent.FLAG_ACTIVITY_NEW_TASK','YNX_CALLBACK_PACKAGE_NOT_FOUND','scheme == "http" || scheme == "https"'])assert.ok(exactCallbackModule.includes(required),`Android callback bridge must enforce ${required}`);
assert.ok(exactCallbackPackage.includes("listOf(ExactCallbackModule(reactContext))"),"Android callback bridge package must register its native module");
assert.ok(androidApplication.includes("add(ExactCallbackPackage())"),"Android application must install the exact callback package bridge");
for(const required of ['action:"intent-approved"','action:"approval-returned"','action:"request-rejected"'])assert.ok(source.includes(`${required},account:selected.account`)&&source.includes("()=>guard.verify(attempt,new Date())"),`authorization ${required} must stay bound to its active Modal lifecycle`);
for(const required of ["MAX_AUDIT_RECORDS=1000","MAX_AUDIT_BYTES=1024*1024","raw.length>MAX_AUDIT_BYTES","records.length>=MAX_AUDIT_RECORDS","await this.save([...records,record])"])assert.ok(audit.includes(required),`authorization audit must fail closed at bounded capacity through ${required}`);
for(const required of ["assertStoredTransition(records,record)","Wallet authorization audit contains conflicting decisions","Wallet authorization audit callback has no approval intent","Wallet authorization audit revocation has no returned approval"])assert.ok(audit.includes(required),`authorization audit reconstruction must replay its decision state machine through ${required}`);
assert.ok(androidActivity.includes("window.addFlags(WindowManager.LayoutParams.FLAG_SECURE)"),"Android native launch window must set FLAG_SECURE before React starts");
assert.ok(androidActivity.indexOf("window.addFlags(WindowManager.LayoutParams.FLAG_SECURE)")<androidActivity.indexOf("super.onCreate(null)"),"Android FLAG_SECURE must precede React/splash lifecycle startup");
for(const required of ['android:fullBackupContent="@xml/secure_store_backup_rules"','android:dataExtractionRules="@xml/secure_store_data_extraction_rules"'])assert.ok(androidManifest.includes(required),`Android manifest must bind SecureStore backup exclusion: ${required}`);
assert.ok(secureStorage.includes("WHEN_UNLOCKED_THIS_DEVICE_ONLY"),"Wallet secrets must use device-bound secure storage accessible only while unlocked");
for(const required of ['MUTATION_KEY = "ynx.wallet.mutation.v1"','beginMutation("add"','beginMutation("delete"','await this.recoverPendingMutation()','private enqueue<T>'])assert.ok(walletRepository.includes(required),`Wallet account storage must preserve restart-safe mutation boundary ${required}`);
for(const required of ["removeCompletedLegacyMigration(manifest)","parseLegacyIdentity(serialized)","Legacy secure identity conflicts with the migrated Wallet manifest"])assert.ok(walletRepository.includes(required),`Wallet restart must complete strict legacy-secret cleanup through ${required}`);
for(const required of ["resetCorruptStorage(assertActive","assertActive();await this.storage.deleteItem(secretKey(item.account))","assertActive();\n    await this.storage.deleteItem(MANIFEST_KEY)","assertActive();\n    await this.storage.deleteItem(LEGACY_IDENTITY_KEY)","assertActive();\n    await this.storage.deleteItem(MUTATION_KEY)"])assert.ok(walletRepository.includes(required),`unreadable Wallet reset must revalidate lifecycle through ${required}`);
for(const required of ["BIOMETRIC_STRONG","disableDeviceFallback: true",'biometricsSecurityLevel: "strong"'])assert.ok(`${localAuthorization}\n${localAuthorizationPolicy}`.includes(required),`local key authorization must require ${required}`);
for(const required of ["export function withSecretBytes","try { return operation(secret); }","finally { secret.fill(0); }","bytes.fill(0); throw new WalletAuthError"])assert.ok(walletAuthCrypto.includes(required),`temporary signing key bytes must zero through ${required}`);
for(const signer of walletAuthSecretSigning){assert.ok(signer.includes("withSecretBytes"),"every Wallet signing domain must use the zeroing key-byte boundary");assert.equal(/hexToBytes\([^)]*accountSecret/.test(signer),false,"Wallet signing domains must not create untracked secret byte buffers")}
for(const required of ["class LocalAuthorizationAttemptCoordinator","attempt.generation!==this.generation","this.activePrompt=prompt","const hadActivePrompt=this.activePrompt!==null","this.activePrompt=null"])assert.ok(localAuthorizationAttemptPolicy.includes(required),`biometric attempt lifecycle must enforce ${required}`);
for(const required of ['Platform.OS==="android"&&nativePromptActive','LocalAuthentication.cancelAuthenticate().catch(()=>undefined)','attempts.assertActive(attempt);const result=await platformLocalAuthentication.hasHardware()','const prompt=attempts.beginPrompt(attempt)','attempts.assertActive(attempt);return result','attempts.finishPrompt(prompt)'])assert.ok(localAuthorization.includes(required),`native biometric authorization must fail closed through ${required}`);
for(const required of ['cancelLocalKeyAuthorization();unlockEpochRef.current+=1;dispatchLock({type:"lock",reason:"restart"})','if(next!=="active"){cancelLocalKeyAuthorization();unlockEpochRef.current+=1','cancelLocalKeyAuthorization();unlockEpochRef.current+=1;dispatchLock({type:"lock",reason:"user"})','cancelLocalKeyAuthorization();unlockEpochRef.current+=1;epoch=unlockEpochRef.current','function dismissSensitiveSheet(close:()=>void){cancelLocalKeyAuthorization();close()}'])assert.ok(source.includes(required),`Wallet lifecycle must actively cancel biometrics through ${required}`);
assert.ok(source.includes('const handleLink=useCallback((url:string)=>{\n    cancelLocalKeyAuthorization();try{const parsedURL=new URL(url)'),"a foreground-admitted replacement deep link must cancel any in-flight biometric before parsing or replacing its review");
assert.equal((source.match(/onRequestClose=\{\(\) => dismissSensitiveSheet\(close\)\}/g)??[]).length,15,"every native Modal dismissal must cancel an in-flight biometric prompt");
assert.ok(source.includes('AppState.addEventListener("change"'),"Wallet must observe application background state");
assert.ok(source.includes('dispatchLock({type:"lock",reason:"background"})'),"Wallet must lock when leaving the active state");
for(const setter of ["setAuthorization(null)","setExchangeAction(null)","setDeveloperDeployment(null)","setDexAction(null)","setQuantAction(null)"])assert.ok(source.includes(setter),`background/link handling must clear ${setter}`);
for(const required of ["attempt.generation!==current.generation","attempt.account!==current.account","now.toISOString()>=expiresAt"])assert.ok(authorizationLifecyclePolicy.includes(required),`authorization lifecycle must fail closed on ${required}`);
assert.ok((source.match(/useAuthorizationAttemptGuard\(selected\.account,request\.expiresAt\)/g)??[]).length===5,"all five authorization/action Modals must use the lifecycle attempt guard");
assert.ok(source.includes("parseAuthorizationRequest(activeRequest,{now,registry:PRODUCT_REGISTRY})"),"canonical authorization must revalidate expiry after private-key access and before signing");
assert.equal(source.includes("actionReplays"),false,"runtime must not bypass recoverable action callback state with the legacy consume-only store");
for(const required of ['CALLBACK_STORE_KEY="ynx.wallet.action-callbacks.v2"','LEGACY_REPLAY_KEY="ynx.wallet.action-replays.v1"',"const responseURL=await createResponse();","assertActive();assertBinding(binding,now());",'state:"pending" as const', 'state:"delivered" as const,responseURL:null',"Wallet action callback state conflicts with legacy replay state","responseURL!==`${callback}?response=${response}`","serialized.length>MAX_STORE_BYTES",'record.state==="pending"&&record.expiresAt<=now',"if(discarded>0)await this.save(next)"])assert.ok(actionCallbackStore.includes(required),`persistent action callback state must fail closed through ${required}`);
assert.ok(source.includes("actionCallbacks.discardExpired(new Date())"),"process reconstruction must clear expired pending callback payloads while retaining replay markers");
assert.ok(actionReplayStore.includes('ACTION_REPLAY_KEY="ynx.wallet.action-replays.v1"'),"legacy action replay format must remain available for migration compatibility tests");
for(const parser of actionDeepLinkParsers)assert.ok(parser.includes("link is not canonical"),"every action deep-link parser must reject byte-noncanonical URLs after strict request parsing");
for(const required of ["callback.toString() !== response.callback","url !== `${expectedCallback}?response=${response}`","parsed.port","expected.port"])assert.ok(canonicalDeepLink.includes(required),`Wallet callback handling must enforce ${required}`);
assert.ok(source.includes('dispatchLock({type:"lock",reason:"restart"})'),"every repository reconstruction must relock before reading persisted state");
assert.ok(source.includes("setManifest(null)"),"repository reconstruction must discard stale in-memory account state");
assert.ok(source.includes("dismissAuthorizationReviews()"),"repository reconstruction must discard pending authorization reviews");
assert.ok(source.includes("unlockAccountFailClosed(reviewedAccount"),"Wallet unlock must use the exact-account fail-closed policy");
for(const required of ["await authorizeBiometric()","await verifyAccountSecret(reviewedAccount)","currentSelectedAccount()!==reviewedAccount","assertActive();"])assert.ok(unlockPolicy.includes(required),`unlock policy must enforce ${required}`);
for(const required of ["unlockEpochRef.current+=1","epoch!==unlockEpochRef.current",'appStateRef.current!=="active"',"Wallet unlock was cancelled by lock or background"])assert.ok(source.includes(required),`in-flight unlock must fail closed through ${required}`);
assert.ok(source.includes("unlockAttemptGate.current.tryBegin()"),"Wallet unlock must reject synchronous biometric attempt reentry before React busy state renders");
assert.ok(source.includes("createAttemptGate.current.tryBegin()"),"Wallet account secret generation must reject synchronous Create reentry");
for(const required of ["switchAttemptGate.current.tryBegin()",'busy={busy||switching}',"epoch!==unlockEpochRef.current",'appStateRef.current!=="active"',"Wallet account switch was cancelled by lock or background"])assert.ok(source.includes(required),`account switching must reject reentry and stale foreground persistence through ${required}`);
assert.ok(walletRepository.includes("selectAccount(account: string,assertActive:()=>void=()=>{})")&&walletRepository.includes("selectAccountExclusive(account,assertActive)"),"selected-account persistence must accept a final lifecycle assertion");
for(const required of ["generateRecoveryKeyFailClosed(()=>getRandomBytesAsync(32),assertActive)","Wallet recovery-key generation was cancelled by lock or background"])assert.ok(source.includes(required),`Wallet recovery-key generation must bind lifecycle through ${required}`);
for(const required of ['return Object.freeze({...saving,recoveryKey:"",backupConfirmation:""})','state.phase==="saving"','The recovery key has been removed from the form'])assert.ok(`${source}\n${onboardingState}`.includes(required),`onboarding must remove recovery material from React state while saving through ${required}`);
for(const required of ["bytes.length!==32","assertActive();","bytes.fill(0)"])assert.ok(recoveryKeyGenerationPolicy.includes(required),`temporary recovery-key entropy must fail closed through ${required}`);
for(const required of ["await protectScreen();","assertActive();"])assert.ok(recoveryDisplayPrivacyPolicy.includes(required),`new recovery-key display must fail closed through ${required}`);
for(const required of ['prepareRecoveryKeyDisplayFailClosed(()=>preventScreenCaptureAsync("wallet-recovery")',"const ready=protectedSecret===pending.secretHex","Recovery key remains hidden:"])assert.ok(source.includes(required),`new recovery key must remain hidden until dedicated screenshot protection through ${required}`);
for(const required of ["await protectScreen();","await authorizeBiometric();","const secret=await readSecret();","assertActive();","/^[0-9a-f]{64}$/"])assert.ok(recoveryRevealPolicy.includes(required),`recovery-key reveal must fail closed through ${required}`);
assert.ok(source.includes('revealRecoverySecretFailClosed(()=>preventScreenCaptureAsync("wallet-recovery-export"),()=>authorizeLocalKeyUse("recovery-view"),()=>repository.accountSecret(account.account),()=>sensitiveGuard.verify(attempt))'),"recovery-key reveal must confirm screenshot protection before biometric and SecureStore access");
assert.ok(source.includes("if(!await load()){gate.fail();foregroundGate.fail();return}"),"cold-start deep links must wait for successful secure repository reconstruction and close both gates on failure");
assert.ok(source.indexOf("await load()")<source.indexOf("await Linking.getInitialURL()"),"secure repository reconstruction must precede initial deep-link admission");
for(const required of ['phase:"restoring"|"ready"|"failed"','this.pending=null;this.ambiguous=true','if(pending!==null)this.handle(pending)'])assert.ok(startupDeepLinkPolicy.includes(required),`startup deep-link gate must enforce ${required}`);
assert.ok(lockState.includes("unlockedAccount: null"),"background/restart lock must clear the in-memory unlocked account");
assert.ok(lockState.includes('reason:"restart"'),"repository reconstruction must be an explicit lock action");
assert.ok(source.includes("switchAccountFailClosed(account"),"account selection must use the fail-closed relock policy");
assert.ok(lockState.includes('reason: "account-switch"'),"every account switch must clear authorization and require a fresh unlock");
assert.ok(source.includes("isSelectedAccountUnlocked(lockState,selected.account)"),"Dashboard access must bind authorization to the exact selected account");
assert.ok(clipboardPrivacy.includes("const DEFAULT_TTL_MS = 30_000"),"public clipboard values must default to a bounded 30-second lifetime");
assert.ok(clipboardPrivacy.includes('await clipboard.setStringAsync("")'),"clipboard expiry must clear only the still-matching value");
assert.ok(config.plugins.includes("./plugins/withYnxAndroidReleaseSigning"),"Wallet must preserve Release signing policy through Expo prebuild");
for(const required of ["ynxReleaseSigningConfigured ? signingConfigs.release : null","System.getenv(\"YNX_ANDROID_KEYSTORE_PATH\")","ynxDebugKeystorePath"])assert.equal(`${androidGradle}\n${signingPlugin}`.includes(required),true,`missing Android signing boundary ${required}`);
assert.equal(androidGradle.includes("            signingConfig signingConfigs.debug\n            def enableShrinkResources"),false,"Release must never inherit debug signing");
for(const required of ["mktemp -d /private/tmp/ynx-wallet-disposable-qa-custody","chmod 0700","openssl rand","YNX_ANDROID_KEYSTORE_PATH","apksigner verify --verbose --print-certs","APK Signature Scheme v2","disposable-qa-release-key","productionSigned:false","storeReleased:false"])assert.equal(androidQaBuild.includes(required),true,`missing disposable Android QA build boundary ${required}`);
for(const forbidden of ["androiddebugkey","storePassword 'android'","keyPassword 'android'"])assert.equal(androidQaBuild.includes(forbidden),false,`disposable Android QA build must not use ${forbidden}`);
for(const required of ["firstColdLaunch.pid!==receipt.secondColdLaunch.pid","fatalExceptionCount===0","androidRuntimeCrashCount===0","flagSecureObserved===true","evmChainIdHex===\"0x1917\"","receipt.rawEvidence.length>=6","productionSigned:false","storeReleased:false"])assert.equal(androidQaVerify.includes(required),true,`missing Android API 36 receipt boundary ${required}`);
for(const forbidden of ["Social Feed","Shop tab","Pay tab","Exchange tab"])assert.equal(source.includes(forbidden),false);
for(const required of ["Sign in with YNX Wallet","Requesting App","App identity","Permissions","Purpose","Valid until","Approve","Reject"])assert.equal(`${source}\n${i18n}`.includes(required),true,`missing ${required}`);
for(const required of ["parseExchangeOrderActionDeepLink","Review Exchange order","Review margin transfer","Review perpetual order","Review order cancellation","Approve and return to Exchange","No native withdrawal, reusable mandate or unlimited approval is included."])assert.equal(source.includes(required),true,`missing Exchange action boundary ${required}`);
for(const required of ["AI security explanation","authorizationAudit.ensure","approval-revoked"])assert.equal(`${source}\n${i18n}\n${audit}`.includes(required),true,`missing ${required}`);
for(const required of ["useColorScheme","isReduceMotionEnabled","isHighTextContrastEnabled","Text follows the device font scale"])assert.equal(source.includes(required),true,`missing adaptive UI contract ${required}`);
for(const required of ["WELCOME","Create a new Wallet","Import account","Recover Wallet","WALLET LOCKED","NATIVE ACCOUNT","Assets","Activity","Receive YNXT","Send Review","Connected Apps","Sessions","Devices","Recovery","Security","Authorization Audit","Network"])assert.equal(`${source}\n${i18n}`.toLowerCase().includes(required.toLowerCase()),true,`missing Wallet IA surface ${required}`);
for(const required of ["Smart Account & Capital","CAPITAL REVIEW","Sponsored gas","Yield source","Historical yield","Lock / cooldown","Slashing / drawdown","Withdrawal / reserve","Immediate exit"])assert.equal(`${source}\n${controlCopy}`.includes(required),true,`missing Wallet control surface ${required}`);
for(const required of ["withdrawal-queue","trading-subaccount","api-wallet","cross-chain-route","missingCapitalProducts","staleCapitalProducts"])assert.equal(controls.includes(required),true,`missing fail-closed capital control ${required}`);
for(const locale of ["en","zh-Hans","zh-Hant","ja","ko","es","fr","de","pt","ru","ar","id"])assert.equal(i18n.includes(`\"${locale}\"`)||i18n.includes(`${locale}:`),true,`missing locale ${locale}`);
assert.ok((source.match(/accessibilityLabel=/g)??[]).length>=14,"Wallet controls need explicit accessibility labels");
for(const file of ["RECOVERY.md","REFERENCE.md","PARITY.md","WEB4_IDENTITY.md","FEATURE_COMPLETION_EVIDENCE.md","CAPITAL_DESIGN.md","API_REGISTRY.md","MIGRATION_COMPATIBILITY.md","SLO_CAPACITY_PLAN.md","UNIT_ECONOMICS.md","OBSERVABILITY.md","THIRD_PARTY_NOTICES.md","PRODUCT_KPIS.md","public-product-metadata.json"])await access(new URL(`../${file}`,import.meta.url));
for(const file of ["../../../packages/wallet-auth/integration/gateway-integration.manifest.json","../../../packages/wallet-auth/integration/gateway-state.schema.json","../../../packages/wallet-auth/integration/smart-account-testnet.manifest.json","../../../packages/wallet-auth/integration/chain-erc4337-requirements.json","../../../packages/wallet-auth/integration/CHAIN_ERC4337_HANDOFF.md","../../../packages/wallet-auth/testdata/product-session-http-proof-v1.json","../proof/gateway-benchmark-local.json","../proof/smart-account-hardhat-local.json","../proof/sponsorship-bundler-hardhat-local.json","../proof/public-evm-read-probe-2026-07-22.json","../proof/wallet-control-surface-local.json","../proof/wallet-control-android-installed-2026-07-22.json","../proof/ynx-wallet-control-android-current.png"])await access(new URL(file,import.meta.url));
const release=JSON.parse(await readFile(new URL("../product-release.json",import.meta.url),"utf8"));
const gatewayProof=JSON.parse(await readFile(new URL("../proof/wallet-gateway-public-2026-08-11.json",import.meta.url),"utf8"));
assert.equal(release.integratedCentral,true);
assert.equal(release.deployedPublic,false,"native Wallet aggregate must remain false until a current public application release exists");
assert.equal(release.centralIntegration.registryProducts,34);
assert.equal(release.centralIntegration.registryEnabledProducts,27);
assert.equal(release.capabilityStates.canonicalGatewayAdapter.deployedPublic,true);
assert.equal(gatewayProof.deployment.sourceCommit,release.centralIntegration.deployedSourceCommit);
assert.equal(gatewayProof.deployment.release,release.centralIntegration.deployedRelease);
assert.equal(gatewayProof.registry.products,release.centralIntegration.registryProducts);
assert.equal(gatewayProof.registry.enabledProducts,release.centralIntegration.registryEnabledProducts);
assert.equal(gatewayProof.bridgeProductSessionE2E.postRevocationError,"REVOKED");
assert.equal(gatewayProof.claims.walletNativeApplicationDeployedPublic,false);
assert.equal(gatewayProof.secretMaterialRecorded,false);
const metadata=JSON.parse(await readFile(new URL("../public-product-metadata.json",import.meta.url),"utf8"));
assert.equal(metadata.productId,"wallet");
assert.equal(metadata.canonicalRoute,"/wallet");
assert.equal(metadata.releaseStatus,"testnet-engineering-preview");
console.log("wallet product-check passed: independent IDs, exact network/asset identity, bounded authorization and capital UI, audit/revocation, 12 locales, route isolation, and accessibility labels");
