import assert from "node:assert/strict";
import { access, readFile } from "node:fs/promises";

const config=JSON.parse(await readFile(new URL("../app.json",import.meta.url),"utf8")).expo;
const source=await readFile(new URL("../App.tsx",import.meta.url),"utf8");
const i18n=await readFile(new URL("../src/i18n/i18n.ts",import.meta.url),"utf8");
const audit=await readFile(new URL("../src/protocol/authorizationAudit.ts",import.meta.url),"utf8");
const actionReplayStore=await readFile(new URL("../src/protocol/actionReplayStore.ts",import.meta.url),"utf8");
const controls=await readFile(new URL("../src/control/controlSurface.ts",import.meta.url),"utf8");
const controlCopy=await readFile(new URL("../src/control/controlCopy.ts",import.meta.url),"utf8");
const androidGradle=await readFile(new URL("../android/app/build.gradle",import.meta.url),"utf8");
const androidActivity=await readFile(new URL("../android/app/src/main/java/com/ynxweb4/wallet/MainActivity.kt",import.meta.url),"utf8");
const androidManifest=await readFile(new URL("../android/app/src/main/AndroidManifest.xml",import.meta.url),"utf8");
const secureStorage=await readFile(new URL("../src/storage/secureStorage.ts",import.meta.url),"utf8");
const localAuthorization=await readFile(new URL("../src/security/localAuthorization.ts",import.meta.url),"utf8");
const localAuthorizationPolicy=await readFile(new URL("../src/security/localAuthorizationPolicy.ts",import.meta.url),"utf8");
const authorizationLifecyclePolicy=await readFile(new URL("../src/security/authorizationLifecyclePolicy.ts",import.meta.url),"utf8");
const foregroundDeepLinkPolicy=await readFile(new URL("../src/security/foregroundDeepLinkPolicy.ts",import.meta.url),"utf8");
const sensitiveOperationPolicy=await readFile(new URL("../src/security/sensitiveOperationPolicy.ts",import.meta.url),"utf8");
const startupDeepLinkPolicy=await readFile(new URL("../src/security/startupDeepLinkPolicy.ts",import.meta.url),"utf8");
const walletOpenLinkPolicy=await readFile(new URL("../src/security/walletOpenLinkPolicy.ts",import.meta.url),"utf8");
const unlockPolicy=await readFile(new URL("../src/security/unlockPolicy.ts",import.meta.url),"utf8");
const lockState=await readFile(new URL("../src/state/lockState.ts",import.meta.url),"utf8");
const clipboardPrivacy=await readFile(new URL("../src/security/clipboardPrivacy.ts",import.meta.url),"utf8");
const signingPlugin=await readFile(new URL("../plugins/withYnxAndroidReleaseSigning.js",import.meta.url),"utf8");
const androidQaBuild=await readFile(new URL("./build-disposable-android-qa-release.sh",import.meta.url),"utf8");
const androidQaVerify=await readFile(new URL("./verify-android-api36-qa-receipt.mjs",import.meta.url),"utf8");
const actionDeepLinkParsers=await Promise.all(["exchange-action.js","developer-deployment.js","dex-action.js","quant-action.js"].map((file)=>readFile(new URL(`../../../packages/wallet-auth/src/${file}`,import.meta.url),"utf8")));
const canonicalDeepLink=await readFile(new URL("../../../packages/wallet-auth/src/deep-link.js",import.meta.url),"utf8");
assert.equal(config.name,"YNX Wallet");
assert.equal(config.version,"1.0.1");
assert.equal(config.scheme,"ynxwallet");
assert.equal(config.android.package,"com.ynxweb4.wallet");
assert.equal(config.ios.bundleIdentifier,"com.ynxweb4.wallet");
assert.equal(config.extra.nativeChainId,"ynx_6423-1");
assert.equal(config.extra.evmChainId,6423);
assert.equal(config.extra.nativeAsset,"YNXT");
assert.equal(config.extra.internalAcceptanceShell,false);
assert.equal(config.userInterfaceStyle,"automatic");
assert.equal(config.android.intentFilters[0].data[0].host,"authorize");
assert.equal(config.android.intentFilters[0].data[1].host,"action");
assert.equal(config.android.intentFilters[0].data[2].host,"open");
assert.equal(source.includes("if(isExactWalletOpenLink(url))"),true,"Wallet must route the safe launcher through its byte-exact policy");
assert.equal(walletOpenLinkPolicy.includes('url==="ynxwallet://open"'),true,"Wallet must support only the exact safe launcher without treating ambiguous URL variants as open");
assert.ok(source.includes("assertDeepLinkForeground(appStateRef.current)"),"every runtime and startup deep link must require the exact active foreground");
assert.ok(source.includes("appStateRef.current=next"),"deep-link foreground admission must track AppState changes synchronously");
assert.ok(foregroundDeepLinkPolicy.includes('state!=="active"'),"background, inactive and unknown AppState must reject authorization links");
for(const required of ["!current.active","attempt.generation!==current.generation","attempt.binding!==current.binding"])assert.ok(sensitiveOperationPolicy.includes(required),`sensitive operation policy must enforce ${required}`);
for(const boundary of ["transaction-sign","recovery-view","account-import","account-delete"])assert.ok(source.includes(`authorizeLocalKeyUse("${boundary}")`),`Wallet must retain biometric purpose ${boundary}`);
assert.ok((source.match(/useSensitiveOperationGuard\(/g)??[]).length>=6,"send, recovery, onboarding, delete, revoke and the guard implementation must share lifecycle invalidation");
for(const required of ["repository.addAccount(onboardingAccountInput(saving,new Date().toISOString()),()=>sensitiveGuard.verify(attempt))","repository.deleteAccount(account.account,()=>sensitiveGuard.verify(attempt))","authorizationAudit.revoke(record.requestDigest,new Date().toISOString(),()=>sensitiveGuard.verify(attempt))","sensitiveGuard.verify(attempt);const result=await client.broadcast"])assert.ok(source.includes(required),`sensitive mutations must verify lifecycle at ${required}`);
assert.ok(androidActivity.includes("window.addFlags(WindowManager.LayoutParams.FLAG_SECURE)"),"Android native launch window must set FLAG_SECURE before React starts");
assert.ok(androidActivity.indexOf("window.addFlags(WindowManager.LayoutParams.FLAG_SECURE)")<androidActivity.indexOf("super.onCreate(null)"),"Android FLAG_SECURE must precede React/splash lifecycle startup");
for(const required of ['android:fullBackupContent="@xml/secure_store_backup_rules"','android:dataExtractionRules="@xml/secure_store_data_extraction_rules"'])assert.ok(androidManifest.includes(required),`Android manifest must bind SecureStore backup exclusion: ${required}`);
assert.ok(secureStorage.includes("WHEN_UNLOCKED_THIS_DEVICE_ONLY"),"Wallet secrets must use device-bound secure storage accessible only while unlocked");
for(const required of ["BIOMETRIC_STRONG","disableDeviceFallback: true",'biometricsSecurityLevel: "strong"'])assert.ok(`${localAuthorization}\n${localAuthorizationPolicy}`.includes(required),`local key authorization must require ${required}`);
assert.ok(source.includes('AppState.addEventListener("change"'),"Wallet must observe application background state");
assert.ok(source.includes('dispatchLock({type:"lock",reason:"background"})'),"Wallet must lock when leaving the active state");
for(const setter of ["setAuthorization(null)","setExchangeAction(null)","setDeveloperDeployment(null)","setDexAction(null)","setQuantAction(null)"])assert.ok(source.includes(setter),`background/link handling must clear ${setter}`);
for(const required of ["attempt.generation!==current.generation","attempt.account!==current.account","now.toISOString()>=expiresAt"])assert.ok(authorizationLifecyclePolicy.includes(required),`authorization lifecycle must fail closed on ${required}`);
assert.ok((source.match(/useAuthorizationAttemptGuard\(selected\.account,request\.expiresAt\)/g)??[]).length===5,"all five authorization/action Modals must use the lifecycle attempt guard");
assert.ok(source.includes("parseAuthorizationRequest(activeRequest,{now,registry:PRODUCT_REGISTRY})"),"canonical authorization must revalidate expiry after private-key access and before signing");
assert.equal((source.match(/await actionReplays\.consume\(/g)??[]).length,4,"all four signed action callbacks must persist exact-request replay state before returning");
assert.equal((source.match(/await actionReplays\.consume\([^;]+;guard\.verify\(attempt,new Date\(\)\);await Linking\.openURL/g)??[]).length,4,"action replay consumption and lifecycle validation must precede every callback handoff");
for(const required of ["MAX_ACTION_REPLAY_RECORDS=4096","MAX_ACTION_REPLAY_BYTES=512*1024","this.pending.then","records.some(([key])=>key===record.key)","await this.storage.setItem(ACTION_REPLAY_KEY"])assert.ok(actionReplayStore.includes(required),`action replay store must enforce ${required}`);
for(const parser of actionDeepLinkParsers)assert.ok(parser.includes("link is not canonical"),"every action deep-link parser must reject byte-noncanonical URLs after strict request parsing");
for(const required of ["callback.toString() !== response.callback","url !== `${expectedCallback}?response=${response}`","parsed.port","expected.port"])assert.ok(canonicalDeepLink.includes(required),`Wallet callback handling must enforce ${required}`);
assert.ok(source.includes('dispatchLock({type:"lock",reason:"restart"})'),"every repository reconstruction must relock before reading persisted state");
assert.ok(source.includes("setManifest(null)"),"repository reconstruction must discard stale in-memory account state");
assert.ok(source.includes("dismissAuthorizationReviews()"),"repository reconstruction must discard pending authorization reviews");
assert.ok(source.includes("unlockAccountFailClosed(reviewedAccount"),"Wallet unlock must use the exact-account fail-closed policy");
for(const required of ["await authorizeBiometric()","await verifyAccountSecret(reviewedAccount)","currentSelectedAccount()!==reviewedAccount"])assert.ok(unlockPolicy.includes(required),`unlock policy must enforce ${required}`);
assert.ok(source.includes("if(!await load()){gate.fail();return}"),"cold-start deep links must wait for successful secure repository reconstruction");
assert.ok(source.indexOf("await load()")<source.indexOf("await Linking.getInitialURL()"),"secure repository reconstruction must precede initial deep-link admission");
for(const required of ['phase:"restoring"|"ready"|"failed"','this.pending=null;this.ambiguous=true','if(pending!==null)this.handle(pending)'])assert.ok(startupDeepLinkPolicy.includes(required),`startup deep-link gate must enforce ${required}`);
assert.ok(lockState.includes("unlockedAccount: null"),"background/restart lock must clear the in-memory unlocked account");
assert.ok(lockState.includes('reason:"restart"'),"repository reconstruction must be an explicit lock action");
assert.ok(source.includes("switchAccountFailClosed(account"),"account selection must use the fail-closed relock policy");
assert.ok(lockState.includes('reason: "account-switch"'),"every account switch must clear authorization and require a fresh unlock");
assert.ok(source.includes("isSelectedAccountUnlocked(lockState,selected.account)"),"Dashboard access must bind authorization to the exact selected account");
assert.ok(clipboardPrivacy.includes("const DEFAULT_TTL_MS = 30_000"),"public clipboard values must default to a bounded 30-second lifetime");
assert.ok(clipboardPrivacy.includes('await clipboard.setStringAsync("")'),"clipboard expiry must clear only the still-matching value");
assert.ok(config.plugins.includes("./plugins/withYnxAndroidReleaseSigning"),"Wallet must preserve Release signing policy through Expo prebuild");
for(const required of ["ynxReleaseSigningConfigured ? signingConfigs.release : null","System.getenv(\"YNX_ANDROID_KEYSTORE_PATH\")","ynxDebugKeystorePath"])assert.equal(`${androidGradle}\n${signingPlugin}`.includes(required),true,`missing Android signing boundary ${required}`);
assert.equal(androidGradle.includes("            signingConfig signingConfigs.debug\n            def enableShrinkResources"),false,"Release must never inherit debug signing");
for(const required of ["mktemp -d /private/tmp/ynx-wallet-disposable-qa-custody","chmod 0700","openssl rand","YNX_ANDROID_KEYSTORE_PATH","apksigner verify --verbose --print-certs","APK Signature Scheme v2","disposable-qa-release-key","productionSigned:false","storeReleased:false"])assert.equal(androidQaBuild.includes(required),true,`missing disposable Android QA build boundary ${required}`);
for(const forbidden of ["androiddebugkey","storePassword 'android'","keyPassword 'android'"])assert.equal(androidQaBuild.includes(forbidden),false,`disposable Android QA build must not use ${forbidden}`);
for(const required of ["firstColdLaunch.pid!==receipt.secondColdLaunch.pid","fatalExceptionCount===0","androidRuntimeCrashCount===0","flagSecureObserved===true","evmChainIdHex===\"0x1917\"","receipt.rawEvidence.length>=6","productionSigned:false","storeReleased:false"])assert.equal(androidQaVerify.includes(required),true,`missing Android API 36 receipt boundary ${required}`);
for(const forbidden of ["Social Feed","Shop tab","Pay tab","Exchange tab"])assert.equal(source.includes(forbidden),false);
for(const required of ["Sign in with YNX Wallet","Requesting App","App identity","Permissions","Purpose","Valid until","Approve","Reject"])assert.equal(`${source}\n${i18n}`.includes(required),true,`missing ${required}`);
for(const required of ["parseExchangeOrderActionDeepLink","Review Exchange order","Review margin transfer","Review perpetual order","Review order cancellation","Approve and return to Exchange","No native withdrawal, reusable mandate or unlimited approval is included."])assert.equal(source.includes(required),true,`missing Exchange action boundary ${required}`);
for(const required of ["AI security explanation","authorizationAudit.append","approval-revoked"])assert.equal(`${source}\n${i18n}\n${audit}`.includes(required),true,`missing ${required}`);
for(const required of ["useColorScheme","isReduceMotionEnabled","isHighTextContrastEnabled","Text follows the device font scale"])assert.equal(source.includes(required),true,`missing adaptive UI contract ${required}`);
for(const required of ["WELCOME","Create a new Wallet","Import account","Recover Wallet","WALLET LOCKED","NATIVE ACCOUNT","Assets","Activity","Receive YNXT","Send Review","Connected Apps","Sessions","Devices","Recovery","Security","Authorization Audit","Network"])assert.equal(`${source}\n${i18n}`.toLowerCase().includes(required.toLowerCase()),true,`missing Wallet IA surface ${required}`);
for(const required of ["Smart Account & Capital","CAPITAL REVIEW","Sponsored gas","Yield source","Historical yield","Lock / cooldown","Slashing / drawdown","Withdrawal / reserve","Immediate exit"])assert.equal(`${source}\n${controlCopy}`.includes(required),true,`missing Wallet control surface ${required}`);
for(const required of ["withdrawal-queue","trading-subaccount","api-wallet","cross-chain-route","missingCapitalProducts","staleCapitalProducts"])assert.equal(controls.includes(required),true,`missing fail-closed capital control ${required}`);
for(const locale of ["en","zh-Hans","zh-Hant","ja","ko","es","fr","de","pt","ru","ar","id"])assert.equal(i18n.includes(`\"${locale}\"`)||i18n.includes(`${locale}:`),true,`missing locale ${locale}`);
assert.ok((source.match(/accessibilityLabel=/g)??[]).length>=14,"Wallet controls need explicit accessibility labels");
for(const file of ["RECOVERY.md","REFERENCE.md","PARITY.md","WEB4_IDENTITY.md","FEATURE_COMPLETION_EVIDENCE.md","CAPITAL_DESIGN.md","API_REGISTRY.md","MIGRATION_COMPATIBILITY.md","SLO_CAPACITY_PLAN.md","UNIT_ECONOMICS.md","OBSERVABILITY.md","THIRD_PARTY_NOTICES.md","PRODUCT_KPIS.md","public-product-metadata.json"])await access(new URL(`../${file}`,import.meta.url));
for(const file of ["../../../packages/wallet-auth/integration/gateway-integration.manifest.json","../../../packages/wallet-auth/integration/gateway-state.schema.json","../../../packages/wallet-auth/integration/smart-account-testnet.manifest.json","../../../packages/wallet-auth/integration/chain-erc4337-requirements.json","../../../packages/wallet-auth/integration/CHAIN_ERC4337_HANDOFF.md","../../../packages/wallet-auth/testdata/product-session-http-proof-v1.json","../proof/gateway-benchmark-local.json","../proof/smart-account-hardhat-local.json","../proof/sponsorship-bundler-hardhat-local.json","../proof/public-evm-read-probe-2026-07-22.json","../proof/wallet-control-surface-local.json","../proof/wallet-control-android-installed-2026-07-22.json","../proof/ynx-wallet-control-android-current.png"])await access(new URL(file,import.meta.url));
const release=JSON.parse(await readFile(new URL("../product-release.json",import.meta.url),"utf8"));
const gatewayProof=JSON.parse(await readFile(new URL("../proof/wallet-gateway-public-2026-08-11.json",import.meta.url),"utf8"));
assert.equal(release.integratedCentral,true);
assert.equal(release.deployedPublic,false,"native Wallet aggregate must remain false until a current public application release exists");
assert.equal(release.centralIntegration.registryProducts,34);
assert.equal(release.centralIntegration.registryEnabledProducts,27);
assert.equal(release.capabilityStates.canonicalGatewayAdapter.deployedPublic,true);
assert.equal(gatewayProof.deployment.sourceCommit,release.centralIntegration.deployedSourceCommit);
assert.equal(gatewayProof.deployment.release,release.centralIntegration.deployedRelease);
assert.equal(gatewayProof.registry.products,release.centralIntegration.registryProducts);
assert.equal(gatewayProof.registry.enabledProducts,release.centralIntegration.registryEnabledProducts);
assert.equal(gatewayProof.bridgeProductSessionE2E.postRevocationError,"REVOKED");
assert.equal(gatewayProof.claims.walletNativeApplicationDeployedPublic,false);
assert.equal(gatewayProof.secretMaterialRecorded,false);
const metadata=JSON.parse(await readFile(new URL("../public-product-metadata.json",import.meta.url),"utf8"));
assert.equal(metadata.productId,"wallet");
assert.equal(metadata.canonicalRoute,"/wallet");
assert.equal(metadata.releaseStatus,"testnet-engineering-preview");
console.log("wallet product-check passed: independent IDs, exact network/asset identity, bounded authorization and capital UI, audit/revocation, 12 locales, route isolation, and accessibility labels");
