import assert from "node:assert/strict";
import { access, readFile } from "node:fs/promises";

const config=JSON.parse(await readFile(new URL("../app.json",import.meta.url),"utf8")).expo;
const source=await readFile(new URL("../App.tsx",import.meta.url),"utf8");
const i18n=await readFile(new URL("../src/i18n/i18n.ts",import.meta.url),"utf8");
const audit=await readFile(new URL("../src/protocol/authorizationAudit.ts",import.meta.url),"utf8");
const controls=await readFile(new URL("../src/control/controlSurface.ts",import.meta.url),"utf8");
const controlCopy=await readFile(new URL("../src/control/controlCopy.ts",import.meta.url),"utf8");
const mandateReview=await readFile(new URL("../src/strategy/strategyMandateReview.ts",import.meta.url),"utf8");
const androidGradle=await readFile(new URL("../android/app/build.gradle",import.meta.url),"utf8");
const androidActivity=await readFile(new URL("../android/app/src/main/java/com/ynxweb4/wallet/MainActivity.kt",import.meta.url),"utf8");
const androidManifest=await readFile(new URL("../android/app/src/main/AndroidManifest.xml",import.meta.url),"utf8");
const secureStorage=await readFile(new URL("../src/storage/secureStorage.ts",import.meta.url),"utf8");
const localAuthorization=await readFile(new URL("../src/security/localAuthorization.ts",import.meta.url),"utf8");
const lockState=await readFile(new URL("../src/state/lockState.ts",import.meta.url),"utf8");
const clipboardPrivacy=await readFile(new URL("../src/security/clipboardPrivacy.ts",import.meta.url),"utf8");
const signingPlugin=await readFile(new URL("../plugins/withYnxAndroidReleaseSigning.js",import.meta.url),"utf8");
const androidQaBuild=await readFile(new URL("./build-disposable-android-qa-release.sh",import.meta.url),"utf8");
const androidQaVerify=await readFile(new URL("./verify-android-api36-qa-receipt.mjs",import.meta.url),"utf8");
assert.equal(config.name,"YNX Wallet");
assert.equal(config.version,"1.0.1");
assert.equal(config.scheme,"ynxwallet");
assert.equal(config.android.package,"com.ynxweb4.wallet");
assert.equal(config.ios.bundleIdentifier,"com.ynxweb4.wallet");
assert.equal(config.extra.nativeChainId,"ynx_6423-1");
assert.equal(config.extra.evmChainId,6423);
assert.equal(config.extra.nativeAsset,"YNXT");
assert.equal(config.extra.internalAcceptanceShell,false);
assert.equal(config.userInterfaceStyle,"automatic");
assert.equal(config.android.intentFilters[0].data[0].host,"authorize");
assert.equal(config.android.intentFilters[0].data[1].host,"action");
assert.equal(config.android.intentFilters[0].data[2].host,"open");
assert.equal(source.includes('parsedURL.hostname==="open"'),true,"Wallet must support the safe ynxwallet://open launcher without treating it as an authorization request");
assert.ok(androidActivity.includes("window.addFlags(WindowManager.LayoutParams.FLAG_SECURE)"),"Android native launch window must set FLAG_SECURE before React starts");
assert.ok(androidActivity.indexOf("window.addFlags(WindowManager.LayoutParams.FLAG_SECURE)")<androidActivity.indexOf("super.onCreate(null)"),"Android FLAG_SECURE must precede React/splash lifecycle startup");
for(const required of ['android:fullBackupContent="@xml/secure_store_backup_rules"','android:dataExtractionRules="@xml/secure_store_data_extraction_rules"'])assert.ok(androidManifest.includes(required),`Android manifest must bind SecureStore backup exclusion: ${required}`);
assert.ok(secureStorage.includes("WHEN_UNLOCKED_THIS_DEVICE_ONLY"),"Wallet secrets must use device-bound secure storage accessible only while unlocked");
for(const required of ["BIOMETRIC_STRONG","disableDeviceFallback: true",'biometricsSecurityLevel: "strong"'])assert.ok(localAuthorization.includes(required),`local key authorization must require ${required}`);
assert.ok(source.includes('AppState.addEventListener("change"'),"Wallet must observe application background state");
assert.ok(source.includes('dispatchLock({type:"lock",reason:"background"})'),"Wallet must lock when leaving the active state");
assert.ok(lockState.includes("unlockedAccount: null"),"background/restart lock must clear the in-memory unlocked account");
assert.ok(clipboardPrivacy.includes("const DEFAULT_TTL_MS = 30_000"),"public clipboard values must default to a bounded 30-second lifetime");
assert.ok(clipboardPrivacy.includes('await clipboard.setStringAsync("")'),"clipboard expiry must clear only the still-matching value");
assert.ok(config.plugins.includes("./plugins/withYnxAndroidReleaseSigning"),"Wallet must preserve Release signing policy through Expo prebuild");
for(const required of ["ynxReleaseSigningConfigured ? signingConfigs.release : null","System.getenv(\"YNX_ANDROID_KEYSTORE_PATH\")","ynxDebugKeystorePath"])assert.equal(`${androidGradle}\n${signingPlugin}`.includes(required),true,`missing Android signing boundary ${required}`);
assert.equal(androidGradle.includes("            signingConfig signingConfigs.debug\n            def enableShrinkResources"),false,"Release must never inherit debug signing");
for(const required of ["mktemp -d /private/tmp/ynx-wallet-disposable-qa-custody","chmod 0700","openssl rand","YNX_ANDROID_KEYSTORE_PATH","apksigner verify --verbose --print-certs","APK Signature Scheme v2","disposable-qa-release-key","productionSigned:false","storeReleased:false"])assert.equal(androidQaBuild.includes(required),true,`missing disposable Android QA build boundary ${required}`);
for(const forbidden of ["androiddebugkey","storePassword 'android'","keyPassword 'android'"])assert.equal(androidQaBuild.includes(forbidden),false,`disposable Android QA build must not use ${forbidden}`);
for(const required of ["firstColdLaunch.pid!==receipt.secondColdLaunch.pid","fatalExceptionCount===0","androidRuntimeCrashCount===0","flagSecureObserved===true","evmChainIdHex===\"0x1917\"","receipt.rawEvidence.length>=6","productionSigned:false","storeReleased:false"])assert.equal(androidQaVerify.includes(required),true,`missing Android API 36 receipt boundary ${required}`);
for(const forbidden of ["Social Feed","Shop tab","Pay tab","Exchange tab"])assert.equal(source.includes(forbidden),false);
for(const required of ["Sign in with YNX Wallet","Requesting App","App identity","Permissions","Purpose","Valid until","Approve","Reject"])assert.equal(`${source}\n${i18n}`.includes(required),true,`missing ${required}`);
for(const required of ["parseExchangeOrderActionDeepLink","Review Exchange order","Review margin transfer","Review perpetual order","Review order cancellation","Approve and return to Exchange","No native withdrawal, reusable mandate or unlimited approval is included."])assert.equal(source.includes(required),true,`missing Exchange action boundary ${required}`);
for(const required of ["AI security explanation","authorizationAudit.append","approval-revoked"])assert.equal(`${source}\n${i18n}\n${audit}`.includes(required),true,`missing ${required}`);
for(const required of ["useColorScheme","isReduceMotionEnabled","isHighTextContrastEnabled","Text follows the device font scale"])assert.equal(source.includes(required),true,`missing adaptive UI contract ${required}`);
for(const required of ["WELCOME","Create a new Wallet","Import account","Recover Wallet","WALLET LOCKED","NATIVE ACCOUNT","Assets","Activity","Receive YNXT","Send Review","Connected Apps","Sessions","Devices","Recovery","Security","Authorization Audit","Network"])assert.equal(`${source}\n${i18n}`.toLowerCase().includes(required.toLowerCase()),true,`missing Wallet IA surface ${required}`);
for(const required of ["Smart Account & Capital","CAPITAL REVIEW","Sponsored gas","Yield source","Historical yield","Lock / cooldown","Slashing / drawdown","Withdrawal / reserve","Immediate exit"])assert.equal(`${source}\n${controlCopy}`.includes(required),true,`missing Wallet control surface ${required}`);
for(const required of ["withdrawal-queue","trading-subaccount","api-wallet","cross-chain-route","missingCapitalProducts","staleCapitalProducts"])assert.equal(controls.includes(required),true,`missing fail-closed capital control ${required}`);
for(const required of ["Identity and source","Strategy and engine","Exact execution scope","Capital and risk limits","Asset authority boundaries","Explicit fees","Immediate safety controls","Profit, loss and Testnet truth","Exchange subaccount","No-withdraw API Wallet","DEX Strategy Vault","Typed Vault / Pool / Router targets","No transfer / owner / unlimited approval","Real profit and loss","Net assets","High-water mark","Loss carry-forward","YNX Testnet assets have no real-world value"])assert.equal(`${source}\n${mandateReview}`.includes(required),true,`missing Strategy Mandate Review disclosure ${required}`);
for(const required of ["parseStrategyMandate","rejectAlwaysAvailable: true","canApprove: acknowledgements.risk === true && acknowledgements.fees === true","providerRequest: false","callback: false","signing: false","accountAccess: false","network: false"])assert.equal(mandateReview.includes(required),true,`missing fail-closed Strategy Mandate Review boundary ${required}`);
for(const required of ["Strategy Mandate Review","Reject mandate","Approve bounded mandate","Reject is always available"])assert.equal(source.includes(required),true,`missing Strategy Mandate Review UI ${required}`);
for(const forbidden of ["eth_requestAccounts","provider.request","Linking.openURL","signAuthorization","fetch(","XMLHttpRequest"])assert.equal(mandateReview.includes(forbidden),false,`Strategy Mandate Review view model must not invoke ${forbidden}`);
for(const locale of ["en","zh-Hans","zh-Hant","ja","ko","es","fr","de","pt","ru","ar","id"])assert.equal(i18n.includes(`\"${locale}\"`)||i18n.includes(`${locale}:`),true,`missing locale ${locale}`);
assert.ok((source.match(/accessibilityLabel=/g)??[]).length>=14,"Wallet controls need explicit accessibility labels");
for(const file of ["RECOVERY.md","REFERENCE.md","PARITY.md","WEB4_IDENTITY.md","FEATURE_COMPLETION_EVIDENCE.md","CAPITAL_DESIGN.md","API_REGISTRY.md","MIGRATION_COMPATIBILITY.md","SLO_CAPACITY_PLAN.md","UNIT_ECONOMICS.md","OBSERVABILITY.md","THIRD_PARTY_NOTICES.md","PRODUCT_KPIS.md","public-product-metadata.json"])await access(new URL(`../${file}`,import.meta.url));
for(const file of ["../../../packages/wallet-auth/integration/gateway-integration.manifest.json","../../../packages/wallet-auth/integration/gateway-state.schema.json","../../../packages/wallet-auth/integration/smart-account-testnet.manifest.json","../../../packages/wallet-auth/integration/chain-erc4337-requirements.json","../../../packages/wallet-auth/integration/CHAIN_ERC4337_HANDOFF.md","../../../packages/wallet-auth/testdata/product-session-http-proof-v1.json","../proof/gateway-benchmark-local.json","../proof/smart-account-hardhat-local.json","../proof/sponsorship-bundler-hardhat-local.json","../proof/public-evm-read-probe-2026-07-22.json","../proof/wallet-control-surface-local.json","../proof/wallet-control-android-installed-2026-07-22.json","../proof/ynx-wallet-control-android-current.png"])await access(new URL(file,import.meta.url));
const release=JSON.parse(await readFile(new URL("../product-release.json",import.meta.url),"utf8"));
const gatewayProof=JSON.parse(await readFile(new URL("../proof/wallet-gateway-public-2026-08-11.json",import.meta.url),"utf8"));
assert.equal(release.integratedCentral,true);
assert.equal(release.deployedPublic,false,"native Wallet aggregate must remain false until a current public application release exists");
assert.equal(release.centralIntegration.registryProducts,34);
assert.equal(release.centralIntegration.registryEnabledProducts,27);
assert.equal(release.capabilityStates.canonicalGatewayAdapter.deployedPublic,true);
assert.equal(gatewayProof.deployment.sourceCommit,release.centralIntegration.deployedSourceCommit);
assert.equal(gatewayProof.deployment.release,release.centralIntegration.deployedRelease);
assert.equal(gatewayProof.registry.products,release.centralIntegration.registryProducts);
assert.equal(gatewayProof.registry.enabledProducts,release.centralIntegration.registryEnabledProducts);
assert.equal(gatewayProof.bridgeProductSessionE2E.postRevocationError,"REVOKED");
assert.equal(gatewayProof.claims.walletNativeApplicationDeployedPublic,false);
assert.equal(gatewayProof.secretMaterialRecorded,false);
const metadata=JSON.parse(await readFile(new URL("../public-product-metadata.json",import.meta.url),"utf8"));
assert.equal(metadata.productId,"wallet");
assert.equal(metadata.canonicalRoute,"/wallet");
assert.equal(metadata.releaseStatus,"testnet-engineering-preview");
console.log("wallet product-check passed: independent IDs, exact network/asset identity, bounded authorization and capital UI, audit/revocation, 12 locales, route isolation, and accessibility labels");
