import type { CardSession } from "./wallet";

const GATEWAY=(process.env.EXPO_PUBLIC_YNX_CARD_GATEWAY_URL??"").replace(/\/$/,"");

export type Eligibility=Readonly<{reference:string;status:"eligible_sandbox"|"pending_review"|"rejected"|"provider_unavailable";provider:string;updatedAt:string}>;
export type Controls=Readonly<{spendLimitMinor:number;currency:string;online:boolean;international:boolean;atm:boolean;allowedMcc:readonly string[];blockedMcc:readonly string[];allowedCountries:readonly string[]}>;
export type Card=Readonly<{id:string;account:string;applicationId:string;providerCardId:string;provider:string;network:"YNX Testnet Sandbox";last4:string;expiryMonth:number;expiryYear:number;status:"issued_sandbox"|"active"|"frozen"|"closed";replacementFor?:string;controls:Controls;createdAt:string;updatedAt:string}>;
export type CardEvent=Readonly<{id:string;cardId:string;type:"authorization"|"reversal"|"clearing"|"decline"|"refund";amountMinor:number;currency:string;merchant:string;reasonCode?:string;occurredAt:string;idempotencyKey?:string;source?:"provider"|"simulation";chainEvidence?:TopupEvidence}>;
export type Application=Readonly<{id:string;eligibilityReference:string;status:"requested"|"pending_review"|"issued_sandbox"|"rejected"|"provider_unavailable";provider:string;createdAt:string;updatedAt:string}>;
export type Notification=Readonly<{id:string;eventId:string;type:string;title:string;body:string;createdAt:string}>;
export type AIRun=Readonly<{id:string;workflow:string;contextEventId:string;outputLanguage:string;provider?:string;model?:string;status:"running"|"provider_unavailable"|"provider_failed"|"review"|"reviewed";draft?:string;decision?:"apply"|"reject";costUnits?:number;createdAt:string;updatedAt:string}>;
export type SimulationAuditEntry=Readonly<{id:string;kind:"topup"|"authorization"|"capture"|"reversal"|"refund";cardId:string;merchant:string;amountMinor:number;currency:string;idempotencyKey:string;status:"accepted"|"failed"|"duplicate"|"recovered";reason:string;txHash?:string;chainId?:string;createdAt:string;updatedAt:string}>;
export type CardState=Readonly<{eligibility?:Eligibility;applications:readonly Application[];cards:readonly Card[];events:readonly CardEvent[];disputes:readonly unknown[];notifications:readonly Notification[];aiRuns:readonly AIRun[];audit:readonly unknown[];simulations:readonly SimulationAuditEntry[]}>;
export type TopupEvidence=Readonly<{chainId:string;txHash:string;blockNumber:string;blockHash:string;from:string;to:string}>;
export type TopupInput=Readonly<{txHash:string;idempotencyKey:string}>;
export type SimulationInput=Readonly<{operation:"authorization"|"capture"|"reversal"|"refund";cardId:string;merchant:string;amountMinor:number;currency:string;idempotencyKey:string;walletAddress?:string;topupTxHash?:string}>;

export async function state(session:CardSession,signal?:AbortSignal):Promise<CardState>{return parseState(await request("/app/card/v1/account/state",session,{signal}))}
export async function apply(session:CardSession,input:{eligibilityReference:string;legalConsentVersion:"card-testnet-v1";idempotencyKey:string}):Promise<Application>{return await request("/app/card/v1/card/applications",session,{method:"POST",body:input}) as Application}
export async function action(session:CardSession,cardId:string,kind:"activate"|"freeze"|"unfreeze"|"close"|"replace",idempotencyKey:string):Promise<Card>{return parseCard(await request(`/app/card/v1/cards/${encodeURIComponent(cardId)}/actions`,session,{method:"POST",body:{action:kind,idempotencyKey}}))}
export async function updateControls(session:CardSession,cardId:string,input:Controls&{idempotencyKey:string}):Promise<Card>{return parseCard(await request(`/app/card/v1/cards/${encodeURIComponent(cardId)}/controls`,session,{method:"PUT",body:input}))}
export async function dispute(session:CardSession,cardId:string,input:{eventId:string;reason:string;idempotencyKey:string}):Promise<unknown>{return request(`/app/card/v1/cards/${encodeURIComponent(cardId)}/disputes`,session,{method:"POST",body:input})}
export async function explain(session:CardSession,input:{workflow:"card_decline_explanation"|"card_fee_explanation"|"card_support_draft";contextEventId:string;outputLanguage:string;permission:"allow_once"}):Promise<unknown>{return request("/app/card/v1/ai/runs",session,{method:"POST",body:input})}
export async function reviewAI(session:CardSession,id:string,decision:"apply"|"reject"):Promise<AIRun>{return request(`/app/card/v1/ai/runs/${encodeURIComponent(id)}/review`,session,{method:"POST",body:{decision}}) as Promise<AIRun>}
export async function topupTestnet(session:CardSession,input:TopupInput):Promise<TopupEvidence>{return parseTopupEvidence(await request("/app/card/v1/testnet/topups",session,{method:"POST",body:input}))}
export async function simulateAuthorization(session:CardSession,input:SimulationInput):Promise<CardEvent>{if(input.operation!=="authorization")throw new Error("Operation must be authorization");return parseEvent(await request(`/app/card/v1/cards/${encodeURIComponent(input.cardId)}/simulation/events`,session,{method:"POST",body:{...input,type:"authorization"}}))}
export async function simulateCapture(session:CardSession,input:SimulationInput):Promise<CardEvent>{if(input.operation!=="capture")throw new Error("Operation must be capture");return parseEvent(await request(`/app/card/v1/cards/${encodeURIComponent(input.cardId)}/simulation/events`,session,{method:"POST",body:{...input,type:"clearing"}}))}
export async function simulateReversal(session:CardSession,input:SimulationInput):Promise<CardEvent>{if(input.operation!=="reversal")throw new Error("Operation must be reversal");return parseEvent(await request(`/app/card/v1/cards/${encodeURIComponent(input.cardId)}/simulation/events`,session,{method:"POST",body:{...input,type:"reversal"}}))}
export async function simulateRefund(session:CardSession,input:SimulationInput):Promise<CardEvent>{if(input.operation!=="refund")throw new Error("Operation must be refund");return parseEvent(await request(`/app/card/v1/cards/${encodeURIComponent(input.cardId)}/simulation/events`,session,{method:"POST",body:{...input,type:"refund"}}))}

async function request(path:string,session:CardSession,options:{method?:string;body?:unknown;signal?:AbortSignal}={}):Promise<unknown>{if(!GATEWAY)throw new Error("YNX Card central Gateway is not configured");const controller=new AbortController(),abort=()=>controller.abort();if(options.signal?.aborted)controller.abort();else options.signal?.addEventListener("abort",abort,{once:true});const timer=setTimeout(abort,10_000);try{const response=await fetch(GATEWAY+path,{method:options.method??"GET",body:options.body===undefined?undefined:JSON.stringify(options.body),signal:controller.signal,headers:{Accept:"application/json",...(options.body===undefined?{}:{"Content-Type":"application/json"}),"X-YNX-Client":"ynx-card-v1","X-YNX-App-Session":session.token,"X-YNX-Device-ID":session.deviceId}});const value=await response.json().catch(()=>({error:"Invalid Card service response"}));if(!response.ok)throw new Error(object(value)&&typeof value.error==="string"?value.error:`YNX Card returned ${response.status}`);rejectSensitive(value);return value}finally{clearTimeout(timer);options.signal?.removeEventListener("abort",abort)}}

export function parseState(value:unknown):CardState{rejectSensitive(value);if(!object(value)||!Array.isArray(value.applications)||!Array.isArray(value.cards)||!Array.isArray(value.events)||!Array.isArray(value.disputes)||!Array.isArray(value.notifications)||!Array.isArray(value.aiRuns)||!Array.isArray(value.audit))throw new Error("Invalid Card account state");return Object.freeze({...value,cards:Object.freeze(value.cards.map(parseCard)),events:Object.freeze(value.events.map(parseEvent)),simulations:Object.freeze(Array.isArray((value as {simulations?:unknown}).simulations)?(value as {simulations:unknown[]}).simulations.map(parseSimulationAudit):[] as unknown[])}) as CardState}

function parseCard(value:unknown):Card{if(!object(value)||typeof value.id!=="string"||typeof value.account!=="string"||typeof value.providerCardId!=="string"||value.network!=="YNX Testnet Sandbox"||typeof value.last4!=="string"||!/^[0-9]{4}$/.test(value.last4)||!object(value.controls)||![("issued_sandbox"),("active"),("frozen"),("closed")].includes(String(value.status)))throw new Error("Invalid safe Card reference");return Object.freeze(value) as Card}

function parseEvent(value:unknown):CardEvent{if(!object(value)||typeof value.id!=="string"||typeof value.cardId!=="string"||!["authorization","reversal","clearing","decline","refund"].includes(String(value.type))||typeof value.amountMinor!=="number"||typeof value.currency!=="string"||typeof value.merchant!=="string")throw new Error("Invalid Card activity");return Object.freeze(value) as CardEvent}
function parseTopupEvidence(value:unknown):TopupEvidence{if(!object(value)||typeof value.txHash!=="string"||typeof value.chainId!=="string"||typeof value.blockNumber!=="string"||typeof value.blockHash!=="string"||typeof value.from!=="string"||typeof value.to!=="string")throw new Error("Invalid topup evidence");return Object.freeze(value) as TopupEvidence}
function parseSimulationAudit(value:unknown):SimulationAuditEntry{if(!object(value)||typeof value.id!=="string"||typeof value.kind!=="string"||typeof value.cardId!=="string"||typeof value.merchant!=="string"||typeof value.amountMinor!=="number"||typeof value.currency!=="string"||typeof value.idempotencyKey!=="string"||typeof value.status!=="string"||typeof value.reason!=="string"||typeof value.createdAt!=="string"||typeof value.updatedAt!=="string")throw new Error("Invalid simulation audit");return Object.freeze(value) as SimulationAuditEntry}
function rejectSensitive(value:unknown,path="response"){if(Array.isArray(value)){value.forEach((item,index)=>rejectSensitive(item,`${path}[${index}]`));return}if(!object(value))return;for(const[key,child]of Object.entries(value)){if(/^(pan|cvv|cvc|pin|track(data|1|2)?|magneticStripe|fullCardNumber|identityDocument|passportImage)$/i.test(key))throw new Error(`Sensitive issuer data rejected at ${path}`);rejectSensitive(child,`${path}.${key}`)}}
function object(value:unknown):value is Record<string,unknown>{return typeof value==="object"&&value!==null&&!Array.isArray(value)}
