import {createCoreCardCreationConsumer} from './coreCardCreation';
import type {CoreCreationJournal} from './providerApprovalJournal';
import React,{useEffect,useRef,useState} from 'react';
import {Platform,Pressable,StyleSheet,Switch,View} from 'react-native';
import * as SecureStore from 'expo-secure-store';
import {createCardApplicationApprovalRequest,type CardApplicationApprovalRequest} from '@ynx-chain/wallet-auth-card-provider-v2';
import registry from '../vendor/product-session-registry-b754ffc42.json';
import {CardText as Text,CardTextInput as TextInput} from './cardTypography';
import type {Locale} from './i18n';
import {CardBusinessClient,type CardApplicationView,type CardPrivateIdentity} from './cardBusinessClient';
import {createHostedCardApprovalConsumer,type HostedCardApprovalTransport} from './hostedCardApproval';

type CoreCopy=readonly [string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string];
const copy:Record<Locale,CoreCopy>={
  en:['Apply for a Testnet card','Private sandbox application. No bank card, PAN, CVV, fiat or real payment. Wallet review never submits card creation automatically.','Card nickname','Intended use','YNXT test spending limit (whole tokens)','I accept card-testnet-v1 terms and Testnet risks','Create application','Prepare approval challenge','Review in YNX Wallet','Submit approved application','Refresh applications','Cancel application','No application yet.','Request could not be confirmed. Refresh before retrying.','Saved Wallet review','Approve this exact application in Wallet, then submit separately.',"Creation result is unknown. Keep this original request; refresh records before retrying.","Retry the exact saved request","New application (keep previous request)","Original request"],
  'zh-CN':['申请测试网卡','私有沙箱申请，不是银行卡，不涉及 PAN、CVV、法币或真实支付。钱包审批不会自动提交开卡。','卡片名称','用途','YNXT 测试消费限额（整数代币）','我接受 card-testnet-v1 条款及测试网风险','创建申请','准备审批挑战','在 YNX 钱包中审批','提交已批准申请','刷新申请','取消申请','尚无申请。','无法确认结果，请刷新后再决定是否重试。','已保存的钱包审批','先在钱包中批准此精确申请，再单独提交。',"创建结果未知。请保留原请求，重试前先刷新记录。","重试已保存的同一请求","新申请（保留原请求）","原请求"],
  'zh-TW':['申請測試網卡','私人沙箱申請，不是銀行卡，不涉及 PAN、CVV、法幣或真實支付。錢包審批不會自動提交開卡。','卡片名稱','用途','YNXT 測試消費限額（整數代幣）','我接受 card-testnet-v1 條款及測試網風險','建立申請','準備審批挑戰','在 YNX 錢包中審批','提交已批准申請','重新整理申請','取消申請','尚無申請。','無法確認結果，請重新整理後再決定是否重試。','已儲存的錢包審批','先在錢包中批准此精確申請，再單獨提交。',"建立結果未知。請保留原請求，重試前先重新整理記錄。","重試已儲存的同一請求","新申請（保留原請求）","原請求"],
  ja:['テストネットカード申請','非公開の試験申請。銀行カード、PAN、CVV、法定通貨、実決済ではありません。承認で自動発行されません。','カード名','用途','YNXT 試験上限（整数）','card-testnet-v1 規約と試験リスクに同意','申請作成','承認チャレンジ準備','YNX Wallet で確認','承認済み申請を送信','申請を更新','申請取消','申請はありません。','結果不明。再試行前に更新してください。','保存済み承認','正確な申請を承認し、別途送信してください。',"作成結果不明。元の要求を保持し、再試行前に更新してください。","保存済みの同じ要求を再試行","新規申請（元の要求を保持）","元の要求"],
  ko:['테스트넷 카드 신청','비공개 시험 신청입니다. 은행 카드, PAN, CVV, 법정화폐 또는 실제 결제가 아닙니다. 승인으로 자동 발급되지 않습니다.','카드 이름','용도','YNXT 시험 한도 (정수)','card-testnet-v1 약관과 시험 위험에 동의','신청 만들기','승인 챌린지 준비','YNX Wallet에서 검토','승인된 신청 제출','신청 새로 고침','신청 취소','신청이 없습니다.','결과를 확인할 수 없습니다. 재시도 전에 새로 고치세요.','저장된 승인','정확한 신청을 승인한 후 별도로 제출하세요.',"생성 결과를 알 수 없습니다. 원래 요청을 보관하고 재시도 전에 새로 고치세요.","저장된 동일 요청 재시도","새 신청 (원래 요청 유지)","원래 요청"],
  es:['Solicitar tarjeta Testnet','Solicitud privada de prueba. Sin tarjeta bancaria, PAN, CVV, dinero fiduciario ni pago real. La aprobación no crea una tarjeta automáticamente.','Nombre de tarjeta','Uso previsto','Límite YNXT de prueba (entero)','Acepto card-testnet-v1 y los riesgos Testnet','Crear solicitud','Preparar desafío','Revisar en YNX Wallet','Enviar solicitud aprobada','Actualizar solicitudes','Cancelar solicitud','Sin solicitudes.','Resultado incierto. Actualiza antes de reintentar.','Revisión guardada','Aprueba esta solicitud exacta y envíala por separado.',"Resultado de creación incierto. Conserva la solicitud y actualiza antes de reintentar.","Reintentar la solicitud exacta","Nueva solicitud (conservar anterior)","Solicitud original"],
  fr:['Demander une carte Testnet','Demande privée de test. Ni carte bancaire, PAN, CVV, monnaie fiduciaire ni paiement réel. L’accord ne crée pas automatiquement de carte.','Nom de carte','Usage prévu','Plafond YNXT de test (entier)','J’accepte card-testnet-v1 et les risques Testnet','Créer la demande','Préparer le défi','Vérifier dans YNX Wallet','Envoyer la demande approuvée','Actualiser les demandes','Annuler la demande','Aucune demande.','Résultat incertain. Actualisez avant de réessayer.','Vérification enregistrée','Approuvez la demande exacte, puis envoyez-la séparément.',"Création incertaine. Conservez la demande et actualisez avant de réessayer.","Réessayer la demande exacte","Nouvelle demande (conserver l’ancienne)","Demande initiale"],
  de:['Testnet-Karte beantragen','Privater Testantrag. Keine Bankkarte, PAN, CVV, Fiatwährung oder echte Zahlung. Freigabe erstellt keine Karte automatisch.','Kartenname','Verwendungszweck','YNXT-Testlimit (ganze Token)','Ich akzeptiere card-testnet-v1 und Testnet-Risiken','Antrag erstellen','Freigabe-Challenge vorbereiten','In YNX Wallet prüfen','Freigegebenen Antrag senden','Anträge aktualisieren','Antrag stornieren','Keine Anträge.','Ergebnis unklar. Vor Wiederholung aktualisieren.','Gespeicherte Freigabe','Exakten Antrag freigeben und separat senden.',"Erstellung unklar. Ursprünglichen Antrag behalten und vor Wiederholung aktualisieren.","Exakten gespeicherten Antrag wiederholen","Neuer Antrag (vorherigen behalten)","Ursprünglicher Antrag"],
  pt:['Solicitar cartão Testnet','Solicitação privada de teste. Sem cartão bancário, PAN, CVV, moeda fiduciária ou pagamento real. Aprovação não cria cartão automaticamente.','Nome do cartão','Uso pretendido','Limite YNXT de teste (inteiro)','Aceito card-testnet-v1 e os riscos Testnet','Criar solicitação','Preparar desafio','Revisar no YNX Wallet','Enviar solicitação aprovada','Atualizar solicitações','Cancelar solicitação','Nenhuma solicitação.','Resultado incerto. Atualize antes de tentar novamente.','Revisão salva','Aprove a solicitação exata e envie separadamente.',"Criação incerta. Guarde a solicitação e atualize antes de tentar novamente.","Repetir a solicitação exata","Nova solicitação (guardar anterior)","Solicitação original"],
  ru:['Заявка на карту Testnet','Приватная тестовая заявка. Не банковская карта, PAN, CVV, фиат или реальные платежи. Одобрение не создаёт карту автоматически.','Название карты','Назначение','Лимит YNXT (целые токены)','Принимаю card-testnet-v1 и риски Testnet','Создать заявку','Подготовить запрос','Проверить в YNX Wallet','Отправить одобренную заявку','Обновить заявки','Отменить заявку','Заявок нет.','Результат неизвестен. Обновите перед повтором.','Сохранённое одобрение','Одобрите точную заявку, затем отправьте отдельно.',"Создание не подтверждено. Сохраните исходный запрос и обновите перед повтором.","Повторить сохранённый запрос","Новая заявка (сохранить предыдущую)","Исходный запрос"],
  ar:['طلب بطاقة شبكة الاختبار','طلب اختبار خاص. ليس بطاقة مصرفية أو PAN أو CVV أو نقوداً أو دفعاً حقيقياً. الموافقة لا تنشئ بطاقة تلقائياً.','اسم البطاقة','الاستخدام','حد YNXT التجريبي (عدد صحيح)','أقبل شروط card-testnet-v1 ومخاطر الاختبار','إنشاء طلب','تحضير تحدي الموافقة','مراجعة في YNX Wallet','إرسال الطلب الموافق عليه','تحديث الطلبات','إلغاء الطلب','لا طلبات.','النتيجة غير مؤكدة. حدّث قبل المحاولة مجدداً.','مراجعة محفوظة','وافق على الطلب المحدد ثم أرسله بشكل منفصل.',"نتيجة الإنشاء غير مؤكدة. احتفظ بالطلب وحدّث السجلات قبل المحاولة.","إعادة الطلب المحفوظ نفسه","طلب جديد (مع إبقاء السابق)","الطلب الأصلي"],
  id:['Ajukan kartu Testnet','Permohonan uji privat. Bukan kartu bank, PAN, CVV, uang fiat atau pembayaran nyata. Persetujuan tidak otomatis membuat kartu.','Nama kartu','Tujuan penggunaan','Batas uji YNXT (token bulat)','Saya menerima card-testnet-v1 dan risiko Testnet','Buat permohonan','Siapkan tantangan','Tinjau di YNX Wallet','Kirim permohonan disetujui','Muat ulang permohonan','Batalkan permohonan','Belum ada permohonan.','Hasil belum pasti. Muat ulang sebelum mencoba lagi.','Tinjauan tersimpan','Setujui permohonan yang tepat lalu kirim secara terpisah.',"Hasil pembuatan belum pasti. Simpan permintaan asli dan muat ulang sebelum mencoba.","Ulangi permintaan tersimpan yang sama","Permohonan baru (simpan sebelumnya)","Permintaan asli"],
};
const randomId=()=>globalThis.crypto.randomUUID();
const contextKey=(identity:CardPrivateIdentity)=>JSON.stringify([identity.owner,identity.sessionBinding,identity.expiresAt]);
export function CoreCardApplicationExperience({client,identity,locale,transport}:{client:CardBusinessClient;identity:CardPrivateIdentity;locale:Locale;transport:HostedCardApprovalTransport|null}){
  const text=copy[locale],key=contextKey(identity);
  const live=useRef({client,identity,key});live.current={client,identity,key};
  const epoch=useRef(0),mounted=useRef(false),flight=useRef(false);
  const [records,setRecords]=useState<{key:string;client:CardBusinessClient;apps:readonly CardApplicationView[]}|null>(null),[selected,setSelected]=useState('');
  const [nickname,setNickname]=useState(''),[useCase,setUseCase]=useState(''),[limit,setLimit]=useState('100'),[terms,setTerms]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [review,setReview]=useState<{key:string;id:string;state:string}|null>(null);
  const [creation,setCreation]=useState<{key:string;journal:CoreCreationJournal}|null>(null);
  const current=()=>mounted.current&&live.current.client===client&&live.current.key===key&&Date.parse(live.current.identity.expiresAt)>Date.now();
  const consumer=()=>createHostedCardApprovalConsumer({registry,storage:{getItem:async name=>Platform.OS==='web'?window.localStorage.getItem(name):SecureStore.getItemAsync(name),setItem:async(name,value)=>{if(Platform.OS==='web')window.localStorage.setItem(name,value);else await SecureStore.setItemAsync(name,value,{keychainAccessible:SecureStore.WHEN_UNLOCKED_THIS_DEVICE_ONLY})}},context:()=>current()?{owner:identity.owner,contextKey:key}:null});
  const creationConsumer=()=>createCoreCardCreationConsumer({storage:{getItem:async name=>Platform.OS==='web'?window.localStorage.getItem(name):SecureStore.getItemAsync(name),setItem:async(name,value)=>{if(Platform.OS==='web')window.localStorage.setItem(name,value);else await SecureStore.setItemAsync(name,value,{keychainAccessible:SecureStore.WHEN_UNLOCKED_THIS_DEVICE_ONLY})}},context:()=>current()?{owner:identity.owner,contextKey:key}:null,create:(details,id)=>client.createApplication(details,id),readBack:()=>client.state(),id:randomId});
  const recoverCreation=async()=>{const journal=await creationConsumer().recover();if(!current())throw Error('CARD_CREATION_CONTEXT_CHANGED');setCreation({key,journal});return journal};
  const load=async()=>{const snapshot=await client.state();if(!current())throw Error('CARD_APPROVAL_CONTEXT_CHANGED');setRecords({key,client,apps:snapshot.applications});setSelected(previous=>previous||snapshot.applications[0]?.id||'');return snapshot;};
  const run=async(operation:()=>Promise<unknown>)=>{if(flight.current||!current())return;const token=++epoch.current;flight.current=true;setBusy(true);setError('');try{await operation()}catch(e){if(current()&&token===epoch.current)setError(e instanceof Error&&/^[A-Z0-9_]{3,100}$/.test(e.message)?e.message:'CARD_API_UNAVAILABLE')}finally{if(current()&&token===epoch.current){flight.current=false;setBusy(false)}}};
  useEffect(()=>{mounted.current=true;flight.current=false;setSelected('');setReview(null);setNickname('');setUseCase('');setTerms(false);setLimit('100');void run(async()=>{await load();await recoverCreation()});return()=>{mounted.current=false;epoch.current++;flight.current=false}},[client,key]);
  const apps=records?.key===key&&records.client===client?records.apps:[],application=apps.find(item=>item.id===selected);
  useEffect(()=>{let active=true;setReview(null);if(selected&&current())void consumer().recover(selected).then(saved=>{if(active&&current()&&saved)setReview({key,id:selected,state:saved.entry.state})}).catch(()=>{if(active&&current())setError('CARD_APPROVAL_RECOVERY_REQUIRED')});return()=>{active=false}},[client,key,selected]);
  const readApplication=async(id:string)=>{const snapshot=await client.state();if(!current())throw Error('CARD_APPROVAL_CONTEXT_CHANGED');const app=snapshot.applications.find(item=>item.id===id);if(!app)throw Error('CARD_APPLICATION_NOT_FOUND');return app;};
  const activeCreation=creation?.key===key?creation.journal.entries.find(entry=>entry.operationId===creation.journal.activeOperationId):null,pendingCreation=activeCreation&&activeCreation.state!=='confirmed';
  const create=()=>void run(async()=>{if(!terms||!nickname.trim()||!useCase.trim()||!/^\d{1,12}$/.test(limit)||BigInt(limit)<=0n)throw Error('CARD_APPLICATION_DETAILS_INVALID');try{const result=await creationConsumer().create({nickname:nickname.trim(),useCase:useCase.trim(),limitWei:(BigInt(limit)*10n**18n).toString(),riskAccepted:true,termsVersion:'card-testnet-v1'});if(!current())throw Error('CARD_APPROVAL_CONTEXT_CHANGED');setCreation({key,journal:result.journal});setSelected(result.application.id);setTerms(false);await load()}catch(e){await recoverCreation();throw e}});
  const reviewApplication=()=>{if(!application)return;const id=application.id;void run(async()=>{
    if(Platform.OS!=='web')throw Error('CARD_WEB_APPLICATION_APPROVAL_TRANSPORT_UNAVAILABLE');
    const result=await consumer().review({applicationId:id,transport,operationId:randomId(),resultOperationId:randomId(),readRecord:()=>readApplication(id),prepare:async()=>{const exact=await readApplication(id);if(exact.status!=='APPROVAL_REQUIRED'||!exact.challenge)throw Error('CARD_APPROVAL_CHALLENGE_REQUIRED');return createCardApplicationApprovalRequest(registry,{productId:'card',platform:'web',account:identity.owner,challenge:exact.challenge as unknown as CardApplicationApprovalRequest['challenge'],details:exact.details as unknown as Extract<CardApplicationApprovalRequest,{version:'1'}>['details'],requestId:randomId(),state:randomId()})}});
    if(!current())throw Error('CARD_APPROVAL_CONTEXT_CHANGED');setReview({key,id,state:result.entry.state});await load();
  })};
  const submit=()=>{if(!application)return;const id=application.id;void run(async()=>{const approved=await consumer().beforeSubmit(id,()=>readApplication(id));const original=await readApplication(id);if(original.status!=='APPROVAL_REQUIRED')throw Error('CARD_APPROVAL_STATE_CHANGED');await client.submitApplication(id,approved.approval,approved.entry.operationId);await load()})};
  const Button=({title,onPress,disabled=false}:{title:string;onPress:()=>void;disabled?:boolean})=><Pressable accessibilityRole="button" accessibilityLabel={title} accessibilityState={{disabled:busy||disabled}} disabled={busy||disabled} onPress={onPress} style={[s.button,(busy||disabled)&&s.disabled]}><Text style={s.buttonText}>{title}</Text></Pressable>;
  return <View style={s.panel} testID="card-private-application">
    <Text accessibilityRole="header" style={s.title}>{text[0]}</Text><Text style={s.body}>{text[1]}</Text>
    {[{title:text[2],value:nickname,set:setNickname},{title:text[3],value:useCase,set:setUseCase},{title:text[4],value:limit,set:setLimit}].map(field=><View key={field.title}><Text style={s.body}>{field.title}</Text><TextInput accessibilityLabel={field.title} editable={!busy} value={field.value} onChangeText={field.set} style={s.input}/></View>)}
    <View style={s.row}><Switch accessibilityLabel={text[5]} value={terms} disabled={busy} onValueChange={setTerms}/><Text style={s.body}>{text[5]}</Text></View>
    <View style={s.row}><Button title={text[6]} onPress={create} disabled={!terms||Boolean(pendingCreation)}/><Button title={text[10]} onPress={()=>void run(async()=>{await load();await recoverCreation()})}/></View>
    {pendingCreation?<View style={s.record}><Text accessibilityRole="alert" style={s.body}>{text[16]}</Text><Text style={s.body}>{text[19]}: {activeCreation.details.nickname} · {activeCreation.details.limitWei} YNXT WEI / TESTNET</Text><Text selectable style={s.code}>{activeCreation.operationId}</Text><View style={s.row}><Button title={text[17]} onPress={()=>void run(async()=>{try{const result=await creationConsumer().retryExact();if(!current())throw Error('CARD_CREATION_CONTEXT_CHANGED');setSelected(result.application.id);setCreation({key,journal:result.journal});await load()}catch(e){await recoverCreation();throw e}})}/><Button title={text[18]} onPress={()=>void run(async()=>{const journal=await creationConsumer().startNewIntent();if(!current())throw Error('CARD_CREATION_CONTEXT_CHANGED');setCreation({key,journal});setReview(null);setSelected('');setTerms(false)})}/></View></View>:null}
    {!apps.length?<Text style={s.body}>{text[12]}</Text>:apps.map(app=><Pressable key={app.id} accessibilityRole="button" accessibilityState={{selected:app.id===selected,disabled:busy}} disabled={busy} onPress={()=>setSelected(app.id)} style={s.record}><Text style={s.body}>{app.details.nickname} · {app.status}</Text><Text selectable style={s.code}>{app.id}</Text></Pressable>)}
    {application?<View style={s.record}><Text style={s.body}>{text[15]}</Text>{review?.key===key&&review.id===application.id?<Text accessibilityLiveRegion="polite" style={s.body}>{text[14]}: {review.state.toUpperCase()}</Text>:null}<View style={s.row}>
      {['DRAFT','DEGRADED','REJECTED'].includes(application.status)?<Button title={text[7]} onPress={()=>void run(async()=>{await client.requestApproval(application.id,randomId());await load()})}/>:null}
      {application.status==='APPROVAL_REQUIRED'?<Button title={text[8]} onPress={reviewApplication}/>:null}
      {application.status==='APPROVAL_REQUIRED'&&review?.key===key&&review.id===application.id&&review.state==='approved'?<Button title={text[9]} onPress={submit}/>:null}
      {!['ACTIVE','CANCELLED'].includes(application.status)?<Button title={text[11]} onPress={()=>void run(async()=>{await client.cancelApplication(application.id,randomId());await load()})}/>:null}
    </View></View>:null}
    {error?<View accessibilityRole="alert"><Text style={s.body}>{text[13]}</Text><Text style={s.code}>{error}</Text></View>:null}
  </View>;
}
const s=StyleSheet.create({panel:{gap:12,padding:16,borderWidth:1,borderColor:'#C9D5FF',borderRadius:12,backgroundColor:'#F4F7FF'},title:{fontSize:19,fontWeight:'700',color:'#171A22'},body:{fontSize:14,lineHeight:22,color:'#414957'},code:{fontSize:12,color:'#5B6270'},input:{minHeight:44,borderWidth:1,borderColor:'#DFE3EA',borderRadius:8,padding:10,backgroundColor:'#FFFFFF',color:'#171A22'},row:{flexDirection:'row',flexWrap:'wrap',alignItems:'center',gap:10},record:{padding:12,gap:8,borderWidth:1,borderColor:'#DFE3EA',borderRadius:8,backgroundColor:'#FFFFFF'},button:{minHeight:44,padding:12,justifyContent:'center',backgroundColor:'#002FA7',borderRadius:8},buttonText:{fontSize:14,fontWeight:'600',color:'#FFFFFF'},disabled:{opacity:0.5}});
