import test from"node:test";
import assert from"node:assert/strict";
import{CardDataFabricOutbox,mapProcessorEvent}from"./dataFabric";
import{TestnetSimulationProcessor,YNXT_TESTNET_ASSET}from"./processor";

const now="2026-08-20T00:00:00.000Z",hash="0x1111111111111111111111111111111111111111111111111111111111111111";
function setup(){const processor=new TestnetSimulationProcessor();processor.createCard({cardAccountId:"account_1",walletAccount:"0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",cardId:"card_1",createdAt:now});return processor}
test("Data Fabric emits card.funded only from verified Testnet funding proof",()=>{const processor=setup(),funding=processor.creditTestnetFunding("card_1",{txHash:hash,chainId:"0x1917",amountMinor:900,confirmations:2,idempotencyKey:"funding-1"},now),events=mapProcessorEvent(funding);assert.deepEqual(events.map(event=>event.name),["card.funded"]);assert.deepEqual(events[0]?.chainEvidence,{chainId:"0x1917",txHash:hash});assert.deepEqual(mapProcessorEvent({...funding,relatedId:"not-a-hash"}),[])});
test("Data Fabric maps simulated authorization lifecycle without sensitive card data",()=>{const processor=setup();processor.creditTestnetFunding("card_1",{txHash:hash,chainId:"0x1917",amountMinor:900,confirmations:2,idempotencyKey:"funding-1"},now);const authorization=processor.authorize("card_1",{merchantId:"merchant_demo",merchantName:"Simulated Merchant",merchantCategoryCode:"5812",country:"YN",amountMinor:100,currency:YNXT_TESTNET_ASSET,channel:"online",cardNotPresent:true,recurring:false,timestamp:now,idempotencyKey:"auth-1"});assert.deepEqual(mapProcessorEvent(authorization).map(event=>event.name),["card.authorization.requested","card.authorization.approved"]);const capture=processor.capture("card_1",{authorizationId:authorization.id,amountMinor:100,idempotencyKey:"capture-1",timestamp:now});assert.deepEqual(mapProcessorEvent(capture).map(event=>event.name),["card.capture.completed"])});
test("Data Fabric outbox deduplicates and retries the same event identity",async()=>{const processor=setup(),funding=processor.creditTestnetFunding("card_1",{txHash:hash,chainId:"0x1917",amountMinor:900,confirmations:2,idempotencyKey:"funding-1"},now),event=mapProcessorEvent(funding),outbox=new CardDataFabricOutbox();outbox.enqueue(event);outbox.enqueue(event);assert.equal(outbox.pending().length,1);let attempt=0;await outbox.flush({publish:async()=>{attempt++;throw new Error("offline")}});assert.deepEqual(outbox.pending().map(record=>record.attempts),[1]);await outbox.flush({publish:async()=>{attempt++}});assert.equal(outbox.pending().length,0);assert.equal(attempt,2)});
