import {type Locale} from "./i18n";

export type HostedWalletNotice="choice"|"connected"|"rejected"|"popupBlocked"|"popupClosed"|"expired"|"accountChanged"|"disconnected"|"wrongNetwork"|"unavailable"|"localOnly";
type Messages=Readonly<Record<HostedWalletNotice,string>>;

// Hosted errors are rendered from a code at display time, so changing language
// cannot leave an English async Wallet error inside another locale.
export const hostedWalletMessages:Readonly<Record<Locale,Messages>>={
  en:{choice:"Installed YNX Wallet extension or official Hosted Wallet popup. Approval is required.",connected:"Connected through YNX Wallet Web. Card private services and funding remain separate.",rejected:"YNX Wallet request was rejected. No account was connected.",popupBlocked:"YNX Wallet popup was blocked. Allow popups and retry; no account was connected.",popupClosed:"YNX Wallet popup was closed. No account was connected.",expired:"YNX Wallet request expired or this page reloaded. Retry with a new request.",accountChanged:"YNX Wallet account changed. Reconnect explicitly; private Card access was cleared.",disconnected:"YNX Wallet disconnected. Reconnect to continue.",wrongNetwork:"YNX Wallet is not on YNX Testnet. Reconnect and confirm chain 0x1917.",unavailable:"YNX Wallet Web is unavailable. Guest mode and MetaMask remain available.",localOnly:"Card disconnected YNX Wallet Web locally. Remote permission revocation was not proven."},
  "zh-CN":{choice:"使用已安装的 YNX Wallet 扩展，或打开官方托管钱包弹窗；必须明确批准。",connected:"已通过 YNX Wallet Web 连接。Card 私有服务与充值权限仍相互独立。",rejected:"YNX Wallet 请求被拒绝。未连接账户。",popupBlocked:"YNX Wallet 弹窗被阻止。允许弹窗后重试；未连接账户。",popupClosed:"YNX Wallet 弹窗已关闭。未连接账户。",expired:"YNX Wallet 请求已过期或页面已重载。请用新请求重试。",accountChanged:"YNX Wallet 账户已变更。请明确重新连接；私有 Card 权限已清除。",disconnected:"YNX Wallet 已断开。请重新连接。",wrongNetwork:"YNX Wallet 不在 YNX 测试网。重新连接并确认链 0x1917。",unavailable:"YNX Wallet Web 暂不可用。访客模式与 MetaMask 仍可使用。",localOnly:"Card 已在本地断开 YNX Wallet Web；尚未证明远端权限已撤销。"},
  "zh-TW":{choice:"使用已安裝的 YNX Wallet 擴充功能，或開啟官方託管錢包視窗；必須明確批准。",connected:"已透過 YNX Wallet Web 連線。Card 私有服務與儲值權限仍各自獨立。",rejected:"YNX Wallet 請求遭拒。未連線帳戶。",popupBlocked:"YNX Wallet 彈出視窗遭封鎖。允許後重試；未連線帳戶。",popupClosed:"YNX Wallet 彈出視窗已關閉。未連線帳戶。",expired:"YNX Wallet 請求已過期或頁面已重新載入。請以新請求重試。",accountChanged:"YNX Wallet 帳戶已變更。請明確重新連線；私有 Card 權限已清除。",disconnected:"YNX Wallet 已中斷連線。請重新連線。",wrongNetwork:"YNX Wallet 不在 YNX 測試網。重新連線並確認鏈 0x1917。",unavailable:"YNX Wallet Web 暫時無法使用。訪客模式與 MetaMask 仍可使用。",localOnly:"Card 已在本機中斷 YNX Wallet Web；尚未證明遠端權限已撤銷。"},
  ja:{choice:"インストール済みの YNX Wallet 拡張機能、または公式ホスト型ウォレットのポップアップを使います。承認が必要です。",connected:"YNX Wallet Web で接続しました。Card の非公開サービスと入金権限は別です。",rejected:"YNX Wallet の要求は拒否されました。アカウントは接続されていません。",popupBlocked:"YNX Wallet のポップアップがブロックされました。許可して再試行してください。接続はありません。",popupClosed:"YNX Wallet のポップアップが閉じられました。接続はありません。",expired:"YNX Wallet の要求が期限切れか、ページが再読み込みされました。新しい要求で再試行してください。",accountChanged:"YNX Wallet のアカウントが変わりました。明示的に再接続してください。Card の非公開アクセスは解除されました。",disconnected:"YNX Wallet が切断されました。再接続してください。",wrongNetwork:"YNX Wallet は YNX テストネット上にありません。再接続してチェーン 0x1917 を確認してください。",unavailable:"YNX Wallet Web は利用できません。ゲストモードと MetaMask は引き続き使えます。",localOnly:"Card は YNX Wallet Web をローカルで切断しました。リモート権限の取り消しは確認されていません。"},
  ko:{choice:"설치된 YNX Wallet 확장 프로그램 또는 공식 호스팅 지갑 팝업을 사용합니다. 승인이 필요합니다.",connected:"YNX Wallet Web으로 연결했습니다. Card 비공개 서비스와 충전 권한은 별개입니다.",rejected:"YNX Wallet 요청이 거절되었습니다. 연결된 계정은 없습니다.",popupBlocked:"YNX Wallet 팝업이 차단되었습니다. 팝업을 허용하고 다시 시도하세요. 계정은 연결되지 않았습니다.",popupClosed:"YNX Wallet 팝업이 닫혔습니다. 계정은 연결되지 않았습니다.",expired:"YNX Wallet 요청이 만료되었거나 페이지가 새로고침되었습니다. 새 요청으로 다시 시도하세요.",accountChanged:"YNX Wallet 계정이 변경되었습니다. 명시적으로 다시 연결하세요. Card 비공개 접근은 해제되었습니다.",disconnected:"YNX Wallet 연결이 끊겼습니다. 다시 연결하세요.",wrongNetwork:"YNX Wallet이 YNX 테스트넷에 있지 않습니다. 다시 연결하고 체인 0x1917을 확인하세요.",unavailable:"YNX Wallet Web을 사용할 수 없습니다. 게스트 모드와 MetaMask는 계속 사용할 수 있습니다.",localOnly:"Card가 YNX Wallet Web을 로컬에서 연결 해제했습니다. 원격 권한 철회는 확인되지 않았습니다."},
  es:{choice:"Usa la extensión YNX Wallet instalada o la ventana oficial de la billetera alojada. Se requiere aprobación.",connected:"Conectado mediante YNX Wallet Web. Los servicios privados de Card y la recarga son independientes.",rejected:"Se rechazó la solicitud de YNX Wallet. No se conectó ninguna cuenta.",popupBlocked:"Se bloqueó la ventana de YNX Wallet. Permite ventanas emergentes y reintenta; no se conectó ninguna cuenta.",popupClosed:"Se cerró la ventana de YNX Wallet. No se conectó ninguna cuenta.",expired:"La solicitud de YNX Wallet caducó o se recargó la página. Reintenta con una solicitud nueva.",accountChanged:"Cambió la cuenta de YNX Wallet. Reconecta de forma explícita; se borró el acceso privado de Card.",disconnected:"YNX Wallet se desconectó. Reconecta para continuar.",wrongNetwork:"YNX Wallet no está en la red de pruebas YNX. Reconecta y confirma la cadena 0x1917.",unavailable:"YNX Wallet Web no está disponible. El modo invitado y MetaMask siguen disponibles.",localOnly:"Card desconectó YNX Wallet Web localmente. No se comprobó la revocación del permiso remoto."},
  fr:{choice:"Utilisez l’extension YNX Wallet installée ou la fenêtre officielle du portefeuille hébergé. Une approbation est requise.",connected:"Connecté via YNX Wallet Web. Les services privés Card et le financement restent distincts.",rejected:"La demande YNX Wallet a été refusée. Aucun compte n’est connecté.",popupBlocked:"La fenêtre YNX Wallet a été bloquée. Autorisez les fenêtres puis réessayez ; aucun compte n’est connecté.",popupClosed:"La fenêtre YNX Wallet a été fermée. Aucun compte n’est connecté.",expired:"La demande YNX Wallet a expiré ou la page a été rechargée. Réessayez avec une nouvelle demande.",accountChanged:"Le compte YNX Wallet a changé. Reconnectez-vous explicitement ; l’accès privé Card a été effacé.",disconnected:"YNX Wallet est déconnecté. Reconnectez-vous pour continuer.",wrongNetwork:"YNX Wallet n’est pas sur le réseau de test YNX. Reconnectez-vous et confirmez la chaîne 0x1917.",unavailable:"YNX Wallet Web est indisponible. Le mode invité et MetaMask restent accessibles.",localOnly:"Card a déconnecté YNX Wallet Web localement. La révocation distante n’est pas prouvée."},
  de:{choice:"Verwende die installierte YNX-Wallet-Erweiterung oder das offizielle gehostete Wallet-Popup. Eine Freigabe ist erforderlich.",connected:"Über YNX Wallet Web verbunden. Private Card-Dienste und Aufladung bleiben getrennt.",rejected:"Die YNX-Wallet-Anfrage wurde abgelehnt. Kein Konto wurde verbunden.",popupBlocked:"Das YNX-Wallet-Popup wurde blockiert. Popups erlauben und erneut versuchen; kein Konto wurde verbunden.",popupClosed:"Das YNX-Wallet-Popup wurde geschlossen. Kein Konto wurde verbunden.",expired:"Die YNX-Wallet-Anfrage ist abgelaufen oder die Seite wurde neu geladen. Mit neuer Anfrage erneut versuchen.",accountChanged:"Das YNX-Wallet-Konto hat sich geändert. Bitte bewusst neu verbinden; privater Card-Zugriff wurde entfernt.",disconnected:"YNX Wallet wurde getrennt. Zum Fortfahren erneut verbinden.",wrongNetwork:"YNX Wallet ist nicht im YNX-Testnetz. Erneut verbinden und Chain 0x1917 bestätigen.",unavailable:"YNX Wallet Web ist nicht verfügbar. Gastmodus und MetaMask bleiben nutzbar.",localOnly:"Card hat YNX Wallet Web lokal getrennt. Ein Widerruf der Remote-Berechtigung ist nicht belegt."},
  pt:{choice:"Use a extensão YNX Wallet instalada ou a janela oficial da carteira hospedada. É necessária aprovação.",connected:"Conectado pelo YNX Wallet Web. Serviços privados do Card e recarga continuam separados.",rejected:"A solicitação da YNX Wallet foi recusada. Nenhuma conta foi conectada.",popupBlocked:"A janela da YNX Wallet foi bloqueada. Permita pop-ups e tente novamente; nenhuma conta foi conectada.",popupClosed:"A janela da YNX Wallet foi fechada. Nenhuma conta foi conectada.",expired:"A solicitação da YNX Wallet expirou ou a página foi recarregada. Tente novamente com uma nova solicitação.",accountChanged:"A conta da YNX Wallet mudou. Reconecte explicitamente; o acesso privado do Card foi removido.",disconnected:"A YNX Wallet foi desconectada. Reconecte para continuar.",wrongNetwork:"A YNX Wallet não está na rede de testes YNX. Reconecte e confirme a cadeia 0x1917.",unavailable:"O YNX Wallet Web está indisponível. O modo visitante e a MetaMask continuam disponíveis.",localOnly:"O Card desconectou o YNX Wallet Web localmente. A revogação remota não foi comprovada."},
  ru:{choice:"Используйте установленное расширение YNX Wallet или официальное всплывающее окно размещённого кошелька. Требуется подтверждение.",connected:"Подключено через YNX Wallet Web. Частные сервисы Card и пополнение остаются отдельными.",rejected:"Запрос YNX Wallet отклонён. Аккаунт не подключён.",popupBlocked:"Окно YNX Wallet заблокировано. Разрешите всплывающие окна и повторите попытку; аккаунт не подключён.",popupClosed:"Окно YNX Wallet закрыто. Аккаунт не подключён.",expired:"Запрос YNX Wallet истёк или страница перезагрузилась. Повторите с новым запросом.",accountChanged:"Аккаунт YNX Wallet изменился. Подключитесь заново явно; частный доступ Card сброшен.",disconnected:"YNX Wallet отключён. Подключитесь заново.",wrongNetwork:"YNX Wallet не в тестовой сети YNX. Подключитесь заново и проверьте сеть 0x1917.",unavailable:"YNX Wallet Web недоступен. Гостевой режим и MetaMask остаются доступны.",localOnly:"Card отключил YNX Wallet Web только локально. Отзыв удалённого разрешения не подтверждён."},
  ar:{choice:"استخدم إضافة YNX Wallet المثبتة أو نافذة المحفظة المستضافة الرسمية. يلزم موافقة صريحة.",connected:"تم الاتصال عبر YNX Wallet Web. تبقى خدمات Card الخاصة والتمويل منفصلين.",rejected:"رُفض طلب YNX Wallet. لم يُربط أي حساب.",popupBlocked:"حُظرت نافذة YNX Wallet. اسمح بالنوافذ المنبثقة ثم أعد المحاولة؛ لم يُربط أي حساب.",popupClosed:"أُغلقت نافذة YNX Wallet. لم يُربط أي حساب.",expired:"انتهت صلاحية طلب YNX Wallet أو أُعيد تحميل الصفحة. أعد المحاولة بطلب جديد.",accountChanged:"تغيّر حساب YNX Wallet. أعد الاتصال صراحةً؛ أُلغي وصول Card الخاص.",disconnected:"انقطع اتصال YNX Wallet. أعد الاتصال للمتابعة.",wrongNetwork:"YNX Wallet ليس على شبكة YNX التجريبية. أعد الاتصال وأكّد السلسلة 0x1917.",unavailable:"YNX Wallet Web غير متاح. يبقى وضع الضيف وMetaMask متاحين.",localOnly:"فصل Card اتصال YNX Wallet Web محلياً فقط. لم يثبت إلغاء الإذن البعيد."},
  id:{choice:"Gunakan ekstensi YNX Wallet yang terpasang atau popup Dompet Hosted resmi. Persetujuan diperlukan.",connected:"Terhubung melalui YNX Wallet Web. Layanan privat Card dan pendanaan tetap terpisah.",rejected:"Permintaan YNX Wallet ditolak. Tidak ada akun yang terhubung.",popupBlocked:"Popup YNX Wallet diblokir. Izinkan popup lalu coba lagi; tidak ada akun yang terhubung.",popupClosed:"Popup YNX Wallet ditutup. Tidak ada akun yang terhubung.",expired:"Permintaan YNX Wallet kedaluwarsa atau halaman dimuat ulang. Coba lagi dengan permintaan baru.",accountChanged:"Akun YNX Wallet berubah. Hubungkan ulang secara jelas; akses privat Card telah dihapus.",disconnected:"YNX Wallet terputus. Hubungkan ulang untuk melanjutkan.",wrongNetwork:"YNX Wallet tidak berada di Testnet YNX. Hubungkan ulang dan pastikan chain 0x1917.",unavailable:"YNX Wallet Web tidak tersedia. Mode tamu dan MetaMask tetap tersedia.",localOnly:"Card memutus YNX Wallet Web secara lokal. Pencabutan izin jarak jauh belum terbukti."}
};

export function hostedWalletNotice(code:string|null):HostedWalletNotice {
  switch(code){
    case "USER_REJECTED":return "rejected";
    case "HOSTED_POPUP_BLOCKED":return "popupBlocked";
    case "HOSTED_POPUP_CLOSED":return "popupClosed";
    case "HOSTED_REQUEST_EXPIRED_OR_RELOADED":case "HOSTED_REQUEST_TIMEOUT":return "expired";
    case "HOSTED_ACCOUNT_CHANGED":return "accountChanged";
    case "HOSTED_DISCONNECTED":return "disconnected";
    case "WRONG_NETWORK":return "wrongNetwork";
    default:return "unavailable";
  }
}
export function hostedWalletText(locale:Locale,notice:HostedWalletNotice):string{return hostedWalletMessages[locale][notice];}
