import type{Locale}from './i18n';
type Kind='rejected'|'expired'|'permission'|'context'|'network'|'source'|'unavailable';
const kinds:readonly Kind[]=['rejected','expired','permission','context','network','source','unavailable'];
const messages:Record<Locale,readonly string[]>={
 en:['Wallet review was declined. No new Card permission was granted.','Card permission expired or was revoked. Review access again to continue.','Review the required Card permission in Wallet to continue.','Your Card identity changed. Refresh records for the current account.','The private request could not finish. Retry without changing your Standard Wallet connection.','The Card service version could not be verified. Existing records are preserved.','Card private services are unavailable. Standard Wallet and guest exploration remain independent.'],
 'zh-CN':['钱包审批已拒绝，未授予新的 Card 权限。','Card 权限已过期或撤销，请重新审核访问权限。','请在钱包中审核所需 Card 权限后继续。','Card 身份已变化，请刷新当前账户的记录。','私有请求未能完成，请重试；标准钱包连接不受影响。','无法验证 Card 服务版本，现有记录已保留。','Card 私有服务暂不可用，标准钱包和访客浏览保持独立。'],
 'zh-TW':['錢包審批已拒絕，未授予新的 Card 權限。','Card 權限已過期或撤銷，請重新審核存取權限。','請在錢包中審核所需 Card 權限後繼續。','Card 身分已變更，請重新整理目前帳戶的記錄。','私人請求未能完成，請重試；標準錢包連線不受影響。','無法驗證 Card 服務版本，現有記錄已保留。','Card 私人服務暫不可用，標準錢包和訪客瀏覽保持獨立。'],
 ja:['ウォレット審査は拒否されました。新しい Card 権限はありません。','Card 権限が期限切れまたは取り消されました。再確認してください。','ウォレットで必要な Card 権限を確認してください。','Card の識別情報が変わりました。現在のアカウントの記録を更新してください。','非公開リクエストは完了できませんでした。標準ウォレットを変更せず再試行してください。','Card サービスのバージョンを確認できません。既存の記録は保持されています。','Card の非公開サービスは利用できません。標準ウォレットとゲストは独立しています。'],
 ko:['지갑 승인이 거절되었습니다. 새 Card 권한은 없습니다.','Card 권한이 만료되거나 취소되었습니다. 접근 권한을 다시 확인하세요.','지갑에서 필요한 Card 권한을 확인하세요.','Card 계정이 변경되었습니다. 현재 계정 기록을 새로 고침하세요.','비공개 요청을 완료하지 못했습니다. 표준 지갑 연결을 변경하지 않고 다시 시도하세요.','Card 서비스 버전을 확인할 수 없습니다. 기존 기록은 보존됩니다.','Card 비공개 서비스를 사용할 수 없습니다. 표준 지갑과 게스트는 독립적입니다.'],
 es:['Revisión rechazada. No se concedió ningún permiso nuevo de Card.','El permiso de Card caducó o fue revocado. Revisa el acceso.','Revisa el permiso de Card requerido en Wallet.','Cambió tu identidad de Card. Actualiza los registros de la cuenta actual.','La solicitud privada no terminó. Reintenta sin cambiar la conexión Wallet estándar.','No se verificó la versión de Card. Los registros existentes se conservan.','Servicios privados de Card no disponibles. Wallet estándar e invitado son independientes.'],
 fr:['Demande refusée. Aucun nouveau droit Card accordé.','Le droit Card a expiré ou a été révoqué. Vérifiez à nouveau l’accès.','Vérifiez le droit Card nécessaire dans Wallet.','Votre identité Card a changé. Actualisez les données du compte actuel.','La demande privée n’a pas abouti. Réessayez sans changer la connexion Wallet standard.','La version du service Card n’est pas vérifiée. Les données sont conservées.','Services privés Card indisponibles. Wallet standard et invité restent indépendants.'],
 de:['Wallet-Prüfung abgelehnt. Keine neue Card-Berechtigung erteilt.','Card-Berechtigung abgelaufen oder widerrufen. Zugriff erneut prüfen.','Erforderliche Card-Berechtigung im Wallet prüfen.','Card-Identität geändert. Daten des aktuellen Kontos aktualisieren.','Private Anfrage nicht abgeschlossen. Ohne Änderung der Standard-Wallet-Verbindung erneut versuchen.','Card-Serviceversion nicht verifiziert. Vorhandene Daten bleiben erhalten.','Private Card-Dienste nicht verfügbar. Standard-Wallet und Gast bleiben unabhängig.'],
 pt:['Revisão recusada. Nenhuma nova permissão Card concedida.','A permissão Card expirou ou foi revogada. Revise o acesso.','Revise a permissão Card necessária no Wallet.','Sua identidade Card mudou. Atualize os registros da conta atual.','A solicitação privada não terminou. Tente novamente sem alterar o Wallet padrão.','A versão do serviço Card não foi verificada. Registros existentes preservados.','Serviços privados Card indisponíveis. Wallet padrão e visitante são independentes.'],
 ru:['Запрос отклонён. Новые права Card не предоставлены.','Разрешение Card истекло или отозвано. Проверьте доступ заново.','Проверьте необходимое разрешение Card в кошельке.','Идентификатор Card изменился. Обновите записи текущего аккаунта.','Приватный запрос не завершён. Повторите без изменения стандартного кошелька.','Версия сервиса Card не проверена. Существующие записи сохранены.','Приватные сервисы Card недоступны. Стандартный кошелёк и гостевой режим независимы.'],
 ar:['رُفضت مراجعة المحفظة. لم يُمنح إذن Card جديد.','انتهى إذن Card أو أُلغي. راجع الوصول مجدداً.','راجع إذن Card المطلوب في المحفظة.','تغيّرت هوية Card. حدّث سجلات الحساب الحالي.','لم يكتمل الطلب الخاص. أعد المحاولة دون تغيير اتصال المحفظة القياسية.','لم يُتحقق من إصدار خدمة Card. السجلات الحالية محفوظة.','خدمات Card الخاصة غير متاحة. المحفظة القياسية ووضع الضيف مستقلان.'],
 id:['Peninjauan ditolak. Tidak ada izin Card baru.','Izin Card kedaluwarsa atau dicabut. Tinjau akses kembali.','Tinjau izin Card yang diperlukan di Wallet.','Identitas Card berubah. Muat ulang catatan akun saat ini.','Permintaan privat belum selesai. Coba lagi tanpa mengubah Wallet standar.','Versi layanan Card belum terverifikasi. Catatan lama tetap terjaga.','Layanan privat Card tidak tersedia. Wallet standar dan tamu tetap independen.'],
};
function kind(code:string):Kind{
 if(code==='USER_REJECTED')return 'rejected';
 if(['PRODUCT_SESSION_EXPIRED','PRODUCT_SESSION_REVOKED'].includes(code))return 'expired';
 if(['PRIVATE_SESSION_REQUIRED','CARD_PERMISSION_DENIED','INSUFFICIENT_SCOPE'].includes(code))return 'permission';
 if(['CARD_CONTEXT_CHANGED','CARD_WEB_PRIVATE_CONTEXT_CHANGED'].includes(code))return 'context';
 if(['PRODUCT_SESSION_GATEWAY_UNREACHABLE','CARD_WEB_PRIVATE_TRANSPORT_TIMEOUT','PRIVATE_SESSION_PROOF_TIMEOUT','CARD_API_TIMEOUT'].includes(code))return 'network';
 if(['CARD_API_SOURCE_MISMATCH','CARD_API_SOURCE_UNAVAILABLE'].includes(code))return 'source';
 return 'unavailable';
}
/** Presentation only: never interprets a code as approval, identity or permissions. */
export function privateServiceText(locale:Locale,code:string):string{return messages[locale][kinds.indexOf(kind(code))]!;}
