import React,{useCallback,useEffect,useRef,useState} from 'react';
import {ActivityIndicator,Linking,Platform,Pressable,StyleSheet,Switch,Text,TextInput,View} from 'react-native';
import * as SecureStore from 'expo-secure-store';
import {encodeCardApplicationApprovalWalletURL,type CardApplicationApprovalRequest} from '@ynx-chain/wallet-auth-card-provider-v2';
import registry from '../vendor/product-session-registry-b754ffc42.json';
import {CardProviderClient} from './providerApplicationClient';
import type {Locale} from './i18n';
import {formatProviderAmount,parseProviderLimit,providerBlockState} from './providerAmounts';
import {approvalJournalKey,readApprovalJournal,rememberApproval,savedApproval,type ApprovalContinuation} from './providerApprovalJournal';

type Program={provider:'immersve';programId:string;environment:'TEST';cardAccountCurrency:string;minorUnitDigits:number;termsVersion:string;termsHash:string;feeDisclosureText:string;feeDisclosureHash:string};
type Application={id:string;productCardId:string;programId:string;provider:string;status:string;nickname:string;testSpendingLimitMinor:string;cardAccountCurrency:string;minorUnitDigits:number;upstreamCardId:string|null;walletApprovalVerified:boolean;createdAt:string};
type Card={cardId:string;lastFour:string|null;status:string;isBlocked:boolean|null;sourceAsOf:string|null};
type History={items:readonly {id:string;status:string;paymentType:string;amountMinor:string|null;currency:string|null;minorUnitDigits:number|null;reconciliation:string;occurredAt:string|null}[];nextCursor:string|null};
type Selection={id:string;generation:number;client:CardProviderClient;owner:string|null};
const BLUE='#002FA7',INK='#171A22',MUTED='#5B6270',LINE='#DFE3EA';
const financeScopeAvailable=Boolean(registry.products.find(product=>product.productId==='card')?.scopes.includes('card:finance:share'));

function list<T>(value:unknown):T[]{return Array.isArray(value)?value as T[]:[]}
function object(value:unknown):Record<string,unknown>{return value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:{}}
function code(error:unknown){const value=object(error).code??(error instanceof Error?error.message:null);return typeof value==='string'&&/^[A-Z0-9_]{3,80}$/.test(value)?value:'CARD_API_UNAVAILABLE'}
function id(){return 'ui-'+Array.from(globalThis.crypto.getRandomValues(new Uint8Array(16)),value=>value.toString(16).padStart(2,'0')).join('')}
async function journal(owner:string){const key=approvalJournalKey(owner);const raw=Platform.OS==='web'?window.localStorage.getItem(key):await SecureStore.getItemAsync(key);return readApprovalJournal(raw,owner)}
async function saveContinuation(entry:ApprovalContinuation){const key=approvalJournalKey(entry.owner),value=JSON.stringify(rememberApproval(await journal(entry.owner),entry));if(Platform.OS==='web'){window.localStorage.setItem(key,value);if(window.localStorage.getItem(key)!==value)throw Error('CARD_APPROVAL_STORAGE_FAILED')}else{await SecureStore.setItemAsync(key,value,{keychainAccessible:SecureStore.WHEN_UNLOCKED_THIS_DEVICE_ONLY});if(await SecureStore.getItemAsync(key)!==value)throw Error('CARD_APPROVAL_STORAGE_FAILED')}}

function label(locale:Locale,en:string,zh:string){return locale==='zh-CN'||locale==='zh-TW'?zh:en}

/** Provider TEST records stay separate from the guest YNXT simulation. */
export function ProviderExperience({client,locale,platform,requestFinancePermission}:{client:CardProviderClient;requestFinancePermission?:()=>Promise<void>;locale:Locale;platform:'web'|'ios'|'android'}){
  const [programs,setPrograms]=useState<Program[]>([]),[apps,setApps]=useState<Application[]>([]),[selected,setSelected]=useState(''),[status,setStatus]=useState<Card|null>(null),[funding,setFunding]=useState<Record<string,unknown>|null>(null),[history,setHistory]=useState<History|null>(null),[consent,setConsent]=useState<Record<string,unknown>|null>(null);
  const [draftProgramId,setDraftProgramId]=useState(''),[nickname,setNickname]=useState('My TEST card'),[useCase,setUseCase]=useState('Testnet QA'),[limit,setLimit]=useState('100'),[terms,setTerms]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[showDiagnostics,setShowDiagnostics]=useState(false);
  const [financeActivity,setFinanceActivity]=useState(false),[financeTransactions,setFinanceTransactions]=useState(false),[approvalOperation,setApprovalOperation]=useState('');
  const selectionRef=useRef<Selection>({id:'',generation:0,client,owner:client.currentOwner()});
  const clientRef=useRef(client),mountedRef=useRef(false),operationRef=useRef(0);
  clientRef.current=client;
  useEffect(()=>{mountedRef.current=true;return()=>{mountedRef.current=false;operationRef.current++;selectionRef.current={...selectionRef.current,generation:selectionRef.current.generation+1}}},[]);
  const errorMessage=(value:string)=>{
    if(value==='CARD_LIMIT_INVALID')return label(locale,'Enter a positive spending limit with the supported currency precision.','请输入大于零的消费限额，小数位数须符合所选币种。');
    if(value==='PRIVATE_SESSION_REQUIRED'||value==='PRIVATE_SESSION_PROOF_UNAVAILABLE'||value==='CARD_PERMISSION_DENIED')return label(locale,'Review this permission in Wallet, then return to continue. Existing transactions are unchanged.','请先在钱包中审核此权限，再返回继续。现有交易不会因此变更。');
    if(value.includes('JOURNAL')||value.includes('STORAGE'))return label(locale,'Your saved approval could not be read or saved. Keep the current app data and check application status before trying again.','无法读取或保存审批记录。请保留当前应用数据，先检查申请状态，再尝试操作。');
    if(value==='BLOCKED_PROVIDER_SPEC_SESSION_LOOKUP')return label(locale,'Identity verification is not connected for this test program yet.','此测试项目暂未接通身份验证。');
    if(value==='PROVIDER_PROGRAM_NOT_CONFIGURED')return label(locale,'This test program is not connected yet. Your existing cards remain available.','此测试项目尚未接通，已有卡片记录仍会保留。');
    if(value==='CARD_APPROVAL_REJECTED')return label(locale,'You declined the Wallet request. No card creation was submitted.','你已拒绝钱包请求，未提交开卡操作。');
    return label(locale,'The result could not be confirmed. Refresh records to check the current status before repeating an operation.','暂时无法确认结果。请刷新记录检查当前状态，再决定是否继续操作。');
  };
  const formatMinor=(value:unknown,digits:unknown,currency:unknown)=>formatProviderAmount(value,digits,currency)??label(locale,'Not available','暂不可用');
  const current=apps.find(app=>app.id===selected)??null,program=programs.find(item=>item.programId===current?.programId)??null,draftProgram=programs.find(item=>item.programId===draftProgramId)??programs[0]??null;
  const isCurrent=useCallback((context:Selection)=>mountedRef.current&&clientRef.current===context.client&&selectionRef.current===context&&context.client.currentOwner()===context.owner,[]);
  const selectApplication=useCallback((id:string)=>{const previous=selectionRef.current,owner=client.currentOwner();if(previous.id===id&&previous.client===client&&previous.owner===owner)return;selectionRef.current={id,generation:previous.generation+1,client,owner};operationRef.current++;setSelected(id);setStatus(null);setFunding(null);setHistory(null);setApprovalOperation('');setBusy(false);setError('');setNotice('')},[client]);
  const perform=useCallback(async<T,>(operation:()=>Promise<T>,after?:(result:T)=>void|Promise<void>,valid:()=>boolean=()=>true)=>{const context=selectionRef.current,allowed=()=>valid()&&isCurrent(context);if(!allowed())return null;const token=++operationRef.current;setBusy(true);setError('');try{const result=await operation();if(allowed())await after?.(result);return result}catch(e){if(allowed())setError(code(e));return null}finally{if(allowed()&&operationRef.current===token)setBusy(false)}},[isCurrent]);
  const performSelected=useCallback(<T,>(id:string,operation:()=>Promise<T>,after?:(result:T)=>void|Promise<void>)=>{const context=selectionRef.current;return perform(operation,after,()=>context.id===id&&isCurrent(context))},[isCurrent,perform]);
  const renderOwner=client.currentOwner();
  useEffect(()=>{if(selectionRef.current.client!==client||selectionRef.current.owner!==renderOwner)selectApplication(selectionRef.current.id)},[client,renderOwner,selectApplication]);
  const refresh=useCallback(async()=>{const context=selectionRef.current;await perform(async()=>{const [p,a,c]=await Promise.all([client.programs(),client.listApplications(),client.financeConsent()]);return {p,a,c}},result=>{setPrograms(list<Program>(result.p));const applications=list<Application>(result.a);setApps(applications);setConsent(result.c?object(result.c):null);selectApplication(applications.some(item=>item.id===selectionRef.current.id)?selectionRef.current.id:applications[0]?.id??'')},()=>isCurrent(context))},[client,isCurrent,perform,selectApplication]);
  useEffect(()=>{void refresh()},[refresh]);
  useEffect(()=>{if(!selected)return;const context=selectionRef.current;if(context.id!==selected)return;let live=true;const valid=()=>live&&isCurrent(context);void perform(async()=>{const [s,f]=await Promise.allSettled([client.status(selected),client.funding(selected)]);return {s,f}},result=>{if(result.s.status==='fulfilled')setStatus(object(result.s.value).card as Card);if(result.f.status==='fulfilled')setFunding(object(result.f.value))},valid);return()=>{live=false}},[selected,client,renderOwner,isCurrent,perform]);
  useEffect(()=>{let live=true;setApprovalOperation('');const owner=client.currentOwner();if(owner&&selected)void journal(owner).then(value=>{if(live&&client.currentOwner()===owner)setApprovalOperation(savedApproval(value,selected)?.operationId??'')}).catch(()=>{if(live)setError('CARD_APPROVAL_STORAGE_FAILED')});return()=>{live=false}},[client,selected]);
  useEffect(()=>{let live=true,accepting=false;const accept=async(url:string)=>{
    let callback:URL;try{callback=new URL(url)}catch{return}if(!callback.searchParams.has('cardApplicationApprovalResult')||accepting)return;
    const owner=client.currentOwner();if(!owner)return;accepting=true;const context=selectionRef.current,valid=()=>live&&isCurrent(context);
    await perform(async()=>{const saved=savedApproval(await journal(owner));if(!saved)throw Error('CARD_APPROVAL_CONTINUATION_MISSING');if(!valid())throw Error('CARD_CONTEXT_CHANGED');await client.acceptApproval(saved.applicationId,url,saved.resultOperationId);return saved},saved=>{selectApplication(saved.applicationId);setApprovalOperation(saved.operationId);setNotice(label(locale,'Wallet approval saved. Review the application before submitting.','钱包审批已保存，请核对申请后提交。'));if(Platform.OS==='web')window.history.replaceState(null,'','/');void refresh()},valid);accepting=false;
  };const subscription=Linking.addEventListener('url',event=>{void accept(event.url)});if(Platform.OS==='web'&&typeof window!=='undefined')void accept(window.location.href);else void Linking.getInitialURL().then(url=>{if(url)void accept(url)});return()=>{live=false;subscription.remove()}},[client,isCurrent,locale,perform,refresh,selectApplication]);
  const create=()=>{if(!draftProgram||!terms)return;const context=selectionRef.current;void perform(()=>client.createDraft({provider:draftProgram.provider,programId:draftProgram.programId,nickname:nickname.trim(),useCase:useCase.trim(),testSpendingLimitMinor:parseProviderLimit(limit,draftProgram.minorUnitDigits),cardAccountCurrency:draftProgram.cardAccountCurrency,minorUnitDigits:draftProgram.minorUnitDigits,termsVersion:draftProgram.termsVersion,termsHash:draftProgram.termsHash,feeDisclosureHash:draftProgram.feeDisclosureHash,riskAccepted:true},id()),()=>{setTerms(false);void refresh()},()=>isCurrent(context))};
  const approve=()=>{if(!current||!funding||typeof funding.fundingSourceId!=='string')return;const applicationId=current.id,owner=client.currentOwner(),context=selectionRef.current;if(!owner)return;const valid=()=>isCurrent(context);void performSelected(applicationId,async()=>{
    const existing=savedApproval(await journal(owner),applicationId),operation=existing?.operationId??id();
    const result=await client.prepareApproval(applicationId,{platform,fundingSourceId:funding.fundingSourceId as string,idempotencyKey:operation},operation);
    const request=result as CardApplicationApprovalRequest,url=encodeCardApplicationApprovalWalletURL(registry,request),approvedId=request.version==='2'?request.details.idempotencyKey:operation;
    if(!valid()||client.currentOwner()!==owner)throw Error('CARD_CONTEXT_CHANGED');
    await saveContinuation({owner,applicationId,operationId:approvedId,resultOperationId:existing?.resultOperationId??id()});
    if(!valid()||client.currentOwner()!==owner)throw Error('CARD_CONTEXT_CHANGED');setApprovalOperation(approvedId);await Linking.openURL(url);
  })};
  const loadHistory=(cursor?:string)=>{if(!current)return;const cardId=current.id,context=selectionRef.current,valid=()=>isCurrent(context);void performSelected(cardId,()=>client.history(cardId,cursor),result=>{const page=result as History;setHistory(previous=>{if(!valid())return previous;if(!cursor)return page;if(!previous||previous.nextCursor!==cursor)return previous;return {items:[...previous.items,...page.items],nextCursor:page.nextCursor}})})};
  const controls=(action:'freeze'|'unfreeze')=>{if(!current)return;const cardId=current.id;void performSelected(cardId,()=>client.control(cardId,action,id()),result=>{setNotice(object(result).status==='UNKNOWN'?label(locale,'Result pending confirmation. Refresh the card status before another operation.','结果待确认，请先刷新卡片状态再进行其他操作。'):label(locale,'Request recorded. Refresh to confirm card status.','请求已记录，请刷新确认卡片状态。'));void performSelected(cardId,()=>client.status(cardId),value=>setStatus(object(value).card as Card))})};
  const scopes=[...(financeActivity?['card.provider-activity.read']:[]),...(financeTransactions?['card.provider-transactions.read']:[])] as ('card.provider-activity.read'|'card.provider-transactions.read')[];
  return <View style={s.panel} testID="provider-test-workspace"><Text style={s.title}>{label(locale,'Your test cards','我的测试卡片')}</Text><Text style={s.note}>{label(locale,'Immersve TEST records are separate from the local YNXT demo. No real card, funds or payment acceptance is represented.','Immersve TEST 记录与本地 YNXT 演示分开；这里不代表真实卡、资金或支付受理。')}</Text>
    <Button title={label(locale,'Refresh records','刷新记录')} busy={busy} onPress={()=>void refresh()}/>{busy?<ActivityIndicator color={BLUE}/>:null}{error?<View><Text accessibilityRole="alert" style={s.error}>{errorMessage(error)}</Text><Pressable accessibilityRole="button" onPress={()=>setShowDiagnostics(value=>!value)}><Text style={s.note}>{label(locale,'Technical details','技术详情')}</Text></Pressable>{showDiagnostics?<Text style={s.note}>{error}</Text>:null}</View>:null}{notice?<Text accessibilityRole="alert" style={s.note}>{notice}</Text>:null}
    {programs.length===0?<Text style={s.empty}>{label(locale,'No enabled TEST program or disclosure is configured.','尚未配置可用的 TEST 项目及费用披露。')}</Text>:<View style={s.box}><Text style={s.heading}>{label(locale,'Eligibility and fee disclosure','资格与费用披露')}</Text><View style={s.row}>{programs.map(item=><Pressable key={item.programId} accessibilityRole="button" accessibilityState={{selected:item.programId===draftProgram?.programId}} onPress={()=>{setDraftProgramId(item.programId);setTerms(false)}} style={[s.choice,item.programId===draftProgram?.programId&&s.selected]}><Text style={s.strong}>{item.programId} · {item.cardAccountCurrency}</Text></Pressable>)}</View><Text style={s.note}>{draftProgram?.programId} · {draftProgram?.cardAccountCurrency} · TEST</Text><Text style={s.note}>{draftProgram?.feeDisclosureText}</Text><Text style={s.note}>{label(locale,'Eligibility and KYC are verified by the provider; a draft is not an issued card.','资格和 KYC 由服务商验证；草稿并非已发行卡。')}</Text><Text style={s.strong}>{label(locale,'Card name','卡片名称')}</Text><TextInput accessibilityLabel="TEST card nickname" style={s.input} value={nickname} onChangeText={setNickname}/><Text style={s.strong}>{label(locale,'Intended use','用途')}</Text><TextInput accessibilityLabel="TEST use case" style={s.input} value={useCase} onChangeText={setUseCase}/><Text style={s.strong}>{label(locale,'Test spending limit','测试消费限额')} · {draftProgram?.cardAccountCurrency}</Text><TextInput accessibilityLabel={label(locale,'TEST spending limit','测试消费限额')} keyboardType="decimal-pad" style={s.input} value={limit} onChangeText={setLimit}/><View style={s.row}><Switch value={terms} onValueChange={setTerms}/><Text style={s.note}>{label(locale,'I accept this exact TEST disclosure and risk','我接受此 TEST 费用披露及风险')}</Text></View><Button title={label(locale,'Create TEST draft','创建 TEST 草稿')} busy={busy||!terms} onPress={create}/></View>}
    <View style={s.box}><Text style={s.heading}>{label(locale,'Applications and card status','申请与卡状态')}</Text>{apps.length===0?<Text style={s.empty}>{label(locale,'No provider application yet.','暂无服务商申请。')}</Text>:apps.map(app=><Pressable key={app.id} accessibilityRole="button" accessibilityState={{selected:app.id===selected}} onPress={()=>selectApplication(app.id)} style={[s.choice,app.id===selected&&s.selected]}><Text style={s.strong}>{app.nickname} · {app.status}</Text><Text style={s.note}>{app.programId} · {app.provider} TEST</Text></Pressable>)}
    {current?<><Text style={s.note}>{label(locale,'TEST limit','TEST 限额')}: {formatMinor(current.testSpendingLimitMinor,current.minorUnitDigits,current.cardAccountCurrency)}</Text><Text style={s.note}>{label(locale,'Card','卡')}: {status?.lastFour?'•••• '+status.lastFour:label(locale,'Not verified','未验证')} · {status?.status??label(locale,'Unknown','未知')} · {providerBlockState(status?.isBlocked)==='unknown'?label(locale,'Freeze status unavailable','冻结状态暂不可用'):status?.isBlocked?label(locale,'Frozen','已冻结'):label(locale,'Unfrozen','未冻结')}</Text><Text style={s.note}>{label(locale,'Provider observation','服务商读取时间')}: {status?.sourceAsOf??label(locale,'Unknown','未知')}</Text><View style={s.row}>{current.status==='DRAFT'?<Button title={label(locale,'Acknowledge terms','确认条款')} busy={busy} onPress={()=>void performSelected(current.id,()=>client.acknowledgeTerms(current.id,{termsVersion:program?.termsVersion,termsHash:program?.termsHash,feeDisclosureHash:program?.feeDisclosureHash,riskAccepted:true},id()),()=>void refresh())}/>:null}{current.status==='KYC_REQUIRED'||current.status==='DEGRADED'?<Button title={label(locale,'Start hosted verification','开始托管验证')} busy={busy} onPress={()=>void performSelected(current.id,()=>client.beginHostedKyc(current.id,id()),result=>{const url=object(result).hostedUrl;if(typeof url==='string')void Linking.openURL(url);else setNotice(errorMessage('BLOCKED_PROVIDER_SPEC_SESSION_LOOKUP'));void refresh()})}/>:null}{current.status==='APPROVAL_REQUIRED'?<Button title={label(locale,'Request Wallet review','请求钱包审批')} busy={busy||!funding} onPress={approve}/>:null}{current.status==='APPROVAL_REQUIRED'&&current.walletApprovalVerified?<Button title={label(locale,'Submit one TEST create request','提交唯一 TEST 创建请求')} busy={busy||!approvalOperation} onPress={()=>void performSelected(current.id,()=>client.submit(current.id,approvalOperation),result=>{setNotice(object(result).status==='UNKNOWN'?label(locale,'Outcome unknown. Do not submit again.','结果未知，请勿重试提交。'):label(locale,'Provider response recorded. Read back status.','服务商响应已记录，请读取状态。'));void refresh()})}/>:null}</View>
      <View style={s.row}><Button title={label(locale,'Read provider status','读取服务商状态')} busy={busy} onPress={()=>void performSelected(current.id,()=>client.status(current.id),result=>setStatus(object(result).card as Card))}/><Button title={label(locale,'Read funding source','读取资金来源')} busy={busy} onPress={()=>void performSelected(current.id,()=>client.funding(current.id),result=>setFunding(object(result)))}/>{status?.status==='active'&&status.isBlocked===false?<Button title={label(locale,'Freeze','冻结')} busy={busy} onPress={()=>controls('freeze')}/>:null}{status?.status==='active'&&status.isBlocked===true?<Button title={label(locale,'Unfreeze','解冻')} busy={busy} onPress={()=>controls('unfreeze')}/>:null}</View>
      {funding?<Text style={s.note}>{label(locale,'Provider TEST funding source balance, not Card spendable balance','服务商 TEST 资金来源余额，并非卡可用余额')}: {formatMinor(String(funding.balanceMinor??''),funding.decimals,funding.balanceCurrency)} · {String(funding.fundingNetwork??'')} · {String(funding.observedAt??'')}</Text>:null}</>:null}</View>
    {current?<View style={s.box}><Text style={s.heading}>{label(locale,'Transactions and reconciliation','交易与对账')}</Text><Button title={label(locale,'Read history','读取历史')} busy={busy} onPress={()=>loadHistory()}/>{history?.items.length===0?<Text style={s.empty}>{label(locale,'No provider transactions returned.','服务商未返回交易。')}</Text>:history?.items.map(item=><View key={item.id} style={s.choice}><Text style={s.strong}>{item.paymentType} · {item.status} · {formatMinor(item.amountMinor,item.minorUnitDigits,item.currency)}</Text><Text style={s.note}>{item.occurredAt??'Unknown time'} · {item.reconciliation}</Text></View>)}{history?.nextCursor?<Button title={label(locale,'Load more','加载更多')} busy={busy} onPress={()=>loadHistory(history.nextCursor!)}/>:null}</View>:null}
    <View style={s.box}><Text style={s.heading}>{label(locale,'Share read-only Card records with Finance','向 Finance 共享只读 Card 记录')}</Text><Text style={s.note}>{label(locale,'This requires a separate fresh Wallet permission. It never authorizes transactions.','此操作需要单独的钱包新授权，绝不授权交易。')}</Text>{!financeScopeAvailable?<Text style={s.note}>{label(locale,'Wallet has not enabled the dedicated Card-to-Finance sharing scope. Sharing is unavailable.','钱包尚未启用 Card 向 Finance 共享的独立权限，当前无法共享。')}</Text>:null}{requestFinancePermission?<Button title={label(locale,'Review sharing permission in Wallet','在钱包中审核共享权限')} busy={busy} onPress={()=>void requestFinancePermission()}/>:null}<Text style={s.note}>{label(locale,'Consent','同意')}: {consent?.revokedAt?'revoked':consent?.expiresAt?String(consent.expiresAt):'not granted'}</Text><View style={s.row}><Switch value={financeActivity} onValueChange={setFinanceActivity}/><Text style={s.note}>{label(locale,'Activity','活动记录')}</Text><Switch value={financeTransactions} onValueChange={setFinanceTransactions}/><Text style={s.note}>{label(locale,'Transactions','交易记录')}</Text></View><View style={s.row}><Button title={label(locale,'Grant 30-day read consent','授予 30 天只读同意')} busy={busy||!financeScopeAvailable||scopes.length===0} onPress={()=>void perform(()=>client.grantFinanceConsent(scopes,new Date(Date.now()+30*86400000-1000).toISOString(),id()),result=>setConsent(object(result)))}/><Button title={label(locale,'Revoke sharing','撤销共享')} busy={busy||!financeScopeAvailable} onPress={()=>void perform(()=>client.revokeFinanceConsent(id()),result=>setConsent(result?object(result):null))}/></View></View>
  </View>;
}
function Button({title,busy,onPress}:{title:string;busy:boolean;onPress:()=>void}){return <Pressable accessibilityRole="button" accessibilityLabel={title} disabled={busy} onPress={onPress} style={[s.button,busy&&s.disabled]}><Text style={s.buttonText}>{title}</Text></Pressable>}
const s=StyleSheet.create({panel:{padding:20,gap:14,backgroundColor:'#F4F7FF',borderWidth:1,borderColor:'#C9D5FF',borderRadius:14},title:{fontSize:22,fontWeight:'800',color:BLUE},heading:{fontSize:17,fontWeight:'800',color:INK},note:{fontSize:13,lineHeight:20,color:MUTED,flexShrink:1},strong:{fontSize:14,fontWeight:'700',color:INK},empty:{fontSize:14,color:MUTED,paddingVertical:10},error:{fontSize:13,color:'#B42318',fontWeight:'700'},box:{padding:15,gap:10,backgroundColor:'#FFFFFF',borderWidth:1,borderColor:LINE,borderRadius:11},row:{flexDirection:'row',flexWrap:'wrap',alignItems:'center',gap:10},choice:{padding:10,borderWidth:1,borderColor:LINE,borderRadius:8,gap:3},selected:{borderColor:BLUE},input:{padding:10,borderWidth:1,borderColor:LINE,borderRadius:8,color:INK,minHeight:44},button:{paddingVertical:10,paddingHorizontal:14,borderRadius:8,backgroundColor:BLUE,alignSelf:'flex-start',minHeight:44,justifyContent:'center'},buttonText:{color:'#FFFFFF',fontWeight:'700',fontSize:13},disabled:{opacity:.5}});
