export type RegistrationStatus="DRAFT"|"SUBMITTED"|"APPROVAL_REQUIRED"|"ACTIVE"|"REJECTED"|"CANCELLED"|"DEGRADED";
export type CardRegistration=Readonly<{id:string;owner:string;status:RegistrationStatus;nickname:string;useCase:string;spendingLimitYnxt:string;riskAccepted:boolean;controls:Readonly<{online:boolean;international:boolean;frozen:boolean}>;idempotencyKey:string;audit:readonly Readonly<{event:string;at:string;detail:string;idempotencyKey:string}>[];createdAt:string;updatedAt:string;reason?:string;backendReceipt?:string}>;
const states:readonly RegistrationStatus[]=["DRAFT","SUBMITTED","APPROVAL_REQUIRED","ACTIVE","REJECTED","CANCELLED","DEGRADED"];
const owner=(value:string)=>value.trim().toLowerCase();
const validOwner=(value:string)=>/^0x[0-9a-f]{40}$/.test(owner(value));
const validLimit=(value:string)=>/^[1-9][0-9]{0,5}(?:\.[0-9]{1,6})?$/.test(value);
const audit=(event:string,detail:string,idempotencyKey:string,now:Date)=>Object.freeze({event,detail,idempotencyKey,at:now.toISOString()});
const transition=(record:CardRegistration,status:RegistrationStatus,detail:string,idempotencyKey:string,now:Date,extra:Partial<CardRegistration>={}):CardRegistration=>record.idempotencyKey===idempotencyKey?record:Object.freeze({...record,...extra,status,idempotencyKey,updatedAt:now.toISOString(),audit:Object.freeze([audit(status,detail,idempotencyKey,now),...record.audit].slice(0,80))});

export function createDraft(wallet:string,now=new Date()):CardRegistration{if(!validOwner(wallet))throw new Error("A Standard EVM wallet is required");const key=`draft-${owner(wallet)}`;return Object.freeze({id:`card-app-${now.toISOString().replace(/[^0-9]/g,"")}`,owner:owner(wallet),status:"DRAFT",nickname:"",useCase:"",spendingLimitYnxt:"10",riskAccepted:false,controls:Object.freeze({online:true,international:false,frozen:false}),idempotencyKey:key,audit:Object.freeze([audit("DRAFT","Wallet-bound Testnet application created",key,now)]),createdAt:now.toISOString(),updatedAt:now.toISOString()});}
export function updateDraft(record:CardRegistration,input:Readonly<{nickname:string;useCase:string;spendingLimitYnxt:string;riskAccepted:boolean;controls:CardRegistration["controls"]}>,now=new Date()):CardRegistration{if(record.status!=="DRAFT")throw new Error("Only DRAFT applications are editable");if(input.nickname.trim().length<2||input.nickname.trim().length>48||input.useCase.trim().length<4||input.useCase.trim().length>160||!validLimit(input.spendingLimitYnxt))throw new Error("Complete nickname, use case, and a valid YNXT limit");return Object.freeze({...record,nickname:input.nickname.trim(),useCase:input.useCase.trim(),spendingLimitYnxt:input.spendingLimitYnxt,riskAccepted:input.riskAccepted,controls:Object.freeze({...input.controls}),updatedAt:now.toISOString()});}
export function saveDraftFields(record:CardRegistration,input:Pick<CardRegistration,"nickname"|"useCase"|"spendingLimitYnxt"|"riskAccepted">,now=new Date()):CardRegistration{
  if(record.status!=="DRAFT")throw new Error("Only DRAFT applications are editable");
  const nickname=input.nickname,useCase=input.useCase,spendingLimitYnxt=input.spendingLimitYnxt,riskAccepted=input.riskAccepted;
  if(typeof nickname!=="string"||nickname.length>48||typeof useCase!=="string"||useCase.length>160||typeof spendingLimitYnxt!=="string"||!validLimit(spendingLimitYnxt)||typeof riskAccepted!=="boolean")throw new Error("Complete nickname, use case, and a valid YNXT limit");
  if(nickname===record.nickname&&useCase===record.useCase&&spendingLimitYnxt===record.spendingLimitYnxt&&riskAccepted===record.riskAccepted)return record;
  const at=now.toISOString();
  return Object.freeze({...record,nickname,useCase,spendingLimitYnxt,riskAccepted,updatedAt:at,audit:Object.freeze([audit("DRAFT_SAVED","Testnet draft fields saved locally; no approval or account creation",`draft-save-${record.id}-${at}`,now),...record.audit].slice(0,80))});
}
export function requestApproval(record:CardRegistration,idempotencyKey:string,now=new Date()):CardRegistration{if(record.idempotencyKey===idempotencyKey)return record;if(record.status!=="DRAFT"||!record.riskAccepted||!record.nickname||!record.useCase||!validLimit(record.spendingLimitYnxt))throw new Error("Testnet terms and application details must be accepted first");return transition(record,"APPROVAL_REQUIRED","A real wallet signature and sandbox backend receipt are required",idempotencyKey,now);}
export function submitForBackend(record:CardRegistration,idempotencyKey:string,now=new Date()):CardRegistration{if(record.status!=="APPROVAL_REQUIRED")throw new Error("Application is not awaiting approval");return transition(record,"SUBMITTED","Awaiting verified wallet signature and sandbox backend receipt",idempotencyKey,now);}
export function completeFromSandboxReceipt(record:CardRegistration,input:Readonly<{idempotencyKey:string;approved:boolean;receipt?:string;reason?:string}>,now=new Date()):CardRegistration{if(record.status!=="SUBMITTED")throw new Error("Only submitted applications accept backend results");if(!input.approved)return transition(record,"REJECTED",input.reason??"Sandbox backend rejected the application",input.idempotencyKey,now,{reason:input.reason??"Sandbox backend rejected the application"});if(!input.receipt||!/^sandbox-receipt-[A-Za-z0-9_-]{8,100}$/.test(input.receipt))throw new Error("A verified sandbox receipt is required for ACTIVE");return transition(record,"ACTIVE","Verified sandbox backend created the Testnet account",input.idempotencyKey,now,{backendReceipt:input.receipt,reason:undefined});}
export function degrade(record:CardRegistration,reason:string,idempotencyKey:string,now=new Date()):CardRegistration{if(!reason.trim())throw new Error("A degraded reason is required");return transition(record,"DEGRADED",reason.trim(),idempotencyKey,now,{reason:reason.trim()});}
export function cancel(record:CardRegistration,idempotencyKey:string,now=new Date()):CardRegistration{if(record.status==="ACTIVE")throw new Error("ACTIVE applications cannot be cancelled here");return transition(record,"CANCELLED","User cancelled the Testnet application",idempotencyKey,now);}
export function restoreForWallet(value:unknown,wallet:string):CardRegistration|null{
  if(!validOwner(wallet)||typeof value!=="object"||value===null||Array.isArray(value))return null;
  const record=value as Partial<CardRegistration>;
  if(record.owner!==owner(wallet)||typeof record.id!=="string"||!record.id||!states.includes(record.status as RegistrationStatus)||typeof record.nickname!=="string"||typeof record.useCase!=="string"||typeof record.spendingLimitYnxt!=="string"||!validLimit(record.spendingLimitYnxt)||typeof record.riskAccepted!=="boolean"||typeof record.idempotencyKey!=="string"||!record.idempotencyKey||!record.controls||[record.controls.online,record.controls.international,record.controls.frozen].some(value=>typeof value!=="boolean")||typeof record.createdAt!=="string"||!Number.isFinite(Date.parse(record.createdAt))||typeof record.updatedAt!=="string"||!Number.isFinite(Date.parse(record.updatedAt))||!Array.isArray(record.audit)||record.audit.length>80||record.audit.some(event=>!event||typeof event.event!=="string"||typeof event.detail!=="string"||typeof event.idempotencyKey!=="string"||!Number.isFinite(Date.parse(event.at))))return null;
  const restored={...record,controls:Object.freeze({...record.controls}),audit:Object.freeze(record.audit.map(event=>Object.freeze({...event})))} as CardRegistration;
  // Even a well-shaped persisted receipt is historical, not a current backend
  // acceptance. Keep all details/key/receipt, but never expose an active card.
  return Object.freeze(record.status==="ACTIVE"||record.status==="SUBMITTED"?{...restored,status:"DEGRADED" as const,reason:"BACKEND_READBACK_REQUIRED"}:restored);
}
