import test from "node:test";
import assert from "node:assert/strict";
import {signAuthorization,createCallbackURL,requestDigest}from"@ynx-chain/wallet-auth";
import{BUNDLE_ID,CALLBACK,CLIENT_ID,PRODUCT_ID,SCOPES,approveTestnetTopup,connectEip1193Wallet,createAuthorization,enhanceCardProductSession,loadTestnetTopupEvidence,parseYnxtAmountToWei,verifiedApproval,walletDeepLink}from"./wallet";

const random={secret:new Uint8Array(32).fill(7),nonce:new Uint8Array(32).fill(9)};
test("Card uses exact canonical Wallet registry identity",async()=>{const now=new Date("2026-07-18T06:00:00.000Z"),pending=await createAuthorization(now,random);assert.equal(pending.request.requestingProduct,PRODUCT_ID);assert.equal(pending.request.productClientId,CLIENT_ID);assert.equal(pending.request.bundleId,BUNDLE_ID);assert.equal(pending.request.callback,CALLBACK);assert.deepEqual(pending.request.scopes,[...SCOPES]);assert.match(walletDeepLink(pending),/^ynxwallet:\/\/authorize\?request=/);assert.equal(requestDigest(pending.request).length,64)});
test("canonical Wallet callback verifies every Card binding",async()=>{const now=new Date("2026-07-18T06:00:00.000Z"),pending=await createAuthorization(now,random);const response=signAuthorization(pending.request,{accountSecret:"1".padStart(64,"0"),issuedAt:"2026-07-18T06:00:01.000Z"});const callback=createCallbackURL(response);const verified=verifiedApproval(callback,pending,new Date("2026-07-18T06:00:02.000Z"));assert.equal(verified.productClientId,CLIENT_ID);assert.equal(verified.bundleId,BUNDLE_ID);assert.equal(verified.requestDigest,requestDigest(pending.request));assert.throws(()=>verifiedApproval(callback.replace("ynxcard:","ynxpay:"),pending,now),/Callback|callback/)});
const sender="0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",recipient="0xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",hash="0x1111111111111111111111111111111111111111111111111111111111111111",intent={id:"intent_1",chainId:"0x1917",recipient,amountWei:"1000000000000000000",minConfirmations:2,expiresAt:"2099-01-01T00:00:00.000Z"} as const;
function topupProvider(overrides:{transaction?:Record<string,unknown>;receipt?:Record<string,unknown>;head?:string}={}){const sent:unknown[]=[];return{sent,request:async({method,params}:{method:string;params?:readonly unknown[]})=>{if(method==="eth_chainId")return"0x1917";if(method==="eth_sendTransaction"){sent.push(params?.[0]);return hash;}if(method==="eth_getTransactionByHash")return{from:sender,to:recipient,value:"0xde0b6b3a7640000",blockNumber:"0x64",...overrides.transaction};if(method==="eth_getTransactionReceipt")return{transactionHash:hash,blockHash:"0xabc",blockNumber:"0x64",status:"0x1",...overrides.receipt};if(method==="eth_blockNumber")return overrides.head??"0x65";throw new Error(`Unexpected ${method}`);}}}
test("Card submits an exact intent-bound YNXT wallet transaction and verifies confirmations",async()=>{const provider=topupProvider();const wallet={address:sender,chainId:"0x1917",connectedAt:"2026-08-20T00:00:00.000Z",provider:"eip1193"} as const;assert.equal(parseYnxtAmountToWei("1.25"),"1250000000000000000");assert.equal(await approveTestnetTopup(provider,wallet,intent),hash);assert.deepEqual(provider.sent,[{from:sender,to:recipient,value:"0xde0b6b3a7640000",chainId:"0x1917"}]);const evidence=await loadTestnetTopupEvidence(provider,hash,{...intent,sender});assert.equal(evidence.confirmations,2);assert.equal(evidence.valueWei,intent.amountWei)});
test("Card rejects failed, redirected, or under-confirmed Testnet top-ups",async()=>{assert.throws(()=>parseYnxtAmountToWei("0"),/greater than zero/);await assert.rejects(()=>loadTestnetTopupEvidence(topupProvider({receipt:{status:"0x0"}}),hash,{...intent,sender}),/failed/);await assert.rejects(()=>loadTestnetTopupEvidence(topupProvider({transaction:{to:sender}}),hash,{...intent,sender}),/recipient/);await assert.rejects(()=>loadTestnetTopupEvidence(topupProvider({head:"0x64"}),hash,{...intent,sender}),/requires 2 confirmation/)});
test("Card consumes the Standard Wallet SDK and retains CONNECTED state when private service degrades",async()=>{const provider={request:async({method}:{method:string})=>method==="eth_requestAccounts"?[sender]:method==="eth_chainId"?"0x1917":Promise.reject(new Error(`Unexpected ${method}`))};const standard=await connectEip1193Wallet(provider,new Date("2026-08-20T00:00:00.000Z"));assert.deepEqual(standard,{address:sender,chainId:"0x1917",connectedAt:"2026-08-20T00:00:00.000Z",provider:"eip1193"});const degraded=await enhanceCardProductSession(standard,async()=>{throw Object.assign(new Error("Gateway unavailable"),{status:503,requestId:"request-card-1",traceId:"trace-card-1"})});assert.deepEqual(degraded,{state:"PRIVATE_SERVICE_DEGRADED",code:"PRODUCT_SESSION_GATEWAY_UNREACHABLE",requestId:"request-card-1",traceId:"trace-card-1",errorId:undefined});assert.equal(standard.address,sender);assert.equal(standard.chainId,"0x1917")});
