import test from "node:test";
import assert from "node:assert/strict";
import {createAuthorizationRejection,signAuthorization,createCallbackURL,requestDigest}from"@ynx-chain/wallet-auth";
import{acceptedCardGatewayEndpoint,validateAcceptedCardGatewayManifest}from"./publicEndpointManifest";
import{BUNDLE_ID,CALLBACK,CLIENT_ID,PRODUCT_ID,SCOPES,approveTestnetTopup,classifyCardWalletError,completeLegacyCentralSession,connectEip1193Wallet,connectMetaMaskWallet,createAuthorization,enhanceCardProductSession,loadTestnetTopupEvidence,parseWalletAuthorizationCallback,parseYnxtAmountToWei,verifiedApproval,walletDeepLink}from"./wallet";

const random={secret:new Uint8Array(32).fill(7),nonce:new Uint8Array(32).fill(9)};
test("Card uses exact canonical Wallet registry identity",async()=>{const now=new Date("2026-07-18T06:00:00.000Z"),pending=await createAuthorization(now,random);assert.equal(pending.request.requestingProduct,PRODUCT_ID);assert.equal(pending.request.productClientId,CLIENT_ID);assert.equal(pending.request.bundleId,BUNDLE_ID);assert.equal(pending.request.callback,CALLBACK);assert.deepEqual(pending.request.scopes,[...SCOPES]);assert.match(walletDeepLink(pending),/^ynxwallet:\/\/authorize\?request=/);assert.equal(requestDigest(pending.request).length,64)});
test("canonical Wallet callback verifies every Card binding",async()=>{const now=new Date("2026-07-18T06:00:00.000Z"),pending=await createAuthorization(now,random);const response=signAuthorization(pending.request,{accountSecret:"1".padStart(64,"0"),issuedAt:"2026-07-18T06:00:01.000Z"});const callback=createCallbackURL(response);const verified=verifiedApproval(callback,pending,new Date("2026-07-18T06:00:02.000Z"));assert.equal(verified.productClientId,CLIENT_ID);assert.equal(verified.bundleId,BUNDLE_ID);assert.equal(verified.requestDigest,requestDigest(pending.request));assert.throws(()=>verifiedApproval(callback.replace("ynxcard:","ynxpay:"),pending,now),/Callback|callback/)});
test("Card root callback parser binds an approval or rejection to the same persisted request",async()=>{const now=new Date("2026-07-18T06:00:00.000Z"),pending=await createAuthorization(now,random),rejection=createAuthorizationRejection(pending.request,{decisionCode:"USER_REJECTED",rejectedAt:"2026-07-18T06:00:01.000Z"}),result=parseWalletAuthorizationCallback(createCallbackURL(rejection),pending,new Date("2026-07-18T06:00:02.000Z"));assert.equal(result.decision,"rejected");assert.throws(()=>parseWalletAuthorizationCallback(createCallbackURL(rejection).replace("ynxcard:","ynxpay:"),pending,now),/Callback|callback/);});
const sender="0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",recipient="0xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",hash="0x1111111111111111111111111111111111111111111111111111111111111111",intent={id:"intent_1",chainId:"0x1917",recipient,amountWei:"1000000000000000000",minConfirmations:2,expiresAt:"2099-01-01T00:00:00.000Z"} as const;
function topupProvider(overrides:{transaction?:Record<string,unknown>;receipt?:Record<string,unknown>;head?:string}={}){const sent:unknown[]=[];return{sent,request:async({method,params}:{method:string;params?:readonly unknown[]})=>{if(method==="eth_chainId")return"0x1917";if(method==="eth_sendTransaction"){sent.push(params?.[0]);return hash;}if(method==="eth_getTransactionByHash")return{from:sender,to:recipient,value:"0xde0b6b3a7640000",blockNumber:"0x64",...overrides.transaction};if(method==="eth_getTransactionReceipt")return{transactionHash:hash,blockHash:"0xabc",blockNumber:"0x64",status:"0x1",...overrides.receipt};if(method==="eth_blockNumber")return overrides.head??"0x65";throw new Error(`Unexpected ${method}`);}}}
test("Card submits an exact intent-bound YNXT wallet transaction and verifies confirmations",async()=>{const provider=topupProvider();const wallet={address:sender,chainId:"0x1917",connectedAt:"2026-08-20T00:00:00.000Z",provider:"eip1193"} as const;assert.equal(parseYnxtAmountToWei("1.25"),"1250000000000000000");assert.equal(await approveTestnetTopup(provider,wallet,intent),hash);assert.deepEqual(provider.sent,[{from:sender,to:recipient,value:"0xde0b6b3a7640000",chainId:"0x1917"}]);const evidence=await loadTestnetTopupEvidence(provider,hash,{...intent,sender});assert.equal(evidence.confirmations,2);assert.equal(evidence.valueWei,intent.amountWei)});
test("Card rejects failed, redirected, or under-confirmed Testnet top-ups",async()=>{assert.throws(()=>parseYnxtAmountToWei("0"),/greater than zero/);await assert.rejects(()=>loadTestnetTopupEvidence(topupProvider({receipt:{status:"0x0"}}),hash,{...intent,sender}),/failed/);await assert.rejects(()=>loadTestnetTopupEvidence(topupProvider({transaction:{to:sender}}),hash,{...intent,sender}),/recipient/);await assert.rejects(()=>loadTestnetTopupEvidence(topupProvider({head:"0x64"}),hash,{...intent,sender}),/requires 2 confirmation/)});
test("Card consumes the Standard Wallet SDK and retains CONNECTED state when private service degrades",async()=>{const provider={request:async({method}:{method:string})=>method==="eth_requestAccounts"?[sender]:method==="eth_chainId"?"0x1917":Promise.reject(new Error(`Unexpected ${method}`))};const standard=await connectEip1193Wallet(provider,new Date("2026-08-20T00:00:00.000Z"));assert.deepEqual(standard,{address:sender,chainId:"0x1917",connectedAt:"2026-08-20T00:00:00.000Z",provider:"eip1193"});const degraded=await enhanceCardProductSession(standard,async()=>{throw Object.assign(new Error("Gateway unavailable"),{status:503,requestId:"request-card-1",traceId:"trace-card-1"})});assert.equal(degraded.state,"PRIVATE_SERVICE_DEGRADED");assert.equal(degraded.code,"GATEWAY_UNAVAILABLE");assert.equal(degraded.safeMessage,"Private YNX services are temporarily unavailable; your Wallet connection remains active.");assert.equal(degraded.requestId,"request-card-1");assert.equal(standard.address,sender);assert.equal(standard.chainId,"0x1917")});
test("Card MetaMask action uses the explicit EVM-only MetaMask adapter",async()=>{const calls:string[]=[],provider={isMetaMask:true,request:async({method}:{method:string})=>{calls.push(method);if(method==="eth_chainId")return"0x1917";if(method==="eth_requestAccounts")return[sender];throw new Error(`Unexpected ${method}`)}};const connected=await connectMetaMaskWallet(new Date("2026-08-21T00:00:00.000Z"),provider);assert.deepEqual(connected,{address:sender,chainId:"0x1917",connectedAt:"2026-08-21T00:00:00.000Z",provider:"eip1193"});assert.deepEqual(calls,["eth_chainId","eth_requestAccounts"]);await assert.rejects(()=>connectMetaMaskWallet(new Date(),{request:provider.request}),/MetaMask/);});
test("legacy Card private routes remain blocked and are not v2 evidence",async()=>{const accepted={schemaVersion:"1.0.0",manifestVersion:"1.0.0-p0.2",sourceCommit:"bfd850a2c7bd238e3febc7267ff31be17890888d",environment:"testnet",evmChainId:6423,evmChainHex:"0x1917",appGateway:"https://gateway.ynxweb4.com",endpointStates:{appGateway:{status:"DEGRADED"}}};assert.equal(validateAcceptedCardGatewayManifest(accepted),"https://gateway.ynxweb4.com");for(const hostile of ["https://evil.example","https://user:pass@gateway.ynxweb4.com","https://gateway.ynxweb4.com/card","https://gateway.ynxweb4.com?redirect=https://evil.example"]){assert.throws(()=>validateAcceptedCardGatewayManifest({...accepted,appGateway:hostile}),/fixed accepted Testnet endpoint/);}assert.throws(()=>acceptedCardGatewayEndpoint(),error=>(error as {code?:unknown}).code==="PRODUCT_SESSION_GATEWAY_UNREACHABLE");const now=new Date("2026-07-18T06:00:00.000Z"),pending=await createAuthorization(now,random),approval=signAuthorization(pending.request,{accountSecret:"1".padStart(64,"0"),issuedAt:"2026-07-18T06:00:01.000Z"});await assert.rejects(()=>completeLegacyCentralSession(pending,approval),error=>(error as {code?:unknown}).code==="PRODUCT_SESSION_GATEWAY_UNREACHABLE");});
test("Card preserves provider identity and fails closed on unknown Wallet errors",()=>{for(const[providerCode,code]of [[4001,"USER_REJECTED"],[4100,"UNAUTHORIZED"],[4200,"UNSUPPORTED_METHOD"],[4900,"PROVIDER_DISCONNECTED"],[4901,"CHAIN_DISCONNECTED"],[4902,"UNKNOWN_CHAIN"]] as const){const classified=classifyCardWalletError(providerCode);assert.equal(classified.code,code);assert.notEqual(classified.code,"GATEWAY_UNAVAILABLE");}const safe=classifyCardWalletError({code:"INVALID_DEVICE_PROOF",requestId:"request-card-2",traceId:"trace-card-2",errorId:"error-card-2"});assert.deepEqual(safe,{code:"INVALID_DEVICE_PROOF",retryable:false,safeMessage:"Device verification failed.",monitoringClass:"device-proof",userAction:"register-device",requestId:"request-card-2",traceId:"trace-card-2",errorId:"error-card-2"});assert.deepEqual(classifyCardWalletError({code:"UNTRUSTED_ERROR",requestId:" should-not-leak "}),{code:"UNKNOWN_WALLET_ERROR",retryable:false,safeMessage:"Wallet error could not be verified.",monitoringClass:"wallet-contract",userAction:"return-to-product"})});
