"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Lang = "en" | "zh-CN" | "zh-TW" | "ja" | "ko" | "es" | "fr" | "de" | "pt" | "ru" | "ar" | "id";
type Copy = { nav: string; eyebrow: string; title: string; intro: string; endpoint: string; connected: string; unconfigured: string; unavailable: string; refresh: string; lastCheck: string; health: string; version: string; latency: string; inspect: string; market: string; dataType: string; query: string; noQuery: string; result: string; quality: string; sources: string; stale: string; confidence: string; circuit: string; contract: string; contractText: string; reject: string; schema: string; risk: string; riskText: string; status: string; security: string; support: string; language: string; theme: string; light: string; dark: string; auto: string; yes: string; no: string; notReported: string; failure: string };

const messages: Record<Lang, Copy> = {
  en: { nav: "Oracle", eyebrow: "YNX MARKET DATA CONTROL PLANE", title: "Price evidence, not price promises.", intro: "Inspect availability, lineage, coverage, staleness, and circuit-breaker state before any consumer accepts a value.", endpoint: "API endpoint", connected: "Live endpoint verified", unconfigured: "Public endpoint not configured", unavailable: "Endpoint unavailable", refresh: "Run live check", lastCheck: "Last check", health: "Health", version: "Version", latency: "Round-trip", inspect: "Inspect a market", market: "Market symbol", dataType: "Data type", query: "Query live price", noQuery: "Enter a market to request authoritative data. No sample price is shown.", result: "Response", quality: "Quality", sources: "Independent sources", stale: "Stale", confidence: "Confidence", circuit: "Circuit breaker", contract: "Consumer contract", contractText: "HTTP 200 is not acceptance. Verify schema, source, version, time, coverage, confidence, failure, and breaker state.", reject: "Reject when any required invariant fails", schema: "Schema ynx.oracle.v1", risk: "Testnet risk", riskText: "Market data can be delayed, incomplete, divergent, or unavailable. Consumers must fail closed. This console does not provide investment advice or guaranteed pricing.", status: "Status", security: "Security", support: "Support", language: "Language", theme: "Theme", light: "Light", dark: "Dark", auto: "System", yes: "Yes", no: "No", notReported: "Not reported", failure: "Request failed" },
  "zh-CN": { nav: "预言机", eyebrow: "YNX 市场数据控制平面", title: "提供价格证据，而非价格承诺。", intro: "在消费者接受数值前，检查可用性、血缘、覆盖率、时效性与熔断状态。", endpoint: "API 端点", connected: "已验证实时端点", unconfigured: "尚未配置公共端点", unavailable: "端点不可用", refresh: "执行实时检查", lastCheck: "上次检查", health: "健康状态", version: "版本", latency: "往返延迟", inspect: "检查市场", market: "市场符号", dataType: "数据类型", query: "查询实时价格", noQuery: "输入市场后请求权威数据。此处不展示示例价格。", result: "响应", quality: "质量", sources: "独立来源", stale: "已过期", confidence: "置信度", circuit: "熔断器", contract: "消费者契约", contractText: "HTTP 200 不代表可接受。必须验证架构、来源、版本、时间、覆盖率、置信度、失败与熔断状态。", reject: "任一必要不变量失败时拒绝", schema: "架构 ynx.oracle.v1", risk: "测试网风险", riskText: "市场数据可能延迟、不完整、分歧或不可用。消费者必须安全关闭。本控制台不提供投资建议或价格保证。", status: "状态", security: "安全", support: "支持", language: "语言", theme: "主题", light: "浅色", dark: "深色", auto: "跟随系统", yes: "是", no: "否", notReported: "未报告", failure: "请求失败" },
  "zh-TW": { nav: "預言機", eyebrow: "YNX 市場資料控制平面", title: "提供價格證據，而非價格承諾。", intro: "在消費者接受數值前，檢查可用性、血緣、覆蓋率、時效性與熔斷狀態。", endpoint: "API 端點", connected: "已驗證即時端點", unconfigured: "尚未設定公開端點", unavailable: "端點無法使用", refresh: "執行即時檢查", lastCheck: "上次檢查", health: "健康狀態", version: "版本", latency: "往返延遲", inspect: "檢查市場", market: "市場符號", dataType: "資料類型", query: "查詢即時價格", noQuery: "輸入市場後請求權威資料。此處不顯示範例價格。", result: "回應", quality: "品質", sources: "獨立來源", stale: "已過期", confidence: "信賴度", circuit: "熔斷器", contract: "消費者契約", contractText: "HTTP 200 不代表可接受。必須驗證架構、來源、版本、時間、覆蓋率、信賴度、失敗與熔斷狀態。", reject: "任一必要不變量失敗時拒絕", schema: "架構 ynx.oracle.v1", risk: "測試網風險", riskText: "市場資料可能延遲、不完整、分歧或無法使用。消費者必須安全關閉。本控制台不提供投資建議或價格保證。", status: "狀態", security: "安全", support: "支援", language: "語言", theme: "主題", light: "淺色", dark: "深色", auto: "跟隨系統", yes: "是", no: "否", notReported: "未報告", failure: "請求失敗" },
  ja: { nav: "オラクル", eyebrow: "YNX 市場データ制御プレーン", title: "価格の約束ではなく、価格の証拠を。", intro: "値を受け入れる前に、可用性、系譜、カバレッジ、鮮度、サーキットブレーカーを確認します。", endpoint: "API エンドポイント", connected: "ライブ接続を検証済み", unconfigured: "公開接続先は未設定", unavailable: "接続先を利用できません", refresh: "ライブ確認", lastCheck: "最終確認", health: "健全性", version: "バージョン", latency: "往復時間", inspect: "市場を検査", market: "市場シンボル", dataType: "データ種別", query: "ライブ価格を照会", noQuery: "市場を入力して権威データを要求してください。サンプル価格は表示しません。", result: "応答", quality: "品質", sources: "独立ソース", stale: "期限切れ", confidence: "信頼度", circuit: "サーキットブレーカー", contract: "消費者契約", contractText: "HTTP 200だけでは受理できません。スキーマ、ソース、版、時刻、カバレッジ、信頼度、失敗、遮断状態を検証してください。", reject: "必須条件が一つでも失敗したら拒否", schema: "スキーマ ynx.oracle.v1", risk: "テストネットのリスク", riskText: "市場データは遅延、不完全、乖離、利用不能になり得ます。消費者は安全側に停止してください。投資助言や価格保証ではありません。", status: "状態", security: "セキュリティ", support: "サポート", language: "言語", theme: "テーマ", light: "ライト", dark: "ダーク", auto: "システム", yes: "はい", no: "いいえ", notReported: "未報告", failure: "要求に失敗" },
  ko: { nav: "오라클", eyebrow: "YNX 시장 데이터 제어 영역", title: "가격 약속이 아닌 가격 증거.", intro: "소비자가 값을 수락하기 전에 가용성, 계보, 커버리지, 신선도와 회로 차단기 상태를 확인합니다.", endpoint: "API 엔드포인트", connected: "실시간 연결 확인됨", unconfigured: "공개 엔드포인트 미설정", unavailable: "엔드포인트 사용 불가", refresh: "실시간 확인", lastCheck: "마지막 확인", health: "상태", version: "버전", latency: "왕복 지연", inspect: "시장 검사", market: "시장 기호", dataType: "데이터 유형", query: "실시간 가격 조회", noQuery: "권위 데이터를 요청할 시장을 입력하세요. 예시 가격은 표시하지 않습니다.", result: "응답", quality: "품질", sources: "독립 출처", stale: "오래됨", confidence: "신뢰도", circuit: "회로 차단기", contract: "소비자 계약", contractText: "HTTP 200만으로 수락할 수 없습니다. 스키마, 출처, 버전, 시간, 커버리지, 신뢰도, 실패와 차단 상태를 검증하세요.", reject: "필수 불변 조건 실패 시 거부", schema: "스키마 ynx.oracle.v1", risk: "테스트넷 위험", riskText: "시장 데이터는 지연, 불완전, 불일치 또는 사용 불가 상태가 될 수 있습니다. 소비자는 안전하게 실패해야 합니다. 투자 조언이나 가격 보장이 아닙니다.", status: "상태", security: "보안", support: "지원", language: "언어", theme: "테마", light: "라이트", dark: "다크", auto: "시스템", yes: "예", no: "아니요", notReported: "보고되지 않음", failure: "요청 실패" },
  es: { nav: "Oráculo", eyebrow: "PLANO DE CONTROL DE DATOS YNX", title: "Evidencia de precio, no promesas.", intro: "Comprueba disponibilidad, linaje, cobertura, vigencia y circuitos antes de aceptar un valor.", endpoint: "Punto API", connected: "Conexión verificada", unconfigured: "Punto público no configurado", unavailable: "Punto no disponible", refresh: "Comprobar en vivo", lastCheck: "Última revisión", health: "Salud", version: "Versión", latency: "Ida y vuelta", inspect: "Inspeccionar mercado", market: "Símbolo", dataType: "Tipo de dato", query: "Consultar precio", noQuery: "Introduce un mercado para solicitar datos autorizados. No se muestran precios de ejemplo.", result: "Respuesta", quality: "Calidad", sources: "Fuentes independientes", stale: "Obsoleto", confidence: "Confianza", circuit: "Cortacircuitos", contract: "Contrato del consumidor", contractText: "HTTP 200 no basta. Verifica esquema, fuente, versión, tiempo, cobertura, confianza, fallo y cortacircuitos.", reject: "Rechazar si falla cualquier invariante", schema: "Esquema ynx.oracle.v1", risk: "Riesgo de testnet", riskText: "Los datos pueden retrasarse, ser incompletos, divergir o no estar disponibles. Los consumidores deben fallar con seguridad. No es asesoramiento ni garantía.", status: "Estado", security: "Seguridad", support: "Soporte", language: "Idioma", theme: "Tema", light: "Claro", dark: "Oscuro", auto: "Sistema", yes: "Sí", no: "No", notReported: "No informado", failure: "Solicitud fallida" },
  fr: { nav: "Oracle", eyebrow: "PLAN DE CONTRÔLE DES DONNÉES YNX", title: "Des preuves de prix, pas des promesses.", intro: "Vérifiez disponibilité, traçabilité, couverture, fraîcheur et disjoncteur avant d’accepter une valeur.", endpoint: "Point API", connected: "Connexion vérifiée", unconfigured: "Point public non configuré", unavailable: "Point indisponible", refresh: "Vérifier en direct", lastCheck: "Dernière vérification", health: "Santé", version: "Version", latency: "Aller-retour", inspect: "Inspecter un marché", market: "Symbole", dataType: "Type de donnée", query: "Interroger le prix", noQuery: "Saisissez un marché pour demander les données officielles. Aucun prix d’exemple n’est affiché.", result: "Réponse", quality: "Qualité", sources: "Sources indépendantes", stale: "Périmé", confidence: "Confiance", circuit: "Disjoncteur", contract: "Contrat consommateur", contractText: "HTTP 200 ne suffit pas. Vérifiez schéma, source, version, heure, couverture, confiance, échec et disjoncteur.", reject: "Rejeter si un invariant requis échoue", schema: "Schéma ynx.oracle.v1", risk: "Risque testnet", riskText: "Les données peuvent être retardées, incomplètes, divergentes ou indisponibles. Les consommateurs doivent échouer de façon sûre. Aucun conseil ni garantie.", status: "Statut", security: "Sécurité", support: "Assistance", language: "Langue", theme: "Thème", light: "Clair", dark: "Sombre", auto: "Système", yes: "Oui", no: "Non", notReported: "Non indiqué", failure: "Échec de la requête" },
  de: { nav: "Oracle", eyebrow: "YNX MARKTDATEN-STEUERUNG", title: "Preisnachweise statt Preisversprechen.", intro: "Prüfen Sie Verfügbarkeit, Herkunft, Abdeckung, Aktualität und Schutzschalter, bevor ein Wert akzeptiert wird.", endpoint: "API-Endpunkt", connected: "Live-Endpunkt geprüft", unconfigured: "Öffentlicher Endpunkt nicht konfiguriert", unavailable: "Endpunkt nicht verfügbar", refresh: "Live prüfen", lastCheck: "Letzte Prüfung", health: "Zustand", version: "Version", latency: "Roundtrip", inspect: "Markt prüfen", market: "Marktsymbol", dataType: "Datentyp", query: "Live-Preis abfragen", noQuery: "Markt eingeben, um autoritative Daten anzufordern. Es wird kein Beispielpreis gezeigt.", result: "Antwort", quality: "Qualität", sources: "Unabhängige Quellen", stale: "Veraltet", confidence: "Konfidenz", circuit: "Schutzschalter", contract: "Verbrauchervertrag", contractText: "HTTP 200 genügt nicht. Schema, Quelle, Version, Zeit, Abdeckung, Konfidenz, Fehler und Schutzschalter prüfen.", reject: "Bei verletzter Invariante ablehnen", schema: "Schema ynx.oracle.v1", risk: "Testnet-Risiko", riskText: "Marktdaten können verzögert, unvollständig, abweichend oder nicht verfügbar sein. Verbraucher müssen sicher ausfallen. Keine Beratung oder Preisgarantie.", status: "Status", security: "Sicherheit", support: "Support", language: "Sprache", theme: "Darstellung", light: "Hell", dark: "Dunkel", auto: "System", yes: "Ja", no: "Nein", notReported: "Nicht gemeldet", failure: "Anfrage fehlgeschlagen" },
  pt: { nav: "Oráculo", eyebrow: "PLANO DE CONTROLE DE DADOS YNX", title: "Evidência de preço, não promessas.", intro: "Verifique disponibilidade, linhagem, cobertura, atualidade e disjuntor antes de aceitar um valor.", endpoint: "Endpoint da API", connected: "Endpoint ao vivo verificado", unconfigured: "Endpoint público não configurado", unavailable: "Endpoint indisponível", refresh: "Verificar ao vivo", lastCheck: "Última verificação", health: "Saúde", version: "Versão", latency: "Ida e volta", inspect: "Inspecionar mercado", market: "Símbolo", dataType: "Tipo de dado", query: "Consultar preço", noQuery: "Informe um mercado para solicitar dados oficiais. Nenhum preço de exemplo é exibido.", result: "Resposta", quality: "Qualidade", sources: "Fontes independentes", stale: "Desatualizado", confidence: "Confiança", circuit: "Disjuntor", contract: "Contrato do consumidor", contractText: "HTTP 200 não basta. Verifique esquema, fonte, versão, tempo, cobertura, confiança, falha e disjuntor.", reject: "Rejeitar se qualquer invariante falhar", schema: "Esquema ynx.oracle.v1", risk: "Risco de testnet", riskText: "Os dados podem atrasar, ficar incompletos, divergentes ou indisponíveis. Consumidores devem falhar com segurança. Não é aconselhamento nem garantia.", status: "Status", security: "Segurança", support: "Suporte", language: "Idioma", theme: "Tema", light: "Claro", dark: "Escuro", auto: "Sistema", yes: "Sim", no: "Não", notReported: "Não informado", failure: "Falha na solicitação" },
  ru: { nav: "Оракул", eyebrow: "КОНТУР РЫНОЧНЫХ ДАННЫХ YNX", title: "Доказательства цены, а не обещания.", intro: "Проверяйте доступность, происхождение, покрытие, свежесть и предохранитель до принятия значения.", endpoint: "Конечная точка API", connected: "Подключение проверено", unconfigured: "Публичная точка не настроена", unavailable: "Точка недоступна", refresh: "Проверить сейчас", lastCheck: "Последняя проверка", health: "Состояние", version: "Версия", latency: "Задержка", inspect: "Проверить рынок", market: "Символ рынка", dataType: "Тип данных", query: "Запросить цену", noQuery: "Введите рынок для запроса авторитетных данных. Пример цены не показывается.", result: "Ответ", quality: "Качество", sources: "Независимые источники", stale: "Устарело", confidence: "Уверенность", circuit: "Предохранитель", contract: "Контракт потребителя", contractText: "HTTP 200 недостаточно. Проверьте схему, источник, версию, время, покрытие, уверенность, ошибку и предохранитель.", reject: "Отклонять при нарушении любого инварианта", schema: "Схема ynx.oracle.v1", risk: "Риск тестовой сети", riskText: "Данные могут задерживаться, быть неполными, расходиться или отсутствовать. Потребители должны безопасно прекращать работу. Это не совет и не гарантия.", status: "Статус", security: "Безопасность", support: "Поддержка", language: "Язык", theme: "Тема", light: "Светлая", dark: "Тёмная", auto: "Системная", yes: "Да", no: "Нет", notReported: "Не сообщено", failure: "Ошибка запроса" },
  ar: { nav: "أوراكل", eyebrow: "طبقة تحكم بيانات سوق YNX", title: "دليل للسعر، لا وعود بالسعر.", intro: "تحقق من التوافر والمصدر والتغطية والحداثة وقاطع الدائرة قبل قبول أي قيمة.", endpoint: "نقطة API", connected: "تم التحقق من الاتصال الحي", unconfigured: "النقطة العامة غير مهيأة", unavailable: "النقطة غير متاحة", refresh: "إجراء تحقق حي", lastCheck: "آخر تحقق", health: "السلامة", version: "الإصدار", latency: "زمن الذهاب والعودة", inspect: "فحص سوق", market: "رمز السوق", dataType: "نوع البيانات", query: "طلب السعر الحي", noQuery: "أدخل سوقاً لطلب بيانات موثوقة. لا يُعرض سعر تجريبي.", result: "الاستجابة", quality: "الجودة", sources: "مصادر مستقلة", stale: "قديم", confidence: "الثقة", circuit: "قاطع الدائرة", contract: "عقد المستهلك", contractText: "استجابة HTTP 200 لا تكفي. تحقق من المخطط والمصدر والإصدار والوقت والتغطية والثقة والفشل وحالة القاطع.", reject: "ارفض عند فشل أي شرط إلزامي", schema: "المخطط ynx.oracle.v1", risk: "مخاطر شبكة الاختبار", riskText: "قد تتأخر البيانات أو تكون ناقصة أو متباينة أو غير متاحة. يجب أن يفشل المستهلك بأمان. هذه ليست نصيحة أو ضماناً للسعر.", status: "الحالة", security: "الأمان", support: "الدعم", language: "اللغة", theme: "المظهر", light: "فاتح", dark: "داكن", auto: "النظام", yes: "نعم", no: "لا", notReported: "غير مبلّغ", failure: "فشل الطلب" },
  id: { nav: "Oracle", eyebrow: "PUSAT KENDALI DATA PASAR YNX", title: "Bukti harga, bukan janji harga.", intro: "Periksa ketersediaan, asal, cakupan, kesegaran, dan pemutus sirkuit sebelum menerima nilai.", endpoint: "Endpoint API", connected: "Endpoint langsung terverifikasi", unconfigured: "Endpoint publik belum dikonfigurasi", unavailable: "Endpoint tidak tersedia", refresh: "Periksa langsung", lastCheck: "Pemeriksaan terakhir", health: "Kesehatan", version: "Versi", latency: "Pulang-pergi", inspect: "Periksa pasar", market: "Simbol pasar", dataType: "Jenis data", query: "Minta harga langsung", noQuery: "Masukkan pasar untuk meminta data berwenang. Tidak ada harga contoh yang ditampilkan.", result: "Respons", quality: "Kualitas", sources: "Sumber independen", stale: "Kedaluwarsa", confidence: "Keyakinan", circuit: "Pemutus sirkuit", contract: "Kontrak konsumen", contractText: "HTTP 200 tidak cukup. Periksa skema, sumber, versi, waktu, cakupan, keyakinan, kegagalan, dan pemutus.", reject: "Tolak jika invariant wajib gagal", schema: "Skema ynx.oracle.v1", risk: "Risiko testnet", riskText: "Data dapat terlambat, tidak lengkap, menyimpang, atau tidak tersedia. Konsumen harus gagal dengan aman. Bukan saran atau jaminan harga.", status: "Status", security: "Keamanan", support: "Dukungan", language: "Bahasa", theme: "Tema", light: "Terang", dark: "Gelap", auto: "Sistem", yes: "Ya", no: "Tidak", notReported: "Tidak dilaporkan", failure: "Permintaan gagal" },
};

const languageNames: Record<Lang, string> = { en: "English", "zh-CN": "简体中文", "zh-TW": "繁體中文", ja: "日本語", ko: "한국어", es: "Español", fr: "Français", de: "Deutsch", pt: "Português", ru: "Русский", ar: "العربية", id: "Bahasa Indonesia" };
const apiBase = (process.env.NEXT_PUBLIC_ORACLE_API_BASE_URL ?? "").replace(/\/$/, "");
const types = ["spot_price", "index_price", "mark_price", "funding_reference", "fx", "stablecoin_price", "stablecoin_reserve_ratio", "stablecoin_depeg", "dex_twap", "interest_rate_candidate"];

type Probe = { state: "idle" | "loading" | "connected" | "failed"; health?: Record<string, unknown>; version?: Record<string, unknown>; latency?: number; checkedAt?: Date; error?: string };

export default function OracleConsole() {
  const [lang, setLang] = useState<Lang>("en");
  const [theme, setTheme] = useState("auto");
  const [probe, setProbe] = useState<Probe>({ state: "idle" });
  const [market, setMarket] = useState("");
  const [kind, setKind] = useState("spot_price");
  const [price, setPrice] = useState<Record<string, unknown> | null>(null);
  const [priceError, setPriceError] = useState("");
  const t = messages[lang];
  const formatter = useMemo(() => new Intl.DateTimeFormat(lang, { dateStyle: "medium", timeStyle: "medium" }), [lang]);

  const runProbe = useCallback(async () => {
    if (!apiBase) { setProbe({ state: "idle" }); return; }
    setProbe({ state: "loading" });
    const started = performance.now();
    try {
      const controller = new AbortController();
      const timer = setTimeout(() => controller.abort(), 7000);
      const [healthResponse, versionResponse] = await Promise.all([fetch(`${apiBase}/health`, { signal: controller.signal, cache: "no-store" }), fetch(`${apiBase}/version`, { signal: controller.signal, cache: "no-store" })]);
      clearTimeout(timer);
      if (!healthResponse.ok || !versionResponse.ok) throw new Error(`HTTP ${healthResponse.status}/${versionResponse.status}`);
      const [health, version] = await Promise.all([healthResponse.json(), versionResponse.json()]);
      setProbe({ state: "connected", health, version, latency: Math.round(performance.now() - started), checkedAt: new Date() });
    } catch (error) {
      setProbe({ state: "failed", latency: Math.round(performance.now() - started), checkedAt: new Date(), error: error instanceof Error ? error.message : t.failure });
    }
  }, [t.failure]);

  useEffect(() => { document.documentElement.lang = lang; document.documentElement.dir = lang === "ar" ? "rtl" : "ltr"; }, [lang]);
  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem("ynx-oracle-theme", theme); }, [theme]);
  useEffect(() => { if ("serviceWorker" in navigator) navigator.serviceWorker.register("/sw.js").catch(() => undefined); const timer = window.setTimeout(runProbe, 0); return () => window.clearTimeout(timer); }, [runProbe]);

  async function requestPrice(event: FormEvent) {
    event.preventDefault(); setPrice(null); setPriceError("");
    const normalized = market.trim().toUpperCase();
    if (!apiBase || !normalized) return;
    try {
      const response = await fetch(`${apiBase}/prices?market=${encodeURIComponent(normalized)}&type=${encodeURIComponent(kind)}`, { cache: "no-store" });
      const body = await response.json();
      if (!response.ok) throw new Error(typeof body?.error === "string" ? body.error : `HTTP ${response.status}`);
      setPrice(body);
    } catch (error) { setPriceError(error instanceof Error ? error.message : t.failure); }
  }

  const stateLabel = !apiBase ? t.unconfigured : probe.state === "connected" ? t.connected : probe.state === "failed" ? t.unavailable : t.refresh;
  const quality = price?.quality as Record<string, unknown> | undefined;
  return <main>
    <a className="skip" href="#content">Skip to content</a>
    <header className="topbar"><a className="brand" href="/oracle" aria-label="YNX Oracle"><span className="brandmark">Y</span><span>YNX <b>{t.nav}</b></span></a><div className="controls"><label><span className="sr-only">{t.language}</span><select value={lang} onChange={e => setLang(e.target.value as Lang)}>{Object.entries(languageNames).map(([code, name]) => <option key={code} value={code}>{name}</option>)}</select></label><label><span className="sr-only">{t.theme}</span><select value={theme} onChange={e => setTheme(e.target.value)}><option value="auto">{t.auto}</option><option value="light">{t.light}</option><option value="dark">{t.dark}</option></select></label></div></header>
    <div id="content" className="shell">
      <section className="hero"><p className="eyebrow">{t.eyebrow}</p><h1>{t.title}</h1><p className="lede">{t.intro}</p><div className={`endpoint-state ${probe.state}`}><span className="pulse" aria-hidden="true"/><div><strong>{stateLabel}</strong><small>{t.endpoint}: {apiBase || "—"}</small></div><button onClick={runProbe} disabled={!apiBase || probe.state === "loading"}>{t.refresh}</button></div></section>
      <section className="metrics" aria-label={t.status}><article><span>{t.health}</span><strong>{String(probe.health?.status ?? t.notReported)}</strong><small>{probe.checkedAt ? `${t.lastCheck}: ${formatter.format(probe.checkedAt)}` : t.unconfigured}</small></article><article><span>{t.version}</span><strong>{String(probe.version?.version ?? t.notReported)}</strong><small>{String(probe.version?.schemaVersion ?? "ynx.oracle.v1")}</small></article><article><span>{t.latency}</span><strong>{probe.latency === undefined ? "—" : `${probe.latency} ms`}</strong><small>{probe.error || t.endpoint}</small></article></section>
      <div className="grid">
        <section className="panel query"><div className="panel-head"><div><p className="kicker">01 / LIVE QUERY</p><h2>{t.inspect}</h2></div><span className="tag">GET /prices</span></div><form onSubmit={requestPrice}><label>{t.market}<input value={market} onChange={e => setMarket(e.target.value)} autoComplete="off" spellCheck={false} pattern="[A-Za-z0-9._/-]{3,64}" required /></label><label>{t.dataType}<select value={kind} onChange={e => setKind(e.target.value)}>{types.map(type => <option key={type}>{type}</option>)}</select></label><button type="submit" disabled={!apiBase}>{t.query}</button></form>{priceError && <p role="alert" className="error">{t.failure}: {priceError}</p>}{price ? <div className="result"><div className="result-title"><span>{t.result}</span><code>{String(price.market ?? market.toUpperCase())}</code></div><div className="value">{typeof price.value === "number" ? new Intl.NumberFormat(lang, { maximumFractionDigits: 8 }).format(price.value) : t.notReported}</div><div className="quality-grid"><span>{t.sources}<b>{String(quality?.sourceCount ?? t.notReported)}</b></span><span>{t.confidence}<b>{typeof quality?.confidencePpm === "number" ? `${(quality.confidencePpm / 10000).toFixed(2)}%` : t.notReported}</b></span><span>{t.stale}<b>{typeof quality?.stale === "boolean" ? (quality.stale ? t.yes : t.no) : t.notReported}</b></span><span>{t.circuit}<b>{typeof quality?.circuitBreaker === "boolean" ? (quality.circuitBreaker ? t.yes : t.no) : t.notReported}</b></span></div></div> : <p className="empty">{t.noQuery}</p>}</section>
        <aside className="panel contract"><div className="panel-head"><div><p className="kicker">02 / VALIDATION</p><h2>{t.contract}</h2></div><span className="tag">{t.schema}</span></div><p>{t.contractText}</p><ol><li><i>1</i>schemaVersion + policyVersion</li><li><i>2</i>source + sourceCount + coverage</li><li><i>3</i>asOf + stale + confidence</li><li><i>4</i>failure + circuitBreaker</li></ol><div className="reject"><span>×</span>{t.reject}</div></aside>
      </div>
      <section className="risk"><div><p className="kicker">03 / DISCLOSURE</p><h2>{t.risk}</h2></div><p>{t.riskText}</p></section>
    </div>
    <footer><span>YNX Oracle · {new Date().getFullYear()}</span><span>{t.schema} · {t.risk}</span></footer>
  </main>;
}
