import express, { type Request, type Response } from 'express';
import { isIP } from 'node:net';
import { readFile } from 'node:fs/promises';
import { ipKeyGenerator, rateLimit } from 'express-rate-limit';
import { BoundedRateLimitStore, createAdmissionLayer } from './admission.js';
import { auth, createCsrfToken, createToken, loadUsers, permissionsForRole, requireMutationProtection, requirePermission, verifyUser } from './auth.js';
import { PublicStatusError, PublicStatusReplayGuard, filePublicStatusSource, parsePublicStatusSource, publicStatusFailure, type PublicStatusSource } from './public-status.js';
import { buildP0ConnectivitySnapshot, type P0ConnectivityProbeConfig, type ProbeHistory } from './p0-connectivity.js';
import { IncidentTransitionError, OpsStore } from './store.js';
import type { IncidentAction, Permission, Principal, Role } from './types.js';

interface Probe { id:string; label:string; url:string; status:'healthy'|'unavailable'; checkedAt:string; latencyMs?:number; httpStatus?:number; data?:unknown; errorCode?:'dependency_unavailable' }
const bounded = (value:unknown,limit=240) => String(value ?? '').slice(0,limit);
const evidenceList=(value:unknown)=>Array.isArray(value)?value.slice(0,12).map(item=>bounded(item,500)).filter(Boolean):[];
const isoDate=(value:unknown)=>{const text=bounded(value,80);const millis=Date.parse(text);return text&&Number.isFinite(millis)?new Date(millis).toISOString():undefined;};
const nonNegativeInteger=(value:unknown):value is number=>typeof value==='number'&&Number.isInteger(value)&&value>=0;
const browserSafeText=(value:unknown,limit=500)=>{const text=bounded(value,limit);return /(?:localhost|127\.0\.0\.1|10\.\d+\.\d+\.\d+|192\.168\.\d+\.\d+|172\.(?:1[6-9]|2\d|3[01])\.\d+\.\d+|\/(?:Users|home|var|etc|srv|private|tmp)\/|authorization|bearer|password|private[_ -]?key|api[_ -]?key)/i.test(text)?'redacted-internal-evidence':text;};
const browserSafeValue=(value:unknown,depth=0):unknown=>{if(depth>6)return'redacted-depth-limit';if(typeof value==='string')return browserSafeText(value,2_000);if(Array.isArray(value))return value.slice(0,64).map(item=>browserSafeValue(item,depth+1));if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).slice(0,64).map(([key,item])=>[bounded(key,120),browserSafeValue(item,depth+1)]));return value;};
const browserSafeRecords=(value:unknown)=>Array.isArray(value)?value.slice(0,128).map(item=>browserSafeValue(item)):[];
const directRateLimitKey=(request:Request)=>{const candidate=request.socket.remoteAddress?.replace(/^::ffff:/i,'')??'::';return`ip:${ipKeyGenerator(isIP(candidate)?candidate:'::',56)}`;};
const directRateLimitHandler=(_request:Request,response:Response,_next:unknown,options:{windowMs:number;statusCode:number})=>{const retryAfterSeconds=Math.max(1,Math.ceil(options.windowMs/1_000));response.setHeader('Retry-After',String(retryAfterSeconds));response.status(options.statusCode).json({error:'rate_limited',retryAfterSeconds});};
const incidentActions:readonly IncidentAction[]=['acknowledge','investigate','mitigate','begin_recovery','verify_recovery','reopen'];
const incidentActionPermission=(action:IncidentAction):Permission=>action==='verify_recovery'?'incident:recovery_verify':'incident:manage';
type WalletVerifier=(input:{challengeId:string;nonce:string;origin:string;network:string;chainId:number;signature:string;signedPayload:string})=>Promise<{account:string}>;

async function probe(id:string,label:string,url:string):Promise<Probe>{
  const started=Date.now();const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),2500);
  try{const response=await fetch(url,{signal:controller.signal});const text=await response.text();let data:unknown;try{data=JSON.parse(text);}catch{data=text.slice(0,1000);}return{id,label,url,status:response.ok?'healthy':'unavailable',checkedAt:new Date().toISOString(),latencyMs:Date.now()-started,httpStatus:response.status,data};}
	catch{return{id,label,url,status:'unavailable',checkedAt:new Date().toISOString(),latencyMs:Date.now()-started,errorCode:'dependency_unavailable'};}
  finally{clearTimeout(timeout);}
}

const objectValue=(value:unknown):Record<string,any>=>value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,any>:{};
const safeDependencyStates=(value:unknown)=>Object.fromEntries(Object.entries(objectValue(value)).filter(([id])=>/^[a-z0-9][a-z0-9._:-]{0,79}$/i.test(id)).slice(0,32).map(([id,item])=>[id,{status:bounded(objectValue(item).status,80)||'unknown'}]));
const safeValidator=(value:unknown)=>{const item=objectValue(value);return{address:bounded(item.address,160),moniker:bounded(item.moniker,120),role:bounded(item.role,80),active:Boolean(item.active),peerReady:Boolean(item.peerReady),peerStatus:bounded(item.peerStatus,80),votingPower:nonNegativeInteger(item.votingPower)?item.votingPower:null,latestHeight:nonNegativeInteger(item.latestHeight)?item.latestHeight:null,syncStatus:bounded(item.syncStatus??item.peerStatus,80)||'unknown'};};
function projectProbeData(id:string,value:unknown){
	const data=objectValue(value);
	if(id==='validators')return{validators:(Array.isArray(data.validators)?data.validators:[]).slice(0,16).map(safeValidator)};
	if(id==='peers')return{peers:(Array.isArray(data.peers)?data.peers:[]).slice(0,64).map(safeValidator)};
	if(id==='peer-sync'){const records=Array.isArray(data.peerSync)?data.peerSync:Array.isArray(data.records)?data.records:[];return{records:records.slice(0,64).map(safeValidator)};}
	if(id==='blocks'){const blocks=Array.isArray(data.blocks)?data.blocks:[];return{blocks:blocks.slice(0,25).map((block:unknown)=>{const item=objectValue(block);return{height:nonNegativeInteger(item.height)?item.height:null,hash:bounded(item.hash,160),time:isoDate(item.time),validator:bounded(item.validator,160),transactionCount:Array.isArray(item.transactions)?item.transactions.length:0};})};}
	const build=objectValue(data.build);
	return{ok:data.ok===true,status:bounded(data.status,80),service:bounded(data.service,120),network:bounded(data.network,120),chainId:nonNegativeInteger(data.chainId)?data.chainId:null,nativeSymbol:bounded(data.nativeSymbol??data.nativeCurrencySymbol,20),height:nonNegativeInteger(data.height)?data.height:null,lastIndexedHeight:nonNegativeInteger(data.lastIndexedHeight)?data.lastIndexedHeight:null,lastSourceHeight:nonNegativeInteger(data.lastSourceHeight)?data.lastSourceHeight:null,indexedTxCount:nonNegativeInteger(data.indexedTxCount)?data.indexedTxCount:null,validatorCount:nonNegativeInteger(data.validatorCount)?data.validatorCount:null,startedAt:isoDate(data.startedAt),checkedAt:isoDate(data.checkedAt??data.lastCheckedAt),sourceCommit:bounded(data.sourceCommit??data.commit??build.commit,120)||null,release:bounded(data.release??build.release,120)||null,dependencies:safeDependencyStates(data.dependencies)};
}
function publicProbe(probe:Probe){return{id:probe.id,label:probe.label,status:probe.status,checkedAt:probe.checkedAt,latencyMs:probe.latencyMs,httpStatus:probe.httpStatus,data:projectProbeData(probe.id,probe.data),...(probe.errorCode?{errorCode:probe.errorCode}:{})};}
function networkProjection(probes:Probe[]){
	const find=(id:string)=>probes.find(probe=>probe.id===id);
	const nodeProbe=find('node'),indexerProbe=find('indexer');
	const node=objectValue(nodeProbe?.data),indexer=objectValue(indexerProbe?.data);
	const validatorsRaw=objectValue(find('validators')?.data),validators=(Array.isArray(validatorsRaw.validators)?validatorsRaw.validators:[]).slice(0,16).map(safeValidator);
	const peersRaw=objectValue(find('peers')?.data),peers=Array.isArray(peersRaw.peers)?peersRaw.peers:[];
	const blocksRaw=objectValue(find('blocks')?.data),blocks=(Array.isArray(blocksRaw.blocks)?blocksRaw.blocks:[]).filter((value:unknown)=>isoDate(objectValue(value).time));
	let blockIntervalSeconds:null|number=null,tps:null|number=null;
	if(blocks.length>=2){const newest=Date.parse(String(objectValue(blocks[0]).time)),oldest=Date.parse(String(objectValue(blocks[blocks.length-1]).time)),duration=Math.max(0,(newest-oldest)/1000);if(duration>0){blockIntervalSeconds=duration/(blocks.length-1);tps=blocks.reduce((total:number,value:unknown)=>total+(Array.isArray(objectValue(value).transactions)?objectValue(value).transactions.length:0),0)/duration;}}
	const canonicalHeight=nonNegativeInteger(node.height)?node.height:null,indexedHeight=nonNegativeInteger(indexer.lastIndexedHeight)?indexer.lastIndexedHeight:null;
	const finalityAvailable=nodeProbe?.status==='healthy'&&indexerProbe?.status==='healthy'&&indexer.ok===true&&canonicalHeight!==null&&indexedHeight!==null&&indexedHeight<=canonicalHeight;
	return{expectedValidatorCount:4,observedValidatorCount:validators.length,validatorSetStatus:validators.length===4?'complete':'degraded',canonicalHeight,indexedHeight,indexLag:canonicalHeight!==null&&indexedHeight!==null?Math.max(0,canonicalHeight-indexedHeight):null,finality:{status:finalityAvailable?'canonical-indexed':'unavailable',height:finalityAvailable?indexedHeight:null},blockIntervalSeconds,tps,peerCount:peers.length,validators,consensus:{streamBFT:{status:'shadow/candidate',active:false,statement:'StreamBFT remains a shadow/candidate and is not reported as active consensus.'}}};
}
function browserIncidents(incidents:ReturnType<OpsStore['snapshot']>['incidents']){return incidents.map(incident=>({...incident,source:browserSafeText(incident.source,160),evidence:incident.evidence.map(value=>browserSafeText(value)),notes:incident.notes.map(value=>browserSafeText(value,1000)),timeline:incident.timeline.map(entry=>({...entry,summary:browserSafeText(entry.summary,1000),evidence:entry.evidence.map(value=>browserSafeText(value))}))}));}
function browserAlerts(alerts:ReturnType<OpsStore['snapshot']>['alerts']){return alerts.map(alert=>({...alert,reason:browserSafeText(alert.reason,500),evidenceUrl:'/ops/overview'}));}

export async function createApp(options:{store?:OpsStore;secret?:string;integrityKey?:string;rpcUrl?:string;explorerUrl?:string;indexerUrl?:string;faucetUrl?:string;gatewayUrl?:string;aiUrl?:string;users?:ReturnType<typeof loadUsers>;walletVerifier?:WalletVerifier;walletRoles?:Record<string,Role>;walletOrigin?:string;allowedOrigins?:string[];automationTargets?:string[];publicStatusSource?:PublicStatusSource|null;publicStatusMaxAgeSeconds?:number;publicStatusIntegrityKey?:string;publicStatusExpectedSource?:string;p0ConnectivityProbes?:P0ConnectivityProbeConfig[];trustedProxyAddresses?:string[]}={}){
  const secret=options.secret??process.env.YNX_MONITOR_SESSION_SECRET;if(!secret||secret.length<24)throw new Error('YNX_MONITOR_SESSION_SECRET must contain at least 24 characters');
  const users=options.users??loadUsers();const integrityKey=options.integrityKey??process.env.YNX_MONITOR_STATE_INTEGRITY_KEY;if(!options.store&&(!integrityKey||integrityKey.length<32))throw new Error('YNX_MONITOR_STATE_INTEGRITY_KEY must contain at least 32 characters');const store=options.store??new OpsStore(process.env.YNX_MONITOR_STATE_PATH||'tmp/monitor/state.json',integrityKey!);await store.load();
  const rpc=(options.rpcUrl??process.env.YNX_MONITOR_RPC_URL??'http://127.0.0.1:6420').replace(/\/$/,'');
  const explorer=(options.explorerUrl??process.env.YNX_MONITOR_EXPLORER_URL??'http://127.0.0.1:6427').replace(/\/$/,'');
  const indexer=(options.indexerUrl??process.env.YNX_MONITOR_INDEXER_URL??'http://127.0.0.1:6426').replace(/\/$/,'');
	const faucet=(options.faucetUrl??process.env.YNX_MONITOR_FAUCET_URL??'http://127.0.0.1:6428').replace(/\/$/,'');
	const gateway=(options.gatewayUrl??process.env.YNX_MONITOR_GATEWAY_URL??'http://127.0.0.1:6437').replace(/\/$/,'');
  const ai=(options.aiUrl??process.env.YNX_MONITOR_AI_URL??'http://127.0.0.1:6429').replace(/\/$/,'');
  const logSources:Record<string,string>=process.env.YNX_MONITOR_LOG_SOURCES?JSON.parse(process.env.YNX_MONITOR_LOG_SOURCES):{};
  const walletOrigin=options.walletOrigin??process.env.YNX_MONITOR_PUBLIC_ORIGIN??'http://127.0.0.1:4674';
  const configuredOrigins=process.env.YNX_MONITOR_ALLOWED_ORIGINS?.split(',').map(value=>value.trim()).filter(Boolean);
  const allowedOrigins=options.allowedOrigins??configuredOrigins??[walletOrigin];
  const automationTargets=[...new Set(options.automationTargets??process.env.YNX_MONITOR_AUTOMATION_TARGETS?.split(',').map(value=>value.trim()).filter(Boolean)??[])].filter(value=>/^[a-z0-9][a-z0-9._:-]{0,119}$/i.test(value)).sort();
  const walletRoles=options.walletRoles??(process.env.YNX_MONITOR_WALLET_ROLES?JSON.parse(process.env.YNX_MONITOR_WALLET_ROLES):{});
  const publicStatusPath=process.env.YNX_MONITOR_PUBLIC_STATUS_PATH?.trim();
  const publicStatusSource=options.publicStatusSource===null?undefined:options.publicStatusSource??(publicStatusPath?filePublicStatusSource(publicStatusPath):undefined);
  const configuredPublicStatusMaxAge=Number(process.env.YNX_MONITOR_PUBLIC_STATUS_MAX_AGE_SECONDS??300);
  const publicStatusMaxAgeSeconds=options.publicStatusMaxAgeSeconds??configuredPublicStatusMaxAge;
  if(!Number.isInteger(publicStatusMaxAgeSeconds)||publicStatusMaxAgeSeconds<30||publicStatusMaxAgeSeconds>86_400)throw new Error('YNX_MONITOR_PUBLIC_STATUS_MAX_AGE_SECONDS must be an integer between 30 and 86400');
  const publicStatusIntegrityKey=options.publicStatusIntegrityKey??process.env.YNX_MONITOR_PUBLIC_STATUS_INTEGRITY_KEY;
  if(publicStatusSource&&(!publicStatusIntegrityKey||publicStatusIntegrityKey.length<32))throw new Error('YNX_MONITOR_PUBLIC_STATUS_INTEGRITY_KEY must contain at least 32 characters when public status is configured');
  const publicStatusExpectedSource=options.publicStatusExpectedSource??process.env.YNX_MONITOR_PUBLIC_STATUS_EXPECTED_SOURCE;
  if(publicStatusSource&&(!publicStatusExpectedSource||!/^[a-z0-9][a-z0-9._:-]{0,119}$/i.test(publicStatusExpectedSource)))throw new Error('YNX_MONITOR_PUBLIC_STATUS_EXPECTED_SOURCE must identify the approved publisher when public status is configured');
  const publicStatusReplayGuard=new PublicStatusReplayGuard();
  const configuredP0ConnectivityProbes=options.p0ConnectivityProbes??(process.env.YNX_MONITOR_P0_CONNECTIVITY_PROBES?JSON.parse(process.env.YNX_MONITOR_P0_CONNECTIVITY_PROBES) as P0ConnectivityProbeConfig[]:[]);
  if(!Array.isArray(configuredP0ConnectivityProbes))throw new Error('YNX_MONITOR_P0_CONNECTIVITY_PROBES must be a JSON array');
  const p0ConnectivityHistory:ProbeHistory=new Map();
  const walletVerifier=options.walletVerifier??(process.env.YNX_MONITOR_WALLET_AUTH_URL?async(input)=>{const response=await fetch(process.env.YNX_MONITOR_WALLET_AUTH_URL!,{method:'POST',headers:{'content-type':'application/json',...(process.env.YNX_MONITOR_WALLET_AUTH_KEY?{'x-ynx-gateway-key':process.env.YNX_MONITOR_WALLET_AUTH_KEY}:{})},body:JSON.stringify(input)});if(!response.ok)throw new Error('wallet_gateway_rejected');const body=await response.json() as {account?:string};if(!body.account)throw new Error('wallet_gateway_invalid_response');return{account:body.account};}:undefined);
  const configuredTrustedProxyAddresses=process.env.YNX_MONITOR_TRUSTED_PROXY_ADDRESSES?.split(',').map(value=>value.trim()).filter(Boolean)??[];
  const admission=createAdmissionLayer({trustedProxyAddresses:options.trustedProxyAddresses??configuredTrustedProxyAddresses});
  const startedAt=new Date().toISOString();
  const app=express();app.disable('x-powered-by');app.set('trust proxy',false);app.use(express.json({limit:'128kb'}));
  app.get('/health',...admission.public,(_req,res)=>res.json({status:'available',scope:'monitor-control-plane-process',stateLoaded:true,startedAt,checkedAt:new Date().toISOString()}));
  app.get('/version',...admission.public,(_req,res)=>res.json({schemaVersion:'ynx.monitor.version.v1',service:'ynx-monitor-control-plane',contractVersion:'ynx.monitor.integration.v1',commit:process.env.YNX_MONITOR_SOURCE_COMMIT||null,release:process.env.YNX_MONITOR_RELEASE||null,startedAt}));
  app.get('/connectivity',...admission.public,async(_req,res)=>{res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');try{return res.json(await buildP0ConnectivitySnapshot(configuredP0ConnectivityProbes,{history:p0ConnectivityHistory}));}catch{return res.status(503).json({schemaVersion:'ynx.monitor.p0-connectivity.v1',availability:'unavailable',error:'connectivity_probe_configuration_invalid',servedAt:new Date().toISOString()});}});
  app.get('/status',...admission.public,async(_req,res)=>{res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');if(!publicStatusSource)return res.status(503).json(publicStatusFailure('public_status_unavailable'));try{const snapshot=publicStatusReplayGuard.accept(parsePublicStatusSource(await publicStatusSource(),{maxAgeSeconds:publicStatusMaxAgeSeconds,integrityKey:publicStatusIntegrityKey!,expectedSource:publicStatusExpectedSource!}));return res.json({...snapshot,servedAt:new Date().toISOString()});}catch(error){const code=error instanceof PublicStatusError?error.code:'public_status_unavailable';return res.status(503).json(publicStatusFailure(code));}});
  const sessionResponse=(principal:Principal)=>{const token=createToken(principal,secret);return{token,csrfToken:createCsrfToken(token,secret),principal,permissions:permissionsForRole(principal.role),expiresIn:3600};};
  app.post('/ops/login',...admission.authentication,async(req,res)=>{if(!users.length)return res.status(503).json({error:'password_login_not_configured'});const principal=verifyUser(users,bounded(req.body?.username,80),bounded(req.body?.password,200));if(!principal)return res.status(401).json({error:'invalid_credentials'});await store.audit(principal,'session.login','monitor','authenticated');return res.json(sessionResponse(principal));});
  app.post('/ops/wallet/challenges',...admission.authentication,async(req,res)=>{if(!walletVerifier)return res.status(503).json({error:'wallet_gateway_not_configured'});const accountHint=bounded(req.body?.accountHint,160)||undefined;const{challenge,nonce}=await store.createWalletChallenge(walletOrigin,accountHint);return res.status(201).json({challengeId:challenge.id,nonce,origin:challenge.origin,network:'ynx_6423-1',chainId:6423,purpose:'Sign in to YNX Monitor',issuedAt:challenge.issuedAt,expiresAt:challenge.expiresAt});});
  app.post('/ops/wallet/sessions',...admission.authentication,async(req,res)=>{if(!walletVerifier)return res.status(503).json({error:'wallet_gateway_not_configured'});const challengeId=bounded(req.body?.challengeId,100),nonce=bounded(req.body?.nonce,200),signature=bounded(req.body?.signature,2000),signedPayload=bounded(req.body?.signedPayload,4000);if(!challengeId||!nonce||!signature||!signedPayload)return res.status(400).json({error:'signed_challenge_required'});const challenge=await store.consumeWalletChallenge(challengeId,nonce);if(!challenge)return res.status(409).json({error:'challenge_invalid_expired_or_replayed'});try{const verified=await walletVerifier({challengeId,nonce,origin:challenge.origin,network:'ynx_6423-1',chainId:6423,signature,signedPayload});const role=walletRoles[verified.account];if(!role)return res.status(403).json({error:'wallet_not_authorized'});const principal={username:`wallet:${verified.account}`,role};await store.audit(principal,'session.wallet_login','monitor','authenticated',{account:verified.account,challengeId});return res.json(sessionResponse(principal));}catch{return res.status(401).json({error:'wallet_signature_rejected'});}});
  app.use('/ops',rateLimit({identifier:'monitor-ops-ip',limit:240,windowMs:60_000,standardHeaders:'draft-8',legacyHeaders:false,passOnStoreError:false,store:new BoundedRateLimitStore({windowMs:60_000}),keyGenerator:directRateLimitKey,handler:directRateLimitHandler}),auth(secret),...admission.operator,...admission.sensitive);
  app.use('/ops',requireMutationProtection(secret,allowedOrigins));
  app.get('/ops/me',(req,res)=>res.json({principal:req.principal,permissions:permissionsForRole(req.principal!.role)}));
  app.get('/ops/overview',async(req,res)=>{
	const probes=await Promise.all([probe('node','RPC / chain status',`${rpc}/status`),probe('identity','Release identity',`${rpc}/node/identity`),probe('validators','Validators',`${rpc}/validators`),probe('peers','Peers',`${rpc}/validators/peers`),probe('peer-sync','Peer sync',`${rpc}/validators/peer-sync`),probe('blocks','Canonical indexed blocks',`${indexer}/blocks/latest?limit=12`),probe('explorer','Explorer',`${explorer}/health`),probe('indexer','Indexer',`${indexer}/health`),probe('faucet','Faucet',`${faucet}/health`),probe('gateway','Gateway',`${gateway}/health`)]);
	for(const item of probes){if(item.status==='healthy')await store.observeRecovery(item.id);else await store.observeFailure(item.id,item.errorCode||`HTTP ${item.httpStatus}`,item.url);}
    const state=store.snapshot();
	res.setHeader('Cache-Control','no-store');return res.json({checkedAt:new Date().toISOString(),probes:probes.map(publicProbe),network:networkProjection(probes),slo:{definition:'Current bounded endpoint availability only; no historical uptime is inferred.',passing:probes.filter(p=>p.status==='healthy').length,total:probes.length},incidents:browserIncidents(state.incidents),alerts:browserAlerts(state.alerts),rollbackProposals:browserSafeRecords(state.rollbackProposals),automationProposals:browserSafeRecords(state.automationProposals),backupRecords:browserSafeRecords(state.backupRecords),restoreDrills:browserSafeRecords(state.restoreDrills)});
  });
  app.get('/ops/audit',(req,res)=>res.json({audit:store.snapshot().audits}));
  app.get('/ops/automation-policy',(_req,res)=>res.json({targets:automationTargets,allowedActions:['pause','resume'],maxPauseSeconds:900,proposalTtlSeconds:300,executionBoundary:'central infrastructure owner',authorityBoundary:'pause-or-resume-only; no asset movement or authority expansion'}));
  app.get('/ops/automation-proposals',(_req,res)=>res.json({proposals:store.snapshot().automationProposals}));
	app.get('/ops/logs',rateLimit({identifier:'monitor-logs-ip',limit:120,windowMs:60_000,standardHeaders:'draft-8',legacyHeaders:false,passOnStoreError:false,store:new BoundedRateLimitStore({windowMs:60_000}),keyGenerator:directRateLimitKey,handler:directRateLimitHandler}),async(req,res)=>{const names=Object.keys(logSources).sort();const source=bounded(req.query.source,80);if(!source)return res.json({status:names.length?'sources_available':'not_configured',sources:names,lines:[]});const path=logSources[source];if(!path)return res.status(404).json({error:'log_source_not_allowed'});try{const raw=await readFile(path);const tail=raw.subarray(Math.max(0,raw.length-65_536)).toString('utf8');const lines=tail.split(/\r?\n/).slice(-200).map(line=>browserSafeText(line.slice(0,2_000).replace(/(authorization:\s*bearer|x-ynx-[\w-]*-key[=:]?|password[=:]?|private[_ -]?key[=:]?)\s*\S+/gi,'$1 [REDACTED]'),2_000));await store.audit(req.principal!,'logs.read',source,'read',{bytes:Math.min(raw.length,65_536),lines:lines.length});return res.json({status:'available',source,sources:names,lines,truncated:raw.length>65_536,fetchedAt:new Date().toISOString()});}catch{return res.status(502).json({error:'log_source_unavailable'})}});
  app.post('/ops/incidents',requirePermission('incident:create'),async(req,res)=>{const title=bounded(req.body?.title,160),source=bounded(req.body?.source,160),severity=req.body?.severity,evidence=evidenceList(req.body?.evidence);if(!title||!source||!['low','medium','high','critical'].includes(severity))return res.status(400).json({error:'invalid_incident'});return res.status(201).json(await store.createIncident(req.principal!,{title,source,severity,evidence}));});
  app.post('/ops/incidents/:id/assign',requirePermission('incident:manage'),async(req,res)=>{const owner=bounded(req.body?.owner,120),evidence=evidenceList(req.body?.evidence);if(!owner)return res.status(400).json({error:'incident_owner_required'});const result=await store.assignIncident(req.principal!,String(req.params.id),owner,evidence);return result?res.json(result):res.status(404).json({error:'incident_not_found'});});
  app.post('/ops/incidents/:id/notes',requirePermission('incident:manage'),async(req,res)=>{const summary=bounded(req.body?.summary,1000),evidence=evidenceList(req.body?.evidence);if(!summary)return res.status(400).json({error:'incident_note_required'});const incident=await store.addIncidentNote(req.principal!,String(req.params.id),summary,evidence);return incident?res.json({incident}):res.status(404).json({error:'incident_not_found'});});
  app.post('/ops/incidents/:id/actions/:action',async(req,res)=>{const action=String(req.params.action) as IncidentAction;if(!incidentActions.includes(action))return res.status(400).json({error:'unsupported_incident_action'});const requiredPermission=incidentActionPermission(action);if(!permissionsForRole(req.principal!.role).includes(requiredPermission))return res.status(403).json({error:'permission_required',requiredPermission});const summary=bounded(req.body?.summary,1000),evidence=evidenceList(req.body?.evidence);if(!summary)return res.status(400).json({error:'incident_transition_summary_required'});try{const result=await store.transitionIncident(req.principal!,String(req.params.id),action,summary,evidence);return result?res.json(result):res.status(404).json({error:'incident_not_found'});}catch(error){if(error instanceof IncidentTransitionError)return res.status(409).json({error:error.message,action:error.action,currentStatus:error.status});if(error instanceof Error&&error.message==='recovery_evidence_required')return res.status(400).json({error:error.message});throw error;}});
  app.post('/ops/incidents/:id/postmortem',requirePermission('incident:postmortem'),async(req,res)=>{const summary=bounded(req.body?.summary,2000),rootCause=bounded(req.body?.rootCause,2000),correctiveActions=Array.isArray(req.body?.correctiveActions)?req.body.correctiveActions.slice(0,20).map((item:unknown)=>bounded(item,500)).filter(Boolean):[],evidence=evidenceList(req.body?.evidence);if(!summary||!rootCause||!correctiveActions.length||!evidence.length)return res.status(400).json({error:'complete_postmortem_required'});try{const result=await store.completePostmortem(req.principal!,String(req.params.id),{summary,rootCause,correctiveActions,evidence});return result?res.json(result):res.status(404).json({error:'incident_not_found'});}catch(error){if(error instanceof IncidentTransitionError)return res.status(409).json({error:error.message,action:error.action,currentStatus:error.status});throw error;}});
  app.get('/ops/incidents/:id/export',(req,res)=>{const incident=store.exportIncident(String(req.params.id));if(!incident)return res.status(404).json({error:'incident_not_found'});res.setHeader('Cache-Control','no-store');return res.json({schemaVersion:'ynx.monitor.incident-export.v1',exportedAt:new Date().toISOString(),incident});});
  app.post('/ops/alerts/:id/acknowledge',requirePermission('alert:acknowledge'),async(req,res)=>{if(req.body?.approvalPhrase!=='ACKNOWLEDGE')return res.status(409).json({error:'explicit_operator_approval_required',requiredPhrase:'ACKNOWLEDGE'});const alert=await store.acknowledge(req.principal!,String(req.params.id));return alert?res.json(alert):res.status(404).json({error:'alert_not_found'});});
  app.post('/ops/backups',requirePermission('backup:record'),async(req,res)=>{
    const kind=bounded(req.body?.kind,40),service=bounded(req.body?.service,120),artifactRef=bounded(req.body?.artifactRef,500),digest=bounded(req.body?.digest,128).toLowerCase(),createdAt=isoDate(req.body?.createdAt),retentionClass=bounded(req.body?.retentionClass,80),retentionUntil=isoDate(req.body?.retentionUntil),storageLocation=bounded(req.body?.storageLocation,500),encryption=req.body?.encryption,rpoTargetSeconds=req.body?.rpoTargetSeconds,rtoTargetSeconds=req.body?.rtoTargetSeconds,sizeBytes=req.body?.sizeBytes,evidence=evidenceList(req.body?.evidence);
    if(!['state','database','configuration','release','other'].includes(kind)||!service||!artifactRef||!/^[a-f0-9]{64}$/.test(digest)||!nonNegativeInteger(sizeBytes)||!createdAt||!retentionClass||!retentionUntil||Date.parse(retentionUntil)<Date.parse(createdAt)||!storageLocation||!['encrypted','unknown'].includes(encryption)||!nonNegativeInteger(rpoTargetSeconds)||!nonNegativeInteger(rtoTargetSeconds)||!evidence.length)return res.status(400).json({error:'invalid_backup_record'});
    return res.status(201).json(await store.registerBackup(req.principal!,{kind:kind as 'state'|'database'|'configuration'|'release'|'other',service,artifactRef,digestAlgorithm:'sha256',digest,sizeBytes,createdAt,retentionClass,retentionUntil,storageLocation,encryption:encryption as 'encrypted'|'unknown',rpoTargetSeconds,rtoTargetSeconds,evidence}));
  });
  app.post('/ops/backups/:id/verify',rateLimit({identifier:'monitor-backup-verify-ip',limit:30,windowMs:60_000,standardHeaders:'draft-8',legacyHeaders:false,passOnStoreError:false,store:new BoundedRateLimitStore({windowMs:60_000}),keyGenerator:directRateLimitKey,handler:directRateLimitHandler}),requirePermission('backup:verify'),async(req,res)=>{
    const result=req.body?.result,digestMatch=req.body?.digestMatch,accessible=req.body?.accessible,evidence=evidenceList(req.body?.evidence),notes=bounded(req.body?.notes,1000);
    if(!['verified','rejected'].includes(result)||typeof digestMatch!=='boolean'||typeof accessible!=='boolean')return res.status(400).json({error:'invalid_backup_verification'});
    try{const verification=await store.verifyBackup(req.principal!,String(req.params.id),{result,digestMatch,accessible,evidence,notes});return verification?res.json(verification):res.status(404).json({error:'backup_not_found'});}catch(error){const code=error instanceof Error?error.message:'backup_verification_failed';return res.status(code==='backup_verification_already_final'||code==='independent_backup_verifier_required'?409:400).json({error:code});}
  });
  app.post('/ops/restore-drills',requirePermission('backup:record'),async(req,res)=>{
    const backupId=bounded(req.body?.backupId,120),environment=bounded(req.body?.environment,120),startedAt=isoDate(req.body?.startedAt),completedAt=isoDate(req.body?.completedAt),reportedResult=req.body?.reportedResult,rpoObservedSeconds=req.body?.rpoObservedSeconds,rtoObservedSeconds=req.body?.rtoObservedSeconds,integrityVerified=req.body?.integrityVerified,applicationVerified=req.body?.applicationVerified,evidence=evidenceList(req.body?.evidence),failureReason=bounded(req.body?.failureReason,1000)||undefined;
    if(!backupId||!environment||!startedAt||!completedAt||Date.parse(completedAt)<Date.parse(startedAt)||!['passed','failed'].includes(reportedResult)||!nonNegativeInteger(rpoObservedSeconds)||!nonNegativeInteger(rtoObservedSeconds)||typeof integrityVerified!=='boolean'||typeof applicationVerified!=='boolean')return res.status(400).json({error:'invalid_restore_drill'});
    try{const drill=await store.recordRestoreDrill(req.principal!,{backupId,environment,startedAt,completedAt,reportedResult,rpoObservedSeconds,rtoObservedSeconds,integrityVerified,applicationVerified,evidence,...(failureReason?{failureReason}:{})});return drill?res.status(201).json(drill):res.status(404).json({error:'backup_not_found'});}catch(error){return res.status(400).json({error:error instanceof Error?error.message:'restore_drill_failed'});}
  });
  app.post('/ops/restore-drills/:id/verify',rateLimit({identifier:'monitor-restore-verify-ip',limit:30,windowMs:60_000,standardHeaders:'draft-8',legacyHeaders:false,passOnStoreError:false,store:new BoundedRateLimitStore({windowMs:60_000}),keyGenerator:directRateLimitKey,handler:directRateLimitHandler}),requirePermission('backup:verify'),async(req,res)=>{
    const result=req.body?.result,evidence=evidenceList(req.body?.evidence),notes=bounded(req.body?.notes,1000);
    if(!['accepted','rejected'].includes(result))return res.status(400).json({error:'invalid_restore_verification'});
    try{const verification=await store.verifyRestoreDrill(req.principal!,String(req.params.id),{result,evidence,notes});return verification?res.json(verification):res.status(404).json({error:'restore_drill_not_found'});}catch(error){const code=error instanceof Error?error.message:'restore_verification_failed';return res.status(['restore_verification_already_final','independent_restore_verifier_required','backup_not_verified'].includes(code)?409:400).json({error:code});}
  });
  app.post('/ops/backup-records',requirePermission('backup:record'),async(req,res)=>{const evidence=bounded(req.body?.evidence,500);if(!evidence)return res.status(400).json({error:'backup_evidence_required'});return res.status(201).json(await store.addBackupRecord(req.principal!,evidence));});
  app.post('/ops/rollback-proposals',requirePermission('rollback:propose'),async(req,res)=>{if(req.body?.approvalPhrase!=='APPROVE ROLLBACK PROPOSAL')return res.status(409).json({error:'explicit_operator_approval_required',requiredPhrase:'APPROVE ROLLBACK PROPOSAL'});const candidateRelease=bounded(req.body?.candidateRelease??req.body?.release,120),previousRelease=bounded(req.body?.previousRelease,120)||undefined,reason=bounded(req.body?.reason,500),dryRunEvidence=evidenceList(req.body?.dryRunEvidence);if(!candidateRelease||!reason)return res.status(400).json({error:'release_and_reason_required'});return res.status(201).json(await store.addRollbackProposal(req.principal!,candidateRelease,reason,previousRelease,dryRunEvidence));});
  app.post('/ops/rollback-proposals/:id/verify',rateLimit({identifier:'monitor-rollback-verify-ip',limit:30,windowMs:60_000,standardHeaders:'draft-8',legacyHeaders:false,passOnStoreError:false,store:new BoundedRateLimitStore({windowMs:60_000}),keyGenerator:directRateLimitKey,handler:directRateLimitHandler}),requirePermission('rollback:verify'),async(req,res)=>{const result=req.body?.result,evidence=evidenceList(req.body?.evidence),notes=bounded(req.body?.notes,1000);if(!['verified','rejected'].includes(result))return res.status(400).json({error:'invalid_rollback_verification'});try{const verification=await store.verifyRollbackProposal(req.principal!,String(req.params.id),{result,evidence,notes});return verification?res.json(verification):res.status(404).json({error:'rollback_proposal_not_found'});}catch(error){const code=error instanceof Error?error.message:'rollback_verification_failed';return res.status(['rollback_verification_already_final','independent_rollback_verifier_required'].includes(code)?409:400).json({error:code});}});
  app.post('/ops/automation-proposals',requirePermission('automation:propose'),async(req,res)=>{
    const action=req.body?.action,target=bounded(req.body?.target,120),reason=bounded(req.body?.reason,500),evidence=evidenceList(req.body?.evidence),maxPauseSeconds=req.body?.maxPauseSeconds,pauseProposalId=bounded(req.body?.pauseProposalId,120)||undefined;
    if(!['pause','resume'].includes(action)||!target||!reason||!evidence.length)return res.status(400).json({error:'invalid_automation_proposal'});
    if(!automationTargets.includes(target))return res.status(403).json({error:'automation_target_not_preapproved'});
    if(action==='pause'&&(!Number.isInteger(maxPauseSeconds)||maxPauseSeconds<1||maxPauseSeconds>900))return res.status(400).json({error:'bounded_pause_duration_required',maxPauseSeconds:900});
    if(action==='resume'&&!pauseProposalId)return res.status(400).json({error:'pause_proposal_id_required'});
    if(req.body?.approvalPhrase!==`PROPOSE ${String(action).toUpperCase()} ${target}`)return res.status(409).json({error:'explicit_operator_approval_required',requiredPhrase:`PROPOSE ${String(action).toUpperCase()} ${target}`});
    try{return res.status(201).json(await store.addAutomationProposal(req.principal!,{action:action as 'pause'|'resume',target,reason,evidence,...(action==='pause'?{maxPauseSeconds}:{pauseProposalId})}));}
    catch(error){return res.status(409).json({error:error instanceof Error?error.message:'automation_proposal_failed'});}
  });
  app.post('/ops/automation-proposals/:id/review',requirePermission('automation:review'),async(req,res)=>{
    const decision=req.body?.decision,evidence=evidenceList(req.body?.evidence),notes=bounded(req.body?.notes,1000);
    if(!['approved','rejected'].includes(decision)||req.body?.approvalPhrase!==`REVIEW AUTOMATION ${String(decision).toUpperCase()}`)return res.status(409).json({error:'explicit_reviewer_approval_required',requiredPhrase:`REVIEW AUTOMATION ${String(decision).toUpperCase()}`});
    try{const result=await store.reviewAutomationProposal(req.principal!,String(req.params.id),{decision:decision as 'approved'|'rejected',evidence,notes});return result?res.json(result):res.status(404).json({error:'automation_proposal_not_found'});}
    catch(error){const code=error instanceof Error?error.message:'automation_review_failed';return res.status(['independent_automation_reviewer_required','automation_review_already_final','automation_proposal_expired','approved_pause_proposal_required'].includes(code)?409:400).json({error:code});}
  });
  app.post('/ops/incidents/:id/ai',async(req:Request,res:Response)=>{const incident=store.snapshot().incidents.find(x=>x.id===String(req.params.id));if(!incident)return res.status(404).json({error:'incident_not_found'});const context={id:incident.id,title:incident.title,severity:incident.severity,status:incident.status,source:incident.source,evidence:incident.evidence};const key=process.env.YNX_MONITOR_AI_KEY;if(!key)return res.status(503).json({error:'ai_gateway_not_configured'});const language=bounded(req.body?.language,80)||'English';await store.audit(req.principal!,'incident.ai_summary',incident.id,'requested',{contextFields:Object.keys(context),authority:'advisory-only',language});const prompt=`Respond in ${language}. Summarize this incident using only the cited evidence and propose numbered runbook steps. Do not acknowledge alerts, restart services, rotate keys, execute rollback, mutate operations state, or claim an action happened. Evidence: ${JSON.stringify(context)}`;const upstream=await fetch(`${ai}/ai/stream?session=${encodeURIComponent(`monitor-${incident.id}`)}&q=${encodeURIComponent(prompt)}`,{headers:{'X-YNX-AI-Key':key}});res.status(upstream.status);for(const [name,value] of upstream.headers)if(['content-type','cache-control'].includes(name))res.setHeader(name,value);if(!upstream.body)return res.end();const reader=upstream.body.getReader();while(true){const{done,value}=await reader.read();if(done)break;res.write(Buffer.from(value));}res.end();});
  app.use((_req,res)=>res.status(404).json({error:'not_found'}));
  return app;
}
