import assert from "node:assert/strict";
import { createServer } from "node:http";
import test from "node:test";
import { createChainService } from "../src/service.mjs";

const status={chainId:6423,nativeCurrencySymbol:"YNXT",network:"YNX Testnet",publicNetwork:true,height:42};
async function fixture(t){const calls=[],fetcher=async(url,options={})=>{calls.push([String(url),options]);if(String(url).endsWith("/status"))return response(status);if(String(url).endsWith("/txs/0x"+"a".repeat(64)))return response({hash:`0x${"a".repeat(64)}`,height:41});if(String(url).includes("/blocks/"))return response({height:41});if(String(url).endsWith("/ide/compiler"))return response({version:"0.8.24"});const body=JSON.parse(options.body),result=body.method==="eth_chainId"?"0x1917":body.method==="eth_getTransactionReceipt"?{transactionHash:body.params[0],status:"0x1",blockNumber:"0x29"}:body.method==="eth_getTransactionByHash"?{hash:body.params[0],from:"0x"+"1".repeat(40),to:"0x"+"2".repeat(40)}:{number:"0x29"};return response({jsonrpc:"2.0",id:body.id,result})},service=createChainService({ownerForRequest:request=>request.headers["x-owner"],upstreamURL:"https://rpc.ynxweb4.com",fetcher}),server=createServer((request,response)=>service.handler(request,response).then(handled=>{if(!handled)response.writeHead(404).end()}));await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));t.after(()=>new Promise(resolve=>server.close(resolve)));return{base:`http://127.0.0.1:${server.address().port}`,calls}}
function response(value,statusCode=200){return new Response(JSON.stringify(value),{status:statusCode,headers:{"content-type":"application/json"}})}
async function call(base,path,options={}){const response=await fetch(`${base}${path}`,{...options,headers:{"x-owner":"owner-a",...(options.body?{"content-type":"application/json"}:{}),...options.headers}});return{response,value:await response.json()}}
test("status and bounded read-only RPC verify canonical YNX Testnet identity",async t=>{const{base}=await fixture(t),live=await call(base,"/runtime/chain/status");assert.equal(live.response.status,200);assert.equal(live.value.status.chainId,6423);const rpc=await call(base,"/runtime/chain/rpc",{method:"POST",body:JSON.stringify({protocolVersion:"ynx-code-chain/v1",method:"eth_chainId",params:[]})});assert.equal(rpc.value.result,"0x1917");const rejected=await call(base,"/runtime/chain/rpc",{method:"POST",body:JSON.stringify({protocolVersion:"ynx-code-chain/v1",method:"eth_sendTransaction",params:[]})});assert.equal(rejected.response.status,400);assert.equal(rejected.value.code,"rpc_method_not_allowed")});
test("transaction debugger joins REST record, EVM transaction and authoritative receipt",async t=>{const{base}=await fixture(t),hash=`0x${"a".repeat(64)}`,value=await call(base,`/runtime/chain/transactions/${hash}`);assert.equal(value.response.status,200);assert.equal(value.value.record.height,41);assert.equal(value.value.transaction.hash,hash);assert.equal(value.value.receipt.status,"0x1");assert.equal(value.value.confirmed,true)});
test("chain routes require a signed owner and reject non-canonical identity",async t=>{const{base}=await fixture(t),unauthorized=await fetch(`${base}/runtime/chain/status`);assert.equal(unauthorized.status,401);const service=createChainService({ownerForRequest:()=>"owner",upstreamURL:"http://127.0.0.1:6420",fetcher:async()=>response({...status,chainId:1})}),server=createServer((request,response)=>service.handler(request,response));await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));t.after(()=>new Promise(resolve=>server.close(resolve)));const mismatch=await fetch(`http://127.0.0.1:${server.address().port}/runtime/chain/status`);assert.equal(mismatch.status,502);assert.equal((await mismatch.json()).code,"chain_identity_mismatch")});
