import { expect, test, type Page } from "@playwright/test";
import { mkdir } from "node:fs/promises";
import path from "node:path";

const token0="0x0000000000000000000000000000000000000001";
const token1="0x0000000000000000000000000000000000000002";
const pool="0x0000000000000000000000000000000000000011";

async function liveFixture(page:Page){
 await page.route("**/v1/**",async route=>{const path=new URL(route.request().url()).pathname;let body:unknown;if(path==="/v1/tokens")body={items:[{chainId:6423,address:token0,symbol:"T0",name:"Test Zero",decimals:18,standard:"ERC-20",reviewStatus:"owner-reviewed-testnet"},{chainId:6423,address:token1,symbol:"T1",name:"Test One",decimals:18,standard:"ERC-20",reviewStatus:"owner-reviewed-testnet"}],source:"owner-reviewed Testnet token list",chainId:6423,mainnet:false};else if(path==="/v1/pools")body={items:[{address:pool,token0,token1,reserve0:"1000000000000000000000",reserve1:"2000000000000000000000",contractVersion:"ynx-dex-cpmm-v1",updatedBlock:17,updatedAt:"2026-07-18T00:00:00Z"}],source:"indexed YNX Testnet EVM events"};else if(path==="/v1/transactions")body={items:[],source:"indexed YNX Testnet EVM events"};else if(path==="/v1/prices"||path==="/v1/twap"||path==="/v1/fees")body={items:[],source:"indexed raw amounts"};else body={source:"YNX Testnet EVM events",indexedEvents:2,pools:1,swaps:0,liquidityEvents:1,latestBlock:17};await route.fulfill({status:200,contentType:"application/json",body:JSON.stringify(body)})});
}

test("quotes indexed reserves, reviews risk, and fails closed at Wallet",async({page})=>{await liveFixture(page);await page.goto("/");await page.getByLabel("You pay amount").fill("1");await expect(page.getByText("Deterministic quote from current indexed reserves.")).toBeVisible();await expect(page.getByLabel("You receive amount")).toHaveValue(/1\.99/);await page.getByRole("button",{name:"Review swap"}).click();const review=page.getByRole("dialog",{name:"Review swap"});await expect(review.getByText(/Minimum received/)).toBeVisible();await expect(review.getByRole("button",{name:"Continue in YNX Wallet"})).toBeDisabled()});

test("opens pool detail and exposes add/remove liquidity without signing",async({page})=>{await liveFixture(page);await page.goto("/#pools");await page.getByRole("button",{name:"T0 / T1"}).click();const detail=page.getByRole("dialog",{name:"T0 / T1"});await expect(detail.getByText(pool)).toBeVisible();await detail.getByRole("tab",{name:"Remove liquidity"}).click();await expect(detail.getByRole("button",{name:"Review remove liquidity"})).toBeDisabled();await expect(detail.getByText(/registry is not integrated/)).toBeVisible()});

test("AI workflow previews context and reports unavailable provider honestly",async({page})=>{await liveFixture(page);await page.goto("/");await page.getByLabel("You pay amount").fill("1");await page.getByRole("button",{name:"Explain risk with AI"}).click();const dialog=page.getByRole("dialog",{name:"AI risk explanation"});await expect(dialog.getByText("1. Select context")).toBeVisible();await expect(dialog.getByText(/Provider unavailable/)).toBeVisible();await expect(dialog.getByRole("button",{name:"Request explanation"})).toBeDisabled();await expect(dialog.getByText(/Audit chain: verified/)).toBeVisible()});

test("mobile layout has no horizontal overflow and keeps primary tabs reachable",async({page},testInfo)=>{test.skip(!testInfo.project.name.startsWith("mobile"),"mobile project only");await liveFixture(page);await page.goto("/");const widths=await page.evaluate(()=>({client:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth}));expect(widths.scroll).toBe(widths.client);await page.getByRole("navigation",{name:"Mobile navigation"}).getByRole("button",{name:"Pools"}).click();await expect(page.getByRole("heading",{name:"Pools"})).toBeVisible()});

test("installed service worker cold-reloads the shell offline",async({page,context})=>{test.skip(page.context().browser()?.browserType().name()!=="chromium","Chromium service worker evidence");await liveFixture(page);await page.goto("/");await page.waitForFunction(()=>navigator.serviceWorker?.ready);await page.reload();await page.waitForFunction(()=>Boolean(navigator.serviceWorker?.controller));await context.setOffline(true);await page.reload({waitUntil:"domcontentloaded"});await expect(page.getByRole("heading",{name:"Swap"})).toBeVisible();await expect(page.getByText(/Offline/)).toBeVisible()});

test("captures explicitly labelled fixture, tablet, large-text, loading, and failure evidence",async({page,browser},testInfo)=>{test.skip(!testInfo.project.name.startsWith("desktop"),"single visual evidence project");const directory=path.resolve("../../docs/evidence/dex/ui");await mkdir(directory,{recursive:true});await liveFixture(page);await page.setViewportSize({width:1024,height:768});await page.goto("/#pools");await expect(page.getByRole("heading",{name:"Pools"})).toBeVisible();await page.screenshot({path:path.join(directory,"tablet-live-fixture-1024x768.png"),fullPage:true});await page.setViewportSize({width:1440,height:900});await page.goto("/");await page.getByLabel("You pay amount").fill("1");await expect(page.getByText("Deterministic quote from current indexed reserves.")).toBeVisible();await page.screenshot({path:path.join(directory,"success-indexed-fixture-1440x900.png"),fullPage:true});const largeContext=await browser.newContext({viewport:{width:960,height:600},deviceScaleFactor:1.5});const largePage=await largeContext.newPage();await liveFixture(largePage);await largePage.goto("/");await largePage.getByLabel("You pay amount").fill("1");await expect(largePage.getByText("Deterministic quote from current indexed reserves.")).toBeVisible();expect(await largePage.evaluate(()=>document.documentElement.scrollWidth)).toBe(await largePage.evaluate(()=>document.documentElement.clientWidth));await largePage.screenshot({path:path.join(directory,"large-text-fixture-1440x900.png"),fullPage:false});await largeContext.close();await page.unroute("**/v1/**");await page.route("**/v1/**",async route=>{await new Promise(resolve=>setTimeout(resolve,5_000));await route.fulfill({status:200,contentType:"application/json",body:"{}"})});await page.goto("/");await page.screenshot({path:path.join(directory,"loading-1440x900.png"),fullPage:true});await page.unroute("**/v1/**");await page.route("**/v1/**",route=>route.fulfill({status:503,contentType:"application/json",body:'{"error":"unavailable"}'}));await page.goto("/");await expect(page.getByRole("alert")).toBeVisible();await page.screenshot({path:path.join(directory,"api-failure-1440x900.png"),fullPage:true})});
