export const supported=['en','zh-CN','zh-TW','ja','ko','es','fr','de','pt','ru','ar','id'];
const rows={en:['Language','AI output language','Unavailable','Security verification failed','Offline. No success is simulated.'],'zh-CN':['语言','AI 输出语言','不可用','安全验证失败','当前离线，不会模拟成功。'],'zh-TW':['語言','AI 輸出語言','無法使用','安全驗證失敗','目前離線，不會模擬成功。'],ja:['言語','AI出力言語','利用不可','セキュリティ検証に失敗しました','オフラインです。成功を装いません。'],ko:['언어','AI 출력 언어','사용 불가','보안 검증에 실패했습니다','오프라인입니다. 성공을 가장하지 않습니다.'],es:['Idioma','Idioma de salida de IA','No disponible','Falló la verificación de seguridad','Sin conexión. No se simula el éxito.'],fr:['Langue','Langue de sortie IA','Indisponible','La vérification de sécurité a échoué','Hors ligne. Aucun succès n’est simulé.'],de:['Sprache','KI-Ausgabesprache','Nicht verfügbar','Sicherheitsprüfung fehlgeschlagen','Offline. Erfolg wird nicht simuliert.'],pt:['Idioma','Idioma de saída da IA','Indisponível','Falha na verificação de segurança','Offline. Nenhum sucesso é simulado.'],ru:['Язык','Язык ответа ИИ','Недоступно','Проверка безопасности не пройдена','Нет сети. Успех не имитируется.'],ar:['اللغة','لغة مخرجات الذكاء الاصطناعي','غير متاح','فشل التحقق الأمني','غير متصل. لا تتم محاكاة النجاح.'],id:['Bahasa','Bahasa keluaran AI','Tidak tersedia','Verifikasi keamanan gagal','Luring. Keberhasilan tidak disimulasikan.']};
const keys=['language','aiLanguage','unavailable','securityError','offline'];export const messages=Object.fromEntries(supported.map(c=>[c,Object.fromEntries(keys.map((k,i)=>[k,rows[c][i]]))]));
const normalize=v=>v?.startsWith('zh-Hant')||v==='zh-TW'?'zh-TW':v?.startsWith('zh')?'zh-CN':supported.find(c=>v?.toLowerCase().startsWith(c.toLowerCase()))||'en';
let language=normalize(localStorage.getItem('ynx-ui-language')||navigator.language),aiLanguage=normalize(localStorage.getItem('ynx-ai-language')||language);
export const t=k=>messages[language]?.[k]||messages.en[k]||k;export const outputLanguage=()=>aiLanguage;
export const formatAmount=v=>new Intl.NumberFormat(language,{maximumFractionDigits:8}).format(v);export const formatDate=v=>new Intl.DateTimeFormat(language,{dateStyle:'medium',timeStyle:'short'}).format(new Date(v));export const plural=(n,one,many)=>new Intl.PluralRules(language).select(n)==='one'?one:many;
const chooser=(id,label,current,change)=>{const wrap=document.createElement('label');wrap.className='language-control';wrap.textContent=label+' ';const select=document.createElement('select');select.id=id;select.setAttribute('aria-label',label);supported.forEach(c=>select.add(new Option(c,c,false,c===current)));select.onchange=()=>change(select.value);wrap.append(select);return wrap};
export function installI18n(){document.documentElement.lang=language;document.documentElement.dir=language==='ar'?'rtl':'ltr';const host=document.querySelector('header')||document.body;host.append(chooser('uiLanguage',t('language'),language,v=>{localStorage.setItem('ynx-ui-language',v);location.reload()}));host.append(chooser('aiLanguage',t('aiLanguage'),aiLanguage,v=>{aiLanguage=v;localStorage.setItem('ynx-ai-language',v)}));}
