import test from 'node:test';import assert from 'node:assert/strict';import {runNativeInstallCommand} from '../scripts/native-zfs-install.mjs';
const options={shell:false,env:{PATH:'/safe',LD_LIBRARY_PATH:'/reviewed/lib'},timeout:30000,maxBuffer:262144};
test('actual noninteractive child receives empty stdin EOF before doing work',async()=>{
  const script="let bytes=0;process.stdin.on('data',x=>bytes+=x.length);process.stdin.on('end',()=>{console.log(JSON.stringify({eof:true,bytes,argument:process.argv[1],language:process.env.LANG}));});";
  const actual={shell:false,env:{LANG:'C'},timeout:1000,maxBuffer:262144};
  const result=await runNativeInstallCommand(process.execPath,['-e',script,'exact-argument'],actual);
  assert.deepEqual(JSON.parse(result.stdout),{eof:true,bytes:0,argument:'exact-argument',language:'C'});
  assert.equal(result.stderr,'');
  assert.deepEqual(actual,{shell:false,env:{LANG:'C'},timeout:1000,maxBuffer:262144});
});
test('fixed child diagnostics preserve failure without retaining secrets or changing command budget',async()=>{const error=Object.assign(new Error('private error'),{code:1,stderr:'Error: permission denied token=do-not-record /private/customer',signal:null,killed:false});let seen;await assert.rejects(runNativeInstallCommand('/snap/bin/lxc',['storage','create','ynx-core-quota','zfs','size=64GiB'],options,{now:()=>123,runner:async(...args)=>{seen=args;throw error}}),e=>e===error);assert.deepEqual(seen,['/snap/bin/lxc',['storage','create','ynx-core-quota','zfs','size=64GiB'],options]);assert.equal(error.nativeInstallDiagnostic.phase,'lxd-storage-create');assert.equal(error.nativeInstallDiagnostic.exitCode,1);assert.deepEqual(error.nativeInstallDiagnostic.stderrMarkers,['permission-denied']);assert.equal(error.nativeInstallDiagnostic.timeoutMs,30000);assert(!JSON.stringify(error.nativeInstallDiagnostic).includes('do-not-record'));assert(!JSON.stringify(error.nativeInstallDiagnostic).includes('customer'));});
test('actual timeout elapsed and signal are retained without retrying the child',async()=>{const error=Object.assign(new Error('timeout'),{code:null,signal:'SIGTERM',killed:true,stderr:''});let calls=0,t=0;await assert.rejects(runNativeInstallCommand('/snap/bin/lxc',['storage','create'],options,{now:()=>t,runner:async()=>{calls++;t=30049;throw error}}));assert.equal(calls,1);assert.equal(error.nativeInstallDiagnostic.elapsedMs,30049);assert.equal(error.nativeInstallDiagnostic.signal,'SIGTERM');assert.equal(error.nativeInstallDiagnostic.killed,true);assert.equal(error.nativeInstallDiagnostic.timeoutMs,30000);});
test('loader and absent-tool diagnostics use only bounded enum markers',async()=>{const error=Object.assign(new Error('not-found'),{code:'ENOENT',stderr:'error while loading shared libraries: private-library not found\n'+('x'.repeat(300000))});await assert.rejects(runNativeInstallCommand('/snap/lxd/40958/zfs-2.2/bin/zpool',['list'],options,{runner:async()=>{throw error}}));const d=error.nativeInstallDiagnostic;assert.equal(d.phase,'zpool-list');assert.equal(d.errorCode,'ENOENT');assert.equal(d.stderrTruncated,true);assert(d.stderrBytes<=262144);assert.deepEqual(d.stderrMarkers,['shared-library-unavailable','not-found']);});
test('successful child result and exact protected options remain unchanged',async()=>{const expected={stdout:'result',stderr:''};assert.equal(await runNativeInstallCommand('/usr/bin/id',['-u','ubuntu'],options,{runner:async(exe,args,opts)=>{assert.equal(opts,options);return expected}}),expected);});
