package com.ynxweb4.music;

import android.content.Context;
import android.content.Intent;
import android.net.Uri;
import android.os.Handler;
import android.os.Looper;
import android.webkit.*;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.Instant;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicLong;

// The engine loads only pinned packaged source. No port is available to remote
// content, arbitrary navigation, Intent JSON or a second app-selected authority.
final class NativeSessionBridge {
 static final String GATEWAY="https://wallet-auth.ynxweb4.com",ENGINE="https://music-native.ynx.invalid/native-session/";
 static final String SOURCE_SHA="07d4cab47a6a3bd964d7ec59cb1d9bbf441fa34cf52cd8d6a129a1d005de0480";
 static final String SDK_SHA="e0147cf9f324f4eca8f98f7ca3a154d1cfe130fbb072314924ceb57441048575";
 interface Result {void done(JSONObject value,Exception error);}
 private final Context context;private final Handler main=new Handler(Looper.getMainLooper());private final AtomicLong revision=new AtomicLong();
 private final ConcurrentHashMap<String,Waiter> pending=new ConcurrentHashMap<>();private final CompletableFuture<Void> ready=new CompletableFuture<>();
 private final NativeProtectedRuntime runtime;private final WebView engine;private final JSONObject registry;
 private volatile NativeSessionIdentity active;private volatile boolean denied=true,closed;private final java.util.concurrent.CopyOnWriteArrayList<Runnable> listeners=new java.util.concurrent.CopyOnWriteArrayList<>();
 private static final class Waiter{final long revision;final String method;final CompletableFuture<JSONObject> result=new CompletableFuture<>();Waiter(long revision,String method){this.revision=revision;this.method=method;}}
 private NativeSessionBridge(Context context){this.context=context;NativeProtectedRuntime ports=null;WebView view=null;JSONObject registrations=null;try{if(Looper.myLooper()!=Looper.getMainLooper())throw new SecurityException("Native engine must be created on UI thread");byte[] sdk=asset("wallet-auth-native-consumer.mjs");if(!SDK_SHA.equals(hex(MessageDigest.getInstance("SHA-256").digest(sdk))))throw new SecurityException("Pinned Native SDK bytes changed");verifyAssets();registrations=new JSONObject(new String(asset("registry.json"),StandardCharsets.UTF_8));ports=new NativeProtectedRuntime(context);view=new WebView(context);WebSettings settings=view.getSettings();settings.setJavaScriptEnabled(true);settings.setAllowFileAccess(false);settings.setAllowContentAccess(false);settings.setDomStorageEnabled(false);settings.setJavaScriptCanOpenWindowsAutomatically(false);settings.setSupportMultipleWindows(false);settings.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);view.setWebViewClient(new WebViewClient(){@Override public WebResourceResponse shouldInterceptRequest(WebView view,WebResourceRequest request){try{Uri url=request.getUrl();String name=url.getLastPathSegment();if(!request.getMethod().equals("GET")||!url.toString().equals(ENGINE+name)||!MusicIO.set("index.html","client.mjs","media-native-consumer.mjs","wallet-auth-native-consumer.mjs").contains(name))return blocked();return new WebResourceResponse(name.endsWith("html")?"text/html":"text/javascript","utf-8",new ByteArrayInputStream(asset(name)));}catch(Exception failure){return blocked();}}@Override public boolean shouldOverrideUrlLoading(WebView view,WebResourceRequest request){return !request.getUrl().toString().equals(ENGINE+"index.html");}});view.addJavascriptInterface(new Ports(),"NativePorts");}catch(Exception failure){ready.completeExceptionally(failure);}runtime=ports;engine=view;registry=registrations;if(engine!=null){engine.loadUrl(ENGINE+"index.html");main.postDelayed(()->{if(!ready.isDone())ready.completeExceptionally(new IOException("Native engine initialization timed out"));},15000);}}
 private static NativeSessionBridge shared;
 static synchronized NativeSessionBridge acquire(Context context){if(shared==null||shared.closed)shared=new NativeSessionBridge(context.getApplicationContext());return shared;}
 void addListener(Runnable listener){listeners.add(listener);}
 void removeListener(Runnable listener){listeners.remove(listener);}
 long epoch(){return revision.get();}
 NativeSessionIdentity session(){NativeSessionIdentity value=active;try{return !closed&&!denied&&value!=null&&value.expiresAt.isAfter(Instant.now())&&value.contextMatches(runtime.readContext())?value:null;}catch(Exception unavailable){return null;}}
 void connect(Result result){active=null;denied=false;revision.incrementAndGet();notifyChanged();perform("connect",new JSONObject(),result);}
 void restore(Result result){active=null;denied=false;revision.incrementAndGet();notifyChanged();perform("restore",new JSONObject(),result);}
 void handleReturn(String url,Result result){try{if(url==null||url.length()>16384)throw new SecurityException("Bounded original callback required");active=null;denied=false;revision.incrementAndGet();notifyChanged();perform("handleReturn",new JSONObject().put("url",url),result);}catch(Exception failure){result.done(null,failure);}}
 void disconnect(Result result){active=null;denied=true;revision.incrementAndGet();notifyChanged();try{if(runtime==null)throw new SecurityException("Original protected runtime unavailable");runtime.requestCurrentRevocation();perform("disconnect",new JSONObject(),result);}catch(Exception error){result.done(null,error);}}
 void rejected(NativeSessionIdentity original)throws Exception{NativeSessionIdentity current=active;if(current!=null&&current.same(original))disconnect((value,error)->{});}
 JSONObject proof(String method,String path,String digest,long size,NativeSessionIdentity expected)throws Exception{
  if(Looper.myLooper()==Looper.getMainLooper())throw new SecurityException("Private proof cannot block UI thread");
  if(expected==null||!expected.same(session())||!expected.contextMatches(runtime.readContext()))throw new SecurityException("Same original native account required");
  long requestEpoch=revision.get();JSONObject args=new JSONObject().put("method",method).put("path",path).put("bodyDigest",digest).put("bodyBytes",size);
  JSONObject result=invoke("prepareRequest",args).get(35,TimeUnit.SECONDS);
  if(requestEpoch!=revision.get()||!expected.same(session())||!expected.contextMatches(runtime.readContext())||!digest.equals(result.getString("bodyDigest"))||size!=result.getLong("bodyBytes")||!expected.account.equals(result.getString("account"))||!expected.binding.equals(result.getString("sessionBinding")))throw new SecurityException("Original Music request retired");
  for(String name:new String[]{"identityHeader","actionHeader"})if(!result.getString(name).matches("[A-Za-z0-9_-]{32,32768}"))throw new SecurityException("Original SDK proof required");return result;
 }
 private void perform(String method,JSONObject args,Result result){invoke(method,args).whenComplete((value,error)->main.post(()->{if(!closed)result.done(value,error==null?null:exception(error));}));}
 private CompletableFuture<JSONObject> invoke(String method,JSONObject args){long epoch=revision.get();CompletableFuture<JSONObject> result=new CompletableFuture<>();ready.whenComplete((ignored,error)->{if(error!=null){result.completeExceptionally(error);return;}main.post(()->{if(closed||engine==null||epoch!=revision.get()){result.completeExceptionally(new SecurityException("Native operation retired"));return;}String id=UUID.randomUUID().toString();Waiter waiter=new Waiter(epoch,method);pending.put(id,waiter);waiter.result.whenComplete((value,failure)->{if(failure!=null)result.completeExceptionally(failure);else result.complete(value);});engine.evaluateJavascript("NativeClient.dispatch("+JSONObject.quote(id)+","+JSONObject.quote(method)+","+args.toString()+")",null);main.postDelayed(()->{Waiter expired=pending.remove(id);if(expired!=null)expired.result.completeExceptionally(new IOException("Native SDK operation remains unresolved"));},35000);});});return result;}
 void close(){closed=true;if(expiryCheck!=null)main.removeCallbacks(expiryCheck);denied=true;active=null;revision.incrementAndGet();for(Waiter waiter:pending.values())waiter.result.completeExceptionally(new SecurityException("Native engine closed"));pending.clear();if(engine!=null){engine.removeJavascriptInterface("NativePorts");engine.stopLoading();engine.destroy();}}
 private Runnable expiryCheck;
 private void scheduleExpiry(NativeSessionIdentity original){main.post(()->{if(closed||active!=original)return;if(expiryCheck!=null)main.removeCallbacks(expiryCheck);expiryCheck=new Runnable(){public void run(){if(closed||active!=original)return;long remaining=java.time.Duration.between(Instant.now(),original.expiresAt).toMillis();if(remaining>0){main.postDelayed(this,remaining+1);return;}denied=true;active=null;revision.incrementAndGet();notifyChanged();}};main.postDelayed(expiryCheck,Math.max(1,java.time.Duration.between(Instant.now(),original.expiresAt).toMillis()+1));});}
 private void notifyChanged(){main.post(()->{if(!closed)for(Runnable listener:listeners)listener.run();});}
 private byte[] asset(String name)throws Exception{try(InputStream input=context.getAssets().open("native-session/"+name)){return bounded(input,2_097_152);}}
 private static WebResourceResponse blocked(){return new WebResourceResponse("text/plain","utf-8",403,"Blocked",java.util.Collections.singletonMap("Cache-Control","no-store"),new ByteArrayInputStream(new byte[0]));}
 private final class Ports {
  @JavascriptInterface public String invoke(String method,String raw){try{if(closed||runtime==null||raw.length()>2_097_152)throw new SecurityException("Protected Native engine unavailable");JSONObject args=new JSONObject(raw);Object value;switch(method){case "config":value=new JSONObject().put("gateway",GATEWAY).put("registry",registry).put("purpose","Explicit YNX Music private account, library, playback and creator access");break;case "readContext":value=runtime.readContext();break;case "randomBytes":value=Base64.getUrlEncoder().withoutPadding().encodeToString(runtime.randomBytes(args.getInt("length")));break;case "walletDetected":value=context.getPackageManager().resolveActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("ynxwallet://authorize")),0)!=null;break;case "fetch":value=fetch(args);break;case "sign":value=runtime.sign(args.getJSONObject("input"),args.getJSONObject("expected"),denied);break;case "openWallet":{final long launchEpoch=revision.get();if(denied)throw new SecurityException("Native launch cancelled");value=runtime.openWallet(args.getJSONObject("input"),args.getJSONObject("expected"),()->{if(closed||denied||launchEpoch!=revision.get())throw new SecurityException("Original Wallet launch retired");return null;}).get(15,TimeUnit.SECONDS);break;}case "get":value=runtime.get(args.getString("namespace"),args.getString("key"),args.getJSONObject("expected"));break;case "set":runtime.set(args.getString("namespace"),args.getString("key"),args.getString("value"),args.getJSONObject("expected"));value=null;break;case "remove":runtime.remove(args.getString("namespace"),args.getString("key"),args.getJSONObject("expected"));value=null;break;case "requestRevocation":denied=true;active=null;runtime.requestRevocation(args.getString("namespace"),args.getJSONObject("expected"));notifyChanged();value=null;break;case "revocationRequested":value=runtime.revocationRequested(args.getString("namespace"),args.getJSONObject("expected"));break;case "saveRevocationIntent":value=runtime.saveRevocationIntent(args.getString("namespace"),args.getString("key"),args.getString("raw"),args.getJSONObject("expected"));break;case "finishRevocationIntent":runtime.finishRevocationIntent(args.getString("namespace"),args.getString("key"),args.getString("raw"),args.getJSONObject("expected"));value=null;break;default:throw new SecurityException("Unknown protected Native port");}return new JSONObject().put("ok",true).put("value",value==null?JSONObject.NULL:value).toString();}catch(Exception failure){return "{\"ok\":false,\"code\":\"NATIVE_PORT_REJECTED\",\"message\":\"Original Native context or operation unavailable\"}";}}
  @JavascriptInterface public void complete(String id,String raw){Waiter captured=null;try{if(closed||raw.length()>131072)return;JSONObject response=new JSONObject(raw);if(id.equals("ready")){if(response.optBoolean("ok"))ready.complete(null);else ready.completeExceptionally(new SecurityException("Native SDK boot failed"));return;}Waiter waiter=pending.remove(id);captured=waiter;if(waiter==null)return;if(waiter.revision!=revision.get()){waiter.result.completeExceptionally(new SecurityException("Native result belongs to retired operation"));return;}JSONObject wrapper=response.optJSONObject("state");if(wrapper!=null){JSONObject state=wrapper.optJSONObject("state");if(!denied&&wrapper.optBoolean("businessVerified")&&state!=null&&"connected".equals(state.optString("status"))){active=new NativeSessionIdentity(state.getJSONObject("session"),runtime.readContext());scheduleExpiry(active);}else active=null;notifyChanged();}
 if(!response.getBoolean("ok")){waiter.result.completeExceptionally(new IOException(response.optString("code","NATIVE_SDK_FAILED")));return;}Object value=response.opt("value");waiter.result.complete(value instanceof JSONObject?(JSONObject)value:new JSONObject());}catch(Exception failure){Waiter waiter=captured!=null?captured:pending.remove(id);if(waiter!=null){waiter.result.completeExceptionally(failure);if(waiter.revision==revision.get()){active=null;notifyChanged();}}}}
 }
 private void verifyAssets()throws Exception{
  byte[] manifestBytes=asset("source.json");if(!SOURCE_SHA.equals(hex(MessageDigest.getInstance("SHA-256").digest(manifestBytes))))throw new SecurityException("Original complete engine source manifest changed");JSONObject manifest=new JSONObject(new String(manifestBytes,StandardCharsets.UTF_8));if(!"5c5e8a234206e306b6044deb6e938c1763ac7005".equals(manifest.getString("sdkSourceCommit"))||!SDK_SHA.equals(manifest.getString("sdkArtifactSHA256")))throw new SecurityException("Approved Media Native source required");
  org.json.JSONArray files=manifest.getJSONArray("files");if(files.length()!=5)throw new SecurityException("Complete original engine assets required");
  Set<String> seen=new HashSet<>();for(int i=0;i<files.length();i++){JSONObject pin=files.getJSONObject(i);String name=pin.getString("path");if(!seen.add(name))throw new SecurityException("Duplicate engine asset");if(!MusicIO.set("index.html","client.mjs","media-native-consumer.mjs","wallet-auth-native-consumer.mjs","registry.json").contains(name))throw new SecurityException("Unexpected engine asset");byte[] bytes=asset(name);if(bytes.length!=pin.getInt("bytes")||!hex(MessageDigest.getInstance("SHA-256").digest(bytes)).equals(pin.getString("sha256")))throw new SecurityException("Frozen engine input changed");}
 }
 private JSONObject fetch(JSONObject args)throws Exception{String method=args.getString("method");URL url=new URL(args.getString("url"));String path=url.getPath();boolean gateway=url.toString().equals(GATEWAY+path)&&url.getQuery()==null&&url.getRef()==null&&(method.equals("GET")&&path.equals("/v2/product-sessions/time")||method.equals("POST")&&MusicIO.set("/v2/product-sessions/challenge","/v2/product-sessions/complete","/v2/product-sessions/introspect","/v2/product-sessions/revoke").contains(path));
 boolean account=method.equals("GET")&&url.toString().equals(BuildConfig.DEFAULT_API+"/api/me");if(!gateway&&!account)throw new SecurityException("Original approved Gateway or Music account read required");HttpURLConnection connection=(HttpURLConnection)url.openConnection();try{connection.setInstanceFollowRedirects(false);connection.setConnectTimeout(8000);connection.setReadTimeout(15000);connection.setRequestMethod(method);JSONObject headers=args.getJSONObject("headers");Iterator<String> keys=headers.keys();while(keys.hasNext()){String key=keys.next();if(!MusicIO.set("accept","content-type","x-request-id","x-ynx-product-session-proof-v2","x-ynx-music-business-proof-v2").contains(key.toLowerCase(Locale.ROOT)))throw new SecurityException("Original Gateway headers required");connection.setRequestProperty(key,headers.getString(key));}String body=args.isNull("body")?"":args.getString("body");byte[] bytes=body.getBytes(StandardCharsets.UTF_8);if(bytes.length>1_048_576||method.equals("GET")&&!body.isEmpty())throw new SecurityException("Bounded exact Gateway body required");if(method.equals("POST")){connection.setDoOutput(true);connection.setFixedLengthStreamingMode(bytes.length);try(OutputStream output=connection.getOutputStream()){output.write(bytes);}}int status=connection.getResponseCode();InputStream input=status>=200&&status<300?connection.getInputStream():connection.getErrorStream();JSONObject responseHeaders=new JSONObject();for(String name:new String[]{"content-type","x-request-id","cache-control","content-length"}){String value=connection.getHeaderField(name);if(value!=null)responseHeaders.put(name,value);}return new JSONObject().put("status",status).put("headers",responseHeaders).put("body",input==null?"":new String(bounded(input,1_048_576),StandardCharsets.UTF_8));}finally{connection.disconnect();}}
 private static byte[] bounded(InputStream input,int limit)throws Exception{try(input;ByteArrayOutputStream output=new ByteArrayOutputStream()){byte[] bytes=new byte[8192];int count,total=0;while((count=input.read(bytes))!=-1){total+=count;if(total>limit)throw new IOException("Native response exceeds limit");output.write(bytes,0,count);}return output.toByteArray();}}
 private static Exception exception(Throwable error){while(error.getCause()!=null&&(error instanceof CompletionException||error instanceof ExecutionException))error=error.getCause();return error instanceof Exception?(Exception)error:new IOException("Native private session failed",error);}
 private static String hex(byte[] bytes){StringBuilder result=new StringBuilder();for(byte value:bytes)result.append(String.format(Locale.ROOT,"%02x",value&255));return result.toString();}
}
