package com.ynxweb4.music;

import org.json.JSONArray;
import org.json.JSONObject;
import java.nio.charset.StandardCharsets;
import java.nio.charset.CodingErrorAction;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

// Adapted from verified Commerce f4f5fad structure; Music tuple/scopes match
// A native artifact source5c/complete641. This is protected metadata, not an
// account vault or authority. Persistence must retain original ciphertext on failure.
// Owner implementation of the adopted SDK's protected storage/context ports.
// A single acknowledged encrypted write publishes context and namespace changes.
final class NativeProductState {
    interface Persistence {String read()throws Exception;void write(String value)throws Exception;}
    interface Action<T> {T run()throws Exception;}
    interface Signer {String sign(byte[] bytes)throws Exception;}
    private final Persistence persistence;
    private JSONObject state;
    private boolean poisoned;
    static final String APP="com.ynxweb4.music",ROOT="ynx.product-session.v2:music:android:"+APP;
    NativeProductState(Persistence persistence,String deviceId,String deviceKey,String securityLevel)throws Exception{
        this.persistence=persistence;String saved=persistence.read();
        if(saved.isEmpty()){JSONObject context=new JSONObject().put("platform","android").put("applicationId",APP).put("deviceId",deviceId).put("deviceKey",deviceKey).put("securityLevel",securityLevel).put("generation",1L).put("account",JSONObject.NULL);validateContext(context);JSONObject initial=new JSONObject().put("context",context).put("namespaces",new JSONObject());persist(initial);}
        else{JSONObject restored=new JSONObject(saved);validateState(restored);JSONObject context=restored.getJSONObject("context");if(!deviceKey.equals(context.getString("deviceKey"))||!securityLevel.equals(context.getString("securityLevel")))throw new SecurityException("Preserve original native key/context; device changed");state=restored;}
    }
    synchronized JSONObject context()throws Exception{if(poisoned)throw new SecurityException("Native persistence result is unconfirmed");return new JSONObject(state.getJSONObject("context").toString());}
    synchronized String sign(JSONObject input,JSONObject expected,boolean revokeOnly,Signer signer)throws Exception{return withExpected(expected,()->{byte[] bytes=signBytes(input,expected);boolean negative=revokeOnly;JSONObject namespaces=state.getJSONObject("namespaces");for(String name:keys(namespaces)){JSONObject box=namespaces.getJSONObject(name);if(canonical(box.getJSONObject("context")).equals(canonical(expected))&&box.getBoolean("revocationRequested"))negative=true;}if(negative){String prefix="YNX_PRODUCT_SESSION_HTTP_PROOF_V2\n",text=new String(bytes,StandardCharsets.UTF_8);if(!"http-proof".equals(input.getString("purpose"))||!text.startsWith(prefix))throw new SecurityException("Only original-target revocation may sign during logout");JSONObject proof=new JSONObject(text.substring(prefix.length()));if(!"POST".equals(proof.getString("method"))||!"/v2/product-sessions/revoke".equals(proof.getString("path"))||!shaHex("{}").equals(proof.getString("bodyDigest")))throw new SecurityException("Original revoke route/body required");boolean original=false;for(String name:keys(namespaces)){JSONObject box=namespaces.getJSONObject(name);if(!canonical(box.getJSONObject("context")).equals(canonical(expected)))continue;String raw=nullable(box.getJSONObject("values"),ROOT+":revoke");if(raw==null)continue;JSONObject pending=intent(raw,expected);if(pending.isNull("session"))continue;JSONObject target=pending.getJSONObject("session");if(target.getString("sessionBinding").equals(proof.getString("sessionBinding"))&&target.getString("account").equals(proof.getString("account")))original=true;}if(!original)throw new SecurityException("Persisted original revoke target required");}return signer.sign(bytes);});}
    synchronized void requestCurrentRevocation(JSONObject expected)throws Exception{withExpected(expected,()->{JSONObject next=copy(),all=next.getJSONObject("namespaces");boolean changed=false;for(String namespace:keys(all)){JSONObject box=all.getJSONObject(namespace);if(canonical(box.getJSONObject("context")).equals(canonical(expected))){box.put("revocationRequested",true);changed=true;}}if(changed)persist(next);return null;});}
    private static String shaHex(String text)throws Exception{byte[] hash=java.security.MessageDigest.getInstance("SHA-256").digest(text.getBytes(StandardCharsets.UTF_8));StringBuilder value=new StringBuilder();for(byte b:hash)value.append(String.format(java.util.Locale.ROOT,"%02x",b&255));return value.toString();}
    synchronized <T>T withSigningExpected(JSONObject expected,Action<T> action)throws Exception{return withExpected(expected,()->{JSONObject all=state.getJSONObject("namespaces");for(String namespace:keys(all)){JSONObject box=all.getJSONObject(namespace);if(canonical(box.getJSONObject("context")).equals(canonical(expected))&&box.getBoolean("revocationRequested"))throw new SecurityException("Original native revocation is pending");}return action.run();});}
    synchronized <T>T withExpected(JSONObject expected,Action<T> action)throws Exception{if(poisoned)throw new SecurityException("Native persistence result is unconfirmed");validateContext(expected);if(!canonical(expected).equals(canonical(state.getJSONObject("context"))))throw new SecurityException("Native context changed");return action.run();}
    // Only the owner controller's real account-selection event calls this port.
    // Account selection is public context, never private authorization.
    synchronized void selectAccount(String account)throws Exception{if(poisoned)throw new SecurityException("Native persistence result is unconfirmed");if(account!=null&&!account.matches("ynx1[023456789acdefghjklmnpqrstuvwxyz]{38}"))throw new SecurityException("Invalid current account");JSONObject current=state.getJSONObject("context");Object selected=account==null?JSONObject.NULL:account;if(selected.equals(current.get("account")))return;long generation=current.getLong("generation");if(generation>=9007199254740991L)throw new SecurityException("Native generation exhausted");JSONObject next=copy();next.getJSONObject("context").put("account",selected).put("generation",generation+1);persist(next);}
    synchronized String get(String namespace,String key,JSONObject expected)throws Exception{return withExpected(expected,()->{checkKey(key);JSONObject box=box(state,namespace,expected,false);return box==null?null:nullable(box.getJSONObject("values"),key);});}
    synchronized void set(String namespace,String key,String value,JSONObject expected)throws Exception{withExpected(expected,()->{checkKey(key);bounded(value);JSONObject next=copy(),box=box(next,namespace,expected,true);box.getJSONObject("values").put(key,value);persist(next);return null;});}
    synchronized void remove(String namespace,String key,JSONObject expected)throws Exception{withExpected(expected,()->{checkKey(key);JSONObject next=copy(),box=box(next,namespace,expected,false);if(box!=null){box.getJSONObject("values").remove(key);persist(next);}return null;});}
    synchronized void requestRevocation(String namespace,JSONObject expected)throws Exception{withExpected(expected,()->{JSONObject next=copy();box(next,namespace,expected,true).put("revocationRequested",true);persist(next);return null;});}
    synchronized boolean revocationRequested(String namespace,JSONObject expected)throws Exception{return withExpected(expected,()->{JSONObject box=box(state,namespace,expected,false);return box!=null&&box.getBoolean("revocationRequested");});}
    synchronized String saveRevocationIntent(String namespace,String key,String raw,JSONObject expected)throws Exception{return withExpected(expected,()->{checkRevokeKey(key);JSONObject incoming=intent(raw,expected),next=copy(),box=box(next,namespace,expected,true),values=box.getJSONObject("values");String previous=nullable(values,key);if(previous!=null){JSONObject original=intent(previous,expected);if(original.getString("intentId").equals(incoming.getString("intentId"))&&original.getString("scope").equals(incoming.getString("scope"))&&original.isNull("session")&&!incoming.isNull("session")){values.put(key,raw);persist(next);return raw;}return previous;}values.put(key,raw);persist(next);return raw;});}
    synchronized void finishRevocationIntent(String namespace,String key,String raw,JSONObject expected)throws Exception{withExpected(expected,()->{checkRevokeKey(key);JSONObject target=intent(raw,expected),next=copy(),box=box(next,namespace,expected,false);if(box==null||!raw.equals(nullable(box.getJSONObject("values"),key)))throw new SecurityException("Original revoke intent changed");JSONObject values=box.getJSONObject("values");String active=nullable(values,ROOT);boolean matches=false;if(active!=null&&!target.isNull("session")){try{matches=canonical(new JSONObject(active)).equals(canonical(target.getJSONObject("session")));}catch(Exception malformed){throw new SecurityException("Preserve malformed current session",malformed);}}if(active==null||matches){values.remove(ROOT);for(String suffix:new String[]{"pending","return","completion"})values.remove(ROOT+":"+suffix);}values.remove(key);box.put("revocationRequested",false);persist(next);return null;});}
    static byte[] signBytes(JSONObject input,JSONObject expected)throws Exception{
        if(input.length()!=4||!"p256-sha256".equals(input.getString("algorithm"))||!expected.getString("deviceKey").equals(input.getString("deviceKey")))throw new SecurityException("Original device signing tuple required");String purpose=input.getString("purpose"),prefix;if("challenge".equals(purpose))prefix="YNX_PRODUCT_SESSION_CHALLENGE_V2\n";else if("http-proof".equals(purpose))prefix="YNX_PRODUCT_SESSION_HTTP_PROOF_V2\n";else throw new SecurityException("Unsupported signing domain");String encoded=input.getString("payload");if(!encoded.matches("[A-Za-z0-9_-]+")||encoded.length()>32768)throw new SecurityException("Invalid original payload");byte[] bytes=java.util.Base64.getUrlDecoder().decode(encoded);if(!java.util.Base64.getUrlEncoder().withoutPadding().encodeToString(bytes).equals(encoded))throw new SecurityException("Noncanonical payload encoding");String text=StandardCharsets.UTF_8.newDecoder().onMalformedInput(CodingErrorAction.REPORT).onUnmappableCharacter(CodingErrorAction.REPORT).decode(ByteBuffer.wrap(bytes)).toString();if(!text.startsWith(prefix))throw new SecurityException("Original protocol domain required");JSONObject subject=new JSONObject(text.substring(prefix.length()));if(!(prefix+canonical(subject)).equals(text))throw new SecurityException("Exact original canonical bytes required");checkSubject(subject,expected);
        if("challenge".equals(purpose)){if(!"ynx_6423-1".equals(subject.getString("chainId"))||!"android".equals(subject.getString("platform"))||!canonical(subject.getJSONArray("scopes")).equals(canonical(originalNativeScopes())))throw new SecurityException("Original registered Music scopes required");}
        return bytes;
    }
    static void checkWalletRequest(JSONObject request,JSONObject expected)throws Exception{checkSubject(request,expected,false);if(!"ynx_6423-1".equals(request.getString("chainId"))||!"android".equals(request.getString("platform"))||!"p256-sha256".equals(request.getString("deviceAlgorithm"))||!canonical(request.getJSONArray("scopes")).equals(canonical(originalNativeScopes())))throw new SecurityException("Original registered Music request required");}
    static void checkSubject(JSONObject subject,JSONObject expected)throws Exception{checkSubject(subject,expected,true);}
    static void checkSubject(JSONObject subject,JSONObject expected,boolean requireAccount)throws Exception{if(!"music".equals(subject.getString("productId"))||!"ynx-music-v1".equals(subject.getString("clientId"))||!APP.equals(subject.getString("applicationId"))||!subject.has("bundleId")||!subject.isNull("bundleId")||!APP.equals(subject.getString("packageId"))||!("app://android/"+APP).equals(subject.getString("origin"))||!"ynxmusic://auth/callback".equals(subject.getString("callback"))||!expected.getString("deviceId").equals(subject.getString("deviceId"))||!expected.getString("deviceKey").equals(subject.getString("deviceKey"))||requireAccount&&!expected.isNull("account")&&!expected.getString("account").equals(subject.getString("account")))throw new SecurityException("Signing subject crosses current product/device/account");}
    private void persist(JSONObject next)throws Exception{validateState(next);String raw=next.toString();try{persistence.write(raw);if(!raw.equals(persistence.read()))throw new SecurityException("Native protected write did not read back");state=new JSONObject(raw);}catch(Exception failure){poisoned=true;throw failure;}}
    private JSONObject copy()throws Exception{return new JSONObject(state.toString());}
    private JSONObject box(JSONObject target,String namespace,JSONObject expected,boolean create)throws Exception{if(namespace==null||!namespace.matches("ynx\\.native-product-session\\.v2:[a-f0-9]{64}"))throw new SecurityException("Invalid native namespace");JSONObject all=target.getJSONObject("namespaces");if(!all.has(namespace)){if(!create)return null;all.put(namespace,new JSONObject().put("context",new JSONObject(expected.toString())).put("values",new JSONObject()).put("revocationRequested",false));}JSONObject box=all.getJSONObject(namespace);if(!canonical(box.getJSONObject("context")).equals(canonical(expected)))throw new SecurityException("Native namespace belongs to an earlier context");return box;}
    private static JSONObject intent(String raw,JSONObject expected)throws Exception{bounded(raw);JSONObject value=new JSONObject(raw);if(value.length()!=4||value.getInt("version")!=1||!value.getString("intentId").matches("[A-Za-z0-9_-]{32,64}")||!value.getString("scope").matches("[a-f0-9]{64}")||!value.has("session")||!value.isNull("session")&&!(value.get("session") instanceof JSONObject))throw new SecurityException("Invalid original revocation intent");if(!revocationScope(expected).equals(value.getString("scope")))throw new SecurityException("Original revoke scope changed");if(!value.isNull("session")){JSONObject target=value.getJSONObject("session");checkSubject(target,expected);if(!"ynx_6423-1".equals(target.getString("chainId"))||!"android".equals(target.getString("platform"))||!"p256-sha256".equals(target.getString("deviceAlgorithm")))throw new SecurityException("Original revoke native tuple changed");if(!canonical(target.getJSONArray("scopes")).equals(canonical(originalNativeScopes())))throw new SecurityException("Original revoke scopes changed");}return value;}
    static JSONArray originalNativeScopes(){return new JSONArray().put("music.creator").put("music.library").put("music.playback").put("music.profile");}
    static String revocationScope(JSONObject expected)throws Exception{JSONObject scope=new JSONObject().put("chainId","ynx_6423-1").put("productId","music").put("clientId","ynx-music-v1").put("platform","android").put("applicationId",APP).put("bundleId",JSONObject.NULL).put("packageId",APP).put("origin","app://android/"+APP).put("callback","ynxmusic://auth/callback").put("deviceId",expected.getString("deviceId")).put("deviceKey",expected.getString("deviceKey")).put("scopes",originalNativeScopes());byte[] hash=java.security.MessageDigest.getInstance("SHA-256").digest(("YNX_PRODUCT_SESSION_LOCAL_REVOCATION_SCOPE_V1\n"+canonical(scope)).getBytes(StandardCharsets.UTF_8));StringBuilder text=new StringBuilder();for(byte b:hash)text.append(String.format(java.util.Locale.ROOT,"%02x",b&255));return text.toString();}
    private static List<String> keys(JSONObject value){List<String> result=new ArrayList<>();java.util.Iterator<String> names=value.keys();while(names.hasNext())result.add(names.next());return result;}
    private static void validateState(JSONObject state)throws Exception{if(state.length()!=2)throw new SecurityException("Invalid original protected state");validateContext(state.getJSONObject("context"));JSONObject namespaces=state.getJSONObject("namespaces");for(String namespace:keys(namespaces)){if(!namespace.matches("ynx\\.native-product-session\\.v2:[a-f0-9]{64}"))throw new SecurityException("Invalid original namespace");JSONObject box=namespaces.getJSONObject(namespace);if(box.length()!=3)throw new SecurityException("Invalid original namespace state");validateContext(box.getJSONObject("context"));if(!(box.get("revocationRequested") instanceof Boolean))throw new SecurityException("Invalid revoke signal");JSONObject values=box.getJSONObject("values");for(String key:keys(values)){checkKey(key);bounded(values.getString(key));}}}
    private static void validateContext(JSONObject value)throws Exception{if(value.length()!=7||!"android".equals(value.getString("platform"))||!APP.equals(value.getString("applicationId"))||!value.getString("deviceId").matches("[A-Za-z0-9._:-]{16,128}")||!value.getString("deviceKey").matches("[A-Za-z0-9_-]{44}")||!("hardware-backed".equals(value.getString("securityLevel"))||"os-protected".equals(value.getString("securityLevel")))||!(value.get("generation") instanceof Number)||!value.get("generation").toString().matches("[1-9][0-9]*")||value.getLong("generation")<1||value.getLong("generation")>9007199254740991L||!value.has("account")||!value.isNull("account")&&!value.getString("account").matches("ynx1[023456789acdefghjklmnpqrstuvwxyz]{38}"))throw new SecurityException("Invalid authoritative native context");byte[] key=java.util.Base64.getUrlDecoder().decode(value.getString("deviceKey"));if(key.length!=33||(key[0]!=2&&key[0]!=3))throw new SecurityException("Compressed P256 device key required");}
    private static void checkKey(String key){if(!ROOT.equals(key)&&!key.matches(java.util.regex.Pattern.quote(ROOT)+":(?:pending|return|completion|revoke)"))throw new SecurityException("Cross-product protected storage key");}
    private static void checkRevokeKey(String key){if(!(ROOT+":revoke").equals(key))throw new SecurityException("Original revoke key required");}
    private static String nullable(JSONObject object,String key)throws Exception{return object.has(key)?object.getString(key):null;}
    private static void bounded(String value){if(value==null||value.length()>16384)throw new SecurityException("Bounded protected value required");}
    private static String quote(String value){StringBuilder result=new StringBuilder("\"");for(int i=0;i<value.length();i++){char c=value.charAt(i);switch(c){case '"':result.append("\\\"");break;case '\\':result.append("\\\\");break;case '\b':result.append("\\b");break;case '\f':result.append("\\f");break;case '\n':result.append("\\n");break;case '\r':result.append("\\r");break;case '\t':result.append("\\t");break;default:if(c<0x20||Character.isHighSurrogate(c)&&(i+1==value.length()||!Character.isLowSurrogate(value.charAt(i+1)))||Character.isLowSurrogate(c)&&(i==0||!Character.isHighSurrogate(value.charAt(i-1))))result.append(String.format(java.util.Locale.ROOT,"\\u%04x",(int)c));else result.append(c);}}return result.append('"').toString();}
    static String canonical(Object value)throws Exception{if(value==JSONObject.NULL)return "null";if(value instanceof JSONObject){JSONObject object=(JSONObject)value;List<String> keys=new ArrayList<>(keys(object));Collections.sort(keys);List<String> parts=new ArrayList<>();for(String key:keys)parts.add(quote(key)+":"+canonical(object.get(key)));return "{"+String.join(",",parts)+"}";}if(value instanceof JSONArray){JSONArray array=(JSONArray)value;List<String> parts=new ArrayList<>();for(int i=0;i<array.length();i++)parts.add(canonical(array.get(i)));return "["+String.join(",",parts)+"]";}if(value instanceof String)return quote((String)value);if(value instanceof Boolean)return value.toString();if(value instanceof Number)return JSONObject.numberToString((Number)value);throw new SecurityException("Unsupported canonical protocol value");}
}
