import {fileURLToPath} from 'node:url';import os from 'node:os';import {createRequire} from 'node:module';import {createServer} from 'node:http';import fs from 'node:fs/promises';import assert from 'node:assert/strict';
// Focused real-IDB regression: dedicated temporary headless profile and intercepted HTTPS origin only.
const root=fileURLToPath(new URL('../../../',import.meta.url)).replace(/\/$/,'');
const qa=await fs.mkdtemp(os.tmpdir()+'/ynx-social-idb-boundaries-');
const require=createRequire(root+'/apps/social/package.json');const {build}=require('esbuild');
const playwrightModule=process.env.YNX_SOCIAL_QA_PLAYWRIGHT_MODULE;if(!playwrightModule)throw Error('Set YNX_SOCIAL_QA_PLAYWRIGHT_MODULE to the installed Playwright module; no shared browser profile is used');
const {chromium}=await import(playwrightModule);
const entry=`import * as p from ${JSON.stringify(root+'/apps/social/web/protected-chat-devices.ts')};import {browserChatDevices} from ${JSON.stringify(root+'/apps/social/web/chat-workspace.ts')};window.qa={...p,browserChatDevices};`;
const built=await build({stdin:{contents:entry,resolveDir:root+'/apps/social',loader:'ts'},bundle:true,write:false,platform:'browser',format:'iife',target:'es2022'});const bundle=built.outputFiles[0].text;await fs.writeFile(qa+'/modules.js',bundle);
const server=createServer((req,res)=>{res.writeHead(200,{'content-type':req.url==='/modules.js'?'text/javascript':'text/html'});res.end(req.url==='/modules.js'?bundle:'<!doctype html><title>Isolated local Social IDB QA</title><script src="/modules.js"></script>');});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;let context;const errors=[];const output={source:'protected-chat-devices.ts from this checkout',scope:'local Chromium only, HTTPS product origin intercepted from localhost, no public requests or accounts',tests:[]};
async function launch(){context=await chromium.launchPersistentContext(qa+'/profile-clean-final',{executablePath:process.env.YNX_SOCIAL_QA_BROWSER_EXECUTABLE,headless:true});await context.route('**/*',async route=>{const u=new URL(route.request().url());if(u.origin==='https://social.ynxweb4.com'){const resp=await fetch(base+u.pathname);await route.fulfill({status:200,contentType:u.pathname==='/modules.js'?'text/javascript':'text/html',body:await resp.text()});}else if(u.origin===base)await route.continue();else await route.abort();});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.name+':'+e.message));await page.goto('https://social.ynxweb4.com');await page.waitForFunction(()=>window.qa);return page;}
async function run(name,fn){try{const result=await fn();output.tests.push({name,passed:true,...result});}catch(e){output.tests.push({name,passed:false,error:e.message});}}
try{let page=await launch();output.browser=await context.browser().version();
await run('real CryptoKey structured-clone, committed IDB and non-exportability',async()=>{const result=await page.evaluate(async()=>{const a='ynx1'+'a'.repeat(38),devices=qa.browserChatDevices(),device=await devices.get(a,true),carrier=await qa.indexedDBChatCarriers(indexedDB).load(a);let exportRejected=false;try{await crypto.subtle.exportKey('raw',carrier.key)}catch{exportRejected=true}const digest=async x=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',x))).map(x=>x.toString(16).padStart(2,'0')).join('');sessionStorage.setItem('qa-seed-digest',await digest(new TextEncoder().encode(JSON.stringify(device))));localStorage.setItem('qa-device-digest',await digest(new TextEncoder().encode(JSON.stringify(device))));localStorage.setItem('qa-ciphertext-digest',await digest(carrier.ciphertext));return {isSecureContext,origin:location.origin,instance:carrier.key instanceof CryptoKey,extractable:carrier.key.extractable,exportRejected,containsPlaintext:JSON.stringify(carrier).includes(device.signingSeed)}});assert.equal(result.isSecureContext,true);assert.equal(result.instance,true);assert.equal(result.extractable,false);assert.equal(result.exportRejected,true);assert.equal(result.containsPlaintext,false);return result;});
await context.close();page=await launch();
await run('browser-process restart decrypts identical persisted ciphertext and device',async()=>{const result=await page.evaluate(async()=>{const a='ynx1'+'a'.repeat(38),carrier=await qa.indexedDBChatCarriers(indexedDB).load(a),device=await qa.browserChatDevices().get(a,false);const digest=async x=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',x))).map(x=>x.toString(16).padStart(2,'0')).join('');return {sameDevice:await digest(new TextEncoder().encode(JSON.stringify(device)))===localStorage.getItem('qa-device-digest'),sameCiphertext:await digest(carrier.ciphertext)===localStorage.getItem('qa-ciphertext-digest'),cloneKey:carrier.key instanceof CryptoKey,extractable:carrier.key.extractable}});assert.equal(result.sameDevice,true);assert.equal(result.sameCiphertext,true);assert.equal(result.cloneKey,true);assert.equal(result.extractable,false);return result;});
await run('legacy exact bytes preserved on interrupted cleanup and retry succeeds',async()=>{const result=await page.evaluate(async()=>{const a='ynx1'+'b'.repeat(38),raw=JSON.stringify({account:a,deviceId:'isolated-local-legacy',signingSeed:'07'.repeat(32),encryptionSeed:'08'.repeat(32),legacyExtra:'exact bytes retained'});await new Promise((resolve,reject)=>{const q=indexedDB.open('ynx-social-chat-devices-v1',1);q.onupgradeneeded=()=>q.result.createObjectStore('devices');q.onsuccess=()=>{const db=q.result,t=db.transaction('devices','readwrite');t.objectStore('devices').put(raw,a);t.oncomplete=()=>{db.close();resolve()};t.onabort=()=>reject(t.error)}});const s=qa.indexedDBChatCarriers(indexedDB);let automatic,confirmation,interrupted;try{await qa.browserChatDevices().get(a,true)}catch(e){automatic=e.code}try{await qa.browserChatDevices().protectLegacy(a,false)}catch(e){confirmation=e.code}try{await qa.protectedChatDevices({...s,removeLegacy:async()=>{throw new Error('QA interrupted cleanup')}}).protectLegacy(a,true)}catch(e){interrupted=!!e}const before=await s.load(a);const retained=await s.legacy(a)===raw;const encryptedExact=await qa.openChatDevice(crypto,a,before)===raw;await qa.browserChatDevices().protectLegacy(a,true);const after=await s.load(a);return {automatic,confirmation,interrupted,retained,encryptedExact,legacyRemoved:await s.legacy(a)===null,sameCiphertext:Array.from(new Uint8Array(before.ciphertext)).join()===Array.from(new Uint8Array(after.ciphertext)).join()}});assert.equal(result.automatic,'CHAT_DEVICE_PROTECTION_REQUIRED');assert.equal(result.confirmation,'CHAT_PROTECTION_CONFIRMATION_REQUIRED');for(const k of ['interrupted','retained','encryptedExact','legacyRemoved','sameCiphertext'])assert.equal(result[k],true);return result;});
await run('real DataCloneError fails closed and clean retry remains possible',async()=>{const result=await page.evaluate(async()=>{const a='ynx1'+'c'.repeat(38),original=IDBObjectStore.prototype.add;IDBObjectStore.prototype.add=function(value,key){return original.call(this,{...value,uncloneable:()=>{}},key)};let code,failed=false;try{await Promise.race([qa.browserChatDevices().get(a,true),new Promise((_,reject)=>setTimeout(()=>reject(new Error('QA timeout')),3000))])}catch(e){failed=true;code=e.code||e.message}finally{IDBObjectStore.prototype.add=original}const missing=await qa.indexedDBChatCarriers(indexedDB).load(a)===null;const retry=await qa.browserChatDevices().get(a,true);return {failed,code,missing,retrySucceeded:!!retry.deviceId}});assert.equal(result.failed,true);assert.equal(result.code,'CHAT_DEVICE_RECOVERY_REQUIRED');assert.equal(result.missing,true);assert.equal(result.retrySucceeded,true);return result;});
await run('unsupported IDB cannot mint device, error classification inspection',async()=>{const result=await page.evaluate(async()=>{let result;try{await qa.browserChatDevices({crypto,isSecureContext,location,indexedDB:undefined}).get('ynx1'+'d'.repeat(38),true)}catch(e){result={errorName:e.name,code:e.code??null,typedRecovery:e instanceof qa.ChatStorageError,message:e.message}}return result});assert.ok(result);assert.equal(result.typedRecovery,true);assert.equal(result.code,"CHAT_SECURE_STORAGE_UNAVAILABLE");return result;});
await run('migration DataCloneError preserves exact old JSON and creates no protected carrier',async()=>{const result=await page.evaluate(async()=>{const a='ynx1'+'f'.repeat(38),raw=JSON.stringify({account:a,deviceId:'isolated-clone-failure',signingSeed:'09'.repeat(32),encryptionSeed:'0a'.repeat(32),unknown:'preserve'});await new Promise((resolve,reject)=>{const q=indexedDB.open('ynx-social-chat-devices-v1');q.onsuccess=()=>{const db=q.result,t=db.transaction('devices','readwrite');t.objectStore('devices').put(raw,a);t.oncomplete=()=>{db.close();resolve()};t.onabort=()=>reject(t.error)}});const add=IDBObjectStore.prototype.add;IDBObjectStore.prototype.add=function(value,key){return add.call(this,{...value,uncloneable:()=>{}},key)};let code;try{await qa.browserChatDevices().protectLegacy(a,true)}catch(e){code=e.code}finally{IDBObjectStore.prototype.add=add}const store=qa.indexedDBChatCarriers(indexedDB);const preserved=await store.legacy(a)===raw;const protectedAbsent=await store.load(a)===null;await qa.browserChatDevices().protectLegacy(a,true);return {code,preserved,protectedAbsent,retryExact:await qa.openChatDevice(crypto,a,await store.load(a))===raw}});assert.equal(result.code,'CHAT_DEVICE_RECOVERY_REQUIRED');assert.equal(result.preserved,true);assert.equal(result.protectedAbsent,true);assert.equal(result.retryExact,true);return result;});
await run('tampered persisted ciphertext never creates replacement and restores after original bytes returned',async()=>{const result=await page.evaluate(async()=>{const a='ynx1'+'a'.repeat(38),store=qa.indexedDBChatCarriers(indexedDB),original=await store.load(a),changed=structuredClone(original);new Uint8Array(changed.ciphertext)[0]^=1;async function put(value){await new Promise((resolve,reject)=>{const q=indexedDB.open('ynx-social-chat-secrets-v2');q.onsuccess=()=>{const db=q.result,t=db.transaction('devices','readwrite');t.objectStore('devices').put(value,a);t.oncomplete=()=>{db.close();resolve()};t.onabort=()=>reject(t.error)}})}await put(changed);let code;try{await qa.browserChatDevices().get(a,true)}catch(e){code=e.code}const retained=await store.load(a);const unchanged=Array.from(new Uint8Array(retained.ciphertext)).join()===Array.from(new Uint8Array(changed.ciphertext)).join();await put(original);const restored=await qa.browserChatDevices().get(a,false);return {code,unchanged,restored:!!restored.deviceId}});assert.equal(result.code,'CHAT_DEVICE_RECOVERY_REQUIRED');assert.equal(result.unchanged,true);assert.equal(result.restored,true);return result;});
await run('actual localhost origin correctly rejected by original module',async()=>{await page.goto(base);await page.waitForFunction(()=>window.qa);const result=await page.evaluate(async()=>{try{await qa.browserChatDevices().get('ynx1'+'e'.repeat(38),true)}catch(e){return {code:e.code,isSecureContext,origin:location.origin}}});assert.equal(result.code,'CHAT_SECURE_STORAGE_UNAVAILABLE');return result;});
}finally{if(context)await context.close();await new Promise(r=>server.close(r));output.pageErrors=errors;await fs.writeFile(qa+'/results.json',JSON.stringify(output,null,2));console.log(JSON.stringify({evidenceDirectory:qa,...output},null,2));if(output.tests.some(test=>test.passed!==true)||errors.length!==0)process.exitCode=1;}
