import{test,expect}from'@playwright/test';
import{createServer}from'node:http';
import{mkdir,readFile}from'node:fs/promises';
import{resolve}from'node:path';
const origin='http://127.0.0.1:4316',evidence=resolve('evidence/visible');
const assets=new Map([['/',['index.html','text/html; charset=utf-8']],['/index.html',['index.html','text/html; charset=utf-8']],['/app.js',['app.js','text/javascript; charset=utf-8']],['/runtime-config.js',['runtime-config.js','text/javascript; charset=utf-8']],['/styles.css',['styles.css','text/css; charset=utf-8']],['/responsive.css',['responsive.css','text/css; charset=utf-8']],['/workflow.css',['workflow.css','text/css; charset=utf-8']],['/assets/ynx-logo.png',['assets/ynx-logo.png','image/png']]]);let server;
test.beforeAll(async()=>{await mkdir(evidence,{recursive:true});server=createServer(async(req,res)=>{const asset=assets.get(new URL(req.url,origin).pathname);if(!asset){res.writeHead(404,{'content-type':'text/plain'});res.end('not found');return}res.writeHead(200,{'content-type':asset[1],'cache-control':'no-store'});res.end(await readFile(resolve('dist',asset[0])))});await new Promise((ok,fail)=>{server.once('error',fail);server.listen(4316,'127.0.0.1',ok)})});
test.afterAll(async()=>{if(server)await new Promise(ok=>server.close(ok))});
async function installProvider(page,{reject=false}={}){await page.addInitScript(({reject})=>{const provider={async request({method}){if(method==='eth_requestAccounts'){if(reject)throw Object.assign(new Error('User rejected the request.'),{code:4001});return['0x1111111111111111111111111111111111111111']}if(method==='eth_chainId')return'0x1917';throw Object.assign(new Error(`Unsupported deterministic method: ${method}`),{code:4200})},on(){},removeListener(){}};const detail=Object.freeze({info:Object.freeze({uuid:reject?'seller-reject':'seller-approve',name:'YNX Test Wallet',icon:"data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg'/>",rdns:'com.ynxweb4.wallet.test'}),provider});addEventListener('eip6963:requestProvider',()=>dispatchEvent(new CustomEvent('eip6963:announceProvider',{detail})))} ,{reject})}
test('approved deterministic Wallet preserves guest preview and separates degraded seller service',async({page})=>{const errors=[];page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await installProvider(page);await page.goto('/');await page.getByRole('button',{name:'Explore without signing in'}).click();await expect(page.getByText('Seller workflow preview')).toBeVisible();await page.getByRole('button',{name:'Connect Wallet'}).click();await expect(page.locator('#wallet')).toContainText('YNX Test Wallet');await expect(page.locator('#state')).toContainText('Standard Wallet connected on 0x1917');await page.locator('#privateSession').click();await expect(page.locator('#state')).toContainText('remains connected');await expect(page.locator('#state')).toContainText('PRIVATE_SERVICE_DEGRADED');await expect(page.getByText('Seller workflow preview')).toBeVisible();await page.screenshot({path:resolve(evidence,'seller-wallet-approved-private-degraded-1440x900.png'),fullPage:true});expect(errors).toEqual([])});
test('rejected deterministic Wallet creates no account and guest preview remains available',async({page})=>{const errors=[];page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await installProvider(page,{reject:true});await page.goto('/');await page.locator('#wallet').click();await expect(page.locator('#wallet')).toHaveText('Connect Wallet');await expect(page.locator('#privateSession')).toBeDisabled();await expect(page.locator('#state')).toContainText('User rejected the request');await page.getByRole('button',{name:'Explore without signing in'}).click();await expect(page.getByText('No seller records, balances, orders, accounts, or permissions are fabricated')).toBeVisible();await page.screenshot({path:resolve(evidence,'seller-wallet-rejected-guest-preview-1440x900.png'),fullPage:true});expect(errors).toEqual([])});
test('private Wallet launch keeps Seller visible and exposes official fallback choices',async({page})=>{await page.addInitScript(()=>Object.defineProperty(globalThis,'__YNX_SELLER_RUNTIME__',{value:Object.freeze({endpoints:Object.freeze({sellerProductApi:Object.freeze({status:'VERIFIED'})})}),configurable:false,writable:false}));await installProvider(page);await page.route('**/api/auth/config?surface=seller',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({version:'1',gateway:'available',chainId:'ynx_6423-1',requestingProduct:'shop-seller',productClientId:'ynx-seller-v1',bundleId:'com.ynxweb4.seller-console',productDeviceAlgorithm:'p256-sha256',callback:'ynxseller://wallet-auth/callback',scopes:['account:read','shop:seller:operate']})}));await page.goto('/');const original=page.url();await page.locator('#wallet').click();await page.locator('#privateSession').click();await expect(page.getByRole('link',{name:'Download YNX Wallet'})).toHaveAttribute('href','https://www.ynxweb4.com/dapp/download');await expect(page.getByRole('link',{name:'Use MetaMask'})).toHaveAttribute('href','https://metamask.io/download/');expect(page.url()).toBe(original);await expect(page.locator('#state')).toContainText('Seller page remains available');await page.screenshot({path:resolve(evidence,'seller-controlled-wallet-fallback-1440x900.png'),fullPage:true})});
