import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {projectTransactionResolution} from "../src/transaction-resolution-display.mjs";
import {TransactionSubmissions} from "../src/transaction-submissions.mjs";
import {parseFeeModel} from "../src/rpc-capabilities.mjs";
import {DURABILITY_MODEL} from "../src/transaction-durability.mjs";
import {CANONICAL_RPC_URL} from "../src/rpc.mjs";

const literal=JSON.parse(await readFile(new URL("./fixtures/transaction-durability/ethereum-block-marker.json",import.meta.url),"utf8"));
const receipt=literal.recoveredReceipt,account=receipt.from,hash=receipt.transactionHash;
const context={account,hash};
const model=parseFeeModel({version:"ynx-ethereum-native-v1",enabled:true,chainId:"0x1917",transactionType:"0x0",feeYNXT:"1",feeWei:"0xde0b6b3a7640000",gas:"0x61a8",gasPrice:"0x246139ca8000",decimals:18,amountQuantumWei:"0xde0b6b3a7640000",scope:"whole-YNXT plain native transfers",fullEVM:false,eip1559:false,durability:DURABILITY_MODEL});
const completed=()=>({hash,account,status:"confirmed",confirmed:true,successful:true,actualFee:"1.0",blockNumber:"0x1",confirmationScope:"local-snapshot",consensusFinality:false,canRetryExact:false});
test("display projection detaches verified primitive facts from mutable response",()=>{const value=completed(),view=projectTransactionResolution({ok:true,value},context);value.actualFee="999.0";assert.equal(view.actualFee,"1.0");assert.equal(Object.isFrozen(view),true);});
for(const field of ["ok","value","confirmed","hash","actualFee"])test(`display does not invoke ${field} accessor`,()=>{let reads=0;const response={ok:true,value:completed()},target=["ok","value"].includes(field)?response:response.value;Object.defineProperty(target,field,{enumerable:true,get(){reads++;return field==="ok"?true:"1.0"}});assert.throws(()=>projectTransactionResolution(response,context));assert.equal(reads,0);});
test("a retry submission is not a completed receipt and cannot appear on check path",()=>{const response={ok:true,value:{hash,account,status:"submitted",confirmed:false,retriedExactBytes:true}};assert.throws(()=>projectTransactionResolution(response,context));const view=projectTransactionResolution(response,{...context,retry:true});assert.equal(view.confirmed,false);assert.equal(view.status,"submitted");assert.equal(Object.hasOwn(view,"actualFee"),false);});
test("original failed terminal DTO retains failure and explicit local scope",()=>{const value={...completed(),successful:false,status:"failed"};assert.equal(projectTransactionResolution({ok:true,value},context).successful,false);});
test("literal failure envelope stays an error, truthy success and inherited success are rejected",()=>{assert.equal(projectTransactionResolution({ok:false,error:{code:"ACCOUNT_CHANGED",message:"Select original account"}},context),null);assert.throws(()=>projectTransactionResolution({ok:1,value:completed()},context));assert.throws(()=>projectTransactionResolution(Object.assign(Object.create({ok:true}),{value:completed()}),context));});

function producer(state=null){
  // Controlled original public intent/receipt fixtures only. No real journal,
  // SDK, network, signer, OS authority or installed runtime is exercised.
  const raw="controlled-original-bytes",intent={hash,account,to:receipt.to,nonce:"0x0",value:"0x1bc16d674ec80000",origin:CANONICAL_RPC_URL,raw,capabilities:model};
  const calls=[],resolutions=[],writes=[];
  const instance=new TransactionSubmissions({verifyChain:async()=>{},capabilities:async()=>model,intentStore:{snapshot:async()=>[structuredClone(intent)],resolutions:async()=>[],resolve:async(...args)=>resolutions.push(args),add:async(...args)=>writes.push(args)},provider:{send:async(method,args)=>{calls.push({method,args});if(method==="eth_getTransactionReceipt")return state?null:structuredClone(receipt);if(method==="ynx_getTransactionDurability")return state;if(method==="eth_sendRawTransaction")return hash;throw Error("Unexpected method");}}});
  return{instance,calls,resolutions,writes,raw};
}
test("original receipt producer composes into display without raw bytes or finality claims",async()=>{const h=producer(),outcome=await h.instance.check(hash,account),view=projectTransactionResolution({ok:true,value:outcome},context);assert.equal(view.actualFee,"1.0");assert.equal(view.confirmed,true);assert.equal(view.consensusFinality,false);assert.equal(h.resolutions.length,1);assert.equal(h.writes.length,0);assert.equal(Object.hasOwn(view,"raw"),false);assert.deepEqual(h.calls.map(c=>c.method),["eth_getTransactionReceipt"]);});
for(const status of ["not_found","uncertain","memory_only","pending_durable","durable"])test(`original ${status} without a mined receipt remains unresolved in display`,async()=>{const proof={version:DURABILITY_MODEL.version,scope:"local-snapshot",status,transactionHash:hash};if(["pending_durable","durable"].includes(status)){const original=receipt.ynxDurability;for(const key of ["checkpointBlockNumber","checkpointBlockHash","snapshotIntegrity"])proof[key]=original[key];if(status==="durable")for(const key of ["blockNumber","blockHash"])proof[key]=original[key];}const h=producer(proof),view=projectTransactionResolution({ok:true,value:await h.instance.check(hash,account)},context);assert.equal(view.confirmed,false);assert.equal(view.durabilityStatus,status);assert.equal(h.resolutions.length,0);assert.equal(h.writes.length,0);assert.equal(Object.hasOwn(view,"actualFee"),false);});
test("explicit original retry broadcasts only original bytes once and still has no completed proof",async()=>{const h=producer({version:DURABILITY_MODEL.version,scope:"local-snapshot",status:"not_found",transactionHash:hash}),guard={account,assert(){}};const view=projectTransactionResolution({ok:true,value:await h.instance.retry(hash,account,guard)},{...context,retry:true});assert.equal(view.confirmed,false);assert.equal(view.retriedExactBytes,true);assert.deepEqual(h.calls.filter(c=>c.method==="eth_sendRawTransaction"),[{method:"eth_sendRawTransaction",args:[h.raw]}]);assert.equal(h.writes.length,1);assert.equal(h.writes[0][1].retry,true);assert.equal(h.resolutions.length,0);});
test("original retry finding completed receipt does not rebroadcast",async()=>{const h=producer(),view=projectTransactionResolution({ok:true,value:await h.instance.retry(hash,account,{account,assert(){}})},{...context,retry:true});assert.equal(view.confirmed,true);assert.equal(h.calls.some(c=>c.method==="eth_sendRawTransaction"),false);assert.equal(h.writes.length,0);});
