import assert from "node:assert/strict";
import test from "node:test";
import {ContactRetry} from "../web/contact-retry.mjs";

function fixture(){let generation=1,current:any=null,fail=true;const sent:any[]=[];const workspace={contactContextGuard(){const epoch=generation;return()=>generation===epoch},isContactPreviewCurrent(preview:any){return current===preview},cancelContactPreview(){current=null},async confirmContact(preview:any,message:string){sent.push({preview,message});if(fail)throw new Error("offline");current=null}};const retry=new ContactRetry(workspace);return {retry,sent,select:(preview:any)=>{current=preview},succeed:()=>{fail=false},changeAccount:()=>{generation++;current=null}}}
const preview=()=>({source:"handle",value:"bob",person:{displayName:"Bob",handle:"bob"},idempotencyKey:"original-key"});
test("Web retry retains exact approved person, note and key without a new preview",async()=>{const f=fixture(),review=preview();f.select(review);f.retry.retain(review," original note ");await assert.rejects(f.retry.attempt(),/offline/);const pending=f.retry.current;assert.ok(pending);assert.equal(pending.preview,review);assert.equal(pending.message,"original note");f.succeed();await f.retry.attempt();assert.deepEqual(f.sent[0],f.sent[1]);assert.equal(f.retry.current,null)});
test("editing requires a new review and retains original uncertain intent metadata",async()=>{const f=fixture(),review=preview();f.select(review);f.retry.retain(review,"note");await assert.rejects(f.retry.attempt());f.retry.reviewAgain();await assert.rejects(f.retry.attempt(),/No current/);assert.equal(f.retry.archived[0].preview,review);assert.equal(f.retry.archived[0].message,"note")});
test("new account discards old-account pending hints and cannot retry them",async()=>{const f=fixture(),review=preview();f.select(review);f.retry.retain(review,"note");f.changeAccount();assert.equal(f.retry.current,null);await assert.rejects(f.retry.attempt());assert.equal(f.sent.length,0)});
test("archived uncertain hints are also generation-scoped",async()=>{const f=fixture(),review=preview();f.select(review);f.retry.retain(review,"note");f.retry.reviewAgain();assert.equal(f.retry.archived.length,1);f.changeAccount();assert.equal(f.retry.current,null);assert.equal(f.retry.archived.length,0)});
