import type { SecureStorageAdapter } from "../storage/walletRepository";

export const SUPPORTED_LOCALES=["en","zh-Hans","zh-Hant","ja","ko","es","fr","de","pt","ru","ar","id"] as const;
export type WalletLocale=typeof SUPPORTED_LOCALES[number];
export const LOCALE_PREFERENCE_KEY="ynx.wallet.locale.v1";
const EN={languageName:"English",settingsTitle:"Language and accessibility",systemDefault:"Use system language",createWallet:"Create a new Wallet",importWallet:"Import recovery key",unlock:"Unlock with biometrics",signInTitle:"Sign in with YNX Wallet",approve:"Approve",reject:"Reject",permissions:"Permissions",purpose:"Purpose",expires:"Valid until",privacy:"Wallet never shares private keys or recovery material.",recovery:"Restore offline with the recovery key. Product sessions are not restored.",retry:"Retry",offline:"Offline. Stored accounts remain available; network data is unavailable.",unavailable:"Service unavailable",errorPrefix:"Security check failed",aiOutputLanguage:"AI output language",close:"Close",revoke:"Revoke approval",audit:"Authorization audit",requestingApp:"Requesting App",appIdentity:"App identity",network:"Network",account:"Account"} as const;
type BaseMessageKey=keyof typeof EN;
const MESSAGES:Record<WalletLocale,Record<BaseMessageKey,string>>={
  en:EN,
  "zh-Hans":{languageName:"简体中文",settingsTitle:"语言与辅助功能",systemDefault:"使用系统语言",createWallet:"创建新钱包",importWallet:"导入恢复密钥",unlock:"使用生物识别解锁",signInTitle:"使用 YNX Wallet 登录",approve:"批准",reject:"拒绝",permissions:"权限",purpose:"用途",expires:"有效期至",privacy:"Wallet 绝不会共享私钥或恢复材料。",recovery:"使用恢复密钥离线恢复。产品会话不会被恢复。",retry:"重试",offline:"当前离线。已存账户仍可使用，网络数据不可用。",unavailable:"服务不可用",errorPrefix:"安全检查失败",aiOutputLanguage:"AI 输出语言",close:"关闭",revoke:"撤销授权",audit:"授权审计",requestingApp:"请求 App",appIdentity:"App 身份",network:"网络",account:"账户"},
  "zh-Hant":{languageName:"繁體中文",settingsTitle:"語言與輔助功能",systemDefault:"使用系統語言",createWallet:"建立新錢包",importWallet:"匯入復原金鑰",unlock:"使用生物辨識解鎖",signInTitle:"使用 YNX Wallet 登入",approve:"核准",reject:"拒絕",permissions:"權限",purpose:"用途",expires:"有效期限",privacy:"Wallet 絕不會分享私鑰或復原資料。",recovery:"使用復原金鑰離線復原。產品工作階段不會復原。",retry:"重試",offline:"目前離線。已儲存帳戶仍可使用，網路資料無法取得。",unavailable:"服務無法使用",errorPrefix:"安全檢查失敗",aiOutputLanguage:"AI 輸出語言",close:"關閉",revoke:"撤銷授權",audit:"授權稽核",requestingApp:"要求 App",appIdentity:"App 身分",network:"網路",account:"帳戶"},
  ja:{languageName:"日本語",settingsTitle:"言語とアクセシビリティ",systemDefault:"システム言語を使用",createWallet:"新しいウォレットを作成",importWallet:"復元キーをインポート",unlock:"生体認証でロック解除",signInTitle:"YNX Wallet でサインイン",approve:"承認",reject:"拒否",permissions:"権限",purpose:"目的",expires:"有効期限",privacy:"Wallet が秘密鍵や復元情報を共有することはありません。",recovery:"復元キーでオフライン復元します。製品セッションは復元されません。",retry:"再試行",offline:"オフラインです。保存済みアカウントは利用できますが、ネットワークデータは取得できません。",unavailable:"サービスを利用できません",errorPrefix:"セキュリティ確認に失敗しました",aiOutputLanguage:"AI 出力言語",close:"閉じる",revoke:"承認を取り消す",audit:"認可監査",requestingApp:"要求元 App",appIdentity:"App ID",network:"ネットワーク",account:"アカウント"},
  ko:{languageName:"한국어",settingsTitle:"언어 및 접근성",systemDefault:"시스템 언어 사용",createWallet:"새 지갑 만들기",importWallet:"복구 키 가져오기",unlock:"생체 인증으로 잠금 해제",signInTitle:"YNX Wallet로 로그인",approve:"승인",reject:"거부",permissions:"권한",purpose:"목적",expires:"유효 기간",privacy:"Wallet은 개인 키나 복구 자료를 공유하지 않습니다.",recovery:"복구 키로 오프라인 복구합니다. 제품 세션은 복구되지 않습니다.",retry:"다시 시도",offline:"오프라인입니다. 저장된 계정은 사용할 수 있지만 네트워크 데이터는 사용할 수 없습니다.",unavailable:"서비스를 사용할 수 없음",errorPrefix:"보안 확인 실패",aiOutputLanguage:"AI 출력 언어",close:"닫기",revoke:"승인 취소",audit:"승인 감사",requestingApp:"요청 App",appIdentity:"App ID",network:"네트워크",account:"계정"},
  es:{languageName:"Español",settingsTitle:"Idioma y accesibilidad",systemDefault:"Usar idioma del sistema",createWallet:"Crear una Wallet nueva",importWallet:"Importar clave de recuperación",unlock:"Desbloquear con biometría",signInTitle:"Iniciar sesión con YNX Wallet",approve:"Aprobar",reject:"Rechazar",permissions:"Permisos",purpose:"Finalidad",expires:"Válido hasta",privacy:"Wallet nunca comparte claves privadas ni material de recuperación.",recovery:"Recupera sin conexión con la clave. Las sesiones de productos no se restauran.",retry:"Reintentar",offline:"Sin conexión. Las cuentas guardadas siguen disponibles; los datos de red no.",unavailable:"Servicio no disponible",errorPrefix:"Falló la comprobación de seguridad",aiOutputLanguage:"Idioma de salida de IA",close:"Cerrar",revoke:"Revocar autorización",audit:"Auditoría de autorizaciones",requestingApp:"App solicitante",appIdentity:"Identidad de la App",network:"Red",account:"Cuenta"},
  fr:{languageName:"Français",settingsTitle:"Langue et accessibilité",systemDefault:"Utiliser la langue du système",createWallet:"Créer un nouveau Wallet",importWallet:"Importer la clé de récupération",unlock:"Déverrouiller par biométrie",signInTitle:"Se connecter avec YNX Wallet",approve:"Approuver",reject:"Refuser",permissions:"Autorisations",purpose:"Finalité",expires:"Valable jusqu’au",privacy:"Wallet ne partage jamais les clés privées ni les éléments de récupération.",recovery:"Restaurez hors ligne avec la clé. Les sessions produit ne sont pas restaurées.",retry:"Réessayer",offline:"Hors ligne. Les comptes enregistrés restent disponibles, pas les données réseau.",unavailable:"Service indisponible",errorPrefix:"Échec du contrôle de sécurité",aiOutputLanguage:"Langue de sortie de l’IA",close:"Fermer",revoke:"Révoquer l’autorisation",audit:"Journal des autorisations",requestingApp:"App demandeuse",appIdentity:"Identité de l’App",network:"Réseau",account:"Compte"},
  de:{languageName:"Deutsch",settingsTitle:"Sprache und Barrierefreiheit",systemDefault:"Systemsprache verwenden",createWallet:"Neue Wallet erstellen",importWallet:"Wiederherstellungsschlüssel importieren",unlock:"Mit Biometrie entsperren",signInTitle:"Mit YNX Wallet anmelden",approve:"Genehmigen",reject:"Ablehnen",permissions:"Berechtigungen",purpose:"Zweck",expires:"Gültig bis",privacy:"Wallet gibt niemals private Schlüssel oder Wiederherstellungsdaten weiter.",recovery:"Offline mit dem Schlüssel wiederherstellen. Produktsitzungen werden nicht wiederhergestellt.",retry:"Erneut versuchen",offline:"Offline. Gespeicherte Konten bleiben verfügbar; Netzwerkdaten nicht.",unavailable:"Dienst nicht verfügbar",errorPrefix:"Sicherheitsprüfung fehlgeschlagen",aiOutputLanguage:"KI-Ausgabesprache",close:"Schließen",revoke:"Genehmigung widerrufen",audit:"Autorisierungsprotokoll",requestingApp:"Anfragende App",appIdentity:"App-Identität",network:"Netzwerk",account:"Konto"},
  pt:{languageName:"Português",settingsTitle:"Idioma e acessibilidade",systemDefault:"Usar idioma do sistema",createWallet:"Criar nova Wallet",importWallet:"Importar chave de recuperação",unlock:"Desbloquear com biometria",signInTitle:"Entrar com YNX Wallet",approve:"Aprovar",reject:"Rejeitar",permissions:"Permissões",purpose:"Finalidade",expires:"Válido até",privacy:"A Wallet nunca compartilha chaves privadas nem material de recuperação.",recovery:"Restaure offline com a chave. Sessões de produtos não são restauradas.",retry:"Tentar novamente",offline:"Offline. Contas salvas continuam disponíveis; dados de rede não.",unavailable:"Serviço indisponível",errorPrefix:"Falha na verificação de segurança",aiOutputLanguage:"Idioma de saída da IA",close:"Fechar",revoke:"Revogar autorização",audit:"Auditoria de autorizações",requestingApp:"App solicitante",appIdentity:"Identidade do App",network:"Rede",account:"Conta"},
  ru:{languageName:"Русский",settingsTitle:"Язык и специальные возможности",systemDefault:"Использовать язык системы",createWallet:"Создать новый Wallet",importWallet:"Импортировать ключ восстановления",unlock:"Разблокировать биометрией",signInTitle:"Войти через YNX Wallet",approve:"Разрешить",reject:"Отклонить",permissions:"Разрешения",purpose:"Назначение",expires:"Действительно до",privacy:"Wallet никогда не передает закрытые ключи или материалы восстановления.",recovery:"Восстановите офлайн с помощью ключа. Сеансы продуктов не восстанавливаются.",retry:"Повторить",offline:"Нет сети. Сохраненные аккаунты доступны, сетевые данные недоступны.",unavailable:"Сервис недоступен",errorPrefix:"Проверка безопасности не пройдена",aiOutputLanguage:"Язык ответа ИИ",close:"Закрыть",revoke:"Отозвать разрешение",audit:"Журнал авторизаций",requestingApp:"Запрашивающее приложение",appIdentity:"Идентификатор приложения",network:"Сеть",account:"Аккаунт"},
  ar:{languageName:"العربية",settingsTitle:"اللغة وإمكانية الوصول",systemDefault:"استخدام لغة النظام",createWallet:"إنشاء محفظة جديدة",importWallet:"استيراد مفتاح الاسترداد",unlock:"فتح القفل بالمقاييس الحيوية",signInTitle:"تسجيل الدخول باستخدام YNX Wallet",approve:"موافقة",reject:"رفض",permissions:"الأذونات",purpose:"الغرض",expires:"صالح حتى",privacy:"لا تشارك Wallet المفاتيح الخاصة أو مواد الاسترداد مطلقًا.",recovery:"استعد دون اتصال باستخدام المفتاح. لا تُستعاد جلسات المنتجات.",retry:"إعادة المحاولة",offline:"غير متصل. تبقى الحسابات المحفوظة متاحة، وبيانات الشبكة غير متاحة.",unavailable:"الخدمة غير متاحة",errorPrefix:"فشل فحص الأمان",aiOutputLanguage:"لغة إخراج الذكاء الاصطناعي",close:"إغلاق",revoke:"إلغاء التفويض",audit:"سجل التفويض",requestingApp:"التطبيق الطالب",appIdentity:"هوية التطبيق",network:"الشبكة",account:"الحساب"},
  id:{languageName:"Bahasa Indonesia",settingsTitle:"Bahasa dan aksesibilitas",systemDefault:"Gunakan bahasa sistem",createWallet:"Buat Wallet baru",importWallet:"Impor kunci pemulihan",unlock:"Buka dengan biometrik",signInTitle:"Masuk dengan YNX Wallet",approve:"Setujui",reject:"Tolak",permissions:"Izin",purpose:"Tujuan",expires:"Berlaku hingga",privacy:"Wallet tidak pernah membagikan kunci privat atau materi pemulihan.",recovery:"Pulihkan secara offline dengan kunci. Sesi produk tidak dipulihkan.",retry:"Coba lagi",offline:"Offline. Akun tersimpan tetap tersedia; data jaringan tidak tersedia.",unavailable:"Layanan tidak tersedia",errorPrefix:"Pemeriksaan keamanan gagal",aiOutputLanguage:"Bahasa keluaran AI",close:"Tutup",revoke:"Cabut persetujuan",audit:"Audit otorisasi",requestingApp:"App peminta",appIdentity:"Identitas App",network:"Jaringan",account:"Akun"},
};

const UI_EN={welcome:"WELCOME · SELF-CUSTODY STARTS HERE",ownAccount:"Own your account.",recoverReplacement:"Recover on a replacement device",beforeBegin:"Before you begin",walletLocked:"WALLET LOCKED",checkingBiometrics:"Checking biometrics…",lostDeviceRecovery:"Lost-device recovery",nativeAccount:"NATIVE ACCOUNT",send:"Send",receive:"Receive",activity:"Activity",accountSafety:"Account safety",lockWallet:"Lock Wallet",createAnother:"Create another account",importAnother:"Import recovery key",authorizationLead:"Review every binding. Approval shares a public account proof only.",aiSecurity:"AI security explanation",aiCannotApprove:"AI cannot sign or approve."} as const;
type UIMessageKey=keyof typeof UI_EN;
export type MessageKey=BaseMessageKey|UIMessageKey;
const UI_MESSAGES:Record<WalletLocale,Record<UIMessageKey,string>>={
  en:UI_EN,
  "zh-Hans":{welcome:"欢迎 · 自托管从这里开始",ownAccount:"掌控你的账户。",recoverReplacement:"在替换设备上恢复",beforeBegin:"开始之前",walletLocked:"钱包已锁定",checkingBiometrics:"正在检查生物识别…",lostDeviceRecovery:"丢失设备恢复",nativeAccount:"原生账户",send:"发送",receive:"接收",activity:"活动",accountSafety:"账户安全",lockWallet:"锁定钱包",createAnother:"创建另一个账户",importAnother:"导入恢复密钥",authorizationLead:"逐项检查绑定。批准只会共享公开账户证明。",aiSecurity:"AI 安全说明",aiCannotApprove:"AI 无法签名或批准。"},
  "zh-Hant":{welcome:"歡迎 · 自我託管從這裡開始",ownAccount:"掌控你的帳戶。",recoverReplacement:"在替換裝置上復原",beforeBegin:"開始之前",walletLocked:"錢包已鎖定",checkingBiometrics:"正在檢查生物辨識…",lostDeviceRecovery:"遺失裝置復原",nativeAccount:"原生帳戶",send:"傳送",receive:"接收",activity:"活動",accountSafety:"帳戶安全",lockWallet:"鎖定錢包",createAnother:"建立另一個帳戶",importAnother:"匯入復原金鑰",authorizationLead:"逐項檢查綁定。核准只會分享公開帳戶證明。",aiSecurity:"AI 安全說明",aiCannotApprove:"AI 無法簽署或核准。"},
  ja:{welcome:"ようこそ · セルフカストディはここから",ownAccount:"自分のアカウントを管理。",recoverReplacement:"交換端末で復元",beforeBegin:"始める前に",walletLocked:"ウォレットはロック中",checkingBiometrics:"生体認証を確認中…",lostDeviceRecovery:"紛失端末から復元",nativeAccount:"ネイティブアカウント",send:"送信",receive:"受取",activity:"履歴",accountSafety:"アカウントの安全",lockWallet:"ウォレットをロック",createAnother:"別のアカウントを作成",importAnother:"復元キーをインポート",authorizationLead:"すべての紐付けを確認してください。承認で共有するのは公開アカウント証明だけです。",aiSecurity:"AI セキュリティ説明",aiCannotApprove:"AI は署名も承認もできません。"},
  ko:{welcome:"환영합니다 · 셀프 커스터디 시작",ownAccount:"내 계정을 직접 관리하세요.",recoverReplacement:"교체 기기에서 복구",beforeBegin:"시작하기 전에",walletLocked:"지갑 잠김",checkingBiometrics:"생체 인증 확인 중…",lostDeviceRecovery:"분실 기기 복구",nativeAccount:"네이티브 계정",send:"보내기",receive:"받기",activity:"활동",accountSafety:"계정 안전",lockWallet:"지갑 잠그기",createAnother:"다른 계정 만들기",importAnother:"복구 키 가져오기",authorizationLead:"모든 바인딩을 확인하세요. 승인은 공개 계정 증명만 공유합니다.",aiSecurity:"AI 보안 설명",aiCannotApprove:"AI는 서명하거나 승인할 수 없습니다."},
  es:{welcome:"BIENVENIDA · TU AUTOCUSTODIA EMPIEZA AQUÍ",ownAccount:"Controla tu cuenta.",recoverReplacement:"Recuperar en otro dispositivo",beforeBegin:"Antes de empezar",walletLocked:"WALLET BLOQUEADA",checkingBiometrics:"Comprobando biometría…",lostDeviceRecovery:"Recuperación por dispositivo perdido",nativeAccount:"CUENTA NATIVA",send:"Enviar",receive:"Recibir",activity:"Actividad",accountSafety:"Seguridad de la cuenta",lockWallet:"Bloquear Wallet",createAnother:"Crear otra cuenta",importAnother:"Importar clave de recuperación",authorizationLead:"Revisa cada vínculo. La aprobación solo comparte una prueba pública de la cuenta.",aiSecurity:"Explicación de seguridad con IA",aiCannotApprove:"La IA no puede firmar ni aprobar."},
  fr:{welcome:"BIENVENUE · L’AUTOGARDE COMMENCE ICI",ownAccount:"Gardez le contrôle de votre compte.",recoverReplacement:"Restaurer sur un appareil de remplacement",beforeBegin:"Avant de commencer",walletLocked:"WALLET VERROUILLÉ",checkingBiometrics:"Vérification biométrique…",lostDeviceRecovery:"Récupération après perte de l’appareil",nativeAccount:"COMPTE NATIF",send:"Envoyer",receive:"Recevoir",activity:"Activité",accountSafety:"Sécurité du compte",lockWallet:"Verrouiller Wallet",createAnother:"Créer un autre compte",importAnother:"Importer la clé de récupération",authorizationLead:"Vérifiez chaque liaison. L’approbation ne partage qu’une preuve publique du compte.",aiSecurity:"Explication de sécurité par IA",aiCannotApprove:"L’IA ne peut ni signer ni approuver."},
  de:{welcome:"WILLKOMMEN · SELBSTVERWAHRUNG BEGINNT HIER",ownAccount:"Behalte die Kontrolle über dein Konto.",recoverReplacement:"Auf einem Ersatzgerät wiederherstellen",beforeBegin:"Bevor du beginnst",walletLocked:"WALLET GESPERRT",checkingBiometrics:"Biometrie wird geprüft…",lostDeviceRecovery:"Wiederherstellung bei Geräteverlust",nativeAccount:"NATIVES KONTO",send:"Senden",receive:"Empfangen",activity:"Aktivität",accountSafety:"Kontosicherheit",lockWallet:"Wallet sperren",createAnother:"Weiteres Konto erstellen",importAnother:"Wiederherstellungsschlüssel importieren",authorizationLead:"Prüfe jede Bindung. Die Genehmigung teilt nur einen öffentlichen Kontonachweis.",aiSecurity:"KI-Sicherheitserklärung",aiCannotApprove:"KI kann weder signieren noch genehmigen."},
  pt:{welcome:"BOAS-VINDAS · A AUTOCUSTÓDIA COMEÇA AQUI",ownAccount:"Controle sua conta.",recoverReplacement:"Recuperar em um dispositivo substituto",beforeBegin:"Antes de começar",walletLocked:"WALLET BLOQUEADA",checkingBiometrics:"Verificando biometria…",lostDeviceRecovery:"Recuperação de dispositivo perdido",nativeAccount:"CONTA NATIVA",send:"Enviar",receive:"Receber",activity:"Atividade",accountSafety:"Segurança da conta",lockWallet:"Bloquear Wallet",createAnother:"Criar outra conta",importAnother:"Importar chave de recuperação",authorizationLead:"Revise cada vínculo. A aprovação compartilha apenas uma prova pública da conta.",aiSecurity:"Explicação de segurança por IA",aiCannotApprove:"A IA não pode assinar nem aprovar."},
  ru:{welcome:"ДОБРО ПОЖАЛОВАТЬ · САМОСТОЯТЕЛЬНОЕ ХРАНЕНИЕ",ownAccount:"Управляйте своим аккаунтом.",recoverReplacement:"Восстановить на новом устройстве",beforeBegin:"Перед началом",walletLocked:"WALLET ЗАБЛОКИРОВАН",checkingBiometrics:"Проверка биометрии…",lostDeviceRecovery:"Восстановление при потере устройства",nativeAccount:"НАТИВНЫЙ АККАУНТ",send:"Отправить",receive:"Получить",activity:"Активность",accountSafety:"Безопасность аккаунта",lockWallet:"Заблокировать Wallet",createAnother:"Создать другой аккаунт",importAnother:"Импортировать ключ восстановления",authorizationLead:"Проверьте каждую привязку. Разрешение передает только публичное подтверждение аккаунта.",aiSecurity:"Объяснение безопасности ИИ",aiCannotApprove:"ИИ не может подписывать или разрешать."},
  ar:{welcome:"مرحبًا · الحفظ الذاتي يبدأ هنا",ownAccount:"امتلك التحكم في حسابك.",recoverReplacement:"الاسترداد على جهاز بديل",beforeBegin:"قبل البدء",walletLocked:"المحفظة مقفلة",checkingBiometrics:"جارٍ التحقق من المقاييس الحيوية…",lostDeviceRecovery:"استرداد الجهاز المفقود",nativeAccount:"الحساب الأصلي",send:"إرسال",receive:"استلام",activity:"النشاط",accountSafety:"أمان الحساب",lockWallet:"قفل المحفظة",createAnother:"إنشاء حساب آخر",importAnother:"استيراد مفتاح الاسترداد",authorizationLead:"راجع كل ارتباط. لا تشارك الموافقة سوى إثبات حساب عام.",aiSecurity:"شرح أمان بالذكاء الاصطناعي",aiCannotApprove:"لا يمكن للذكاء الاصطناعي التوقيع أو الموافقة."},
  id:{welcome:"SELAMAT DATANG · SWAKUSTODI DIMULAI DI SINI",ownAccount:"Kendalikan akun Anda.",recoverReplacement:"Pulihkan di perangkat pengganti",beforeBegin:"Sebelum memulai",walletLocked:"WALLET TERKUNCI",checkingBiometrics:"Memeriksa biometrik…",lostDeviceRecovery:"Pemulihan perangkat hilang",nativeAccount:"AKUN NATIF",send:"Kirim",receive:"Terima",activity:"Aktivitas",accountSafety:"Keamanan akun",lockWallet:"Kunci Wallet",createAnother:"Buat akun lain",importAnother:"Impor kunci pemulihan",authorizationLead:"Tinjau setiap ikatan. Persetujuan hanya membagikan bukti akun publik.",aiSecurity:"Penjelasan keamanan AI",aiCannotApprove:"AI tidak dapat menandatangani atau menyetujui."},
};

export function translate(locale:WalletLocale,key:MessageKey):string{return key in UI_MESSAGES[locale]?UI_MESSAGES[locale][key as UIMessageKey]:MESSAGES[locale][key as BaseMessageKey]}
export function isRTL(locale:WalletLocale):boolean{return locale==="ar"}
export function detectLocale(systemLocale:string|undefined):WalletLocale{const normalized=(systemLocale??"").replace("_","-").toLowerCase();if(normalized.startsWith("zh-hant")||normalized.includes("-tw")||normalized.includes("-hk"))return"zh-Hant";if(normalized.startsWith("zh"))return"zh-Hans";return SUPPORTED_LOCALES.find((item)=>normalized===item.toLowerCase()||normalized.startsWith(`${item.toLowerCase()}-`))??"en"}
export async function loadLocale(storage:SecureStorageAdapter,systemLocale=Intl.DateTimeFormat().resolvedOptions().locale):Promise<WalletLocale>{const saved=await storage.getItem(LOCALE_PREFERENCE_KEY);return saved!==null&&SUPPORTED_LOCALES.includes(saved as WalletLocale)?saved as WalletLocale:detectLocale(systemLocale)}
export async function saveLocale(storage:SecureStorageAdapter,locale:WalletLocale):Promise<void>{if(!SUPPORTED_LOCALES.includes(locale))throw new Error("Unsupported Wallet locale");await storage.setItem(LOCALE_PREFERENCE_KEY,locale)}
export function formatDateTime(locale:WalletLocale,value:string|Date):string{return new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeStyle:"short",timeZone:"UTC"}).format(new Date(value))}
export function formatNumber(locale:WalletLocale,value:number):string{return new Intl.NumberFormat(locale,{maximumFractionDigits:8}).format(value)}
export function formatYNXT(locale:WalletLocale,value:number):string{return `${formatNumber(locale,value)} YNXT`}
export function plural(locale:WalletLocale,count:number,forms:{one:string;other:string}):string{return new Intl.PluralRules(locale).select(count)==="one"?forms.one:forms.other}
export function allMessages():Readonly<Record<WalletLocale,Readonly<Record<MessageKey,string>>>>{return Object.fromEntries(SUPPORTED_LOCALES.map((locale)=>[locale,{...MESSAGES[locale],...UI_MESSAGES[locale]}])) as Record<WalletLocale,Record<MessageKey,string>>}
export function localizeError(locale:WalletLocale,value:unknown):string{const detail=value instanceof Error?value.message:String(value);return `${translate(locale,"errorPrefix")}: ${detail}`}
