import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import ts from 'typescript';
const source=fs.readFileSync(new URL('../App.tsx',import.meta.url),'utf8');
const moments=source.slice(source.indexOf('function Moments('));
function section(begin,end){const start=moments.indexOf(begin),finish=moments.indexOf(end,start);assert.ok(start>=0&&finish>start);return moments.slice(start,finish)}
const refs=section('  const momentSending=','  useEffect(');
const functions=section('  const pickMedia =','  const react =');
const code=ts.transpileModule(`${refs}\n${functions}\nreturn {restoreOriginalMoment,startMomentComposer,closeMomentComposer,pickMedia,publish,editText:value=>{invalidateMomentComposer();setText(value)},editVisibility:value=>{invalidateMomentComposer();setVisibility(value)}}`,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;
function deferred(){let resolve,reject;const promise=new Promise((yes,no)=>{resolve=yes;reject=no});return {promise,resolve,reject}}
const original={text:'Original uncertain draft',visibility:'private',media:[{id:'old-media',uri:'file:///old.png'}]};
function fixture(){
 const view={compose:false,text:'Original draft',visibility:'private',media:[],error:null,uploads:0,sends:0,loads:0,alerts:[]};const read=deferred(),permission=deferred(),picker=deferred(),upload=deferred(),send=deferred();
 const api={authorizationGuard:()=>()=>true,uploadMedia:()=>{view.uploads++;return upload.promise}};
 const args={useRef:value=>({current:value}),api,momentIntents:{load:()=>read.promise},session:{session:{account:'ynx1'+'a'.repeat(38)}},ImagePicker:{requestMediaLibraryPermissionsAsync:()=>permission.promise,launchImageLibraryAsync:()=>picker.promise},digest:async()=>new Uint8Array(32).buffer,CryptoDigestAlgorithm:{SHA256:'fixture'},setCompose:value=>view.compose=value,setText:value=>view.text=value,setVisibility:value=>view.visibility=value,setMedia:value=>view.media=typeof value==='function'?value(view.media):value,setError:value=>view.error=value,load:async current=>{if(!current||current())view.loads++},message:String,Alert:{alert:(title,body,buttons)=>view.alerts.push(buttons)},publishOriginalNativeMoment:async()=>{view.sends++;return send.promise},text:view.text,visibility:view.visibility,media:view.media};
 const owner=new Function(...Object.keys(args),code)(...Object.values(args));return {owner,view,read,permission,picker,upload,send};
}
for(const published of [false,true])test(`late restore cannot ${published?'close':'overwrite'} a newly opened same-account composer`,async()=>{
 const f=fixture();const pending=f.owner.restoreOriginalMoment();f.owner.startMomentComposer();f.view.text='New reviewed draft';f.view.media=[{id:'new-media',uri:'file:///new.png'}];f.read.resolve({...original,...(published?{publishedRecordId:'old-record'}:{})});await pending;
 assert.equal(f.view.compose,true);assert.equal(f.view.text,'New reviewed draft');assert.equal(f.view.media[0].id,'new-media');assert.equal(f.view.loads,0);
});
test('closing or editing retires an outstanding restore without reopening or overwriting',async()=>{
 for(const retire of ['closeMomentComposer','editText','editVisibility']){const f=fixture();f.owner.startMomentComposer();const pending=f.owner.restoreOriginalMoment();f.owner[retire]('new');f.read.resolve(original);await pending;assert.notEqual(f.view.text,original.text);if(retire==='closeMomentComposer')assert.equal(f.view.compose,false)}
});
test('retired restore error does not replace the newer view error',async()=>{const f=fixture();const pending=f.owner.restoreOriginalMoment();f.owner.startMomentComposer();f.view.error='New view notice';f.read.reject(Error('Old storage error'));await pending;assert.equal(f.view.error,'New view notice')});
test('current restore retains original fields and supplies independently editable media',async()=>{const f=fixture();const pending=f.owner.restoreOriginalMoment();f.read.resolve(original);await pending;assert.equal(f.view.compose,true);assert.equal(f.view.text,original.text);assert.deepEqual(f.view.media,original.media);assert.notEqual(f.view.media,original.media);assert.notEqual(f.view.media[0],original.media[0])});
test('picker permission completion after close never starts the picker or upload',async()=>{const f=fixture();f.owner.startMomentComposer();const pending=f.owner.pickMedia();f.owner.closeMomentComposer();f.permission.resolve({granted:true});await pending;assert.equal(f.view.uploads,0);assert.deepEqual(f.view.media,[])});
test('late image upload does not attach to a newer composer',async()=>{const f=fixture();f.owner.startMomentComposer();const pending=f.owner.pickMedia();f.permission.resolve({granted:true});await new Promise(setImmediate);f.picker.resolve({canceled:false,assets:[{base64:'eA==',uri:'file:///fixture',fileSize:1}]});await new Promise(setImmediate);assert.equal(f.view.uploads,1);f.owner.startMomentComposer();f.view.media=[{id:'new-media',uri:'file:///new.png'}];f.upload.resolve({record:{id:'old-upload'}});await pending;assert.equal(f.view.media[0].id,'new-media')});
test('late picker failure cannot write the new composer error',async()=>{const f=fixture();const pending=f.owner.pickMedia();f.owner.startMomentComposer();f.view.error='New notice';f.permission.reject(Error('Old permission error'));await pending;assert.equal(f.view.error,'New notice')});
test('retired publish review never sends the original payload',async()=>{const f=fixture();f.owner.startMomentComposer();f.owner.publish();f.owner.editText('New draft');await f.view.alerts[0].find(button=>button.text==='Publish').onPress();assert.equal(f.view.sends,0)});
test('late publish completion cannot close or clear a newly opened composer',async()=>{const f=fixture();f.owner.startMomentComposer();f.owner.publish();f.view.alerts[0].find(button=>button.text==='Publish').onPress();assert.equal(f.view.sends,1);f.owner.startMomentComposer();f.view.text='New draft';f.send.resolve(true);await new Promise(setImmediate);assert.equal(f.view.compose,true);assert.equal(f.view.text,'New draft');assert.equal(f.view.loads,0)});
