import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import ts from 'typescript';
const source=fs.readFileSync(new URL('../App.tsx',import.meta.url),'utf8'),moments=source.slice(source.indexOf('function Moments('));
const start=moments.indexOf('  const load = async ('),end=moments.indexOf('\n  useEffect(',start);assert.ok(start>=0&&end>start);
const body=ts.transpileModule(moments.slice(start,end),{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;
function gate(){let resolve,reject;const promise=new Promise((yes,no)=>{resolve=yes;reject=no});return {promise,resolve,reject}}
function fixture(){const view={loading:false,items:[],error:null},requests=[],mounted={current:true},loadingOwner={current:null};let authorized=true;
 const load=new Function('api','momentMounted','momentFeedLoadingOwner','setLoading','setItems','setError','message',body+';return load;')({authorizationGuard:()=>()=>authorized,feed:()=>{const request=gate();requests.push(request);return request.promise}},mounted,loadingOwner,v=>view.loading=v,v=>view.items=v,v=>view.error=v,String);
 return {view,requests,mounted,load,retireAuthority:()=>authorized=false};
}
test('retired composer load releases only its own spinner without writing old feed',async()=>{const f=fixture();let current=true;const pending=f.load(()=>current);assert.equal(f.view.loading,true);current=false;f.requests[0].resolve({posts:[{id:'old'}]});await pending;assert.deepEqual(f.view.items,[]);assert.equal(f.view.loading,false)});
test('older load cannot clear a still-pending newer load spinner',async()=>{const f=fixture(),old=f.load(),next=f.load();f.requests[0].resolve({posts:[{id:'old'}]});await old;assert.equal(f.view.loading,true);assert.deepEqual(f.view.items,[]);f.requests[1].resolve({posts:[{id:'new'}]});await next;assert.equal(f.view.loading,false);assert.equal(f.view.items[0].id,'new')});
test('older late success cannot replace a newer completed feed',async()=>{const f=fixture(),old=f.load(),next=f.load();f.requests[1].resolve({posts:[{id:'new'}]});await next;f.requests[0].resolve({posts:[{id:'old'}]});await old;assert.equal(f.view.items[0].id,'new');assert.equal(f.view.loading,false)});
test('retired composer error releases its spinner without replacing the new notice',async()=>{const f=fixture();let current=true;const pending=f.load(()=>current);current=false;f.view.error='New view notice';f.requests[0].reject(Error('Old network failure'));await pending;assert.equal(f.view.error,'New view notice');assert.equal(f.view.loading,false)});
test('old error cannot replace a newer error or spinner ownership',async()=>{const f=fixture(),old=f.load(),next=f.load();f.requests[1].reject(Error('New failure'));await next;f.requests[0].reject(Error('Old failure'));await old;assert.equal(f.view.error,String(Error('New failure')));assert.equal(f.view.loading,false)});
test('current success and error recover through an explicit new load',async()=>{const f=fixture(),bad=f.load();f.requests[0].reject(Error('Network unavailable'));await bad;assert.equal(f.view.loading,false);assert.equal(f.view.error,String(Error('Network unavailable')));const retry=f.load();f.requests[1].resolve({posts:[{id:'recovered'}]});await retry;assert.equal(f.view.loading,false);assert.equal(f.view.error,null);assert.equal(f.view.items[0].id,'recovered')});
test('authority loss suppresses data while releasing only this load spinner',async()=>{const f=fixture(),pending=f.load();f.retireAuthority();f.requests[0].resolve({posts:[{id:'private-old'}]});await pending;assert.deepEqual(f.view.items,[]);assert.equal(f.view.loading,false)});
test('unmounted completion does not update React state',async()=>{const f=fixture(),pending=f.load();f.mounted.current=false;f.requests[0].resolve({posts:[{id:'old'}]});await pending;assert.deepEqual(f.view.items,[]);assert.equal(f.view.loading,true)});
test('retired owner at entry cannot start a request or steal spinner ownership',async()=>{const f=fixture(),old=f.load();await f.load(()=>false);assert.equal(f.requests.length,1);assert.equal(f.view.loading,true);f.requests[0].resolve({posts:[]});await old;assert.equal(f.view.loading,false)});
