import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from'node:fs';import{createHash}from'node:crypto';import{createRequire}from'node:module';import{resolve}from'node:path';
const config=JSON.parse(readFileSync(new URL('../vercel.json',import.meta.url))),html=readFileSync(new URL('./fixtures/matrix-login-callback-reviewed.html',import.meta.url),'utf8'),digest=x=>createHash('sha256').update(x).digest('base64'),callback='/matrix/login/callback';
const original=[{source:'/sso/:path*',destination:'https://api.ynxweb4.com/social/sso/:path*'},{source:'/social/:path*',destination:'https://api.ynxweb4.com/social/:path*'},{source:'/wallet-auth/callback',destination:'/index.html'}];
const headers=path=>Object.fromEntries(config.headers.find(x=>x.source===path).headers.map(x=>[x.key.toLowerCase(),x.value]));
test('original API and Cloud prefix routing and build settings remain unchanged',()=>{assert.deepEqual(config.rewrites.slice(1),original);assert.deepEqual({framework:config.framework,installCommand:config.installCommand,buildCommand:config.buildCommand,outputDirectory:config.outputDirectory},{framework:null,installCommand:'npm ci --ignore-scripts --no-audit --no-fund',buildCommand:'npm run web:build',outputDirectory:'web/dist'});assert.equal(config.rewrites.length,4)});
test('callback has one exact standalone local rewrite before ordinary routing',()=>{assert.deepEqual(config.rewrites[0],{source:callback,destination:'/matrix/login-callback.html'});assert(!config.redirects);assert.equal(new Set(config.rewrites.map(x=>x.source)).size,4)});
test('canonical callback and direct assets receive no-store/no-referrer before content',()=>{assert.deepEqual(config.headers.map(x=>x.source),[callback,'/matrix/login-callback.html','/matrix/login-callback-entry.mjs']);for(const path of config.headers.map(x=>x.source)){const h=headers(path);assert.equal(h['cache-control'],'no-store, max-age=0');assert.equal(h['cdn-cache-control'],'no-store');assert.equal(h['vercel-cdn-cache-control'],'no-store');assert.equal(h['referrer-policy'],'no-referrer');assert.equal(h['x-content-type-options'],'nosniff');assert.equal(h['x-frame-options'],'DENY');assert(!h['cross-origin-opener-policy']);assert.equal(new Set(config.headers.find(x=>x.source===path).headers.map(x=>x.key.toLowerCase())).size,7)}});
test('CSP pins exact reviewed inline bytes without unsafe evaluation or network',()=>{const scripts=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)],styles=[...html.matchAll(/<style>([\s\S]*?)<\/style>/g)];assert.equal(scripts.length,1);assert.equal(styles.length,1);const csp=headers(callback)['content-security-policy'];assert.equal(csp,`default-src 'none'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'; script-src 'self' 'sha256-${digest(scripts[0][1])}'; style-src 'sha256-${digest(styles[0][1])}'; img-src 'self'; connect-src 'none'`);assert(!/unsafe-inline|unsafe-eval|\*|https:/.test(csp));assert(!csp.includes(digest(scripts[0][1]+'changed')))});
test('reviewed callback scrubs before standalone import and has no chat bootstrap',()=>{assert.equal(createHash('sha256').update(html).digest('hex'),'acff1b697a57a57ea8a7632f64ce75a5b11b08f0fba5d4d573ed849c2c4255d7');assert(html.indexOf("replaceState(null, '', '/matrix/login/callback')")<html.indexOf("import('/matrix/login-callback-entry.mjs')"));assert(!/matrix-session-ui|private-session-ui|matrix_sdk_crypto_wasm/.test(html))});
test('actual Chromium executes original standalone callback under configured headers and retains opener',async()=>{
 const source=process.env.YNX_QA_SOCIAL_CALLBACK_REFERENCE;if(!source)throw Error('Explicit immutable callback reference is required');const req=createRequire(resolve(source,'apps/social/package.json')),{build}=req('esbuild'),{chromium}=req('playwright');
 const actualHtml=readFileSync(resolve(source,'apps/social/web/matrix/login-callback.html'),'utf8');assert.equal(actualHtml,html);const bundle=await build({absWorkingDir:resolve(source,'apps/social/web'),entryPoints:['matrix/login-callback-entry.mjs'],bundle:true,platform:'browser',format:'esm',target:'es2022',write:false});const js=bundle.outputFiles[0].text;assert(!js.includes('matrix_sdk_crypto_wasm'));
 const browser=await chromium.launch({headless:true});const context=await browser.newContext();const requests=[],state='a'.repeat(64);
 try{
  await context.route('https://social.ynxweb4.com/**',async route=>{const url=new URL(route.request().url());requests.push({path:url.pathname,referrerPresent:Boolean(route.request().headers().referer)});if(url.pathname==='/'){return route.fulfill({contentType:'text/html',body:`<script>window.results=[];addEventListener('message',e=>{if(e.origin==='https://social.ynxweb4.com')results.push({type:e.data.type,stateMatches:e.data.state==='${state}',tokenPresent:typeof e.data.loginToken==='string'&&e.data.loginToken.length>0})})</script><button id="open">Open</button>`})}if(url.pathname===callback||url.pathname==='/matrix/login-callback.html')return route.fulfill({headers:{...headers(url.pathname),'content-type':'text/html; charset=utf-8'},body:html});if(url.pathname==='/matrix/login-callback-entry.mjs')return route.fulfill({headers:{...headers(url.pathname),'content-type':'text/javascript; charset=utf-8'},body:js});return route.fulfill({status:404,body:''})});
  const opener=await context.newPage();await opener.goto('https://social.ynxweb4.com/');await opener.evaluate(({state})=>document.querySelector('#open').onclick=()=>window.open('/matrix/login/callback?state='+state+'&loginToken=SYNTHETIC_NONSECRET_QA','qa-popup'),{state});await opener.click('#open');await opener.waitForFunction(()=>results.length===1);assert.deepEqual(await opener.evaluate(()=>results),[{type:'ynx-social-matrix-login-token',stateMatches:true,tokenPresent:true}]);
  const invalid=await context.newPage();const response=await invalid.goto('https://social.ynxweb4.com'+callback+'?state=invalid&loginToken=SYNTHETIC_NONSECRET_QA');await invalid.waitForFunction(()=>location.search===''&&document.querySelector('#callback-status').textContent.includes('unavailable'));assert.equal(response.headers()['referrer-policy'],'no-referrer');assert.equal(response.headers()['cache-control'],'no-store, max-age=0');assert.equal(await invalid.evaluate(()=>location.pathname),callback);
  await invalid.evaluate(()=>{window.cspViolations=[];addEventListener('securitypolicyviolation',e=>cspViolations.push(e.violatedDirective));const script=document.createElement('script');script.textContent='window.unapprovedInlineRan=true';document.body.append(script);void fetch('/must-not-reach-service').catch(()=>{})});await invalid.waitForFunction(()=>cspViolations.some(x=>x.startsWith('script-src'))&&cspViolations.includes('connect-src'));assert.equal(await invalid.evaluate(()=>Boolean(window.unapprovedInlineRan)),false);assert(!requests.some(x=>x.path==='/must-not-reach-service'));assert(requests.filter(x=>x.path==='/matrix/login-callback-entry.mjs').every(x=>!x.referrerPresent));
 }finally{await context.close();await browser.close()}
});
