import { createHash, randomUUID } from "node:crypto";
import { DatabaseSync } from "node:sqlite";

const PROTOCOL = "ynx-code-agent/v1", MAX_BODY = 640 * 1024;
export function createAgentOrchestrator({ filename, ownerForRequest, workspaceStore, modelRouter, projectMemory, workspaceRuntime }) {
  const db = new DatabaseSync(filename);
  db.exec("PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL; PRAGMA busy_timeout=5000; CREATE TABLE IF NOT EXISTS agent_runs(owner_id TEXT NOT NULL,run_id TEXT NOT NULL,project_id TEXT NOT NULL,status TEXT NOT NULL,provider TEXT NOT NULL,model TEXT NOT NULL,intent TEXT NOT NULL,workspace_revision INTEGER NOT NULL,plan TEXT,approved_paths TEXT NOT NULL DEFAULT '[]',proposal TEXT,review TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,PRIMARY KEY(owner_id,run_id)); CREATE TABLE IF NOT EXISTS agent_events(owner_id TEXT NOT NULL,run_id TEXT NOT NULL,sequence INTEGER NOT NULL,event_type TEXT NOT NULL,payload TEXT NOT NULL,previous_hash TEXT NOT NULL,event_hash TEXT NOT NULL,created_at TEXT NOT NULL,PRIMARY KEY(owner_id,run_id,sequence));");
  const getRun = db.prepare("SELECT * FROM agent_runs WHERE owner_id=? AND run_id=?"), listRuns = db.prepare("SELECT * FROM agent_runs WHERE owner_id=? AND project_id=? ORDER BY created_at DESC LIMIT 50"), insertRun = db.prepare("INSERT INTO agent_runs(owner_id,run_id,project_id,status,provider,model,intent,workspace_revision,plan,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)"), updateRun = db.prepare("UPDATE agent_runs SET status=?,plan=?,approved_paths=?,proposal=?,review=?,workspace_revision=?,updated_at=? WHERE owner_id=? AND run_id=?"), lastEvent = db.prepare("SELECT sequence,event_hash FROM agent_events WHERE owner_id=? AND run_id=? ORDER BY sequence DESC LIMIT 1"), insertEvent = db.prepare("INSERT INTO agent_events(owner_id,run_id,sequence,event_type,payload,previous_hash,event_hash,created_at) VALUES(?,?,?,?,?,?,?,?)"), events = db.prepare("SELECT sequence,event_type,payload,previous_hash,event_hash,created_at FROM agent_events WHERE owner_id=? AND run_id=? ORDER BY sequence");
  const append = (owner, runId, type, payload) => { const previous = lastEvent.get(owner, runId), sequence = Number(previous?.sequence || 0) + 1, previousHash = previous?.event_hash || "0".repeat(64), serialized = stable(payload), eventHash = createHash("sha256").update(`${previousHash}:${sequence}:${type}:${serialized}`).digest("hex"), createdAt = new Date().toISOString(); insertEvent.run(owner,runId,sequence,type,serialized,previousHash,eventHash,createdAt); return eventHash; };
  const read = (owner, runId) => { const row = getRun.get(owner,runId); return row ? record(row,events.all(owner,runId)) : null; };
  async function handler(request,response) {
    const url = new URL(request.url,`http://${request.headers.host||"127.0.0.1"}`); if (!url.pathname.startsWith("/runtime/agent/runs")) return false;
    const owner = ownerForRequest(request); if (!owner) return json(response,401,{error:"A signed workspace session is required.",code:"workspace_session_required"}),true;
    const clientController=new AbortController(),abortClient=()=>clientController.abort();request.once("aborted",abortClient);response.once("close",()=>{if(!response.writableEnded)abortClient()});
    try {
      const id = url.pathname.split("/")[4] || "";
      if (request.method === "GET") { if (id) { const run=read(owner,id); if(!run) throw fault("Agent run not found.","agent_run_not_found",404); json(response,200,{protocolVersion:PROTOCOL,run}); } else { const projectId=validId(url.searchParams.get("projectId"),"project"); json(response,200,{protocolVersion:PROTOCOL,runs:listRuns.all(owner,projectId).map(row=>record(row,[]))}); } return true; }
      if (request.method !== "POST") throw fault("Method not allowed.","method_not_allowed",405);
      const body=JSON.parse((await readBody(request)).toString("utf8")); Object.defineProperty(body,"requestSignal",{value:clientController.signal,enumerable:false}); if(body.protocolVersion!==PROTOCOL) throw fault("Agent protocol version is required.","protocol_mismatch",400);
      if (!id) { const projectId=validId(body.projectId,"project"), intent=text(body.intent,4,12000,"intent"), workspace=workspaceStore.get(owner,projectId); if(!workspace) throw fault("Workspace not found.","workspace_not_found",404); const model=await modelRouter.generate(modelInput(body,"Planner",`Create a concise implementation plan for this request. Return JSON only as {\"summary\":string,\"steps\":[{\"title\":string,\"acceptance\":string}],\"contextPaths\":[string]}. Available paths: ${Object.keys(workspace.files).join(", ")}\nRequest: ${intent}`,clientController.signal)), plan=validatePlan(parseJson(model.text),workspace.files), runId=randomUUID(), now=new Date().toISOString(); insertRun.run(owner,runId,projectId,"plan_review",model.provider,model.model,intent,workspace.revision,stable(plan),now,now); append(owner,runId,"planner.completed",{provider:model.provider,model:model.model,plan}); json(response,201,{protocolVersion:PROTOCOL,run:read(owner,runId)}); return true; }
      const current=read(owner,id); if(!current) throw fault("Agent run not found.","agent_run_not_found",404); const workspace=workspaceStore.get(owner,current.projectId); if(!workspace) throw fault("Workspace not found.","workspace_not_found",404);
      if(body.action==="approve-plan") { requireState(current,"plan_review"); persist({...current,status:"context_review"}); append(owner,id,"plan.approved",{approval:"explicit"}); }
      else if(body.action==="approve-context") { requireState(current,"context_review"); const paths=validatePaths(body.paths,workspace.files); persist({...current,status:"proposal_generation",approvedPaths:paths}); append(owner,id,"context.approved",{paths,digests:Object.fromEntries(paths.map(path=>[path,sha(workspace.files[path])]))}); }
      else if(body.action==="generate-proposal") { requireState(current,"proposal_generation"); const context=current.approvedPaths.map(path=>`--- ${path} sha256=${sha(workspace.files[path])} ---\n${workspace.files[path]}`).join("\n"), memory=projectMemory?await projectMemory.search(owner,current.projectId,current.intent,8,current.approvedPaths).catch(()=>null):null, memoryContext=memory?.indexedRevision===workspace.revision?memory.results.map(result=>result.content).join("\n"):"", generated=await generateValidatedProposal(modelRouter,body,`Implement the approved plan. Return JSON only as {\"summary\":string,\"edits\":[{\"path\":string,\"expectedDigest\":string,\"replacements\":[{\"find\":string,\"replace\":string}]}]}. Use exact non-empty find text that occurs once. Keep the response compact; never return unchanged files.\nPlan: ${stable(current.plan)}\nApproved semantic memory:\n${memoryContext}\nApproved context:\n${context}`,workspace.files,current.approvedPaths),coder=generated.coder,proposal=generated.proposal, reviewed=await generateValidatedReview(modelRouter,body,`Review this proposed patch for correctness, security, and missing tests. Return JSON only as {\"approved\":boolean,\"summary\":string,\"findings\":[string]}.\nIntent: ${current.intent}\nProposal: ${stable(proposal)}`),review=reviewed.review; persist({...current,status:"diff_review",proposal,review,provider:coder.provider,model:coder.model}); append(owner,id,"coder.proposed",{provider:coder.provider,model:coder.model,memoryRevision:memory?.indexedRevision??null,validationAttempts:generated.attempts,files:proposal.files.map(file=>({path:file.path,digest:sha(file.content),bytes:Buffer.byteLength(file.content)}))}); append(owner,id,"reviewer.completed",{...review,validationAttempts:reviewed.attempts}); }
      else if(body.action==="revise-proposal") { requireState(current,"diff_review");if(current.review?.approved)throw fault("Only a Reviewer-blocked proposal can be revised.","revision_not_required",409);const context=current.approvedPaths.map(path=>`--- ${path} sha256=${sha(workspace.files[path])} ---\n${workspace.files[path]}`).join("\n"),generated=await generateValidatedProposal(modelRouter,body,`Revise the rejected patch to satisfy the user intent and every Reviewer finding. Preserve all unrelated imports, declarations, and behavior. Prefer the smallest exact replacement. Return JSON only as {"summary":string,"edits":[{"path":string,"expectedDigest":string,"replacements":[{"find":string,"replace":string}]}]}.\nIntent: ${current.intent}\nRejected proposal: ${stable(current.proposal)}\nReviewer: ${stable(current.review)}\nApproved context:\n${context}`,workspace.files,current.approvedPaths),coder=generated.coder,proposal=generated.proposal,reviewed=await generateValidatedReview(modelRouter,body,`Review this revised patch against the exact user intent and approved source. Approve a minimal behavior-preserving edit when it satisfies the request. Return JSON only as {"approved":boolean,"summary":string,"findings":[string]}.\nIntent: ${current.intent}\nApproved source:\n${context}\nRevised proposal: ${stable(proposal)}`),review=reviewed.review;persist({...current,status:"diff_review",proposal,review,provider:coder.provider,model:coder.model});append(owner,id,"coder.revised",{provider:coder.provider,model:coder.model,validationAttempts:generated.attempts,files:proposal.files.map(file=>({path:file.path,digest:sha(file.content)}))});append(owner,id,"reviewer.revision_completed",{...review,validationAttempts:reviewed.attempts}); }
      else if(body.action==="apply") { requireState(current,"diff_review"); if(body.approval!=="write-once") throw fault("One-time write approval is required.","write_approval_required",403); if(!current.review?.approved) throw fault("Reviewer did not approve this proposal.","review_not_approved",409); if(workspace.revision!==current.workspaceRevision) throw fault("Workspace changed after agent context capture.","revision_conflict",409); const files={...workspace.files}; for(const file of current.proposal.files) files[file.path]=file.content; const folders=[...new Set([...workspace.folders,...current.proposal.files.flatMap(file=>parents(file.path))])].sort(), applyAttempt=current.events.filter(event=>event.event_type==="write.applied").length+1,saved=workspaceStore.put(owner,current.projectId,{expectedRevision:workspace.revision,idempotencyKey:`agent-${id}-${applyAttempt}`,payload:{name:workspace.name,files,folders,open:workspace.open,active:workspace.active}}); persist({...current,status:"applied",workspaceRevision:saved.revision}); append(owner,id,"write.applied",{approval:"write-once",attempt:applyAttempt,revision:saved.revision,files:current.proposal.files.map(file=>file.path)}); }
      else if(body.action==="run-test") { requireState(current,"applied"); if(body.approval!=="execute-once")throw fault("One-time execute approval is required.","execute_approval_required",403);if(!workspaceRuntime)throw fault("Workspace runtime is unavailable.","runtime_unavailable",503);const activePath=safePath(body.activePath),latest=workspaceStore.get(owner,current.projectId);if(!Object.hasOwn(latest.files,activePath))throw fault("Test entry file was not found.","test_entry_not_found",400);const result=await workspaceRuntime.runTaskForOwner(owner,{protocolVersion:"ynx-code/v1",task:"build-run-active",projectId:current.projectId,activePath,files:latest.files,approval:"execute-once"});persist({...current,status:result.ok?"tested":"test_failed",workspaceRevision:latest.revision});append(owner,id,"tester.completed",{approval:"execute-once",activePath,result}); }
      else if(body.action==="generate-fix") { requireState(current,"test_failed");const latest=workspaceStore.get(owner,current.projectId),failure=current.events.findLast(event=>event.event_type==="tester.completed")?.payload.result;if(!failure||failure.ok)throw fault("No failed Tester evidence is available.","test_evidence_missing",409);const context=current.approvedPaths.map(path=>`--- ${path} sha256=${sha(latest.files[path])} ---\n${latest.files[path]}`).join("\n"),generated=await generateValidatedProposal(modelRouter,body,`Fix the exact Tester failure. Return JSON only as {\"summary\":string,\"edits\":[{\"path\":string,\"expectedDigest\":string,\"replacements\":[{\"find\":string,\"replace\":string}]}]}. Use exact non-empty find text that occurs once and ensure the materialized file changes.\nTester evidence:\n${failure.output}\nApproved current context:\n${context}`,latest.files,current.approvedPaths),coder=generated.coder,proposal=generated.proposal,reviewed=await generateValidatedReview(modelRouter,body,`Review whether this fix addresses the exact Tester evidence without unrelated changes. Return JSON only as {\"approved\":boolean,\"summary\":string,\"findings\":[string]}.\nFailure: ${failure.output}\nFix: ${stable(proposal)}`),review=reviewed.review;persist({...current,status:"diff_review",proposal,review,workspaceRevision:latest.revision});append(owner,id,"coder.fix_proposed",{provider:coder.provider,model:coder.model,validationAttempts:generated.attempts,failureTaskId:failure.taskId,files:proposal.files.map(file=>({path:file.path,digest:sha(file.content)}))});append(owner,id,"reviewer.fix_completed",{...review,validationAttempts:reviewed.attempts}); }
      else throw fault("Unknown agent action.","invalid_agent_action",400);
      json(response,200,{protocolVersion:PROTOCOL,run:read(owner,id)}); return true;
      function persist(value){ const now=new Date().toISOString(); updateRun.run(value.status,nullable(value.plan),stable(value.approvedPaths||[]),nullable(value.proposal),nullable(value.review),value.workspaceRevision,now,owner,id); }
    } catch(error) { if(response.destroyed||response.writableEnded)return true; json(response,error.status||400,{error:error.message||"Agent operation failed.",code:error.code||"agent_operation_failed"}); return true; }
  }
  return {handler,read,close:()=>db.close()};
}
function modelInput(body,role,prompt,signal){const limits={Planner:384,Coder:1024,Reviewer:512};return{provider:body.provider||"ynx-hosted",model:body.model,apiKey:body.apiKey,system:`You are the YNX Code ${role} Agent. Never claim tools ran without supplied evidence. Follow the JSON schema exactly.`,prompt,outputLanguage:body.outputLanguage||"en",maxOutputTokens:limits[role]||1024,responseFormat:"json",signal:signal||body.requestSignal};}
function record(row,eventRows){return{runId:row.run_id,projectId:row.project_id,status:row.status,provider:row.provider,model:row.model,intent:row.intent,workspaceRevision:Number(row.workspace_revision),plan:parseNullable(row.plan),approvedPaths:JSON.parse(row.approved_paths||"[]"),proposal:parseNullable(row.proposal),review:parseNullable(row.review),createdAt:row.created_at,updatedAt:row.updated_at,events:eventRows.map(event=>({...event,payload:JSON.parse(event.payload)}))};}
function validatePlan(value,files){if(!value||typeof value.summary!=="string"||!Array.isArray(value.steps)||value.steps.length<1||value.steps.length>24)throw fault("Planner returned an invalid plan.","invalid_agent_plan",502);return{summary:text(value.summary,1,2000,"summary"),steps:value.steps.map(step=>({title:text(step?.title,1,200,"step title"),acceptance:text(step?.acceptance,1,1000,"acceptance") })),contextPaths:validatePaths(value.contextPaths||[],files)};}
function materializeProposal(value,files,approvedPaths){if(!value||typeof value.summary!=="string"||!Array.isArray(value.edits)||value.edits.length<1||value.edits.length>64)throw fault("Coder returned an invalid edit proposal.","invalid_agent_proposal",502);const approved=new Set(approvedPaths),paths=new Set(),output=[];let bytes=0;for(const edit of value.edits){const path=safePath(modelPath(edit?.path,approvedPaths));if(paths.has(path)||!approved.has(path)||typeof files[path]!=="string")throw fault("Edit path was not approved or is duplicated.","invalid_agent_proposal",502);paths.add(path);if(edit.expectedDigest!==sha(files[path]))throw fault("Edit digest does not match approved context.","proposal_digest_mismatch",409);if(!Array.isArray(edit.replacements)||edit.replacements.length<1||edit.replacements.length>64)throw fault("Edit replacements are invalid.","invalid_agent_proposal",502);let content=files[path];for(const replacement of edit.replacements){const find=typeof replacement?.find==="string"?replacement.find:"",replace=typeof replacement?.replace==="string"?replacement.replace:"";if(!find||find.length>256*1024||replace.length>512*1024)throw fault("Replacement exceeds its boundary.","invalid_agent_proposal",502);const first=content.indexOf(find);if(first<0||content.indexOf(find,first+find.length)>=0)throw fault("Replacement source must match exactly once.","proposal_match_conflict",409);content=`${content.slice(0,first)}${replace}${content.slice(first+find.length)}`;}if(sha(content)===sha(files[path]))throw fault("Proposal did not change the approved file.","proposal_noop",409);bytes+=Buffer.byteLength(content);if(bytes>2*1024*1024)throw fault("Proposal exceeds workspace boundary.","invalid_agent_proposal",502);output.push({path,content});}return{summary:text(value.summary,1,2000,"summary"),files:output};}
function modelPath(value,approvedPaths=[]){if(typeof value!=="string")return value;let path=value.trim().replaceAll("`","");if(((path.startsWith('"')&&path.endsWith('"'))||(path.startsWith("'")&&path.endsWith("'"))||(path.startsWith("<")&&path.endsWith(">")))&&path.length>2)path=path.slice(1,-1).trim();if(path.startsWith("./"))path=path.slice(2);if(approvedPaths.includes(path))return path;const matches=approvedPaths.filter(approved=>path.includes(approved));return matches.length===1?matches[0]:path;}
async function generateValidatedProposal(modelRouter,body,prompt,files,approvedPaths){let lastError;const boundedPrompt=`${prompt}\nAllowed path values: ${JSON.stringify(approvedPaths)}. Every path field must equal one of these strings exactly.`;for(let attempt=1;attempt<=2;attempt++){const coder=await modelRouter.generate(modelInput(body,"Coder",attempt===1?boundedPrompt:`${boundedPrompt}\nYour previous proposal failed server validation: ${lastError.message}. Correct that exact issue and return JSON only.`));try{return{coder,proposal:materializeProposal(parseJson(coder.text),files,approvedPaths),attempts:attempt}}catch(error){lastError=error}}throw lastError;}
async function generateValidatedReview(modelRouter,body,prompt){let lastError;for(let attempt=1;attempt<=2;attempt++){const reviewer=await modelRouter.generate(modelInput(body,"Reviewer",attempt===1?prompt:`${prompt}\nYour previous review failed server validation: ${lastError.message}. Correct the schema and return JSON only.`));try{return{reviewer,review:validateReview(parseJson(reviewer.text)),attempts:attempt}}catch(error){lastError=error}}throw lastError;}
function validateReview(value){if(!value||typeof value.approved!=="boolean"||typeof value.summary!=="string"||!Array.isArray(value.findings))throw fault("Reviewer returned an invalid result.","invalid_agent_review",502);return{approved:value.approved,summary:text(value.summary,1,2000,"review summary"),findings:value.findings.slice(0,50).map(normalizeFinding)};}
function normalizeFinding(value){if(typeof value==="string")return text(value,1,1000,"finding");if(!value||typeof value!=="object"||Array.isArray(value))throw fault("Reviewer returned an invalid finding.","invalid_agent_review",502);const message=typeof value.message==="string"?value.message:typeof value.description==="string"?value.description:typeof value.title==="string"?value.title:null;if(!message)throw fault("Reviewer returned an invalid finding.","invalid_agent_review",502);const severity=typeof value.severity==="string"&&/^(info|low|medium|high|critical)$/i.test(value.severity.trim())?`${value.severity.trim().toLowerCase()}: `:"";return text(`${severity}${message}`,1,1000,"finding");}
function validatePaths(value,files){if(!Array.isArray(value)||value.length>64)throw fault("Invalid context path selection.","invalid_context_paths",400);return[...new Set(value.map(path=>safePath(path)))].filter(path=>Object.hasOwn(files,path));}
function safePath(value){if(typeof value!=="string"||value.length<1||value.length>240||value.startsWith("/")||value.includes("\\")||value.split("/").some(part=>!part||part==="."||part==="..")||!/^[A-Za-z0-9_./ +@-]+$/.test(value))throw fault("Unsafe workspace path.","unsafe_workspace_path",400);return value;}
function parents(path){const parts=path.split("/").slice(0,-1);return parts.map((_,index)=>parts.slice(0,index+1).join("/"));}
function requireState(run,state){if(run.status!==state)throw fault(`Agent run must be in ${state}.`,"invalid_agent_state",409);}
function validId(value,label){if(typeof value!=="string"||!/^[-A-Za-z0-9_]{1,160}$/.test(value))throw fault(`Invalid ${label} identifier.`,`invalid_${label}`,400);return value;}
function text(value,min,max,label){const result=typeof value==="string"?value.trim():"";if(result.length<min||result.length>max)throw fault(`Invalid ${label}.`,`invalid_${label.replaceAll(" ","_")}`,400);return result;}
function parseJson(value){const source=String(value||"").replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/,"").trim();try{return JSON.parse(source)}catch{}let start=-1,depth=0,string=false,escape=false;for(let index=0;index<source.length;index++){const character=source[index];if(start<0){if(character==="{"){start=index;depth=1}continue}if(string){if(escape)escape=false;else if(character==="\\")escape=true;else if(character==='"')string=false;continue}if(character==='"'){string=true;continue}if(character==="{")depth++;else if(character==="}"&&--depth===0){try{return JSON.parse(source.slice(start,index+1))}catch{break}}}throw fault("Model returned malformed JSON.","malformed_model_output",502)}
function parseNullable(value){return value?JSON.parse(value):null} function nullable(value){return value==null?null:stable(value)} function stable(value){if(Array.isArray(value))return`[${value.map(stable).join(",")}]`;if(value&&typeof value==="object")return`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${stable(value[key])}`).join(",")}}`;return JSON.stringify(value)}
function sha(value){return createHash("sha256").update(value).digest("hex")} function fault(message,code,status){return Object.assign(new Error(message),{code,status})}
async function readBody(request){const chunks=[];let size=0;for await(const chunk of request){size+=chunk.length;if(size>MAX_BODY)throw fault("Request too large.","request_too_large",413);chunks.push(chunk)}return Buffer.concat(chunks)} function json(response,status,value){response.writeHead(status,{"content-type":"application/json; charset=utf-8","cache-control":"no-store"});response.end(JSON.stringify(value))}
export const AGENT_PROTOCOL=PROTOCOL;
