import { useEffect, useRef, useState } from "react";
import { Button } from "../components/ui/button";
import { agentAction, createAgentRun, loadModelCatalog, type AgentRun, type ModelCatalog } from "../runtime/client";

export function AgentPanel({projectId,onApplied}:{projectId:string;onApplied:(revision:number)=>void}) {
  const [catalog,setCatalog]=useState<ModelCatalog>(),[run,setRun]=useState<AgentRun>(),[intent,setIntent]=useState(""),[provider,setProvider]=useState("ynx-hosted"),[model,setModel]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const keyRef=useRef<HTMLInputElement>(null);
  useEffect(()=>{loadModelCatalog().then(setCatalog).catch(error=>setError(error.message))},[]);
  const execute=async(action:"create"|"approve-plan"|"approve-context"|"generate-proposal"|"apply")=>{setBusy(true);setError("");try{const apiKey=keyRef.current?.value||undefined;let next;if(action==="create")next=await createAgentRun({projectId,intent,provider,model:model||undefined,apiKey});else next=await agentAction(run!.runId,{action,provider,model:model||undefined,apiKey,...(action==="approve-context"?{paths:run!.plan?.contextPaths||[]}:{}),...(action==="apply"?{approval:"write-once"}: {})});setRun(next);if(action==="apply")onApplied(next.workspaceRevision)}catch(error){setError(error instanceof Error?error.message:String(error))}finally{if(keyRef.current)keyRef.current.value="";setBusy(false)}};
  const needsKey=provider!=="ynx-hosted";
  return <section className="side-section agent-panel"><header><strong>AI SOFTWARE ENGINEER</strong></header><div className="agent-fields"><select value={provider} onChange={event=>setProvider(event.target.value)}><option value="ynx-hosted">YNX hosted · {catalog?.hosted.model||"Qwen"}</option>{catalog?.bringYourOwnKey.map(item=><option key={item.id} value={item.id}>{item.label} · BYO Key</option>)}</select><input value={model} onChange={event=>setModel(event.target.value)} placeholder="Model (provider default)" />{needsKey&&<input ref={keyRef} type="password" autoComplete="off" placeholder="API key · request only" />}</div>{!run?<><textarea value={intent} onChange={event=>setIntent(event.target.value)} placeholder="Describe the software change and acceptance criteria…"/><Button variant="default" disabled={busy||intent.trim().length<4} onClick={()=>execute("create")}>Create reviewed plan</Button></>:<AgentRunView run={run} busy={busy} execute={execute}/>} {error&&<div className="agent-error">{error}</div>}<div className="honest-boundary">Planner → context approval → Coder → Reviewer → one-time write. Network, terminal, Git and deploy remain separately permissioned.</div></section>;
}
function AgentRunView({run,busy,execute}:{run:AgentRun;busy:boolean;execute:(action:any)=>void}) {return <div className="agent-run"><div className="agent-run-meta"><strong>{run.status.replaceAll("_"," ")}</strong><span>{run.provider} · {run.model}</span></div>{run.plan&&<><p>{run.plan.summary}</p><ol>{run.plan.steps.map((step,index)=><li key={index}><strong>{step.title}</strong><span>{step.acceptance}</span></li>)}</ol></>}{run.proposal&&<div className="agent-proposal"><strong>{run.proposal.summary}</strong>{run.proposal.files.map(file=><code key={file.path}>{file.path}</code>)}</div>}{run.review&&<div className={run.review.approved?"agent-approved":"agent-rejected"}>{run.review.approved?"Reviewer approved":"Reviewer blocked"}: {run.review.summary}</div>}{run.status==="plan_review"&&<Button disabled={busy} onClick={()=>execute("approve-plan")}>Approve plan</Button>}{run.status==="context_review"&&<Button disabled={busy} onClick={()=>execute("approve-context")}>Approve {run.plan?.contextPaths.length||0} context files</Button>}{run.status==="proposal_generation"&&<Button disabled={busy} onClick={()=>execute("generate-proposal")}>Generate + review patch</Button>}{run.status==="diff_review"&&run.review?.approved&&<Button variant="default" disabled={busy} onClick={()=>execute("apply")}>Approve write once</Button>}</div>}
