import assert from "node:assert/strict";
import { test } from "node:test";
import { requestDigest, walletIdentity, type AuthorizationRequest } from "@ynx-chain/wallet-auth";
import { PersistentAuthorizationCallbackStore } from "./authorizationCallbackStore";

const account=walletIdentity(`${"00".repeat(31)}01`).account;
const request={version:"1",nonce:"nonce_abcdefghijklmnopqrstuvwxyz12",chainId:"ynx_6423-1",requestingProduct:"social",productClientId:"ynx-social-v1",bundleId:"com.ynx.social",productDeviceAlgorithm:"p256-sha256",productDeviceKey:"AzrThhqVYhOSUWu1k-8FWD7S5YZvXLYmCjAXI3_Ym5Cv",callback:"ynx-social://com.ynx.social",scopes:["account:read","profile:link"],purpose:"Link account",issuedAt:"2026-07-15T11:59:00.000Z",expiresAt:"2026-07-15T12:04:00.000Z"} as AuthorizationRequest;
const url=`${request.callback}?response=${"A".repeat(64)}`,now=()=>new Date("2026-07-15T12:00:00.000Z");
class Memory{values=new Map<string,string>();async getItem(k:string){return this.values.get(k)??null}async setItem(k:string,v:string){this.values.set(k,v)}async deleteItem(k:string){this.values.delete(k)}}
class Delayed extends Memory{started:Promise<void>;private start!:()=>void;private releaseWrite!:()=>void;private released:Promise<void>;constructor(){super();this.started=new Promise(r=>this.start=r);this.released=new Promise(r=>this.releaseWrite=r)}release(){this.releaseWrite()}override async setItem(k:string,v:string){this.start();await this.released;await super.setItem(k,v)}}

test("pending authorization survives restart without signing twice",async()=>{const storage=new Memory();let creates=0;assert.equal(await new PersistentAuthorizationCallbackStore(storage).prepare(request,account,async()=>{creates++;return url},now),url);assert.equal(await new PersistentAuthorizationCallbackStore(storage).prepare(request,account,async()=>{creates++;return "unused"},now),url);assert.equal(creates,1)});
test("delivery clears response while preserving terminal replay",async()=>{const storage=new Memory(),store=new PersistentAuthorizationCallbackStore(storage);await store.prepare(request,account,async()=>url,now);await store.complete(request,url);const raw=storage.values.get("ynx.wallet.authorization-callbacks.v2")!;assert.equal(raw.includes(url),false);await assert.rejects(store.prepare(request,account,async()=>url,now),/already delivered/)});
test("legacy nonce and same nonce under another digest remain terminal",async()=>{const legacy=new Memory();legacy.values.set("ynx.wallet.auth-nonces.v1",JSON.stringify([[request.nonce,request.expiresAt]]));await assert.rejects(new PersistentAuthorizationCallbackStore(legacy).prepare(request,account,async()=>url,now),/already used/);const storage=new Memory(),store=new PersistentAuthorizationCallbackStore(storage);await store.prepare(request,account,async()=>url,now);await assert.rejects(store.prepare({...request,purpose:"Changed"},account,async()=>url,now),/already used/)});
test("account callback response expiry and lifecycle substitution fail closed",async()=>{const storage=new Memory(),store=new PersistentAuthorizationCallbackStore(storage);await store.prepare(request,account,async()=>url,now);await assert.rejects(store.prepare(request,walletIdentity(`${"00".repeat(31)}02`).account,async()=>url,now),/binding differs/);await assert.rejects(new PersistentAuthorizationCallbackStore(new Memory()).prepare({...request,callback:"attacker://callback"},account,async()=>url,now),/does not match/);await assert.rejects(new PersistentAuthorizationCallbackStore(new Memory()).prepare(request,account,async()=>url,()=>new Date(request.expiresAt)),/expired/);const cancelled=new Memory();await assert.rejects(new PersistentAuthorizationCallbackStore(cancelled).prepare(request,account,async()=>url,now,()=>{throw new Error("backgrounded")}),/backgrounded/);assert.equal(cancelled.values.size,0)});
test("concurrent preparation persists one exact response",async()=>{const storage=new Delayed(),store=new PersistentAuthorizationCallbackStore(storage);let creates=0;const first=store.prepare(request,account,async()=>{creates++;return url},now);await storage.started;const second=store.prepare(request,account,async()=>{creates++;return "unused"},now);storage.release();assert.equal(await first,url);assert.equal(await second,url);assert.equal(creates,1)});
test("tamper and legacy-v2 conflicts fail closed",async()=>{for(const raw of ["bad",JSON.stringify({schemaVersion:2,records:[{requestDigest:requestDigest(request),nonce:request.nonce,expiresAt:request.expiresAt,account,bundleId:request.bundleId,callback:request.callback,state:"delivered",responseURL:url}]})]){const storage=new Memory();storage.values.set("ynx.wallet.authorization-callbacks.v2",raw);await assert.rejects(new PersistentAuthorizationCallbackStore(storage).prepare(request,account,async()=>url,now),/unreadable|must not retain/)}const storage=new Memory(),store=new PersistentAuthorizationCallbackStore(storage);await store.prepare(request,account,async()=>url,now);storage.values.set("ynx.wallet.auth-nonces.v1",JSON.stringify([[request.nonce,request.expiresAt]]));await assert.rejects(store.prepare(request,account,async()=>url,now),/conflicts/)});
test("reconstruction strips expired pending response and retains replay",async()=>{const storage=new Memory(),store=new PersistentAuthorizationCallbackStore(storage);await store.prepare(request,account,async()=>url,now);assert.equal(await store.discardExpired(new Date(request.expiresAt)),1);assert.equal(storage.values.get("ynx.wallet.authorization-callbacks.v2")!.includes(url),false);await assert.rejects(store.prepare(request,account,async()=>url,now),/already delivered/)});
test("explicit rejection clears a pending response and idempotently prevents signing",async()=>{const storage=new Memory(),store=new PersistentAuthorizationCallbackStore(storage);await store.prepare(request,account,async()=>url,now);await store.reject(request,account,now);assert.equal(storage.values.get("ynx.wallet.authorization-callbacks.v2")!.includes(url),false);await store.reject(request,account,now);await assert.rejects(store.prepare(request,account,async()=>url,now),/already delivered/)});
test("rejection without a prior approval creates a terminal tombstone",async()=>{const storage=new Memory(),store=new PersistentAuthorizationCallbackStore(storage);await store.reject(request,account,now);await assert.rejects(store.prepare(request,account,async()=>url,now),/already delivered/);assert.match(storage.values.get("ynx.wallet.authorization-callbacks.v2")!,/"state":"delivered"/)});
