import { parseCentralRegistryEntry, registryParserBinding, type ProductBinding } from "@ynx-chain/wallet-auth";

// Wallet-side reviewed tuples. Central registry deployment remains a separate
// gate: this exact local allow-list only decides which requests Wallet may show.
const REVIEWED_ENTRIES = [
  {
    schemaVersion: 2, productClientId: "ynx-browser-android", requestingProduct: "browser",
    bundleId: "com.ynxweb4.browser", callbacks: ["ynxbrowser://com.ynxweb4.browser/auth/callback"],
    scopes: ["account:read", "browser:wallet-request"], maxScopes: 2,
    productDeviceAlgorithms: ["p256-sha256"],
  },
  {
    schemaVersion: 2, productClientId: "ynx-browser-ios", requestingProduct: "browser",
    bundleId: "com.ynxweb4.browser.ios", callbacks: ["ynxbrowser://com.ynxweb4.browser.ios/auth/callback"],
    scopes: ["account:read", "browser:wallet-request"], maxScopes: 2,
    productDeviceAlgorithms: ["p256-sha256"],
  },
  {
    schemaVersion: 2, productClientId: "ynx-browser-macos", requestingProduct: "browser",
    bundleId: "com.ynxweb4.browser.macos", callbacks: ["ynxbrowser://com.ynxweb4.browser.macos/auth/callback"],
    scopes: ["account:read", "browser:wallet-request"], maxScopes: 2,
    productDeviceAlgorithms: ["p256-sha256"],
  },
  {
    schemaVersion: 2, productClientId: "ynx-browser-windows", requestingProduct: "browser",
    bundleId: "com.ynxweb4.browser.windows", callbacks: ["ynxbrowser://com.ynxweb4.browser.windows/auth/callback"],
    scopes: ["account:read", "browser:wallet-request"], maxScopes: 2,
    productDeviceAlgorithms: ["p256-sha256"],
  },
  {
    schemaVersion: 2, productClientId: "ynx-calendar-v1", requestingProduct: "calendar",
    bundleId: "com.ynxweb4.calendar", callbacks: ["ynxcalendar://wallet-auth/callback"],
    scopes: ["calendar:account", "calendar:recover"], maxScopes: 2,
    productDeviceAlgorithms: ["p256-sha256"],
  },
  {
    schemaVersion: 2, productClientId: "ynx-card-v1", requestingProduct: "ynx-card",
    bundleId: "com.ynxweb4.card", callbacks: ["ynxcard://wallet-auth/callback"],
    scopes: ["account:read", "card:application:write", "card:controls:write", "card:dispute:write"], maxScopes: 4,
    productDeviceAlgorithms: ["p256-sha256"],
  },
  {
    schemaVersion: 2, productClientId: "ynx-cloud-mobile-v1", requestingProduct: "cloud",
    bundleId: "com.ynxweb4.cloud", callbacks: ["ynxcloud://wallet-auth/callback"],
    scopes: ["ai.use", "audit.read", "data.delete", "files.read", "files.write", "permissions.manage"], maxScopes: 6,
    productDeviceAlgorithms: ["p256-sha256"],
  },
  {
    schemaVersion: 2, productClientId: "ynx-cloud-web-v1", requestingProduct: "cloud",
    bundleId: "web.ynx.cloud", callbacks: ["https://web4.ynxweb4.com/cloud/auth/callback"],
    scopes: ["ai.use", "audit.read", "data.delete", "files.read", "files.write", "permissions.manage"], maxScopes: 6,
    productDeviceAlgorithms: ["p256-sha256"],
  },
  {
    schemaVersion: 2, productClientId: "ynx-creator-studio-web-v1", requestingProduct: "ynx-creator-studio",
    bundleId: "com.ynxweb4.creator-studio.web", callbacks: ["https://web4.ynxweb4.com/video/studio/wallet-auth/callback"],
    scopes: ["ai.video.propose", "pay.payout.intent", "video.creator", "video.read"], maxScopes: 4,
    productDeviceAlgorithms: ["p256-sha256"],
  },
  {
    schemaVersion: 2, productClientId: "ynx-docs-mobile-v1", requestingProduct: "docs",
    bundleId: "com.ynxweb4.docs", callbacks: ["ynxdocs://wallet-auth/callback"],
    scopes: ["ai.use", "audit.read", "comments.write", "data.delete", "documents.read", "documents.write", "sharing.manage"], maxScopes: 7,
    productDeviceAlgorithms: ["p256-sha256"],
  },
  {
    schemaVersion: 2, productClientId: "ynx-docs-web-v1", requestingProduct: "docs",
    bundleId: "web.ynx.docs", callbacks: ["https://web4.ynxweb4.com/docs-app/auth/callback"],
    scopes: ["ai.use", "audit.read", "comments.write", "data.delete", "documents.read", "documents.write", "sharing.manage"], maxScopes: 7,
    productDeviceAlgorithms: ["p256-sha256"],
  },
  {
    schemaVersion: 2, productClientId: "ynx-developer-v1", requestingProduct: "developer",
    bundleId: "com.ynxweb4.developer.testnetpreview", callbacks: ["ynxdeveloper://wallet-auth/callback"],
    scopes: ["account:read", "developer:deploy"], maxScopes: 2,
    productDeviceAlgorithms: ["p256-sha256"],
  },
  {
    schemaVersion: 2, productClientId: "ynx-dex-web-v1", requestingProduct: "dex",
    bundleId: "com.ynxweb4.dex.web", callbacks: ["https://dex.ynxweb4.com/wallet-auth/callback"],
    scopes: ["account:read", "dex:positions:read", "dex:transaction:request"], maxScopes: 3,
    productDeviceAlgorithms: ["p256-sha256"],
  },
  {
    schemaVersion: 2, productClientId: "ynx-exchange-v1", requestingProduct: "exchange",
    bundleId: "com.ynxweb4.exchange", callbacks: ["https://exchange.ynxweb4.com/wallet-auth/callback", "ynxexchange://wallet-auth/callback"],
    scopes: ["exchange:ai", "exchange:deposit", "exchange:read", "exchange:trade", "exchange:withdrawal-review"], maxScopes: 5,
    productDeviceAlgorithms: ["p256-sha256"],
  },
  {
    schemaVersion: 2, productClientId: "ynx-finance-v1", requestingProduct: "finance",
    bundleId: "com.ynxweb4.finance", callbacks: ["ynxfinance://wallet-auth/callback"],
    scopes: ["finance.ai.draft", "finance.pay.read", "finance.portfolio.read", "finance.profile.write"], maxScopes: 4,
    productDeviceAlgorithms: ["p256-sha256"],
  },
  {
    schemaVersion: 2, productClientId: "ynx-merchant-console-v1", requestingProduct: "pay-merchant",
    bundleId: "com.ynxweb4.merchant-console", callbacks: ["https://pay.ynxweb4.com/merchant/wallet-auth/callback"],
    scopes: ["account:read", "merchant:session:create"], maxScopes: 2,
    productDeviceAlgorithms: ["p256-sha256"],
  },
  {
    schemaVersion: 2, productClientId: "ynx-mail-v1", requestingProduct: "mail",
    bundleId: "com.ynxweb4.mail", callbacks: ["ynxmail://wallet-auth/callback"],
    scopes: ["mail:account", "mail:recover"], maxScopes: 2,
    productDeviceAlgorithms: ["p256-sha256"],
  },
  {
    schemaVersion: 2, productClientId: "ynx-music-v1", requestingProduct: "music",
    bundleId: "com.ynxweb4.music", callbacks: ["ynxmusic://auth/callback"],
    scopes: ["music.creator", "music.library", "music.playback", "music.profile"], maxScopes: 4,
    productDeviceAlgorithms: ["p256-sha256"],
  },
  {
    schemaVersion: 2, productClientId: "ynx-music-web-v1", requestingProduct: "music",
    bundleId: "web.ynx.music", callbacks: ["https://web4.ynxweb4.com/music/auth/callback"],
    scopes: ["music.creator", "music.library", "music.playback", "music.profile"], maxScopes: 4,
    productDeviceAlgorithms: ["p256-sha256"],
  },
  {
    schemaVersion: 2, productClientId: "ynx-pay-v1", requestingProduct: "pay",
    bundleId: "com.ynxweb4.pay", callbacks: ["ynxpay://wallet-auth/callback"],
    scopes: ["account:read", "pay:case:create", "pay:route:select", "pay:settlement:submit", "pay:sponsorship:request"], maxScopes: 5,
    productDeviceAlgorithms: ["p256-sha256"],
  },
  {
    schemaVersion: 2, productClientId: "ynx-quant-v1", requestingProduct: "quant",
    bundleId: "com.ynxweb4.quant", callbacks: ["https://quant.ynxweb4.com/wallet-auth/callback", "ynxquant://wallet-auth/callback"],
    scopes: ["quant:account", "quant:mandate:create", "quant:mandate:execute", "quant:mandate:revoke"], maxScopes: 4,
    productDeviceAlgorithms: ["p256-sha256"],
  },
  {
    schemaVersion: 2, productClientId: "ynx-seller-v1", requestingProduct: "seller-console",
    bundleId: "com.ynxweb4.seller-console", callbacks: ["ynxseller://wallet-auth/callback"],
    scopes: ["account:read", "shop:seller:operate"], maxScopes: 2,
    productDeviceAlgorithms: ["p256-sha256"],
  },
  {
    schemaVersion: 2, productClientId: "ynx-search-web", requestingProduct: "search",
    bundleId: "com.ynxweb4.search.web", callbacks: ["https://web4.ynxweb4.com/search/auth/callback"],
    scopes: ["account:read", "search:cases"], maxScopes: 2,
    productDeviceAlgorithms: ["p256-sha256"],
  },
  {
    schemaVersion: 2, productClientId: "ynx-shop-v1", requestingProduct: "shop",
    bundleId: "com.ynxweb4.shop", callbacks: ["ynxshop://wallet-auth/callback"],
    scopes: ["account:read", "shop:orders:write", "shop:profile:write"], maxScopes: 3,
    productDeviceAlgorithms: ["p256-sha256"],
  },
  {
    schemaVersion: 2, productClientId: "ynx-social-v1", requestingProduct: "social",
    bundleId: "com.ynx.social", callbacks: ["ynx-social://com.ynx.social"],
    scopes: ["account:read", "profile:link"], maxScopes: 2,
    productDeviceAlgorithms: ["p256-sha256"],
  },
  {
    schemaVersion: 2, productClientId: "ynx-video-mobile-v1", requestingProduct: "ynx-video",
    bundleId: "com.ynxweb4.video", callbacks: ["ynxvideo://wallet-auth/callback"],
    scopes: ["video.comment", "video.history", "video.read", "video.report", "video.subscribe"], maxScopes: 5,
    productDeviceAlgorithms: ["p256-sha256"],
  },
  {
    schemaVersion: 2, productClientId: "ynx-video-web-v1", requestingProduct: "ynx-video",
    bundleId: "com.ynxweb4.video.web", callbacks: ["https://web4.ynxweb4.com/video/wallet-auth/callback"],
    scopes: ["video.comment", "video.history", "video.read", "video.report", "video.subscribe"], maxScopes: 5,
    productDeviceAlgorithms: ["p256-sha256"],
  },
] as const;

export const PRODUCT_REGISTRY:Readonly<Record<string,ProductBinding>>=Object.freeze(Object.assign({},...REVIEWED_ENTRIES.map((entry)=>registryParserBinding(parseCentralRegistryEntry(entry)))));

export const SCOPE_EXPLANATIONS: Readonly<Record<string, string>> = Object.freeze({
  "ai.video.propose": "Create reviewable Creator Studio AI proposals; AI cannot publish, claim rights, moderate accounts or move YNXT.",
  "account:read": "Share this account's public ynx1 address. No secret or recovery material leaves Wallet.",
  "browser:wallet-request": "Review one exact Browser-originated Wallet request. Browser cannot sign, move funds, widen scopes or create a Wallet session by itself.",
  "calendar:account": "Connect this account to Calendar events, invitations and settings without sharing keys or recovery material.",
  "calendar:recover": "Review recovery of this account's Calendar access on a new device; it does not reveal Wallet recovery material.",
  "card:application:write": "Create or update only this account's sandbox Card application.",
  "card:controls:write": "Manage only this account's Card controls after a separate review.",
  "card:dispute:write": "Create and update this account's Card disputes; it cannot move funds.",
  "ai.use": "Use only the Cloud content explicitly selected by this account as AI context. AI cannot sign, transfer funds or widen access.",
  "audit.read": "Read this account's Cloud security and activity records without changing stored content.",
  "data.delete": "Request deletion of this account's Cloud product data after a separate exact destructive confirmation.",
  "files.read": "Read only this account's authorized Cloud files and metadata.",
  "files.write": "Create or change only this account's authorized Cloud files; it cannot access another account's workspace.",
  "permissions.manage": "Manage explicit Cloud sharing grants owned by this account; it cannot grant access outside the reviewed product boundary.",
  "comments.write": "Create, reply to, resolve and reopen comments only on Docs content this account can access.",
  "documents.read": "Read only Docs documents and folders explicitly available to this account.",
  "documents.write": "Create or change only this account's authorized Docs documents and folders; it cannot access another workspace.",
  "sharing.manage": "Grant or revoke explicit Docs account and link access owned by this account; it cannot widen access outside Docs.",
  "developer:deploy": "Allow Developer to prepare an exact Testnet deployment for a separate Wallet review. This session cannot sign, broadcast or bypass the final transaction approval.",
  "dex:positions:read": "Read only this account's indexed DEX liquidity positions after a live central session check.",
  "dex:transaction:request": "Prepare an exact swap or liquidity action for a separate Wallet review. DEX cannot sign or broaden the action.",
  "exchange:ai": "Allow Exchange to create reviewable AI drafts; AI cannot sign, trade, deposit or withdraw.",
  "exchange:deposit": "Read and reconcile this account's Testnet deposit evidence; this approval is not a transfer signature.",
  "exchange:read": "Read this account's Exchange balances, orders, trades and audit evidence.",
  "exchange:trade": "Submit bounded Testnet order requests for separate Exchange checks; Wallet approval is not order execution.",
  "exchange:withdrawal-review": "Create a withdrawal review request; a separate native transfer signature is still required to move YNXT.",
  "finance.ai.draft": "Create reviewable Finance drafts from only the records selected by this account; drafts cannot execute actions.",
  "finance.pay.read": "Read this account's verified Pay receipt evidence without creating or signing a payment.",
  "finance.portfolio.read": "Read this account's public YNXT balance and indexed activity from approved sources.",
  "finance.profile.write": "Manage only this account's private Finance categories, budgets, notes and reminders.",
  "merchant:session:create": "Create a short-lived, device-bound session for one authorized merchant role. This cannot sign payments, refunds or settlements.",
  "mail:account": "Connect this account to signed YNX Mail messages and mailbox settings without sharing keys or recovery material.",
  "mail:recover": "Review recovery of this account's Mail access on a new device; it does not reveal Wallet recovery material.",
  "music.creator": "Manage this account's owned or licensed Music drafts, rights evidence and explicit publish or withdrawal actions.",
  "music.library": "Read and update this account's private Music favorites, queue and playlists without exposing Wallet secrets.",
  "music.playback": "Record this account's consented playback position and eligible Testnet usage evidence; it cannot invent streams or revenue.",
  "music.profile": "Read and update this account's Music profile, privacy settings and evidence-bound rights cases.",
  "pay:case:create": "Create a Pay support case for this account without authorizing a transfer.",
  "pay:route:select": "Request and select a bounded Pay routing or bridge option; this does not move funds.",
  "pay:settlement:submit": "Submit a settlement request for separate Pay review; Wallet approval is not a payment signature.",
  "pay:sponsorship:request": "Request a bounded gas sponsorship quote; final payment still requires separate Wallet review.",
  "pay.payout.intent": "Create a payout intent from audited Creator Studio revenue; a separate Wallet confirmation is still required.",
  "profile:link": "Allow this exact Social device to link the public account to its profile.",
  "quant:account": "Share this account's public address with Quant for account-bound research controls.",
  "quant:mandate:create": "Create a bounded Testnet Quant mandate for later review; it does not execute an order.",
  "quant:mandate:execute": "Request execution of an already bounded mandate; execution remains unavailable until its owner transport is accepted.",
  "quant:mandate:revoke": "Revoke this account's Quant mandate and prevent later use.",
  "search:cases": "Associate a public Search correction, removal or appeal case with this account. It cannot change index policy, publish private data or move funds.",
  "shop:orders:write": "Create and update this account's Testnet Shop orders; payment still requires a separate Wallet signature.",
  "shop:profile:write": "Manage only this account's Shop profile, addresses and privacy choices.",
  "shop:seller:operate": "Operate only this account's authorized Seller Console store records. Product-session approval cannot receive customer funds or sign payouts.",
  "video.creator": "Manage this account's channels, uploads, rights evidence and reviewed publication workflow.",
  "video.comment": "Create comments only as this account on published YNX Video records; it cannot edit another viewer's content.",
  "video.history": "Read and update this account's private watch history and playlists without exposing them to other viewers.",
  "video.read": "Read this account's Creator Studio records and authoritative persisted analytics.",
  "video.report": "Submit an evidence-bound Video report for human review; it cannot automatically remove content or penalize an account.",
  "video.subscribe": "Manage this account's Video channel subscriptions and no other account's subscription state.",
});
