import { keccak_256 } from "@noble/hashes/sha3.js";
import { bytesToHex } from "@noble/hashes/utils.js";
import { EIP1193_EVENTS, EIP1193_METHODS, YNX_EVM_CAIP2, answerEip1193Read, approveAndSignEip1193Request, approveEip1193Session, parseEip1193Request, type Eip1193Request, type Eip1193Session } from "./eip1193Provider";

export type DappBrowserResponse=Readonly<{id:string|number;jsonrpc:"2.0";result?:unknown;error?:Readonly<{code:number;message:string}>}>;
export type DappBrowserPort=Readonly<{respond:(value:DappBrowserResponse)=>void;emit?:(name:"accountsChanged"|"chainChanged",data:unknown)=>void}>;
export type PendingConnect=Readonly<{origin:string;name:string;id:string|number;issuedAt:string;expiresAt:string}>;
export type DappBrowserSnapshot=Readonly<{sessions:readonly Eip1193Session[];connection:PendingConnect|null;request:Eip1193Request|null}>;

export class DappBrowserController {
  private sessions=new Map<string,Eip1193Session>();
  private connect:PendingConnect|null=null;
  private request:Eip1193Request|null=null;
  constructor(private readonly port:DappBrowserPort,private readonly now:()=>Date=()=>new Date()){}
  pendingConnection(){return this.connect}
  pendingRequest(){return this.request}
  activeOrigins(){return Object.freeze([...this.sessions.values()].map(value=>Object.freeze({origin:value.origin,name:value.name,account:value.account,expiresAt:value.expiresAt})))}
  snapshot():DappBrowserSnapshot{return Object.freeze({sessions:Object.freeze([...this.sessions.values()].sort((a,b)=>a.origin.localeCompare(b.origin))),connection:this.connect,request:this.request})}
  restoreSnapshot(value:DappBrowserSnapshot){if(this.sessions.size||this.connect||this.request)fail("RESTORE_CONFLICT","DApp Browser runtime is not empty");for(const session of value.sessions)this.sessions.set(session.origin,session);this.connect=value.connection;this.request=value.request}
  confirmPendingReplay(originValue:string,nameValue:string,raw:string){const origin=strictOrigin(originValue),name=strictName(nameValue),input=parseMessage(raw);if(this.connect){if(origin!==this.connect.origin||name!==this.connect.name||input.id!==this.connect.id||input.method!=="eth_requestAccounts"||input.params.length!==0)fail("PENDING_REPLAY_MISMATCH","DApp Browser connection replay differs from the persisted request");return Object.freeze({state:"connection" as const,value:this.connect})}if(this.request){const session=this.sessions.get(origin);if(!session)fail("SESSION_MISSING","DApp Browser replay session is missing");const candidate=parseEip1193Request({sessionId:session.sessionId,requestId:input.id,transport:"dapp-browser",origin,chainId:YNX_EVM_CAIP2,method:input.method,params:input.params,issuedAt:this.request.issuedAt,expiresAt:this.request.expiresAt},session,this.now());if(JSON.stringify(candidate)!==JSON.stringify(this.request))fail("PENDING_REPLAY_MISMATCH","DApp Browser request replay differs from the persisted request");return Object.freeze({state:"request" as const,value:this.request})}fail("PENDING_REPLAY_MISSING","DApp Browser has no persisted request to replay")}

  receive(originValue:string,nameValue:string,raw:string){const origin=strictOrigin(originValue),name=strictName(nameValue),input=parseMessage(raw),now=validNow(this.now()),session=this.sessions.get(origin);if(this.connect||this.request)fail("DAPP_BROWSER_BUSY","Another DApp Browser approval is pending");if(!session){if(input.method!=="eth_requestAccounts"||input.params.length!==0){this.port.respond(error(input.id,4100,"DApp origin is not connected"));return Object.freeze({state:"rejected" as const})}this.connect=Object.freeze({origin,name,id:input.id,issuedAt:now.toISOString(),expiresAt:new Date(now.getTime()+5*60_000).toISOString()});return Object.freeze({state:"connection" as const,value:this.connect})}const request=parseEip1193Request(toRequest(input,session,now),session,now);if(read(request.method)){this.port.respond(Object.freeze({id:input.id,jsonrpc:"2.0",result:answerEip1193Read(request)}));return Object.freeze({state:"responded" as const})}this.request=request;return Object.freeze({state:"request" as const,value:request})}
  approveConnection(selectedYNXAccount:string,activeOrigin:string){const pending=this.connect;if(!pending)fail("CONNECTION_MISSING","DApp Browser connection approval is missing");assertPending(pending.expiresAt,this.now());if(strictOrigin(activeOrigin)!==pending.origin)fail("ORIGIN_DRIFT","DApp Browser navigated away before approval");const session=approveEip1193Session({sessionId:browserSessionIdForOrigin(pending.origin),transport:"dapp-browser",origin:pending.origin,name:pending.name,chains:[YNX_EVM_CAIP2],methods:EIP1193_METHODS,events:EIP1193_EVENTS,expiresAt:new Date(validNow(this.now()).getTime()+24*60*60_000).toISOString()},selectedYNXAccount,this.now());this.sessions.set(pending.origin,session);this.port.respond(Object.freeze({id:pending.id,jsonrpc:"2.0",result:Object.freeze([session.account])}));this.port.emit?.("accountsChanged",[session.account]);this.port.emit?.("chainChanged","0x1917");this.connect=null;return session}
  rejectConnection(){const pending=this.connect;if(!pending)fail("CONNECTION_MISSING","DApp Browser connection approval is missing");this.port.respond(error(pending.id,4001,"User rejected DApp connection"));this.connect=null}
  async approveRequest(activeOrigin:string,boundary:Parameters<typeof approveAndSignEip1193Request>[1]&Readonly<{broadcastSignedTransaction:(raw:string)=>Promise<string>}>){const request=this.request;if(!request)fail("REQUEST_MISSING","DApp Browser request is missing");if(strictOrigin(activeOrigin)!==request.origin)fail("ORIGIN_DRIFT","DApp Browser navigated away before approval");const signed=await approveAndSignEip1193Request(request,boundary),result=request.method==="eth_sendTransaction"?await broadcast(boundary.broadcastSignedTransaction,signed):signed;this.port.respond(Object.freeze({id:wireId(request.requestId),jsonrpc:"2.0",result}));this.request=null;return result}
  rejectRequest(){const request=this.request;if(!request)fail("REQUEST_MISSING","DApp Browser request is missing");this.port.respond(error(wireId(request.requestId),4001,"User rejected DApp request"));this.request=null}
  navigated(activeOrigin:string){const exact=strictOrigin(activeOrigin);if(this.connect&&this.connect.origin!==exact){this.port.respond(error(this.connect.id,4001,"DApp navigation cancelled connection approval"));this.connect=null}if(this.request&&this.request.origin!==exact){this.port.respond(error(wireId(this.request.requestId),4001,"DApp navigation cancelled request approval"));this.request=null}}
  disconnect(origin:string){const exact=strictOrigin(origin);this.sessions.delete(exact);if(this.connect?.origin===exact)this.rejectConnection();if(this.request?.origin===exact)this.rejectRequest();this.port.emit?.("accountsChanged",[])}
}

export const DAPP_BROWSER_INJECTED_PROVIDER=`(function(){if(window.ethereum&&window.ethereum.isYNXWallet)return;var next=1,pending=new Map(),listeners={};function emit(name,value){(listeners[name]||[]).slice().forEach(function(fn){try{fn(value)}catch(_){}})}function receive(input){var value=input;if(typeof value==="string"){try{value=JSON.parse(value)}catch(_){return}}if(!value||value.jsonrpc!=="2.0"||!("id" in value))return;var item=pending.get(value.id);if(!item)return;pending.delete(value.id);if(value.error)item.reject(Object.assign(new Error(value.error.message),{code:value.error.code}));else item.resolve(value.result)}var provider={isYNXWallet:true,request:function(input){return new Promise(function(resolve,reject){if(!input||typeof input.method!=="string"){reject(Object.assign(new Error("Invalid EIP-1193 request"),{code:-32600}));return}var id=next++;pending.set(id,{resolve:resolve,reject:reject});window.ReactNativeWebView.postMessage(JSON.stringify({jsonrpc:"2.0",id:id,method:input.method,params:input.params||[]}))})},on:function(name,fn){if(typeof fn==="function")(listeners[name]||(listeners[name]=[])).push(fn);return this},removeListener:function(name,fn){listeners[name]=(listeners[name]||[]).filter(function(item){return item!==fn});return this},emit:emit};Object.defineProperty(provider,"__ynxReceive",{value:receive,writable:false,configurable:false,enumerable:false});window.addEventListener("message",function(event){receive(event.data)});window.ethereum=provider;window.dispatchEvent(new Event("ethereum#initialized"))})();true;`;

function parseMessage(raw:string){if(typeof raw!=="string"||raw.length>262_144)fail("INVALID_MESSAGE","DApp Browser message is invalid");let parsed:unknown;try{parsed=JSON.parse(raw)}catch{fail("INVALID_MESSAGE","DApp Browser message is not JSON")};if(!plain(parsed)||Object.keys(parsed).sort().join(",")!=="id,jsonrpc,method,params"||parsed.jsonrpc!=="2.0"||!(typeof parsed.id==="string"||Number.isSafeInteger(parsed.id))||typeof parsed.method!=="string"||!Array.isArray(parsed.params))fail("INVALID_MESSAGE","DApp Browser JSON-RPC fields are invalid");return{id:parsed.id as string|number,method:parsed.method,params:parsed.params}}
function toRequest(input:ReturnType<typeof parseMessage>,session:Eip1193Session,now:Date){return{sessionId:session.sessionId,requestId:input.id,transport:"dapp-browser",origin:session.origin,chainId:YNX_EVM_CAIP2,method:input.method,params:input.params,issuedAt:now.toISOString(),expiresAt:new Date(now.getTime()+5*60_000).toISOString()}}
function strictOrigin(value:string){let url:URL;try{url=new URL(value)}catch{fail("INVALID_ORIGIN","DApp Browser origin is invalid")};if(url.protocol!=="https:"||url.origin!==value||url.username||url.password||url.port)fail("INVALID_ORIGIN","DApp Browser requires a canonical HTTPS origin");return value}
function strictName(value:string){if(typeof value!=="string"||value.trim()!==value||value.length<1||value.length>96||/[\u0000-\u001f\u007f]/.test(value))fail("INVALID_NAME","DApp Browser name is invalid");return value}
export function browserSessionIdForOrigin(origin:string){return`browser:${bytesToHex(keccak_256(new TextEncoder().encode(origin)))}`}
function read(method:string){return method==="eth_accounts"||method==="eth_requestAccounts"||method==="eth_chainId"||method==="net_version"}
function error(id:string|number,code:number,message:string){return Object.freeze({id,jsonrpc:"2.0" as const,error:Object.freeze({code,message})})}
function wireId(value:string){if(value.startsWith("n:"))return Number(value.slice(2));if(value.startsWith("s:"))return value.slice(2);fail("INVALID_REQUEST_ID","DApp Browser request ID is invalid")}
async function broadcast(fn:(raw:string)=>Promise<string>,raw:string){const hash=await fn(raw);if(!/^0x[0-9a-f]{64}$/.test(hash))fail("INVALID_BROADCAST","EVM broadcast returned an invalid transaction hash");return hash}
function assertPending(expiresAt:string,now:Date){if(Date.parse(expiresAt)<=validNow(now).getTime())fail("REQUEST_EXPIRED","DApp Browser approval expired")}
function validNow(value:Date){if(!(value instanceof Date)||!Number.isFinite(value.getTime()))fail("INVALID_TIME","DApp Browser clock is invalid");return value}
function plain(value:unknown):value is Record<string,unknown>{return typeof value==="object"&&value!==null&&!Array.isArray(value)&&Object.getPrototypeOf(value)===Object.prototype}
function fail(code:string,message:string):never{throw Object.assign(new Error(message),{code})}
