import assert from "node:assert/strict";
import test from "node:test";
import { runInNewContext } from "node:vm";
import { evmAddressFromYNX, walletIdentity } from "@ynx-chain/wallet-auth";
import { DAPP_BROWSER_INJECTED_PROVIDER, DappBrowserController, type DappBrowserResponse } from "./dappBrowserController";

const NOW=new Date("2026-08-22T06:00:00.000Z"),SECRET=`${"00".repeat(31)}01`,identity=walletIdentity(SECRET),account=evmAddressFromYNX(identity.account).toLowerCase(),origin="https://dapp.example";
const message=(id:number,method:string,params:unknown[]=[])=>JSON.stringify({jsonrpc:"2.0",id,method,params});
function setup(){const responses:DappBrowserResponse[]=[],controller=new DappBrowserController({respond:value=>responses.push(value)},()=>NOW);return{responses,controller}}

test("requestAccounts requires explicit origin-bound approval and exposes only derived 0x",()=>{const{responses,controller}=setup();assert.equal(controller.receive(origin,"External DApp",message(1,"eth_requestAccounts")).state,"connection");assert.equal(responses.length,0);const session=controller.approveConnection(identity.account,origin);assert.equal(session.account,account);assert.equal(session.productSession,false);assert.deepEqual(responses,[{id:1,jsonrpc:"2.0",result:[account]}]);});
test("reject and navigation drift return 4001 with zero session",()=>{const{responses,controller}=setup();controller.receive(origin,"External DApp",message(1,"eth_requestAccounts"));controller.navigated("https://other.example");assert.equal(responses[0]?.error?.code,4001);assert.equal(controller.activeOrigins().length,0);controller.receive(origin,"External DApp",message(2,"eth_requestAccounts"));controller.rejectConnection();assert.equal(responses[1]?.error?.code,4001);});
test("unauthorized methods fail without opening a signing review",()=>{const{responses,controller}=setup();assert.equal(controller.receive(origin,"External DApp",message(3,"personal_sign",["0x00",account])).state,"rejected");assert.equal(responses[0]?.error?.code,4100);assert.equal(controller.pendingRequest(),null);});
test("connected reads answer immediately while message signing remains explicit",async()=>{const{responses,controller}=setup();controller.receive(origin,"External DApp",message(1,"eth_requestAccounts"));controller.approveConnection(identity.account,origin);assert.equal(controller.receive(origin,"External DApp",message(2,"eth_chainId")).state,"responded");assert.equal(responses[1]?.result,"0x1917");assert.equal(controller.receive(origin,"External DApp",message(3,"personal_sign",["0x6869",account])).state,"request");assert.equal(responses.length,2);await controller.approveRequest(origin,{authorize:async()=>{},readAccountSecret:async()=>SECRET,assertActive:()=>{},broadcastSignedTransaction:async()=>{throw new Error("not broadcast")},now:()=>NOW});assert.match(String(responses[2]?.result),/^0x[0-9a-f]{130}$/);});
test("wrong origin and malformed/widened JSON-RPC fail closed",()=>{const{controller}=setup();for(const raw of ["x",JSON.stringify({jsonrpc:"2.0",id:1,method:"eth_accounts",params:[],extra:true}),JSON.stringify({jsonrpc:"2.0",id:1,method:"eth_accounts"})])assert.throws(()=>controller.receive(origin,"DApp",raw));assert.throws(()=>controller.receive("http://dapp.example","DApp",message(1,"eth_accounts")));});
test("native callback survives a DApp document rewrite that removes window message listeners",async()=>{const listeners=new Map<string,(event:{data:unknown})=>void>(),posted:string[]=[];const window:any={addEventListener:(name:string,fn:(event:{data:unknown})=>void)=>listeners.set(name,fn),dispatchEvent:()=>{},ReactNativeWebView:{postMessage:(value:string)=>posted.push(value)}};runInNewContext(DAPP_BROWSER_INJECTED_PROVIDER,{window,Event:class{constructor(readonly type:string){}}});const pending=window.ethereum.request({method:"eth_requestAccounts"});assert.deepEqual(JSON.parse(posted[0]!),{jsonrpc:"2.0",id:1,method:"eth_requestAccounts",params:[]});listeners.clear();const descriptor=Object.getOwnPropertyDescriptor(window.ethereum,"__ynxReceive");assert.equal(descriptor?.enumerable,false);assert.equal(descriptor?.writable,false);window.ethereum.__ynxReceive({id:1,jsonrpc:"2.0",result:[account]});assert.deepEqual(await pending,[account]);const rejected=window.ethereum.request({method:"personal_sign",params:["0x00",account]});window.ethereum.__ynxReceive({id:2,jsonrpc:"2.0",error:{code:4001,message:"User rejected DApp request"}});await assert.rejects(rejected,(caught:any)=>caught?.code===4001);});
