import { answerEip1193Read, approveAndSignEip1193Request, approveEip1193Session, parseEip1193Request, type Eip1193Method, type Eip1193Request, type Eip1193Session, YNX_EVM_CAIP2 } from "./eip1193Provider";

export type WalletConnectProposal=Readonly<{id:number;pairingTopic:string;origin:string;name:string;chains:readonly string[];methods:readonly string[];events:readonly string[];expiresAt:string;verification:"VALID"|"INVALID"|"UNKNOWN";isScam:boolean}>;
export type WalletConnectRequestEvent=Readonly<{topic:string;id:number;chainId:string;method:string;params:readonly unknown[];issuedAt:string;expiresAt:string}>;
export type WalletConnectActiveSession=Readonly<{topic:string;origin:string;name:string;account:string;methods:readonly string[];events:readonly string[];expiresAt:string}>;
export type WalletConnectRestoredSession=Readonly<{topic:string;origin:string;name:string;chains:readonly string[];methods:readonly string[];events:readonly string[];accounts:readonly string[];expiresAt:string}>;
export type WalletConnectPort={
  pair(uri:string):Promise<void>;
  approveSession(input:Readonly<{id:number;namespaces:Readonly<{eip155:Readonly<{accounts:readonly string[];chains:readonly string[];methods:readonly string[];events:readonly string[]}>}>}>):Promise<Readonly<{topic:string}>>;
  rejectSession(id:number,reason:Readonly<{code:number;message:string}>):Promise<void>;
  respond(input:Readonly<{topic:string;response:Readonly<{id:number;jsonrpc:"2.0";result?:unknown;error?:Readonly<{code:number;message:string}>}>}>):Promise<void>;
  disconnect(topic:string,reason:Readonly<{code:number;message:string}>):Promise<void>;
};

export type WalletConnectSigningBoundary=Readonly<{authorize:(method:Eip1193Method)=>Promise<unknown>;readAccountSecret:(account:string)=>Promise<string>;assertActive:()=>void;now?:()=>Date;broadcastSignedTransaction:(rawTransaction:string)=>Promise<string>}>;

export class WalletConnectController{
  private proposal:WalletConnectProposal|null=null;
  private requestEvent:WalletConnectRequestEvent|null=null;
  private sessions=new Map<string,Eip1193Session>();
  constructor(private readonly port:WalletConnectPort,private readonly now:()=>Date=()=>new Date()){}
  pair(uri:string):Promise<void>{return this.port.pair(parseWalletConnectUri(uri))}
  pendingProposal(){return this.proposal}
  pendingRequest(){return this.requestEvent===null?null:Object.freeze({event:this.requestEvent,session:this.sessions.get(this.requestEvent.topic)??null})}
  activeSessions(){return Object.freeze([...this.sessions.entries()].map(([topic,session])=>Object.freeze({topic,session})))}
  restoreSession(value:WalletConnectRestoredSession,selectedYNXAccount:string){const topic=topicValue(value.topic);if(this.sessions.has(topic))fail("SESSION_DUPLICATE","WalletConnect session is already restored");if(!Array.isArray(value.accounts)||value.accounts.length!==1)fail("INVALID_SESSION","WalletConnect restored account is invalid");const session=approveEip1193Session({sessionId:`wc:${topic}`,transport:"walletconnect-v2",origin:value.origin,name:value.name,chains:value.chains,methods:value.methods,events:value.events,expiresAt:value.expiresAt},selectedYNXAccount,this.now());if(value.accounts[0]!==session.caip10Account)fail("ACCOUNT_MISMATCH","WalletConnect restored session belongs to another Wallet account");this.sessions.set(topic,session);return Object.freeze({topic,session})}

  receiveProposal(value:WalletConnectProposal){if(this.proposal!==null||this.requestEvent!==null)fail("WALLETCONNECT_BUSY","Another WalletConnect approval is pending");validateProposal(value,this.now());this.proposal=Object.freeze({...value,chains:Object.freeze([...value.chains]),methods:Object.freeze([...value.methods]),events:Object.freeze([...value.events])});return this.proposal}
  async approveProposal(selectedYNXAccount:string){const proposal=this.proposal;if(proposal===null)fail("PROPOSAL_MISSING","WalletConnect proposal is missing");const session=approveEip1193Session({sessionId:`wc:${proposal.pairingTopic}`,transport:"walletconnect-v2",origin:proposal.origin,name:proposal.name,chains:proposal.chains,methods:proposal.methods,events:proposal.events,expiresAt:proposal.expiresAt},selectedYNXAccount,this.now());const approved=await this.port.approveSession({id:proposal.id,namespaces:{eip155:{accounts:[session.caip10Account],chains:[YNX_EVM_CAIP2],methods:session.methods,events:session.events}}});const topic=topicValue(approved.topic);this.sessions.set(topic,session);this.proposal=null;return Object.freeze({topic,session})}
  async rejectProposal(){const proposal=this.proposal;if(proposal===null)fail("PROPOSAL_MISSING","WalletConnect proposal is missing");await this.port.rejectSession(proposal.id,{code:5000,message:"User rejected WalletConnect session"});this.proposal=null}

  receiveRequest(value:WalletConnectRequestEvent){if(this.requestEvent!==null||this.proposal!==null)fail("WALLETCONNECT_BUSY","Another WalletConnect approval is pending");const topic=topicValue(value.topic),session=this.sessions.get(topic);if(session===undefined)fail("SESSION_MISSING","WalletConnect session is unknown");parseEip1193Request(normalizeRequest(value,session),session,this.now());this.requestEvent=Object.freeze({...value,params:Object.freeze([...value.params])});return this.pendingRequest()}
  async approveRequest(boundary:WalletConnectSigningBoundary){const event=this.requestEvent;if(event===null)fail("REQUEST_MISSING","WalletConnect request is missing");const session=this.sessions.get(event.topic);if(session===undefined)fail("SESSION_MISSING","WalletConnect session is unknown");const request=parseEip1193Request(normalizeRequest(event,session),session,this.now());let result:unknown;if(readMethod(request.method))result=answerEip1193Read(request);else{const signed=await approveAndSignEip1193Request(request,boundary);result=request.method==="eth_sendTransaction"?await broadcastHash(boundary.broadcastSignedTransaction,signed):signed}await this.port.respond({topic:event.topic,response:{id:event.id,jsonrpc:"2.0",result}});this.requestEvent=null;return Object.freeze({request,result})}
  async rejectRequest(){const event=this.requestEvent;if(event===null)fail("REQUEST_MISSING","WalletConnect request is missing");await this.port.respond({topic:event.topic,response:{id:event.id,jsonrpc:"2.0",error:{code:4001,message:"User rejected WalletConnect request"}}});this.requestEvent=null}
  async disconnect(topic:string){const exact=topicValue(topic);if(!this.sessions.has(exact))fail("SESSION_MISSING","WalletConnect session is unknown");await this.port.disconnect(exact,{code:6000,message:"User disconnected WalletConnect session"});this.sessions.delete(exact);if(this.requestEvent?.topic===exact)this.requestEvent=null}
  sessionDeleted(topic:string){const exact=topicValue(topic);this.sessions.delete(exact);if(this.requestEvent?.topic===exact)this.requestEvent=null}
}

export function parseWalletConnectUri(value:string){if(typeof value!=="string"||value.length>2048||value.includes("#"))fail("INVALID_WALLETCONNECT_URI","WalletConnect URI is invalid");const match=/^wc:([0-9a-f]{64})@2\?(.+)$/.exec(value);if(!match)fail("INVALID_WALLETCONNECT_URI","WalletConnect URI must be a v2 pairing URI");const query=new URLSearchParams(match[2]),allowed=new Set(["relay-protocol","relay-data","symKey","expiryTimestamp"]),keys=[...query.keys()];if(new Set(keys).size!==keys.length||keys.some(key=>!allowed.has(key))||query.get("relay-protocol")!=="irn"||!/[0-9a-f]{64}/.test(query.get("symKey")??""))fail("INVALID_WALLETCONNECT_URI","WalletConnect pairing parameters are invalid");const expiry=query.get("expiryTimestamp");if(expiry!==null&&(!/^[1-9][0-9]{9,12}$/.test(expiry)||Number(expiry)*1000<=Date.now()))fail("INVALID_WALLETCONNECT_URI","WalletConnect pairing URI is expired");return value}

function validateProposal(value:WalletConnectProposal,now:Date){if(!value||!Number.isSafeInteger(value.id)||value.id<0)fail("INVALID_PROPOSAL","WalletConnect proposal ID is invalid");topicValue(value.pairingTopic);let origin:URL;try{origin=new URL(value.origin)}catch{fail("INVALID_PROPOSAL","WalletConnect origin is invalid")};if(origin.protocol!=="https:"||origin.origin!==value.origin||origin.username||origin.password||origin.port||typeof value.name!=="string"||value.name.trim()!==value.name||value.name.length<1||value.name.length>96)fail("INVALID_PROPOSAL","WalletConnect DApp identity is invalid");if(!["VALID","INVALID","UNKNOWN"].includes(value.verification)||typeof value.isScam!=="boolean"||value.verification==="INVALID"||value.isScam)fail("UNSAFE_DAPP","WalletConnect verification rejected this DApp");if(!Array.isArray(value.chains)||!Array.isArray(value.methods)||!Array.isArray(value.events))fail("INVALID_PROPOSAL","WalletConnect namespaces are invalid");const expires=Date.parse(value.expiresAt);if(!Number.isFinite(expires)||expires<=now.getTime())fail("INVALID_PROPOSAL","WalletConnect proposal is expired")}
function normalizeRequest(value:WalletConnectRequestEvent,session:Eip1193Session){return{sessionId:session.sessionId,requestId:value.id,transport:"walletconnect-v2",origin:session.origin,chainId:value.chainId,method:value.method,params:value.params,issuedAt:value.issuedAt,expiresAt:value.expiresAt}}
function readMethod(value:Eip1193Method){return value==="eth_accounts"||value==="eth_requestAccounts"||value==="eth_chainId"||value==="net_version"}
async function broadcastHash(broadcast:(raw:string)=>Promise<string>,raw:string){if(typeof broadcast!=="function")fail("RPC_UNAVAILABLE","EVM broadcast transport is unavailable");const hash=await broadcast(raw);if(!/^0x[0-9a-f]{64}$/.test(hash))fail("INVALID_BROADCAST","EVM broadcast returned an invalid transaction hash");return hash}
function topicValue(value:unknown){if(typeof value!=="string"||!/^[0-9a-f]{64}$/.test(value))fail("INVALID_TOPIC","WalletConnect topic is invalid");return value}
function fail(code:string,message:string):never{throw Object.assign(new Error(message),{code})}
