import SwiftUI

extension Notification.Name { static let ynxNavigate=Notification.Name("ynx.navigate");static let ynxBack=Notification.Name("ynx.back");static let ynxForward=Notification.Name("ynx.forward");static let ynxReload=Notification.Name("ynx.reload");static let ynxAi=Notification.Name("ynx.ai") }

struct BrowserScreen: View {
    @EnvironmentObject var model:BrowserModel
    @State private var address=""
    var body: some View {
        VStack(spacing:0){Text(model.notice).font(.caption).foregroundStyle(.secondary).frame(maxWidth:.infinity,alignment:.leading).padding(.horizontal).accessibilityLabel("Status: \(model.notice)")
            ScrollView(.horizontal,showsIndicators:false){HStack{ForEach(model.tabs){tab in HStack(spacing:2){Button((tab.isPrivate ? "Private · ":"")+tab.title){model.active=tab.id;address=tab.url}.buttonStyle(.bordered).tint(tab.id==model.active ? Color(red:0,green:60/255,blue:1):.gray);Button{model.close(tab.id)}label:{Image(systemName:"xmark")}.accessibilityLabel("Close \(tab.title)")}}}.padding(.horizontal)}
            HStack{Button{post(.ynxBack)}label:{Image(systemName:"chevron.left")}.accessibilityLabel("Back");Button{post(.ynxForward)}label:{Image(systemName:"chevron.right")}.accessibilityLabel("Forward");Button{post(.ynxReload)}label:{Image(systemName:"arrow.clockwise")}.accessibilityLabel("Reload");TextField("URL / Search",text:$address).textInputAutocapitalization(.never).autocorrectionDisabled().onSubmit{post(.ynxNavigate,value:normalized(address))}.textFieldStyle(.roundedBorder);Button{model.open("https://search-staging.43.153.202.237.sslip.io",privateMode:false)}label:{Image(systemName:"plus")}.accessibilityLabel(L.text(model.locale,"new"));Button{model.open("https://search-staging.43.153.202.237.sslip.io",privateMode:true)}label:{Image(systemName:"eye.slash")}.accessibilityLabel(L.text(model.locale,"private"))}.padding(.horizontal,8)
            HStack{Button(L.text(model.locale,"history")){model.library = .history};Button(L.text(model.locale,"bookmarks")){model.bookmark();model.library = .bookmarks};Button(L.text(model.locale,"downloads")){model.library = .downloads};Button(L.text(model.locale,"wallet")){model.startWallet()};Button(L.text(model.locale,"ai")){post(.ynxAi)};Button(L.text(model.locale,"settings")){model.showSettings=true}}.font(.caption).buttonStyle(.bordered).padding(.vertical,4)
            if let tab=model.current{BrowserWebView(tab:tab).id(tab.id)}else{ContentUnavailableView("No tab",systemImage:"safari")}
        }.onAppear{address=model.current?.url ?? ""}.onChange(of:model.active){_,_ in address=model.current?.url ?? ""}
        .sheet(item:$model.library){kind in LibrarySheet(kind:kind)}.sheet(isPresented:$model.showSettings){SettingsSheet()}.alert(item:$model.aiPreview){preview in Alert(title:Text("Page AI"),message:Text("Authorized current page only\n\(preview.url)\n\(preview.characters) characters\nProvider: \(preview.provider)\nNo history, Wallet identity, unrelated tabs, or private content."),primaryButton:.default(Text("Approve")){model.approveAi()},secondaryButton:.cancel())}
    }
    private func post(_ name:Notification.Name,value:String?=nil){guard let id=model.active else{return};NotificationCenter.default.post(name:name,object:id,userInfo:value.map{["value":$0]})}
    private func normalized(_ value:String)->String{let text=value.trimmingCharacters(in:.whitespacesAndNewlines);if text.hasPrefix("https://")||text.hasPrefix("http://"){return text};if text.contains(" ")||!text.contains("."){return "https://search-staging.43.153.202.237.sslip.io/?q="+(text.addingPercentEncoding(withAllowedCharacters:.urlQueryAllowed) ?? "")};return "https://"+text}
}

struct LibrarySheet:View{@EnvironmentObject var model:BrowserModel;let kind:BrowserModel.LibraryKind;var items:[BrowserRecord]{switch kind{case.history:return model.history;case.bookmarks:return model.bookmarks;case.downloads:return model.downloads}};var body:some View{NavigationStack{List(items){item in VStack(alignment:.leading){Text(item.title).font(.headline);Text(item.url).font(.caption).foregroundStyle(.secondary);Text(item.at.formatted(date:.abbreviated,time:.shortened)).font(.caption2)}}.overlay{if items.isEmpty{ContentUnavailableView("Nothing here yet",systemImage:"tray")}}.navigationTitle(kind.rawValue.capitalized)}}}
struct SettingsSheet:View{@EnvironmentObject var model:BrowserModel;@State private var clearHistory=true;@State private var clearBookmarks=false;@State private var clearPermissions=true;@State private var clearRecovery=false;var body:some View{NavigationStack{Form{Picker("Language",selection:Binding(get:{model.locale},set:{model.setLocale($0)})){ForEach(L.tags,id:\.self){Text($0).tag($0)}};Picker("AI output language",selection:$model.aiLocale){ForEach(L.tags,id:\.self){Text($0).tag($0)}};Section("Clear local data"){Toggle("History",isOn:$clearHistory);Toggle("Bookmarks",isOn:$clearBookmarks);Toggle("Site permissions",isOn:$clearPermissions);Toggle("Crash recovery",isOn:$clearRecovery);Button("Clear selected data",role:.destructive){model.clear(history:clearHistory,bookmarks:clearBookmarks,permissions:clearPermissions,recovery:clearRecovery);model.showSettings=false}}} .navigationTitle("Settings")}}}
