export const supportedLocales = ["en", "zh-CN", "zh-TW", "ja", "ko", "es", "fr", "de", "pt", "ru", "ar", "id"] as const;
export type Locale = typeof supportedLocales[number];

const en = {
  appName: "YNX AI", signIn: "Sign in with YNX Wallet", signInPurpose: "Approve the exact account and AI scopes in YNX Wallet.",
  noAutoAction: "YNX AI never signs, transfers, publishes, sends, changes permissions, or freezes automatically.",
  conversations: "Conversations", newConversation: "New conversation", emptyConversations: "No conversations yet", archived: "Archived", rename: "Rename", archive: "Archive", delete: "Delete", export: "Export", copy: "Copy",
  ask: "Ask YNX AI", promptHint: "Write a message. Sensitive text is sent only in the encrypted POST body.", send: "Send", cancel: "Cancel", retry: "Retry", streaming: "Streaming provider response…",
  providerAvailable: "Provider available", providerUnavailable: "Provider unavailable. No substitute answer was generated.", rateLimited: "Provider quota reached (429). Retry later.", timedOut: "Request timed out. Retry is available.", offline: "Offline. Reconnect, then retry.",
  model: "Model", usage: "Usage", estimatedCost: "Estimated cost", quotaUnknown: "Provider quota not reported", context: "Context", include: "Include", exclude: "Exclude", attachments: "Attachments", addAttachment: "Add text attachment",
  review: "Review", permissions: "Permissions", tools: "Tools and actions", approve: "Approve", reject: "Reject", explicitApproval: "Every tool or chain action requires explicit approval. Approval does not execute it.",
  privacy: "Privacy and retention", encrypted: "Conversation bodies and attachments are encrypted at rest.", retention: "Retention days", deleteAll: "Delete all AI data", confirmDelete: "Type DELETE to confirm", audit: "Audit", appeal: "Appeal to Trust", restore: "Session restored", signedOut: "Signed out",
  language: "App language", systemLanguage: "System default", outputLanguage: "AI output language", settings: "Settings", history: "History", account: "Account", loading: "Loading…", close: "Close", error: "Error", status: "Status"
} as const;
export type Key = keyof typeof en;

const zhCN: Record<Key,string> = { appName:"YNX AI",signIn:"使用 YNX 钱包登录",signInPurpose:"请在 YNX 钱包中确认准确账户与 AI 权限范围。",noAutoAction:"YNX AI 绝不会自动签名、转账、发布、发送、改变权限或冻结。",conversations:"会话",newConversation:"新建会话",emptyConversations:"暂无会话",archived:"已归档",rename:"重命名",archive:"归档",delete:"删除",export:"导出",copy:"复制",ask:"询问 YNX AI",promptHint:"输入消息。敏感文本仅通过加密 POST 请求体发送。",send:"发送",cancel:"中断",retry:"重试",streaming:"正在流式接收服务商响应…",providerAvailable:"服务商可用",providerUnavailable:"服务商不可用，未生成替代答案。",rateLimited:"服务商配额已达上限（429），请稍后重试。",timedOut:"请求超时，可重试。",offline:"网络离线，请重新连接后重试。",model:"模型",usage:"用量",estimatedCost:"预估成本",quotaUnknown:"服务商未报告配额",context:"上下文",include:"包含",exclude:"排除",attachments:"附件",addAttachment:"添加文本附件",review:"审查",permissions:"权限",tools:"工具与操作",approve:"批准",reject:"拒绝",explicitApproval:"每个工具或链上操作均需明确批准；批准不代表执行。",privacy:"隐私与保留",encrypted:"会话正文与附件均加密存储。",retention:"保留天数",deleteAll:"删除全部 AI 数据",confirmDelete:"输入 DELETE 确认",audit:"审计",appeal:"向 Trust 申诉",restore:"会话已恢复",signedOut:"已退出",language:"应用语言",systemLanguage:"跟随系统",outputLanguage:"AI 输出语言",settings:"设置",history:"历史",account:"账户",loading:"加载中…",close:"关闭",error:"错误",status:"状态"};
const zhTW: Record<Key,string> = { ...zhCN, signIn:"使用 YNX 錢包登入",signInPurpose:"請在 YNX 錢包中確認準確帳戶與 AI 權限範圍。",conversations:"對話",newConversation:"新增對話",emptyConversations:"尚無對話",archive:"封存",archived:"已封存",delete:"刪除",send:"傳送",cancel:"中止",retry:"重試",providerUnavailable:"服務商不可用，未產生替代答案。",permissions:"權限",privacy:"隱私與保留",retention:"保留天數",deleteAll:"刪除全部 AI 資料",settings:"設定",history:"歷史",account:"帳戶" };

const make = (overrides: Partial<Record<Key,string>>): Record<Key,string> => ({...en, ...overrides});
const catalogs: Record<Locale,Record<Key,string>> = {
  en, "zh-CN":zhCN, "zh-TW":zhTW,
  ja:make({signIn:"YNX Walletでサインイン",signInPurpose:"YNX Walletで正確なアカウントとAIスコープを承認してください。",noAutoAction:"YNX AIが自動で署名・送金・公開・送信・権限変更・凍結することはありません。",conversations:"会話",newConversation:"新しい会話",emptyConversations:"会話はまだありません",delete:"削除",send:"送信",cancel:"中断",retry:"再試行",providerUnavailable:"プロバイダーを利用できません。代替回答は生成されていません。",rateLimited:"プロバイダーの上限（429）です。後で再試行してください。",timedOut:"タイムアウトしました。再試行できます。",offline:"オフラインです。再接続して再試行してください。",permissions:"権限",explicitApproval:"すべてのツールとチェーン操作には明示的な承認が必要です。承認だけでは実行されません。",privacy:"プライバシーと保持",language:"アプリの言語",systemLanguage:"システム設定",outputLanguage:"AI出力言語",settings:"設定",audit:"監査"}),
  ko:make({signIn:"YNX Wallet로 로그인",signInPurpose:"YNX Wallet에서 정확한 계정과 AI 범위를 승인하세요.",noAutoAction:"YNX AI는 서명, 송금, 게시, 전송, 권한 변경 또는 동결을 자동으로 수행하지 않습니다.",conversations:"대화",newConversation:"새 대화",emptyConversations:"아직 대화가 없습니다",delete:"삭제",send:"보내기",cancel:"중단",retry:"다시 시도",providerUnavailable:"공급자를 사용할 수 없습니다. 대체 답변을 생성하지 않았습니다.",rateLimited:"공급자 한도(429)에 도달했습니다. 나중에 다시 시도하세요.",offline:"오프라인입니다. 다시 연결한 후 재시도하세요.",permissions:"권한",explicitApproval:"모든 도구와 체인 작업에는 명시적 승인이 필요합니다. 승인만으로 실행되지 않습니다.",privacy:"개인정보 및 보존",language:"앱 언어",systemLanguage:"시스템 기본값",outputLanguage:"AI 출력 언어",settings:"설정",audit:"감사"}),
  es:make({signIn:"Iniciar sesión con YNX Wallet",signInPurpose:"Aprueba la cuenta y los permisos de IA exactos en YNX Wallet.",noAutoAction:"YNX AI nunca firma, transfiere, publica, envía, cambia permisos ni congela automáticamente.",conversations:"Conversaciones",newConversation:"Nueva conversación",emptyConversations:"Aún no hay conversaciones",delete:"Eliminar",send:"Enviar",cancel:"Cancelar",retry:"Reintentar",providerUnavailable:"Proveedor no disponible. No se generó una respuesta sustituta.",rateLimited:"Cuota del proveedor agotada (429). Inténtalo más tarde.",offline:"Sin conexión. Vuelve a conectarte y reintenta.",permissions:"Permisos",explicitApproval:"Cada herramienta o acción en cadena requiere aprobación explícita. Aprobar no la ejecuta.",privacy:"Privacidad y conservación",language:"Idioma de la aplicación",systemLanguage:"Predeterminado del sistema",outputLanguage:"Idioma de salida de IA",settings:"Ajustes",audit:"Auditoría"}),
  fr:make({signIn:"Se connecter avec YNX Wallet",signInPurpose:"Approuvez le compte exact et les portées IA dans YNX Wallet.",noAutoAction:"YNX AI ne signe, transfère, publie, envoie, modifie les autorisations ou ne bloque jamais automatiquement.",conversations:"Conversations",newConversation:"Nouvelle conversation",emptyConversations:"Aucune conversation",delete:"Supprimer",send:"Envoyer",cancel:"Annuler",retry:"Réessayer",providerUnavailable:"Fournisseur indisponible. Aucune réponse de remplacement n’a été générée.",rateLimited:"Quota fournisseur atteint (429). Réessayez plus tard.",offline:"Hors ligne. Reconnectez-vous puis réessayez.",permissions:"Autorisations",explicitApproval:"Chaque outil ou action en chaîne nécessite une approbation explicite. L’approbation ne l’exécute pas.",privacy:"Confidentialité et conservation",language:"Langue de l’application",systemLanguage:"Langue du système",outputLanguage:"Langue de sortie IA",settings:"Paramètres",audit:"Audit"}),
  de:make({signIn:"Mit YNX Wallet anmelden",signInPurpose:"Bestätige das genaue Konto und die AI-Berechtigungen in YNX Wallet.",noAutoAction:"YNX AI signiert, überträgt, veröffentlicht, sendet, ändert Berechtigungen oder sperrt niemals automatisch.",conversations:"Unterhaltungen",newConversation:"Neue Unterhaltung",emptyConversations:"Noch keine Unterhaltungen",delete:"Löschen",send:"Senden",cancel:"Abbrechen",retry:"Erneut versuchen",providerUnavailable:"Anbieter nicht verfügbar. Es wurde keine Ersatzantwort erzeugt.",rateLimited:"Anbieterlimit erreicht (429). Später erneut versuchen.",offline:"Offline. Wieder verbinden und erneut versuchen.",permissions:"Berechtigungen",explicitApproval:"Jedes Tool und jede Chain-Aktion braucht eine ausdrückliche Genehmigung. Genehmigung führt sie nicht aus.",privacy:"Datenschutz und Aufbewahrung",language:"App-Sprache",systemLanguage:"Systemstandard",outputLanguage:"AI-Ausgabesprache",settings:"Einstellungen",audit:"Prüfprotokoll"}),
  pt:make({signIn:"Entrar com YNX Wallet",signInPurpose:"Aprove a conta exata e os escopos de IA na YNX Wallet.",noAutoAction:"A YNX AI nunca assina, transfere, publica, envia, altera permissões ou congela automaticamente.",conversations:"Conversas",newConversation:"Nova conversa",emptyConversations:"Ainda não há conversas",delete:"Excluir",send:"Enviar",cancel:"Cancelar",retry:"Tentar novamente",providerUnavailable:"Provedor indisponível. Nenhuma resposta substituta foi gerada.",rateLimited:"Cota do provedor atingida (429). Tente mais tarde.",offline:"Sem conexão. Reconecte e tente novamente.",permissions:"Permissões",explicitApproval:"Toda ferramenta ou ação na cadeia exige aprovação explícita. Aprovar não a executa.",privacy:"Privacidade e retenção",language:"Idioma do aplicativo",systemLanguage:"Padrão do sistema",outputLanguage:"Idioma de saída da IA",settings:"Configurações",audit:"Auditoria"}),
  ru:make({signIn:"Войти через YNX Wallet",signInPurpose:"Подтвердите точный аккаунт и области AI в YNX Wallet.",noAutoAction:"YNX AI никогда автоматически не подписывает, не переводит, не публикует, не отправляет, не меняет разрешения и не блокирует.",conversations:"Диалоги",newConversation:"Новый диалог",emptyConversations:"Диалогов пока нет",delete:"Удалить",send:"Отправить",cancel:"Отменить",retry:"Повторить",providerUnavailable:"Провайдер недоступен. Подменный ответ не создавался.",rateLimited:"Лимит провайдера исчерпан (429). Повторите позже.",offline:"Нет сети. Подключитесь и повторите.",permissions:"Разрешения",explicitApproval:"Каждый инструмент или действие в цепи требует явного одобрения. Одобрение не запускает действие.",privacy:"Конфиденциальность и хранение",language:"Язык приложения",systemLanguage:"Системный",outputLanguage:"Язык ответа AI",settings:"Настройки",audit:"Аудит"}),
  ar:make({signIn:"تسجيل الدخول بمحفظة YNX",signInPurpose:"وافق على الحساب ونطاقات الذكاء الاصطناعي المحددة في محفظة YNX.",noAutoAction:"لا يوقّع YNX AI أو يحوّل أو ينشر أو يرسل أو يغيّر الصلاحيات أو يجمّد تلقائيًا.",conversations:"المحادثات",newConversation:"محادثة جديدة",emptyConversations:"لا توجد محادثات بعد",delete:"حذف",send:"إرسال",cancel:"إلغاء",retry:"إعادة المحاولة",providerUnavailable:"المزوّد غير متاح. لم يتم إنشاء إجابة بديلة.",rateLimited:"تم بلوغ حصة المزوّد (429). حاول لاحقًا.",timedOut:"انتهت مهلة الطلب. يمكن إعادة المحاولة.",offline:"غير متصل. أعد الاتصال ثم حاول.",permissions:"الصلاحيات",explicitApproval:"تتطلب كل أداة أو عملية على السلسلة موافقة صريحة. الموافقة لا تنفّذها.",privacy:"الخصوصية والاحتفاظ",language:"لغة التطبيق",systemLanguage:"لغة النظام",outputLanguage:"لغة إخراج الذكاء الاصطناعي",settings:"الإعدادات",audit:"التدقيق",confirmDelete:"اكتب DELETE للتأكيد"}),
  id:make({signIn:"Masuk dengan YNX Wallet",signInPurpose:"Setujui akun dan cakupan AI yang tepat di YNX Wallet.",noAutoAction:"YNX AI tidak pernah menandatangani, mentransfer, menerbitkan, mengirim, mengubah izin, atau membekukan secara otomatis.",conversations:"Percakapan",newConversation:"Percakapan baru",emptyConversations:"Belum ada percakapan",delete:"Hapus",send:"Kirim",cancel:"Batalkan",retry:"Coba lagi",providerUnavailable:"Penyedia tidak tersedia. Tidak ada jawaban pengganti yang dibuat.",rateLimited:"Kuota penyedia tercapai (429). Coba lagi nanti.",offline:"Luring. Sambungkan kembali lalu coba lagi.",permissions:"Izin",explicitApproval:"Setiap alat atau tindakan rantai memerlukan persetujuan tegas. Persetujuan tidak menjalankannya.",privacy:"Privasi dan retensi",language:"Bahasa aplikasi",systemLanguage:"Bawaan sistem",outputLanguage:"Bahasa keluaran AI",settings:"Pengaturan",audit:"Audit"})
};

export const isRTL = (locale: Locale) => locale === "ar";
export const translate = (locale: Locale, key: Key): string => catalogs[locale][key] || en[key];
export const resolveLocale = (requested?: string | null): Locale => {
  const normalized = (requested || "").replace("_", "-");
  if ((supportedLocales as readonly string[]).includes(normalized)) return normalized as Locale;
  const language = normalized.split("-")[0];
  return supportedLocales.find(value => value === language) || (language === "zh" ? "zh-CN" : "en");
};
export const formatDate = (locale: Locale, value: string | Date) => new Intl.DateTimeFormat(locale, {dateStyle:"medium",timeStyle:"short"}).format(new Date(value));
export const formatNumber = (locale: Locale, value: number) => new Intl.NumberFormat(locale, {maximumFractionDigits:2}).format(value);
export const formatMoney = (locale: Locale, value: number) => new Intl.NumberFormat(locale, {style:"currency",currency:"USD",maximumFractionDigits:4}).format(value);
export const plural = (locale: Locale, count: number, one: string, many: string) => new Intl.PluralRules(locale).select(count) === "one" ? one : many;
export const catalogForTest = catalogs;
