export const NETWORK = "ynx_6423-1";
export const ASSET = "YNXT";
export const FEE = 1;
const DEFAULT_GATEWAY=process.env.EXPO_PUBLIC_YNX_GATEWAY_URL?.replace(/\/$/,"")??"";
const DEFAULT_API=DEFAULT_GATEWAY?`${DEFAULT_GATEWAY}/app/pay-product`:"";
const QUANT_VERIFIERS=parseVerifierConfig(process.env.EXPO_PUBLIC_YNX_QUANT_VERIFIERS??"");

export type FeeBreakdown = Readonly<{networkFee:number;providerCost:number;protocolFee:number;burn:number;treasury:number;merchantNet:number;sponsorCost:number;userRebate:number;source:string;asOf:string;version:1}>;
export type Settlement = Readonly<{ id:string; chainId:"ynx_6423-1"; transactionHash:string; blockNumber:number; finality:"committed"; payer:string; payee:string; payoutAddress:string; amount:number; asset:"YNXT"; invoiceId:string; centralInvoiceId:string; intentId:string; intentDigest?:string; requestNonce?:string; idempotencyKey:string; receiptId:string; status:"committed"; auditHash:string; auditId:string; committedAt:string; source:"authoritative-central-pay-api"; sourceAsOf:string; sourceVersion:1; confidence:"authoritative" }>;
export type Invoice = Readonly<{ version:1|2|3|4|5; id:string; centralInvoiceId:string; intentId:string; merchantId:string; merchantName:string; payoutAddress:string; description?:string; baseAmount?:number; tipAmount?:number; splitPaymentId?:string; splitShareId?:string; serviceBillId?:string; serviceEvidenceDigest?:string; expectedPayerHash?:string; amount:number; asset:"YNXT"; network:"ynx_6423-1"; fee:1; feeBreakdown?:FeeBreakdown; status:"pending"|"committed"|"expired"; expiresAt:string; createdAt:string; signature:string; signatureKeyId:string; signingPublicKey:string; signatureAlgorithm:"ed25519"; settlement?:Settlement }>;
export type SplitShare = Readonly<{id:string;label:string;amount:number;invoiceId?:string;status:"open"|"pending"|"committed"|"expired"}>;
export type SplitPayment = Readonly<{version:1;id:string;merchantId:string;merchantName:string;payoutAddress:string;description:string;totalAmount:number;asset:"YNXT";network:"ynx_6423-1";status:"open"|"partially_claimed"|"partially_paid"|"committed"|"expired";shares:readonly SplitShare[];expiresAt:string;createdAt:string;updatedAt:string;signature:string;signatureKeyId:string;signingPublicKey:string;signatureAlgorithm:"ed25519"}>;
export type QuantBillingEvidence = Readonly<{version:1;evidenceId:string;merchantId:string;payerAccountHash:string;invoicePayerAccountHash:string;serviceReference:string;periodStart:string;periodEnd:string;startEquityYnxt:number;endEquityYnxt:number;netExternalFlowsYnxt:number;previousHighWaterMarkYnxt:number;performanceFeeBps:number;computeFeeYnxt:number;dataFeeYnxt:number;subscriptionFeeYnxt:number;managementFeeYnxt:number;asset:"YNXT";network:"ynx_6423-1";source:string;sourceVersion:number;asOf:string;expiresAt:string;evidenceKeyId:string;evidencePublicKey:string;signatureAlgorithm:"ed25519";signature:string}>;
export type QuantBillingBreakdown = Readonly<{startEquityYnxt:number;endEquityYnxt:number;netExternalFlowsYnxt:number;adjustedEndEquityYnxt:number;previousHighWaterMarkYnxt:number;highWaterMarkBaseYnxt:number;eligibleProfitYnxt:number;performanceFeeBps:number;performanceFeeYnxt:number;newHighWaterMarkYnxt:number;computeFeeYnxt:number;dataFeeYnxt:number;subscriptionFeeYnxt:number;managementFeeYnxt:number;totalServiceFeeYnxt:number;calculationDomain:"YNX_QUANT_HIGH_WATER_MARK_V1";performanceFeeRounding:"floor-to-whole-YNXT-unit";externalPnlRequired:true;frontendPnlAccepted:false;managerDeclaredPnlAccepted:false}>;
export type QuantBill = Readonly<{version:1;id:string;merchantId:string;merchantName:string;payoutAddress:string;payerAccountHash:string;serviceReference:string;periodStart:string;periodEnd:string;asset:"YNXT";network:"ynx_6423-1";breakdown:QuantBillingBreakdown;evidence:QuantBillingEvidence;evidenceDigest:string;invoiceId:string;status:"pending"|"committed"|"expired";createdAt:string;updatedAt:string}>;
import type { AuthorizationRequest, AuthorizationResponse, GatewayChallenge, GatewayCompletion, SignedPaymentIntent, WalletPaymentResult } from "./walletAuth";
export type WalletSession = Readonly<{ sessionId:string; token:string; account:string; sessionBinding:string; scopes:string[]; expiresAt:string }>;

export class PayAPIError extends Error { constructor(readonly code:"invalid"|"offline"|"unavailable"|"unauthorized"|"expired"|"tamper"|"unknown",message:string,readonly status=0){super(message);this.name="PayAPIError"} }

export function invoiceID(value:string):string {
  const raw=value.trim();
  if(/^inv_[a-f0-9]{20}$/.test(raw)) return raw;
  try { const u=new URL(raw); const match=u.pathname.match(/\/invoices\/(inv_[a-f0-9]{20})$/); if(match?.[1]) return match[1] } catch {}
  const deep=raw.match(/^ynxpay:\/\/invoice\/(inv_[a-f0-9]{20})$/); if(deep?.[1]) return deep[1];
  throw new Error("Use a canonical YNX Pay invoice ID, QR, or deep link.");
}
export function splitPaymentID(value:string):string {
  const raw=value.trim();
  if(/^spl_[a-f0-9]{20}$/.test(raw)) return raw;
  try { const u=new URL(raw); const match=u.pathname.match(/\/split-payments\/(spl_[a-f0-9]{20})$/); if(match?.[1]) return match[1] } catch {}
  const deep=raw.match(/^ynxpay:\/\/split\/(spl_[a-f0-9]{20})$/); if(deep?.[1]) return deep[1];
  throw new Error("Use a canonical YNX Pay split ID, QR, or deep link.");
}
export function isSplitPaymentReference(value:string):boolean{try{splitPaymentID(value);return true}catch{return false}}
export function quantBillID(value:string):string{const raw=value.trim();if(/^qbl_[a-f0-9]{20}$/.test(raw))return raw;try{const u=new URL(raw);const match=u.pathname.match(/\/quant-bills\/(qbl_[a-f0-9]{20})$/);if(match?.[1])return match[1]}catch{}const deep=raw.match(/^ynxpay:\/\/quant\/(qbl_[a-f0-9]{20})$/);if(deep?.[1])return deep[1];throw new Error("Use a canonical YNX Quant bill ID or link.")}
export function isQuantBillReference(value:string):boolean{try{quantBillID(value);return true}catch{return false}}
export async function getInvoice(reference:string,signal?:AbortSignal):Promise<Invoice> { const invoice=parseInvoice(await request(`/v1/invoices/${encodeURIComponent(invoiceID(reference))}`,{signal})); if(!(await verifyInvoiceSignature(invoice))) throw new Error("Merchant invoice signature verification failed"); return invoice }
export async function getSplitPayment(splitId:string,signal?:AbortSignal):Promise<SplitPayment>{const split=parseSplitPayment(await request(`/v1/split-payments/${encodeURIComponent(splitPaymentID(splitId))}`,{signal}));if(!(await verifySplitPaymentSignature(split)))throw new Error("Merchant split signature verification failed");return split}
export async function claimSplitShare(splitId:string,shareId:string,idempotencyKey:string,token:string):Promise<SplitPayment>{const split=parseSplitPayment(await request(`/v1/split-payments/${encodeURIComponent(splitPaymentID(splitId))}/shares/${encodeURIComponent(shareID(shareId))}/claim`,{method:"POST",token,body:JSON.stringify({idempotencyKey})}));if(!(await verifySplitPaymentSignature(split)))throw new Error("Merchant split signature verification failed");return split}
export async function getQuantBill(reference:string,signal?:AbortSignal):Promise<QuantBill>{const bill=parseQuantBill(await request(`/v1/quant-bills/${encodeURIComponent(quantBillID(reference))}`,{signal}));if(!(await verifyQuantBillEvidence(bill)))throw new PayAPIError("unavailable","The Quant evidence signer is not configured or the evidence signature is invalid");return bill}
export async function requestWalletChallenge(input:{request:AuthorizationRequest;approval:AuthorizationResponse}):Promise<GatewayChallenge>{return gatewayRequest("/app/pay/session/challenges",input) as Promise<GatewayChallenge>}
export async function completeWalletSession(input:{request:AuthorizationRequest;approval:AuthorizationResponse;completion:GatewayCompletion}):Promise<WalletSession>{return parseSession(await gatewayRequest("/app/pay/session/complete",input))}
export async function submitSettlement(invoice:string,intent:SignedPaymentIntent,result:WalletPaymentResult,idempotencyKey:string,token:string):Promise<Invoice> { return parseInvoice(await request(`/v1/invoices/${encodeURIComponent(invoice)}/settlements`,{method:"POST",token,body:JSON.stringify({intent,result,idempotencyKey})})) }
export async function requestRefund(invoice:string,amount:number,reason:string,idempotencyKey:string,token:string) { return request(`/v1/invoices/${encodeURIComponent(invoice)}/refund-requests`,{method:"POST",token,body:JSON.stringify({amount,reason,idempotencyKey})}) }
export async function openDispute(invoice:string,reason:string,trustEvidence:string[],idempotencyKey:string,token:string) { return request(`/v1/invoices/${encodeURIComponent(invoice)}/disputes`,{method:"POST",token,body:JSON.stringify({reason,trustEvidence,idempotencyKey})}) }
export async function requestSponsorship(invoice:string,input:{smartAccount:string;mode:"first-payment"|"merchant-sponsored";callDataHash:string;idempotencyKey:string},token:string){return request(`/v1/invoices/${encodeURIComponent(invoice)}/sponsorship-quotes`,{method:"POST",token,body:JSON.stringify(input)})}
export async function confirmSponsorship(quoteId:string,userOperationHash:string,token:string){return request(`/v1/sponsorships/${encodeURIComponent(quoteId)}/receipts`,{method:"POST",token,body:JSON.stringify({userOperationHash})})}
export async function createRouteQuote(invoice:string,input:{sourceChain:string;sourceAsset:string;sourceAmount:number;maxTotalCostYnxt?:number;maxSettlementSeconds?:number;acceptBridgeRiskBps?:number;preferSponsored?:boolean;idempotencyKey:string},token:string){return request(`/v1/invoices/${encodeURIComponent(invoice)}/route-quotes`,{method:"POST",token,body:JSON.stringify(input)})}
export async function selectRoute(quoteId:string,optionId:string,token:string){return request(`/v1/route-quotes/${encodeURIComponent(quoteId)}/select`,{method:"POST",token,body:JSON.stringify({optionId})})}
export async function refreshBridge(transferId:string,token:string){return request(`/v1/bridge-transfers/${encodeURIComponent(transferId)}/refresh`,{method:"POST",token,body:"{}"})}
async function request(path:string,options:{method?:string;body?:string;token?:string;signal?:AbortSignal}={}):Promise<unknown> { if(!DEFAULT_API)throw new PayAPIError("unavailable","YNX Pay product service URL is not configured");const controller=new AbortController();const abort=()=>controller.abort();if(options.signal?.aborted)controller.abort();else options.signal?.addEventListener("abort",abort,{once:true});const timeout=setTimeout(abort,10_000);let response:Response;try{response=await fetch(DEFAULT_API+path,{method:options.method??"GET",body:options.body,signal:controller.signal,headers:{"Content-Type":"application/json",Accept:"application/json",...(options.token?{Authorization:`Bearer ${options.token}`}:{})}})}catch(error){if(error instanceof Error&&error.name==="AbortError")throw new PayAPIError("offline","YNX Pay request timed out or the device is offline");throw new PayAPIError("offline","YNX Pay service is unreachable")}finally{clearTimeout(timeout);options.signal?.removeEventListener("abort",abort)}const value=await response.json().catch(()=>({error:"Invalid server response"}));if(!response.ok){const raw=isObject(value)&&typeof value.error==="string"?value.error:`YNX Pay returned ${response.status}`;const code=response.status===401?"unauthorized":/expired/i.test(raw)?"expired":/tamper|mismatch|signature|replay/i.test(raw)?"tamper":response.status>=500?"unavailable":"unknown";throw new PayAPIError(code,raw,response.status)}return value }
async function gatewayRequest(path:string,body:unknown):Promise<unknown>{if(!DEFAULT_GATEWAY)throw new PayAPIError("unavailable","YNX App Gateway URL is not configured");let response:Response;try{response=await fetch(DEFAULT_GATEWAY+path,{method:"POST",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify(body)})}catch{throw new PayAPIError("offline","YNX App Gateway is unreachable")}const value=await response.json().catch(()=>({error:"Invalid Gateway response"}));if(!response.ok){const raw=isObject(value)&&typeof value.error==="string"?value.error:`YNX Gateway returned ${response.status}`;throw new PayAPIError(response.status===401?"unauthorized":/expired/i.test(raw)?"expired":/tamper|mismatch|signature|replay|scope|callback/i.test(raw)?"tamper":response.status>=500?"unavailable":"unknown",raw,response.status)}return value}

export function parseInvoice(value:unknown):Invoice {
  if(!isObject(value)) throw new Error("Invalid invoice response"); const status=required(value.status,"status"); if(!["pending","committed","expired"].includes(status)) throw new Error("Invoice status is not authoritative");
  const version=integer(value.version,"version");const result={version,id:id(value.id,"invoice"),centralInvoiceId:required(value.centralInvoiceId,"central invoice"),intentId:required(value.intentId,"intent"),merchantId:required(value.merchantId,"merchant"),merchantName:required(value.merchantName,"merchant name"),payoutAddress:nativeAddress(value.payoutAddress),description:typeof value.description==="string"?value.description:undefined,baseAmount:version>=3?positive(value.baseAmount,"base amount"):undefined,tipAmount:version>=3?nonnegative(value.tipAmount,"tip amount"):undefined,splitPaymentId:version===4?splitID(value.splitPaymentId):undefined,splitShareId:version===4?shareID(value.splitShareId):undefined,serviceBillId:version===5?quantBillID(required(value.serviceBillId,"service bill")):undefined,serviceEvidenceDigest:version===5?hex(value.serviceEvidenceDigest,64):undefined,expectedPayerHash:version===4||version===5?hex(value.expectedPayerHash,64):undefined,amount:positive(value.amount,"amount"),asset:required(value.asset,"asset"),network:required(value.network,"network"),fee:integer(value.fee,"fee"),feeBreakdown:version>=2?parseFeeBreakdown(value.feeBreakdown):undefined,status,expiresAt:date(value.expiresAt),createdAt:date(value.createdAt),signature:hex(value.signature,128),signatureKeyId:required(value.signatureKeyId,"signature key"),signingPublicKey:hex(value.signingPublicKey,64),signatureAlgorithm:required(value.signatureAlgorithm,"signature algorithm"),settlement:value.settlement===undefined?undefined:parseSettlement(value.settlement)} as Invoice;
  if(![1,2,3,4,5].includes(result.version)||result.asset!==ASSET||result.network!==NETWORK||result.fee!==FEE||result.signatureAlgorithm!=="ed25519") throw new Error("Invoice network, asset, fee, or signature algorithm is unsafe");
  if(result.version>=2&&(!result.feeBreakdown||result.feeBreakdown.networkFee!==result.fee||result.feeBreakdown.merchantNet!==result.amount))throw new Error("Invoice fee breakdown does not reconcile");
  if(result.version>=3&&((result.baseAmount??0)+(result.tipAmount??0)!==result.amount||(result.tipAmount??0)>(result.baseAmount??0)))throw new Error("Invoice tip does not reconcile");
  if(result.status==="committed"&&!result.settlement) throw new Error("Committed invoice is missing transaction evidence"); if(result.status!=="committed"&&result.settlement) throw new Error("Uncommitted invoice included settlement evidence");if(result.settlement&&(result.settlement.invoiceId!==result.id||result.settlement.centralInvoiceId!==result.centralInvoiceId||result.settlement.intentId!==result.intentId||result.settlement.payee!==result.payoutAddress||result.settlement.amount!==result.amount))throw new Error("Settlement evidence does not match the invoice"); return Object.freeze(result);
}
export async function verifyInvoiceSignature(invoice:Invoice):Promise<boolean> {
  const [{ed25519},{hexToBytes}]=await Promise.all([import("@noble/curves/ed25519.js"),import("@noble/hashes/utils.js")]);
  const base=[String(invoice.version),invoice.id,invoice.centralInvoiceId,invoice.intentId,invoice.merchantId,invoice.merchantName,invoice.payoutAddress,String(invoice.amount),invoice.asset,invoice.network,String(invoice.fee)];
  const v1=["YNX_PAY_INVOICE_V1",...base,invoice.expiresAt,invoice.createdAt,invoice.signatureKeyId,invoice.signingPublicKey,invoice.signatureAlgorithm];
  const v2=["YNX_PAY_INVOICE_V2",...base,...feeMaterial(invoice.feeBreakdown!),invoice.expiresAt,invoice.createdAt,invoice.signatureKeyId,invoice.signingPublicKey,invoice.signatureAlgorithm];
  const v3=["YNX_PAY_INVOICE_V3",...base,...feeMaterial(invoice.feeBreakdown!),String(invoice.baseAmount),String(invoice.tipAmount),invoice.expiresAt,invoice.createdAt,invoice.signatureKeyId,invoice.signingPublicKey,invoice.signatureAlgorithm];
  const v4=["YNX_PAY_INVOICE_V4",...base,...feeMaterial(invoice.feeBreakdown!),String(invoice.baseAmount),String(invoice.tipAmount),invoice.expiresAt,invoice.createdAt,invoice.signatureKeyId,invoice.signingPublicKey,invoice.signatureAlgorithm,invoice.splitPaymentId!,invoice.splitShareId!,invoice.expectedPayerHash!];
  const v5=["YNX_PAY_INVOICE_V5",...base,...feeMaterial(invoice.feeBreakdown!),String(invoice.baseAmount),String(invoice.tipAmount),invoice.expiresAt,invoice.createdAt,invoice.signatureKeyId,invoice.signingPublicKey,invoice.signatureAlgorithm,invoice.serviceBillId!,invoice.serviceEvidenceDigest!,invoice.expectedPayerHash!];
  const material=(invoice.version===1?v1:invoice.version===2?v2:invoice.version===3?v3:invoice.version===4?v4:v5).join("|");
  return ed25519.verify(hexToBytes(invoice.signature),new TextEncoder().encode(material),hexToBytes(invoice.signingPublicKey));
}
function parseFeeBreakdown(value:unknown):FeeBreakdown{if(!isObject(value))throw new Error("Missing fee breakdown");const result={networkFee:nonnegative(value.networkFee,"network fee"),providerCost:nonnegative(value.providerCost,"provider cost"),protocolFee:nonnegative(value.protocolFee,"protocol fee"),burn:nonnegative(value.burn,"burn"),treasury:nonnegative(value.treasury,"treasury"),merchantNet:positive(value.merchantNet,"merchant net"),sponsorCost:nonnegative(value.sponsorCost,"sponsor cost"),userRebate:nonnegative(value.userRebate,"user rebate"),source:required(value.source,"fee source"),asOf:date(value.asOf),version:integer(value.version,"fee version")} as FeeBreakdown;if(result.version!==1)throw new Error("Unsupported fee breakdown version");return Object.freeze(result)}
function feeMaterial(v:FeeBreakdown){return [String(v.networkFee),String(v.providerCost),String(v.protocolFee),String(v.burn),String(v.treasury),String(v.merchantNet),String(v.sponsorCost),String(v.userRebate),v.source,v.asOf,String(v.version)]}
function parseSettlement(value:unknown):Settlement { if(!isObject(value)) throw new Error("Invalid settlement evidence"); const result={id:required(value.id,"settlement"),chainId:required(value.chainId,"chain"),transactionHash:`0x${hex(String(value.transactionHash).replace(/^0x/,""),64)}`,blockNumber:positive(value.blockNumber,"block"),finality:required(value.finality,"finality"),payer:nativeAddress(value.payer),payee:nativeAddress(value.payee),payoutAddress:nativeAddress(value.payoutAddress),amount:positive(value.amount,"settled amount"),asset:required(value.asset,"asset"),invoiceId:id(value.invoiceId,"receipt invoice"),centralInvoiceId:required(value.centralInvoiceId,"receipt central invoice"),intentId:required(value.intentId,"receipt intent"),intentDigest:typeof value.intentDigest==="string"?hex(value.intentDigest,64):undefined,requestNonce:typeof value.requestNonce==="string"?required(value.requestNonce,"request nonce"):undefined,idempotencyKey:required(value.idempotencyKey,"settlement idempotency"),receiptId:required(value.receiptId,"receipt"),status:required(value.status,"settlement status"),auditHash:hex(value.auditHash,64),auditId:required(value.auditId,"audit ID"),committedAt:date(value.committedAt),source:required(value.source,"evidence source"),sourceAsOf:date(value.sourceAsOf),sourceVersion:integer(value.sourceVersion,"source version"),confidence:required(value.confidence,"confidence")} as Settlement; if(result.status!=="committed"||result.finality!=="committed"||result.chainId!==NETWORK||result.asset!==ASSET||result.source!=="authoritative-central-pay-api"||result.sourceVersion!==1||result.confidence!=="authoritative"||result.payee!==result.payoutAddress) throw new Error("Settlement is not authoritative committed YNXT evidence"); return Object.freeze(result) }
export function parseSplitPayment(value:unknown):SplitPayment{
  if(!isObject(value)||!Array.isArray(value.shares))throw new Error("Invalid split payment response");
  const status=required(value.status,"split status");if(!["open","partially_claimed","partially_paid","committed","expired"].includes(status))throw new Error("Invalid split status");
  const shares=value.shares.map(raw=>{if(!isObject(raw))throw new Error("Invalid split share");if(typeof raw.payerAccount==="string"&&raw.payerAccount)throw new Error("Public split response exposed a payer account");const shareStatus=required(raw.status,"share status");if(!["open","pending","committed","expired"].includes(shareStatus))throw new Error("Invalid split share status");return Object.freeze({id:shareID(raw.id),label:required(raw.label,"share label"),amount:positive(raw.amount,"share amount"),invoiceId:raw.invoiceId===undefined?undefined:id(raw.invoiceId,"share invoice"),status:shareStatus}) as SplitShare});
  if(shares.length<2||shares.length>20||new Set(shares.map(v=>v.id)).size!==shares.length||new Set(shares.map(v=>v.label.toLowerCase())).size!==shares.length)throw new Error("Invalid split shares");
  const result={version:integer(value.version,"split version"),id:splitID(value.id),merchantId:required(value.merchantId,"merchant"),merchantName:required(value.merchantName,"merchant name"),payoutAddress:nativeAddress(value.payoutAddress),description:required(value.description,"description"),totalAmount:positive(value.totalAmount,"total amount"),asset:required(value.asset,"asset"),network:required(value.network,"network"),status,shares:Object.freeze(shares),expiresAt:date(value.expiresAt),createdAt:date(value.createdAt),updatedAt:date(value.updatedAt),signature:hex(value.signature,128),signatureKeyId:required(value.signatureKeyId,"signature key"),signingPublicKey:hex(value.signingPublicKey,64),signatureAlgorithm:required(value.signatureAlgorithm,"signature algorithm")} as SplitPayment;
  if(result.version!==1||result.asset!==ASSET||result.network!==NETWORK||result.signatureAlgorithm!=="ed25519"||shares.reduce((sum,v)=>sum+v.amount,0)!==result.totalAmount)throw new Error("Split payment authority or total is invalid");
  return Object.freeze(result);
}
export async function verifySplitPaymentSignature(split:SplitPayment):Promise<boolean>{
  const [{ed25519},{hexToBytes}]=await Promise.all([import("@noble/curves/ed25519.js"),import("@noble/hashes/utils.js")]);
  const material=["YNX_PAY_SPLIT_V1",String(split.version),split.id,split.merchantId,split.merchantName,split.payoutAddress,split.description,String(split.totalAmount),split.asset,split.network,...split.shares.flatMap(v=>[v.id,v.label,String(v.amount)]),split.expiresAt,split.createdAt,split.signatureKeyId,split.signingPublicKey,split.signatureAlgorithm].join("|");
  return ed25519.verify(hexToBytes(split.signature),new TextEncoder().encode(material),hexToBytes(split.signingPublicKey));
}
export function parseQuantBill(value:unknown):QuantBill{
  if(!isObject(value)||!isObject(value.breakdown)||!isObject(value.evidence))throw new Error("Invalid Quant bill response");
  if(typeof value.payerAccount==="string"&&value.payerAccount)throw new Error("Public Quant bill exposed a payer account");
  if(typeof value.evidence.payerAccount==="string"&&value.evidence.payerAccount)throw new Error("Public Quant evidence exposed a payer account");
  const evidence=parseQuantEvidence(value.evidence),breakdown=parseQuantBreakdown(value.breakdown);
  const status=required(value.status,"Quant bill status");if(!["pending","committed","expired"].includes(status))throw new Error("Invalid Quant bill status");
  const result={version:integer(value.version,"Quant bill version"),id:quantBillID(required(value.id,"Quant bill")),merchantId:required(value.merchantId,"merchant"),merchantName:required(value.merchantName,"merchant name"),payoutAddress:nativeAddress(value.payoutAddress),payerAccountHash:hex(value.payerAccountHash,64),serviceReference:required(value.serviceReference,"service reference"),periodStart:date(value.periodStart),periodEnd:date(value.periodEnd),asset:required(value.asset,"asset"),network:required(value.network,"network"),breakdown,evidence,evidenceDigest:hex(value.evidenceDigest,64),invoiceId:id(value.invoiceId,"Quant invoice"),status,createdAt:date(value.createdAt),updatedAt:date(value.updatedAt)} as QuantBill;
  if(result.version!==1||result.asset!==ASSET||result.network!==NETWORK||result.merchantId!==evidence.merchantId||result.payerAccountHash!==evidence.invoicePayerAccountHash||result.serviceReference!==evidence.serviceReference||result.periodStart!==evidence.periodStart||result.periodEnd!==evidence.periodEnd)throw new Error("Quant bill identity does not match its evidence");
  verifyQuantCalculation(evidence,breakdown);
  return Object.freeze(result);
}
function parseQuantEvidence(value:Record<string,unknown>):QuantBillingEvidence{
  const result={version:integer(value.version,"evidence version"),evidenceId:safeIdentifier(value.evidenceId,"evidence ID"),merchantId:safeIdentifier(value.merchantId,"merchant"),payerAccountHash:hex(value.payerAccountHash,64),invoicePayerAccountHash:hex(value.invoicePayerAccountHash,64),serviceReference:safeIdentifier(value.serviceReference,"service reference"),periodStart:date(value.periodStart),periodEnd:date(value.periodEnd),startEquityYnxt:positive(value.startEquityYnxt,"start equity"),endEquityYnxt:nonnegative(value.endEquityYnxt,"end equity"),netExternalFlowsYnxt:integer(value.netExternalFlowsYnxt,"net external flows"),previousHighWaterMarkYnxt:nonnegative(value.previousHighWaterMarkYnxt,"previous high-water mark"),performanceFeeBps:nonnegative(value.performanceFeeBps,"performance fee bps"),computeFeeYnxt:nonnegative(value.computeFeeYnxt,"compute fee"),dataFeeYnxt:nonnegative(value.dataFeeYnxt,"data fee"),subscriptionFeeYnxt:nonnegative(value.subscriptionFeeYnxt,"subscription fee"),managementFeeYnxt:nonnegative(value.managementFeeYnxt,"management fee"),asset:required(value.asset,"asset"),network:required(value.network,"network"),source:safeIdentifier(value.source,"source"),sourceVersion:positive(value.sourceVersion,"source version"),asOf:date(value.asOf),expiresAt:date(value.expiresAt),evidenceKeyId:safeIdentifier(value.evidenceKeyId,"evidence key ID"),evidencePublicKey:hex(value.evidencePublicKey,64),signatureAlgorithm:required(value.signatureAlgorithm,"signature algorithm"),signature:hex(value.signature,128)} as QuantBillingEvidence;
  if(result.version!==1||result.asset!==ASSET||result.network!==NETWORK||result.signatureAlgorithm!=="ed25519"||result.performanceFeeBps>5000||Date.parse(result.periodStart)>=Date.parse(result.periodEnd)||Date.parse(result.periodEnd)>Date.parse(result.asOf)||Date.parse(result.expiresAt)<=Date.parse(result.asOf))throw new Error("Quant evidence authority or time bounds are invalid");
  return Object.freeze(result);
}
function parseQuantBreakdown(value:Record<string,unknown>):QuantBillingBreakdown{return Object.freeze({startEquityYnxt:positive(value.startEquityYnxt,"start equity"),endEquityYnxt:nonnegative(value.endEquityYnxt,"end equity"),netExternalFlowsYnxt:integer(value.netExternalFlowsYnxt,"net external flows"),adjustedEndEquityYnxt:nonnegative(value.adjustedEndEquityYnxt,"adjusted end equity"),previousHighWaterMarkYnxt:nonnegative(value.previousHighWaterMarkYnxt,"previous high-water mark"),highWaterMarkBaseYnxt:nonnegative(value.highWaterMarkBaseYnxt,"high-water-mark base"),eligibleProfitYnxt:nonnegative(value.eligibleProfitYnxt,"eligible profit"),performanceFeeBps:nonnegative(value.performanceFeeBps,"performance fee bps"),performanceFeeYnxt:nonnegative(value.performanceFeeYnxt,"performance fee"),newHighWaterMarkYnxt:nonnegative(value.newHighWaterMarkYnxt,"new high-water mark"),computeFeeYnxt:nonnegative(value.computeFeeYnxt,"compute fee"),dataFeeYnxt:nonnegative(value.dataFeeYnxt,"data fee"),subscriptionFeeYnxt:nonnegative(value.subscriptionFeeYnxt,"subscription fee"),managementFeeYnxt:nonnegative(value.managementFeeYnxt,"management fee"),totalServiceFeeYnxt:positive(value.totalServiceFeeYnxt,"total service fee"),calculationDomain:required(value.calculationDomain,"calculation domain"),performanceFeeRounding:required(value.performanceFeeRounding,"performance fee rounding"),externalPnlRequired:value.externalPnlRequired,frontendPnlAccepted:value.frontendPnlAccepted,managerDeclaredPnlAccepted:value.managerDeclaredPnlAccepted} as QuantBillingBreakdown)}
function verifyQuantCalculation(e:QuantBillingEvidence,b:QuantBillingBreakdown){const adjusted=safeBigIntToNumber(BigInt(e.endEquityYnxt)-BigInt(e.netExternalFlowsYnxt),"adjusted end equity"),hwm=Math.max(e.previousHighWaterMarkYnxt,e.startEquityYnxt),eligible=Math.max(0,adjusted-hwm),performance=safeBigIntToNumber(BigInt(eligible)*BigInt(e.performanceFeeBps)/10000n,"performance fee"),total=safeSum(e.computeFeeYnxt,e.dataFeeYnxt,e.subscriptionFeeYnxt,e.managementFeeYnxt,performance),newHWM=Math.max(e.previousHighWaterMarkYnxt,adjusted-performance);if(adjusted<0||b.startEquityYnxt!==e.startEquityYnxt||b.endEquityYnxt!==e.endEquityYnxt||b.netExternalFlowsYnxt!==e.netExternalFlowsYnxt||b.adjustedEndEquityYnxt!==adjusted||b.previousHighWaterMarkYnxt!==e.previousHighWaterMarkYnxt||b.highWaterMarkBaseYnxt!==hwm||b.eligibleProfitYnxt!==eligible||b.performanceFeeBps!==e.performanceFeeBps||b.performanceFeeYnxt!==performance||b.newHighWaterMarkYnxt!==newHWM||b.computeFeeYnxt!==e.computeFeeYnxt||b.dataFeeYnxt!==e.dataFeeYnxt||b.subscriptionFeeYnxt!==e.subscriptionFeeYnxt||b.managementFeeYnxt!==e.managementFeeYnxt||b.totalServiceFeeYnxt!==total||b.calculationDomain!=="YNX_QUANT_HIGH_WATER_MARK_V1"||b.performanceFeeRounding!=="floor-to-whole-YNXT-unit"||b.externalPnlRequired!==true||b.frontendPnlAccepted!==false||b.managerDeclaredPnlAccepted!==false)throw new Error("Quant high-water-mark calculation does not reconcile")}
export async function verifyQuantBillEvidence(bill:QuantBill,verifiers:Readonly<Record<string,string>>=QUANT_VERIFIERS):Promise<boolean>{const approved=verifiers[bill.evidence.evidenceKeyId]?.toLowerCase();if(!approved||approved!==bill.evidence.evidencePublicKey)return false;const [{ed25519},{sha256},{bytesToHex,hexToBytes}]=await Promise.all([import("@noble/curves/ed25519.js"),import("@noble/hashes/sha2.js"),import("@noble/hashes/utils.js")]);const material=quantEvidenceMaterial(bill.evidence),bytes=new TextEncoder().encode(material);return bytesToHex(sha256(bytes))===bill.evidenceDigest&&ed25519.verify(hexToBytes(bill.evidence.signature),bytes,hexToBytes(approved))}
function quantEvidenceMaterial(e:QuantBillingEvidence){return ["YNX_QUANT_BILLING_EVIDENCE_V1",String(e.version),e.evidenceId,e.merchantId,e.payerAccountHash,e.invoicePayerAccountHash,e.serviceReference,e.periodStart,e.periodEnd,String(e.startEquityYnxt),String(e.endEquityYnxt),String(e.netExternalFlowsYnxt),String(e.previousHighWaterMarkYnxt),String(e.performanceFeeBps),String(e.computeFeeYnxt),String(e.dataFeeYnxt),String(e.subscriptionFeeYnxt),String(e.managementFeeYnxt),e.asset,e.network,e.source,String(e.sourceVersion),e.asOf,e.expiresAt,e.evidenceKeyId,e.evidencePublicKey,e.signatureAlgorithm].join("|")}
function parseVerifierConfig(raw:string):Readonly<Record<string,string>>{if(!raw)return Object.freeze({});try{const value=JSON.parse(raw) as unknown;if(!isObject(value))return Object.freeze({});const out:Record<string,string>={};for(const [keyID,publicKey] of Object.entries(value)){if(/^[a-zA-Z0-9][a-zA-Z0-9._:-]{2,127}$/.test(keyID)&&typeof publicKey==="string"&&/^[a-fA-F0-9]{64}$/.test(publicKey))out[keyID]=publicKey.toLowerCase();else return Object.freeze({})}return Object.freeze(out)}catch{return Object.freeze({})}}
function safeBigIntToNumber(value:bigint,name:string){const number=Number(value);if(!Number.isSafeInteger(number))throw new Error(`Invalid ${name}`);return number}
function safeSum(...values:number[]){return safeBigIntToNumber(values.reduce((sum,value)=>sum+BigInt(value),0n),"fee total")}
function safeIdentifier(value:unknown,name:string){const text=required(value,name);if(!/^[a-zA-Z0-9][a-zA-Z0-9._:-]{2,127}$/.test(text))throw new Error(`Invalid ${name}`);return text}
function parseSession(value:unknown):WalletSession { if(!isObject(value)||!Array.isArray(value.scopes)) throw new PayAPIError("invalid","Invalid Wallet session");const session=Object.freeze({sessionId:required(value.sessionId,"session"),token:required(value.token,"token"),account:nativeAddress(value.account),sessionBinding:hex(value.sessionBinding,64),scopes:value.scopes.map(v=>required(v,"scope")),expiresAt:date(value.expiresAt)});if(session.scopes.join("\n")!=="account:read\npay:case:create\npay:route:select\npay:settlement:submit\npay:sponsorship:request")throw new PayAPIError("tamper","Wallet session scopes do not match YNX Pay");return session }
function isObject(v:unknown):v is Record<string,unknown>{return typeof v==="object"&&v!==null&&!Array.isArray(v)} function required(v:unknown,n:string):string{if(typeof v!=="string"||!v.trim())throw new Error(`Missing ${n}`);return v} function integer(v:unknown,n:string):number{if(typeof v!=="number"||!Number.isSafeInteger(v))throw new Error(`Invalid ${n}`);return v} function nonnegative(v:unknown,n:string):number{const x=integer(v,n);if(x<0)throw new Error(`Invalid ${n}`);return x} function positive(v:unknown,n:string):number{const x=integer(v,n);if(x<=0)throw new Error(`Invalid ${n}`);return x} function id(v:unknown,n:string):string{const x=required(v,n);if(!/^inv_[a-f0-9]{20}$/.test(x))throw new Error(`Invalid ${n}`);return x} function splitID(v:unknown):string{const x=required(v,"split payment");if(!/^spl_[a-f0-9]{20}$/.test(x))throw new Error("Invalid split payment");return x} function shareID(v:unknown):string{const x=required(v,"split share");if(!/^shr_[a-f0-9]{16}$/.test(x))throw new Error("Invalid split share");return x} function hex(v:unknown,length:number):string{const x=required(v,"hex").toLowerCase();if(!new RegExp(`^[a-f0-9]{${length}}$`).test(x))throw new Error("Invalid proof hash");return x} function nativeAddress(v:unknown):string{const x=required(v,"YNX account");if(!/^ynx1[023456789acdefghjklmnpqrstuvwxyz]{38,60}$/.test(x))throw new Error("Invalid native YNX account");return x} function date(v:unknown):string{const x=required(v,"timestamp");if(!Number.isFinite(Date.parse(x)))throw new Error("Invalid timestamp");return x}
