import assert from "node:assert/strict";
import test from "node:test";
import { invoiceID, isSplitPaymentReference, parseInvoice, parseSplitPayment, splitPaymentID } from "./api";
test("invoice references accept only canonical IDs and links",()=>{assert.equal(invoiceID("ynxpay://invoice/inv_0123456789abcdef0123"),"inv_0123456789abcdef0123");assert.throws(()=>invoiceID("paid-demo"))});
test("split references accept canonical IDs, HTTPS links, and deep links",()=>{const id="spl_0123456789abcdef0123";assert.equal(splitPaymentID(id),id);assert.equal(splitPaymentID(`ynxpay://split/${id}`),id);assert.equal(splitPaymentID(`https://pay.ynxweb4.com/split-payments/${id}?source=qr`),id);assert.equal(isSplitPaymentReference(id),true);assert.equal(isSplitPaymentReference("spl_bad"),false);assert.throws(()=>splitPaymentID("https://example.com/not-a-split"))});
test("committed state requires authoritative evidence",()=>{const base={version:1,id:"inv_0123456789abcdef0123",centralInvoiceId:"central",intentId:"intent",merchantId:"merchant",merchantName:"Merchant",payoutAddress:"ynx1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqmcn030",amount:5,asset:"YNXT",network:"ynx_6423-1",fee:1,expiresAt:"2026-07-15T10:00:00Z",createdAt:"2026-07-15T09:00:00Z",signature:"a".repeat(128),signatureKeyId:"merchant-v1",signingPublicKey:"b".repeat(64),signatureAlgorithm:"ed25519"};assert.throws(()=>parseInvoice({...base,status:"committed"}),/missing transaction evidence/);assert.throws(()=>parseInvoice({...base,status:"paid"}),/not authoritative/) });
test("version 2 invoice requires a signed reconciling fee ledger",()=>{const base={version:2,id:"inv_0123456789abcdef0123",centralInvoiceId:"central",intentId:"intent",merchantId:"merchant",merchantName:"Merchant",payoutAddress:"ynx1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqmcn030",amount:5,asset:"YNXT",network:"ynx_6423-1",fee:1,status:"pending",expiresAt:"2026-07-15T10:00:00Z",createdAt:"2026-07-15T09:00:00Z",signature:"a".repeat(128),signatureKeyId:"merchant-v2",signingPublicKey:"b".repeat(64),signatureAlgorithm:"ed25519"};const feeBreakdown={networkFee:1,providerCost:0,protocolFee:0,burn:0,treasury:0,merchantNet:5,sponsorCost:0,userRebate:0,source:"ynx-pay-fee-policy",asOf:"2026-07-15T09:00:00Z",version:1};assert.equal(parseInvoice({...base,feeBreakdown}).feeBreakdown?.merchantNet,5);assert.throws(()=>parseInvoice({...base,feeBreakdown:{...feeBreakdown,merchantNet:4}}),/does not reconcile/);assert.throws(()=>parseInvoice({...base,feeBreakdown:{...feeBreakdown,protocolFee:-1}}),/Invalid protocol fee/) });

test("version 3 invoice binds a bounded tip to the total",()=>{const feeBreakdown={networkFee:1,providerCost:0,protocolFee:0,burn:0,treasury:0,merchantNet:6,sponsorCost:0,userRebate:0,source:"ynx-pay-fee-policy",asOf:"2026-07-15T09:00:00Z",version:1};const value={version:3,id:"inv_0123456789abcdef0123",centralInvoiceId:"central",intentId:"intent",merchantId:"merchant",merchantName:"Merchant",payoutAddress:"ynx1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqmcn030",baseAmount:5,tipAmount:1,amount:6,asset:"YNXT",network:"ynx_6423-1",fee:1,feeBreakdown,status:"pending",expiresAt:"2026-07-15T10:00:00Z",createdAt:"2026-07-15T09:00:00Z",signature:"a".repeat(128),signatureKeyId:"merchant-v3",signingPublicKey:"b".repeat(64),signatureAlgorithm:"ed25519"};assert.equal(parseInvoice(value).tipAmount,1);assert.throws(()=>parseInvoice({...value,tipAmount:2}),/tip does not reconcile/);assert.throws(()=>parseInvoice({...value,baseAmount:2,tipAmount:4}),/tip does not reconcile/) });

test("version 4 invoice requires public split bindings without raw payer",()=>{const feeBreakdown={networkFee:1,providerCost:0,protocolFee:0,burn:0,treasury:0,merchantNet:6,sponsorCost:0,userRebate:0,source:"ynx-pay-fee-policy",asOf:"2026-07-15T09:00:00Z",version:1};const value={version:4,id:"inv_0123456789abcdef0123",centralInvoiceId:"central",intentId:"intent",merchantId:"merchant",merchantName:"Merchant",payoutAddress:"ynx1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqmcn030",baseAmount:6,tipAmount:0,splitPaymentId:"spl_0123456789abcdef0123",splitShareId:"shr_0123456789abcdef",expectedPayerHash:"c".repeat(64),amount:6,asset:"YNXT",network:"ynx_6423-1",fee:1,feeBreakdown,status:"pending",expiresAt:"2026-07-15T10:00:00Z",createdAt:"2026-07-15T09:00:00Z",signature:"a".repeat(128),signatureKeyId:"merchant-v4",signingPublicKey:"b".repeat(64),signatureAlgorithm:"ed25519"};assert.equal(parseInvoice(value).expectedPayerHash,"c".repeat(64));assert.throws(()=>parseInvoice({...value,expectedPayerHash:undefined}),/Missing hex/);assert.throws(()=>parseInvoice({...value,splitShareId:"shr_bad"}),/Invalid split share/) });

test("split payment parser reconciles shares and rejects payer leakage",()=>{const value={version:1,id:"spl_0123456789abcdef0123",merchantId:"merchant",merchantName:"Merchant",payoutAddress:"ynx1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqmcn030",description:"Team lunch",totalAmount:10,asset:"YNXT",network:"ynx_6423-1",status:"partially_claimed",shares:[{id:"shr_0123456789abcdef",label:"Alice",amount:6,invoiceId:"inv_0123456789abcdef0123",status:"pending"},{id:"shr_fedcba9876543210",label:"Bob",amount:4,status:"open"}],expiresAt:"2026-07-15T10:00:00Z",createdAt:"2026-07-15T09:00:00Z",updatedAt:"2026-07-15T09:05:00Z",signature:"a".repeat(128),signatureKeyId:"merchant-v1",signingPublicKey:"b".repeat(64),signatureAlgorithm:"ed25519"};assert.equal(parseSplitPayment(value).shares.length,2);assert.throws(()=>parseSplitPayment({...value,totalAmount:11}),/total is invalid/);assert.throws(()=>parseSplitPayment({...value,shares:[{...value.shares[0],payerAccount:"ynx1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqmcn030"},value.shares[1]]}),/exposed a payer account/) });
