import {secp256k1} from '@noble/curves/secp256k1.js';
import {sha256} from '@noble/hashes/sha2.js';
import {keccak_256} from '@noble/hashes/sha3.js';
import {bytesToHex,hexToBytes,utf8ToBytes} from '@noble/hashes/utils.js';

export const PRODUCT_CLIENT_ID='ynx-pay-v1',BUNDLE_ID='com.ynxweb4.pay',PAYMENT_CALLBACK='ynxpay://payment-result';
const CHAIN_ID='ynx_6423-1',PAYMENT_INTENT_DOMAIN='YNX_PAY_SIGNED_INTENT_V1',PAYMENT_RESULT_DOMAIN='YNX_PAY_WALLET_RESULT_V1',MAX_LIFETIME_MS=5*60_000;
export type SignedPaymentIntent=Readonly<{version:'1';intentType:'pay.ynxt.transfer';requestId:string;chainId:'ynx_6423-1';productClientId:'ynx-pay-v1';bundleId:'com.ynxweb4.pay';sessionBinding:string;invoiceId:string;centralInvoiceId:string;merchantId:string;merchantName:string;payoutAddress:string;amount:number;asset:'YNXT';fee:1;total:number;quoteIssuedAt:string;quoteExpiresAt:string;invoiceSignature:string;callback:'ynxpay://payment-result'}>;
export type WalletPaymentResult=Readonly<{version:'1';intentDigest:string;requestId:string;invoiceId:string;chainId:'ynx_6423-1';account:string;accountPublicKey:string;transactionHash:string;issuedAt:string;walletSignature:string}>;
export class WalletProtocolError extends Error{constructor(readonly code:string,message:string){super(message);this.name='WalletProtocolError'}}

/** Payment intents remain preview-only until an accepted Pay API and private session route exist. */
export function paymentIntent(input:Omit<SignedPaymentIntent,'version'|'intentType'|'chainId'|'productClientId'|'bundleId'|'callback'>):SignedPaymentIntent{const intent=Object.freeze({version:'1',intentType:'pay.ynxt.transfer',chainId:CHAIN_ID,productClientId:PRODUCT_CLIENT_ID,bundleId:BUNDLE_ID,callback:PAYMENT_CALLBACK,...input}) as SignedPaymentIntent;if(intent.total!==intent.amount+intent.fee||intent.asset!=='YNXT'||intent.fee!==1||!walletNonce(intent.requestId)||!strictFutureQuote(intent.quoteIssuedAt,intent.quoteExpiresAt))throw new WalletProtocolError('INVALID_PAYMENT_INTENT','Payment intent quote is invalid');return intent}
export function paymentIntentDigest(intent:SignedPaymentIntent){return digest(PAYMENT_INTENT_DOMAIN,intent)}
export function paymentIntentDeepLink(intent:SignedPaymentIntent){return `ynxwallet://intent?request=${encodeBase64url(utf8ToBytes(canonicalJSON(intent)))}`}
export function parsePaymentResultCallback(url:string,intent:SignedPaymentIntent,account:string,now=new Date()):WalletPaymentResult{const parsed=new URL(url),expected=new URL(PAYMENT_CALLBACK),encoded=parsed.searchParams.get('response');parsed.search='';if(!encoded||parsed.toString()!==expected.toString())throw new WalletProtocolError('CALLBACK_MISMATCH','Wallet payment callback route was substituted');let value:unknown;try{value=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(decodeBase64url(encoded,'payment callback')))}catch{throw new WalletProtocolError('INVALID_CALLBACK','Wallet payment callback payload is invalid')}exactFields(value,['version','intentDigest','requestId','invoiceId','chainId','account','accountPublicKey','transactionHash','issuedAt','walletSignature']);const result=value as WalletPaymentResult;if(result.version!=='1'||result.intentDigest!==paymentIntentDigest(intent)||result.requestId!==intent.requestId||result.invoiceId!==intent.invoiceId||result.chainId!==CHAIN_ID||result.account!==account||!/^(02|03)[0-9a-f]{64}$/.test(result.accountPublicKey)||!/^0x[0-9a-f]{64}$/.test(result.transactionHash)||!/^[0-9a-f]{128}$/.test(result.walletSignature)||walletIdentity(result.accountPublicKey)!==result.account)throw new WalletProtocolError('PAYMENT_BINDING_MISMATCH','Wallet payment result does not match the reviewed intent');const issued=strictTime(result.issuedAt);if(issued<Date.parse(intent.quoteIssuedAt)||issued>Date.parse(intent.quoteExpiresAt)||issued>now.getTime()+30_000)throw new WalletProtocolError('EXPIRED','Wallet payment result is outside the quote lifetime');const {walletSignature,...unsigned}=result;if(!secp256k1.verify(hexToBytes(walletSignature),sha256(utf8ToBytes(`${PAYMENT_RESULT_DOMAIN}\n${canonicalJSON(unsigned)}`)),hexToBytes(result.accountPublicKey),{prehash:false,format:'compact',lowS:true}))throw new WalletProtocolError('INVALID_SIGNATURE','Wallet payment-result signature is invalid');return Object.freeze(result)}
export function canonicalJSON(value:unknown):string{return canonical(value)}
function digest(domain:string,value:unknown){return bytesToHex(sha256(utf8ToBytes(`${domain}\n${canonicalJSON(value)}`)))}
function strictTime(value:string){if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(value)||new Date(value).toISOString()!==value)throw new WalletProtocolError('INVALID_TIME','Protocol timestamp is invalid');return Date.parse(value)}
function strictFutureQuote(issued:string,expires:string){try{const a=strictTime(issued),b=strictTime(expires);return b>a&&b-a<=MAX_LIFETIME_MS}catch{return false}}
function walletNonce(value:string){return /^[A-Za-z0-9_-]{32,64}$/.test(value)}
function exactFields(value:unknown,fields:string[]):asserts value is Record<string,unknown>{if(typeof value!=='object'||value===null||Array.isArray(value)||Object.keys(value).sort().join('\n')!==[...fields].sort().join('\n'))throw new WalletProtocolError('UNKNOWN_OR_MISSING_FIELD','Payment result fields do not match the protocol schema')}
function encodeBase64url(bytes:Uint8Array){let text='';for(const value of bytes)text+=String.fromCharCode(value);return btoa(text).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_')}
function decodeBase64url(value:string,label:string){if(!/^[A-Za-z0-9_-]+$/.test(value))throw new WalletProtocolError('INVALID_ENCODING',`${label} is invalid`);const text=atob(value.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-value.length%4)%4)),bytes=Uint8Array.from(text,char=>char.charCodeAt(0));if(encodeBase64url(bytes)!==value)throw new WalletProtocolError('INVALID_ENCODING',`${label} is not canonical`);return bytes}
function canonical(value:unknown):string{if(value===null||typeof value==='boolean'||typeof value==='number'||typeof value==='string')return JSON.stringify(value);if(Array.isArray(value))return `[${value.map(canonical).join(',')}]`;if(typeof value==='object'){const record=value as Record<string,unknown>;return `{${Object.keys(record).sort().map(key=>`${JSON.stringify(key)}:${canonical(record[key])}`).join(',')}}`}throw new WalletProtocolError('NON_CANONICAL_JSON','Unsupported canonical JSON value')}
function walletIdentity(publicKeyHex:string){const point=secp256k1.Point.fromBytes(hexToBytes(publicKeyHex));const payload=keccak_256(point.toBytes(false).slice(1)).slice(-20),data=convertBits(payload),values=[...hrpExpand('ynx'),...data,0,0,0,0,0,0],checksum=polymod(values)^1,tail=Array.from({length:6},(_,i)=>(checksum>>>(5*(5-i)))&31);return `ynx1${[...data,...tail].map(v=>BECH32[v]).join('')}`}
const BECH32='qpzry9x8gf2tvdw0s3jn54khce6mua7l';function convertBits(data:Uint8Array){let acc=0,bits=0;const out:number[]=[];for(const value of data){acc=((acc<<8)|value)&4095;bits+=8;while(bits>=5){bits-=5;out.push((acc>>bits)&31)}}if(bits>0)out.push((acc<<(5-bits))&31);return out}function hrpExpand(hrp:string){return [...hrp].map(c=>c.charCodeAt(0)>>5).concat([0],[...hrp].map(c=>c.charCodeAt(0)&31))}function polymod(values:number[]){const generators=[0x3b6a57b2,0x26508e6d,0x1ea119fa,0x3d4233dd,0x2a1462b3];let checksum=1;for(const value of values){const top=checksum>>>25;checksum=(((checksum&0x1ffffff)<<5)^value)>>>0;generators.forEach((g,i)=>{if((top>>>i)&1)checksum=(checksum^g)>>>0})}return checksum>>>0}
