export const API=localStorage.getItem("ynx.video.api")||"http://127.0.0.1:8423";let current=null;const $=s=>document.querySelector(s);const token=()=>sessionStorage.getItem("ynx.video.session")||new URLSearchParams(location.hash.slice(1)).get("session");
export async function api(path,options={}){const headers={...(options.headers||{})};if(token())headers.Authorization=`Bearer ${token()}`;const r=await fetch(API+path,{...options,headers});const data=await r.json().catch(()=>({error:"Invalid service response"}));if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data}
function notice(text,bad=false){$("#notice").textContent=text;$("#notice").style.color=bad?"#8b1e2d":"#344054"}function empty(text){$("#content").innerHTML=`<div class="empty"><h2>${text}</h2><p>The service returned no records. YNX Video does not generate placeholder activity.</p></div>`}
async function load(query=""){try{const videos=await api(`/v1/videos?q=${encodeURIComponent(query)}`);$("#content").setAttribute("aria-busy","false");if(!videos.length){empty(query?"No matching published videos":"No published videos yet");return}$("#content").replaceChildren(...videos.map(card));notice(`${videos.length} service record${videos.length===1?"":"s"}`)}catch(e){empty("Video service unavailable");notice(e.message,true)}}
function card(v){const a=document.createElement("article");a.className="card";const state=v.takedown?.state?`Takedown: ${v.takedown.state}`:v.status;a.innerHTML=`<button class="thumb" aria-label="Play ${esc(v.title)}">▶</button><h2>${esc(v.title)}</h2><p class="meta">${esc(state)} · ${esc(v.visibility)}</p><p>${esc(v.description||"No description")}</p>`;a.querySelector("button").onclick=()=>open(v);return a}
function open(v){current=v;$("#player-title").textContent=v.title;$("#player-state").textContent=v.takedown?`Unavailable: ${v.takedown.reason}`:`${v.captions?.length||0} caption track(s)`;const variant=v.variants?.find(x=>x.mime==="application/vnd.apple.mpegurl");$("#video").src=variant?`${API}/media/${variant.object_key}`:"";$("#player").showModal()}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
$("#signin").onclick=()=>{const callback=encodeURIComponent(location.origin+location.pathname);location.href=`ynxwallet://authorize?client=ynx.video.web&chain_id=6423&scopes=video.read%20video.interact&callback=${callback}`};if(token()){sessionStorage.setItem("ynx.video.session",token());history.replaceState(null,"",location.pathname);$("#session").textContent="Wallet-authorized product session active. No account secret is stored here."}
$("#search").onsubmit=e=>{e.preventDefault();load($("#query").value)};$("#close").onclick=()=>{$("#video").pause();$("#player").close()};$("#subscribe").onclick=async()=>{try{await api(`/v1/channels/${current.channel_id}/subscription`,{method:"POST"});notice("Subscription updated from the service.")}catch(e){notice(e.message,true)}};$("#report").onclick=async()=>{const reason=prompt("Reason for review (required)");if(!reason)return;try{await api(`/v1/videos/${current.id}/reports`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({reason,details:"Submitted from YNX Video viewer"})});notice("Report submitted for human review. No automatic takedown occurred.")}catch(e){notice(e.message,true)}};$("#comment").onsubmit=async e=>{e.preventDefault();try{await api(`/v1/videos/${current.id}/comments`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({body:e.target.elements[0].value})});e.target.reset();notice("Comment persisted.")}catch(x){notice(x.message,true)}};$("#playlist").onclick=()=>notice("Create or select a playlist from the Playlists view.");document.querySelectorAll("nav button").forEach(b=>b.onclick=async()=>{document.querySelectorAll("nav button").forEach(x=>x.classList.toggle("active",x===b));if(b.dataset.view==="history"){try{const h=await api("/v1/history");h.length?notice(`${h.length} persisted history event(s)`):empty("History is empty")}catch(e){notice(e.message,true)}}else load()});load();
