import { createCipheriv, createDecipheriv, createHash, randomBytes } from "node:crypto";
import { lookup } from "node:dns/promises";
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, extname, join } from "node:path";
import { DatabaseSync } from "node:sqlite";
import { spawn } from "node:child_process";

const MAX_BODY=3*1024*1024,PROTOCOL="ynx-code-runtime/v1",IMAGES={"ubuntu-24.04":"ubuntu:24.04"};
export function createRuntimeProfileService({filename,ownerForRequest,encryptionKey=process.env.YNX_CODE_PROFILE_KEY,containerImage=process.env.YNX_CODE_LXD_IMAGE||IMAGES["ubuntu-24.04"],maxOwnerLeases=4,maxGlobalLeases=64,lxd=createLxdAdapter(),ssh=createSshAdapter()}){
  const key=deriveKey(encryptionKey),activeTasks=new Set(),db=new DatabaseSync(filename);db.exec("PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL; PRAGMA busy_timeout=5000; CREATE TABLE IF NOT EXISTS runtime_leases(owner_id TEXT NOT NULL,runtime_id TEXT NOT NULL,project_id TEXT NOT NULL,container_name TEXT NOT NULL,image TEXT NOT NULL,status TEXT NOT NULL,created_at TEXT NOT NULL,PRIMARY KEY(owner_id,runtime_id)); CREATE TABLE IF NOT EXISTS ssh_profiles(owner_id TEXT NOT NULL,profile_id TEXT NOT NULL,label TEXT NOT NULL,host TEXT NOT NULL,port INTEGER NOT NULL,user_name TEXT NOT NULL,host_key TEXT NOT NULL,fingerprint TEXT NOT NULL,secret TEXT NOT NULL,created_at TEXT NOT NULL,PRIMARY KEY(owner_id,profile_id));");
  const listLeases=db.prepare("SELECT runtime_id,project_id,container_name,image,status,created_at FROM runtime_leases WHERE owner_id=? ORDER BY created_at DESC"),insertLease=db.prepare("INSERT INTO runtime_leases(owner_id,runtime_id,project_id,container_name,image,status,created_at) VALUES(?,?,?,?,?,?,?)"),markLease=db.prepare("UPDATE runtime_leases SET status=? WHERE owner_id=? AND runtime_id=?"),ownerLeaseCount=db.prepare("SELECT COUNT(*) count FROM runtime_leases WHERE owner_id=?"),globalLeaseCount=db.prepare("SELECT COUNT(*) count FROM runtime_leases"),lease=db.prepare("SELECT runtime_id,project_id,container_name,status FROM runtime_leases WHERE owner_id=? AND runtime_id=?"),deleteLease=db.prepare("DELETE FROM runtime_leases WHERE owner_id=? AND runtime_id=?"),listSsh=db.prepare("SELECT profile_id,label,host,port,user_name,fingerprint,created_at FROM ssh_profiles WHERE owner_id=? ORDER BY created_at DESC"),putSsh=db.prepare("INSERT INTO ssh_profiles(owner_id,profile_id,label,host,port,user_name,host_key,fingerprint,secret,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)"),deleteSsh=db.prepare("DELETE FROM ssh_profiles WHERE owner_id=? AND profile_id=?");
  async function handler(request,response){const url=new URL(request.url,`http://${request.headers.host||"127.0.0.1"}`);if(!url.pathname.startsWith("/runtime/profiles"))return false;const owner=ownerForRequest(request);if(!owner){json(response,401,{error:"A signed workspace session is required.",code:"workspace_session_required"});return true}try{
    if(url.pathname==="/runtime/profiles"&&request.method==="GET"){const inventory=await lxd.inventory();json(response,200,{protocolVersion:PROTOCOL,container:{engine:"lxd",...inventory},leases:listLeases.all(owner).map(runtimeRecord),sshProfiles:listSsh.all(owner).map(sshRecord)});return true}
    if(url.pathname==="/runtime/profiles/lxd/leases"&&request.method==="POST"){const body=await bodyJson(request);if(body.protocolVersion!==PROTOCOL||body.approval!=="create-container-once"||!safeId(body.projectId)||!Object.hasOwn(IMAGES,body.image))throw fault("A reviewed container request is required.","invalid_container_request",400);const inventory=await lxd.inventory();if(!inventory.ready)throw fault("LXD is installed but its isolated workspace profile is not ready.","container_runtime_unavailable",503);db.exec("BEGIN IMMEDIATE");let runtimeId,containerName,createdAt;try{if(Number(ownerLeaseCount.get(owner).count)>=maxOwnerLeases||Number(globalLeaseCount.get().count)>=maxGlobalLeases)throw fault("Container workspace capacity is currently full.","container_capacity_exhausted",429);runtimeId=randomBytes(12).toString("hex");containerName=`ynx-${createHash("sha256").update(owner).digest("hex").slice(0,10)}-${runtimeId}`;createdAt=new Date().toISOString();insertLease.run(owner,runtimeId,body.projectId,containerName,body.image,"creating",createdAt);db.exec("COMMIT")}catch(error){try{db.exec("ROLLBACK")}catch{}throw error}let value;try{value=await lxd.create({containerName,image:containerImage,projectId:body.projectId});markLease.run("running",owner,runtimeId)}catch(error){try{await lxd.remove(containerName)}catch{}deleteLease.run(owner,runtimeId);throw error}json(response,201,{protocolVersion:PROTOCOL,runtime:{runtimeId,projectId:body.projectId,image:body.image,status:"running",createdAt,evidence:value}});return true}
    const taskMatch=url.pathname.match(/^\/runtime\/profiles\/lxd\/leases\/([a-f0-9]{24})\/tasks$/);if(taskMatch&&request.method==="POST"){const row=lease.get(owner,taskMatch[1]);if(!row)throw fault("Runtime lease not found.","runtime_not_found",404);if(activeTasks.has(row.container_name)||activeTasks.size>=16)throw fault("The selected cloud runtime is busy.","container_task_busy",429);const body=await bodyJson(request);validateContainerTask(body);if(row.status!=="running"||row.project_id!==body.projectId)throw fault("The runtime is not assigned to this project.","runtime_project_mismatch",409);activeTasks.add(row.container_name);try{const result=await lxd.runTask({containerName:row.container_name,task:body});json(response,200,{protocolVersion:PROTOCOL,...result})}finally{activeTasks.delete(row.container_name)}return true}
    if(url.pathname.startsWith("/runtime/profiles/lxd/leases/")&&request.method==="DELETE"){const runtimeId=url.pathname.split("/").at(-1),row=lease.get(owner,runtimeId);if(!row)throw fault("Runtime lease not found.","runtime_not_found",404);if(activeTasks.has(row.container_name))throw fault("Stop the active task before deleting its runtime.","container_task_busy",409);await lxd.remove(row.container_name);deleteLease.run(owner,runtimeId);json(response,200,{protocolVersion:PROTOCOL,removed:runtimeId});return true}
    if(url.pathname==="/runtime/profiles/ssh/inspect"&&request.method==="POST"){const body=await bodyJson(request),target=validateSshTarget(body);const evidence=await ssh.inspect(target);json(response,200,{protocolVersion:PROTOCOL,...target,...evidence});return true}
    if(url.pathname==="/runtime/profiles/ssh"&&request.method==="POST"){if(!key)throw fault("Remote SSH secret encryption is not configured.","ssh_encryption_unavailable",503);const body=await bodyJson(request),target=validateSshTarget(body);if(body.protocolVersion!==PROTOCOL||body.approval!=="connect-ssh-once"||typeof body.privateKey!=="string"||body.privateKey.length<64||body.privateKey.length>128*1024||typeof body.reviewedHostKey!=="string")throw fault("A reviewed SSH connection request is required.","invalid_ssh_request",400);const inspected=await ssh.inspect(target);if(body.reviewedHostKey!==inspected.hostKey)throw fault("The SSH host key changed after review.","ssh_host_key_changed",409);await ssh.verify({...target,hostKey:inspected.hostKey,privateKey:body.privateKey});const profileId=randomBytes(12).toString("hex"),createdAt=new Date().toISOString(),label=String(body.label||`${target.user}@${target.host}`).slice(0,80);putSsh.run(owner,profileId,label,target.host,target.port,target.user,inspected.hostKey,inspected.fingerprint,encrypt(key,body.privateKey),createdAt);json(response,201,{protocolVersion:PROTOCOL,profile:{profileId,label,...target,fingerprint:inspected.fingerprint,createdAt}});return true}
    if(url.pathname.startsWith("/runtime/profiles/ssh/")&&request.method==="DELETE"){const profileId=url.pathname.split("/").at(-1);if(!safeId(profileId))throw fault("Invalid SSH profile ID.","invalid_ssh_profile",400);deleteSsh.run(owner,profileId);json(response,200,{protocolVersion:PROTOCOL,removed:profileId});return true}
    throw fault("Method not allowed.","method_not_allowed",405)
  }catch(error){json(response,error.status||400,{error:error.message||"Runtime profile operation failed.",code:error.code||"runtime_profile_failed"});return true}}
  return{handler,status:async()=>({lxd:await lxd.inventory(),sshEncryption:Boolean(key)}),close:()=>db.close()};
}
export function createLxdAdapter({run=runFile}={}){return{
  async inventory(){try{const[{stdout:storage},{stdout:profiles}]=await Promise.all([run("lxc",["storage","list","--format","json"]),run("lxc",["profile","list","--format","json"])]),stores=JSON.parse(storage),items=JSON.parse(profiles);return{installed:true,ready:stores.length>0&&items.some(item=>item.name==="ynx-code-isolated"),storagePools:stores.length,profile:items.some(item=>item.name==="ynx-code-isolated")}}catch{return{installed:false,ready:false,storagePools:0,profile:false}}},
  async create({containerName,image,projectId}){try{await run("lxc",["launch",image,containerName,"--profile","ynx-code-isolated","--config","limits.cpu=2","--config","limits.memory=2GiB","--device","root,size=10GiB"],{timeout:120000});await run("lxc",["exec",containerName,"--","mkdir","-p",`/workspaces/${projectId}`],{timeout:20000});const{stdout}=await run("lxc",["config","get",containerName,"volatile.base_image"]);return{engine:"lxd",containerName,imageFingerprint:stdout.trim()||null,cpu:"2",memory:"2GiB",disk:"10GiB",network:"disabled"}}catch(error){try{await run("lxc",["delete",containerName,"--force"],{timeout:30000})}catch{}throw error}},
  async runTask(value){return runContainerTask(run,value)},
  async remove(containerName){await run("lxc",["delete",containerName,"--force"],{timeout:30000})}
}}
async function runContainerTask(run,{containerName,task}){
  const local=await mkdtemp(join(tmpdir(),"ynx-code-container-task-")),remote=`/workspaces/${task.projectId}`,started=performance.now(),taskId=randomBytes(16).toString("hex");
  try{
    await run("lxc",["exec",containerName,"--","rm","-rf",remote],{timeout:20000});
    await run("lxc",["exec",containerName,"--","mkdir","-p",`${remote}/.ynx-build`],{timeout:20000});
    for(const[path,content]of Object.entries(task.files)){const source=join(local,path);await writeFileTree(source,content);await run("lxc",["file","push","--create-dirs",source,`${containerName}${remote}/${path}`],{timeout:20000})}
    const spec=containerTaskSpec(task.activePath);if(!spec)throw fault("This cloud image has no reviewed adapter for the active file.","container_toolchain_unavailable",503);
    let output="",code=0;
    for(const phase of spec.phases){try{const value=await run("lxc",["exec",containerName,"--cwd",remote,"--",phase.command,...phase.args],{timeout:phase.timeout||60000,maxBuffer:1024*1024});output+=`${phase.label}> ${value.stdout}${value.stderr}`}catch(error){code=Number.isInteger(error.code)?error.code:1;output+=`${phase.label}> ${error.stdout||""}${error.stderr||error.message}`;break}}
    let version="unavailable";try{version=(await run("lxc",["exec",containerName,"--",spec.compiler,...(spec.versionArgs||["--version"])],{timeout:5000,maxBuffer:64*1024})).stdout.split("\n")[0].slice(0,160)}catch{}
    return{taskId,ok:code===0,code,language:spec.language,output:output||"Process completed without output.\n",durationMs:Math.round(performance.now()-started),compiler:{executable:spec.compiler,version},sandbox:{kind:"lxd-container",network:false,writableRoot:"workspace"},truncated:false};
  }finally{await rm(local,{recursive:true,force:true})}
}
async function writeFileTree(path,content){await mkdir(dirname(path),{recursive:true,mode:0o700});await writeFile(path,content,{mode:0o600,flag:"wx"})}
function containerTaskSpec(path){const extension=extname(path).toLowerCase(),program=".ynx-build/program";
  if([".cpp",".cc",".cxx"].includes(extension))return{language:"cpp",compiler:"clang++",phases:[{label:"build",command:"clang++",args:["-std=c++20","-Wall","-Wextra","-pedantic",path,"-o",program]},{label:"run",command:`./${program}`,args:[]}]};
  if([".js",".mjs",".cjs"].includes(extension))return{language:"javascript",compiler:"node",phases:[{label:"run",command:"node",args:[path]}]};
  if(extension===".ts")return{language:"typescript",compiler:"tsc",phases:[{label:"build",command:"tsc",args:["--target","ES2022","--module","commonjs","--rootDir",".","--outDir",".ynx-build",path]},{label:"run",command:"node",args:[`.ynx-build/${path.slice(0,-3)}.js`]}]};
  if(extension===".py")return{language:"python",compiler:"python3",phases:[{label:"run",command:"python3",args:["-I",path]}]};
  if(extension===".go")return{language:"go",compiler:"go",versionArgs:["version"],phases:[{label:"run",command:"go",args:["run",path],timeout:90000}]};
  if(extension===".rs")return{language:"rust",compiler:"rustc",phases:[{label:"build",command:"rustc",args:[path,"-o",program]},{label:"run",command:`./${program}`,args:[]}]};
  if(extension===".sol")return{language:"solidity",compiler:"solcjs",phases:[{label:"compile",command:"solcjs",args:["--bin","--abi","-o",".ynx-build",path]}]};
  return null
}
export function createSshAdapter({run=runFile,resolve=lookup}={}){return{async inspect(target){await assertPublicHost(target.host,resolve);const{stdout}=await run("ssh-keyscan",["-T","5","-p",String(target.port),target.host],{timeout:8000,maxBuffer:128*1024});const line=stdout.split("\n").find(value=>value&&!value.startsWith("#"));if(!line)throw fault("SSH host did not provide a host key.","ssh_host_key_unavailable",422);const keyPart=line.trim().split(/\s+/).slice(-2).join(" "),hostToken=target.port===22?target.host:`[${target.host}]:${target.port}`,hostKey=`${hostToken} ${keyPart}`,encoded=keyPart.split(" ")[1],fingerprint=`SHA256:${createHash("sha256").update(Buffer.from(encoded,"base64")).digest("base64").replace(/=+$/,"")}`;return{hostKey,fingerprint}},async verify({host,port,user,hostKey,privateKey}){const root=await mkdtemp(join(tmpdir(),"ynx-code-ssh-")),identity=join(root,"identity"),known=join(root,"known_hosts");try{await writeFile(identity,privateKey,{mode:0o600});await writeFile(known,`${hostKey}\n`,{mode:0o600});await run("ssh",["-o","BatchMode=yes","-o","IdentitiesOnly=yes","-o","StrictHostKeyChecking=yes","-o",`UserKnownHostsFile=${known}`,"-o","ConnectTimeout=8","-i",identity,"-p",String(port),`${user}@${host}`,"--","true"],{timeout:12000,maxBuffer:128*1024})}catch{throw fault("SSH authentication or host verification failed.","ssh_connection_failed",422)}finally{await rm(root,{recursive:true,force:true})}}}}
async function runFile(command,args,options={}){const maxBuffer=options.maxBuffer||1024*1024,timeoutMs=options.timeout||10000;return new Promise((resolve,reject)=>{const child=spawn(command,args,{stdio:["ignore","pipe","pipe"]}),stdout=[],stderr=[];let size=0,settled=false;const finish=(error,value)=>{if(settled)return;settled=true;clearTimeout(timer);error?reject(error):resolve(value)};for(const[channel,target]of [[child.stdout,stdout],[child.stderr,stderr]])channel.on("data",chunk=>{size+=chunk.length;if(size>maxBuffer){child.kill("SIGKILL");finish(Object.assign(new Error(`${command} output exceeded its boundary.`),{code:"max_buffer"}));return}target.push(chunk)});child.once("error",finish);child.once("close",(code,signal)=>{const value={stdout:Buffer.concat(stdout).toString("utf8"),stderr:Buffer.concat(stderr).toString("utf8")};if(code===0)finish(null,value);else finish(Object.assign(new Error(`${command} exited with code ${code}.`),{code,signal,...value}))});const timer=setTimeout(()=>{child.kill("SIGKILL");finish(Object.assign(new Error(`${command} exceeded ${timeoutMs} ms.`),{code:"timeout"}))},timeoutMs)})}
function validateSshTarget(value){if(value.protocolVersion!==PROTOCOL||typeof value.host!=="string"||!/^([A-Za-z0-9](?:[A-Za-z0-9.-]{0,251}[A-Za-z0-9])?|\d{1,3}(?:\.\d{1,3}){3})$/.test(value.host)||!Number.isInteger(value.port)||value.port<1||value.port>65535||typeof value.user!=="string"||!/^[A-Za-z_][A-Za-z0-9_-]{0,31}$/.test(value.user))throw fault("Invalid SSH target.","invalid_ssh_target",400);return{host:value.host,port:value.port,user:value.user}}
async function assertPublicHost(host,resolve){const records=await resolve(host,{all:true,verbatim:true});if(!records.length||records.some(({address})=>privateAddress(address)))throw fault("Private, loopback and link-local SSH targets are disabled on the public tier.","ssh_target_not_public",403)}
function privateAddress(address){return /^(127\.|10\.|192\.168\.|169\.254\.|0\.|::1$|fc|fd|fe80)/i.test(address)||(/^172\.(\d+)\./.test(address)&&Number(address.split(".")[1])>=16&&Number(address.split(".")[1])<=31)}
function deriveKey(value){return typeof value==="string"&&value.length>=32?createHash("sha256").update(value).digest():null}
function encrypt(key,value){const iv=randomBytes(12),cipher=createCipheriv("aes-256-gcm",key,iv),body=Buffer.concat([cipher.update(value,"utf8"),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),body]).toString("base64")}
export function decryptProfileSecret(keyValue,value){const key=deriveKey(keyValue),data=Buffer.from(value,"base64"),decipher=createDecipheriv("aes-256-gcm",key,data.subarray(0,12));decipher.setAuthTag(data.subarray(12,28));return Buffer.concat([decipher.update(data.subarray(28)),decipher.final()]).toString("utf8")}
function runtimeRecord(row){return{runtimeId:row.runtime_id,projectId:row.project_id,image:row.image,status:row.status,createdAt:row.created_at}}
function sshRecord(row){return{profileId:row.profile_id,label:row.label,host:row.host,port:Number(row.port),user:row.user_name,fingerprint:row.fingerprint,createdAt:row.created_at}}
function safeId(value){return typeof value==="string"&&/^[-A-Za-z0-9_]{1,160}$/.test(value)}
function validateContainerTask(value){if(!value||value.protocolVersion!==PROTOCOL||value.approval!=="execute-container-once"||!safeId(value.projectId)||!safeWorkspacePath(value.activePath)||!value.files||typeof value.files!=="object"||Array.isArray(value.files)||!Object.hasOwn(value.files,value.activePath))throw fault("A reviewed cloud task and valid workspace are required.","invalid_container_task",400);const entries=Object.entries(value.files);let bytes=0;if(entries.length<1||entries.length>256)throw fault("Cloud workspace file count is invalid.","invalid_container_task",400);for(const[path,content]of entries){if(!safeWorkspacePath(path)||typeof content!=="string")throw fault("Cloud workspace contains an invalid text file.","invalid_container_task",400);bytes+=Buffer.byteLength(content);if(bytes>2*1024*1024)throw fault("Cloud workspace exceeds 2 MiB.","container_task_too_large",413)}}
function safeWorkspacePath(value){return typeof value==="string"&&value.length>0&&value.length<=240&&!value.startsWith("/")&&!value.includes("\\")&&!value.split("/").some(part=>!part||part==="."||part==="..")&&/^[A-Za-z0-9_./ +@-]+$/.test(value)}
async function bodyJson(request){const chunks=[];let size=0;for await(const chunk of request){size+=chunk.length;if(size>MAX_BODY)throw fault("Request body is too large.","body_too_large",413);chunks.push(chunk)}try{return JSON.parse(Buffer.concat(chunks).toString("utf8"))}catch{throw fault("Request body must be JSON.","invalid_json",400)}}
function json(response,status,value){response.writeHead(status,{"content-type":"application/json; charset=utf-8","cache-control":"no-store"});response.end(JSON.stringify(value))}
function fault(message,code,status){return Object.assign(new Error(message),{code,status})}
