package com.ynxweb4.video;

import android.net.Uri;
import android.util.Base64;
import org.json.JSONArray;
import org.json.JSONObject;
import java.nio.charset.StandardCharsets;
import java.security.KeyPairGenerator;
import java.security.KeyStore;
import java.security.MessageDigest;
import java.security.SecureRandom;
import java.security.Signature;
import java.security.interfaces.ECPublicKey;
import java.security.spec.ECGenParameterSpec;
import java.time.Instant;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeFormatterBuilder;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Iterator;
import java.util.List;
import java.util.TreeSet;

final class CentralContracts {
    static final String CLIENT="ynx-video-mobile-v1",BUNDLE="com.ynxweb4.video",CALLBACK="ynxvideo://wallet-auth/callback";
    static final List<String> SCOPES=List.of("video.comment","video.history","video.read","video.report","video.subscribe");
    static final class AuthorizationLaunch{final Uri uri;final JSONObject request;AuthorizationLaunch(Uri value,JSONObject body){uri=value;request=body;}}
    static AuthorizationLaunch walletAuthorization(long nowMillis)throws Exception{ArrayList<String> scopes=new ArrayList<>(SCOPES);Collections.sort(scopes);DateTimeFormatter time=new DateTimeFormatterBuilder().appendInstant(3).toFormatter();JSONObject request=new JSONObject().put("version","1").put("nonce",nonce()).put("chainId","ynx_6423-1").put("requestingProduct","ynx-video").put("productClientId",CLIENT).put("bundleId",BUNDLE).put("productDeviceAlgorithm","p256-sha256").put("productDeviceKey",devicePublicKey()).put("callback",CALLBACK).put("scopes",new JSONArray(scopes)).put("purpose","Sign in to YNX Video without sharing Wallet recovery material").put("issuedAt",time.format(Instant.ofEpochMilli(nowMillis))).put("expiresAt",time.format(Instant.ofEpochMilli(nowMillis+300000)));String encoded=Base64.encodeToString(canonical(request).getBytes(StandardCharsets.UTF_8),Base64.URL_SAFE|Base64.NO_WRAP|Base64.NO_PADDING);return new AuthorizationLaunch(Uri.parse("ynxwallet://authorize?request="+encoded),request);}
    static JSONObject walletApproval(String encoded,JSONObject request)throws Exception{JSONObject approval=new JSONObject(new String(Base64.decode(encoded,Base64.URL_SAFE|Base64.NO_WRAP|Base64.NO_PADDING),StandardCharsets.UTF_8));for(String key:List.of("nonce","chainId","requestingProduct","productClientId","bundleId","productDeviceAlgorithm","productDeviceKey","callback","purpose"))if(!request.getString(key).equals(approval.optString(key)))throw new SecurityException("Wallet approval binding mismatch: "+key);if(!canonical(request.getJSONArray("scopes")).equals(canonical(approval.getJSONArray("grantedScopes"))))throw new SecurityException("Wallet scopes changed");if(!Instant.parse(approval.getString("expiresAt")).isAfter(Instant.now()))throw new SecurityException("Wallet approval expired");return approval;}
    static JSONObject gatewayCompletion(JSONObject approval,long nowMillis)throws Exception{Instant now=Instant.ofEpochMilli(nowMillis),approvalExpiry=Instant.parse(approval.getString("expiresAt")),expiry=now.plusSeconds(120).isBefore(approvalExpiry)?now.plusSeconds(120):approvalExpiry;DateTimeFormatter time=new DateTimeFormatterBuilder().appendInstant(3).toFormatter();JSONObject challenge=new JSONObject().put("version","1").put("challenge",nonce()).put("requestDigest",approval.getString("requestDigest")).put("productClientId",CLIENT).put("bundleId",BUNDLE).put("productDeviceAlgorithm","p256-sha256").put("productDeviceKey",devicePublicKey()).put("account",approval.getString("account")).put("scopes",approval.getJSONArray("grantedScopes")).put("issuedAt",time.format(now)).put("expiresAt",time.format(expiry));return new JSONObject().put("challenge",challenge).put("deviceSignature",sign("YNX_PRODUCT_SESSION_CHALLENGE_V1\n"+canonical(challenge)));}
    static String productSessionProof(JSONObject session,String scope,long nowMillis)throws Exception{if(!"ynx-video".equals(session.getString("requestingProduct"))||!CLIENT.equals(session.getString("productClientId"))||!BUNDLE.equals(session.getString("bundleId"))||!devicePublicKey().equals(session.getString("productDeviceKey")))throw new SecurityException("Product Session binding mismatch");JSONArray scopes=session.getJSONArray("scopes");boolean granted=false;for(int index=0;index<scopes.length();index++)if(scope.equals(scopes.getString(index)))granted=true;if(!granted)throw new SecurityException("Product Session scope missing");Instant now=Instant.ofEpochMilli(nowMillis),sessionExpiry=Instant.parse(session.getString("expiresAt")),expiry=now.plusSeconds(30).isBefore(sessionExpiry)?now.plusSeconds(30):sessionExpiry;if(!expiry.isAfter(now))throw new SecurityException("Product Session expired");JSONObject body=new JSONObject().put("requiredScopes",new JSONArray().put(scope));DateTimeFormatter time=new DateTimeFormatterBuilder().appendInstant(3).toFormatter();JSONObject unsigned=new JSONObject().put("version","1").put("sessionBinding",session.getString("sessionBinding")).put("productClientId",CLIENT).put("bundleId",BUNDLE).put("productDeviceKey",devicePublicKey()).put("method","POST").put("path","/v1/wallet/sessions/introspect").put("bodyDigest",hex(MessageDigest.getInstance("SHA-256").digest(canonical(body).getBytes(StandardCharsets.UTF_8)))).put("nonce",nonce()).put("issuedAt",time.format(now)).put("expiresAt",time.format(expiry));JSONObject proof=new JSONObject(unsigned.toString()).put("signature",sign("YNX_PRODUCT_SESSION_HTTP_PROOF_V1\n"+canonical(unsigned)));return Base64.encodeToString(canonical(proof).getBytes(StandardCharsets.UTF_8),Base64.URL_SAFE|Base64.NO_WRAP|Base64.NO_PADDING);}
    private static String sign(String value)throws Exception{Signature signer=Signature.getInstance("SHA256withECDSA");KeyStore store=KeyStore.getInstance("AndroidKeyStore");store.load(null);signer.initSign((java.security.PrivateKey)store.getKey("ynx_video_device_v2",null));signer.update(value.getBytes(StandardCharsets.UTF_8));return Base64.encodeToString(signer.sign(),Base64.URL_SAFE|Base64.NO_WRAP|Base64.NO_PADDING);}
    private static String devicePublicKey()throws Exception{KeyStore store=KeyStore.getInstance("AndroidKeyStore");store.load(null);if(!store.containsAlias("ynx_video_device_v2")){KeyPairGenerator generator=KeyPairGenerator.getInstance("EC","AndroidKeyStore");generator.initialize(new android.security.keystore.KeyGenParameterSpec.Builder("ynx_video_device_v2",android.security.keystore.KeyProperties.PURPOSE_SIGN|android.security.keystore.KeyProperties.PURPOSE_VERIFY).setAlgorithmParameterSpec(new ECGenParameterSpec("secp256r1")).setDigests(android.security.keystore.KeyProperties.DIGEST_SHA256).build());generator.generateKeyPair();}ECPublicKey key=(ECPublicKey)store.getCertificate("ynx_video_device_v2").getPublicKey();byte[] raw=key.getW().getAffineX().toByteArray(),x=new byte[32],out=new byte[33];System.arraycopy(raw,Math.max(0,raw.length-32),x,Math.max(0,32-raw.length),Math.min(32,raw.length));out[0]=(byte)(key.getW().getAffineY().testBit(0)?3:2);System.arraycopy(x,0,out,1,32);return Base64.encodeToString(out,Base64.URL_SAFE|Base64.NO_WRAP|Base64.NO_PADDING);}
    private static String canonical(Object value)throws Exception{if(value==JSONObject.NULL)return"null";if(value instanceof JSONObject){JSONObject object=(JSONObject)value;TreeSet<String> keys=new TreeSet<>();Iterator<String> iterator=object.keys();while(iterator.hasNext())keys.add(iterator.next());StringBuilder out=new StringBuilder("{");for(String key:keys){if(out.length()>1)out.append(',');out.append(JSONObject.quote(key)).append(':').append(canonical(object.get(key)));}return out.append('}').toString();}if(value instanceof JSONArray){JSONArray array=(JSONArray)value;StringBuilder out=new StringBuilder("[");for(int index=0;index<array.length();index++){if(index>0)out.append(',');out.append(canonical(array.get(index)));}return out.append(']').toString();}if(value instanceof String)return JSONObject.quote((String)value);if(value instanceof Boolean||value instanceof Number)return value.toString();throw new IllegalArgumentException("unsupported canonical JSON");}
    private static String nonce(){byte[] bytes=new byte[24];new SecureRandom().nextBytes(bytes);return Base64.encodeToString(bytes,Base64.URL_SAFE|Base64.NO_WRAP|Base64.NO_PADDING);}private static String hex(byte[] bytes){StringBuilder out=new StringBuilder();for(byte value:bytes)out.append(String.format("%02x",value&255));return out.toString();}
}
