package com.ynxweb4.video;
import android.content.Context;
import org.json.JSONObject;
import java.nio.charset.StandardCharsets;
import java.util.UUID;

// Ordinary account-owned viewer data, never credentials or a signing namespace.
// Watch totals are not resume positions. Corrupt records remain held in place.
final class VideoViewerState {
 private final Context context;private final VideoApi api;private final String name;
 VideoViewerState(Context context,VideoApi api)throws Exception{api.requireCurrent();this.context=context;this.api=api;name="ynx_video_viewer_v2_"+VideoApi.digest(api.identity.account.getBytes(StandardCharsets.UTF_8));}
 private JSONObject read()throws Exception{api.requireCurrent();String raw=context.getSharedPreferences(name,0).getString("state",null);if(raw==null)return new JSONObject().put("version",1).put("account",api.identity.account).put("resume",new JSONObject());if(raw.length()>524288)throw new SecurityException("Original viewer state exceeds limit");JSONObject state=new JSONObject(raw);if(state.getInt("version")!=1||!api.identity.account.equals(state.getString("account"))||!(state.get("resume") instanceof JSONObject))throw new SecurityException("Original viewer state unavailable; preserve record");validatePlaylists(state);return state;}
 private void write(JSONObject state)throws Exception{api.requireCurrent();validatePlaylists(state);String raw=state.toString();if(raw.length()>524288)throw new IllegalStateException("Viewer state capacity reached; preserve existing records");if(!context.getSharedPreferences(name,0).edit().putString("state",raw).commit()||!raw.equals(context.getSharedPreferences(name,0).getString("state",null)))throw new IllegalStateException("Original viewer state write unconfirmed");api.requireCurrent();}
 // A failed ACK write must not make SharedPreferences' volatile removal look
 // like durable completion. Retain the latest exact snapshot and still fail.
 private void acknowledge(JSONObject next,JSONObject previous)throws Exception{try{write(next);}catch(Exception failure){try{api.requireCurrent();String original=previous.toString();context.getSharedPreferences(name,0).edit().putString("state",original).commit();if(!original.equals(context.getSharedPreferences(name,0).getString("state",null)))throw new IllegalStateException("Original recovery snapshot retention unconfirmed");api.requireCurrent();}catch(Exception retention){failure.addSuppressed(retention);}throw failure;}}
 synchronized JSONObject playback(String id)throws Exception{synchronized(VideoViewerState.class){if(!id.matches("[A-Za-z0-9_-]+"))throw new SecurityException("Original video ID required");JSONObject state=read(),row=state.getJSONObject("resume").optJSONObject(id);if(row!=null){if(!row.getString("playbackId").matches("[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}")||row.getInt("position")<0)throw new SecurityException("Original resume state unavailable");return new JSONObject(row.toString());}row=new JSONObject().put("playbackId",UUID.randomUUID().toString()).put("position",0);state.getJSONObject("resume").put(id,row);write(state);return row;}}
 synchronized JSONObject position(String id,String playbackId,int position,int seconds,boolean completed)throws Exception{synchronized(VideoViewerState.class){JSONObject state=read(),row=state.getJSONObject("resume").getJSONObject(id);if(!playbackId.equals(row.getString("playbackId")))throw new SecurityException("Original playback retired");if(completed)state.getJSONObject("resume").remove(id);else row.put("position",Math.max(0,position));
        if(seconds<0||seconds>86400)throw new SecurityException("Observed watch increment required");JSONObject pending=null;
        if(seconds>0||completed){org.json.JSONArray batches=state.optJSONArray("watchPending");if(batches==null){batches=new org.json.JSONArray();state.put("watchPending",batches);}pending=new JSONObject().put("key",UUID.randomUUID().toString()).put("videoId",id).put("playbackId",playbackId).put("seconds",seconds).put("completed",completed);batches.put(pending);}
        write(state);return pending;}}
 synchronized org.json.JSONArray watchPending()throws Exception{synchronized(VideoViewerState.class){JSONObject state=read();org.json.JSONArray items=state.optJSONArray("watchPending");if(items!=null&&items.length()>0)write(state);return items==null?new org.json.JSONArray():new org.json.JSONArray(items.toString());}}
 // Reconfirm the exact retained batch against latest account state before wire.
 synchronized void confirmWatch(JSONObject original)throws Exception{synchronized(VideoViewerState.class){JSONObject state=read();org.json.JSONArray rows=state.getJSONArray("watchPending");boolean found=false;for(int i=0;i<rows.length();i++){JSONObject row=rows.getJSONObject(i);if(row.getString("key").equals(original.getString("key"))){if(!NativeProductState.canonical(row).equals(NativeProductState.canonical(original)))throw new SecurityException("Original watch body changed");found=true;}}if(!found)throw new SecurityException("Original watch request retired");write(state);}}
 synchronized void finishWatch(JSONObject original)throws Exception{synchronized(VideoViewerState.class){JSONObject state=read(),previous=new JSONObject(state.toString());org.json.JSONArray items=state.getJSONArray("watchPending"),remaining=new org.json.JSONArray();boolean found=false;for(int i=0;i<items.length();i++){JSONObject item=items.getJSONObject(i);if(original.getString("key").equals(item.getString("key"))){if(!NativeProductState.canonical(original).equals(NativeProductState.canonical(item)))throw new SecurityException("Original watch result changed");found=true;}else remaining.put(item);}if(!found)throw new SecurityException("Original watch result retired");state.put("watchPending",remaining);acknowledge(state,previous);}}
 synchronized JSONObject playlistDraft()throws Exception{synchronized(VideoViewerState.class){JSONObject draft=read().optJSONObject("playlistDraft");if(draft==null)return null;if(!draft.getString("key").matches("[0-9a-f-]{36}")||draft.getString("name").isEmpty())throw new SecurityException("Original playlist draft unavailable");return new JSONObject(draft.toString());}}
 synchronized JSONObject reservePlaylist(String requested)throws Exception{synchronized(VideoViewerState.class){String value=requested.trim();if(value.isEmpty()||value.length()>1024)throw new IllegalArgumentException("Playlist name required");JSONObject state=read(),draft=state.optJSONObject("playlistDraft");if(draft!=null){if(!value.equals(draft.getString("name")))throw new IllegalStateException("Finish the original playlist draft before replacing it");write(state);return new JSONObject(draft.toString());}org.json.JSONArray history=state.optJSONArray("playlistHistory");if(history!=null)for(int i=0;i<history.length();i++){JSONObject retained=history.getJSONObject(i);if(value.equals(retained.getString("name")))return restorePlaylist(retained);}draft=new JSONObject().put("key",UUID.randomUUID().toString()).put("name",value);state.put("playlistDraft",draft);write(state);return draft;}}
 synchronized void finishPlaylist(JSONObject original)throws Exception{synchronized(VideoViewerState.class){JSONObject state=read(),previous=new JSONObject(state.toString()),pending=state.optJSONObject("playlistDraft");if(pending==null||!NativeProductState.canonical(pending).equals(NativeProductState.canonical(original)))throw new SecurityException("Original playlist result retired");state.remove("playlistDraft");acknowledge(state,previous);}}
 private static boolean validPlaylist(JSONObject row){return row!=null&&row.length()==2&&row.optString("key").matches("[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}")&&!row.optString("name").trim().isEmpty()&&row.optString("name").length()<=1024;}
 private static void validatePlaylists(JSONObject state)throws Exception{if(state.has("playlistOperation")&&!validOperation(state.optJSONObject("playlistOperation")))throw new SecurityException("Original playlist operation unavailable; preserve record");java.util.Set<String> keys=new java.util.HashSet<>();JSONObject pending=state.optJSONObject("playlistDraft");if(state.has("playlistDraft")&&(!validPlaylist(pending)||!keys.add(pending.getString("key"))))throw new SecurityException("Original playlist draft unavailable; preserve record");if(state.has("playlistHistory")){org.json.JSONArray history=state.optJSONArray("playlistHistory");if(history==null||history.length()>64)throw new SecurityException("Original playlist history unavailable; preserve record");for(int i=0;i<history.length();i++){JSONObject row=history.optJSONObject(i);if(!validPlaylist(row)||!keys.add(row.getString("key")))throw new SecurityException("Original playlist history unavailable; preserve record");}}}
 synchronized org.json.JSONArray playlistHistory()throws Exception{synchronized(VideoViewerState.class){org.json.JSONArray rows=read().optJSONArray("playlistHistory");return rows==null?new org.json.JSONArray():new org.json.JSONArray(rows.toString());}}
 synchronized void pausePlaylist(JSONObject original)throws Exception{synchronized(VideoViewerState.class){JSONObject state=read(),pending=state.optJSONObject("playlistDraft");if(pending==null||!NativeProductState.canonical(pending).equals(NativeProductState.canonical(original)))throw new SecurityException("Original playlist result retired");org.json.JSONArray history=state.optJSONArray("playlistHistory");if(history==null)history=new org.json.JSONArray();if(history.length()>=64)throw new IllegalStateException("Original playlist history full; preserve pending request");history.put(new JSONObject(pending.toString()));state.put("playlistHistory",history);state.remove("playlistDraft");write(state);}}
 synchronized JSONObject restorePlaylist(JSONObject original)throws Exception{synchronized(VideoViewerState.class){JSONObject state=read();if(state.has("playlistDraft"))throw new IllegalStateException("Finish or pause the current playlist request first");org.json.JSONArray history=state.optJSONArray("playlistHistory"),remaining=new org.json.JSONArray();boolean found=false;if(history!=null)for(int i=0;i<history.length();i++){JSONObject row=history.getJSONObject(i);if(row.getString("key").equals(original.getString("key"))){if(!NativeProductState.canonical(row).equals(NativeProductState.canonical(original)))throw new SecurityException("Original playlist body changed");found=true;}else remaining.put(row);}if(!found)throw new SecurityException("Original playlist request unavailable");JSONObject restored=new JSONObject(original.toString());state.put("playlistHistory",remaining);state.put("playlistDraft",restored);write(state);return restored;}}
 private static boolean validOperation(JSONObject row){if(row==null||row.length()!=5||!(row.opt("key") instanceof String)||!row.optString("key").matches("[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}")||!(row.opt("action") instanceof String)||!java.util.Arrays.asList("add","remove","delete").contains(row.optString("action"))||!(row.opt("playlistID") instanceof String)||!row.optString("playlistID").matches("pl_[A-Za-z0-9_-]{1,157}")||!(row.opt("name") instanceof String)||row.optString("name").trim().isEmpty()||row.optString("name").getBytes(StandardCharsets.UTF_8).length>100)return false;return "delete".equals(row.optString("action"))?row.has("videoID")&&row.isNull("videoID"):row.opt("videoID") instanceof String&&row.optString("videoID").matches("vid_[A-Za-z0-9_-]{1,156}");}
 void requireOriginalApi(VideoApi original){api.requireCurrent();original.requireCurrent();if(original!=api)throw new SecurityException("Original viewer request context required");}
 synchronized JSONObject playlistOperation()throws Exception{synchronized(VideoViewerState.class){JSONObject row=read().optJSONObject("playlistOperation");return row==null?null:new JSONObject(row.toString());}}
 synchronized JSONObject reservePlaylistOperation(String action,String playlistID,String videoID,String title)throws Exception{synchronized(VideoViewerState.class){JSONObject state=read(),row=state.optJSONObject("playlistOperation");if(row!=null){if(!action.equals(row.getString("action"))||!playlistID.equals(row.getString("playlistID"))||!(videoID==null?row.isNull("videoID"):videoID.equals(row.getString("videoID"))))throw new IllegalStateException("Retry original playlist change first");write(state);return new JSONObject(row.toString());}row=new JSONObject().put("key",UUID.randomUUID().toString()).put("action",action).put("playlistID",playlistID).put("videoID",videoID==null?JSONObject.NULL:videoID).put("name",title);if(!validOperation(row))throw new IllegalArgumentException("Original playlist change required");state.put("playlistOperation",row);write(state);return new JSONObject(row.toString());}}
 synchronized void finishPlaylistOperation(JSONObject original)throws Exception{synchronized(VideoViewerState.class){JSONObject state=read(),previous=new JSONObject(state.toString()),row=state.optJSONObject("playlistOperation");if(row==null||!NativeProductState.canonical(row).equals(NativeProductState.canonical(original)))throw new SecurityException("Original playlist change result retired");state.remove("playlistOperation");acknowledge(state,previous);}}
 synchronized void deleteMyData()throws Exception{synchronized(VideoViewerState.class){api.requireCurrent();if(!context.getSharedPreferences(name,0).edit().remove("state").commit()||context.getSharedPreferences(name,0).getString("state",null)!=null)throw new IllegalStateException("Original viewer data deletion unconfirmed");api.requireCurrent();}}
}
