import test from 'node:test';import assert from 'node:assert/strict';
import {HostedAccountManager,hostedEntryMode} from '../src/hosted-account-manager.js';
const vault={account:'0x'+'1'.repeat(40),ciphertext:'encrypted'};
function deferred(){let resolve;const promise=new Promise(r=>resolve=r);return{promise,resolve};}
test('local account mode remains separate from request/connect authority',()=>{assert.equal(hostedEntryMode({origin:'https://wallet.ynxweb4.com',topLevel:true,fragment:''}),'account');assert.equal(hostedEntryMode({origin:'https://wallet.ynxweb4.com',topLevel:true,fragment:'#account'}),'account');assert.equal(hostedEntryMode({origin:'https://wallet.ynxweb4.com',topLevel:true,fragment:'#connect=bad'}),'connect');assert.throws(()=>hostedEntryMode({origin:'https://wallet.ynxweb4.com',topLevel:true,fragment:'#invalid'}));assert.throws(()=>hostedEntryMode({origin:'https://evil.example',topLevel:true,fragment:''}));assert.throws(()=>hostedEntryMode({origin:'https://wallet.ynxweb4.com',topLevel:false,fragment:''}));});
test('unlock validates current encrypted account without returning a secret; fresh manager stays locked',async()=>{const store={read:async()=>vault},manager=new HostedAccountManager(store,async()=>({account:vault.account,secretHex:'never-return'}));assert.equal(await manager.unlock(vault,'password'),undefined);await manager.assertUnlocked(vault);manager.lock();assert.equal(manager.isUnlocked(vault),false);assert.equal(new HostedAccountManager(store).isUnlocked(vault),false);});
test('late unlock after lock or page lifecycle cancellation cannot unlock',async()=>{const waiting=deferred(),manager=new HostedAccountManager({read:async()=>vault},()=>waiting.promise);const action=manager.unlock(vault,'password');await Promise.resolve();await Promise.resolve();manager.lock();waiting.resolve({account:vault.account});await assert.rejects(action,{code:'HOSTED_UNLOCK_CANCELLED'});assert.equal(manager.isUnlocked(vault),false);});
test('account replacement and wrong password preserve locked state',async()=>{let record=vault;const waiting=deferred(),manager=new HostedAccountManager({read:async()=>record},()=>waiting.promise);const action=manager.unlock(vault,'password');await Promise.resolve();await Promise.resolve();record={...vault,ciphertext:'replacement'};waiting.resolve({account:vault.account});await assert.rejects(action,{code:'HOSTED_ACCOUNT_CHANGED'});assert.equal(manager.isUnlocked(vault),false);const wrong=new HostedAccountManager({read:async()=>vault},async()=>{throw Error('wrong password')});await assert.rejects(()=>wrong.unlock(vault,'wrong'));assert.equal(wrong.isUnlocked(vault),false);});

test('create/import lifecycle token covers work before unlock starts',async()=>{const manager=new HostedAccountManager({read:async()=>vault},async()=>({account:vault.account}));const generation=manager.begin();manager.lock();assert.equal(manager.isCurrent(generation),false);await assert.rejects(()=>manager.unlock(vault,'password',generation),{code:'HOSTED_UNLOCK_CANCELLED'});assert.equal(manager.isUnlocked(vault),false);const fresh=manager.begin();await manager.unlock(vault,'password',fresh);assert.equal(manager.isUnlocked(vault),true);});
