const $=s=>document.querySelector(s);let selectedCase="",preparedAI="";const identity=()=>{const token=sessionStorage.getItem("ynxSession");return token?{"Authorization":`Bearer ${token}`}:{"X-YNX-Actor":$("#actor").value.trim(),"X-YNX-Role":$("#role").value}};const key=()=>crypto.randomUUID();
async function api(path,options={}){const r=await fetch(path,{...options,headers:{"Content-Type":"application/json",...identity(),...(options.headers||{})}});const body=await r.json();if(!r.ok)throw new Error(body.error||`Request failed: ${r.status}`);return body}
function status(t,error=false){const e=$("#status");e.textContent=t;e.style.color=error?"#a12020":""}
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x===b));document.querySelectorAll(".view").forEach(v=>v.classList.add("hidden"));$("#"+b.dataset.view).classList.remove("hidden");if(b.dataset.view==="transparency")loadTransparency()});
async function load(){status("Loading persisted case records…");try{const d=await api("/api/state");renderCases(d.cases);status(`${d.cases.length} accessible case record${d.cases.length===1?"":"s"}. Role-scoped view.`)}catch(e){status(e.message,true)}}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function renderCases(cs){const root=$("#case-list");root.replaceChildren();if(!cs.length){root.append($("#empty").content.cloneNode(true));return}cs.forEach(c=>{const el=document.createElement("article");el.className="case";el.tabIndex=0;el.innerHTML=`<div><div class="state">${esc(c.status.replaceAll("_"," "))}</div><small>${esc(c.id)}</small><p><button data-id="${esc(c.id)}">Use for AI</button></p></div><dl><dt>Subject</dt><dd>${esc(c.subject)}</dd><dt>Purpose</dt><dd>${esc(c.purpose)}</dd><dt>Evidence</dt><dd>${c.evidence.length} record(s), source visible</dd><dt>Reason</dt><dd>${esc(c.validityReason)}</dd><dt>Appeals</dt><dd>${c.appeals.length}; appeal remains available</dd><dt>Label</dt><dd>${c.label?`<span class="tag">${esc(c.label.value)} · ${esc(c.label.source)} · expires ${esc(new Date(c.label.expiresAt).toLocaleDateString())}</span>`:"None"}</dd></dl>`;el.querySelector("button").onclick=()=>{selectedCase=c.id;status(`Selected ${c.id} for a bounded AI explanation.`);document.querySelector('[data-view="ai"]').click()};root.append(el)})}
$("#case-form").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{await api("/api/actions",{method:"POST",body:JSON.stringify({type:"submit_case",idempotencyKey:key(),subject:f.get("subject"),purpose:f.get("purpose"),requestScope:f.get("requestScope"),requestedAction:f.get("requestedAction"),evidence:[{source:f.get("source"),digest:f.get("digest"),summary:f.get("summary"),visibleToSubject:f.get("visible")==="on"}]})});e.target.reset();document.querySelector('[data-view="cases"]').click();await load();status("Evidence record persisted and subject notice recorded.")}catch(x){status(x.message,true)}};
$("#refresh").onclick=load;$("#actor").onchange=load;$("#role").onchange=load;
$("#ai-prepare").onclick=async()=>{if(!selectedCase){status("Select an accessible case first.",true);return}const context=[...document.querySelectorAll("#ai-context input:checked")].map(x=>x.value);try{const r=await api("/api/actions",{method:"POST",body:JSON.stringify({type:"ai_prepare",idempotencyKey:key(),caseId:selectedCase,purpose:"Explain evidence, classification and appeal options",context})});preparedAI=r.ai.id;$("#ai-result").innerHTML=`<b>Privacy preview</b> ${esc(r.ai.privacyPreview)}\n<b>Provider</b> ${esc(r.ai.provider)} / ${esc(r.ai.model)}\n<b>Estimate</b> ${r.ai.estimatedCredits} AI Credits\n<button id="run-ai">Allow and stream explanation</button> <button id="cancel-ai">Cancel</button>`;$("#run-ai").onclick=runAI;$("#cancel-ai").onclick=cancelAI}catch(e){status(e.message,true)}};
async function runAI(){try{$("#ai-result").textContent="Contacting YNX AI Gateway…";const r=await api("/api/actions",{method:"POST",body:JSON.stringify({type:"ai_run",idempotencyKey:key(),aiId:preparedAI,permission:true})});$("#ai-result").textContent=r.ai.status==="completed"?r.ai.result:`Provider failure: ${r.ai.error}`;status("AI output stored for review; no case state or label was changed.")}catch(e){status(e.message,true)}}
async function cancelAI(){try{await api("/api/actions",{method:"POST",body:JSON.stringify({type:"ai_cancel",idempotencyKey:key(),aiId:preparedAI})});$("#ai-result").textContent="Explanation cancelled. No action was applied."}catch(e){status(e.message,true)}}
async function loadTransparency(){try{const d=await api("/api/transparency");$("#transparency-data").innerHTML=`<p>${esc(d.method)}</p><dl><dt>Appeals</dt><dd>${d.appeals}</dd><dt>False-positive corrections</dt><dd>${d.falsePositiveCorrections}</dd><dt>Status counts</dt><dd><pre>${esc(JSON.stringify(d.caseCounts,null,2))}</pre></dd></dl>`}catch(e){status(e.message,true)}}load();
