import {StandardWalletConnection} from "../../../packages/dapp-connect-sdk/src/provider.js";
import {discoverEIP6963} from "../../../packages/dapp-connect-sdk/src/discovery.js";
import {YNX_TESTNET} from "../../../packages/dapp-connect-sdk/src/constants.js";

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],tr=k=>YNXI18n.t(k);let selectedCase="",preparedAI="",allCases=[],currentFilter="all",standardWallet=null;const key=()=>crypto.randomUUID();
const identity=()=>({});
async function api(path,options={}){const r=await fetch(path,{...options,headers:{"Content-Type":"application/json",...identity(),...(options.headers||{})}});let body={};try{body=await r.json()}catch{body={error:`Invalid API response (${r.status})`}}if(!r.ok)throw new Error(body.error||`Request failed: ${r.status}`);return body}
function setStatus(text,error=false){const root=$("#status");root.classList.toggle("error",error);root.querySelector("span").textContent=text}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function activate(view){$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$$('.view').forEach(x=>x.classList.toggle('hidden',x.id!==view));const names={cases:'Request desk',submit:'Evidence intake',authority:'Review & appeal',ai:'AI explanation',transparency:'Transparency'};$('#view-title').textContent=names[view];if(view==='transparency')loadTransparency()}
$$('.nav').forEach(b=>b.onclick=()=>activate(b.dataset.view));
async function load(){setStatus(tr('loadingCases'));try{const d=await api('/api/state');allCases=d.cases||[];renderCases();setStatus(`${YNXI18n.number(allCases.length)} ${tr('cases')}`)}catch(e){allCases=[];renderCases();setStatus(`${tr('unavailable')}: ${e.message}`,true)}}
function matches(c){if(currentFilter==='all')return true;if(currentFilter==='rejected')return ['illegal_or_abusive','overbroad','out_of_scope','rejected'].includes(c.status);return c.status===currentFilter}
function renderCases(){const root=$('#case-list');root.replaceChildren();const cases=allCases.filter(matches);if(!cases.length){root.append($('#empty').content.cloneNode(true));const action=root.querySelector('[data-empty-action]');if(action)action.onclick=()=>activate('submit');$('#case-detail').className='detail-empty';$('#case-detail').innerHTML='<p class="eyebrow">EVIDENCE INSPECTOR</p><h3>No request selected</h3><p>Empty and unavailable states never contain synthetic cases.</p>';return}cases.forEach(c=>{const b=document.createElement('button');b.className=`case-row ${c.id===selectedCase?'active':''}`;b.dataset.id=c.id;b.innerHTML=`<span class="row-top"><b>${esc(c.subject)}</b><span class="state ${esc(c.status)}">${esc(c.status.replaceAll('_',' '))}</span></span><p>${esc(c.purpose)}</p><small>${esc(c.id)} · ${YNXI18n.date(c.updatedAt)}</small>`;b.onclick=()=>{selectedCase=c.id;renderCases();renderDetail(c)};root.append(b)});const selected=cases.find(c=>c.id===selectedCase)||cases[0];selectedCase=selected.id;root.querySelector(`[data-id="${CSS.escape(selected.id)}"]`)?.classList.add('active');renderDetail(selected)}
function renderDetail(c){const evidence=(c.evidence||[]).map(e=>`<div class="evidence-event"><b>${esc(e.source)}</b><p>${esc(e.summary)}</p><div class="hash">packet ${esc(e.packet||'missing')}<br>source ${esc(e.sourceHash||e.digest)}</div><small>${esc(e.authority||'authority missing')} · ${esc(e.jurisdiction||'jurisdiction missing')} · ${e.expiresAt?YNXI18n.date(e.expiresAt):'expiry missing'}</small></div>`).join('');$('#case-detail').className='';$('#case-detail').innerHTML=`<div class="detail-head"><div><p class="eyebrow">${esc(c.id)}</p><h3>${esc(c.subject)}</h3></div><span class="state ${esc(c.status)}">${esc(c.status.replaceAll('_',' '))}</span></div><div class="validity-banner ${esc(c.status)}"><b>Request validity</b>${esc(c.validityReason)}</div><dl class="facts"><dt>Requester</dt><dd>${esc(c.requester)}</dd><dt>Authority</dt><dd>${esc(c.authority||'Not supplied')}</dd><dt>Jurisdiction</dt><dd>${esc(c.jurisdiction||'Not supplied')}</dd><dt>Scope</dt><dd>${esc(c.requestScope)}</dd><dt>Asset boundary</dt><dd>${esc(c.assetBoundary||'Not supplied')}</dd><dt>Request expiry</dt><dd>${c.requestExpiresAt&&!c.requestExpiresAt.startsWith('0001-')?YNXI18n.date(c.requestExpiresAt):'Not supplied'}</dd><dt>User notice</dt><dd>${c.notice?`${YNXI18n.date(c.notice.sentAt)} · ${esc(c.notice.reason)}`:'Pending'}</dd><dt>Appeals</dt><dd>${(c.appeals||[]).length} · correction path remains open</dd><dt>Advisory label</dt><dd>${c.label?`${esc(c.label.value)} · ${esc(c.label.confidence)} confidence · ${esc(c.label.severity)} · advisory only`:'None'}</dd></dl><p class="eyebrow">EVIDENCE TIMELINE</p><div class="timeline">${evidence||'<div class="evidence-event">No evidence packet.</div>'}</div><div class="detail-actions"><button data-ai-case="${esc(c.id)}">Explain with AI</button><button data-appeal-case="${esc(c.id)}">Open appeal path</button></div>`;$('#case-detail [data-ai-case]').onclick=()=>{selectedCase=c.id;activate('ai');setStatus(`Selected ${c.id}; preview context before permission.`)};$('#case-detail [data-appeal-case]').onclick=()=>activate('authority')}
$$('.filter').forEach(b=>b.onclick=()=>{currentFilter=b.dataset.filter;$$('.filter').forEach(x=>x.classList.toggle('active',x===b));renderCases()});$('#refresh').onclick=load;
$('#case-form').onsubmit=async e=>{e.preventDefault();setStatus('Private Trust submission is degraded because the accepted App Gateway is unavailable. Your form remains on this device; no local or synthetic authority record was created.',true)};
$('#ai-prepare').onclick=async()=>{if(!selectedCase){setStatus(tr('selectCase'),true);return}const context=$$('#ai-context input:checked').map(x=>x.value);try{const r=await api('/api/actions',{method:'POST',body:JSON.stringify({type:'ai_prepare',idempotencyKey:key(),caseId:selectedCase,purpose:'Explain evidence, validity and appeal options',context,language:$('#ai-language').value})});preparedAI=r.ai.id;$('#ai-result').innerHTML=`<p class="eyebrow">PERMISSION PREVIEW</p><b>${esc(tr('privacyPreview'))}</b><p>${esc(r.ai.privacyPreview)}</p><dl class="facts"><dt>Provider / model</dt><dd>${esc(r.ai.provider)} / ${esc(r.ai.model)}</dd><dt>Status</dt><dd>${esc(r.ai.status)}</dd><dt>Language</dt><dd>${esc(r.ai.outputLanguage)}</dd><dt>Estimated cost</dt><dd>${YNXI18n.number(r.ai.estimatedCredits)} AI Credits</dd></dl><button id="run-ai">${esc(tr('allowAI'))}</button> <button id="cancel-ai">${esc(tr('cancel'))}</button>`;$('#run-ai').onclick=runAI;$('#cancel-ai').onclick=cancelAI}catch(e){setStatus(`${tr('unavailable')}: ${e.message}`,true)}};
async function runAI(){try{$(`#ai-result`).textContent=tr('loading');const r=await api('/api/actions',{method:'POST',body:JSON.stringify({type:'ai_run',idempotencyKey:key(),aiId:preparedAI,permission:true})});if(r.ai.status==='completed')$('#ai-result').innerHTML=`<p class="eyebrow">HUMAN REVIEW REQUIRED</p><p>${esc(r.ai.result)}</p><button id="apply-ai">Apply explanation</button> <button id="reject-ai">Reject explanation</button>`,$('#apply-ai').onclick=()=>reviewAI('apply'),$('#reject-ai').onclick=()=>reviewAI('reject');else $('#ai-result').textContent=`${tr('providerFailure')}: ${r.ai.error}`;setStatus(tr('aiStored'))}catch(e){setStatus(`${tr('providerFailure')}: ${e.message}`,true)}}
async function reviewAI(decision){try{const r=await api('/api/actions',{method:'POST',body:JSON.stringify({type:'ai_review',idempotencyKey:key(),aiId:preparedAI,decision})});$('#ai-result').textContent=`Explanation ${r.ai.status}. No Trust decision or label changed.`}catch(e){setStatus(e.message,true)}}
async function cancelAI(){try{await api('/api/actions',{method:'POST',body:JSON.stringify({type:'ai_cancel',idempotencyKey:key(),aiId:preparedAI})});$('#ai-result').textContent=tr('aiCancelled')}catch(e){setStatus(e.message,true)}}
async function loadTransparency(){try{const path=sessionStorage.getItem('ynxTrustSessionBinding')?'/api/authority/transparency':'/api/transparency';const d=await api(path);$('#transparency-data').innerHTML=`<pre>${esc(JSON.stringify(d,null,2))}</pre>`}catch(e){$('#transparency-data').innerHTML=`<div class="validity-banner"><b>Unavailable</b>${esc(e.message)}. No local transparency result substituted.</div>`}}
$('#authority-query').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),base={evidence:'evidence',governance:'governance/requests',appeal:'appeals'}[f.get('kind')];try{$('#authority-result').textContent=JSON.stringify(await api(`/api/authority/${base}/${encodeURIComponent(f.get('id'))}`),null,2)}catch(x){$('#authority-result').textContent=`${x.message}. ${tr('localResultBlocked')}`}};$('#appeal-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{$(`#authority-result`).textContent=JSON.stringify(await api('/api/authority/appeals',{method:'POST',body:JSON.stringify({idempotencyKey:key(),subjectId:f.get('subjectId'),reason:f.get('reason'),evidence:JSON.parse(f.get('evidence'))})}),null,2)}catch(x){$('#authority-result').textContent=x.message}};$('#review-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{$(`#authority-result`).textContent=JSON.stringify(await api(`/api/authority/governance/requests/${encodeURIComponent(f.get('id'))}/review`,{method:'POST',body:JSON.stringify(JSON.parse(f.get('review')))}),null,2)}catch(x){$('#authority-result').textContent=x.message}};
const names={en:'English','zh-Hans':'简体中文','zh-Hant':'繁體中文',ja:'日本語',ko:'한국어',es:'Español',fr:'Français',de:'Deutsch',pt:'Português',ru:'Русский',ar:'العربية',id:'Bahasa Indonesia'};$$('.locale-select,#ai-language').forEach(s=>{s.innerHTML=YNXI18n.codes.map(c=>`<option value="${c}">${names[c]}</option>`).join('');s.value=s.id==='ai-language'?(localStorage.getItem('ynxTrustAILocale')||YNXI18n.locale):YNXI18n.locale});function syncLocaleLabel(){const n=$('.locale-current');if(n)n.textContent=names[YNXI18n.locale];}syncLocaleLabel();$('.locale-select').onchange=e=>{YNXI18n.set(e.target.value);syncLocaleLabel();const menu=e.target.closest('details');if(menu)menu.open=false;load()};$('#ai-language').onchange=e=>localStorage.setItem('ynxTrustAILocale',e.target.value);
$('#wallet-open').onclick=()=>$('#wallet').classList.remove('hidden');$('.sheet-close').onclick=()=>$('#wallet').classList.add('hidden');
async function availableProviders(){const announced=await discoverEIP6963(window,{timeoutMs:180});if(window.ethereum?.request&&!announced.some(x=>x.provider===window.ethereum))announced.push({info:{uuid:'legacy-injected',name:'Injected wallet'},provider:window.ethereum});return announced}
async function connectStandard({metamaskOnly=false}={}){const result=$('#wallet-result');result.textContent='Looking for an approved standard wallet…';try{const providers=await availableProviders(),chosen=(metamaskOnly?providers.find(x=>/metamask/i.test(x.info?.name||'')):providers.find(x=>/ynx/i.test(x.info?.name||'')))||providers[0];if(!chosen){result.innerHTML=`No compatible wallet was detected. <a href="${globalThis.YNX_TRUST_RUNTIME.walletDownload}" target="_blank" rel="noopener noreferrer">Download YNX Wallet</a> or <a href="${globalThis.YNX_TRUST_RUNTIME.metamaskDownload}" target="_blank" rel="noopener noreferrer">install MetaMask</a>.`;return}const connection=new StandardWalletConnection(chosen.provider,{chain:YNX_TESTNET}),connected=await connection.connect();await connection.ensureYNXTestnet({addChain:{chainId:'0x1917',chainName:'YNX Testnet',nativeCurrency:{name:'YNX Testnet',symbol:'YNXT',decimals:18},rpcUrls:[globalThis.YNX_TRUST_RUNTIME.evmRpc.url],blockExplorerUrls:[globalThis.YNX_TRUST_RUNTIME.explorer.url]}});standardWallet=connection;$('#wallet-account').textContent=`${connected.account.slice(0,8)}…${connected.account.slice(-6)}`;$('#wallet-standard-state').textContent='CONNECTED · 0x1917';$('#wallet-open').textContent='Wallet connected';result.textContent='Standard Wallet Connection is active. The unavailable private Trust service did not remove it.';chosen.provider.on?.('accountsChanged',accounts=>{if(!accounts?.[0]){$('#wallet-standard-state').textContent='DISCONNECTED';$('#wallet-account').textContent='Not connected'}});chosen.provider.on?.('chainChanged',chainId=>{$('#wallet-standard-state').textContent=String(chainId).toLowerCase()==='0x1917'?'CONNECTED · 0x1917':'WRONG CHAIN'})}catch(error){result.textContent=`Wallet connection failed: ${error.code||'WALLET_CONNECTION_FAILED'}. Public Trust records remain available.`}}
$('#wallet-connect').onclick=()=>connectStandard();$('#wallet-metamask').onclick=()=>connectStandard({metamaskOnly:true});
function applyPrefs(){document.body.classList.toggle('large-text',localStorage.getItem('ynxTrustLargeText')==='1');document.body.classList.toggle('theme-dark',localStorage.getItem('ynxTrustTheme')==='dark');$('#text-size').setAttribute('aria-pressed',String(document.body.classList.contains('large-text')));$('#theme-toggle').setAttribute('aria-pressed',String(document.body.classList.contains('theme-dark')))}
$('#text-size').onclick=()=>{localStorage.setItem('ynxTrustLargeText',document.body.classList.contains('large-text')?'0':'1');applyPrefs()};$('#theme-toggle').onclick=()=>{localStorage.setItem('ynxTrustTheme',document.body.classList.contains('theme-dark')?'light':'dark');applyPrefs()};applyPrefs();load();
