import assert from "node:assert/strict";
import { createServer } from "node:http";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { createWorkspaceRuntime } from "../src/runtime.mjs";

async function fixture(t){const root=await mkdtemp(join(tmpdir(),"ynx-code-test-")),runtime=createWorkspaceRuntime({root,sessionKey:Buffer.alloc(32,7),concurrency:4,queueLimit:16}),server=createServer((request,response)=>runtime.handler(request,response).then(handled=>{if(!handled)response.writeHead(404).end()}));await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));t.after(async()=>{await new Promise(resolve=>server.close(resolve));await rm(root,{recursive:true,force:true})});return{url:`http://127.0.0.1:${server.address().port}`,runtime}}
async function session(url){const response=await fetch(`${url}/runtime/health`),cookie=response.headers.get("set-cookie")?.split(";")[0];assert.ok(cookie);return cookie}
function task(source="int main(){return 0;}"){return{protocolVersion:"ynx-code/v1",task:"build-run-active",projectId:"cpp-project",activePath:"src/main.cpp",files:{"src/main.cpp":source},approval:"execute-once"}}
test("health creates an isolated guest session and reports sandbox truth",async t=>{const{url}=await fixture(t),response=await fetch(`${url}/runtime/health`),value=await response.json();assert.equal(value.protocolVersion,"ynx-code/v1");assert.equal(value.sessionClass,"ephemeral-guest");assert.equal(typeof value.sandboxReady,"boolean");assert.match(response.headers.get("set-cookie"),/HttpOnly; SameSite=Strict/)});
test("C++ is really compiled and executed through the approved sandbox",async t=>{const{url}=await fixture(t),cookie=await session(url),response=await fetch(`${url}/runtime/tasks`,{method:"POST",headers:{cookie,"content-type":"application/json"},body:JSON.stringify(task('#include <iostream>\nint main(){std::cout << "YNX-CPP-42"; return 0;}'))}),value=await response.json();assert.equal(response.status,200,JSON.stringify(value));assert.equal(value.ok,true);assert.equal(value.language,"cpp");assert.match(value.output,/YNX-CPP-42/);assert.equal(value.sandbox.network,false);assert.equal(value.sandbox.writableRoot,"workspace");assert.equal(JSON.stringify(value).includes(tmpdir()),false)});
test("streaming tasks emit ordered compiler and program events before the result",async t=>{const{url}=await fixture(t),cookie=await session(url),response=await fetch(`${url}/runtime/tasks/stream`,{method:"POST",headers:{cookie,"content-type":"application/json"},body:JSON.stringify(task('#include <iostream>\nint main(){std::cout << "STREAMED-CPP"; return 0;}'))});assert.equal(response.status,200);assert.match(response.headers.get("content-type"),/application\/x-ndjson/);const events=(await response.text()).trim().split("\n").map(line=>JSON.parse(line));const sequenced=events.filter(event=>event.sequence);assert.deepEqual(sequenced.map(event=>event.sequence),sequenced.map((_,index)=>index+1));assert.equal(events[0].type,"phase");assert.ok(events.some(event=>event.type==="output"&&event.data.includes("STREAMED-CPP")));assert.equal(events.at(-1).type,"result");assert.equal(events.at(-1).value.ok,true)});
test("task approval, path traversal and compiler errors fail closed",async t=>{const{url}=await fixture(t),cookie=await session(url);for(const body of [{...task(),approval:"chat-approved"},{...task(),activePath:"../main.cpp",files:{"../main.cpp":""}}]){const response=await fetch(`${url}/runtime/tasks`,{method:"POST",headers:{cookie,"content-type":"application/json"},body:JSON.stringify(body)});assert.ok([400,403].includes(response.status))}const failed=await fetch(`${url}/runtime/tasks`,{method:"POST",headers:{cookie,"content-type":"application/json"},body:JSON.stringify(task("int main( {"))});const value=await failed.json();assert.equal(failed.status,200);assert.equal(value.ok,false);assert.notEqual(value.code,0)});
test("parallel users receive bounded independent workspaces",async t=>{const{url,runtime}=await fixture(t),cookies=await Promise.all(Array.from({length:8},()=>session(url))),results=await Promise.all(cookies.map((cookie,index)=>fetch(`${url}/runtime/tasks`,{method:"POST",headers:{cookie,"content-type":"application/json"},body:JSON.stringify({...task(`#include <iostream>\nint main(){std::cout << ${index};}`),projectId:`p-${index}`})}).then(response=>response.json())));assert.deepEqual(results.map(value=>value.ok),Array(8).fill(true));assert.deepEqual(results.map(value=>value.output.match(/run> (\d)/)?.[1]),["0","1","2","3","4","5","6","7"]);assert.equal(runtime.status().active,0);assert.equal(runtime.status().queued,0)});
