import { createServer } from "node:http";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { SearchStore } from "./store.js";
import { indexRegisteredSource } from "./crawler.js";
import { SearchAi } from "./ai.js";
import { SEARCH_PROVIDER_CONTRACT, SEARCH_INDEX_CONTRACT, walletRequest, parseWalletCallback } from "./contracts.js";
import { createTrustReferral, validateWalletAuthorizationV1 } from "../../../packages/web4-permissions/src/index.js";

const dataPath=process.env.YNX_SEARCH_DATA_PATH??join(process.cwd(),"var","search-index.json");
const store=new SearchStore(dataPath),port=Number(process.env.PORT??4313),publicDir=join(import.meta.dirname,"public"),sharedI18n=fileURLToPath(new URL("../../../packages/web4-permissions/src/i18n.js",import.meta.url));
const build={version:process.env.YNX_BUILD_VERSION??"0.2.0",commit:process.env.YNX_BUILD_COMMIT??"development",builtAt:process.env.YNX_BUILD_TIME??null,releaseChannel:process.env.YNX_RELEASE_CHANNEL??"local"};
const securityHeaders={"x-content-type-options":"nosniff","x-frame-options":"DENY","referrer-policy":"no-referrer","permissions-policy":"camera=(), microphone=(), geolocation=(), payment=(), usb=()","cross-origin-resource-policy":"same-origin"};
function json(res,status,value){res.writeHead(status,{"content-type":"application/json; charset=utf-8","cache-control":"no-store","content-security-policy":"default-src 'none'; frame-ancestors 'none'",...securityHeaders});res.end(JSON.stringify(value))}
async function body(req){let text="";for await(const chunk of req){text+=chunk;if(text.length>1_000_000)throw new Error("request body too large")}return text?JSON.parse(text):{}}
function admin(req){const expected=process.env.YNX_SEARCH_ADMIN_TOKEN;if(!expected||req.headers.authorization!==`Bearer ${expected}`)throw Object.assign(new Error("admin authorization required"),{status:401})}
function origin(req){const value=process.env.YNX_PUBLIC_ORIGIN??`http://${req.headers.host??"localhost"}`;if(req.headers.origin&&req.headers.origin!==value)throw Object.assign(new Error("cross-origin mutation rejected"),{status:403});return value}
const rates=new Map();function rate(req,bucket,limit){const now=Date.now(),key=`${bucket}:${req.socket.remoteAddress??"unknown"}`,prior=rates.get(key)??{start:now,count:0};if(now-prior.start>=60_000){prior.start=now;prior.count=0}prior.count++;rates.set(key,prior);if(prior.count>limit)throw Object.assign(new Error("rate limit exceeded; retry after one minute"),{status:429})}
async function createCase(kind,input){const item=await store.createCase(kind,input),trustReferral=createTrustReferral({product:"search",kind:kind==="removal"?"abuse-removal":kind,objectId:item.id,sourceUrl:item.sourceUrl,reason:item.reason,evidenceUrls:item.evidenceUrls});return{case:item,trustReferral,trustStatus:process.env.YNX_TRUST_API_URL?"referral-ready":"central-trust-unavailable"}}

const server=createServer(async(req,res)=>{try{
  const url=new URL(req.url,`http://${req.headers.host??"localhost"}`);
  if(req.method==="GET"&&url.pathname==="/api/health")return json(res,200,{status:"available",build,provider:SEARCH_PROVIDER_CONTRACT,index:SEARCH_INDEX_CONTRACT,aiGateway:process.env.YNX_AI_GATEWAY_URL&&process.env.YNX_AI_GATEWAY_CLIENT_TOKEN?"configured":"unavailable",walletGateway:process.env.YNX_WALLET_GATEWAY_URL?"configured":"unavailable",trustGateway:process.env.YNX_TRUST_API_URL?"configured":"unavailable",offline:"cached shell only; search requires local service/index"});
  if(req.method==="GET"&&url.pathname==="/api/search"){rate(req,"query",120);return json(res,200,await store.search(url.searchParams.get("q"),{page:Number(url.searchParams.get("page")??1),pageSize:Number(url.searchParams.get("pageSize")??10),sourceId:url.searchParams.get("source")||null,freshnessDays:url.searchParams.get("freshnessDays")?Number(url.searchParams.get("freshnessDays")):null,contentType:url.searchParams.get("type")||null}))}
  if(req.method==="GET"&&url.pathname==="/api/index/status"){const db=await store.snapshot();return json(res,200,{contract:SEARCH_INDEX_CONTRACT,coverageClaim:SEARCH_PROVIDER_CONTRACT.coverage,sources:Object.values(db.sources).map(({authorizationEvidence,...source})=>source),documentCount:Object.keys(db.documents).length,revision:db.revision})}
  if(req.method==="POST"&&url.pathname==="/api/sources"){admin(req);return json(res,201,await store.registerSource(await body(req)))}
  if(req.method==="POST"&&/^\/api\/sources\/[^/]+\/index$/.test(url.pathname)){admin(req);const id=url.pathname.split("/")[3],source=(await store.snapshot()).sources[id];if(!source)throw Object.assign(new Error("source not found"),{status:404});return json(res,200,await indexRegisteredSource(store,source))}
  if(req.method==="POST"&&/^\/api\/(removal|correction|appeal)$/.test(url.pathname)){origin(req);rate(req,"case",10);return json(res,201,await createCase(url.pathname.split("/").at(-1),await body(req)))}
  if(req.method==="GET"&&/^\/api\/cases\/[0-9a-f-]+$/.test(url.pathname)){const id=url.pathname.split("/").at(-1),item=(await store.snapshot()).cases[id];if(!item)throw Object.assign(new Error("case not found"),{status:404});return json(res,200,{case:item,trustStatus:process.env.YNX_TRUST_API_URL?"configured":"central-trust-unavailable"})}
  if(req.method==="GET"&&url.pathname==="/api/admin/cases"){admin(req);const db=await store.snapshot();return json(res,200,{cases:Object.values(db.cases),revision:db.revision})}
  if(req.method==="POST"&&/^\/api\/admin\/cases\/[0-9a-f-]+\/decision$/.test(url.pathname)){admin(req);const id=url.pathname.split("/")[4],input=await body(req);return json(res,200,{case:await store.updateCase(id,input.status,input.note,input.actor??"operator")})}
  if(req.method==="POST"&&url.pathname==="/api/wallet/prepare"){const input=await body(req);origin(req);if(typeof input.deviceKey!=="string"||input.deviceKey.length!==44)throw new Error("compressed P-256 product device key required");const request=walletRequest({callback:process.env.YNX_SEARCH_WALLET_CALLBACK??"https://search-staging.43.153.202.237.sslip.io/auth/callback",deviceKey:input.deviceKey});validateWalletAuthorizationV1(request);await store.createWalletChallenge(request);return json(res,200,{request,deepLink:`ynxwallet://authorize?request=${Buffer.from(JSON.stringify(request)).toString("base64url")}`,expiresInSeconds:300})}
  if(req.method==="POST"&&url.pathname==="/api/wallet/callback"){origin(req);const response=parseWalletCallback(await body(req));const consumed=await store.consumeWalletChallenge(response.nonce,response);return json(res,202,{...consumed,message:"Callback binding accepted. Central Wallet Gateway signature and device challenge verification are required; no session was created."})}
  if(req.method==="POST"&&url.pathname==="/api/privacy/clear"){origin(req);return json(res,200,await store.clearPrivateData(await body(req)))}
  if(req.method==="POST"&&url.pathname==="/api/ai/prepare"){origin(req);const input=await body(req),retrieval=await store.search(input.query,{pageSize:8,...input.filters});return json(res,200,{providerStatus:process.env.YNX_AI_GATEWAY_URL&&process.env.YNX_AI_GATEWAY_CLIENT_TOKEN?"configured":"unavailable",model:input.model??"default",outputLocale:input.outputLocale??"en",contextClasses:["indexed-public-source-snippets"],sources:retrieval.results.map(r=>({sourceUrl:r.sourceUrl,title:r.title,fetchedAt:r.freshness.fetchedAt})),estimate:{unit:"source snippets",maximum:retrieval.results.length},permissionRequired:true})}
  if(req.method==="POST"&&url.pathname==="/api/ai/answer"){origin(req);const input=await body(req),retrieval=await store.search(input.query,{pageSize:8,...input.filters}),ai=new SearchAi({gatewayUrl:process.env.YNX_AI_GATEWAY_URL,clientToken:process.env.YNX_AI_GATEWAY_CLIENT_TOKEN,store});return json(res,200,await ai.answer({...input,results:retrieval.results}))}
  if(req.method==="POST"&&url.pathname==="/api/ai/stream"){origin(req);const input=await body(req),retrieval=await store.search(input.query,{pageSize:8,...input.filters}),ai=new SearchAi({gatewayUrl:process.env.YNX_AI_GATEWAY_URL,clientToken:process.env.YNX_AI_GATEWAY_CLIENT_TOKEN,store}),controller=new AbortController();req.on("close",()=>controller.abort());const stream=await ai.startStream({...input,results:retrieval.results},{signal:controller.signal});res.writeHead(200,{"content-type":"text/plain; charset=utf-8","cache-control":"no-store","x-ynx-retrieval-sources":JSON.stringify(stream.citations),"x-content-type-options":"nosniff"});for await(const chunk of stream.response.body)res.write(chunk);res.end();await store.auditAi({event:"stream-completed",model:input.model??"default",sourceUrls:stream.citations,resultingAction:"result-review"});return}
  if(req.method==="POST"&&url.pathname==="/api/ai/review"){origin(req);const input=await body(req);if(!["accept","reject","request-correction"].includes(input.decision))throw new Error("invalid AI review");await store.auditAi({event:"result-reviewed",reviewer:"user",resultingAction:input.decision,sourceUrls:(input.sourceUrls??[]).slice(0,8)});return json(res,200,{decision:input.decision})}
  const asset=(url.pathname==="/"||url.pathname==="/auth/callback")?"index.html":url.pathname.slice(1);if(["index.html","app.js","i18n.js","shared-i18n.js","styles.css","sw.js"].includes(asset)){const content=await readFile(asset==="shared-i18n.js"?sharedI18n:join(publicDir,asset));res.writeHead(200,{"content-type":asset.endsWith(".html")?"text/html; charset=utf-8":asset.endsWith(".css")?"text/css; charset=utf-8":"text/javascript; charset=utf-8","cache-control":asset==="sw.js"?"no-cache":"no-store","content-security-policy":"default-src 'self'; style-src 'self'; script-src 'self'; connect-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'",...securityHeaders});return res.end(content)}
  json(res,404,{error:"not found"});
}catch(error){if(!res.headersSent)json(res,error.status??400,{error:error.message,retryable:(error.status??400)>=500});else res.end()}});

if(process.argv[1]===fileURLToPath(import.meta.url))server.listen(port,"127.0.0.1",()=>console.log(`YNX Search listening on http://127.0.0.1:${port}`));
export{server,store};
