import { useEffect, useMemo, useState } from "react";
import type { ReactNode } from "react";
import { catalogs, locales } from "./i18n";
import { useDexData } from "./useDexData";
import type { ChainEvent, Locale, Pool } from "./types";

type Page="swap"|"pools"|"positions"|"explore"|"analytics"|"governance"|"docs";
const pages:Page[]=["swap","pools","positions","explore","analytics","governance","docs"];
const short=(value:string)=>value?`${value.slice(0,6)}…${value.slice(-4)}`:"—";

export default function App(){
 const [locale,setLocale]=useState<Locale>(()=>(localStorage.getItem("ynx-dex-locale") as Locale)||"en");
 const [page,setPage]=useState<Page>(()=>{const value=location.hash.slice(1) as Page;return pages.includes(value)?value:"swap"});
 const [theme,setTheme]=useState<"system"|"light"|"dark">(()=>(localStorage.getItem("ynx-dex-theme") as "system"|"light"|"dark")||"system");
 const [settings,setSettings]=useState(false); const [wallet,setWallet]=useState(false); const [mobileMenu,setMobileMenu]=useState(false);
 const {data,retry}=useDexData(); const t=catalogs[locale]; const rtl=locale==="ar";
 useEffect(()=>{document.documentElement.lang=locale;document.documentElement.dir=rtl?"rtl":"ltr";localStorage.setItem("ynx-dex-locale",locale)},[locale,rtl]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem("ynx-dex-theme",theme)},[theme]);
 useEffect(()=>{const onHash=()=>{const value=location.hash.slice(1) as Page;if(pages.includes(value))setPage(value)};addEventListener("hashchange",onHash);return()=>removeEventListener("hashchange",onHash)},[]);
 const navigate=(next:Page)=>{location.hash=next;setPage(next);setMobileMenu(false)};
 const pools=data.state==="ready"?data.data.pools:[]; const events=data.state==="ready"?data.data.events:[];
 return <div className="app-shell">
   <a className="skip-link" href="#main">Skip to content</a>
   <aside className={`sidebar ${mobileMenu?"mobile-open":""}`} aria-label="Primary navigation">
    <div className="brand-row"><Mark/><div><strong>YNX DEX</strong><span>{t.testnet}</span></div><button className="icon-button mobile-close" onClick={()=>setMobileMenu(false)} aria-label={t.close}><Icon name="close"/></button></div>
    <nav>{pages.map((item)=><button key={item} aria-current={page===item?"page":undefined} onClick={()=>navigate(item)}><Icon name={item}/><span>{t[item]}</span></button>)}</nav>
    <div className="sidebar-foot"><span className="network-dot" aria-hidden="true"/><div><strong>{t.network}</strong><span>{data.state==="ready"?`${t.latestBlock} ${data.data.analytics.latestBlock||"—"}`:t.unavailable}</span></div></div>
   </aside>
   <section className="workspace">
    <header className="topbar"><button className="icon-button mobile-menu" onClick={()=>setMobileMenu(true)} aria-label={t.menu}><Icon name="menu"/></button><div className="mobile-brand"><Mark/><strong>DEX</strong></div><div className="top-actions"><button className="icon-button" onClick={()=>setSettings(true)} aria-label={t.settings}><Icon name="settings"/></button><button className="wallet-button" onClick={()=>setWallet(true)}><Icon name="wallet"/>{t.connect}</button></div></header>
    {!navigator.onLine&&<div className="offline-banner" role="status"><Icon name="offline"/>{t.offline}</div>}
    <main id="main" tabIndex={-1}>
      {page==="swap"&&<SwapPage pools={pools} loading={data.state==="loading"} error={data.state==="error"?data.message:""} retry={retry} t={t}/>} 
      {page==="pools"&&<PoolsPage pools={pools} state={data} retry={retry} t={t}/>} 
      {page==="positions"&&<EmptyPage icon="positions" title={t.emptyPositions} detail={t.centralPending} action={t.connect} onAction={()=>setWallet(true)}/>} 
      {page==="explore"&&<ExplorePage events={events} state={data} retry={retry} t={t}/>} 
      {page==="analytics"&&<AnalyticsPage data={data} t={t}/>} 
      {page==="governance"&&<InfoPage title={t.governance} text={t.governanceText} rows={[[t.protocol,"ynx-dex-cpmm-v1"],[t.status,t.readOnly],[t.security,"2-day public delay"]]}/>} 
      {page==="docs"&&<InfoPage title={t.docs} text={t.docsText} rows={[[t.network,"6423 / ynx_6423-1"],[t.contract,"Versioned deployment manifest"],[t.source,"Verified contract source required"]]}/>} 
   </main>
   </section>
   <nav className="mobile-tabs" aria-label="Mobile navigation">{(["swap","pools","positions","explore"] as Page[]).map(item=><button key={item} aria-current={page===item?"page":undefined} onClick={()=>navigate(item)}><Icon name={item}/><span>{t[item]}</span></button>)}</nav>
   {settings&&<Modal title={t.settings} close={()=>setSettings(false)}><div className="settings-list"><label><span>{t.language}</span><select value={locale} onChange={event=>setLocale(event.target.value as Locale)}>{locales.map(item=><option key={item}>{item}</option>)}</select></label><fieldset><legend>{t.appearance}</legend>{(["system","light","dark"] as const).map(item=><label key={item}><input type="radio" checked={theme===item} onChange={()=>setTheme(item)}/><span>{t[item]}</span></label>)}</fieldset><div className="settings-note"><Icon name="security"/><div><strong>{t.security}</strong><p>{t.liveOnly}</p></div></div></div></Modal>}
   {wallet&&<Modal title={t.connect} close={()=>setWallet(false)}><div className="wallet-state"><span className="state-icon warning"><Icon name="wallet"/></span><h3>{t.unavailable}</h3><p>{t.centralPending}</p><dl><div><dt>{t.network}</dt><dd>ynx_6423-1</dd></div><div><dt>Client</dt><dd>ynx-dex-web-v1</dd></div><div><dt>Scopes</dt><dd>account:read · dex:positions:read · dex:transaction:request</dd></div></dl><button className="primary" disabled>{t.confirmWallet}</button></div></Modal>}
   {mobileMenu&&<button className="scrim" aria-label={t.close} onClick={()=>setMobileMenu(false)}/>} 
 </div>
}

function SwapPage({pools,loading,error,retry,t}:{pools:Pool[];loading:boolean;error:string;retry:()=>void;t:typeof catalogs.en}){
 const tokens=useMemo(()=>Array.from(new Set(pools.flatMap(pool=>[pool.token0,pool.token1]))),[pools]);
 const [from,setFrom]=useState("");const [to,setTo]=useState("");const [amount,setAmount]=useState("");
 useEffect(()=>{if(tokens.length>1){setFrom(value=>value||tokens[0]);setTo(value=>value||tokens[1])}},[tokens]);
 const hasRoute=Boolean(from&&to&&from!==to&&pools.some(pool=>(pool.token0===from&&pool.token1===to)||(pool.token1===from&&pool.token0===to)));
 return <div className="swap-layout"><section className="composer-column"><div className="page-kicker"><span>{t.testnet}</span><span>•</span><span>{t.protocol}</span></div><h1>{t.swap}</h1><p className="lede">{t.liveOnly}</p>
   <div className="swap-composer"><TokenAmount label={t.from} value={amount} onChange={setAmount} token={from} onToken={setFrom} tokens={tokens}/><button className="swap-direction" aria-label="Reverse tokens" onClick={()=>{setFrom(to);setTo(from)}}><Icon name="down"/></button><TokenAmount label={t.to} value="" onChange={()=>undefined} token={to} onToken={setTo} tokens={tokens} readonly/>
   {loading?<Skeleton rows={2}/>:error?<InlineError message={error} retry={retry} label={t.retry}/>:<div className="quote-empty"><Icon name="route"/><div><strong>{hasRoute&&amount?t.review:t.noRoute}</strong><span>{hasRoute&&amount?"A fresh signed quote is required before review.":t.routeHint}</span></div></div>}
   <button className="primary review-button" disabled={!hasRoute||!amount}>{t.review}</button></div></section>
   <aside className="inspector" aria-label={t.details}><h2>{t.details}</h2><InspectorRow label="Route" value={hasRoute?`${short(from)} → ${short(to)}`:"—"}/><InspectorRow label={t.fees} value={hasRoute?"0.30%":"—"}/><InspectorRow label={t.minimum} value="—"/><InspectorRow label={t.slippage} value="0.50%"/><InspectorRow label={t.deadline} value="10 min"/><InspectorRow label={t.gas} value="—"/><div className="risk-note"><Icon name="security"/><p>{t.docsText}</p></div></aside>
 </div>
}
function TokenAmount({label,value,onChange,token,onToken,tokens,readonly=false}:{label:string;value:string;onChange:(v:string)=>void;token:string;onToken:(v:string)=>void;tokens:string[];readonly?:boolean}){return <label className="token-field"><span>{label}</span><div><input inputMode="decimal" placeholder="0" value={value} readOnly={readonly} onChange={event=>{if(/^\d*(\.\d*)?$/.test(event.target.value))onChange(event.target.value)}} aria-label={`${label} amount`}/><select value={token} onChange={event=>onToken(event.target.value)} aria-label={`${label} token`}><option value="">Token</option>{tokens.map(item=><option value={item} key={item}>{short(item)}</option>)}</select></div></label>}
function PoolsPage({pools,state,retry,t}:{pools:Pool[];state:{state:string;message?:string};retry:()=>void;t:typeof catalogs.en}){return <PageFrame title={t.pools} subtitle={t.liveOnly}>{state.state==="loading"?<Skeleton rows={6}/>:state.state==="error"?<InlineError message={state.message||t.unavailable} retry={retry} label={t.retry}/>:pools.length===0?<EmptyPage icon="pools" title={t.emptyPools} detail={t.liveOnly}/>:<div className="table-wrap"><table><thead><tr><th>{t.pool}</th><th>{t.reserves}</th><th>{t.updated}</th><th>{t.status}</th></tr></thead><tbody>{pools.map(pool=><tr key={pool.address}><td><strong>{short(pool.token0)} / {short(pool.token1)}</strong><span>{short(pool.address)}</span></td><td><code>{pool.reserve0}</code><span><code>{pool.reserve1}</code></span></td><td>#{pool.updatedBlock}<span>{new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(pool.updatedAt))}</span></td><td><span className="status-pill"><i/>Indexed</span></td></tr>)}</tbody></table></div>}</PageFrame>}
function ExplorePage({events,state,retry,t}:{events:ChainEvent[];state:{state:string;message?:string};retry:()=>void;t:typeof catalogs.en}){const [query,setQuery]=useState("");const filtered=events.filter(event=>`${event.txHash} ${event.pool} ${event.type}`.toLowerCase().includes(query.toLowerCase()));return <PageFrame title={t.explore} subtitle={t.liveOnly} action={<label className="search"><Icon name="search"/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder={t.search}/></label>}>{state.state==="loading"?<Skeleton rows={6}/>:state.state==="error"?<InlineError message={state.message||t.unavailable} retry={retry} label={t.retry}/>:filtered.length===0?<EmptyPage icon="explore" title={t.emptyEvents} detail={t.liveOnly}/>:<div className="timeline">{filtered.map(event=><article key={event.id}><span className="timeline-icon"><Icon name={event.type==="swap"?"swap":"pools"}/></span><div><strong>{event.type.replaceAll("-"," ")}</strong><p>{short(event.txHash)} · {short(event.pool)}</p></div><div className="timeline-meta"><strong>#{event.blockNumber}</strong><span>{new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(event.timestamp))}</span></div></article>)}</div>}</PageFrame>}
function AnalyticsPage({data,t}:{data:ReturnType<typeof useDexData>["data"];t:typeof catalogs.en}){if(data.state==="loading")return <PageFrame title={t.analytics}><Skeleton rows={5}/></PageFrame>;if(data.state==="error")return <PageFrame title={t.analytics}><EmptyPage icon="analytics" title={t.unavailable} detail={data.message}/></PageFrame>;const metrics=[[t.indexed,data.data.analytics.indexedEvents],[t.pools,data.data.analytics.pools],[t.swap,data.data.analytics.swaps],[t.latestBlock,data.data.analytics.latestBlock||"—"]];return <PageFrame title={t.analytics} subtitle={t.liveOnly}><div className="metrics">{metrics.map(([label,value])=><div key={label}><span>{label}</span><strong>{new Intl.NumberFormat().format(value as number)}</strong></div>)}</div><div className="chart-empty"><div className="axis-lines"/><Icon name="analytics"/><strong>Historical series unavailable</strong><p>Charts appear only after real indexed intervals are available.</p></div><p className="source-line"><Icon name="info"/>{t.source}: {data.data.analytics.source}</p></PageFrame>}
function PageFrame({title,subtitle,action,children}:{title:string;subtitle?:string;action?:ReactNode;children:ReactNode}){return <div className="page"><div className="page-heading"><div><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div>{action}</div>{children}</div>}
function InfoPage({title,text,rows}:{title:string;text:string;rows:string[][]}){return <PageFrame title={title} subtitle={text}><div className="info-list">{rows.map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong><Icon name="chevron"/></div>)}</div></PageFrame>}
function EmptyPage({icon,title,detail,action,onAction}:{icon:string;title:string;detail:string;action?:string;onAction?:()=>void}){return <div className="empty-state"><span className="state-icon"><Icon name={icon}/></span><h2>{title}</h2><p>{detail}</p>{action&&<button className="secondary" onClick={onAction}>{action}</button>}</div>}
function InlineError({message,retry,label}:{message:string;retry:()=>void;label:string}){return <div className="inline-error" role="alert"><Icon name="warning"/><div><strong>Unable to load live data</strong><span>{message}</span></div><button onClick={retry}>{label}</button></div>}
function Skeleton({rows}:{rows:number}){return <div className="skeleton" aria-label="Loading" aria-busy="true">{Array.from({length:rows},(_,index)=><i key={index}/>)}</div>}
function InspectorRow({label,value}:{label:string;value:string}){return <div className="inspector-row"><span>{label}</span><strong>{value}</strong></div>}
function Modal({title,close,children}:{title:string;close:()=>void;children:ReactNode}){useEffect(()=>{const onKey=(event:KeyboardEvent)=>{if(event.key==="Escape")close()};addEventListener("keydown",onKey);return()=>removeEventListener("keydown",onKey)},[close]);return <div className="modal-layer" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)close()}}><section className="modal" role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button className="icon-button" onClick={close} aria-label="Close"><Icon name="close"/></button></header>{children}</section></div>}
function Mark(){return <span className="mark" aria-hidden="true"><i/><i/></span>}
function Icon({name}:{name:string}){const paths:Record<string,string>={swap:"M7 7h11l-3-3m3 3-3 3M17 17H6l3 3m-3-3 3-3",pools:"M4 8h16M6 4h12l2 16H4L6 4Zm2 8h8",positions:"M6 5h12v14H6zM9 9h6m-6 4h6",explore:"M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18Zm3-12-2 4-4 2 2-4 4-2Z",analytics:"M4 19V9m5 10V5m5 14v-7m5 7V3",governance:"M3 10h18M5 10v8m4-8v8m6-8v8m4-8v8M3 21h18M12 3l9 4H3l9-4Z",docs:"M6 3h9l3 3v15H6V3Zm9 0v4h4M9 11h6m-6 4h6",settings:"M12 15.5A3.5 3.5 0 1 0 12 8a3.5 3.5 0 0 0 0 7.5Zm8-3.5 2-1-2-4-2 .5-1.5-1L16 4h-4l-.5 2.5-1.5 1-2-.5-2 4 2 1v2l-2 1 2 4 2-.5 1.5 1L12 22h4l.5-2.5 1.5-1 2 .5 2-4-2-1v-2Z",wallet:"M4 6h14v12H4V6Zm14 4h3v4h-3",menu:"M4 7h16M4 12h16M4 17h16",close:"m6 6 12 12M18 6 6 18",down:"m8 10 4 4 4-4",route:"M6 5h5a3 3 0 0 1 3 3v8m-3-3 3 3 3-3M6 5l3-3M6 5l3 3",offline:"M3 3l18 18M8 8a7 7 0 0 1 10 1m-13 3a10 10 0 0 1 2-2m3 5a3 3 0 0 1 4 0m-2 4h.01",security:"M12 3 5 6v5c0 4.6 3 8 7 10 4-2 7-5.4 7-10V6l-7-3Zm-3 9 2 2 4-5",warning:"M12 3 2 21h20L12 3Zm0 6v5m0 3h.01",search:"m21 21-4.3-4.3M19 11a8 8 0 1 1-16 0 8 8 0 0 1 16 0Z",chevron:"m9 18 6-6-6-6",info:"M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20Zm0-11v6m0-10h.01"};return <svg viewBox="0 0 24 24" aria-hidden="true"><path d={paths[name]||paths.info}/></svg>}
