import type { Locale } from "./types";
const en = {
  swap:"Swap",pools:"Pools",positions:"My Positions",explore:"Explore",analytics:"Analytics",governance:"Governance",docs:"Docs",settings:"Settings",
  testnet:"Testnet Preview",connect:"Connect Wallet",wrongNetwork:"Wrong network",from:"You pay",to:"You receive",selectToken:"Select token",amount:"Amount",review:"Review swap",noRoute:"No executable route",routeHint:"Choose two supported tokens and enter an amount to request a live quote.",
  liveOnly:"Only indexed YNX Testnet events are shown. No estimated TVL, APY, volume, or users.",pool:"Pool",reserves:"Reserves",updated:"Updated",emptyPools:"No verified pools indexed yet",emptyPositions:"Connect YNX Wallet to view positions",emptyEvents:"No DEX transactions indexed yet",retry:"Retry",offline:"Offline — cached shell only",stale:"Data may be stale",source:"Source",status:"Status",indexed:"Indexed events",latestBlock:"Latest block",language:"Language",appearance:"Appearance",system:"System",light:"Light",dark:"Dark",highImpact:"High price impact",deadline:"Deadline",slippage:"Slippage",fees:"Fees",minimum:"Minimum received",gas:"Gas estimate",contract:"Contract",cancel:"Cancel",confirmWallet:"Continue in YNX Wallet",unavailable:"Unavailable",centralPending:"Central Wallet registry is not integrated. Connection fails closed until the canonical verifier accepts this DEX client.",readOnly:"Read-only",security:"Security",network:"YNX Testnet · Chain 6423",back:"Back",details:"Details",protocol:"Constant product · 0.30%",governanceText:"Pool code is immutable. Token support and protocol fee recipient changes use a public two-day delay.",docsText:"Review swaps carefully. Slippage and deadlines limit execution; they do not eliminate MEV or token risk.",search:"Search pools or transactions",menu:"Menu",close:"Close"
};
type Catalog=typeof en;
const override=(values:Partial<Catalog>):Catalog=>({...en,...values});
export const catalogs:Record<Locale,Catalog>={
 en,
 "zh-CN":override({swap:"兑换",pools:"资金池",positions:"我的仓位",explore:"探索",analytics:"分析",governance:"治理",docs:"文档",settings:"设置",testnet:"测试网预览",connect:"连接钱包",from:"支付",to:"收到",review:"检查兑换",noRoute:"没有可执行路径",liveOnly:"仅显示已索引的 YNX 测试网事件，不估算 TVL、APY、交易量或用户数。",emptyPools:"尚未索引到已验证资金池",emptyPositions:"连接 YNX Wallet 查看仓位",emptyEvents:"尚未索引到 DEX 交易",retry:"重试",offline:"离线——仅缓存应用外壳",stale:"数据可能已过期",language:"语言",appearance:"外观",light:"浅色",dark:"深色",centralPending:"中央 Wallet registry 尚未集成。在 canonical verifier 接受该 DEX client 前，连接会失败关闭。",network:"YNX 测试网 · 链 6423",back:"返回",details:"详情"}),
 "zh-TW":override({swap:"兌換",pools:"資金池",positions:"我的部位",explore:"探索",analytics:"分析",governance:"治理",docs:"文件",settings:"設定",testnet:"測試網預覽",connect:"連接錢包",from:"支付",to:"收到",review:"檢查兌換",noRoute:"沒有可執行路徑",emptyPools:"尚未索引已驗證資金池",emptyPositions:"連接 YNX Wallet 查看部位",retry:"重試",language:"語言",appearance:"外觀",back:"返回"}),
 ja:override({swap:"スワップ",pools:"プール",positions:"ポジション",explore:"探索",analytics:"分析",governance:"ガバナンス",docs:"ドキュメント",settings:"設定",testnet:"テストネットプレビュー",connect:"ウォレット接続",from:"支払い",to:"受け取り",review:"スワップを確認",noRoute:"実行可能なルートがありません",emptyPools:"検証済みプールはまだありません",emptyPositions:"YNX Wallet を接続してください",retry:"再試行",language:"言語",appearance:"外観",back:"戻る"}),
 ko:override({swap:"스왑",pools:"풀",positions:"내 포지션",explore:"탐색",analytics:"분석",governance:"거버넌스",docs:"문서",settings:"설정",testnet:"테스트넷 미리보기",connect:"지갑 연결",from:"지불",to:"수령",review:"스왑 검토",noRoute:"실행 가능한 경로 없음",emptyPools:"검증된 풀이 아직 없습니다",emptyPositions:"YNX Wallet을 연결하세요",retry:"다시 시도",language:"언어",appearance:"화면",back:"뒤로"}),
 es:override({swap:"Intercambiar",pools:"Fondos",positions:"Mis posiciones",explore:"Explorar",analytics:"Análisis",governance:"Gobernanza",docs:"Documentos",settings:"Ajustes",connect:"Conectar cartera",from:"Pagas",to:"Recibes",review:"Revisar intercambio",noRoute:"No hay ruta ejecutable",emptyPools:"Aún no hay fondos verificados",retry:"Reintentar",language:"Idioma",appearance:"Apariencia",back:"Atrás"}),
 fr:override({swap:"Échanger",pools:"Pools",positions:"Mes positions",explore:"Explorer",analytics:"Analyses",governance:"Gouvernance",docs:"Documentation",settings:"Réglages",connect:"Connecter le portefeuille",from:"Vous payez",to:"Vous recevez",review:"Vérifier l’échange",noRoute:"Aucune route exécutable",emptyPools:"Aucun pool vérifié indexé",retry:"Réessayer",language:"Langue",appearance:"Apparence",back:"Retour"}),
 de:override({swap:"Tauschen",pools:"Pools",positions:"Meine Positionen",explore:"Entdecken",analytics:"Analyse",governance:"Governance",docs:"Dokumentation",settings:"Einstellungen",connect:"Wallet verbinden",from:"Sie zahlen",to:"Sie erhalten",review:"Tausch prüfen",noRoute:"Keine ausführbare Route",emptyPools:"Noch keine verifizierten Pools",retry:"Erneut versuchen",language:"Sprache",appearance:"Darstellung",back:"Zurück"}),
 pt:override({swap:"Trocar",pools:"Pools",positions:"Minhas posições",explore:"Explorar",analytics:"Análises",governance:"Governança",docs:"Documentos",settings:"Definições",connect:"Ligar carteira",from:"Paga",to:"Recebe",review:"Rever troca",noRoute:"Sem rota executável",retry:"Tentar novamente",language:"Idioma",appearance:"Aparência",back:"Voltar"}),
 ru:override({swap:"Обмен",pools:"Пулы",positions:"Мои позиции",explore:"Обзор",analytics:"Аналитика",governance:"Управление",docs:"Документы",settings:"Настройки",connect:"Подключить кошелёк",from:"Вы платите",to:"Вы получаете",review:"Проверить обмен",noRoute:"Нет доступного маршрута",retry:"Повторить",language:"Язык",appearance:"Оформление",back:"Назад"}),
 ar:override({swap:"مبادلة",pools:"المجمعات",positions:"مراكزي",explore:"استكشاف",analytics:"التحليلات",governance:"الحوكمة",docs:"المستندات",settings:"الإعدادات",testnet:"معاينة شبكة الاختبار",connect:"ربط المحفظة",from:"أنت تدفع",to:"أنت تستلم",review:"مراجعة المبادلة",noRoute:"لا يوجد مسار قابل للتنفيذ",routeHint:"اختر أصلين مدعومين وأدخل المبلغ لطلب عرض سعر مباشر.",liveOnly:"تُعرض فقط أحداث شبكة اختبار YNX المفهرسة. لا توجد تقديرات لقيمة السيولة أو العائد أو الحجم أو عدد المستخدمين.",emptyPools:"لا توجد مجمعات موثقة بعد",emptyPositions:"اربط محفظة YNX لعرض المراكز",emptyEvents:"لا توجد معاملات DEX مفهرسة بعد",retry:"إعادة المحاولة",offline:"غير متصل — واجهة التطبيق المخزنة فقط",stale:"قد تكون البيانات قديمة",source:"المصدر",status:"الحالة",indexed:"الأحداث المفهرسة",latestBlock:"أحدث كتلة",language:"اللغة",appearance:"المظهر",system:"النظام",light:"فاتح",dark:"داكن",fees:"الرسوم",minimum:"الحد الأدنى للاستلام",slippage:"الانزلاق",deadline:"المهلة",gas:"تقدير رسوم الشبكة",contract:"العقد",unavailable:"غير متاح",centralPending:"لم يُدمج سجل المحفظة المركزي بعد. يُرفض الاتصال بأمان حتى يقبل المدقق الرسمي عميل DEX هذا.",readOnly:"للقراءة فقط",security:"الأمان",network:"شبكة اختبار YNX · السلسلة 6423",back:"رجوع",details:"التفاصيل",docsText:"راجع المبادلة بعناية. يحد الانزلاق والموعد النهائي من التنفيذ، لكنهما لا يزيلان مخاطر MEV أو مخاطر الأصل.",governanceText:"رمز المجمع غير قابل للتغيير. تخضع تغييرات دعم الأصول ومستلم رسوم البروتوكول لتأخير علني مدته يومان.",menu:"القائمة",close:"إغلاق"}),
 id:override({swap:"Tukar",pools:"Pool",positions:"Posisi saya",explore:"Jelajahi",analytics:"Analitik",governance:"Tata kelola",docs:"Dokumen",settings:"Pengaturan",connect:"Hubungkan dompet",from:"Anda bayar",to:"Anda terima",review:"Tinjau pertukaran",noRoute:"Tidak ada rute yang dapat dijalankan",retry:"Coba lagi",language:"Bahasa",appearance:"Tampilan",back:"Kembali"})
};
export const locales=Object.keys(catalogs) as Locale[];
