export type ProviderStatus="available"|"unavailable"|"degraded";
export type RiskContext={pair:string;amount:string;routePools:string[];minimumReceived:string;priceImpactBps:number;slippageBps:number;deadlineSeconds:number};
export type RiskRequest={schemaVersion:1;productId:"ynx-dex";chainId:6423;purpose:"swap-risk-explanation";provider:string;model:string;selectedContext:(keyof RiskContext)[];context:Partial<RiskContext>};
export type AuditAction="previewed"|"permission-granted"|"started"|"cancelled"|"failed"|"reviewed"|"applied"|"rejected";
export type AuditEntry={sequence:number;timestamp:string;action:AuditAction;requestDigest:string;detail:string;previousHash:string;hash:string};

export class RiskAssistantError extends Error{constructor(public code:string,message:string){super(message);this.name="RiskAssistantError"}}

const allowedContext:(keyof RiskContext)[]=["pair","amount","routePools","minimumReceived","priceImpactBps","slippageBps","deadlineSeconds"];
const hex=(bytes:ArrayBuffer)=>Array.from(new Uint8Array(bytes),value=>value.toString(16).padStart(2,"0")).join("");
const digest=async(value:string)=>hex(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)));
const canonical=(value:unknown):string=>{if(value===null||typeof value!=="object")return JSON.stringify(value);if(Array.isArray(value))return `[${value.map(canonical).join(",")}]`;return `{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>`${JSON.stringify(key)}:${canonical(item)}`).join(",")}}`};

export function buildRiskRequest(input:{context:RiskContext;selectedContext:(keyof RiskContext)[];provider:string;model:string}):RiskRequest{
 if(!input.provider.trim()||!input.model.trim())throw new RiskAssistantError("INVALID_PROVIDER","Provider and model identity are required.");
 const selected=[...new Set(input.selectedContext)];if(selected.length===0||selected.some(key=>!allowedContext.includes(key)))throw new RiskAssistantError("INVALID_CONTEXT","Select at least one supported context field.");
 const context:Partial<RiskContext>={};for(const key of selected)(context as Record<string,unknown>)[key]=input.context[key];
 return {schemaVersion:1,productId:"ynx-dex",chainId:6423,purpose:"swap-risk-explanation",provider:input.provider,model:input.model,selectedContext:selected,context};
}

export async function streamRiskExplanation(input:{endpoint:string;request:RiskRequest;providerStatus:ProviderStatus;permission:{granted:boolean;scope:string};signal?:AbortSignal;timeoutMs?:number;onDelta?:(text:string)=>void;fetcher?:typeof fetch}):Promise<{text:string;costMicros:number|null}>{
 if(!input.endpoint.trim()||input.providerStatus==="unavailable")throw new RiskAssistantError("PROVIDER_UNAVAILABLE","AI provider is unavailable.");
 const base=globalThis.location?.origin||"https://ynx-dex.invalid";const endpointURL=new URL(input.endpoint,base);if(endpointURL.origin!==base)throw new RiskAssistantError("CROSS_ORIGIN_ENDPOINT","AI provider must use the same-origin canonical gateway.");
 if(input.providerStatus==="degraded")throw new RiskAssistantError("PROVIDER_DEGRADED","AI provider is degraded; retry later.");
 if(!input.permission.granted||input.permission.scope!=="dex:risk-explanation")throw new RiskAssistantError("PERMISSION_DENIED","Explicit risk-explanation permission is required.");
 const timeoutMs=input.timeoutMs??30_000;if(!Number.isInteger(timeoutMs)||timeoutMs<100||timeoutMs>60_000)throw new RiskAssistantError("INVALID_TIMEOUT","AI timeout must be 100..60000 ms.");const timeout=AbortSignal.timeout(timeoutMs);const signal=input.signal?AbortSignal.any([input.signal,timeout]):timeout;
 const fetcher=input.fetcher||fetch;let response:Response;
 try{response=await fetcher(`${endpointURL.href.replace(/\/$/,"")}/v1/explanations:stream`,{method:"POST",credentials:"omit",headers:{"Content-Type":"application/json","Accept":"application/x-ndjson","X-YNX-AI-Permission":"dex:risk-explanation"},body:JSON.stringify(input.request),signal})}catch(error){if(input.signal?.aborted)throw new RiskAssistantError("CANCELLED","Explanation was cancelled.");if(timeout.aborted)throw new RiskAssistantError("TIMEOUT","AI provider timed out.");if(error instanceof DOMException&&error.name==="AbortError")throw new RiskAssistantError("INTERRUPTED","AI stream was interrupted.");throw new RiskAssistantError("INTERRUPTED","AI request was interrupted.")}
 if(response.status===429)throw new RiskAssistantError("RATE_LIMITED","AI provider rate limit reached.");if(!response.ok||!response.body)throw new RiskAssistantError("PROVIDER_ERROR",`AI provider returned ${response.status}.`);if(!response.headers.get("Content-Type")?.toLowerCase().startsWith("application/x-ndjson"))throw new RiskAssistantError("INVALID_STREAM","AI provider returned the wrong content type.");
 const reader=response.body.getReader();const decoder=new TextDecoder();let pending="",text="",costMicros:number|null=null,done=false;
 const consume=(line:string)=>{if(!line.trim())return;let value:unknown;try{value=JSON.parse(line)}catch{throw new RiskAssistantError("INVALID_STREAM","AI stream contained invalid JSON.")}if(!value||typeof value!=="object"||Array.isArray(value))throw new RiskAssistantError("INVALID_STREAM","AI stream event is invalid.");const event=value as Record<string,unknown>;const keys=Object.keys(event).sort().join("|");if(event.type==="delta"&&keys==="text|type"&&typeof event.text==="string"&&event.text.length>0){text+=event.text;if(text.length>20_000)throw new RiskAssistantError("OUTPUT_TOO_LARGE","AI explanation exceeded the safe limit.");input.onDelta?.(event.text)}else if(event.type==="usage"&&keys==="costMicros|type"&&Number.isSafeInteger(event.costMicros)&&Number(event.costMicros)>=0){costMicros=Number(event.costMicros)}else if(event.type==="done"&&keys==="type"){done=true}else throw new RiskAssistantError("INVALID_STREAM","AI stream event schema is invalid.")};
 try{for(;;){const part=await reader.read();pending+=decoder.decode(part.value,{stream:!part.done});let newline;while((newline=pending.indexOf("\n"))>=0){consume(pending.slice(0,newline));pending=pending.slice(newline+1)}if(part.done)break}if(pending.trim())consume(pending)}catch(error){if(input.signal?.aborted)throw new RiskAssistantError("CANCELLED","Explanation was cancelled.");if(timeout.aborted)throw new RiskAssistantError("TIMEOUT","AI provider timed out.");throw error}
 if(!done||!text.trim())throw new RiskAssistantError("EMPTY_RESPONSE","AI provider returned no completed explanation.");return {text:text.trim(),costMicros};
}

export async function requestDigest(request:RiskRequest){return digest(canonical(request))}
const auditQueues=new WeakMap<Storage,Map<string,Promise<unknown>>>();
export async function appendRiskAudit(storage:Storage,key:string,input:Omit<AuditEntry,"sequence"|"timestamp"|"previousHash"|"hash">):Promise<AuditEntry>{let queues=auditQueues.get(storage);if(!queues){queues=new Map();auditQueues.set(storage,queues)}const previous=queues.get(key)??Promise.resolve();const operation=previous.catch(()=>undefined).then(async()=>{const entries=readRiskAudit(storage,key);if(!await verifyEntries(entries))throw new RiskAssistantError("AUDIT_CORRUPT","Risk audit integrity check failed.");const previousHash=entries.at(-1)?.hash||"0".repeat(64);const base={sequence:entries.length+1,timestamp:new Date().toISOString(),...input,previousHash};const entry={...base,hash:await digest(canonical(base))};storage.setItem(key,JSON.stringify([...entries,entry]));return entry});queues.set(key,operation);return operation}
export function readRiskAudit(storage:Storage,key:string):AuditEntry[]{const raw=storage.getItem(key);if(!raw)return[];const value=JSON.parse(raw);if(!Array.isArray(value))throw new RiskAssistantError("AUDIT_CORRUPT","Risk audit is not an array.");return value as AuditEntry[]}
async function verifyEntries(entries:AuditEntry[]):Promise<boolean>{let previous="0".repeat(64);for(let index=0;index<entries.length;index++){const entry=entries[index];if(!entry||typeof entry!=="object")return false;const {hash,...base}=entry;if(base.sequence!==index+1||base.previousHash!==previous||typeof hash!=="string"||hash!==await digest(canonical(base)))return false;previous=hash}return true}
export async function verifyRiskAudit(storage:Storage,key:string):Promise<boolean>{try{return verifyEntries(readRiskAudit(storage,key))}catch{return false}}
