import {describe,expect,it,vi} from "vitest";
import {appendRiskAudit,buildRiskRequest,RiskAssistantError,streamRiskExplanation,verifyRiskAudit} from "./riskAssistant";

const context={pair:"T0 / T1",amount:"1 T0",routePools:["0x0000000000000000000000000000000000000011"],minimumReceived:"1.9 T1",priceImpactBps:12,slippageBps:50,deadlineSeconds:600};
const request=()=>buildRiskRequest({context,selectedContext:["pair","amount","routePools","minimumReceived","priceImpactBps","slippageBps","deadlineSeconds"],provider:"canonical-ai",model:"risk-explainer-v1"});
const response=(chunks:string[],status=200)=>new Response(new ReadableStream({start(controller){for(const chunk of chunks)controller.enqueue(new TextEncoder().encode(chunk));controller.close()}}),{status,headers:{"Content-Type":"application/x-ndjson"}});

describe("risk assistant boundary",()=>{
 it("streams provider output and reports actual usage cost",async()=>{const onDelta=vi.fn();const result=await streamRiskExplanation({endpoint:"/ai",request:request(),providerStatus:"available",permission:{granted:true,scope:"dex:risk-explanation"},onDelta,fetcher:vi.fn(async()=>response(['{"type":"delta","text":"Check "}\n{"type":"delta","text":"impact."}\n','{"type":"usage","costMicros":12}\n{"type":"done"}\n']))});expect(result).toEqual({text:"Check impact.",costMicros:12});expect(onDelta).toHaveBeenCalledTimes(2)});
 it.each([
  ["unavailable",{endpoint:"",providerStatus:"unavailable",permission:{granted:true,scope:"dex:risk-explanation"}},"PROVIDER_UNAVAILABLE"],
  ["permission",{endpoint:"/ai",providerStatus:"available",permission:{granted:false,scope:"dex:risk-explanation"}},"PERMISSION_DENIED"],
 ] as const)("fails honestly for %s",async(_name,partial,code)=>{await expect(streamRiskExplanation({...partial,request:request()})).rejects.toMatchObject({code})});
 it("rejects 429, empty, invalid, and cancelled streams",async()=>{const base={endpoint:"/ai",request:request(),providerStatus:"available" as const,permission:{granted:true,scope:"dex:risk-explanation"}};await expect(streamRiskExplanation({...base,fetcher:vi.fn(async()=>response([],429))})).rejects.toMatchObject({code:"RATE_LIMITED"});await expect(streamRiskExplanation({...base,fetcher:vi.fn(async()=>response(['{"type":"done"}\n']))})).rejects.toMatchObject({code:"EMPTY_RESPONSE"});await expect(streamRiskExplanation({...base,fetcher:vi.fn(async()=>response(['{"type":"success","text":"canned"}\n']))})).rejects.toMatchObject({code:"INVALID_STREAM"});const controller=new AbortController();const fetcher=vi.fn(async(_url:RequestInfo|URL,init?:RequestInit)=>{controller.abort();throw new DOMException("aborted","AbortError")});await expect(streamRiskExplanation({...base,signal:controller.signal,fetcher})).rejects.toMatchObject({code:"CANCELLED"})});
 it("fails closed on timeout and wrong stream media type",async()=>{const base={endpoint:"/ai",request:request(),providerStatus:"available" as const,permission:{granted:true,scope:"dex:risk-explanation"}};const hanging=vi.fn((_url:RequestInfo|URL,init?:RequestInit)=>new Promise<Response>((_resolve,reject)=>init?.signal?.addEventListener("abort",()=>reject(new DOMException("timeout","AbortError")))));await expect(streamRiskExplanation({...base,timeoutMs:100,fetcher:hanging})).rejects.toMatchObject({code:"TIMEOUT"});const wrong=vi.fn(async()=>new Response('{"type":"done"}\n',{status:200,headers:{"Content-Type":"application/json"}}));await expect(streamRiskExplanation({...base,fetcher:wrong})).rejects.toMatchObject({code:"INVALID_STREAM"})});
 it("rejects a cross-origin provider endpoint",async()=>{await expect(streamRiskExplanation({endpoint:"https://ai.test",request:request(),providerStatus:"available",permission:{granted:true,scope:"dex:risk-explanation"}})).rejects.toMatchObject({code:"CROSS_ORIGIN_ENDPOINT"})});
 it("maintains a persistent hash-chained audit and detects tampering",async()=>{const storage=new MapStorage();await appendRiskAudit(storage,"audit",{action:"previewed",requestDigest:"a".repeat(64),detail:"selected context"});await appendRiskAudit(storage,"audit",{action:"rejected",requestDigest:"a".repeat(64),detail:"user rejected"});expect(await verifyRiskAudit(storage,"audit")).toBe(true);storage.setItem("audit",storage.getItem("audit")!.replace("user rejected","applied without review"));expect(await verifyRiskAudit(storage,"audit")).toBe(false)});
 it("rejects context expansion and missing provider identity",()=>{expect(()=>buildRiskRequest({context,selectedContext:[],provider:"p",model:"m"})).toThrow(RiskAssistantError);expect(()=>buildRiskRequest({context,selectedContext:["pair"],provider:"",model:"m"})).toThrow(RiskAssistantError)});
});

class MapStorage implements Storage{private values=new Map<string,string>();get length(){return this.values.size}clear(){this.values.clear()}getItem(key:string){return this.values.get(key)??null}key(index:number){return [...this.values.keys()][index]??null}removeItem(key:string){this.values.delete(key)}setItem(key:string,value:string){this.values.set(key,value)}}
