const exactKeys=["version","nonce","chainId","requestingProduct","productClientId","bundleId","productDeviceAlgorithm","productDeviceKey","callback","scopes","purpose","issuedAt","expiresAt"].sort().join("|");
const scopes=["account:read","dex:positions:read","dex:transaction:request"] as const;
export type WalletRequest={version:"1";nonce:string;chainId:"ynx_6423-1";requestingProduct:"dex";productClientId:"ynx-dex-web-v1";bundleId:"com.ynxweb4.dex.web";productDeviceAlgorithm:"p256-sha256";productDeviceKey:string;callback:"https://dex.ynxweb4.com/wallet-auth/callback";scopes:typeof scopes;purpose:string;issuedAt:string;expiresAt:string};
export class WalletRequestError extends Error{constructor(public code:string,message:string){super(message)}}
export function buildWalletRequest(input:{nonce:string;productDeviceKey:string;now?:Date}):WalletRequest{
 const now=input.now||new Date();if(!/^nonce_[A-Za-z0-9_-]{24,96}$/.test(input.nonce))throw new WalletRequestError("INVALID_NONCE","nonce is invalid");
 if(!/^[A-Za-z0-9_-]{44}$/.test(input.productDeviceKey))throw new WalletRequestError("INVALID_DEVICE_KEY","compressed P-256 key is invalid");
 const issuedAt=now.toISOString();const expiresAt=new Date(now.valueOf()+5*60_000).toISOString();
 return Object.freeze({version:"1",nonce:input.nonce,chainId:"ynx_6423-1",requestingProduct:"dex",productClientId:"ynx-dex-web-v1",bundleId:"com.ynxweb4.dex.web",productDeviceAlgorithm:"p256-sha256",productDeviceKey:input.productDeviceKey,callback:"https://dex.ynxweb4.com/wallet-auth/callback",scopes,purpose:"Connect this YNX account to YNX DEX on this device to read positions and request transaction reviews. YNX DEX cannot sign transactions.",issuedAt,expiresAt});
}
export function walletDeepLink(request:WalletRequest){assertWalletRequest(request);const json=canonicalJSON(request);const encoded=base64url(new TextEncoder().encode(json));return `ynxwallet://authorize?request=${encoded}`}
export function assertWalletRequest(value:WalletRequest){if(!value||typeof value!=="object"||Object.keys(value).sort().join("|")!==exactKeys)throw new WalletRequestError("UNKNOWN_OR_MISSING_FIELD","request schema mismatch");const expected=buildWalletRequest({nonce:value.nonce,productDeviceKey:value.productDeviceKey,now:new Date(value.issuedAt)});for(const key of exactKeys.split("|")){if(JSON.stringify(value[key as keyof WalletRequest])!==JSON.stringify(expected[key as keyof WalletRequest]))throw new WalletRequestError("BINDING_MISMATCH",`${key} does not match DEX registry`)}return value}
function canonicalJSON(value:unknown):string{if(value===null||typeof value!=="object")return JSON.stringify(value);if(Array.isArray(value))return `[${value.map(canonicalJSON).join(",")}]`;return `{${Object.keys(value as object).sort().map(key=>`${JSON.stringify(key)}:${canonicalJSON((value as Record<string,unknown>)[key])}`).join(",")}}`}
function base64url(bytes:Uint8Array){let binary="";for(const byte of bytes)binary+=String.fromCharCode(byte);return btoa(binary).replaceAll("+","-").replaceAll("/","_").replace(/=+$/g,"")}
