import {describe,expect,it,vi} from 'vitest';
import {beginWalletAuthorization,connectMetaMask,configureDexPrivateConnection,dexProductSessionGatewayOrigin,disconnectStandardWallet,observeStandardWallet,restoreStandardWallet,standardWalletDetails,WalletRequestError,YNX_EVM_CHAIN} from './wallet';

describe('DEX Wallet Product Session v2 adapter',()=>{
  it('keeps Standard EIP-1193 separate and adds YNX Testnet when required',async()=>{const calls:string[]=[];const provider={request:vi.fn(async({method}:{method:string})=>{calls.push(method);if(method==='wallet_switchEthereumChain'&&calls.length===1)throw Object.assign(new Error('unknown chain'),{code:4902});if(method==='eth_chainId')return YNX_EVM_CHAIN.chainId;if(method==='eth_requestAccounts')return [`0x${'A'.repeat(40)}`];return null;})};await expect(connectMetaMask(provider)).resolves.toBe(`0x${'a'.repeat(40)}`);expect(calls).toEqual(['wallet_switchEthereumChain','wallet_addEthereumChain','wallet_switchEthereumChain','eth_chainId','eth_requestAccounts']);});
  it('keeps Web provider discovery available without a Product Session capability',async()=>{await expect(beginWalletAuthorization()).resolves.toMatchObject({status:'unsupported'});});
  it('accepts only a capability surface without endpoint, callback, origin or session injection',()=>{expect(typeof configureDexPrivateConnection).toBe('function');expect(dexProductSessionGatewayOrigin()).toBeNull();expect(new WalletRequestError('x','x').code).toBe('x');});
  it('restores only an already-approved account without requesting accounts again',async()=>{const calls:string[]=[];const provider={request:vi.fn(async({method}:{method:string})=>{calls.push(method);return method==='eth_accounts'?[`0x${'D'.repeat(40)}`]:method==='eth_chainId'?YNX_EVM_CHAIN.chainId:null;})};await expect(restoreStandardWallet(provider,'ynx-wallet')).resolves.toBe(`0x${'d'.repeat(40)}`);expect(calls).toEqual(['eth_accounts','eth_chainId']);expect(standardWalletDetails()).toMatchObject({status:'connected',providerKind:'ynx-wallet',chooserOpen:false});disconnectStandardWallet();});
  it('keeps discovered YNX Wallet and MetaMask providers distinct before any account request',async()=>{const ynx={isYNXWallet:true,providerInfo:{rdns:'com.ynx.wallet'},request:vi.fn()},metaMask={isMetaMask:true,providerInfo:{rdns:'io.metamask'},request:vi.fn()},scope={ethereum:{providers:[ynx,metaMask]}};configureDexPrivateConnection({device:{key:'Am_wO5SSQc4drdQ1GeaWDgqFtBppoFwygQOqK84VlMoW'},storage:{securityLevel:'os-protected',get:()=>null,set:()=>undefined,remove:()=>undefined},scope});const launch=await beginWalletAuthorization();expect(launch.status).toBe('provider-ready');expect(launch.providerKind).toBe('ynx-wallet');expect(launch.providers.ynxWallet).toBe(ynx);expect(launch.providers.metaMask).toBe(metaMask);expect(ynx.request).not.toHaveBeenCalled();expect(metaMask.request).not.toHaveBeenCalled();});
  it('reflects account, chain and disconnect provider events without a new account request',async()=>{const handlers=new Map<string,(value?:unknown)=>void>(),provider={request:vi.fn(async({method}:{method:string})=>method==='wallet_switchEthereumChain'||method==='eth_chainId'?YNX_EVM_CHAIN.chainId:method==='eth_requestAccounts'?[`0x${'B'.repeat(40)}`]:null),on:vi.fn((event:string,listener:(value?:unknown)=>void)=>handlers.set(event,listener)),removeListener:vi.fn()};await connectMetaMask(provider);const seen:string[]=[];const stop=observeStandardWallet(provider,state=>seen.push(state.status));handlers.get('accountsChanged')?.([`0x${'C'.repeat(40)}`]);expect(standardWalletDetails().account).toBe(`0x${'c'.repeat(40)}`);handlers.get('chainChanged')?.('0x1');expect(standardWalletDetails().status).toBe('wrong-chain');handlers.get('disconnect')?.();expect(standardWalletDetails().status).toBe('disconnected');expect(seen).toEqual(['connected','wrong-chain','disconnected']);stop();disconnectStandardWallet();});
});
