export const LOCALES = Object.freeze([
  ["en", "English"], ["zh-CN", "简体中文"], ["zh-TW", "繁體中文"], ["ja", "日本語"],
  ["ko", "한국어"], ["es", "Español"], ["fr", "Français"], ["de", "Deutsch"],
  ["pt", "Português"], ["ru", "Русский"], ["ar", "العربية"], ["id", "Bahasa Indonesia"],
]);

const en = {
  eyebrow: "Wallet companion", title: "Connect to YNX Testnet", intro: "Use an installed wallet. This app never receives your recovery phrase or private key.",
  detected: "YNX Wallet detected", connectYNX: "Open YNX Wallet", download: "Download YNX Wallet", metamask: "Use MetaMask", unavailable: "No supported wallet detected",
  add: "Add YNX Testnet", switch: "Switch network", sign: "Sign message", send: "Send transaction", message: "Message", recipient: "Recipient", value: "Value (hex wei)", data: "Data (hex)",
  connected: "Connected", disconnected: "Not connected", rpcCheck: "The selected wallet confirms the active network. Browser RPC probes are diagnostic only.", testnet: "Testnet assets have no represented monetary value.",
  light: "Light", dark: "Dark", language: "Language", status: "Status", txHash: "Transaction hash", signature: "Signature", working: "Waiting for wallet approval…", requestFailed:"The request failed closed. No wallet state was changed.", walletConnection:"Wallet connection", walletActions:"Wallet actions", preferencesRejected: "Saved display preferences were invalid or stale and were reset safely.", disconnect:"Disconnect", switchAccount:"Switch account", metamaskDetected:"MetaMask provider detected", providerNotInjected:"No wallet provider was detected. Enable an installed wallet and retry.", walletLocked:"The installed wallet is locked. Unlock it, then retry.", siteAccessDenied:"Wallet site access is denied for this HTTPS DApp. Allow access, then retry.",
};

const overrides = {
  "zh-CN": {eyebrow:"钱包伴侣",title:"连接 YNX 测试网",intro:"使用已安装的钱包。本应用绝不会获取助记词或私钥。",detected:"检测到 YNX Wallet",connectYNX:"打开 YNX Wallet",download:"下载 YNX Wallet",metamask:"使用 MetaMask",unavailable:"未检测到支持的钱包",add:"添加 YNX 测试网",switch:"切换网络",sign:"签名消息",send:"发送交易",message:"消息",recipient:"接收地址",value:"数值（十六进制 wei）",data:"数据（十六进制）",connected:"已连接",disconnected:"未连接",rpcCheck:"改变网络或交易前必须完成实时 RPC 验证。",testnet:"测试网资产不代表任何现实价值。",light:"浅色",dark:"深色",language:"语言",status:"状态",txHash:"交易哈希",signature:"签名",working:"等待钱包批准…",requestFailed:"请求已失败关闭，钱包状态没有改变。",walletConnection:"钱包连接",walletActions:"钱包操作",preferencesRejected:"已保存的显示偏好无效或已过期，已安全重置。",disconnect:"断开连接",switchAccount:"切换账户",metamaskDetected:"已检测到 MetaMask provider",providerNotInjected:"钱包 provider 尚未注入。请解锁或启用扩展、授予本站访问权限后重试。"},
  "zh-TW": {eyebrow:"錢包伴侶",title:"連接 YNX 測試網",intro:"使用已安裝的錢包。本應用絕不會取得助記詞或私鑰。",detected:"偵測到 YNX Wallet",connectYNX:"開啟 YNX Wallet",download:"下載 YNX Wallet",metamask:"使用 MetaMask",unavailable:"未偵測到支援的錢包",add:"加入 YNX 測試網",switch:"切換網路",sign:"簽署訊息",send:"傳送交易",message:"訊息",recipient:"接收地址",value:"數值（十六進位 wei）",data:"資料（十六進位）",connected:"已連線",disconnected:"未連線",rpcCheck:"變更網路或交易前必須完成即時 RPC 驗證。",testnet:"測試網資產不代表任何現實價值。",light:"淺色",dark:"深色",language:"語言",status:"狀態",txHash:"交易雜湊",signature:"簽章",working:"等待錢包核准…",requestFailed:"請求已失敗關閉，錢包狀態沒有變更。",walletConnection:"錢包連線",walletActions:"錢包操作",preferencesRejected:"已儲存的顯示偏好無效或已過期，已安全重設。",disconnect:"中斷連線",switchAccount:"切換帳戶",metamaskDetected:"已偵測到 MetaMask provider",providerNotInjected:"錢包 provider 尚未注入。請解鎖或啟用擴充功能、授予本站存取權後重試。"},
  ja: {eyebrow:"ウォレットコンパニオン",title:"YNXテストネットに接続",intro:"インストール済みウォレットを使用します。復元フレーズや秘密鍵は取得しません。",detected:"YNX Walletを検出",connectYNX:"YNX Walletを開く",download:"YNX Walletをダウンロード",metamask:"MetaMaskを使う",unavailable:"対応ウォレットがありません",add:"YNXテストネットを追加",switch:"ネットワークを切替",sign:"メッセージに署名",send:"取引を送信",message:"メッセージ",recipient:"送信先",value:"値（16進wei）",data:"データ（16進）",connected:"接続済み",disconnected:"未接続",rpcCheck:"チェーン変更や取引前にライブRPC検証が必要です。",testnet:"テストネット資産に現実の価値はありません。",light:"ライト",dark:"ダーク",language:"言語",status:"状態",txHash:"トランザクションハッシュ",signature:"署名",working:"ウォレットの承認待ち…",requestFailed:"リクエストは安全に失敗し、ウォレットの状態は変更されませんでした。",walletConnection:"ウォレット接続",walletActions:"ウォレット操作",preferencesRejected:"保存された表示設定が無効または期限切れのため、安全にリセットしました。"},
  ko: {eyebrow:"지갑 도우미",title:"YNX 테스트넷 연결",intro:"설치된 지갑을 사용합니다. 복구 문구나 개인 키를 받지 않습니다.",detected:"YNX Wallet 감지됨",connectYNX:"YNX Wallet 열기",download:"YNX Wallet 다운로드",metamask:"MetaMask 사용",unavailable:"지원 지갑 없음",add:"YNX 테스트넷 추가",switch:"네트워크 전환",sign:"메시지 서명",send:"거래 보내기",message:"메시지",recipient:"받는 주소",value:"값(16진수 wei)",data:"데이터(16진수)",connected:"연결됨",disconnected:"연결 안 됨",rpcCheck:"체인 변경이나 거래 전 실시간 RPC 검증이 필요합니다.",testnet:"테스트넷 자산은 실제 가치를 나타내지 않습니다.",light:"라이트",dark:"다크",language:"언어",status:"상태",txHash:"트랜잭션 해시",signature:"서명",working:"지갑 승인 대기 중…",requestFailed:"요청은 안전하게 실패했으며 지갑 상태는 변경되지 않았습니다.",walletConnection:"지갑 연결",walletActions:"지갑 작업",preferencesRejected:"저장된 표시 설정이 유효하지 않거나 오래되어 안전하게 초기화되었습니다."},
  es: {eyebrow:"Asistente de cartera",title:"Conectar a YNX Testnet",intro:"Usa una cartera instalada. La aplicación nunca recibe tu frase de recuperación ni clave privada.",detected:"YNX Wallet detectada",connectYNX:"Abrir YNX Wallet",download:"Descargar YNX Wallet",metamask:"Usar MetaMask",unavailable:"No se detectó una cartera compatible",add:"Añadir YNX Testnet",switch:"Cambiar red",sign:"Firmar mensaje",send:"Enviar transacción",message:"Mensaje",recipient:"Destinatario",value:"Valor (wei hexadecimal)",data:"Datos (hexadecimal)",connected:"Conectado",disconnected:"Sin conexión",rpcCheck:"Se exige verificar el RPC en vivo antes de cambiar la red o enviar.",testnet:"Los activos de Testnet no representan valor real.",light:"Claro",dark:"Oscuro",language:"Idioma",status:"Estado",txHash:"Hash de transacción",signature:"Firma",working:"Esperando aprobación…",requestFailed:"La solicitud se cerró con error y no se modificó el estado de la cartera.",walletConnection:"Conexión de cartera",walletActions:"Acciones de cartera",preferencesRejected:"Las preferencias de visualización guardadas no eran válidas o estaban obsoletas y se restablecieron de forma segura."},
  fr: {eyebrow:"Compagnon de portefeuille",title:"Se connecter au Testnet YNX",intro:"Utilisez un portefeuille installé. L’application ne reçoit jamais votre phrase de récupération ni votre clé privée.",detected:"YNX Wallet détecté",connectYNX:"Ouvrir YNX Wallet",download:"Télécharger YNX Wallet",metamask:"Utiliser MetaMask",unavailable:"Aucun portefeuille compatible détecté",add:"Ajouter le Testnet YNX",switch:"Changer de réseau",sign:"Signer le message",send:"Envoyer la transaction",message:"Message",recipient:"Destinataire",value:"Valeur (wei hexadécimal)",data:"Données (hexadécimal)",connected:"Connecté",disconnected:"Non connecté",rpcCheck:"Une vérification RPC en direct est requise avant toute modification ou tout envoi.",testnet:"Les actifs Testnet n’ont aucune valeur réelle représentée.",light:"Clair",dark:"Sombre",language:"Langue",status:"État",txHash:"Hachage de transaction",signature:"Signature",working:"En attente de l’approbation…",requestFailed:"La demande a échoué de manière sécurisée et l’état du portefeuille n’a pas été modifié.",walletConnection:"Connexion du portefeuille",walletActions:"Actions du portefeuille",preferencesRejected:"Les préférences d’affichage enregistrées étaient invalides ou obsolètes et ont été réinitialisées en toute sécurité."},
  de: {eyebrow:"Wallet-Begleiter",title:"Mit YNX Testnet verbinden",intro:"Verwenden Sie eine installierte Wallet. Die App erhält niemals Wiederherstellungsphrase oder privaten Schlüssel.",detected:"YNX Wallet erkannt",connectYNX:"YNX Wallet öffnen",download:"YNX Wallet laden",metamask:"MetaMask verwenden",unavailable:"Keine unterstützte Wallet erkannt",add:"YNX Testnet hinzufügen",switch:"Netzwerk wechseln",sign:"Nachricht signieren",send:"Transaktion senden",message:"Nachricht",recipient:"Empfänger",value:"Wert (Hex-wei)",data:"Daten (Hex)",connected:"Verbunden",disconnected:"Nicht verbunden",rpcCheck:"Vor Netzwerk- oder Transaktionsänderungen ist eine Live-RPC-Prüfung erforderlich.",testnet:"Testnet-Assets stellen keinen realen Wert dar.",light:"Hell",dark:"Dunkel",language:"Sprache",status:"Status",txHash:"Transaktionshash",signature:"Signatur",working:"Warte auf Wallet-Freigabe…",requestFailed:"Die Anfrage wurde sicher abgebrochen; der Wallet-Status blieb unverändert.",walletConnection:"Wallet-Verbindung",walletActions:"Wallet-Aktionen",preferencesRejected:"Gespeicherte Anzeigeeinstellungen waren ungültig oder veraltet und wurden sicher zurückgesetzt."},
  pt: {eyebrow:"Assistente da carteira",title:"Conectar à YNX Testnet",intro:"Use uma carteira instalada. O app nunca recebe sua frase de recuperação ou chave privada.",detected:"YNX Wallet detectada",connectYNX:"Abrir YNX Wallet",download:"Baixar YNX Wallet",metamask:"Usar MetaMask",unavailable:"Nenhuma carteira compatível detectada",add:"Adicionar YNX Testnet",switch:"Trocar rede",sign:"Assinar mensagem",send:"Enviar transação",message:"Mensagem",recipient:"Destinatário",value:"Valor (wei hexadecimal)",data:"Dados (hexadecimal)",connected:"Conectado",disconnected:"Desconectado",rpcCheck:"A verificação RPC ao vivo é obrigatória antes de mudanças ou transações.",testnet:"Ativos de Testnet não representam valor real.",light:"Claro",dark:"Escuro",language:"Idioma",status:"Estado",txHash:"Hash da transação",signature:"Assinatura",working:"Aguardando aprovação…",requestFailed:"A solicitação falhou de forma segura e o estado da carteira não foi alterado.",walletConnection:"Conexão da carteira",walletActions:"Ações da carteira",preferencesRejected:"As preferências de exibição salvas eram inválidas ou estavam desatualizadas e foram redefinidas com segurança."},
  ru: {eyebrow:"Помощник кошелька",title:"Подключиться к YNX Testnet",intro:"Используйте установленный кошелёк. Приложение не получает фразу восстановления или закрытый ключ.",detected:"YNX Wallet обнаружен",connectYNX:"Открыть YNX Wallet",download:"Скачать YNX Wallet",metamask:"Использовать MetaMask",unavailable:"Поддерживаемый кошелёк не обнаружен",add:"Добавить YNX Testnet",switch:"Сменить сеть",sign:"Подписать сообщение",send:"Отправить транзакцию",message:"Сообщение",recipient:"Получатель",value:"Значение (hex wei)",data:"Данные (hex)",connected:"Подключено",disconnected:"Не подключено",rpcCheck:"Перед сменой сети или транзакцией обязательна проверка живого RPC.",testnet:"Активы Testnet не имеют заявленной реальной стоимости.",light:"Светлая",dark:"Тёмная",language:"Язык",status:"Статус",txHash:"Хэш транзакции",signature:"Подпись",working:"Ожидание подтверждения…",requestFailed:"Запрос безопасно завершился ошибкой; состояние кошелька не изменилось.",walletConnection:"Подключение кошелька",walletActions:"Действия кошелька",preferencesRejected:"Сохранённые настройки отображения были недействительными или устарели и были безопасно сброшены."},
  ar: {eyebrow:"مرافق المحفظة",title:"الاتصال بشبكة YNX التجريبية",intro:"استخدم محفظة مثبّتة. لا يستلم التطبيق عبارة الاسترداد أو المفتاح الخاص.",detected:"تم اكتشاف YNX Wallet",connectYNX:"فتح YNX Wallet",download:"تنزيل YNX Wallet",metamask:"استخدام MetaMask",unavailable:"لم يتم اكتشاف محفظة مدعومة",add:"إضافة شبكة YNX التجريبية",switch:"تبديل الشبكة",sign:"توقيع الرسالة",send:"إرسال المعاملة",message:"الرسالة",recipient:"المستلم",value:"القيمة (wei سداسي)",data:"البيانات (سداسية)",connected:"متصل",disconnected:"غير متصل",rpcCheck:"يلزم تحقق RPC مباشر قبل تغيير الشبكة أو إرسال معاملة.",testnet:"أصول الشبكة التجريبية لا تمثل قيمة مالية حقيقية.",light:"فاتح",dark:"داكن",language:"اللغة",status:"الحالة",txHash:"تجزئة المعاملة",signature:"التوقيع",working:"بانتظار موافقة المحفظة…",requestFailed:"فشل الطلب بشكل آمن ولم تتغير حالة المحفظة.",walletConnection:"اتصال المحفظة",walletActions:"إجراءات المحفظة",preferencesRejected:"كانت تفضيلات العرض المحفوظة غير صالحة أو قديمة، وأُعيد ضبطها بأمان."},
  id: {eyebrow:"Pendamping dompet",title:"Hubungkan ke YNX Testnet",intro:"Gunakan dompet terpasang. Aplikasi tidak pernah menerima frasa pemulihan atau kunci privat.",detected:"YNX Wallet terdeteksi",connectYNX:"Buka YNX Wallet",download:"Unduh YNX Wallet",metamask:"Gunakan MetaMask",unavailable:"Dompet yang didukung tidak terdeteksi",add:"Tambahkan YNX Testnet",switch:"Ganti jaringan",sign:"Tandatangani pesan",send:"Kirim transaksi",message:"Pesan",recipient:"Penerima",value:"Nilai (wei heksadesimal)",data:"Data (heksadesimal)",connected:"Terhubung",disconnected:"Belum terhubung",rpcCheck:"Verifikasi RPC langsung wajib sebelum perubahan jaringan atau transaksi.",testnet:"Aset Testnet tidak mewakili nilai dunia nyata.",light:"Terang",dark:"Gelap",language:"Bahasa",status:"Status",txHash:"Hash transaksi",signature:"Tanda tangan",working:"Menunggu persetujuan dompet…",requestFailed:"Permintaan gagal secara aman dan status dompet tidak berubah.",walletConnection:"Koneksi dompet",walletActions:"Tindakan dompet",preferencesRejected:"Preferensi tampilan tersimpan tidak valid atau kedaluwarsa dan telah direset dengan aman."},
};

const connectOverrides=Object.freeze({
  "zh-CN":{disconnect:"断开连接",switchAccount:"切换账户",metamaskDetected:"已检测到 MetaMask provider",providerNotInjected:"未检测到钱包 provider。请启用已安装的钱包后重试。",walletLocked:"已安装的钱包处于锁定状态。解锁后重试。",siteAccessDenied:"钱包未获准访问此 HTTPS DApp。授权本站访问后重试。",rpcCheck:"当前网络由所选钱包确认；浏览器 RPC 探测仅用于诊断。"},
  "zh-TW":{disconnect:"中斷連線",switchAccount:"切換帳戶",metamaskDetected:"已偵測到 MetaMask provider",providerNotInjected:"未偵測到錢包 provider。請啟用已安裝的錢包後重試。",walletLocked:"已安裝的錢包已鎖定。解鎖後重試。",siteAccessDenied:"錢包未獲准存取此 HTTPS DApp。允許存取後重試。",rpcCheck:"目前網路由所選錢包確認；瀏覽器 RPC 探測僅供診斷。"},
  ja:{disconnect:"切断",switchAccount:"アカウントを切替",metamaskDetected:"MetaMask providerを検出",providerNotInjected:"ウォレット provider が見つかりません。インストール済みウォレットを有効にして再試行してください。",walletLocked:"インストール済みウォレットはロックされています。ロック解除後に再試行してください。",siteAccessDenied:"この HTTPS DApp へのウォレットアクセスが拒否されています。アクセスを許可して再試行してください。",rpcCheck:"現在のネットワークは選択したウォレットが確認します。ブラウザーのRPCプローブは診断専用です。"},
  ko:{disconnect:"연결 해제",switchAccount:"계정 전환",metamaskDetected:"MetaMask provider 감지됨",providerNotInjected:"지갑 provider가 감지되지 않았습니다. 설치된 지갑을 활성화한 뒤 다시 시도하세요.",walletLocked:"설치된 지갑이 잠겨 있습니다. 잠금을 해제한 뒤 다시 시도하세요.",siteAccessDenied:"이 HTTPS DApp에 대한 지갑 사이트 접근이 거부되었습니다. 접근을 허용한 뒤 다시 시도하세요.",rpcCheck:"활성 네트워크는 선택한 지갑이 확인합니다. 브라우저 RPC 검사는 진단 전용입니다."},
  es:{disconnect:"Desconectar",switchAccount:"Cambiar cuenta",metamaskDetected:"Provider de MetaMask detectado",providerNotInjected:"No se detectó ningún provider de cartera. Habilita una cartera instalada y vuelve a intentarlo.",walletLocked:"La cartera instalada está bloqueada. Desbloquéala y vuelve a intentarlo.",siteAccessDenied:"La cartera no tiene acceso a esta DApp HTTPS. Permite el acceso y vuelve a intentarlo.",rpcCheck:"La cartera seleccionada confirma la red activa; la sonda RPC del navegador es solo diagnóstica."},
  fr:{disconnect:"Déconnecter",switchAccount:"Changer de compte",metamaskDetected:"Provider MetaMask détecté",providerNotInjected:"Aucun provider de portefeuille détecté. Activez un portefeuille installé puis réessayez.",walletLocked:"Le portefeuille installé est verrouillé. Déverrouillez-le puis réessayez.",siteAccessDenied:"L’accès du portefeuille à cette DApp HTTPS est refusé. Autorisez-le puis réessayez.",rpcCheck:"Le portefeuille sélectionné confirme le réseau actif ; la sonde RPC du navigateur sert uniquement au diagnostic."},
  de:{disconnect:"Trennen",switchAccount:"Konto wechseln",metamaskDetected:"MetaMask-Provider erkannt",providerNotInjected:"Kein Wallet-Provider erkannt. Aktivieren Sie eine installierte Wallet und versuchen Sie es erneut.",walletLocked:"Die installierte Wallet ist gesperrt. Entsperren Sie sie und versuchen Sie es erneut.",siteAccessDenied:"Der Wallet-Zugriff auf diese HTTPS-DApp ist verweigert. Erlauben Sie den Zugriff und versuchen Sie es erneut.",rpcCheck:"Die ausgewählte Wallet bestätigt das aktive Netzwerk; die Browser-RPC-Prüfung dient nur der Diagnose."},
  pt:{disconnect:"Desconectar",switchAccount:"Trocar conta",metamaskDetected:"Provider MetaMask detectado",providerNotInjected:"Nenhum provider de carteira foi detectado. Ative uma carteira instalada e tente novamente.",walletLocked:"A carteira instalada está bloqueada. Desbloqueie-a e tente novamente.",siteAccessDenied:"O acesso da carteira a esta DApp HTTPS foi negado. Permita o acesso e tente novamente.",rpcCheck:"A carteira selecionada confirma a rede ativa; a sondagem RPC do navegador é apenas diagnóstica."},
  ru:{disconnect:"Отключить",switchAccount:"Сменить аккаунт",metamaskDetected:"Provider MetaMask обнаружен",providerNotInjected:"Provider кошелька не обнаружен. Включите установленный кошелёк и повторите попытку.",walletLocked:"Установленный кошелёк заблокирован. Разблокируйте его и повторите попытку.",siteAccessDenied:"Доступ кошелька к этому HTTPS DApp запрещён. Разрешите доступ и повторите попытку.",rpcCheck:"Активную сеть подтверждает выбранный кошелёк; RPC-проверка браузера используется только для диагностики."},
  ar:{disconnect:"قطع الاتصال",switchAccount:"تبديل الحساب",metamaskDetected:"تم اكتشاف provider ‏MetaMask",providerNotInjected:"لم يتم اكتشاف provider للمحفظة. فعّل محفظة مثبّتة ثم أعد المحاولة.",walletLocked:"المحفظة المثبّتة مقفلة. افتحها ثم أعد المحاولة.",siteAccessDenied:"وصول المحفظة إلى تطبيق HTTPS هذا مرفوض. اسمح بالوصول ثم أعد المحاولة.",rpcCheck:"تؤكد المحفظة المحددة الشبكة النشطة؛ فحص RPC في المتصفح للتشخيص فقط."},
  id:{disconnect:"Putuskan",switchAccount:"Ganti akun",metamaskDetected:"Provider MetaMask terdeteksi",providerNotInjected:"Provider dompet tidak terdeteksi. Aktifkan dompet yang terpasang lalu coba lagi.",walletLocked:"Dompet yang terpasang terkunci. Buka kunci lalu coba lagi.",siteAccessDenied:"Akses dompet ke DApp HTTPS ini ditolak. Izinkan akses lalu coba lagi.",rpcCheck:"Dompet yang dipilih mengonfirmasi jaringan aktif; probe RPC browser hanya untuk diagnosis."},
});
export function catalog(locale) { return Object.freeze({...en, ...(overrides[locale] || {}),...(connectOverrides[locale]||{})}); }
export function untranslatedKeys(locale) { const localized={...(overrides[locale]||{}),...(connectOverrides[locale]||{})};return locale === "en" ? [] : Object.keys(en).filter(key=>!Object.hasOwn(localized,key)); }
export function isRTL(locale) { return locale === "ar"; }
