import{walletAuthorizationURL}from"./wallet-auth.js";
import{ready as i18nReady,t}from"./i18n.js";
const API=localStorage.getItem("ynx.video.api")||"http://127.0.0.1:8423",$=s=>document.querySelector(s);
const session=()=>sessionStorage.getItem("ynx.video.session")||new URLSearchParams(location.hash.slice(1)).get("gateway_session");let snapshot=null,currentAI=null;
async function api(path,opt={}){const headers={...(opt.headers||{})},method=(opt.method||"GET").toUpperCase();if(session())headers["X-YNX-App-Session"]=session();if(!["GET","HEAD"].includes(method))headers["Idempotency-Key"]||=crypto.randomUUID();let response;for(let attempt=0;attempt<2;attempt++){try{response=await fetch(API+path,{...opt,headers});break}catch(error){if(attempt===1)throw error}}const data=await response.json().catch(()=>({error:"Invalid service response"}));if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);return data}
const json=body=>({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),get=(x,lower,upper)=>x?.[lower]??x?.[upper],esc=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
function status(message,bad=false){$("#status").textContent=message;$("#status").style.color=bad?"#9b2335":"#344054"}
function rows(target,items,render,empty){$(target).innerHTML=items.length?items.map(render).join(""):`<p class="meta">${empty}</p>`}

$("#signin").onclick=async()=>{try{location.href=await walletAuthorizationURL({requestingProduct:"ynx-creator-studio",productClientId:"ynx-creator-studio-web-v1",bundleId:"com.ynxweb4.creator-studio.web",callback:"https://creator.video.ynxweb4.com/wallet-auth/callback",scopes:["ai.video.propose","pay.payout.intent","video.creator","video.read"],purpose:"Manage owned media, review AI proposals, disputes, and Wallet-confirmed payout intents. No key or recovery material is requested."})}catch(error){status(error.message,true)}};
if(session()){sessionStorage.setItem("ynx.video.session",session());history.replaceState(null,"",location.pathname);$("#signin").textContent="Wallet connected"}
document.querySelectorAll("nav button").forEach(button=>button.onclick=()=>{document.querySelectorAll("nav button").forEach(x=>x.classList.toggle("active",x===button));document.querySelectorAll(".panel").forEach(x=>x.classList.toggle("active",x.id===button.dataset.panel));$("#heading").textContent=button.textContent});

async function refresh(){try{snapshot=await api("/v1/studio");const a=snapshot.analytics;$("#views").textContent=a.views;$("#watch").textContent=`${a.watch_seconds}s`;$("#subs").textContent=a.subscribers;$("#revenue").textContent=`${a.revenue_ynxt} YNXT`;renderContent();renderAudit();status("Studio state loaded from persistent records.")}catch(error){status(t("unavailable"),true)}}
function renderContent(){const box=$("#videos"),videos=snapshot?.videos||[];box.replaceChildren();if(!videos.length){box.innerHTML='<p class="meta">No content records. Upload repository-owned media to begin.</p>';return}for(const video of videos){const row=document.createElement("div");row.className="row";const takedown=video.takedown?` · takedown ${video.takedown.state}`:"";row.innerHTML=`<div><b>${esc(video.title)}</b><small>${esc(video.id)}</small></div><span class="state">${esc(video.status)}${esc(takedown)}</span><span>${esc(video.visibility)}</span><div class="row-actions"><button data-action="edit">Edit</button><button data-action="visibility">Visibility</button>${video.status==="failed"?'<button data-action="retry">Retry</button>':""}</div>`;row.querySelector('[data-action="edit"]').onclick=()=>editVideo(video);row.querySelector('[data-action="visibility"]').onclick=()=>publishVideo(video);row.querySelector('[data-action="retry"]')?.addEventListener("click",()=>retryVideo(video));box.append(row)}}
async function editVideo(video){const title=prompt("Title",video.title);if(!title)return;const description=prompt("Description",video.description||"");if(description===null)return;try{await api(`/v1/videos/${video.id}/metadata`,json({title,description}));await refresh()}catch(error){status(error.message,true)}}
async function publishVideo(video){const visibility=prompt("Visibility: private, unlisted, or public",video.visibility);if(!visibility)return;try{await api(`/v1/videos/${video.id}/publish`,json({visibility}));status("Human-reviewed visibility persisted.");await refresh()}catch(error){status(error.message,true)}}
async function retryVideo(video){try{status("Retrying malware scan and media processing…");await api(`/v1/videos/${video.id}/retry-processing`,{method:"POST"});await refresh()}catch(error){status(error.message,true)}}
function renderAudit(){rows("#revenue-list",snapshot.revenue||[],r=>`<div class="row"><b>${esc(get(r,"id","ID"))}</b><span>${get(r,"amount_ynxt","AmountYNXT")} YNXT</span><span>${esc(get(r,"pay_receipt_id","PayReceiptID"))}</span></div>`,"No verified revenue records.");rows("#payout-list",snapshot.payout_intents||[],p=>`<div class="row"><b>${esc(get(p,"id","ID"))}</b><span>${get(p,"amount_ynxt","AmountYNXT")} YNXT</span><span class="state">${esc(get(p,"state","State"))}</span></div>`,"No payout intents.");rows("#report-list",snapshot.reports||[],r=>`<div class="row"><b>${esc(get(r,"id","ID"))}</b><span>${esc(get(r,"reason","Reason"))}</span><span class="state">${esc(get(r,"state","State"))}</span></div>`,"No reports on owned videos.");rows("#appeal-list",snapshot.appeals||[],a=>`<div class="row"><b>${esc(get(a,"id","ID"))}</b><span>${esc(get(a,"reason","Reason"))}</span><span class="state">${esc(get(a,"state","State"))}</span></div>`,"No appeals.");rows("#dispute-list",snapshot.disputes||[],d=>`<div class="row"><b>${esc(get(d,"id","ID"))}</b><span>${esc(get(d,"reason","Reason"))}</span><span class="state">${esc(get(d,"state","State"))}</span></div>`,"No revenue disputes.")}

$("#refresh").onclick=refresh;$("#channel-form").onsubmit=async event=>{event.preventDefault();try{const channel=await api("/v1/channels",json({handle:event.target.handle.value,name:event.target.name.value}));$("#channel-result").textContent=JSON.stringify(channel,null,2);status("Channel persisted.")}catch(error){status(error.message,true)}};
$("#upload-form").onsubmit=async event=>{event.preventDefault();const file=event.target.media.files[0];if(!["video/mp4","video/webm"].includes(file?.type)){status("Select an MP4 or WebM file.",true);return}const data=new FormData();for(const [key,value] of [["channel_id",event.target.channel_id.value],["media",file],["size",String(file.size)],["title",event.target.title.value],["description",event.target.description.value],["owned_content_declaration",String(event.target.owned.checked)]])data.set(key,value);try{status("Uploading for malware scan and adaptive processing…");const video=await api("/v1/uploads",{method:"POST",body:data});status(`Processing state: ${video.status}. Publication still requires review.`);await refresh()}catch(error){status(error.message,true)}};
$("#thumbnail-form").onsubmit=async event=>{event.preventDefault();const file=event.target.thumbnail.files[0],data=new FormData();data.set("thumbnail",file);data.set("size",String(file.size));try{await api(`/v1/videos/${event.target.video_id.value}/thumbnail`,{method:"POST",body:data});status("Thumbnail stored.");await refresh()}catch(error){status(error.message,true)}};
$("#caption-form").onsubmit=async event=>{event.preventDefault();const file=event.target.captions.files[0],data=new FormData();data.set("captions",file);data.set("size",String(file.size));data.set("language",event.target.language.value);data.set("label",event.target.label.value);data.set("ai_proposed","false");try{await api(`/v1/videos/${event.target.video_id.value}/captions`,{method:"POST",body:data});status("Human-approved caption track stored.");await refresh()}catch(error){status(error.message,true)}};
$("#monetization").onsubmit=async event=>{event.preventDefault();try{const result=await api(`/v1/videos/${event.target.video_id.value}/monetization`,{method:"POST"});status(`${get(result,"state","State")}: ${get(result,"reason","Reason")}`);await refresh()}catch(error){status(error.message,true)}};
$("#payout").onsubmit=async event=>{event.preventDefault();try{const intent=await api("/v1/studio/payout-intents",json({amount_ynxt:Number(event.target.amount.value)}));status(`Pay intent ${get(intent,"pay_intent_id","PayIntentID")} awaits Wallet confirmation.`);await refresh()}catch(error){status(error.message,true)}};
$("#appeal").onsubmit=async event=>{event.preventDefault();try{await api(`/v1/reports/${event.target.report_id.value}/appeals`,json({reason:event.target.reason.value}));status("Appeal submitted for human review.");await refresh()}catch(error){status(error.message,true)}};
$("#dispute").onsubmit=async event=>{event.preventDefault();try{await api(`/v1/revenue/${event.target.record_id.value}/disputes`,json({reason:event.target.reason.value}));status("Revenue dispute persisted.");await refresh()}catch(error){status(error.message,true)}};

async function providerStatus(){try{const p=await api("/v1/ai/status");$("#ai-provider").textContent=p.configured?"AI Gateway configured. Provider/model are recorded with each result.":"AI Gateway unavailable. Requests will fail honestly until configured."}catch(error){$("#ai-provider").textContent="AI Gateway status unavailable."}}
function showAI(job){currentAI=job;$("#ai-result").textContent=JSON.stringify(job,null,2);const state=get(job,"state","State");$("#ai-run").disabled=!['awaiting_permission','failed'].includes(state);$("#ai-cancel").disabled=!['awaiting_permission','running'].includes(state);$("#ai-accept").disabled=state!=="review_required";$("#ai-reject").disabled=state!=="review_required";$("#ai-delete").disabled=state==="running"}
$("#ai-form").onsubmit=async event=>{event.preventDefault();try{const job=await api("/v1/ai/jobs",json({video_id:event.target.video_id.value,kind:event.target.kind.value,context_classes:event.target.metadata.checked?["metadata"]:[],output_language:localStorage.getItem("ynx.creator.ai-locale")||localStorage.getItem("ynx.creator.locale")||"en"}));showAI(job);status("Review context preview, output language and estimated units, then explicitly approve or reject.")}catch(error){status(error.message,true)}};
$("#ai-run").onclick=async()=>{if(!currentAI)return;const id=get(currentAI,"id","ID");showAI({...currentAI,State:"running",state:"running"});status("Provider stream running. Cancel remains available.");let streamed="",buffer="";
try{const response=await fetch(`${API}/v1/ai/jobs/${id}/stream`,{method:"POST",headers:{"X-YNX-App-Session":session()||"","Idempotency-Key":crypto.randomUUID(),Accept:"application/x-ndjson"}});
if(!response.ok)throw new Error(`HTTP ${response.status}`);const reader=response.body.getReader(),decoder=new TextDecoder();for(;;){const {value,done}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done});const lines=buffer.split("\n");buffer=lines.pop()||"";for(const line of lines){if(!line)continue;const event=JSON.parse(line);if(event.error)throw new Error(event.error);if(event.delta){streamed+=event.delta;$("#ai-result").textContent=`Streaming provider output — review required\n\n${streamed}`};if(event.job)showAI(event.job)}if(done)break}if(!['review_required','cancelled'].includes(get(currentAI,"state","State")))showAI(await api(`/v1/ai/jobs/${id}`));status(get(currentAI,"state","State")==="review_required"?"AI stream finished; human review is required.":"AI stream ended without applying an action.")}catch(error){status(error.message,true);try{showAI(await api(`/v1/ai/jobs/${id}`))}catch{}}};
$("#ai-cancel").onclick=async()=>{if(!currentAI)return;try{showAI(await api(`/v1/ai/jobs/${get(currentAI,"id","ID")}/cancel`,{method:"POST"}));status("AI request cancelled and audited.")}catch(error){status(error.message,true)}};
async function reviewAI(apply){try{showAI(await api(`/v1/ai/jobs/${get(currentAI,"id","ID")}/review`,json({apply})));status(apply?"Suggestion accepted; publication still requires a separate human action.":"Suggestion rejected and audited.")}catch(error){status(error.message,true)}}$("#ai-accept").onclick=()=>reviewAI(true);$("#ai-reject").onclick=()=>reviewAI(false);
$("#ai-delete").onclick=async()=>{if(!currentAI||!confirm("Delete this AI context and result? The minimal deletion audit remains."))return;try{await api(`/v1/ai/jobs/${get(currentAI,"id","ID")}`,{method:"DELETE"});currentAI=null;$("#ai-result").textContent="AI context and result deleted.";for(const id of ["#ai-run","#ai-cancel","#ai-accept","#ai-reject","#ai-delete"])$(id).disabled=true;status("AI data deleted within the service retention boundary.");await refresh()}catch(error){status(error.message,true)}};
await i18nReady.catch(()=>null);refresh();providerStatus();
