import assert from "node:assert/strict";
import { createServer } from "node:http";
import { mkdtemp, rm } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import test from "node:test";
import { createRuntimeProfileService, createSshAdapter } from "../src/service.mjs";

const KEY="runtime-profile-test-key-that-is-at-least-thirty-two-bytes";
async function fixture(t){const root=await mkdtemp(join(tmpdir(),"ynx-profile-test-")),events=[],lxd={inventory:async()=>({installed:true,ready:true,storagePools:1,profile:true}),create:async value=>(events.push(["create",value]),{containerName:value.containerName,imageFingerprint:"abc123",network:"disabled"}),remove:async value=>events.push(["remove",value])},ssh={inspect:async target=>({hostKey:`[${target.host}]:${target.port} ssh-ed25519 AAAATEST`,fingerprint:"256 SHA256:test ED25519"}),verify:async value=>events.push(["verify",value])},service=createRuntimeProfileService({filename:join(root,"profiles.sqlite"),ownerForRequest:request=>request.headers["x-owner"]||null,encryptionKey:KEY,lxd,ssh}),server=createServer((request,response)=>service.handler(request,response).then(handled=>{if(!handled)response.writeHead(404).end()}));await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));t.after(async()=>{service.close();await new Promise(resolve=>server.close(resolve));await rm(root,{recursive:true,force:true})});return{base:`http://127.0.0.1:${server.address().port}`,events}}
async function call(base,owner,path,body,method="POST"){const response=await fetch(`${base}${path}`,{method,headers:{"content-type":"application/json","x-owner":owner},...(body===undefined?{}:{body:JSON.stringify(body)})});return{response,value:await response.json()}}
test("LXD leases are bounded to their owner and use an approved image",async t=>{const{base,events}=await fixture(t),created=await call(base,"owner-a","/runtime/profiles/lxd/leases",{protocolVersion:"ynx-code-runtime/v1",approval:"create-container-once",projectId:"project-a",image:"ubuntu-24.04"});assert.equal(created.response.status,201);assert.equal(created.value.runtime.evidence.network,"disabled");assert.equal(events[0][1].image,"ubuntu:24.04");const list=await call(base,"owner-a","/runtime/profiles",undefined,"GET"),other=await call(base,"owner-b","/runtime/profiles",undefined,"GET");assert.equal(list.value.leases.length,1);assert.equal(other.value.leases.length,0);assert.equal((await call(base,"owner-b",`/runtime/profiles/lxd/leases/${created.value.runtime.runtimeId}`,undefined,"DELETE")).response.status,404);assert.equal((await call(base,"owner-a",`/runtime/profiles/lxd/leases/${created.value.runtime.runtimeId}`,undefined,"DELETE")).response.status,200);assert.equal(events.at(-1)[0],"remove")});
test("SSH requires reviewed host key, verifies access and never returns the private key",async t=>{const{base,events}=await fixture(t),target={protocolVersion:"ynx-code-runtime/v1",host:"code.example.com",port:22,user:"developer"},inspected=await call(base,"owner-a","/runtime/profiles/ssh/inspect",target),privateKey="-----BEGIN OPENSSH PRIVATE KEY-----\n"+"A".repeat(80)+"\n-----END OPENSSH PRIVATE KEY-----",changed=await call(base,"owner-a","/runtime/profiles/ssh",{...target,label:"Production",approval:"connect-ssh-once",reviewedHostKey:"wrong",privateKey});assert.equal(changed.response.status,409);const saved=await call(base,"owner-a","/runtime/profiles/ssh",{...target,label:"Production",approval:"connect-ssh-once",reviewedHostKey:inspected.value.hostKey,privateKey});assert.equal(saved.response.status,201);assert.equal(events.at(-1)[0],"verify");const list=await call(base,"owner-a","/runtime/profiles",undefined,"GET");assert.equal(list.value.sshProfiles[0].fingerprint,"256 SHA256:test ED25519");assert.equal(JSON.stringify(list.value).includes("PRIVATE KEY"),false)});

test("SSH adapter canonicalizes default-port host keys and rejects private targets",async()=>{const key=Buffer.from("real-host-key-material").toString("base64"),calls=[],adapter=createSshAdapter({resolve:async()=>[{address:"203.0.113.20",family:4}],run:async(command,args)=>{calls.push([command,args]);return{stdout:`code.example.com ssh-ed25519 ${key}\n`,stderr:""}}}),inspected=await adapter.inspect({host:"code.example.com",port:22,user:"developer"});assert.equal(inspected.hostKey,`code.example.com ssh-ed25519 ${key}`);assert.match(inspected.fingerprint,/^SHA256:/);const blocked=createSshAdapter({resolve:async()=>[{address:"127.0.0.1",family:4}],run:async()=>({stdout:"",stderr:""})});await assert.rejects(()=>blocked.inspect({host:"localhost",port:22,user:"developer"}),error=>error.code==="ssh_target_not_public");assert.equal(calls[0][0],"ssh-keyscan")});
