const $=id=>document.getElementById(id);
const text=(id,value)=>{$(id).textContent=value??"—"};
const human=value=>String(value??"unknown").replaceAll("-"," ");
let routeCatalog=[],currentQuote=null;

async function json(path,options={}){const response=await fetch(`/api${path}`,{...options,headers:{Accept:"application/json",...(options.body?{"Content-Type":"application/json"}:{}),...(options.headers||{})}});const value=await response.json().catch(()=>({error:"Invalid service response"}));if(!response.ok)throw new Error(value.error||`${path} returned ${response.status}`);return value}

function renderRoutes(routes){$("route-list").replaceChildren(...routes.map(route=>{const card=document.createElement("article");card.className="data-card";const title=document.createElement("h3");title.textContent=`${route.source?.chain??"Unknown"} → ${route.destination?.chain??"Unknown"}`;const tag=document.createElement("span");tag.className="tag";tag.textContent=route.executable?"Executable":"Unavailable";const header=document.createElement("header");header.append(title,tag);const asset=document.createElement("p");asset.className="route";asset.textContent=`${route.source?.symbol??route.source?.asset??"—"} → ${route.destination?.symbol??route.destination?.asset??"—"}`;const reason=document.createElement("p");reason.textContent=`${route.provider} · ${human(route.failureStatus)}`;card.append(header,asset,reason);return card}))}
function renderProviders(providers){$("provider-list").replaceChildren(...providers.map(provider=>{const card=document.createElement("article");card.className="data-card";const title=document.createElement("h3");title.textContent=provider.product||provider.provider;const tag=document.createElement("span");tag.className="tag";tag.textContent=provider.executable?"Executable":human(provider.availability||"review only");const header=document.createElement("header");header.append(title,tag);const route=document.createElement("p");route.className="route";route.textContent=`${provider.sourceChain} → ${provider.destinationChain}`;const details=document.createElement("p");details.textContent=`${human(provider.classification)} · ${provider.authentication}`;card.append(header,route,details);return card}))}

function populateRoutes(routes){routeCatalog=routes;const source=$("source-chain"),destination=$("destination-chain");source.replaceChildren(...routes.map((route,index)=>new Option(`${route.source.chain} · ${route.source.symbol||route.source.asset}`,String(index))));destination.replaceChildren();source.disabled=routes.length===0;syncRoute()}
function syncRoute(){const route=routeCatalog[Number($("source-chain").value)||0];$("destination-chain").replaceChildren(new Option(route?`${route.destination.chain} · ${route.destination.symbol||route.destination.asset}`:"Unavailable",""));text("asset-symbol",route?.source.symbol||route?.source.asset||"ASSET")}
function bridgeWallet(){return window.YNXBridgeWallet}
async function requestQuote(){const wallet=bridgeWallet(),route=routeCatalog[Number($("source-chain").value)||0];if(!wallet||!route)throw new Error("Bridge route or Wallet runtime is unavailable.");text("quote-detail","Requesting a fresh account-bound quote…");const proof=await wallet.requireProof("bridge:quote:read"),payload={sourceChain:route.source.chain,sourceAsset:route.source.asset,destinationChain:route.destination.chain,destinationAsset:route.destination.asset,amount:$("amount").value.trim(),sender:$("sender").value.trim(),recipient:$("recipient").value.trim()};currentQuote=await json("/bridge/quotes",{method:"POST",headers:{"X-YNX-Product-Session-Proof":proof},body:JSON.stringify(payload)});text("quote-state",currentQuote.executable?"Executable":"Review only · unavailable");text("quote-detail",`${currentQuote.id} · expires ${new Date(currentQuote.expiresAt).toLocaleTimeString()} · ${human(currentQuote.failureStatus)}. This quote does not submit a transaction.`);$("review-quote").disabled=false}
async function reviewQuote(){if(!currentQuote)throw new Error("Request a fresh Bridge quote first.");const wallet=bridgeWallet();if(!wallet)throw new Error("Wallet runtime is unavailable.");text("quote-detail","Creating an exact Wallet review of the current quote…");const proof=await wallet.requireProof("bridge:review:create"),review=await json("/bridge/wallet-reviews",{method:"POST",headers:{"X-YNX-Product-Session-Proof":proof},body:JSON.stringify({quote:currentQuote})});text("quote-detail",`${review.id||"Wallet review created"} · ${human(review.status||"review only")}. External submission remains disabled.`)}
function actionError(error){text("quote-detail",error instanceof Error?error.message:"Bridge request failed closed.")}

async function refresh(){text("runtime-status","Refreshing live evidence…");try{const[health,routes,providers]=await Promise.all([json("/health"),json("/bridge/routes"),json("/bridge/providers")]);text("runtime-status",health.liveBridge?"Bridge execution live":"Coordinator online · execution disabled");text("as-of",`Started ${new Date(health.startedAt).toLocaleString()}`);$("status-dot").className=`dot ${health.liveBridge?"ok":"warning"}`;text("service-state",health.degraded?"Degraded safely":"Operational");text("route-count",health.routeCount);text("provider-count",`${health.availableProviderCount}/${health.providerCount}`);text("transfer-count",health.transferCount);text("finalized-count",health.finalizedLocalCount);text("provider-status",human(health.providerStatus));text("contract-status",human(health.contractStatus));text("reconciliation-status",human(health.reconciliationStatus));text("state-integrity",health.stateIntegrity);text("submission",health.externalSubmissionEnabled?"Enabled":"Disabled");const first=providers.providers?.[0],timing=first?.estimatedTime;text("estimate",timing?.estimatedMinSeconds?`${timing.estimatedMinSeconds}–${timing.estimatedMaxSeconds}s (configured)`:"Unavailable");text("quote-state",routes.routes?.some(route=>route.executable)?"Available":"Unavailable until Wallet quote");renderRoutes(routes.routes||[]);renderProviders(providers.providers||[]);populateRoutes(routes.routes||[])}catch(error){text("runtime-status","Bridge evidence unavailable");text("as-of",error instanceof Error?error.message:"Refresh failed");$("status-dot").className="dot";text("service-state","Unavailable")}}

$("refresh").addEventListener("click",refresh);$("source-chain").addEventListener("change",syncRoute);$("request-quote").addEventListener("click",()=>requestQuote().catch(actionError));$("review-quote").addEventListener("click",()=>reviewQuote().catch(actionError));window.addEventListener("ynx-bridge-wallet-change",()=>{const account=bridgeWallet()?.account();if(account){$("request-quote").disabled=false;for(const id of["sender","recipient"])if(!$(id).value)$(id).value=account}});refresh();setInterval(refresh,15000);
