const copy={
 en:{title:'Your private conversations',intro:'Choose a conversation, compare devices, then share messages and files.',open:'Open private chat',lock:'Lock chat',rooms:'Conversations and invitations',devices:'My devices',people:'Start a conversation',peer:'Accepted contact',chooseContact:'Choose a contact',noContacts:'No accepted contacts yet',refreshContacts:'Refresh accepted contacts',contactHelp:'Choose a person whose contact request has been accepted. No wallet address is needed.',openContactChat:'Open private chat using your existing Social identity, then choose this accepted contact again.',create:'Start encrypted conversation',message:'Your message',send:'Send message',attachment:'Add an encrypted file',checks:'Device checks',details:'Connection details',permissions:'Review sign-in and chat permissions',account:'YNX account',site:'Chat service',device:'Device',conversation:'Conversation',cancel:'Cancel',remove:'Remove device access',done:'Done',hide:'Hide progress',accept:'Accept invitation',locked:'Private chat is locked. Your messages and devices are retained.',approval:'Sign in and review your chat permissions to continue.',connecting:'Checking your sign-in. Your encrypted history is retained.',waiting:'Continue sign-in when you are ready. You can cancel without changing your device.',connected:'Chat is connected. Choose a conversation to continue.',verifying:'Compare devices before sending. Your draft is retained.',ready:'Devices checked. You can send to this conversation.',offline:'Connection interrupted. Retry explicitly and check devices before sending. Your history and draft are retained.',removing:'Requesting device removal. Complete identity verification if asked. Locking chat cannot undo a request already sent.',removeTitle:'Remove this device\'s access?',removeBody:'Only approve if you recognize this device. Downloaded messages and files cannot be recalled. Saved encryption history is not erased.',currentBody:'This is the device you are using. If removal succeeds, you must sign in again. Downloaded copies cannot be recalled.',removedTitle:'Device access removed',removedBody:'The chat service confirmed removal. Your saved encrypted history is retained.',failedTitle:'Removal not confirmed',failedBody:'The request did not complete with a confirmed result. Check the device list before retrying; do not assume access was removed.',failed:'Chat could not complete this action. Please try again. Your encrypted history is retained.',invitationTitle:'Join this conversation?',invitationBody:'Review the conversation first. You will still need to compare devices before sending.',stateLocked:'Locked',stateApproval:'Permission needed',stateConnecting:'Connecting',stateWaiting:'Waiting for you',stateConnected:'Connected',stateVerifying:'Check devices',stateReady:'Ready to send',stateOffline:'Connection interrupted',stateRemoving:'Removing device',stateError:'Action needs attention'},
 zh:{title:'你的私密对话',intro:'选择对话、核对设备，然后分享消息和文件。',open:'打开私密聊天',lock:'锁定聊天',rooms:'对话与邀请',devices:'我的设备',people:'开始对话',peer:'已接受的联系人',chooseContact:'选择联系人',noContacts:'暂无已接受的联系人',refreshContacts:'刷新好友列表',contactHelp:'选择双方已接受申请的联系人，无需输入钱包地址。',openContactChat:'请使用原有 Social 身份打开私密聊天，然后再次选择这位好友。',create:'开始加密对话',message:'你的消息',send:'发送消息',attachment:'添加加密文件',checks:'设备验证',details:'连接详情',permissions:'检查登录与聊天授权',account:'YNX 账号',site:'聊天服务',device:'设备',conversation:'对话',cancel:'取消',remove:'移除设备访问权限',done:'完成',hide:'收起进度',accept:'接受邀请',locked:'私密聊天已锁定。消息与设备数据均已保留。',approval:'请登录并检查聊天授权，然后继续。',connecting:'正在检查登录状态，原有加密历史已保留。',waiting:'准备好后再继续登录。取消不会更改设备。',connected:'聊天已连接，请选择对话。',verifying:'发送前请核对设备，草稿已保留。',ready:'设备检查通过，可以向此对话发送消息。',offline:'连接中断。请重新连接并检查设备后再发送，历史与草稿已保留。',removing:'正在请求移除设备，请按提示完成身份验证。锁定聊天无法撤回已发送的请求。',removeTitle:'移除此设备的访问权限？',removeBody:'请确认你认识此设备。已下载的消息和文件无法收回，保存的加密历史不会被清除。',currentBody:'这是当前正在使用的设备。移除成功后需要重新登录，已下载的内容无法收回。',removedTitle:'设备访问权限已移除',removedBody:'聊天服务已确认移除，原有加密历史已保留。',failedTitle:'尚未确认移除结果',failedBody:'请求未获得确定结果。请先检查设备列表再重试，不要假定访问权限已经移除。',failed:'本次操作未能完成，请重试。原有加密历史已保留。',invitationTitle:'加入此对话？',invitationBody:'请先检查对话。发送消息前仍需核对设备。',stateLocked:'已锁定',stateApproval:'需要授权',stateConnecting:'正在连接',stateWaiting:'等待确认',stateConnected:'已连接',stateVerifying:'请核对设备',stateReady:'可以发送',stateOffline:'连接中断',stateRemoving:'正在移除设备',stateError:'请检查操作'}
};
Object.assign(copy.en,{
 compareDisplays:'Compare on both devices:',compareDevice:'Compare this device with the other person:',
 displaysMatch:'Both displays match',displaysDiffer:'Do not match',acceptVerification:'Accept request',
 startSas:'Start SAS comparison',rejectVerification:'Reject',conversations:'Your conversations',
 signInCancelled:'Sign-in cancelled. Open private chat again when you are ready. Your encrypted history is retained.'
});
Object.assign(copy.zh,{
 compareDisplays:'请在两台设备上比较：',compareDevice:'请与对方核对此设备：',
 displaysMatch:'双方显示一致',displaysDiffer:'显示不一致',acceptVerification:'接受验证请求',
 startSas:'开始 SAS 比较',rejectVerification:'拒绝',conversations:'你的对话',
 signInCancelled:'登录已取消。准备好后可再次打开私密聊天，原有加密历史已保留。'
});
export function createChatCopy(document=globalThis.document){
 const text=key=>copy[/^zh(?:-|$)/i.test(document?.documentElement?.lang??'')?'zh':'en'][key]??copy.en[key]??key;
 const message=value=>{const key=Object.keys(copy.en).find(key=>copy.en[key]===value);return key?text(key):value};
 return {text,message};
}
