import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const source=readFileSync(new URL('./session-ui.mjs',import.meta.url),'utf8').replace(/^import .*;\n/gm,'');
const A='ynx1'+'a'.repeat(38),B='ynx1'+'b'.repeat(38);
function deferred(){let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve}}
class Node{constructor(){this.children=[];this.dataset={};this.value='';this.disabled=false;this.textContent=''}append(...nodes){this.children.push(...nodes)}replaceChildren(...nodes){this.children=nodes}click(){this.onclick?.()}remove(){}}
function harness(){const state={actor:A,permission:true,network:false,identityCalls:0,decryptCalls:0,urls:0,stops:0,downloads:0,connectCalls:0,messages:async room=>[{sender:room,content:{body:room}}]},nodes=new Map(),timers=[];const root=new Node();root.querySelector=key=>{if(!nodes.has(key))nodes.set(key,new Node());return nodes.get(key)};root.querySelectorAll=()=>[...nodes.values()];
 for(const key of ['[data-status]','[data-verification]','[data-devices]','[data-messages]','[data-connect]','[data-stop]','[data-peer-form]','[data-rooms]','[data-send-form]','[data-attachment]'])root.querySelector(key);
 const permission=()=>({status:state.permission?'connected':'disconnected',session:{account:state.actor,scopes:['social.profile','social.contacts','social.messaging']}});
 class Transport{constructor(options){this.options=options;this.generation=0;state.t=this;this.client=null;this.binding=null}capture(){if(!this.client)throw Object.assign(Error('Locked'),{code:'MATRIX_LOCKED'});return {generation:this.generation,client:this.client,binding:this.binding}}guard(op){if(op.generation!==this.generation||op.client!==this.client||op.binding!==this.binding)throw Object.assign(Error('Stale'),{code:'MATRIX_STALE_SESSION'})}stop(){state.stops++;this.generation++;this.client=null;this.binding=null}async connect(binding){state.connectCalls++;if(state.connectFail)throw Error("Initialization rejected");this.generation++;this.binding=binding;this.client={getRooms:()=>['!a','!b'].map(roomId=>({roomId,getMyMembership:()=> 'join',getJoinedMembers:()=>[]}))};const operation=this.capture();if(state.connectWait)await state.connectWait();this.guard(operation)}async devices(user){const op=this.capture();const result=state.devices?await state.devices(user):[];this.guard(op);return result}async messages(room){state.decryptCalls++;return state.messages(room)}async downloadAttachment(content){state.downloads++;return state.download?state.download(content):new ArrayBuffer(2)}async requestVerification(user,id){state.sasCalls=(state.sasCalls??0)+1;state.sasTarget={user,id}}async revokeOwnDevice(id,confirmed){state.revokeCalls=(state.revokeCalls??0)+1;state.revokeTarget={id,confirmed}}crypto(){return {getDeviceVerificationStatus:async(...args)=>state.verify?state.verify(...args):({isVerified:()=>true})}}}
 const context=vm.createContext({document:{getElementById:()=>root,createElement:()=>new Node(),addEventListener(){}},MatrixSocialTransport:Transport,fetchMatrixBinding:async({account})=>state.bindingWait?state.bindingWait(account):({account,userId:`@${account}:hs.test`,deviceId:'original',homeserver:'https://hs.test/'}),matrixCryptoStore:async()=>state.storeWait?state.storeWait():({deviceId:'original',storageKey:new Uint8Array(32)}),createSocialPrivateSession:()=>({restore:async()=>state.restore?state.restore():permission(),proof:async()=>({proofHeader:'synthetic'})}),SOCIAL_CHAT_SCOPES:[],MATRIX_PROTOCOL:'qa',createSsoReauthController:()=>({cancel(){},request(){}}),fetch:async()=>{state.identityCalls++;if(state.network)throw Error('Network interrupted');return {ok:true,json:async()=>({account:state.actor,csrfToken:'qa'})}},setInterval:fn=>{timers.push(fn);return 1},setTimeout:()=>1,URL:{createObjectURL:()=>{state.urls++;return 'blob:qa'},revokeObjectURL(){}},Blob:class{},confirm:()=>state.confirm!==false,Uint8Array,console});vm.runInContext(source,context);return {state,root,nodes,timers};}
const flush=async()=>{for(let i=0;i<20;i++)await Promise.resolve();await new Promise(r=>setImmediate(r))};
async function connect(h){h.nodes.get('[data-connect]').onclick();await flush()}
async function select(h,index=0){h.nodes.get('[data-rooms]').onclick();await flush();h.nodes.get('[data-verification]').children[index].onclick();await flush()}
async function ready(){const h=harness();await connect(h);await select(h);return h}
function texts(h){return h.nodes.get('[data-messages]').children.map(n=>n.textContent).join('|')}
test('encrypted-event checks current private approval before decryption',async()=>{const h=await ready(),before=h.state.decryptCalls;h.state.permission=false;h.state.t.options.publish({type:'encrypted-event'});await flush();assert.equal(h.state.decryptCalls,before);assert.equal(h.state.t.client,null);assert.equal(texts(h),'')});
test('late previous-room messages cannot replace the newly selected room',async()=>{const h=await ready(),block=deferred();h.state.messages=room=>room==='!a'?block.promise:Promise.resolve([{sender:room,content:{body:'NEW ROOM'}}]);h.state.t.options.publish({type:'encrypted-event'});await flush();await select(h,1);block.resolve([{sender:'old',content:{body:'OLD ROOM'}}]);await flush();assert.ok(!texts(h).includes('OLD ROOM'));assert.ok(texts(h).includes('NEW ROOM'))});
test('account lock discards delayed message plaintext',async()=>{const h=await ready(),block=deferred();h.state.messages=()=>block.promise;h.state.t.options.publish({type:'encrypted-event'});await flush();h.nodes.get('[data-stop]').onclick();block.resolve([{sender:'old',content:{body:'OLD ACCOUNT'}}]);await flush();assert.equal(texts(h),'')});
test('attachment is not released after private permission expires during decryption',async()=>{const h=await ready();h.state.messages=async()=>[{sender:'peer',content:{body:'secret.txt',file:{url:'mxc://hs.test/file'}}}];h.state.t.options.publish({type:'encrypted-event'});await flush();const block=deferred();h.state.download=()=>block.promise;h.nodes.get('[data-messages]').children[0].children[0].onclick();await flush();h.state.permission=false;block.resolve(new ArrayBuffer(2));await flush();assert.equal(h.state.urls,0)});
test('bursts coalesce rather than run unbounded permission checks and decryptions',async()=>{const h=await ready(),before=h.state.decryptCalls,block=deferred();let first=true;h.state.messages=()=>{if(first){first=false;return block.promise}return Promise.resolve([{sender:'peer',content:{body:'LATEST'}}])};for(let n=0;n<500;n++)h.state.t.options.publish({type:'encrypted-event'});await flush();assert.equal(h.state.decryptCalls-before,1);block.resolve([{sender:'peer',content:{body:'FIRST'}}]);await flush();assert.ok(h.state.decryptCalls-before<=2);assert.ok(texts(h).includes('LATEST'))});
test('temporary identity network failure preserves keys and allows normal recovery',async()=>{const h=await ready(),stops=h.state.stops,before=h.state.decryptCalls;h.state.network=true;h.state.t.options.publish({type:'encrypted-event'});await flush();assert.equal(h.state.stops,stops);assert.equal(h.state.decryptCalls,before);h.state.network=false;h.state.messages=async()=>[{sender:'peer',content:{body:'RECOVERED'}}];h.state.t.options.publish({type:'encrypted-event'});await flush();assert.ok(texts(h).includes('RECOVERED'))});
test('expired old identity result cannot lock newly connected account',async()=>{const h=await ready(),block=deferred();let first=true;h.state.restore=()=>{if(first){first=false;return block.promise}return {status:'connected',session:{account:h.state.actor,scopes:['social.profile','social.contacts','social.messaging']}}};h.state.t.options.publish({type:'encrypted-event'});await flush();h.nodes.get('[data-stop]').onclick();h.state.actor=B;await connect(h);const stops=h.state.stops;block.resolve({status:'disconnected'});await flush();assert.equal(h.state.stops,stops);assert.equal(h.state.t.binding.account,B)});
test('normal current attachment is released exactly once',async()=>{const h=await ready();h.state.messages=async()=>[{sender:'peer',content:{body:'approved.txt',file:{url:'mxc://hs.test/approved'}}}];h.state.t.options.publish({type:'encrypted-event'});await flush();h.nodes.get('[data-messages]').children[0].children[0].onclick();await flush();assert.equal(h.state.downloads,1);assert.equal(h.state.urls,1)});
test('permission expiring during delayed message decryption cannot release new plaintext',async()=>{const h=await ready(),block=deferred();h.state.messages=()=>block.promise;h.state.t.options.publish({type:'encrypted-event'});await flush();h.state.permission=false;block.resolve([{sender:'peer',content:{body:'EXPIRED DURING DECRYPT'}}]);await flush();assert.ok(!texts(h).includes('EXPIRED DURING DECRYPT'));assert.equal(h.state.t.client,null)});

const offline=()=>Object.freeze({status:'network-unavailable',message:'Network unavailable; cached Product Session is not treated as authoritative',actions:Object.freeze(['retry','guest'])});
test('SDK network-unavailable return retains runtime without releasing fresh plaintext',async()=>{const h=await ready(),client=h.state.t.client,stops=h.state.stops,before=h.state.decryptCalls;h.state.restore=offline;h.state.t.options.publish({type:'encrypted-event'});await flush();assert.equal(h.state.stops,stops);assert.equal(h.state.t.client,client);assert.equal(h.state.decryptCalls,before);h.state.restore=null;h.state.messages=async()=>[{sender:'peer',content:{body:'SDK RECOVERED'}}];h.state.t.options.publish({type:'encrypted-event'});await flush();assert.ok(texts(h).includes('SDK RECOVERED'))});
for(const status of ['expired','retry-required'])test('authoritative '+status+' still locks',async()=>{const h=await ready();h.state.restore=()=>({status,revocationPending:status==='retry-required'});h.state.t.options.publish({type:'encrypted-event'});await flush();assert.equal(h.state.t.client,null)});
for(const phase of ['store','binding','connect'])test('stop during '+phase+' cannot revive pending connection',async()=>{const h=harness(),block=deferred(),key=new Uint8Array(32).fill(7);if(phase==='store')h.state.storeWait=()=>block.promise;if(phase==='binding')h.state.bindingWait=()=>block.promise;if(phase==='connect')h.state.connectWait=()=>block.promise;h.nodes.get('[data-connect]').onclick();await flush();h.nodes.get('[data-stop]').onclick();block.resolve(phase==='store'?{deviceId:'original',storageKey:key}:phase==='binding'?{account:A,userId:'@'+A+':hs.test'}:undefined);await flush();assert.equal(h.state.t.client,null);assert.equal(h.state.connectCalls,phase==='connect'?1:0);assert.ok(!h.nodes.get('[data-status]').textContent.includes('YNX account verified'));if(phase==='store')assert.ok(key.every(x=>x===0))});
for(const phase of ['store','binding'])test('account switch during '+phase+' rejects old connection',async()=>{const h=harness(),block=deferred();if(phase==='store')h.state.storeWait=()=>block.promise;else h.state.bindingWait=()=>block.promise;h.nodes.get('[data-connect]').onclick();await flush();h.state.actor=B;block.resolve(phase==='store'?{deviceId:'original',storageKey:new Uint8Array(32)}:{account:A,userId:'@'+A+':hs.test'});await flush();assert.equal(h.state.connectCalls,0);assert.equal(h.state.t.client,null)});
test('initialization rejection before client creation is consumed and temporary key cleared',async()=>{const h=harness(),key=new Uint8Array(32).fill(9);h.state.storeWait=async()=>({deviceId:'original',storageKey:key});h.state.connectFail=true;await connect(h);assert.equal(h.state.connectCalls,1);assert.equal(h.state.t.client,null);assert.equal(h.nodes.get('[data-status]').textContent,'Initialization rejected');assert.ok(key.every(x=>x===0))});
const device=()=>({deviceId:'original',getFingerprint:()=> 'QA-FINGERPRINT'});
async function deviceReady(){const h=harness();h.state.devices=async()=>[device()];await connect(h);return h}
for(const phase of ['list','verification'])for(const change of ['stop','account'])test('late device '+phase+' after '+change+' cannot refill locked UI',async()=>{const h=harness(),block=deferred();h.state.devices=async()=>phase==='list'?block.promise:[device()];if(phase==='verification')h.state.verify=()=>{h.state.verifyCalls=(h.state.verifyCalls??0)+1;return block.promise};h.nodes.get('[data-connect]').onclick();await flush();if(phase==='verification')assert.equal(h.state.verifyCalls,1);if(change==='stop')h.nodes.get('[data-stop]').onclick();else{h.state.actor=B;h.timers[0]();await flush()}block.resolve(phase==='list'?[device()]:{isVerified:()=>true});await flush();assert.equal(h.nodes.get('[data-devices]').children.length,0);assert.equal(h.state.t.client,null)});
test('normal device list and SAS action remain usable',async()=>{const h=await deviceReady(),row=h.nodes.get('[data-devices]').children[0];assert.ok(row.children[0].textContent.includes('QA-FINGERPRINT'));row.children[1].onclick();await flush();assert.equal(h.state.sasCalls,1);assert.equal(h.state.sasTarget.user,'@'+A+':hs.test')});
test('normal device removal requires explicit confirmation',async()=>{const h=await deviceReady(),remove=h.nodes.get('[data-devices]').children[0].children[2];h.state.confirm=false;remove.onclick();await flush();assert.equal(h.state.revokeCalls??0,0);h.state.confirm=true;remove.onclick();await flush();assert.equal(h.state.revokeCalls,1);assert.equal(h.state.revokeTarget.confirmed,true)});
for(const action of ['sas','revoke'])test('retained old device '+action+' button cannot act on new account',async()=>{const h=await deviceReady(),button=h.nodes.get('[data-devices]').children[0].children[action==='sas'?1:2];h.nodes.get('[data-stop]').onclick();h.state.actor=B;await connect(h);button.onclick();await flush();assert.equal(h.state.sasCalls??0,0);assert.equal(h.state.revokeCalls??0,0);assert.equal(h.state.t.binding.account,B)});
test('device list is committed atomically after every verification completes',async()=>{const h=harness(),block=deferred();h.state.devices=async()=>[device(),{...device(),deviceId:'second'}];h.state.verify=async(user,id)=>id==='second'?block.promise:{isVerified:()=>true};h.nodes.get('[data-connect]').onclick();await flush();assert.equal(h.nodes.get('[data-devices]').children.length,0);block.resolve({isVerified:()=>false});await flush();const rows=h.nodes.get('[data-devices]').children;assert.equal(rows.length,2);assert.ok(rows[1].children[0].textContent.includes('unverified'))});
for(const action of ['sas','revoke'])test('stop during device '+action+' permission check prevents action',async()=>{const h=await deviceReady(),block=deferred(),button=h.nodes.get('[data-devices]').children[0].children[action==='sas'?1:2];h.state.restore=()=>block.promise;button.onclick();await flush();h.nodes.get('[data-stop]').onclick();const stops=h.state.stops;block.resolve({status:'connected',session:{account:A,scopes:['social.profile','social.contacts','social.messaging']}});await flush();assert.equal(h.state.sasCalls??0,0);assert.equal(h.state.revokeCalls??0,0);assert.equal(h.state.stops,stops)});
