import type {CentralSession} from "./wallet";
const BASE=(process.env.EXPO_PUBLIC_YNX_EXCHANGE_API_URL||"http://10.0.2.2:6442/api").replace(/\/$/,"");
export type IntegrationStatus={gateway:string;gatewayReason?:string;walletRegistry:string;custody:string;indexer:string;crossChain:string};
export type Config={chainId:string;custodyAddress:string;integrations:IntegrationStatus;networks:Array<{asset:string;network:string;depositEnabled:boolean;withdrawalEnabled:boolean;withdrawalReviewEnabled:boolean;crossChain:boolean;unavailableReason?:string;withdrawalFeeMicro?:number}>;warnings:string[]};
export type Order={id:string;side:string;priceMicro:number;amountMicro:number;filledMicro:number;status:string;createdAt:string;authorizationDigest:string};
export type Account={balances:Array<{asset:string;availableMicro:number;reservedMicro:number}>;orders:Order[];trades:unknown[];fees:unknown[];ledger:unknown[];audit:unknown[];security:{withdrawalLock:boolean;orderConfirmation:boolean;sessionTtlMinutes:number}};
export async function publicState(){const [config,markets,book]=await Promise.all([get<Config>("/v1/config"),get<any>("/v1/markets"),get<any>("/v1/orderbook")]);return{config,markets:markets.markets,book}}
export async function account(session:CentralSession){return get<Account>("/v1/account",session.token)}
export async function draftAI(session:CentralSession,prompt:string,language:string){return post("/v1/ai/drafts",session.token,{kind:"risk_explanation",prompt:`[output-language:${language}] ${prompt}`,contextClasses:["public_market_rules","owned_orders","owned_trades"],permission:true})}
async function get<T>(path:string,token?:string):Promise<T>{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),8000);try{const response=await fetch(BASE+path,{headers:token?{authorization:`Bearer ${token}`}:{},signal:controller.signal});const value=await response.json().catch(()=>({}));if(!response.ok)throw new Error(value.error||`Exchange returned ${response.status}`);return value as T}finally{clearTimeout(timer)}}
async function post(path:string,token:string,body:unknown){const response=await fetch(BASE+path,{method:"POST",headers:{authorization:`Bearer ${token}`,"content-type":"application/json"},body:JSON.stringify(body)});const value=await response.json().catch(()=>({}));if(!response.ok)throw new Error(value.error||`Exchange returned ${response.status}`);return value as {status:string;providerStatus:string}}
