import {gatewayProof,type CentralSession} from "./wallet";
import type {ExchangeOrderActionResponse} from "@ynx-chain/wallet-auth";
import {tradingRequest} from "./trading";
export {tradingRequest} from "./trading";
const BASE=(process.env.EXPO_PUBLIC_YNX_EXCHANGE_API_URL||"https://exchange.ynxweb4.com/api").replace(/\/$/,"");
export type IntegrationStatus={gateway:string;gatewayReason?:string;walletRegistry:string;custody:string;indexer:string;crossChain:string};
export type Config={chainId:string;custodyAddress:string;integrations:IntegrationStatus;networks:Array<{asset:string;network:string;depositEnabled:boolean;withdrawalEnabled:boolean;withdrawalReviewEnabled:boolean;crossChain:boolean;unavailableReason?:string;withdrawalFeeMicro?:number}>;warnings:string[]};
export type Order={id:string;side:string;priceMicro:number;amountMicro:number;filledMicro:number;status:string;createdAt:string;authorizationDigest:string};
export type PublicTrade={id:string;priceMicro:number;amountMicro:number;createdAt:string;sourceType:string;sourceDigest:string};
export type PerpetualOrder={id:string;side:string;priceMicro:number;amountMicro:number;filledMicro:number;leverage:number;reduceOnly:boolean;status:string;createdAt:string;authorizationDigest:string};
export type MarginSnapshot={account:{collateralMicro:number;orderMarginMicro:number;positionMarginMicro:number};equityMicro:number;freeCollateralMicro:number;positions:Array<{market:string;sizeMicro:number;entryPriceMicro:number;markPriceMicro:number;unrealizedPnlMicro:number;leverage:number;status:string}>;orders:PerpetualOrder[]};
export type Account={balances:Array<{asset:string;availableMicro:number;reservedMicro:number}>;orders:Order[];trades:unknown[];fees:unknown[];ledger:unknown[];audit:unknown[];margin:MarginSnapshot;security:{withdrawalLock:boolean;orderConfirmation:boolean;sessionTtlMinutes:number}};
export async function publicState(){const [config,markets,book,tape,risk,perpetualBook]=await Promise.all([get<Config>("/v1/config"),get<any>("/v1/markets"),get<any>("/v1/orderbook"),get<{trades:PublicTrade[]}>("/v1/market-data/trades"),get<any>("/v1/risk"),get<any>("/v1/perpetual/orderbook")]);return{config,markets:markets.markets,book,trades:tape.trades,risk,perpetualBook}}
export async function account(session:CentralSession){return get<Account>("/v1/account",session,"exchange:read")}
export async function draftAI(session:CentralSession,prompt:string,language:string){return post("/v1/ai/drafts",session,"exchange:ai",{kind:"risk_explanation",prompt:`[output-language:${language}] ${prompt}`,contextClasses:["public_market_rules","owned_orders","owned_trades"],permission:true})}
export async function executeTradingAction(session:CentralSession,action:ExchangeOrderActionResponse){const request=tradingRequest(action);return post(request.path,session,"exchange:trade",request.body)}
async function get<T>(path:string,session?:CentralSession,scope?:string):Promise<T>{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),8000);try{const headers:Record<string,string>={};if(session&&scope)headers["X-YNX-Product-Session-Proof"]=await gatewayProof(session,scope);const response=await fetch(BASE+path,{headers,signal:controller.signal});const value=await response.json().catch(()=>({}));if(!response.ok)throw new Error(value.error||`Exchange returned ${response.status}`);return value as T}finally{clearTimeout(timer)}}
async function post(path:string,session:CentralSession,scope:string,body:unknown){const response=await fetch(BASE+path,{method:"POST",headers:{"X-YNX-Product-Session-Proof":await gatewayProof(session,scope),"content-type":"application/json"},body:JSON.stringify(body)});const value=await response.json().catch(()=>({}));if(!response.ok)throw new Error(value.error||`Exchange returned ${response.status}`);return value as any}
