import * as Crypto from "expo-crypto";
import * as Linking from "expo-linking";
import * as SecureStore from "expo-secure-store";
import {p256} from "@noble/curves/nist.js";
import {hexToBytes} from "@noble/hashes/utils.js";
import {canonicalJSON,createGatewayChallenge,createProductSessionProof,encodeExchangeOrderActionDeepLink,encodeRequestDeepLink,httpBodyDigest,parseCallbackURL,requestDigest,signGatewayChallenge,verifyAuthorization,verifyExchangeOrderActionResponse,type AuthorizationRequest,type AuthorizationResponse,type CentralWalletSession,type ExchangeActionName,type ExchangeActionParameters,type ExchangeOrderActionRequest,type ExchangeOrderActionResponse} from "@ynx-chain/wallet-auth";
import {BUNDLE_ID,CALLBACK,CLIENT_ID,SCOPES} from "./wallet-config";

const DEVICE="ynx-exchange-device-p256-v1", PENDING="ynx-exchange-wallet-request-v1", SESSION="ynx-exchange-central-session-v1",ACTION_PENDING="ynx-exchange-action-request-v1";
function encodeBase64url(bytes:Uint8Array){return btoa(String.fromCharCode(...bytes)).replace(/=+$/g,"").replace(/\+/g,"-").replace(/\//g,"_")}
function decodeBase64url(value:string){const normalized=value.replace(/-/g,"+").replace(/_/g,"/")+"=".repeat((4-value.length%4)%4);return Uint8Array.from(atob(normalized),character=>character.charCodeAt(0))}
export type CentralSession=CentralWalletSession;
async function deviceSecret(){let value=await SecureStore.getItemAsync(DEVICE);if(value&&/^[A-Za-z0-9_-]{43}$/.test(value)){const bytes=decodeBase64url(value);if(bytes.length===32&&p256.utils.isValidSecretKey(bytes))return value}if(value&&/^[0-9a-f]{64}$/.test(value)){const bytes=hexToBytes(value);if(p256.utils.isValidSecretKey(bytes)){value=encodeBase64url(bytes);await SecureStore.setItemAsync(DEVICE,value);return value}}for(;;){const bytes=await Crypto.getRandomBytesAsync(32);if(p256.utils.isValidSecretKey(bytes)){value=encodeBase64url(bytes);await SecureStore.setItemAsync(DEVICE,value);return value}}}
export async function beginWalletSignIn(){const secret=await deviceSecret();const now=new Date();const request:AuthorizationRequest={version:"1",nonce:encodeBase64url(await Crypto.getRandomBytesAsync(24)),chainId:"ynx_6423-1",requestingProduct:"exchange",productClientId:CLIENT_ID,bundleId:BUNDLE_ID,productDeviceAlgorithm:"p256-sha256",productDeviceKey:encodeBase64url(p256.getPublicKey(decodeBase64url(secret),true)),callback:CALLBACK,scopes:[...SCOPES],purpose:"Sign in to the YNX-owned deterministic testnet exchange; authorize only reviewed actions and never share a recovery key",issuedAt:now.toISOString(),expiresAt:new Date(now.getTime()+5*60_000).toISOString()};await SecureStore.setItemAsync(PENDING,JSON.stringify(request));await Linking.openURL(encodeRequestDeepLink(request));return request}
export async function finishWalletSignIn(url:string):Promise<CentralSession>{const raw=await SecureStore.getItemAsync(PENDING);if(!raw)throw new Error("No pending Wallet request exists.");const request=JSON.parse(raw) as AuthorizationRequest;const now=new Date(),approval=verifyAuthorization(parseCallbackURL(url,CALLBACK),{...request,requestDigest:requestDigest(request),now}) as AuthorizationResponse;const gateway=(process.env.EXPO_PUBLIC_YNX_EXCHANGE_GATEWAY_URL||"https://wallet-auth.ynxweb4.com").replace(/\/$/,"");const expiresAt=new Date(Math.min(Date.parse(approval.expiresAt),now.getTime()+120_000)).toISOString(),challenge=createGatewayChallenge(approval,{challenge:encodeBase64url(await Crypto.getRandomBytesAsync(24)),expiresAt},now),gatewayCompletion=signGatewayChallenge(challenge,await deviceSecret());const envelope=await post(`${gateway}/v1/wallet/sessions/complete`,{authorizationRequest:request,walletApproval:approval,gatewayCompletion});const session=envelope?.result as CentralSession;if(!envelope?.ok||!session?.sessionBinding)throw new Error("Central Gateway did not issue a canonical Product Session.");await SecureStore.setItemAsync(SESSION,canonicalJSON(session));await SecureStore.deleteItemAsync(PENDING);return session}
export async function restoreSession(){const raw=await SecureStore.getItemAsync(SESSION);if(!raw)return null;try{const v=JSON.parse(raw) as CentralSession;if(Date.parse(v.expiresAt)>Date.now())return v}catch{}await SecureStore.deleteItemAsync(SESSION);return null}
export async function signOut(){await SecureStore.deleteItemAsync(SESSION)}
export async function beginExchangeAction(session:CentralSession,action:ExchangeActionName,parameters:ExchangeActionParameters){const now=new Date(),request={version:"1",chainId:"ynx_6423-1",productClientId:CLIENT_ID,bundleId:BUNDLE_ID,callback:CALLBACK,sessionBinding:session.sessionBinding,account:session.account,action,parameters,nonce:encodeBase64url(await Crypto.getRandomBytesAsync(24)),issuedAt:now.toISOString(),expiresAt:new Date(now.getTime()+300_000).toISOString()} as ExchangeOrderActionRequest;await SecureStore.setItemAsync(ACTION_PENDING,canonicalJSON(request));await Linking.openURL(encodeExchangeOrderActionDeepLink(request));return request}
export async function pendingExchangeAction(){return(await SecureStore.getItemAsync(ACTION_PENDING))!==null}
export async function finishExchangeAction(url:string){const raw=await SecureStore.getItemAsync(ACTION_PENDING);if(!raw)throw new Error("No pending Exchange action exists on this device.");const request=JSON.parse(raw) as ExchangeOrderActionRequest,encoded=new URL(url).searchParams.get("response");if(!encoded)throw new Error("Wallet Exchange action response is missing.");let response:unknown;try{response=JSON.parse(new TextDecoder("utf-8",{fatal:true}).decode(decodeBase64url(encoded)))}catch{throw new Error("Wallet Exchange action response is invalid.")}return verifyExchangeOrderActionResponse(response,request,new Date()) as ExchangeOrderActionResponse}
export async function clearPendingExchangeAction(){await SecureStore.deleteItemAsync(ACTION_PENDING)}
export async function gatewayProof(session:CentralSession,scope:string){const body=canonicalJSON({requiredScopes:[scope]}),now=new Date(),expiresAt=new Date(Math.min(Date.parse(session.expiresAt),now.getTime()+30_000)).toISOString();if(Date.parse(expiresAt)<=now.getTime())throw new Error("Wallet session expired. Reauthorize in YNX Wallet.");const proof=createProductSessionProof(session,{method:"POST",path:"/v1/wallet/sessions/introspect",bodyDigest:httpBodyDigest(body),nonce:encodeBase64url(await Crypto.getRandomBytesAsync(24)),issuedAt:now.toISOString(),expiresAt},await deviceSecret());return encodeBase64url(new TextEncoder().encode(canonicalJSON(proof)))}
async function post(url:string,body:unknown){const response=await fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:canonicalJSON(body)});const value=await response.json().catch(()=>({}));if(!response.ok)throw new Error(value?.error?.message||`Central Gateway returned ${response.status}`);return value}
