export const supported=['en','zh-CN','zh-TW','ja','ko','es','fr','de','pt','ru','ar','id'];
const names={en:'Language','zh-CN':'语言','zh-TW':'語言',ja:'言語',ko:'언어',es:'Idioma',fr:'Langue',de:'Sprache',pt:'Idioma',ru:'Язык',ar:'اللغة',id:'Bahasa'};
const uiKeys=['wallet','profile','orders','cart','products','boundary','serviceStatus','trust','browse','compare','searchPlaceholder','search'];
const uiRows={
en:['Sign in with YNX Wallet','Profile','Orders','Cart','Products','Only committed Pay evidence marks an order paid. Seller-entered shipment data is labelled manual.','Service status','Seller policy and Trust evidence stay attached to the order timeline.','Browse by image, price, and availability','AI comparison','Search products and categories','Search'],
'zh-CN':['使用 YNX Wallet 登录','资料','订单','购物袋','商品','只有已提交的 Pay 证据才能将订单标记为已付款。卖家填写的物流信息会标记为手动且未验证。','服务状态','卖家政策与 Trust 证据会保留在订单时间线中。','按图片、价格与库存浏览','AI 比较','搜索商品和分类','搜索'],
'zh-TW':['使用 YNX Wallet 登入','資料','訂單','購物袋','商品','只有已提交的 Pay 證據才能將訂單標記為已付款。賣家填寫的物流資訊會標記為手動且未驗證。','服務狀態','賣家政策與 Trust 證據會保留在訂單時間軸中。','依圖片、價格與庫存瀏覽','AI 比較','搜尋商品與分類','搜尋'],
ja:['YNX Walletでサインイン','プロフィール','注文','バッグ','商品','コミット済みのPay証拠がある場合のみ支払い済みになります。販売者入力の配送情報は手動・未検証と表示されます。','サービス状況','販売者ポリシーとTrust証拠は注文タイムラインに保持されます。','画像・価格・在庫で探す','AI比較','商品とカテゴリを検索','検索'],
ko:['YNX Wallet로 로그인','프로필','주문','장바구니','상품','커밋된 Pay 증거가 있어야만 결제 완료로 표시됩니다. 판매자 입력 배송 정보는 수동·미검증으로 표시됩니다.','서비스 상태','판매자 정책과 Trust 증거는 주문 타임라인에 유지됩니다.','이미지, 가격, 재고로 탐색','AI 비교','상품 및 카테고리 검색','검색'],
es:['Iniciar sesión con YNX Wallet','Perfil','Pedidos','Bolsa','Productos','Solo la evidencia confirmada de Pay marca un pedido como pagado. El envío introducido por el vendedor se etiqueta como manual y no verificado.','Estado del servicio','La política del vendedor y la evidencia de Trust permanecen en la cronología del pedido.','Explorar por imagen, precio y disponibilidad','Comparación con IA','Buscar productos y categorías','Buscar'],
fr:['Se connecter avec YNX Wallet','Profil','Commandes','Panier','Produits','Seule une preuve Pay validée marque une commande comme payée. Le suivi saisi par le vendeur est indiqué comme manuel et non vérifié.','État du service','La politique du vendeur et les preuves Trust restent dans la chronologie de commande.','Parcourir par image, prix et disponibilité','Comparaison IA','Rechercher des produits et catégories','Rechercher'],
de:['Mit YNX Wallet anmelden','Profil','Bestellungen','Warenkorb','Produkte','Nur bestätigte Pay-Nachweise markieren eine Bestellung als bezahlt. Vom Verkäufer eingegebener Versand ist manuell und ungeprüft.','Dienststatus','Verkäuferrichtlinie und Trust-Nachweise bleiben in der Bestellchronik.','Nach Bild, Preis und Verfügbarkeit suchen','KI-Vergleich','Produkte und Kategorien suchen','Suchen'],
pt:['Entrar com YNX Wallet','Perfil','Pedidos','Sacola','Produtos','Somente evidência confirmada do Pay marca um pedido como pago. O envio informado pelo vendedor é manual e não verificado.','Estado do serviço','A política do vendedor e as evidências do Trust permanecem na linha do tempo do pedido.','Explorar por imagem, preço e disponibilidade','Comparação por IA','Buscar produtos e categorias','Buscar'],
ru:['Войти через YNX Wallet','Профиль','Заказы','Корзина','Товары','Заказ считается оплаченным только по подтвержденным данным Pay. Доставка от продавца помечается как ручная и непроверенная.','Состояние сервисов','Политика продавца и доказательства Trust сохраняются в истории заказа.','Поиск по изображению, цене и наличию','Сравнение ИИ','Искать товары и категории','Поиск'],
ar:['تسجيل الدخول عبر YNX Wallet','الملف الشخصي','الطلبات','الحقيبة','المنتجات','لا يُعد الطلب مدفوعًا إلا بدليل Pay مُعتمد. وتُوسم بيانات الشحن التي يُدخلها البائع بأنها يدوية وغير متحقق منها.','حالة الخدمات','تبقى سياسة البائع وأدلة Trust ضمن الخط الزمني للطلب.','تصفح حسب الصورة والسعر والتوفر','مقارنة بالذكاء الاصطناعي','ابحث في المنتجات والفئات','بحث'],
id:['Masuk dengan YNX Wallet','Profil','Pesanan','Tas','Produk','Pesanan hanya berstatus dibayar setelah bukti Pay tercatat. Pengiriman yang dimasukkan penjual diberi label manual dan belum diverifikasi.','Status layanan','Kebijakan penjual dan bukti Trust tetap ada di linimasa pesanan.','Jelajahi berdasarkan gambar, harga, dan ketersediaan','Perbandingan AI','Cari produk dan kategori','Cari']};
const ui=Object.fromEntries(supported.map(code=>[code,Object.fromEntries(uiKeys.map((key,index)=>[key,uiRows[code][index]]))]));
const navKeys=['discover','home','tech','outdoor','catalog','category','maxPrice','inStock','reset'];
const navRows={en:['Discover','Home','Tech','Outdoor','CATALOG','Category','Max price (YNXT)','In stock only','Reset filters'],'zh-CN':['发现','家居','科技','户外','商品目录','分类','最高价格（YNXT）','仅看有货','重置筛选'],'zh-TW':['探索','居家','科技','戶外','商品目錄','分類','最高價格（YNXT）','僅顯示有貨','重設篩選'],ja:['見つける','ホーム','テック','アウトドア','カタログ','カテゴリ','最高価格（YNXT）','在庫ありのみ','フィルターを解除'],ko:['둘러보기','홈','테크','아웃도어','카탈로그','카테고리','최대 가격(YNXT)','재고 있음만','필터 초기화'],es:['Descubrir','Hogar','Tecnología','Exterior','CATÁLOGO','Categoría','Precio máximo (YNXT)','Solo con stock','Restablecer filtros'],fr:['Découvrir','Maison','Tech','Plein air','CATALOGUE','Catégorie','Prix maximal (YNXT)','En stock uniquement','Réinitialiser'],de:['Entdecken','Zuhause','Technik','Outdoor','KATALOG','Kategorie','Höchstpreis (YNXT)','Nur verfügbar','Filter zurücksetzen'],pt:['Descobrir','Casa','Tecnologia','Ar livre','CATÁLOGO','Categoria','Preço máximo (YNXT)','Somente em estoque','Redefinir filtros'],ru:['Обзор','Дом','Техника','Туризм','КАТАЛОГ','Категория','Максимальная цена (YNXT)','Только в наличии','Сбросить фильтры'],ar:['استكشاف','المنزل','التقنية','الأنشطة الخارجية','الكتالوج','الفئة','السعر الأقصى (YNXT)','المتوفر فقط','إعادة ضبط عوامل التصفية'],id:['Jelajahi','Rumah','Teknologi','Luar ruang','KATALOG','Kategori','Harga maksimum (YNXT)','Hanya tersedia','Atur ulang filter']};
const navCopy=Object.fromEntries(supported.map(code=>[code,Object.fromEntries(navKeys.map((key,index)=>[key,navRows[code][index]]))]));
const normalize=v=>v?.startsWith('zh-Hant')||v==='zh-TW'?'zh-TW':v?.startsWith('zh')?'zh-CN':supported.find(c=>v?.toLowerCase().startsWith(c.toLowerCase()))||'en';let language=normalize(localStorage.getItem('ynx-ui-language')||navigator.language),aiLanguage=normalize(localStorage.getItem('ynx-ai-language')||language);
export const outputLanguage=()=>aiLanguage;export const formatAmount=v=>new Intl.NumberFormat(language,{maximumFractionDigits:8}).format(v);export const formatDate=v=>new Intl.DateTimeFormat(language,{dateStyle:'medium',timeStyle:'short'}).format(new Date(v));export const plural=(n,one,many)=>new Intl.PluralRules(language).select(n)==='one'?one:many;
const select=(label,current,change)=>{const e=document.createElement('select');e.setAttribute('aria-label',label);supported.forEach(c=>e.add(new Option(c,c,false,c===current)));e.onchange=()=>change(e.value);return e};
export function installI18n(){document.documentElement.lang=language;document.documentElement.dir=language==='ar'?'rtl':'ltr';const c=ui[language],n=navCopy[language];const set=(selector,value)=>{const node=document.querySelector(selector);if(node)node.textContent=value};const lead=(selector,value)=>{const node=document.querySelector(selector);if(node?.firstChild)node.firstChild.nodeValue=value+' '};set('.shopIntro h1',c.products);set('.introBoundary',c.boundary);set('.trust b',c.serviceStatus);set('.trust span:not(#capabilities)',c.trust);set('.sectionTitle h2',c.browse);set('.sectionTitle p',n.catalog);set('#compare',c.compare);set('#wallet',c.wallet);set('#profileButton',c.profile);set('#ordersButton',c.orders);lead('#cartButton',c.cart);for(const [value,key]of[['','discover'],['home','home'],['tech','tech'],['outdoor','outdoor']])set(`[data-category="${value}"]`,n[key]);const labels=document.querySelectorAll('#filters label');if(labels[0])lead('#filters label:nth-of-type(1)',n.category);if(labels[1])lead('#filters label:nth-of-type(2)',n.maxPrice);if(labels[2])labels[2].lastChild.nodeValue=' '+n.inStock;set('#filters button[type="reset"]',n.reset);const query=document.querySelector('#query');if(query)query.placeholder=c.searchPlaceholder;set('#search button',c.search);const host=document.querySelector('header')||document.body;host.append(select(names[language],language,v=>{localStorage.setItem('ynx-ui-language',v);location.reload()}));host.append(select(names[language]+' · AI',aiLanguage,v=>{aiLanguage=v;localStorage.setItem('ynx-ai-language',v)}));}
