import {createEncryptedVault,generateExtensionSecret} from "./extension-vault.js";

const api=globalThis.browser||globalThis.chrome,password=document.querySelector("#password"),secret=document.querySelector("#secret"),backup=document.querySelector("#backup"),recovery=document.querySelector("#recovery"),confirmed=document.querySelector("#confirmed"),save=document.querySelector("#save"),remove=document.querySelector("#remove"),status=document.querySelector("#status"),account=document.querySelector("#account");
let prepared=null;
function message(value,kind="info"){status.textContent=value;status.dataset.kind=kind}
function sensitiveClear(){password.value="";secret.value="";recovery.textContent="";prepared=null;confirmed.checked=false;save.disabled=true;backup.classList.add("hidden")}
async function runtime(input){const result=await api.runtime.sendMessage(input);if(result?.ok!==true)throw Object.assign(new Error(result?.error?.message||"Wallet vault request failed."),{code:result?.error?.code||"VAULT_RUNTIME_UNAVAILABLE"});return result}
async function refresh(){try{const result=await runtime({type:"YNX_VAULT_STATUS_V1"});account.textContent=result.configured?result.account:"No YNX extension account configured";remove.classList.toggle("hidden",!result.configured)}catch(error){account.textContent="Unavailable";message(`${error.code}: ${error.message}`,"error")}}
document.querySelector("#prepare").addEventListener("click",async()=>{try{const value=secret.value.trim().toLowerCase(),generated=value==="";if(password.value.length<12)throw Object.assign(new Error("Use at least 12 password characters."),{code:"VAULT_PASSWORD_INVALID"});prepared=generated?generateExtensionSecret():value;await createEncryptedVault({password:password.value,secretHex:prepared});recovery.textContent=prepared;backup.classList.remove("hidden");confirmed.checked=!generated;save.disabled=generated;message(generated?"Store the recovery key offline, then confirm.":"Import is ready. Save it into the encrypted browser vault.")}catch(error){sensitiveClear();message(`${error.code||"VAULT_PREPARE_FAILED"}: ${error.message}`,"error")}});
confirmed.addEventListener("change",()=>{save.disabled=!confirmed.checked||!prepared});
save.addEventListener("click",async()=>{try{save.disabled=true;const vault=await createEncryptedVault({password:password.value,secretHex:prepared});const result=await runtime({type:"YNX_VAULT_STORE_V1",vault});sensitiveClear();message(`Saved ${result.account}. Existing site permissions were revoked.`);await refresh()}catch(error){message(`${error.code||"VAULT_SAVE_FAILED"}: ${error.message}`,"error");save.disabled=false}});
remove.addEventListener("click",async()=>{if(!confirm("Remove this encrypted account and all site permissions from this browser profile?"))return;try{await runtime({type:"YNX_VAULT_REMOVE_V1"});sensitiveClear();message("Account and site permissions removed.");await refresh()}catch(error){message(`${error.code||"VAULT_REMOVE_FAILED"}: ${error.message}`,"error")}});
addEventListener("pagehide",sensitiveClear);void refresh();
