import {toYNXAddress} from "./wallet-address.js";
import {createEncryptedVault,generateExtensionSecret} from "./extension-vault.js";

const api=globalThis.browser||globalThis.chrome,password=document.querySelector("#password"),secret=document.querySelector("#secret"),backup=document.querySelector("#backup"),recovery=document.querySelector("#recovery"),confirmed=document.querySelector("#confirmed"),save=document.querySelector("#save"),remove=document.querySelector("#remove"),status=document.querySelector("#status"),account=document.querySelector("#account");
let prepared=null,transactionRecord=null,recoveryGeneration=0,recoveryRequest=null,recoveryBusy=false;
function message(value,kind="info"){status.textContent=value;status.dataset.kind=kind}
function sensitiveClear(){password.value="";secret.value="";recovery.textContent="";prepared=null;confirmed.checked=false;save.disabled=true;backup.classList.add("hidden")}
async function runtime(input){const result=await api.runtime.sendMessage(input);if(result?.ok!==true)throw Object.assign(new Error(result?.error?.message||"Wallet vault request failed."),{code:result?.error?.code||"VAULT_RUNTIME_UNAVAILABLE"});return result}
async function refresh(){const generation=recoveryGeneration;try{const result=await runtime({type:"YNX_VAULT_STATUS_V1"});if(generation!==recoveryGeneration)return;account.textContent=result.configured?toYNXAddress(result.account):"No YNX extension account configured";document.querySelector("#evm-account").textContent=result.configured?result.account:"Unavailable";document.querySelector("#copy-address").disabled=!result.configured;remove.classList.toggle("hidden",!result.configured);showTransaction(result.transaction)}catch(error){account.textContent="Unavailable";message(`${error.code}: ${error.message}`,"error")}}
document.querySelector("#prepare").addEventListener("click",async()=>{try{const value=secret.value.trim().toLowerCase(),generated=value==="";if(password.value.length<12)throw Object.assign(new Error("Use at least 12 password characters."),{code:"VAULT_PASSWORD_INVALID"});prepared=generated?generateExtensionSecret():value;await createEncryptedVault({password:password.value,secretHex:prepared});recovery.textContent=prepared;backup.classList.remove("hidden");confirmed.checked=!generated;save.disabled=generated;message(generated?"Store the recovery key offline, then confirm.":"Import is ready. Save it into the encrypted browser vault.")}catch(error){sensitiveClear();message(`${error.code||"VAULT_PREPARE_FAILED"}: ${error.message}`,"error")}});
confirmed.addEventListener("change",()=>{save.disabled=!confirmed.checked||!prepared});
save.addEventListener("click",async()=>{try{cancelRecovery();save.disabled=true;const vault=await createEncryptedVault({password:password.value,secretHex:prepared});const result=await runtime({type:"YNX_VAULT_STORE_V1",vault});sensitiveClear();message(`Saved ${toYNXAddress(result.account)}. Existing site permissions were revoked.`);await refresh()}catch(error){message(`${error.code||"VAULT_SAVE_FAILED"}: ${error.message}`,"error");save.disabled=false}});
remove.addEventListener("click",async()=>{if(!confirm("Remove this encrypted account and all site permissions from this browser profile?"))return;try{cancelRecovery();await runtime({type:"YNX_VAULT_REMOVE_V1"});sensitiveClear();message("Account and site permissions removed.");await refresh()}catch(error){message(`${error.code||"VAULT_REMOVE_FAILED"}: ${error.message}`,"error")}});
addEventListener("pagehide",()=>{cancelRecovery();sensitiveClear()});void refresh();

const checkButton=document.querySelector("#transaction-check"),retryButton=document.querySelector("#transaction-retry"),retryConfirm=document.querySelector("#transaction-retry-confirm"),retryPassword=document.querySelector("#transaction-password"),rpcConfirm=document.querySelector("#transaction-rpc-confirm"),cancelButton=document.querySelector("#transaction-cancel");
function ynxt(wei){const value=BigInt(wei),whole=value/10n**18n,fraction=(value%10n**18n).toString().padStart(18,"0").replace(/0+$/u,"");return whole.toString()+(fraction?"."+fraction:"")}
function updateRecoveryActions(){const pending=transactionRecord?.blocksNewSend===true,rpcReady=!transactionRecord?.rpcConfirmationRequired||rpcConfirm.checked;checkButton.disabled=recoveryBusy||!pending||!rpcReady;retryButton.disabled=recoveryBusy||!pending||!rpcReady||!retryConfirm.checked||retryPassword.value.length<12;cancelButton.classList.toggle("hidden",!recoveryRequest)}
function showTransaction(transaction){
  if(transactionRecord?.transactionHash!==transaction?.transactionHash||transactionRecord?.account!==transaction?.account){retryConfirm.checked=false;rpcConfirm.checked=false;retryPassword.value=""}
  transactionRecord=transaction||null;document.querySelector("#transaction").classList.toggle("hidden",!transaction);document.querySelector("#transaction-hash").textContent=transaction?.transactionHash||"";
  document.querySelector("#transaction-status").textContent=transaction?.durabilityConfirmed?((transaction.receiptStatus==="0x1"?"Transfer recorded":"Failed transfer recorded")+" in this node's durable local snapshot. This is not consensus finality."):transaction?(transaction.status+(transaction.blocksNewSend?" — original transaction unresolved; new sends blocked":"")):"";
  document.querySelector("#transaction-legacy").classList.toggle("hidden",!transaction?.legacyEvidenceUnavailable||transaction?.durabilityConfirmed);
  document.querySelector("#transaction-rpc-choice").classList.toggle("hidden",!transaction?.rpcConfirmationRequired);
  document.querySelector("#transaction-retry-panel").classList.toggle("hidden",!transaction?.blocksNewSend);
  const review=transaction?.review;document.querySelector("#transaction-review").textContent=review?[
    "From: "+toYNXAddress(review.from),"To: "+(review.to?toYNXAddress(review.to):"No recipient"),"Amount: "+ynxt(review.valueWei)+" YNXT","Ethereum nonce: "+review.nonce,
    "Maximum fee: "+(review.maximumFeeWei===null?"unavailable":ynxt(review.maximumFeeWei)+" YNXT"),"Network: YNX Testnet (6423)",
    "RPC: "+(transaction.rpcOrigin||"Original source unverified"),"Source site: "+(transaction.sourceOrigin||"Unverified older source")].join("\n"):"";
  updateRecoveryActions();
}
function recoveryTarget(){if(!transactionRecord?.blocksNewSend)throw Object.assign(new Error("No original transaction is awaiting recovery."),{code:"TRANSACTION_NOT_PENDING"});if(transactionRecord.rpcConfirmationRequired&&!rpcConfirm.checked)throw Object.assign(new Error("Select the configured RPC for this older record first."),{code:"RECOVERY_RPC_CONFIRMATION_REQUIRED"});return{account:transactionRecord.account,transactionHash:transactionRecord.transactionHash,...(transactionRecord.rpcConfirmationRequired?{selectedRpcOrigin:transactionRecord.configuredRpcOrigin}:{})}}
function cancelRecovery(){recoveryGeneration++;if(recoveryRequest)void api.runtime.sendMessage({type:"YNX_VAULT_TRANSACTION_CANCEL_V2",requestId:recoveryRequest}).catch(()=>{});recoveryRequest=null;recoveryBusy=false;retryPassword.value="";retryConfirm.checked=false;updateRecoveryActions()}
for(const[element,event]of[[retryConfirm,"change"],[rpcConfirm,"change"],[retryPassword,"input"]])element.addEventListener(event,updateRecoveryActions);
checkButton.addEventListener("click",async()=>{const generation=recoveryGeneration;try{const target=recoveryTarget();recoveryBusy=true;updateRecoveryActions();const result=await runtime({type:"YNX_VAULT_TRANSACTION_CHECK_V2",...target});if(generation===recoveryGeneration)showTransaction(result.transaction)}catch(error){if(generation===recoveryGeneration)message(error.code+": "+error.message,"error")}finally{if(generation===recoveryGeneration){recoveryBusy=false;updateRecoveryActions()}}});
retryButton.addEventListener("click",async()=>{
  const generation=recoveryGeneration;try{const target=recoveryTarget();if(!retryConfirm.checked||retryPassword.value.length<12)throw Object.assign(new Error("Review the original transaction and enter the vault password."),{code:"INVALID_RECOVERY_REQUEST"});
    recoveryRequest="recovery-"+crypto.randomUUID();recoveryBusy=true;updateRecoveryActions();const passwordValue=retryPassword.value;retryPassword.value="";
    const result=await runtime({type:"YNX_VAULT_TRANSACTION_RETRY_V2",...target,requestId:recoveryRequest,deadlineAt:Date.now()+120000,password:passwordValue,reviewed:true});
    if(generation===recoveryGeneration){showTransaction(result.transaction);message("The RPC acknowledged the original transaction. Check status for local durability evidence.")}
  }catch(error){if(generation===recoveryGeneration)message(error.code+": "+error.message,"error")}
  finally{if(generation===recoveryGeneration){recoveryRequest=null;recoveryBusy=false;retryPassword.value="";retryConfirm.checked=false;updateRecoveryActions()}}
});
cancelButton.addEventListener("click",()=>{cancelRecovery();message("Retry authorization cancelled. A submission already sent may still finish; check the original transaction.")});

document.querySelector("#copy-address").addEventListener("click",()=>{void navigator.clipboard.writeText(toYNXAddress(account.textContent)).then(()=>message("YNX address copied.")).catch(()=>message("Unable to copy the address.","error"))});
