const $=(s)=>document.querySelector(s);const $$=(s)=>[...document.querySelectorAll(s)];
const state={token:'',account:null,side:'buy',snapshot:null,book:null,publicTrades:[],config:null,solvency:null,risk:null,perpBook:null,activity:'trades'};
const micro=(v)=>Math.round(Number(v)*1e6);const display=(v,d=6)=>Number(v/1e6).toLocaleString(undefined,{maximumFractionDigits:d,minimumFractionDigits:Math.min(2,d)});
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),3500)}
async function api(path,options={}){const headers={'content-type':'application/json',...(options.headers||{})};if(state.token)headers.authorization=`Bearer ${state.token}`;const response=await fetch(`/api${path}`,{...options,headers});let body={};try{body=await response.json()}catch{}if(!response.ok)throw new Error(body.error||`Request failed (${response.status})`);return body}
function idempotency(prefix){return `${prefix}-${Date.now()}-${crypto.getRandomValues(new Uint32Array(1))[0]}`}
function requireCentralSession(){if(state.token)return true;$('#wallet-dialog').showModal();return false}

async function boot(){bind();try{[state.config,state.solvency,state.risk,state.perpBook]=await Promise.all([api('/v1/config'),api('/v1/solvency'),api('/v1/risk'),api('/v1/perpetual/orderbook')]);$('#custody-address').textContent=state.config.custodyAddress||'Not configured — deposits and withdrawals disabled';$('#withdraw-fee').textContent=`${display(withdrawFee())} YNXT`;renderSolvency();renderPerpetualPublic();await refreshBook()}catch(e){toast(e.message)}if(state.token)await refreshAccount()}
function bind(){
  $$('.topbar nav button').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
  $('#connect').addEventListener('click',()=>$('#wallet-dialog').showModal());
  $('#buy-tab').addEventListener('click',()=>setSide('buy'));$('#sell-tab').addEventListener('click',()=>setSide('sell'));
  $('#price').addEventListener('input',estimate);$('#amount').addEventListener('input',estimate);$('#withdraw-amount').addEventListener('input',withdrawEstimate);
  $('#order-form').addEventListener('submit',reviewOrder);$('#deposit-form').addEventListener('submit',observeDeposit);$('#withdraw-form').addEventListener('submit',reviewWithdrawal);
  $('#route-form').addEventListener('submit',quoteLiquidity);
  $('#refresh').addEventListener('click',refreshAll);$('#security-form').addEventListener('submit',saveSecurity);$('#support-form').addEventListener('submit',openSupport);
  $('#ai-submit').addEventListener('click',requestAI);$('#draft-order').addEventListener('click',()=>{showView('controls');$('#ai-kind').value='order_draft';$('#ai-prompt').focus()});
  $('#load-liability-proof').addEventListener('click',loadLiabilityProof);
  $('#perp-order-form').addEventListener('submit',reviewPerpetualOrder);$('#margin-deposit').addEventListener('click',reviewMarginTransfer);$('#margin-withdraw').addEventListener('click',reviewMarginTransfer);
  $$('.tabs button').forEach(b=>b.addEventListener('click',()=>{state.activity=b.dataset.activity;$$('.tabs button').forEach(x=>x.setAttribute('aria-selected',String(x===b)));renderActivity()}));
}
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.topbar nav button').forEach(b=>b.classList.toggle('nav-active',b.dataset.view===id));location.hash=id;document.title=`YNX Exchange — ${id[0].toUpperCase()+id.slice(1)}`}
function setSide(side){state.side=side;$('#buy-tab').setAttribute('aria-selected',side==='buy');$('#sell-tab').setAttribute('aria-selected',side==='sell');estimate()}
function estimate(){const p=micro($('#price').value||0),a=micro($('#amount').value||0);if(p<=0||a<=0){$('#reservation').textContent='—';return}if(state.side==='buy'){const q=Math.floor(a*p/1e6);$('#reservation').textContent=`${display(q+Math.ceil(q*.002))} YUSD_TEST max`}else{$('#reservation').textContent=`${display(a)} YNXT`}}
function withdrawFee(){return state.config?.networks?.find(n=>n.asset==='YNXT'&&n.network==='YNX Testnet')?.withdrawalFeeMicro||0}
function withdrawEstimate(){const a=micro($('#withdraw-amount').value||0),fee=withdrawFee();$('#withdraw-receive').textContent=a>fee?`${display(a-fee)} YNXT`:'—'}

async function refreshAll(){await Promise.all([refreshBook(),refreshPerpetual(),refreshAccount()])}
async function refreshBook(){try{const [book,tape]=await Promise.all([api('/v1/orderbook'),api('/v1/market-data/trades')]);state.book=book;state.publicTrades=tape.trades||[];renderBook();renderPublicMarket()}catch(e){toast(e.message)}}
async function refreshPerpetual(){try{[state.risk,state.perpBook]=await Promise.all([api('/v1/risk'),api('/v1/perpetual/orderbook')]);renderPerpetualPublic()}catch(e){toast(e.message)}}
async function refreshAccount(){if(!state.token)return;try{state.snapshot=await api('/v1/account');state.account=state.snapshot.balances[0]?.account;$('#connect').textContent=state.account?`${state.account.slice(0,8)}…${state.account.slice(-4)}`:'Wallet session';renderAccount()}catch(e){state.token='';$('#connect').textContent='Sign in with YNX Wallet';toast(e.message)}}
function renderBook(){renderRows('#asks',(state.book?.asks||[]).slice(0,7).reverse());renderRows('#bids',(state.book?.bids||[]).slice(0,7));const all=[...(state.book?.asks||[]),...(state.book?.bids||[])];$('#spread').textContent=all.length?'Owned venue open orders':'No public market depth'}
function renderRows(selector,rows){const root=$(selector);root.replaceChildren();if(!rows.length){const div=document.createElement('div');div.innerHTML='<span>—</span><span>—</span><span>—</span>';root.append(div);return}rows.forEach(o=>{const div=document.createElement('div');[display(o.priceMicro),display(o.amountMicro-o.filledMicro),display(Math.floor((o.amountMicro-o.filledMicro)*o.priceMicro/1e6))].forEach(v=>{const span=document.createElement('span');span.textContent=v;div.append(span)});root.append(div)})}
function renderAccount(){renderOrders();renderBalances();renderActivity();renderMargin();const s=state.snapshot.security;$('#withdraw-lock').checked=!!s.withdrawalLock;$('#session-ttl').value=String(s.sessionTtlMinutes||480);const volume=(state.snapshot.trades||[]).reduce((n,t)=>n+t.amountMicro,0);$('#owned-volume').textContent=volume?`${display(volume)} YNXT`:'—'}
function renderOrders(){const root=$('#orders');root.replaceChildren();const rows=(state.snapshot.orders||[]).filter(o=>['open','partially_filled'].includes(o.status));if(!rows.length){root.innerHTML='<tr><td colspan="6" class="empty-cell">No open orders. The venue does not seed fake depth.</td></tr>';return}rows.sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).forEach(o=>{const tr=document.createElement('tr');const values=[new Date(o.createdAt).toLocaleTimeString(),o.side,display(o.priceMicro),`${display(o.amountMicro)} / ${display(o.filledMicro)}`,o.status];values.forEach((v,i)=>{const td=document.createElement('td');td.textContent=v;if(i===4)td.className=`status-${o.status}`;tr.append(td)});const td=document.createElement('td');const btn=document.createElement('button');btn.className='text-button';btn.textContent='Cancel';btn.addEventListener('click',()=>cancelOrder(o));td.append(btn);tr.append(td);root.append(tr)})}
function renderBalances(){const root=$('#balances');root.replaceChildren();(state.snapshot.balances||[]).forEach(b=>{const div=document.createElement('div');div.className='balance-card';const title=document.createElement('strong');title.textContent=b.asset;const dl=document.createElement('dl');dl.innerHTML=`<div><dt>Available</dt><dd>${display(b.availableMicro)}</dd></div><div><dt>Reserved</dt><dd>${display(b.reservedMicro)}</dd></div>`;div.append(title,dl);root.append(div)})}
function renderPerpetualPublic(){const risk=state.risk||{},oracle=risk.oracle||{},market=risk.market||{};$('#perp-status').textContent=evidenceLabel(risk.status);$('#perp-mark').textContent=oracle.markPriceMicro?`${display(oracle.markPriceMicro)} YUSD_TEST`:'Unavailable';$('#perp-open-interest').textContent=`${display(market.openInterestMicro||0)} YNXT`;$('#perp-insurance').textContent=`${display(risk.insuranceFund?.balanceMicro||0)} YUSD_TEST`;$('#perp-risk-reason').textContent=risk.unavailableReason||market.circuitBreakerReason||'Oracle current · policy bands enforced';renderRows('#perp-asks',(state.perpBook?.asks||[]).slice(0,7).reverse());renderRows('#perp-bids',(state.perpBook?.bids||[]).slice(0,7))}
function renderMargin(){const margin=state.snapshot?.margin;if(!margin)return;const root=$('#margin-summary');root.replaceChildren();const summary=document.createElement('dl');summary.className='review';for(const [label,value] of [['Collateral',margin.account.collateralMicro],['Equity',margin.equityMicro],['Free collateral',margin.freeCollateralMicro],['Order margin',margin.account.orderMarginMicro],['Position margin',margin.account.positionMarginMicro]]){const row=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=`${display(value||0)} YUSD_TEST`;row.append(dt,dd);summary.append(row)}root.append(summary);const body=$('#perp-positions');body.replaceChildren();const positions=(margin.positions||[]).filter(p=>p.status==='open');if(!positions.length){body.innerHTML='<tr><td colspan="6" class="empty-cell">No open perpetual positions.</td></tr>';return}for(const p of positions){const row=document.createElement('tr');const values=[`${p.sizeMicro>0?'Long':'Short'} ${display(Math.abs(p.sizeMicro))}`,`${display(p.entryPriceMicro)} / ${display(p.markPriceMicro)}`,display(p.unrealizedPnlMicro),`${display(p.initialMarginMicro)} / ${display(p.maintenanceMarginMicro)}`,`${p.leverage}×`,p.status];for(const value of values){const cell=document.createElement('td');cell.textContent=value;row.append(cell)}body.append(row)}}
function evidenceLabel(value){return String(value||'unavailable').replaceAll('_',' ')}
function renderSolvency(){const report=state.solvency;if(!report)return;$('#liability-root').textContent=report.liabilityMerkleRoot;$('#liability-leaves').textContent=String(report.liabilityLeafCount);$('#solvency-status').textContent=evidenceLabel(report.status);$('#solvency-height').textContent=report.committedHeight?Number(report.committedHeight).toLocaleString():'Unavailable';$('#solvency-disclosure').textContent=report.disclosure;const root=$('#solvency-assets');root.replaceChildren();for(const asset of report.assets||[]){const panel=document.createElement('section');panel.className='panel solvency-asset';const header=document.createElement('header'),title=document.createElement('h2'),status=document.createElement('span');title.textContent=asset.asset;status.textContent=evidenceLabel(asset.assetProofStatus);header.append(title,status);const dl=document.createElement('dl');const rows=[['User liabilities',`${display(asset.liabilitiesMicro)} ${asset.asset}`],['Available / reserved',`${display(asset.availableLiabilitiesMicro)} / ${display(asset.reservedLiabilitiesMicro)}`],['Committed custody assets',asset.assetsMicro==null?'Unavailable':`${display(asset.assetsMicro)} ${asset.asset}`],['Reserve ratio',asset.reserveRatioBps==null?'Unavailable':`${(asset.reserveRatioBps/100).toFixed(2)}%`],['Withdrawal capacity',asset.withdrawalCapacityMicro==null?'Unavailable':`${display(asset.withdrawalCapacityMicro)} ${asset.asset}`]];for(const [label,value] of rows){const row=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;row.append(dt,dd);dl.append(row)}panel.append(header,dl);if(asset.unavailableReason){const note=document.createElement('p');note.className='source-note';note.textContent=asset.unavailableReason;panel.append(note)}root.append(panel)}}
async function loadLiabilityProof(){if(!requireCentralSession())return;const root=$('#liability-proof');root.textContent='Requesting Wallet-bound liability proof…';try{const proof=await api('/v1/solvency/liability-proof?asset=YNXT');root.replaceChildren();const summary=document.createElement('strong');summary.textContent=proof.verified?'Verified against the current Merkle root':'Verification failed';const details=document.createElement('p');details.textContent=`Leaf ${proof.leafIndex+1} of ${proof.leafCount} · ${display(proof.balance.availableMicro+proof.balance.reservedMicro)} YNXT · ${proof.proof.length} proof steps`;const code=document.createElement('code');code.textContent=proof.leafHash;root.append(summary,details,code)}catch(e){root.textContent=e.message}}
async function quoteLiquidity(event){event.preventDefault();const amount=micro($('#route-amount').value||0),side=$('#route-side').value,root=$('#route-result');if(amount<=0){root.textContent='Enter a positive YNXT amount.';return}root.textContent='Reading executable venue state…';try{const route=await api(`/v1/liquidity/quote?market=YNXT-YUSD_TEST&side=${encodeURIComponent(side)}&amountMicro=${amount}`);root.replaceChildren();const heading=document.createElement('strong');heading.textContent=route.selected?`Selected: ${route.selectedVenue}`:'No complete executable route';const disclosure=document.createElement('p');disclosure.textContent=route.disclosure;root.append(heading,disclosure);for(const candidate of route.candidates){const card=document.createElement('div');card.className=`route-candidate ${candidate.status}`;const name=document.createElement('strong');name.textContent=candidate.venue;const detail=document.createElement('span');detail.textContent=candidate.status==='available'?`${side==='buy'?'All-in spend':'All-in proceeds'} ${display(candidate.allInQuoteMicro)} YUSD_TEST · avg ${display(candidate.averagePriceMicro)} · fee ${display(candidate.cost.tradingFeeMicro)}`:candidate.unavailableReason;const factors=document.createElement('small');factors.textContent=(candidate.cost.unavailableFactors||[]).length?`Unmeasured: ${candidate.cost.unavailableFactors.join(', ')}`:'All configured cost factors available';card.append(name,detail,factors);root.append(card)}}catch(e){root.textContent=e.message}}
function renderActivity(){if(!state.snapshot)return;const head=$('#activity-head'),body=$('#activity-body');head.replaceChildren();body.replaceChildren();let rows=[],columns=[];if(state.activity==='trades'){columns=['Time','Side','Price','Amount','Fee'];rows=(state.snapshot.trades||[]).map(t=>[new Date(t.createdAt).toLocaleString(),t.buyer===state.account?'buy':'sell',display(t.priceMicro),display(t.amountMicro),display(t.buyer===state.account?t.buyerFeeMicro:t.sellerFeeMicro)])}else if(state.activity==='fees'){columns=['Time','Kind','Asset','Exact fee','Reference'];rows=(state.snapshot.fees||[]).map(f=>[new Date(f.createdAt).toLocaleString(),f.kind,f.asset,display(f.amountMicro),f.reference])}else{columns=['Time','Action','Object','Proof digest'];rows=(state.snapshot.audit||[]).map(a=>[new Date(a.createdAt).toLocaleString(),a.action,`${a.objectType}:${a.objectId}`,a.digest.slice(0,18)+'…'])}const tr=document.createElement('tr');columns.forEach(c=>{const th=document.createElement('th');th.textContent=c;tr.append(th)});head.append(tr);if(!rows.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=columns.length;td.className='empty-cell';td.textContent='No owned records yet.';tr.append(td);body.append(tr)}else rows.reverse().forEach(row=>{const tr=document.createElement('tr');row.forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td)});body.append(tr)})}
function renderPublicMarket(){const trades=[...state.publicTrades].sort((a,b)=>a.createdAt.localeCompare(b.createdAt));const body=$('#public-trades');body.replaceChildren();if(!trades.length){body.innerHTML='<tr><td colspan="5" class="empty-cell">No actual venue matches yet.</td></tr>';return}for(const trade of [...trades].reverse().slice(0,20)){const tr=document.createElement('tr');[new Date(trade.createdAt).toLocaleString(),display(trade.priceMicro),display(trade.amountMicro),trade.sourceType,trade.sourceDigest.slice(0,18)+'…'].forEach(value=>{const td=document.createElement('td');td.textContent=value;tr.append(td)});body.append(tr)}$('#chart-empty').hidden=true;const svg=$('#chart-svg');svg.hidden=false;const prices=trades.slice(-60).map(t=>t.priceMicro),lo=Math.min(...prices),hi=Math.max(...prices);const points=prices.map((p,i)=>`${30+i*(740/Math.max(1,prices.length-1))},${250-(p-lo)/Math.max(1,hi-lo)*210}`).join(' ');svg.replaceChildren();const polyline=document.createElementNS('http://www.w3.org/2000/svg','polyline');polyline.setAttribute('fill','none');polyline.setAttribute('stroke','#002FA7');polyline.setAttribute('stroke-width','4');polyline.setAttribute('points',points);const label=document.createElementNS('http://www.w3.org/2000/svg','text');label.setAttribute('x','30');label.setAttribute('y','25');label.setAttribute('fill','#667085');label.setAttribute('font-size','14');label.textContent='Actual YNX-owned matching-engine trades';svg.append(polyline,label);$('#last-price').textContent=`${display(prices.at(-1))} YUSD_TEST`}

function reviewOrder(event){event.preventDefault();requireCentralSession()}
function reviewPerpetualOrder(event){event.preventDefault();requireCentralSession()}
function reviewMarginTransfer(){requireCentralSession()}
function cancelOrder(){requireCentralSession()}
async function observeDeposit(event){event.preventDefault();if(!requireCentralSession())return}
function reviewWithdrawal(event){event.preventDefault();requireCentralSession()}
async function saveSecurity(event){event.preventDefault();requireCentralSession()}
async function openSupport(event){event.preventDefault();requireCentralSession()}
async function requestAI(){requireCentralSession()}
function renderAIState(r){const root=$('#ai-result');root.replaceChildren();const message=document.createElement('p');message.textContent=r.status==='permission_required'?'Permission is required before selected context can be sent.':`Provider unavailable: ${r.providerStatus}. Streaming did not start and no generated or canned result was substituted.`;root.append(message);for(const action of ['retry','cancel','reject','delete']){const button=document.createElement('button');button.className='text-button';button.textContent=action[0].toUpperCase()+action.slice(1);button.addEventListener('click',async()=>{try{const next=await api(`/v1/ai/drafts/${encodeURIComponent(r.id)}/actions`,{method:'POST',body:JSON.stringify({action})});renderAIState(next);await refreshAccount()}catch(e){toast(e.message)}});root.append(button)}}
boot();
