const $=(s)=>document.querySelector(s);const $$=(s)=>[...document.querySelectorAll(s)];
const state={account:null,side:'buy',snapshot:null,book:null,publicTrades:[],spotCandles:[],perpCandles:[],config:null,solvency:null,risk:null,perpBook:null,activity:'trades'};
const READ_RETRY_DELAYS=[0,600,1600];
const micro=(v)=>Math.round(Number(v)*1e6);const display=(v,d=6)=>Number(v/1e6).toLocaleString(undefined,{maximumFractionDigits:d,minimumFractionDigits:Math.min(2,d)});
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),3500)}
function wait(ms){return new Promise(resolve=>setTimeout(resolve,ms))}
function setNetworkStatus(message,stateName='live'){const label=$('#network-status'),root=label?.closest('.truth');if(label)label.textContent=message;if(root)root.dataset.network=stateName}
async function api(path,options={},scope=''){
  const method=String(options.method||'GET').toUpperCase(),readOnly=method==='GET',attempts=readOnly?READ_RETRY_DELAYS.length:1;
  for(let attempt=0;attempt<attempts;attempt++){
    if(attempt){setNetworkStatus(`Reconnecting ${attempt}/${attempts-1}…`,'retrying');await wait(READ_RETRY_DELAYS[attempt])}
    try{
      const headers={'content-type':'application/json',...(options.headers||{})};
      if(scope){const wallet=window.YNXExchangeWallet;if(!wallet)throw Object.assign(new Error('YNX Wallet integration is unavailable.'),{nonRetryable:true});try{headers['X-YNX-Product-Session-Proof']=await wallet.requireProof(scope)}catch(error){error.nonRetryable=true;throw error}}
      const response=await fetch(`/api${path}`,{...options,method,headers,signal:AbortSignal.timeout(10_000)});let body={};try{body=await response.json()}catch{}
      if(!response.ok){const error=new Error(body.error||`Request failed (${response.status})`);error.status=response.status;if(!readOnly||![502,503,504].includes(response.status)||attempt===attempts-1)throw error;continue}
      setNetworkStatus('YNX Testnet connected','live');return body
    }catch(error){if(!readOnly||error?.status||error?.nonRetryable||attempt===attempts-1){if(!error?.nonRetryable&&(!error?.status||[502,503,504].includes(error.status)))setNetworkStatus('Connection unavailable · Retry','offline');throw error}}
  }
  throw new Error('Read connection retry exhausted.')
}
function idempotency(prefix){return `${prefix}-${Date.now()}-${crypto.getRandomValues(new Uint32Array(1))[0]}`}
function requireCentralSession(){if(window.YNXExchangeWallet?.connected())return true;$('#wallet-dialog').showModal();return false}

async function boot(){bind();window.addEventListener('ynx-exchange-wallet-error',event=>toast(event.detail));try{await window.YNXExchangeWallet?.ready;const action=window.YNXExchangeWallet?.consumeActionResult();if(action)toast(`${evidenceLabel(action.kind)} accepted${action.record?.status?`: ${action.record.status}`:''}`);[state.config,state.solvency]=await Promise.all([api('/v1/config'),api('/v1/solvency')]);$('#custody-address').textContent=state.config.custodyAddress||'Not configured — deposits and withdrawals disabled';$('#withdraw-fee').textContent=`${display(withdrawFee())} YNXT`;renderSolvency();await Promise.all([refreshBook(),refreshPerpetual()])}catch(e){toast(e.message)}if(window.YNXExchangeWallet?.connected())await refreshAccount()}
function bind(){
  $$('.topbar nav button').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
  $('#connect').addEventListener('click',()=>$('#wallet-dialog').showModal());
  $('#buy-tab').addEventListener('click',()=>setSide('buy'));$('#sell-tab').addEventListener('click',()=>setSide('sell'));
  $('#price').addEventListener('input',estimate);$('#amount').addEventListener('input',estimate);$('#withdraw-amount').addEventListener('input',withdrawEstimate);
  $('#order-form').addEventListener('submit',reviewOrder);$('#deposit-form').addEventListener('submit',observeDeposit);$('#withdraw-form').addEventListener('submit',reviewWithdrawal);
  $('#route-form').addEventListener('submit',quoteLiquidity);
  $('#refresh').addEventListener('click',refreshAll);$('#security-form').addEventListener('submit',saveSecurity);$('#support-form').addEventListener('submit',openSupport);
  $('#network-retry').addEventListener('click',()=>refreshAll().catch(e=>toast(e.message)));
  $('#ai-submit').addEventListener('click',requestAI);$('#draft-order').addEventListener('click',()=>{showView('controls');$('#ai-kind').value='order_draft';$('#ai-prompt').focus()});
  $('#load-liability-proof').addEventListener('click',loadLiabilityProof);
  $('#perp-order-form').addEventListener('submit',reviewPerpetualOrder);$('#margin-deposit').addEventListener('click',reviewMarginTransfer);$('#margin-withdraw').addEventListener('click',reviewMarginTransfer);
  $('#spot-interval').addEventListener('change',refreshBook);$('#perp-interval').addEventListener('change',refreshPerpetual);
  $$('.tabs button').forEach(b=>b.addEventListener('click',()=>{state.activity=b.dataset.activity;$$('.tabs button').forEach(x=>x.setAttribute('aria-selected',String(x===b)));renderActivity()}));
}
window.addEventListener('online',()=>refreshAll().catch(e=>toast(e.message)));
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.topbar nav button').forEach(b=>b.classList.toggle('nav-active',b.dataset.view===id));location.hash=id;document.title=`YNX Exchange — ${id[0].toUpperCase()+id.slice(1)}`}
function setSide(side){state.side=side;$('#buy-tab').setAttribute('aria-selected',side==='buy');$('#sell-tab').setAttribute('aria-selected',side==='sell');estimate()}
function estimate(){const p=micro($('#price').value||0),a=micro($('#amount').value||0);if(p<=0||a<=0){$('#reservation').textContent='—';return}if(state.side==='buy'){const q=Math.floor(a*p/1e6);$('#reservation').textContent=`${display(q+Math.ceil(q*.002))} YUSD_TEST max`}else{$('#reservation').textContent=`${display(a)} YNXT`}}
function withdrawFee(){return state.config?.networks?.find(n=>n.asset==='YNXT'&&n.network==='YNX Testnet')?.withdrawalFeeMicro||0}
function withdrawEstimate(){const a=micro($('#withdraw-amount').value||0),fee=withdrawFee();$('#withdraw-receive').textContent=a>fee?`${display(a-fee)} YNXT`:'—'}

async function refreshAll(){await Promise.all([refreshBook(),refreshPerpetual(),refreshAccount()])}
async function refreshBook(){try{const interval=$('#spot-interval').value,[book,tape,candles]=await Promise.all([api('/v1/orderbook'),api('/v1/market-data/trades'),api(`/v1/market-data/candles?market=YNXT-YUSD_TEST&interval=${interval}&limit=120`)]);state.book=book;state.publicTrades=tape.trades||[];state.spotCandles=candles.candles||[];renderBook();renderPublicMarket();renderCandles('#chart-svg','#chart-empty',state.spotCandles,'Spot')}catch(e){toast(e.message)}}
async function refreshPerpetual(){try{const interval=$('#perp-interval').value,[risk,book,candles]=await Promise.all([api('/v1/risk'),api('/v1/perpetual/orderbook'),api(`/v1/market-data/candles?market=YNXT-YUSD_TEST-PERP&interval=${interval}&limit=120`)]);state.risk=risk;state.perpBook=book;state.perpCandles=candles.candles||[];renderPerpetualPublic();renderCandles('#perp-chart-svg','#perp-chart-empty',state.perpCandles,'Perpetual')}catch(e){toast(e.message)}}
async function refreshAccount(){if(!window.YNXExchangeWallet?.connected())return;try{state.snapshot=await api('/v1/account',{},'exchange:read');state.account=window.YNXExchangeWallet.session()?.account||state.snapshot.balances[0]?.account;$('#connect').textContent=state.account?`${state.account.slice(0,8)}…${state.account.slice(-4)}`:'Wallet session';renderAccount()}catch(e){$('#connect').textContent='Sign in with YNX Wallet';toast(e.message)}}
function renderBook(){renderRows('#asks',(state.book?.asks||[]).slice(0,7).reverse());renderRows('#bids',(state.book?.bids||[]).slice(0,7));const all=[...(state.book?.asks||[]),...(state.book?.bids||[])];$('#spread').textContent=all.length?'Owned venue open orders':'No public market depth'}
function renderRows(selector,rows){const root=$(selector);root.replaceChildren();if(!rows.length){const div=document.createElement('div');div.innerHTML='<span>—</span><span>—</span><span>—</span>';root.append(div);return}rows.forEach(o=>{const div=document.createElement('div');[display(o.priceMicro),display(o.amountMicro-o.filledMicro),display(Math.floor((o.amountMicro-o.filledMicro)*o.priceMicro/1e6))].forEach(v=>{const span=document.createElement('span');span.textContent=v;div.append(span)});root.append(div)})}
function renderAccount(){renderOrders();renderBalances();renderActivity();renderMargin();const s=state.snapshot.security;$('#withdraw-lock').checked=!!s.withdrawalLock;$('#session-ttl').value=String(s.sessionTtlMinutes||480);const volume=(state.snapshot.trades||[]).reduce((n,t)=>n+t.amountMicro,0);$('#owned-volume').textContent=volume?`${display(volume)} YNXT`:'—'}
function renderOrders(){const root=$('#orders');root.replaceChildren();const rows=(state.snapshot.orders||[]).filter(o=>['open','partially_filled'].includes(o.status));if(!rows.length){root.innerHTML='<tr><td colspan="6" class="empty-cell">No open orders. The venue does not seed fake depth.</td></tr>';return}rows.sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).forEach(o=>{const tr=document.createElement('tr');const values=[new Date(o.createdAt).toLocaleTimeString(),o.side,display(o.priceMicro),`${display(o.amountMicro)} / ${display(o.filledMicro)}`,o.status];values.forEach((v,i)=>{const td=document.createElement('td');td.textContent=v;if(i===4)td.className=`status-${o.status}`;tr.append(td)});const td=document.createElement('td');const btn=document.createElement('button');btn.className='text-button';btn.textContent='Cancel';btn.addEventListener('click',()=>cancelOrder(o));td.append(btn);tr.append(td);root.append(tr)})}
function renderBalances(){const root=$('#balances');root.replaceChildren();(state.snapshot.balances||[]).forEach(b=>{const div=document.createElement('div');div.className='balance-card';const title=document.createElement('strong');title.textContent=b.asset;const dl=document.createElement('dl');dl.innerHTML=`<div><dt>Available</dt><dd>${display(b.availableMicro)}</dd></div><div><dt>Reserved</dt><dd>${display(b.reservedMicro)}</dd></div>`;div.append(title,dl);root.append(div)})}
function renderPerpetualPublic(){const risk=state.risk||{},oracle=risk.oracle||{},market=risk.market||{};$('#perp-status').textContent=evidenceLabel(risk.status);$('#perp-mark').textContent=oracle.markPriceMicro?`${display(oracle.markPriceMicro)} YUSD_TEST`:'Unavailable';$('#perp-open-interest').textContent=`${display(market.openInterestMicro||0)} YNXT`;$('#perp-insurance').textContent=`${display(risk.insuranceFund?.balanceMicro||0)} YUSD_TEST`;$('#perp-risk-reason').textContent=risk.unavailableReason||market.circuitBreakerReason||'Oracle current · policy bands enforced';renderRows('#perp-asks',(state.perpBook?.asks||[]).slice(0,7).reverse());renderRows('#perp-bids',(state.perpBook?.bids||[]).slice(0,7))}
function renderMargin(){const margin=state.snapshot?.margin;if(!margin)return;const root=$('#margin-summary');root.replaceChildren();const summary=document.createElement('dl');summary.className='review';for(const [label,value] of [['Collateral',margin.account.collateralMicro],['Equity',margin.equityMicro],['Free collateral',margin.freeCollateralMicro],['Order margin',margin.account.orderMarginMicro],['Position margin',margin.account.positionMarginMicro]]){const row=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=`${display(value||0)} YUSD_TEST`;row.append(dt,dd);summary.append(row)}root.append(summary);const body=$('#perp-positions');body.replaceChildren();const positions=(margin.positions||[]).filter(p=>p.status==='open');if(!positions.length)body.innerHTML='<tr><td colspan="6" class="empty-cell">No open perpetual positions.</td></tr>';else for(const p of positions){const row=document.createElement('tr');const values=[`${p.sizeMicro>0?'Long':'Short'} ${display(Math.abs(p.sizeMicro))}`,`${display(p.entryPriceMicro)} / ${display(p.markPriceMicro)}`,display(p.unrealizedPnlMicro),`${display(p.initialMarginMicro)} / ${display(p.maintenanceMarginMicro)}`,`${p.leverage}×`,p.status];for(const value of values){const cell=document.createElement('td');cell.textContent=value;row.append(cell)}body.append(row)}const ordersRoot=$('#perp-orders');ordersRoot.replaceChildren();const orders=(margin.orders||[]).filter(o=>['open','partially_filled'].includes(o.status));if(!orders.length)ordersRoot.innerHTML='<tr><td colspan="7" class="empty-cell">No open perpetual orders.</td></tr>';else for(const o of orders.sort((a,b)=>b.createdAt.localeCompare(a.createdAt))){const row=document.createElement('tr');for(const value of [new Date(o.createdAt).toLocaleTimeString(),o.side,display(o.priceMicro),`${display(o.amountMicro)} / ${display(o.filledMicro)}`,`${o.leverage}×`,o.reduceOnly?'Reduce only':'May increase']){const cell=document.createElement('td');cell.textContent=value;row.append(cell)}const action=document.createElement('td'),button=document.createElement('button');button.className='text-button';button.textContent='Cancel';button.addEventListener('click',()=>cancelPerpetualOrder(o));action.append(button);row.append(action);ordersRoot.append(row)}}
function evidenceLabel(value){return String(value||'unavailable').replaceAll('_',' ')}
function renderSolvency(){const report=state.solvency;if(!report)return;$('#liability-root').textContent=report.liabilityMerkleRoot;$('#liability-leaves').textContent=String(report.liabilityLeafCount);$('#solvency-status').textContent=evidenceLabel(report.status);$('#solvency-height').textContent=report.committedHeight?Number(report.committedHeight).toLocaleString():'Unavailable';$('#solvency-disclosure').textContent=report.disclosure;const root=$('#solvency-assets');root.replaceChildren();for(const asset of report.assets||[]){const panel=document.createElement('section');panel.className='panel solvency-asset';const header=document.createElement('header'),title=document.createElement('h2'),status=document.createElement('span');title.textContent=asset.asset;status.textContent=evidenceLabel(asset.assetProofStatus);header.append(title,status);const dl=document.createElement('dl');const rows=[['User liabilities',`${display(asset.liabilitiesMicro)} ${asset.asset}`],['Available / reserved',`${display(asset.availableLiabilitiesMicro)} / ${display(asset.reservedLiabilitiesMicro)}`],['Committed custody assets',asset.assetsMicro==null?'Unavailable':`${display(asset.assetsMicro)} ${asset.asset}`],['Reserve ratio',asset.reserveRatioBps==null?'Unavailable':`${(asset.reserveRatioBps/100).toFixed(2)}%`],['Withdrawal capacity',asset.withdrawalCapacityMicro==null?'Unavailable':`${display(asset.withdrawalCapacityMicro)} ${asset.asset}`]];for(const [label,value] of rows){const row=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;row.append(dt,dd);dl.append(row)}panel.append(header,dl);if(asset.unavailableReason){const note=document.createElement('p');note.className='source-note';note.textContent=asset.unavailableReason;panel.append(note)}root.append(panel)}}
async function loadLiabilityProof(){if(!requireCentralSession())return;const root=$('#liability-proof');root.textContent='Requesting Wallet-bound liability proof…';try{const proof=await api('/v1/solvency/liability-proof?asset=YNXT',{},'exchange:read');root.replaceChildren();const summary=document.createElement('strong');summary.textContent=proof.verified?'Verified against the current Merkle root':'Verification failed';const details=document.createElement('p');details.textContent=`Leaf ${proof.leafIndex+1} of ${proof.leafCount} · ${display(proof.balance.availableMicro+proof.balance.reservedMicro)} YNXT · ${proof.proof.length} proof steps`;const code=document.createElement('code');code.textContent=proof.leafHash;root.append(summary,details,code)}catch(e){root.textContent=e.message}}
async function quoteLiquidity(event){event.preventDefault();const amount=micro($('#route-amount').value||0),side=$('#route-side').value,root=$('#route-result');if(amount<=0){root.textContent='Enter a positive YNXT amount.';return}root.textContent='Reading executable venue state…';try{const route=await api(`/v1/liquidity/quote?market=YNXT-YUSD_TEST&side=${encodeURIComponent(side)}&amountMicro=${amount}`);root.replaceChildren();const heading=document.createElement('strong');heading.textContent=route.selected?`Selected: ${route.selectedVenue}`:'No complete executable route';const disclosure=document.createElement('p');disclosure.textContent=route.disclosure;root.append(heading,disclosure);for(const candidate of route.candidates){const card=document.createElement('div');card.className=`route-candidate ${candidate.status}`;const name=document.createElement('strong');name.textContent=candidate.venue;const detail=document.createElement('span');detail.textContent=candidate.status==='available'?`${side==='buy'?'All-in spend':'All-in proceeds'} ${display(candidate.allInQuoteMicro)} YUSD_TEST · avg ${display(candidate.averagePriceMicro)} · fee ${display(candidate.cost.tradingFeeMicro)}`:candidate.unavailableReason;const factors=document.createElement('small');factors.textContent=(candidate.cost.unavailableFactors||[]).length?`Unmeasured: ${candidate.cost.unavailableFactors.join(', ')}`:'All configured cost factors available';card.append(name,detail,factors);root.append(card)}}catch(e){root.textContent=e.message}}
function renderActivity(){if(!state.snapshot)return;const head=$('#activity-head'),body=$('#activity-body');head.replaceChildren();body.replaceChildren();let rows=[],columns=[];if(state.activity==='trades'){columns=['Time','Side','Price','Amount','Fee'];rows=(state.snapshot.trades||[]).map(t=>[new Date(t.createdAt).toLocaleString(),t.buyer===state.account?'buy':'sell',display(t.priceMicro),display(t.amountMicro),display(t.buyer===state.account?t.buyerFeeMicro:t.sellerFeeMicro)])}else if(state.activity==='fees'){columns=['Time','Kind','Asset','Exact fee','Reference'];rows=(state.snapshot.fees||[]).map(f=>[new Date(f.createdAt).toLocaleString(),f.kind,f.asset,display(f.amountMicro),f.reference])}else{columns=['Time','Action','Object','Proof digest'];rows=(state.snapshot.audit||[]).map(a=>[new Date(a.createdAt).toLocaleString(),a.action,`${a.objectType}:${a.objectId}`,a.digest.slice(0,18)+'…'])}const tr=document.createElement('tr');columns.forEach(c=>{const th=document.createElement('th');th.textContent=c;tr.append(th)});head.append(tr);if(!rows.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=columns.length;td.className='empty-cell';td.textContent='No owned records yet.';tr.append(td);body.append(tr)}else rows.reverse().forEach(row=>{const tr=document.createElement('tr');row.forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td)});body.append(tr)})}
function renderPublicMarket(){const trades=[...state.publicTrades].sort((a,b)=>a.createdAt.localeCompare(b.createdAt));const body=$('#public-trades');body.replaceChildren();if(!trades.length){body.innerHTML='<tr><td colspan="5" class="empty-cell">No actual venue matches yet.</td></tr>';return}for(const trade of [...trades].reverse().slice(0,20)){const tr=document.createElement('tr');[new Date(trade.createdAt).toLocaleString(),display(trade.priceMicro),display(trade.amountMicro),trade.sourceType,trade.sourceDigest.slice(0,18)+'…'].forEach(value=>{const td=document.createElement('td');td.textContent=value;tr.append(td)});body.append(tr)}$('#last-price').textContent=`${display(trades.at(-1).priceMicro)} YUSD_TEST`}
function renderCandles(svgSelector,emptySelector,candles,label){const svg=$(svgSelector),empty=$(emptySelector);svg.replaceChildren();if(!candles.length){svg.hidden=true;empty.hidden=false;return}svg.hidden=false;empty.hidden=true;const width=Number(svg.viewBox.baseVal.width)||800,height=Number(svg.viewBox.baseVal.height)||280,pad={left:64,right:18,top:26,bottom:34};const lows=candles.map(c=>c.lowMicro),highs=candles.map(c=>c.highMicro),lo=Math.min(...lows),hi=Math.max(...highs),range=Math.max(1,hi-lo),plotW=width-pad.left-pad.right,plotH=height-pad.top-pad.bottom,step=plotW/Math.max(1,candles.length),bodyWidth=Math.max(2,Math.min(14,step*.62)),y=p=>pad.top+(hi-p)/range*plotH,ns='http://www.w3.org/2000/svg';for(let i=0;i<5;i++){const value=hi-range*i/4,line=document.createElementNS(ns,'line'),text=document.createElementNS(ns,'text'),yy=pad.top+plotH*i/4;line.setAttribute('x1',pad.left);line.setAttribute('x2',width-pad.right);line.setAttribute('y1',yy);line.setAttribute('y2',yy);line.setAttribute('class','chart-grid');text.setAttribute('x',pad.left-8);text.setAttribute('y',yy+4);text.setAttribute('text-anchor','end');text.setAttribute('class','chart-axis');text.textContent=display(value,4);svg.append(line,text)}candles.forEach((c,i)=>{const x=pad.left+step*(i+.5),up=c.closeMicro>=c.openMicro,color=up?'#087a55':'#c0342b',wick=document.createElementNS(ns,'line'),body=document.createElementNS(ns,'rect');wick.setAttribute('x1',x);wick.setAttribute('x2',x);wick.setAttribute('y1',y(c.highMicro));wick.setAttribute('y2',y(c.lowMicro));wick.setAttribute('stroke',color);wick.setAttribute('stroke-width','1.5');const top=Math.min(y(c.openMicro),y(c.closeMicro)),bodyHeight=Math.max(2,Math.abs(y(c.openMicro)-y(c.closeMicro)));body.setAttribute('x',x-bodyWidth/2);body.setAttribute('y',top);body.setAttribute('width',bodyWidth);body.setAttribute('height',bodyHeight);body.setAttribute('fill',up?'#d8f3e8':color);body.setAttribute('stroke',color);body.setAttribute('aria-label',`${new Date(c.openTime).toLocaleString()} open ${display(c.openMicro)} high ${display(c.highMicro)} low ${display(c.lowMicro)} close ${display(c.closeMicro)} volume ${display(c.baseVolumeMicro)} trades ${c.trades}`);svg.append(wick,body)});const source=document.createElementNS(ns,'text');source.setAttribute('x',pad.left);source.setAttribute('y',height-8);source.setAttribute('class','chart-axis');source.textContent=`${label} · ${candles.length} non-empty intervals · persisted fills only`;svg.append(source)}

async function reviewOrder(event){event.preventDefault();if(!requireCentralSession())return;const priceMicro=micro($('#price').value),amountMicro=micro($('#amount').value);if(!Number.isSafeInteger(priceMicro)||!Number.isSafeInteger(amountMicro)||priceMicro<=0||amountMicro<=0){toast('Enter a positive limit price and amount.');return}try{await window.YNXExchangeWallet.placeSpotOrder({market:'YNXT-YUSD_TEST',side:state.side,type:'limit',priceMicro,amountMicro,idempotencyKey:idempotency('spot-order')})}catch(e){toast(e.message)}}
async function reviewPerpetualOrder(event){event.preventDefault();if(!requireCentralSession())return;const priceMicro=micro($('#perp-price').value),amountMicro=micro($('#perp-amount').value),leverage=Number($('#perp-leverage').value);if(!Number.isSafeInteger(priceMicro)||!Number.isSafeInteger(amountMicro)||priceMicro<=0||amountMicro<=0){toast('Enter a positive perpetual limit price and amount.');return}try{await window.YNXExchangeWallet.placePerpetualOrder({market:'YNXT-YUSD_TEST-PERP',side:$('#perp-side').value,type:'limit',timeInForce:'gtc',priceMicro,amountMicro,leverage,reduceOnly:$('#perp-reduce-only').checked,idempotencyKey:idempotency('perpetual-order')})}catch(e){toast(e.message)}}
async function reviewMarginTransfer(event){if(!requireCentralSession())return;const amountMicro=micro($('#margin-amount').value),direction=event.currentTarget.id==='margin-deposit'?'deposit':'withdraw';if(!Number.isSafeInteger(amountMicro)||amountMicro<=0){toast('Enter a positive YUSD_TEST margin transfer amount.');return}try{await window.YNXExchangeWallet.transferMargin({direction,amountMicro,idempotencyKey:idempotency(`margin-${direction}`)})}catch(e){toast(e.message)}}
async function cancelOrder(order){if(!requireCentralSession())return;try{await window.YNXExchangeWallet.cancelSpotOrder(order.id,idempotency('spot-cancel'))}catch(e){toast(e.message)}}
async function cancelPerpetualOrder(order){if(!requireCentralSession())return;try{await window.YNXExchangeWallet.cancelPerpetualOrder(order.id,idempotency('perpetual-cancel'))}catch(e){toast(e.message)}}
async function observeDeposit(event){event.preventDefault();if(!requireCentralSession())return}
function reviewWithdrawal(event){event.preventDefault();requireCentralSession()}
async function saveSecurity(event){event.preventDefault();requireCentralSession()}
async function openSupport(event){event.preventDefault();requireCentralSession()}
async function requestAI(){requireCentralSession()}
function renderAIState(r){const root=$('#ai-result');root.replaceChildren();const message=document.createElement('p');message.textContent=r.status==='permission_required'?'Permission is required before selected context can be sent.':`Provider unavailable: ${r.providerStatus}. Streaming did not start and no generated or canned result was substituted.`;root.append(message);for(const action of ['retry','cancel','reject','delete']){const button=document.createElement('button');button.className='text-button';button.textContent=action[0].toUpperCase()+action.slice(1);button.addEventListener('click',async()=>{try{const next=await api(`/v1/ai/drafts/${encodeURIComponent(r.id)}/actions`,{method:'POST',body:JSON.stringify({action})});renderAIState(next);await refreshAccount()}catch(e){toast(e.message)}});root.append(button)}}
boot();
