const $=(s)=>document.querySelector(s);const $$=(s)=>[...document.querySelectorAll(s)];
const state={token:sessionStorage.getItem('ynx.exchange.session')||'',account:null,side:'buy',snapshot:null,book:null,config:null,activity:'trades'};
const micro=(v)=>Math.round(Number(v)*1e6);const display=(v,d=6)=>Number(v/1e6).toLocaleString(undefined,{maximumFractionDigits:d,minimumFractionDigits:Math.min(2,d)});
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),3500)}
async function api(path,options={}){const headers={'content-type':'application/json',...(options.headers||{})};if(state.token)headers.authorization=`Bearer ${state.token}`;const response=await fetch(`/api${path}`,{...options,headers});let body={};try{body=await response.json()}catch{}if(!response.ok)throw new Error(body.error||`Request failed (${response.status})`);return body}
function idempotency(prefix){return `${prefix}-${Date.now()}-${crypto.getRandomValues(new Uint32Array(1))[0]}`}
function walletURI(action,payload){const callback='ynxexchange://wallet/callback';return `ynxwallet://authorize?client_id=ynx.exchange&chain_id=ynx_6423-1&callback=${encodeURIComponent(callback)}&action=${encodeURIComponent(action)}&payload=${encodeURIComponent(btoa(unescape(encodeURIComponent(payload))))}`}
function openWalletAction(action,payload,request){sessionStorage.setItem('ynx.exchange.pending',JSON.stringify({action,payload,request}));location.href=walletURI(action,payload);toast('Review the exact action in YNX Wallet. Nothing executes without a returned signature.')}

async function boot(){bind();try{state.config=await api('/v1/config');$('#custody-address').textContent=state.config.custodyAddress||'Not configured — deposits and withdrawals disabled';$('#withdraw-fee').textContent=`${display(withdrawFee())} YNXT`;await refreshBook()}catch(e){toast(e.message)}if(state.token)await refreshAccount();consumeWalletCallback()}
function bind(){
  $$('.topbar nav button').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
  $('#connect').addEventListener('click',()=>$('#wallet-dialog').showModal());
  $('#wallet-request').addEventListener('click',requestChallenge);$('#accept-token').addEventListener('click',acceptToken);
  $('#buy-tab').addEventListener('click',()=>setSide('buy'));$('#sell-tab').addEventListener('click',()=>setSide('sell'));
  $('#price').addEventListener('input',estimate);$('#amount').addEventListener('input',estimate);$('#withdraw-amount').addEventListener('input',withdrawEstimate);
  $('#order-form').addEventListener('submit',reviewOrder);$('#deposit-form').addEventListener('submit',observeDeposit);$('#withdraw-form').addEventListener('submit',reviewWithdrawal);
  $('#refresh').addEventListener('click',refreshAll);$('#security-form').addEventListener('submit',saveSecurity);$('#support-form').addEventListener('submit',openSupport);
  $('#ai-submit').addEventListener('click',requestAI);$('#draft-order').addEventListener('click',()=>{showView('controls');$('#ai-kind').value='order_draft';$('#ai-prompt').focus()});
  $$('.tabs button').forEach(b=>b.addEventListener('click',()=>{state.activity=b.dataset.activity;$$('.tabs button').forEach(x=>x.setAttribute('aria-selected',String(x===b)));renderActivity()}));
}
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.topbar nav button').forEach(b=>b.classList.toggle('nav-active',b.dataset.view===id));location.hash=id;document.title=`YNX Exchange — ${id[0].toUpperCase()+id.slice(1)}`}
function setSide(side){state.side=side;$('#buy-tab').setAttribute('aria-selected',side==='buy');$('#sell-tab').setAttribute('aria-selected',side==='sell');estimate()}
function estimate(){const p=micro($('#price').value||0),a=micro($('#amount').value||0);if(p<=0||a<=0){$('#reservation').textContent='—';return}if(state.side==='buy'){const q=Math.floor(a*p/1e6);$('#reservation').textContent=`${display(q+Math.ceil(q*.002))} YUSD_TEST max`}else{$('#reservation').textContent=`${display(a)} YNXT`}}
function withdrawFee(){return state.config?.networks?.find(n=>n.asset==='YNXT'&&n.network==='YNX Testnet')?.withdrawalFeeMicro||0}
function withdrawEstimate(){const a=micro($('#withdraw-amount').value||0),fee=withdrawFee();$('#withdraw-receive').textContent=a>fee?`${display(a-fee)} YNXT`:'—'}

async function requestChallenge(){try{const account=$('#wallet-account').value.trim(),deviceId=$('#device-id').value.trim();const c=await api('/v1/auth/challenges',{method:'POST',body:JSON.stringify({account,deviceId,scopes:['exchange:read','exchange:trade','exchange:withdraw','exchange:ai']})});$('#wallet-state').textContent=`Challenge ${c.id} expires ${new Date(c.expiresAt).toLocaleTimeString()}. Review scopes and callback in Wallet.`;sessionStorage.setItem('ynx.exchange.challenge',JSON.stringify(c));location.href=walletURI('sign_in',new TextDecoder().decode(new TextEncoder().encode(JSON.stringify(c))))}catch(e){$('#wallet-state').textContent=e.message}}
async function acceptToken(){const token=$('#session-token').value.trim();if(!token)return;state.token=token;sessionStorage.setItem('ynx.exchange.session',token);$('#wallet-dialog').close();await refreshAccount();toast('Wallet-bound Exchange session active')}
function consumeWalletCallback(){const params=new URLSearchParams(location.search);const token=params.get('session_token'),signature=params.get('wallet_signature');if(token){$('#session-token').value=token;$('#wallet-dialog').showModal()}if(signature){const raw=sessionStorage.getItem('ynx.exchange.pending');if(raw){const pending=JSON.parse(raw);executeAuthorized(pending,signature).catch(e=>toast(e.message))}}if(token||signature)history.replaceState({},'',location.pathname+location.hash)}
async function executeAuthorized(pending,signature){let result;if(pending.action==='place_order'){result=await api('/v1/orders',{method:'POST',body:JSON.stringify({...pending.request,walletSignature:signature})})}else if(pending.action==='withdrawal_review'){result=await api('/v1/withdrawals/review',{method:'POST',body:JSON.stringify({...pending.request,walletSignature:signature})})}else if(pending.action==='cancel_order'){result=await api(`/v1/orders/${encodeURIComponent(pending.request.id)}/cancel`,{method:'POST',body:JSON.stringify({idempotencyKey:pending.request.idempotencyKey,walletSignature:signature})})}sessionStorage.removeItem('ynx.exchange.pending');toast(`Authorized action recorded: ${result.status}`);await refreshAll()}

async function refreshAll(){await Promise.all([refreshBook(),refreshAccount()])}
async function refreshBook(){try{state.book=await api('/v1/orderbook');renderBook()}catch(e){toast(e.message)}}
async function refreshAccount(){if(!state.token)return;try{state.snapshot=await api('/v1/account');state.account=state.snapshot.balances[0]?.account;$('#connect').textContent=state.account?`${state.account.slice(0,8)}…${state.account.slice(-4)}`:'Wallet session';renderAccount()}catch(e){state.token='';sessionStorage.removeItem('ynx.exchange.session');$('#connect').textContent='Sign in with YNX Wallet';toast(e.message)}}
function renderBook(){renderRows('#asks',(state.book?.asks||[]).slice(0,7).reverse());renderRows('#bids',(state.book?.bids||[]).slice(0,7));const all=[...(state.book?.asks||[]),...(state.book?.bids||[])];$('#spread').textContent=all.length?'Owned venue open orders':'No public market depth'}
function renderRows(selector,rows){const root=$(selector);root.replaceChildren();if(!rows.length){const div=document.createElement('div');div.innerHTML='<span>—</span><span>—</span><span>—</span>';root.append(div);return}rows.forEach(o=>{const div=document.createElement('div');[display(o.priceMicro),display(o.amountMicro-o.filledMicro),display(Math.floor((o.amountMicro-o.filledMicro)*o.priceMicro/1e6))].forEach(v=>{const span=document.createElement('span');span.textContent=v;div.append(span)});root.append(div)})}
function renderAccount(){renderOrders();renderBalances();renderActivity();renderChart();const s=state.snapshot.security;$('#withdraw-lock').checked=!!s.withdrawalLock;$('#session-ttl').value=String(s.sessionTtlMinutes||480);const volume=(state.snapshot.trades||[]).reduce((n,t)=>n+t.amountMicro,0);$('#owned-volume').textContent=volume?`${display(volume)} YNXT`:'—'}
function renderOrders(){const root=$('#orders');root.replaceChildren();const rows=(state.snapshot.orders||[]).filter(o=>['open','partially_filled'].includes(o.status));if(!rows.length){root.innerHTML='<tr><td colspan="6" class="empty-cell">No open orders. The venue does not seed fake depth.</td></tr>';return}rows.sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).forEach(o=>{const tr=document.createElement('tr');const values=[new Date(o.createdAt).toLocaleTimeString(),o.side,display(o.priceMicro),`${display(o.amountMicro)} / ${display(o.filledMicro)}`,o.status];values.forEach((v,i)=>{const td=document.createElement('td');td.textContent=v;if(i===4)td.className=`status-${o.status}`;tr.append(td)});const td=document.createElement('td');const btn=document.createElement('button');btn.className='text-button';btn.textContent='Cancel';btn.addEventListener('click',()=>cancelOrder(o));td.append(btn);tr.append(td);root.append(tr)})}
function renderBalances(){const root=$('#balances');root.replaceChildren();(state.snapshot.balances||[]).forEach(b=>{const div=document.createElement('div');div.className='balance-card';const title=document.createElement('strong');title.textContent=b.asset;const dl=document.createElement('dl');dl.innerHTML=`<div><dt>Available</dt><dd>${display(b.availableMicro)}</dd></div><div><dt>Reserved</dt><dd>${display(b.reservedMicro)}</dd></div>`;div.append(title,dl);root.append(div)})}
function renderActivity(){if(!state.snapshot)return;const head=$('#activity-head'),body=$('#activity-body');head.replaceChildren();body.replaceChildren();let rows=[],columns=[];if(state.activity==='trades'){columns=['Time','Side','Price','Amount','Fee'];rows=(state.snapshot.trades||[]).map(t=>[new Date(t.createdAt).toLocaleString(),t.buyer===state.account?'buy':'sell',display(t.priceMicro),display(t.amountMicro),display(t.buyer===state.account?t.buyerFeeMicro:t.sellerFeeMicro)])}else if(state.activity==='fees'){columns=['Time','Kind','Asset','Exact fee','Reference'];rows=(state.snapshot.fees||[]).map(f=>[new Date(f.createdAt).toLocaleString(),f.kind,f.asset,display(f.amountMicro),f.reference])}else{columns=['Time','Action','Object','Proof digest'];rows=(state.snapshot.audit||[]).map(a=>[new Date(a.createdAt).toLocaleString(),a.action,`${a.objectType}:${a.objectId}`,a.digest.slice(0,18)+'…'])}const tr=document.createElement('tr');columns.forEach(c=>{const th=document.createElement('th');th.textContent=c;tr.append(th)});head.append(tr);if(!rows.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=columns.length;td.className='empty-cell';td.textContent='No owned records yet.';tr.append(td);body.append(tr)}else rows.reverse().forEach(row=>{const tr=document.createElement('tr');row.forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td)});body.append(tr)})}
function renderChart(){const trades=state.snapshot?.trades||[];if(!trades.length)return;$('#chart-empty').hidden=true;const svg=$('#chart-svg');svg.hidden=false;const prices=trades.map(t=>t.priceMicro);const lo=Math.min(...prices),hi=Math.max(...prices);const points=prices.map((p,i)=>`${30+i*(740/Math.max(1,prices.length-1))},${250-(p-lo)/Math.max(1,hi-lo)*210}`).join(' ');svg.innerHTML=`<polyline fill="none" stroke="#002FA7" stroke-width="4" points="${points}"/><text x="30" y="25" fill="#667085" font-size="14">Actual owned-account matched trades</text>`;$('#last-price').textContent=`${display(prices.at(-1))} YUSD_TEST`}

function reviewOrder(event){event.preventDefault();if(!state.token){$('#wallet-dialog').showModal();return}const req={market:'YNXT-YUSD_TEST',side:state.side,type:'limit',priceMicro:micro($('#price').value),amountMicro:micro($('#amount').value),idempotencyKey:idempotency('order')};if(req.priceMicro<=0||req.amountMicro<=0){toast('Enter a positive price and amount');return}const payload=['ynx-exchange-order-v1',state.account,req.market,req.side,req.type,req.priceMicro,req.amountMicro,req.idempotencyKey].join('\n');openWalletAction('place_order',payload,req)}
function cancelOrder(order){const req={id:order.id,idempotencyKey:idempotency('cancel')};const payload=['ynx-exchange-cancel-v1',state.account,req.id,req.idempotencyKey].join('\n');openWalletAction('cancel_order',payload,req)}
async function observeDeposit(event){event.preventDefault();try{const dep=await api('/v1/deposits',{method:'POST',body:JSON.stringify({txHash:$('#deposit-tx').value.trim(),idempotencyKey:idempotency('deposit')})});$('#deposit-state').textContent=`${dep.status}: ${dep.confirmations}/${dep.required} confirmations. ${display(dep.amountMicro)} YNXT.`;await refreshAccount()}catch(e){$('#deposit-state').textContent=e.message}}
function reviewWithdrawal(event){event.preventDefault();const amountMicro=micro($('#withdraw-amount').value),destination=$('#withdraw-destination').value.trim(),req={asset:'YNXT',network:'YNX Testnet',destination,amountMicro,idempotencyKey:idempotency('withdrawal')};const payload=['ynx-exchange-withdrawal-review-v1',state.account,req.asset,req.network,req.destination,req.amountMicro,withdrawFee(),req.idempotencyKey].join('\n');openWalletAction('withdrawal_review',payload,req)}
async function saveSecurity(event){event.preventDefault();try{await api('/v1/security',{method:'PUT',body:JSON.stringify({withdrawalLock:$('#withdraw-lock').checked,orderConfirmation:true,sessionTtlMinutes:Number($('#session-ttl').value)})});toast('Security settings saved and audited');await refreshAccount()}catch(e){toast(e.message)}}
async function openSupport(event){event.preventDefault();try{const c=await api('/v1/support',{method:'POST',body:JSON.stringify({category:$('#support-category').value,message:$('#support-message').value,idempotencyKey:idempotency('support')})});toast(`Support case ${c.id} opened`);event.target.reset();await refreshAccount()}catch(e){toast(e.message)}}
async function requestAI(){try{const r=await api('/v1/ai/drafts',{method:'POST',body:JSON.stringify({kind:$('#ai-kind').value,prompt:$('#ai-prompt').value,contextClasses:[$('#ai-context').value],permission:$('#ai-permission').checked})});renderAIState(r);await refreshAccount()}catch(e){$('#ai-result').textContent=e.message}}
function renderAIState(r){const root=$('#ai-result');root.replaceChildren();const message=document.createElement('p');message.textContent=r.status==='permission_required'?'Permission is required before selected context can be sent.':`Provider unavailable: ${r.providerStatus}. Streaming did not start and no generated or canned result was substituted.`;root.append(message);for(const action of ['retry','cancel','reject','delete']){const button=document.createElement('button');button.className='text-button';button.textContent=action[0].toUpperCase()+action.slice(1);button.addEventListener('click',async()=>{try{const next=await api(`/v1/ai/drafts/${encodeURIComponent(r.id)}/actions`,{method:'POST',body:JSON.stringify({action})});renderAIState(next);await refreshAccount()}catch(e){toast(e.message)}});root.append(button)}}
boot();
