// Product UI only. Stores a language preference, never identity or credentials.
export const locales=['en','zh-Hans','zh-Hant','ja','ko','es','fr','de','pt','ru','ar','id'];
const keys=['language','market','assets','activity','controls','loading','connected','degraded','authorization-required','guest','closed','approval-pending','selected-pending','market-loading','market-live','market-single','market-polling','market-reconnecting','market-offline','market-unavailable'];
const rows={
 en:['Language','Trade','Assets','Activity','Controls','Verifying the Exchange private account…','Read-only Exchange account verified by the private authority and Product API. No order or withdrawal permission.','Private account unavailable. Retry can recover its protected state; your standard Wallet remains unchanged.','Private account authorization expired or was rejected. Retry or start a new explicit approval.','Guest mode. Private venue data is hidden; standard Wallet and public markets are independent.','Private account is closed.','Request saved. Click Open YNX Wallet to review read-only access. Native installation is unverified; returning here alone is not approval.','Review Exchange read-only access in the selected Wallet. No venue data is available until its approved return is verified.','Loading venue market data…','Connected · venue market data','Connected · single-host test data','Connected · periodic market snapshots','Market connection interrupted · reconnecting','Offline · reconnect when your network returns','Market data unavailable · retrying'],
 'zh-Hans':['语言','交易','资产','活动','管理','正在验证 Exchange 私有账户…','私有授权服务与产品 API 已验证只读账户。没有下单或提现权限。','私有账户不可用。重试可恢复受保护状态；标准 Wallet 连接保持不变。','私有账户授权已过期或被拒绝。请重试或重新明确授权。','访客模式。私有交易场所数据已隐藏；标准 Wallet 与公开行情相互独立。','私有账户已关闭。','请求已保存。点击打开 YNX Wallet 审核只读访问。原生安装尚未验证；返回本页本身不代表批准。','请在所选 Wallet 审核 Exchange 只读访问。批准返回验证前不会显示账户数据。','正在加载交易场所行情…','已连接 · 场所行情','已连接 · 单主机测试数据','已连接 · 定期行情快照','行情连接中断 · 正在重连','离线 · 网络恢复后重连','行情不可用 · 正在重试'],
 'zh-Hant':['語言','交易','資產','活動','管理','正在驗證 Exchange 私有帳戶…','私有授權服務與產品 API 已驗證唯讀帳戶。沒有下單或提現權限。','私有帳戶不可用。重試可恢復受保護狀態；標準 Wallet 連線不變。','私有帳戶授權已過期或被拒絕。請重試或重新明確授權。','訪客模式。私有交易場所資料已隱藏；標準 Wallet 與公開行情獨立。','私有帳戶已關閉。','請求已儲存。點選開啟 YNX Wallet 審核唯讀存取。原生安裝尚未驗證；返回本頁不代表批准。','請在所選 Wallet 審核 Exchange 唯讀存取。批准返回驗證前不顯示帳戶資料。','正在載入交易場所行情…','已連線 · 場所行情','已連線 · 單主機測試資料','已連線 · 定期行情快照','行情連線中斷 · 正在重連','離線 · 網路恢復後重連','行情不可用 · 正在重試'],
 ja:['言語','取引','資産','履歴','管理','Exchange の非公開アカウントを検証中…','非公開認証サービスと製品 API が読み取り専用アカウントを検証しました。注文・出金権限はありません。','非公開アカウントを利用できません。再試行で復旧できます。標準 Wallet 接続は変わりません。','非公開アクセスが期限切れまたは拒否されました。再試行するか改めて明示的に承認してください。','ゲストモード。非公開データは非表示です。標準 Wallet と公開市場は独立しています。','非公開アカウントは閉じられました。','要求を保存しました。YNX Wallet を開いて読み取り専用アクセスを確認してください。ネイティブのインストールは未検証で、戻るだけでは承認になりません。','選択した Wallet で Exchange の読み取り専用アクセスを確認してください。承認された戻りを検証するまでデータは表示されません。','市場データを読み込み中…','接続済み · 市場データ','接続済み · 単一ホストのテストデータ','接続済み · 定期市場スナップショット','市場接続が中断 · 再接続中','オフライン · ネットワーク復旧後に再接続','市場データ利用不可 · 再試行中'],
 ko:['언어','거래','자산','활동','관리','Exchange 비공개 계정 확인 중…','비공개 권한 서비스와 제품 API가 읽기 전용 계정을 확인했습니다. 주문 또는 출금 권한은 없습니다.','비공개 계정을 사용할 수 없습니다. 재시도로 복구할 수 있으며 표준 Wallet 연결은 유지됩니다.','비공개 권한이 만료되거나 거부되었습니다. 재시도하거나 새로 명시적 승인하세요.','게스트 모드. 비공개 데이터는 숨겨지며 표준 Wallet과 공개 시장은 독립적입니다.','비공개 계정이 닫혔습니다.','요청을 저장했습니다. YNX Wallet을 열어 읽기 전용 접근을 검토하세요. 네이티브 설치는 미확인이며 돌아오기만 해서는 승인되지 않습니다.','선택한 Wallet에서 Exchange 읽기 전용 접근을 검토하세요. 승인된 복귀를 확인하기 전에는 계정 데이터가 없습니다.','시장 데이터 로드 중…','연결됨 · 시장 데이터','연결됨 · 단일 호스트 테스트 데이터','연결됨 · 정기 시장 스냅샷','시장 연결 중단 · 재연결 중','오프라인 · 네트워크 복구 후 재연결','시장 데이터 사용 불가 · 재시도 중'],
 es:['Idioma','Operar','Activos','Actividad','Controles','Verificando la cuenta privada de Exchange…','La autoridad privada y la API verificaron la cuenta de solo lectura. Sin permiso para órdenes o retiros.','Cuenta privada no disponible. Reintentar puede recuperarla; la conexión Wallet estándar no cambia.','La autorización privada caducó o fue rechazada. Reintenta o inicia una nueva aprobación explícita.','Modo invitado. Datos privados ocultos; Wallet estándar y mercados públicos son independientes.','La cuenta privada está cerrada.','Solicitud guardada. Abre YNX Wallet para revisar el acceso de lectura. Instalación nativa no verificada; volver aquí no es aprobar.','Revisa el acceso de lectura de Exchange en la Wallet seleccionada. No hay datos hasta verificar el retorno aprobado.','Cargando datos del mercado…','Conectado · datos del mercado','Conectado · datos de prueba de un solo servidor','Conectado · instantáneas periódicas','Conexión de mercado interrumpida · reconectando','Sin conexión · reconectar al recuperar la red','Datos de mercado no disponibles · reintentando'],
 fr:['Langue','Trader','Actifs','Activité','Contrôles','Vérification du compte privé Exchange…','Compte en lecture seule vérifié par l’autorité privée et l’API. Aucune permission d’ordre ou de retrait.','Compte privé indisponible. Réessayer peut le rétablir ; la connexion Wallet standard reste inchangée.','Autorisation privée expirée ou refusée. Réessayez ou demandez une nouvelle approbation explicite.','Mode invité. Données privées masquées ; Wallet standard et marchés publics sont indépendants.','Le compte privé est fermé.','Demande enregistrée. Ouvrez YNX Wallet pour vérifier l’accès en lecture. Installation native non vérifiée ; revenir ne vaut pas approbation.','Vérifiez l’accès Exchange en lecture dans le Wallet sélectionné. Aucune donnée avant vérification du retour approuvé.','Chargement des données de marché…','Connecté · données de marché','Connecté · données de test sur un seul hôte','Connecté · instantanés périodiques','Connexion de marché interrompue · reconnexion','Hors ligne · reconnecter au retour du réseau','Données de marché indisponibles · nouvelle tentative'],
 de:['Sprache','Handel','Vermögen','Aktivität','Steuerung','Privates Exchange-Konto wird geprüft…','Nur-Lese-Konto durch private Autorität und Produkt-API geprüft. Keine Auftrags- oder Auszahlungsberechtigung.','Privates Konto nicht verfügbar. Erneut versuchen; die Standard-Wallet-Verbindung bleibt bestehen.','Private Berechtigung abgelaufen oder abgelehnt. Erneut versuchen oder ausdrücklich neu genehmigen.','Gastmodus. Private Daten verborgen; Standard-Wallet und öffentliche Märkte sind unabhängig.','Privates Konto ist geschlossen.','Anfrage gespeichert. YNX Wallet zur Prüfung des Lesezugriffs öffnen. Native Installation ungeprüft; die Rückkehr allein ist keine Genehmigung.','Exchange-Lesezugriff im gewählten Wallet prüfen. Keine Kontodaten bis die genehmigte Rückkehr geprüft ist.','Marktdaten werden geladen…','Verbunden · Marktdaten','Verbunden · Testdaten eines einzelnen Hosts','Verbunden · regelmäßige Marktsnapshots','Marktverbindung unterbrochen · erneut verbinden','Offline · nach Netzwerkwiederherstellung verbinden','Marktdaten nicht verfügbar · erneuter Versuch'],
 pt:['Idioma','Negociar','Ativos','Atividade','Controles','Verificando a conta privada Exchange…','Conta somente leitura verificada pela autoridade privada e API. Sem permissão para ordens ou saques.','Conta privada indisponível. Tentar novamente pode recuperá-la; a conexão Wallet padrão permanece.','Autorização privada expirada ou rejeitada. Tente novamente ou inicie uma nova aprovação explícita.','Modo visitante. Dados privados ocultos; Wallet padrão e mercados públicos são independentes.','A conta privada está fechada.','Solicitação salva. Abra YNX Wallet para revisar acesso de leitura. Instalação nativa não verificada; retornar não significa aprovar.','Revise acesso Exchange de leitura na Wallet selecionada. Sem dados até verificar o retorno aprovado.','Carregando dados de mercado…','Conectado · dados de mercado','Conectado · dados de teste em um único host','Conectado · instantâneos periódicos','Conexão de mercado interrompida · reconectando','Offline · reconectar quando a rede voltar','Dados de mercado indisponíveis · tentando novamente'],
 ru:['Язык','Торговля','Активы','Активность','Управление','Проверка приватного счёта Exchange…','Счёт только для чтения проверен приватной службой и API. Нет права на ордера или вывод.','Приватный счёт недоступен. Повтор может восстановить его; стандартное подключение Wallet не меняется.','Приватное разрешение истекло или отклонено. Повторите или запросите новое явное одобрение.','Гостевой режим. Приватные данные скрыты; стандартный Wallet и публичные рынки независимы.','Приватный счёт закрыт.','Запрос сохранён. Откройте YNX Wallet для проверки доступа на чтение. Установка не проверена; возврат сам по себе не является одобрением.','Проверьте доступ Exchange на чтение в выбранном Wallet. Данные недоступны до проверки одобренного возврата.','Загрузка рыночных данных…','Подключено · рыночные данные','Подключено · тестовые данные одного хоста','Подключено · периодические снимки рынка','Рыночное подключение прервано · переподключение','Нет сети · подключение после восстановления','Рыночные данные недоступны · повтор'],
 ar:['اللغة','تداول','الأصول','النشاط','الإدارة','جارٍ التحقق من حساب Exchange الخاص…','تحققت جهة التفويض الخاصة وواجهة المنتج من حساب للقراءة فقط. لا إذن للأوامر أو السحب.','الحساب الخاص غير متاح. يمكن إعادة المحاولة لاستعادته؛ اتصال Wallet القياسي لا يتغير.','انتهى التفويض الخاص أو رُفض. أعد المحاولة أو ابدأ موافقة صريحة جديدة.','وضع الضيف. البيانات الخاصة مخفية؛ Wallet القياسي والأسواق العامة مستقلان.','الحساب الخاص مغلق.','تم حفظ الطلب. افتح YNX Wallet لمراجعة القراءة فقط. تثبيت التطبيق غير متحقق؛ العودة وحدها ليست موافقة.','راجع وصول Exchange للقراءة في Wallet المختار. لا بيانات حتى التحقق من العودة المعتمدة.','جارٍ تحميل بيانات السوق…','متصل · بيانات السوق','متصل · بيانات اختبار على مضيف واحد','متصل · لقطات سوق دورية','انقطع اتصال السوق · جارٍ الاتصال مجددًا','غير متصل · أعد الاتصال عند عودة الشبكة','بيانات السوق غير متاحة · إعادة المحاولة'],
 id:['Bahasa','Perdagangan','Aset','Aktivitas','Kontrol','Memverifikasi akun privat Exchange…','Akun hanya-baca diverifikasi otoritas privat dan API produk. Tanpa izin order atau penarikan.','Akun privat tidak tersedia. Coba lagi untuk memulihkan; koneksi Wallet standar tetap.','Otorisasi privat kedaluwarsa atau ditolak. Coba lagi atau mulai persetujuan eksplisit baru.','Mode tamu. Data privat tersembunyi; Wallet standar dan pasar publik terpisah.','Akun privat ditutup.','Permintaan disimpan. Buka YNX Wallet untuk meninjau akses baca. Instalasi native belum diverifikasi; kembali saja bukan persetujuan.','Tinjau akses baca Exchange di Wallet terpilih. Data belum tersedia sampai kepulangan yang disetujui diverifikasi.','Memuat data pasar…','Terhubung · data pasar','Terhubung · data uji satu host','Terhubung · snapshot pasar berkala','Koneksi pasar terputus · menghubungkan kembali','Offline · hubungkan kembali saat jaringan pulih','Data pasar tidak tersedia · mencoba lagi']
};
export const catalogs=Object.freeze(Object.fromEntries(locales.map(locale=>{
  if(rows[locale].length!==keys.length)throw new Error('EXCHANGE_LOCALE_CATALOG_INCOMPLETE');
  return [locale,Object.freeze(Object.fromEntries(keys.map((key,i)=>[key,rows[locale][i]])))];
})));
export const normalizeLocale=value=>locales.includes(value)?value:'en';
export const translate=(locale,key)=>catalogs[normalizeLocale(locale)][key]??key;

export function installExchangeLocale({document,storage,onChange=()=>{}}){
  let locale='en';try{locale=normalizeLocale(storage?.getItem('ynx-exchange-language'))}catch{}
  const messages=new Map();
  const api={
    locale:()=>locale,
    write(element,key,suffix=''){if(!element)return;messages.set(element,{key,suffix});element.textContent=translate(locale,key)+suffix},
    set(value){locale=normalizeLocale(value);try{storage?.setItem('ynx-exchange-language',locale)}catch{}apply();onChange(locale);return locale}
  };
  function apply(){
    document.documentElement.lang=locale;document.documentElement.dir=locale==='ar'?'rtl':'ltr';
    for(const element of document.querySelectorAll('[data-exchange-locale]'))element.textContent=translate(locale,element.dataset.exchangeLocale);
    for(const [element,{key,suffix}]of messages){if(element.isConnected)element.textContent=translate(locale,key)+suffix;else messages.delete(element)}
    const selector=document.querySelector('#exchange-language');if(selector)selector.value=locale;
  }
  const selector=document.querySelector('#exchange-language');selector?.addEventListener('change',()=>api.set(selector.value));
  apply();return Object.freeze(api);
}
