import assert from "node:assert/strict";
import { createServer } from "node:http";
import test from "node:test";
import { createWalletReadinessService } from "../src/service.mjs";

const build={sourceCommit:"6b6cb8f5b125bbffb4f18f766d6f21014d21d873",release:"wallet-auth-testnet-preview",buildTime:"2026-08-03T22:22:00.000Z"};
function response(value,status=200){return new Response(JSON.stringify(value),{status,headers:{"content-type":"application/json"}})}
async function fixture(t,version={ok:true,remoteDeployed:true,build}){const fetcher=async(url)=>String(url).endsWith("/health")?response({ok:true,remoteDeployed:true}):String(url).endsWith("/ready")?response({ok:true,runtimeReady:true,publicDeploymentReady:true}):response(version),service=createWalletReadinessService({ownerForRequest:request=>request.headers["x-owner"],fetcher}),server=createServer((request,res)=>service.handler(request,res).then(handled=>{if(!handled)res.writeHead(404).end()}));await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));t.after(()=>new Promise(resolve=>server.close(resolve)));return`http://127.0.0.1:${server.address().port}`}
test("running legacy Gateway does not attest the Developer registry",async t=>{const base=await fixture(t),response=await fetch(`${base}/runtime/wallet/readiness`,{headers:{"x-owner":"a"}}),value=await response.json();assert.equal(response.status,200);assert.equal(value.gateway.runtimeReady,true);assert.equal(value.gateway.build.sourceCommit,build.sourceCommit);assert.equal(value.developerBinding.attested,false);assert.equal(value.developerBinding.reason,"gateway_version_does_not_attest_developer_registry")});
test("exact versioned registry attestation enables only the reviewed Developer tuple",async t=>{const registrySha256="a".repeat(64),base=await fixture(t,{ok:true,remoteDeployed:true,build,registrySha256,enabledProductClientIds:["ynx-developer-v1"]}),value=await(await fetch(`${base}/runtime/wallet/readiness`,{headers:{"x-owner":"a"}})).json();assert.equal(value.developerBinding.attested,true);assert.equal(value.developerBinding.registrySha256,registrySha256);assert.deepEqual(value.developerBinding.scopes,["account:read","developer:deploy"])});
test("Wallet readiness requires owner identity and fails closed on upstream failure",async t=>{const base=await fixture(t),unauthorized=await fetch(`${base}/runtime/wallet/readiness`);assert.equal(unauthorized.status,401);const service=createWalletReadinessService({ownerForRequest:()=>"a",fetcher:async()=>{throw new Error("private details")}}),server=createServer((request,response)=>service.handler(request,response));await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));t.after(()=>new Promise(resolve=>server.close(resolve)));const failed=await fetch(`http://127.0.0.1:${server.address().port}/runtime/wallet/readiness`),value=await failed.json();assert.equal(failed.status,503);assert.equal(value.gateway.reachable,false);assert.equal(JSON.stringify(value).includes("private details"),false)});
test("session completion remains closed unless public deployment and exact registry are attested",async t=>{const base=await fixture(t),blocked=await fetch(`${base}/runtime/wallet/sessions/complete`,{method:"POST",headers:{"x-owner":"a","content-type":"application/json"},body:"{}"}),value=await blocked.json();assert.equal(blocked.status,503);assert.equal(value.code,"wallet_public_gate_closed")});
test("session completion forwards canonical JSON only after every server-side gate passes",async t=>{const calls=[];const fetcher=async(url,options={})=>{calls.push({url:String(url),options});if(String(url).endsWith("/health"))return response({ok:true,remoteDeployed:true});if(String(url).endsWith("/ready"))return response({ok:true,runtimeReady:true,publicDeploymentReady:true});if(String(url).endsWith("/version"))return response({ok:true,build,registrySha256:"b".repeat(64),enabledProductClientIds:["ynx-developer-v1"]});return response({ok:true,result:{sessionBinding:"c".repeat(64),productClientId:"ynx-developer-v1"}})};const service=createWalletReadinessService({ownerForRequest:req=>req.headers["x-owner"],fetcher}),server=createServer((req,res)=>service.handler(req,res));await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));t.after(()=>new Promise(resolve=>server.close(resolve)));const base=`http://127.0.0.1:${server.address().port}`,bad=await fetch(`${base}/runtime/wallet/sessions/complete`,{method:"POST",headers:{"x-owner":"a","content-type":"application/json"},body:'{"z":1,"a":2}'});assert.equal(bad.status,400);const body='{"authorizationRequest":{},"gatewayCompletion":{},"walletApproval":{}}',completed=await fetch(`${base}/runtime/wallet/sessions/complete`,{method:"POST",headers:{"x-owner":"a","content-type":"application/json"},body}),value=await completed.json();assert.equal(completed.status,200);assert.equal(value.session.productClientId,"ynx-developer-v1");const forwarded=calls.find(call=>call.url.endsWith("/v1/wallet/sessions/complete"));assert.equal(forwarded.options.body,body);assert.equal(forwarded.options.redirect,"error")});
