import test from 'node:test';
import assert from 'node:assert/strict';
import {createPaperIntentController} from '../web/paper-intents.js';
const strategyHash='a'.repeat(64),input={strategyHash,side:'buy',amount:1000000};
function setup(){let owner={status:'connected',ready:true,account:'native-owner-a',epoch:1},rows={account:owner.account,paper:{KillSwitch:false},strategies:{a:{StrategyHash:strategyHash}}},hook;
  const map=new Map(),calls=[],storage={getItem:key=>map.get(key)??null,setItem:(key,value)=>map.set(key,value),removeItem:key=>map.delete(key)};
  const request=async(path,options)=>{calls.push([path,options]);const body=JSON.parse(options.body);return hook?hook(body):{ID:'paper-000001',StrategyHash:body.strategyHash,Side:body.side,Amount:body.amount,IdempotencyKey:body.idempotencyKey};};
  const make=()=>createPaperIntentController({session:()=>owner,snapshot:()=>rows,request,storage,uuid:()=> '11111111-1111-4111-8111-111111111111'});
  return {make,calls,map,owner:()=>owner,change:()=>{owner={...owner,account:'native-owner-b',epoch:2};rows={...rows,account:owner.account};},hook:value=>{hook=value;},kill:()=>{rows.paper.KillSwitch=true;}};
}
test('preview is read-only; explicit confirmation is single-flight with exact captured bytes',async()=>{const f=setup(),c=f.make();const draft=c.preview(input);assert.equal(f.calls.length,0);let release;f.hook(body=>new Promise(resolve=>{release=()=>resolve({ID:'paper-1',StrategyHash:body.strategyHash,Side:body.side,Amount:body.amount,IdempotencyKey:body.idempotencyKey});}));const a=c.confirm(draft),b=c.confirm(draft);assert.equal(a,b);await Promise.resolve();assert.equal(f.calls.length,1);release();await a;assert.equal(c.pending(),null);});
test('unknown outcome survives reload with same key; edited input cannot create another intent',async()=>{const f=setup(),c=f.make();f.hook(()=>{throw new Error('network');});const draft=c.preview(input);await assert.rejects(c.confirm(draft));const retained=c.pending();const reload=f.make();assert.throws(()=>reload.preview({...input,amount:2}),{code:'PAPER_PENDING_MISMATCH'});const retry=reload.preview(input);assert.equal(retry.retry,true);assert.equal(retry.body.idempotencyKey,retained.idempotencyKey);f.hook(null);await reload.confirm(retry);assert.equal(reload.pending(),null);assert.equal(f.calls[0][1].body,f.calls[1][1].body);});
test('edited preview, foreign strategy, unsafe amounts and kill switch cannot write',()=>{const f=setup(),c=f.make(),d=c.preview(input);c.invalidate();assert.throws(()=>c.confirm(d),{code:'PAPER_PREVIEW_REQUIRED'});for(const body of [{...input,strategyHash:'b'.repeat(64)},{...input,amount:1.1},{...input,amount:9007199254740992}])assert.throws(()=>c.preview(body),{code:'PAPER_DRAFT_INVALID'});f.kill();assert.throws(()=>c.preview(input),{code:'PAPER_WORKSPACE_UNAVAILABLE'});assert.equal(f.calls.length,0);});
test('account change cannot consume or erase another owner unresolved receipt',async()=>{const f=setup(),c=f.make(),d=c.preview(input);let release;f.hook(body=>new Promise(resolve=>{release=()=>resolve({ID:'paper-1',StrategyHash:body.strategyHash,Side:body.side,Amount:body.amount,IdempotencyKey:body.idempotencyKey});}));const result=c.confirm(d);await Promise.resolve();f.change();release();await assert.rejects(result,{code:'PRIVATE_OPERATION_SUPERSEDED'});assert.equal(c.pending(),null);assert.equal(f.map.size,1);assert.throws(()=>c.confirm(d),{code:'PAPER_PREVIEW_REQUIRED'});});
test('unbound receipt and invalid stored bytes remain unresolved instead of being forgotten',async()=>{const f=setup(),c=f.make(),d=c.preview(input);f.hook(()=>({ID:'paper-1'}));await assert.rejects(c.confirm(d),{code:'PAPER_RECEIPT_MISMATCH'});assert.ok(c.pending());f.map.set('ynx.quant.native-paper.intent.v1:native-owner-a','{bad');assert.throws(()=>c.preview(input),{code:'PAPER_PENDING_INVALID'});assert.equal(f.calls.length,1);});
test('owner changes before asynchronous dispatch never write under the new account',async()=>{const f=setup(),c=f.make(),d=c.preview(input);const result=c.confirm(d);f.change();await assert.rejects(result,{code:'PRIVATE_OPERATION_SUPERSEDED'});assert.equal(f.calls.length,0);assert.equal(f.map.size,1);});
