import test from 'node:test';
import assert from 'node:assert/strict';
import {createPaperBacktestController} from '../web/paper-backtest-intents.js';
function fixture(){let current={account:'A',epoch:1,status:'connected',ready:true};const values=new Map(),writes=[];const storage={getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)};const request=async(path,options)=>{writes.push({path,...options});return {id:'original',status:'completed_oos',researchRequestKey:JSON.parse(options.body).idempotencyKey};};const make=override=>createPaperBacktestController({session:()=>current,request:override||request,storage,uuid:()=> '11111111-1111-4111-8111-111111111111'});return {make,storage,values,writes,set:value=>{current=value}};}
const input={strategy:{id:'one',name:'reviewed'},assumptions:{feeBPS:10}};
test('native backtest review/cancel does not write; confirmation is coalesced',async()=>{const f=fixture(),c=f.make();c.preview(input);c.invalidate();assert.equal(f.writes.length,0);const draft=c.preview(input),first=c.confirm(draft);assert.equal(c.confirm(draft),first);await first;assert.equal(f.writes.length,1);assert.equal(f.values.size,0);});
test('lost return persists exact native owner request across reload; explicit retry cannot regenerate strategy/body/key',async()=>{const f=fixture(),c=f.make(async()=>{throw Error('lost return')});await assert.rejects(c.confirm(c.preview(input)));const raw=[...f.values.values()][0],next=f.make(),retry=next.preview({strategy:{id:'different'},assumptions:{feeBPS:99}});assert.equal(retry.raw,raw);assert.equal(f.writes.length,0);await next.confirm(retry);assert.equal(f.writes[0].body,raw);assert.equal(f.values.size,0);});
test('owner switch before dispatch prevents HTTP and preserves original owner journal',async()=>{const f=fixture(),c=f.make(),flight=c.confirm(c.preview(input));f.set({account:'B',epoch:2,status:'connected',ready:true});await assert.rejects(flight);assert.equal(f.writes.length,0);assert.equal(c.pending(),null);assert.equal(f.values.size,1);});
test('edited preview, failed durable storage and mismatched receipt fail closed',async()=>{const f=fixture(),c=f.make(),draft=c.preview(input);draft.body.strategy.id='tampered';assert.throws(()=>c.confirm(draft));assert.equal(f.writes.length,0);f.storage.setItem=()=>{};assert.throws(()=>c.confirm(c.preview(input)));assert.equal(f.writes.length,0);const g=fixture(),bad=g.make(async()=>({id:'bad',status:'completed_oos',researchRequestKey:'wrong'}));await assert.rejects(bad.confirm(bad.preview(input)));assert.equal(g.values.size,1);});
