import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {fileURLToPath} from 'node:url';import {createStandardWalletConnectState,reduceStandardWalletConnectState,STANDARD_WALLET_RPC_PROBE_TRANSPORT} from '../node_modules/@ynx-chain/wallet-auth/src/standard-wallet-connect-state.js';import {ensureYNXTestnet} from '../web/ynx-testnet.js';const root=fileURLToPath(new URL('../',import.meta.url));
test('Quant Web consumes the exact shared runtime and reducer without a browser RPC probe',async()=>{
  const [html,wallet,chain,lock]=await Promise.all(['web/index.html','web/wallet-auth-entry.js','web/ynx-testnet.js','package-lock.json'].map(file=>readFile(root+file,'utf8')));
  for(const marker of ['standard-wallet-browser-c97f85e9.mjs','StandardWalletConnection','discoverWalletProviders','discovery.metamask?.provider','connection.connect()','connection.restore()','connection.revoke()','Product Session remains DEGRADED','createStandardWalletConnectState','reduceStandardWalletConnectState','STANDARD_WALLET_RPC_PROBE_TRANSPORT','RPC_PROBE_DEGRADED'])assert.ok(wallet.includes(marker),marker);
  for(const marker of ['wallet_switchEthereumChain','wallet_addEthereumChain',"'0x1917'"])assert.ok(chain.includes(marker),marker);
  for(const prohibited of ['ynxwallet://authorize','window.open','<iframe','location.assign','location.href=','createProductWalletConnection','fetch('])assert.equal(wallet.includes(prohibited),false,prohibited);
  for(const id of ['connect-wallet','connect-metamask','install-wallet','install-metamask','wallet-revoke'])assert.ok(html.includes(`id="${id}"`));
  assert.match(lock,/provider-connect-state-p0/);
  const {createHash}=await import('node:crypto');
  const runtime=await readFile(root+'vendor/standard-wallet-browser-c97f85e9.mjs');
  assert.equal(runtime.length,22417);
  assert.equal(createHash('sha256').update(runtime).digest('hex'),'b8a900ef2a5ece693cb2808a47ed0072d97c425236deb80c39497886f1535e43');
});
test('shared reducer closes the chooser, preserves a connected Wallet through RPC degradation, and restores a prior account',()=>{let state=createStandardWalletConnectState();state=reduceStandardWalletConnectState(state,{type:'BEGIN',pendingIntent:'quant_provider_connect_1234'});state=reduceStandardWalletConnectState(state,{type:'PROVIDER_SELECTED',providerKind:'metamask'});state=reduceStandardWalletConnectState(state,{type:'ACCOUNT_APPROVED',account:'0x1111111111111111111111111111111111111111'});state=reduceStandardWalletConnectState(state,{type:'CHAIN_CONFIRMED',chainId:'0x1917'});assert.equal(state.status,'connected');assert.equal(state.chooserOpen,false);assert.equal(state.pendingIntent,null);state=reduceStandardWalletConnectState(state,{type:'RPC_PROBE_DEGRADED',probeTransport:STANDARD_WALLET_RPC_PROBE_TRANSPORT,code:'RPC_PROBE_UNAVAILABLE'});assert.equal(state.status,'connected');assert.equal(state.account,'0x1111111111111111111111111111111111111111');assert.equal(state.chooserOpen,false);state=reduceStandardWalletConnectState(state,{type:'RESTORE',providerKind:'metamask',accounts:['0x1111111111111111111111111111111111111111'],chainId:'0x1917'});assert.equal(state.status,'connected');assert.equal(state.focusRestoreTarget,'wallet-connect-trigger');});
test('Quant verifies or adds YNX Testnet before any account permission is requested',async()=>{const calls=[];let switches=0;const provider={request:async request=>{calls.push(request.method);if(request.method==='wallet_switchEthereumChain'&&++switches===1)throw Object.assign(new Error('unknown chain'),{code:4902});if(request.method==='wallet_switchEthereumChain'||request.method==='wallet_addEthereumChain')return null;if(request.method==='eth_chainId')return '0x1917';throw new Error(`unexpected request: ${request.method}`);}};await assert.doesNotReject(ensureYNXTestnet(provider));assert.deepEqual(calls,['wallet_switchEthereumChain','wallet_addEthereumChain','wallet_switchEthereumChain','eth_chainId']);});
