import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../',import.meta.url));

test('Quant Lab exposes seven workflows and honest boundaries',async()=>{const [html,css,js,i18n]=await Promise.all([readFile(root+'web/index.html','utf8'),readFile(root+'web/styles.css','utf8'),readFile(root+'web/app.js','utf8'),readFile(root+'web/i18n.js','utf8')]);for(const name of ['Research','Strategies','Experiments','Paper','Testnet','Risk','Audit'])assert.match(html,new RegExp(name));assert.match(html,/SIMULATED \/ TESTNET ONLY/);assert.match(html,/Real-money auto-trading is structurally disabled/);assert.match(css,/prefers-color-scheme:\s*dark/);assert.match(css,/prefers-reduced-motion:\s*reduce/);assert.match(js,/t\("emptyExperiment"\)/);assert.match(i18n,/No experiments\. Empty means no invented performance/)});
test('Quant uses the accepted canonical launcher, persists the pending request, and retains standard-wallet separation',async()=>{const [html,js,wallet,registry,lock]=await Promise.all([readFile(root+'web/index.html','utf8'),readFile(root+'web/app.js','utf8'),readFile(root+'web/wallet-auth-entry.js','utf8'),readFile(root+'web/product-session-registry.js','utf8'),readFile(root+'package-lock.json','utf8')]);for(const id of ['connect-wallet','connect-metamask','install-wallet','install-metamask','wallet-status','mandate-form','preview-mandate','mandate-signature','testnet-order-form','preview-order','order-signature','risk-reference'])assert.match(html,new RegExp(`id="${id}"`));assert.match(js,/\/v1\/testnet\/signing-payloads\/mandate/);assert.match(js,/\/v1\/testnet\/signing-payloads\/order/);assert.match(js,/"x-ynx-quant-product-session-proof"/);assert.match(js,/"x-ynx-tenant-id"/);for(const marker of ['launchWebAuthorization','parseAuthorizationCallbackURL','parseAuthorizationRequest','PENDING_KEY','PRIVATE_SERVICE_DEGRADED','eth_requestAccounts','Standard Wallet remains unchanged'])assert.match(wallet,new RegExp(marker));for(const prohibited of ['createProductWalletConnection','PRODUCT_SESSION_PUBLIC_GATEWAY_ORIGIN','location.assign','location.href=','encodeRequestDeepLink','createProductSessionProof','/api/v1/wallet/sessions/complete','X-YNX-Exchange-Session','ynxwallet://authorize'])assert.doesNotMatch(wallet,new RegExp(prohibited.replaceAll('/','\\/')));assert.match(registry,/quantWalletAuthorizationRegistry/);assert.match(registry,/origins/);assert.match(registry,/https:\/\/quant\.ynxweb4\.com\/wallet-auth\/callback/);assert.doesNotMatch(registry,/ynxwallet:/);assert.match(lock,/safe-authorize-p0\.0/);assert.doesNotMatch(html,/Exchange session \(not saved\)/i);assert.doesNotMatch(js,/X-YNX-Exchange-Session/i);assert.doesNotMatch(js,/localStorage\.setItem\([^\n]*session/i)});
test('locale selector contains twelve choices including Arabic RTL',async()=>{const html=await readFile(root+'web/index.html','utf8');const locale=html.match(/<select id="locale">([\s\S]*?)<\/select>/)?.[1]||'';assert.equal((locale.match(/<option/g)||[]).length,12);assert.match(locale,/value="ar">العربية/)});
test('all twelve locale catalogs cover every English key without blanks',async()=>{const source=await readFile(root+'web/i18n.js','utf8');const {runInNewContext}=await import('node:vm');const window={};runInNewContext(source,{window});const catalogs=window.QuantI18n.catalogs,keys=Object.keys(catalogs.en);assert.deepEqual(Object.keys(catalogs),['en','zh-CN','zh-TW','ja','ko','es','fr','de','pt','ru','ar','id']);for(const [code,catalog] of Object.entries(catalogs)){assert.deepEqual(Object.keys(catalog),keys,code);for(const key of keys)assert.ok(catalog[key].trim(),`${code}.${key}`)}assert.match(catalogs.ar.mandateBoundary,/Wallet/)});
