import { createHash } from "node:crypto";
import { DatabaseSync } from "node:sqlite";

export function createWorkspaceStore({filename}){
  const db=new DatabaseSync(filename);db.exec("PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000; CREATE TABLE IF NOT EXISTS workspaces(owner_id TEXT NOT NULL, project_id TEXT NOT NULL, revision INTEGER NOT NULL, payload TEXT NOT NULL, updated_at TEXT NOT NULL, PRIMARY KEY(owner_id,project_id)); CREATE TABLE IF NOT EXISTS workspace_mutations(owner_id TEXT NOT NULL, project_id TEXT NOT NULL, idempotency_key TEXT NOT NULL, request_hash TEXT NOT NULL, revision INTEGER NOT NULL, PRIMARY KEY(owner_id,project_id,idempotency_key));");
  const read=db.prepare("SELECT revision,payload,updated_at FROM workspaces WHERE owner_id=? AND project_id=?"),mutation=db.prepare("SELECT request_hash,revision FROM workspace_mutations WHERE owner_id=? AND project_id=? AND idempotency_key=?"),insert=db.prepare("INSERT INTO workspaces(owner_id,project_id,revision,payload,updated_at) VALUES(?,?,?,?,?)"),update=db.prepare("UPDATE workspaces SET revision=?,payload=?,updated_at=? WHERE owner_id=? AND project_id=? AND revision=?"),record=db.prepare("INSERT INTO workspace_mutations(owner_id,project_id,idempotency_key,request_hash,revision) VALUES(?,?,?,?,?)");
  function get(ownerId,projectId){validateId(ownerId,"owner");validateId(projectId,"project");const row=read.get(ownerId,projectId);return row?{revision:Number(row.revision),updatedAt:row.updated_at,...JSON.parse(row.payload)}:null}
  function put(ownerId,projectId,{expectedRevision,idempotencyKey,payload}){validateId(ownerId,"owner");validateId(projectId,"project");if(!Number.isInteger(expectedRevision)||expectedRevision<0)throw fault("A non-negative expected revision is required.","invalid_revision",400);if(typeof idempotencyKey!=="string"||!/^[-A-Za-z0-9_]{8,160}$/.test(idempotencyKey))throw fault("A valid idempotency key is required.","invalid_idempotency_key",400);validatePayload(payload);const serialized=JSON.stringify(payload),requestHash=createHash("sha256").update(`${expectedRevision}:${serialized}`).digest("hex");db.exec("BEGIN IMMEDIATE");try{const previous=mutation.get(ownerId,projectId,idempotencyKey);if(previous){if(previous.request_hash!==requestHash)throw fault("Idempotency key was already used for a different mutation.","idempotency_conflict",409);const value=get(ownerId,projectId);db.exec("COMMIT");return{...value,replayed:true}}const current=read.get(ownerId,projectId),revision=Number(current?.revision||0);if(revision!==expectedRevision)throw fault("Workspace revision changed. Reload before saving.","revision_conflict",409,{currentRevision:revision});const next=revision+1,now=new Date().toISOString();if(current){const result=update.run(next,serialized,now,ownerId,projectId,revision);if(result.changes!==1)throw fault("Workspace revision changed. Reload before saving.","revision_conflict",409)}else insert.run(ownerId,projectId,next,serialized,now);record.run(ownerId,projectId,idempotencyKey,requestHash,next);db.exec("COMMIT");return{revision:next,updatedAt:now,...payload,replayed:false}}catch(error){try{db.exec("ROLLBACK")}catch{}throw error}}
  return{get,put,close:()=>db.close()};
}
function validateId(value,label){if(typeof value!=="string"||!/^[-A-Za-z0-9_]{1,160}$/.test(value))throw fault(`Invalid ${label} identifier.`,`invalid_${label}`,400)}
function validatePayload(value){if(!value||typeof value!=="object"||Array.isArray(value)||typeof value.name!=="string"||value.name.length>160||!value.files||typeof value.files!=="object"||Array.isArray(value.files)||!Array.isArray(value.folders)||!Array.isArray(value.open)||typeof value.active!=="string")throw fault("Invalid workspace snapshot.","invalid_workspace_snapshot",400);const paths=[...Object.keys(value.files),...value.folders,...value.open,value.active].filter(Boolean);if(Object.keys(value.files).length>256||Buffer.byteLength(JSON.stringify(value.files))>2*1024*1024||paths.some(path=>!safePath(path)))throw fault("Workspace snapshot exceeds its path, file or size boundary.","invalid_workspace_snapshot",400);if(Object.values(value.files).some(content=>typeof content!=="string"))throw fault("Workspace files must contain text.","invalid_workspace_snapshot",400)}
function safePath(value){return typeof value==="string"&&value.length>0&&value.length<=240&&!value.startsWith("/")&&!value.includes("\\")&&!value.split("/").some(part=>!part||part==="."||part==="..")&&/^[A-Za-z0-9_./ +@-]+$/.test(value)}
function fault(message,code,status,extra={}){return Object.assign(new Error(message),{code,status,...extra})}
