package com.ynxweb4.browser;

import java.text.DateFormat;import java.text.NumberFormat;import java.util.*;

final class LocaleCatalog {
  static final String[] TAGS={"en","zh-Hans","zh-Hant","ja","ko","es","fr","de","pt","ru","ar","id"};
  private static final Map<String,String[]> M=new HashMap<>();
  static {
    M.put("app",new String[]{"YNX Browser","YNX 浏览器","YNX 瀏覽器","YNX ブラウザ","YNX 브라우저","Navegador YNX","Navigateur YNX","YNX Browser","Navegador YNX","Браузер YNX","متصفح YNX","Browser YNX"});
    M.put("new",new String[]{"New tab","新标签页","新增分頁","新しいタブ","새 탭","Nueva pestaña","Nouvel onglet","Neuer Tab","Nova aba","Новая вкладка","علامة تبويب جديدة","Tab baru"});
    M.put("private",new String[]{"Private tab","隐私标签页","私密分頁","プライベートタブ","비공개 탭","Pestaña privada","Onglet privé","Privater Tab","Aba privada","Приватная вкладка","علامة تبويب خاصة","Tab privat"});
    M.put("history",new String[]{"History","历史记录","瀏覽記錄","履歴","방문 기록","Historial","Historique","Verlauf","Histórico","История","السجل","Riwayat"});
    M.put("bookmarks",new String[]{"Bookmarks","书签","書籤","ブックマーク","북마크","Marcadores","Favoris","Lesezeichen","Favoritos","Закладки","الإشارات","Markah"});
    M.put("downloads",new String[]{"Downloads","下载","下載","ダウンロード","다운로드","Descargas","Téléchargements","Downloads","Downloads","Загрузки","التنزيلات","Unduhan"});
    M.put("settings",new String[]{"Settings","设置","設定","設定","설정","Ajustes","Réglages","Einstellungen","Configurações","Настройки","الإعدادات","Setelan"});
    M.put("wallet",new String[]{"Sign in with YNX Wallet","使用 YNX Wallet 登录","使用 YNX Wallet 登入","YNX Wallet でサインイン","YNX Wallet으로 로그인","Iniciar sesión con YNX Wallet","Se connecter avec YNX Wallet","Mit YNX Wallet anmelden","Entrar com YNX Wallet","Войти через YNX Wallet","تسجيل الدخول باستخدام YNX Wallet","Masuk dengan YNX Wallet"});
    M.put("walletReview",new String[]{"Review requester, callback, scopes, account, network and expiry in YNX Wallet. The browser never signs.","请在 YNX Wallet 中核对请求方、回调、权限范围、账户、网络和有效期。浏览器绝不签名。","請在 YNX Wallet 中核對請求者、回呼、權限範圍、帳戶、網路及到期時間。瀏覽器絕不簽署。","YNX Wallet で要求元、コールバック、権限、アカウント、ネットワーク、有効期限を確認してください。ブラウザは署名しません。","YNX Wallet에서 요청자, 콜백, 범위, 계정, 네트워크, 만료 시간을 확인하세요. 브라우저는 서명하지 않습니다.","Revisa en YNX Wallet el solicitante, retorno, permisos, cuenta, red y vencimiento. El navegador nunca firma.","Dans YNX Wallet, vérifiez demandeur, rappel, portées, compte, réseau et expiration. Le navigateur ne signe jamais.","Prüfen Sie in YNX Wallet Anfragenden, Rückruf, Bereiche, Konto, Netzwerk und Ablauf. Der Browser signiert nie.","No YNX Wallet, confira solicitante, retorno, escopos, conta, rede e validade. O navegador nunca assina.","В YNX Wallet проверьте отправителя, callback, области, аккаунт, сеть и срок. Браузер никогда не подписывает.","راجع في YNX Wallet الجهة والرد والنطاقات والحساب والشبكة والانتهاء. المتصفح لا يوقّع أبداً.","Di YNX Wallet, tinjau peminta, callback, cakupan, akun, jaringan, dan kedaluwarsa. Browser tidak pernah menandatangani."});
    M.put("privateBoundary",new String[]{"Private mode does not save YNX history or permission decisions. Websites, networks, the OS and downloaded files may retain activity.","隐私模式不会保存 YNX 历史记录或权限决定。网站、网络、操作系统和下载文件仍可能保留活动。","私密模式不會儲存 YNX 瀏覽記錄或權限決定。網站、網路、作業系統及下載檔案仍可能保留活動。","プライベートモードは YNX の履歴や権限判断を保存しません。サイト、ネットワーク、OS、ダウンロードファイルは活動を保持する場合があります。","비공개 모드는 YNX 기록이나 권한 결정을 저장하지 않습니다. 사이트, 네트워크, OS 및 다운로드 파일은 활동을 보존할 수 있습니다.","El modo privado no guarda historial ni decisiones de permisos de YNX. Sitios, redes, el sistema y archivos descargados pueden conservar actividad.","Le mode privé n’enregistre ni historique YNX ni décisions d’autorisation. Sites, réseaux, système et fichiers téléchargés peuvent conserver l’activité.","Privatmodus speichert weder YNX-Verlauf noch Berechtigungsentscheidungen. Websites, Netzwerke, Betriebssystem und Downloads können Aktivitäten behalten.","O modo privado não salva histórico YNX nem decisões de permissão. Sites, redes, sistema e arquivos baixados podem reter atividade.","Приватный режим не сохраняет историю YNX и решения разрешений. Сайты, сети, ОС и скачанные файлы могут сохранять активность.","الوضع الخاص لا يحفظ سجل YNX أو قرارات الأذونات. قد تحتفظ المواقع والشبكات والنظام والملفات المنزلة بالنشاط.","Mode privat tidak menyimpan riwayat YNX atau keputusan izin. Situs, jaringan, OS, dan file unduhan dapat menyimpan aktivitas."});
    M.put("offline",new String[]{"Offline — retry when a network is available","离线——网络恢复后重试","離線——網路恢復後重試","オフライン — 接続後に再試行","오프라인 — 연결 후 다시 시도","Sin conexión — reintenta con red","Hors ligne — réessayez avec le réseau","Offline — bei Netzwerk erneut versuchen","Offline — tente com rede","Нет сети — повторите после подключения","غير متصل — أعد المحاولة عند توفر الشبكة","Offline — coba lagi saat jaringan tersedia"});
    M.put("loading",new String[]{"Loading…","加载中…","載入中…","読み込み中…","로딩 중…","Cargando…","Chargement…","Wird geladen…","Carregando…","Загрузка…","جارٍ التحميل…","Memuat…"});
    M.put("permissions",new String[]{"Site permission","网站权限","網站權限","サイト権限","사이트 권한","Permiso del sitio","Autorisation du site","Website-Berechtigung","Permissão do site","Разрешение сайта","إذن الموقع","Izin situs"});
    M.put("transactionReview",new String[]{"Transaction review — verify every field in YNX Wallet; the browser never signs.","交易核对——请在 YNX Wallet 中逐项确认；浏览器绝不签名。","交易核對——請在 YNX Wallet 中逐項確認；瀏覽器絕不簽署。","取引確認 — YNX Wallet ですべての項目を確認してください。ブラウザは署名しません。","거래 검토 — YNX Wallet에서 모든 항목을 확인하세요. 브라우저는 서명하지 않습니다.","Revisión de transacción: verifica cada campo en YNX Wallet; el navegador nunca firma.","Vérification de transaction : contrôlez chaque champ dans YNX Wallet ; le navigateur ne signe jamais.","Transaktionsprüfung: Prüfen Sie jedes Feld in YNX Wallet; der Browser signiert nie.","Revisão da transação: confira cada campo na YNX Wallet; o navegador nunca assina.","Проверка транзакции: сверьте все поля в YNX Wallet; браузер никогда не подписывает.","مراجعة المعاملة — تحقق من كل حقل في YNX Wallet؛ المتصفح لا يوقّع أبداً.","Tinjau transaksi—periksa setiap kolom di YNX Wallet; browser tidak pernah menandatangani."});
    M.put("clear",new String[]{"Clear browsing data","清除浏览数据","清除瀏覽資料","閲覧データを削除","인터넷 사용 기록 삭제","Borrar datos","Effacer les données","Browserdaten löschen","Limpar dados","Удалить данные","مسح بيانات التصفح","Hapus data"});
    M.put("ai",new String[]{"Page AI","页面 AI","頁面 AI","ページ AI","페이지 AI","IA de página","IA de page","Seiten-KI","IA da página","ИИ страницы","ذكاء الصفحة","AI halaman"});
  }
  static String get(String locale,String key){String[] values=M.get(key);if(values==null)return"["+key+"]";int i=Arrays.asList(TAGS).indexOf(resolve(locale));return values[i<0?0:i];}
  static String resolve(String requested){if(requested==null||requested.isBlank())requested=Locale.getDefault().toLanguageTag();if(requested.startsWith("zh-TW")||requested.startsWith("zh-HK")||requested.contains("Hant"))return"zh-Hant";if(requested.startsWith("zh"))return"zh-Hans";for(String tag:TAGS)if(requested.equalsIgnoreCase(tag)||requested.toLowerCase().startsWith(tag.toLowerCase()+"-"))return tag;return"en";}
  static Locale locale(String tag){return Locale.forLanguageTag(resolve(tag));}
  static String formatDate(String tag,Date date){return DateFormat.getDateTimeInstance(DateFormat.MEDIUM,DateFormat.SHORT,locale(tag)).format(date);}
  static String formatNumber(String tag,long value){return NumberFormat.getIntegerInstance(locale(tag)).format(value);}
}
