(()=>{
  const messages={
    en:{
      language:'Language',skip:'Skip to content',markets:'Markets & products',overview:'Overview',activity:'Activity',planning:'Planning',statements:'Statements',ai:'AI review',privacy:'Privacy & safety',support:'Support',brokerNav:'US stocks · Sandbox',
      workbench:'Finance workbench',choose:'Choose what you want to do',intro:'Browse the official Broker Sandbox without an account, or connect a wallet to open your own testnet portfolio and cross-product evidence.',guest:'Guest available',search:'Search Sandbox markets',connect:'Connect a wallet',signIn:'Sign in for budgets & reports',loading:'Loading available Finance channels',loadingDetail:'No market, balance or availability is inferred while Finance checks the catalog.',catalogUnavailable:'Product catalog unavailable',catalogUnavailableDetail:'Finance will not merge or infer product balances while the versioned catalog is unavailable.',
      portfolio:'Connect to view your portfolio',ownerEvidence:'Connect to view owner evidence',searchAssets:'Search official Sandbox assets',unavailable:'Not available',boundary:'Evidence and product boundary',unit:'Unit',settlement:'Settlement',custody:'Custody',noCapabilities:'No enabled capabilities',
      chain:'YNX Chain public testnet · YNXT',pageTitle:'Your money, with its evidence attached.',notConnected:'Not connected',reconnect:'Reconnect YNX Chain',reconnecting:'Reconnecting',checkingSources:'Checking sources',publicFinanceReachable:'Finance service reachable · Wallet not connected',privateFinanceReachable:'Private Finance service reachable',connectionUnavailable:'Finance connection unavailable',offlineRetry:'Offline · reconnect when network returns',sourcesLive:'Explorer + Pay live',explorerLivePayUnavailable:'Explorer live · Pay unavailable',sourcesUnavailable:'Sources unavailable',walletSignIn:'Connect YNX Wallet',walletSignOut:'Sign out',connectYNX:'Connect YNX Wallet',connectMetaMask:'Connect MetaMask',downloadYNX:'Download YNX Wallet',installMetaMask:'Install MetaMask',verifyIdentity:'Verify Wallet identity',identityUnverified:'Wallet identity has not been verified by a signed Finance challenge. This does not authorize private Finance.',identityChecking:'Waiting for your Wallet signature. Private Finance remains separate.',identityVerified:'Wallet identity verified. Private Finance still requires separate Product Session approval.',identityRejected:'Wallet identity was not verified. Standard Wallet remains connected.',
      brokerHeading:'US stocks Sandbox',brokerStatusMissing:'Not configured. No broker account or market data connection is verified.',brokerDisabled:'Sandbox module disabled. No broker connection is verified; submission is disabled.',brokerConfigured:'Configuration present. Official Sandbox, linked account and trading permissions are not verified.',brokerDisconnected:'Not configured / disconnected. Submission is disabled; no sample balances or trades are substituted.',brokerCheckUnavailable:'Configuration check unavailable. Retry is read-only; order submission remains disabled.',brokerAssetsUnavailable:'Sandbox asset directory is unavailable.',brokerNoAssets:'No active tradable provider asset matched. Nothing was substituted.',brokerActiveAsset:'active/tradable Sandbox asset',brokerSelect:'Select',brokerAddWatch:'Add to watchlist',brokerSearchLabel:'Symbol or company name',brokerSearchButton:'Search active assets',brokerSearchIntro:'Search the provider-backed active asset directory. Finance never asks you to type a provider asset UUID.',brokerFind:'Find a Sandbox asset',brokerNoSearch:'No provider asset search has run.',brokerPrivate:'Sign in to read an owner-mapped Sandbox account. Guest mode never receives balances, positions or orders.',brokerNotLinked:'Not linked',brokerUnknownNotZero:'Unknown — not zero',brokerNoProviderResult:'Unknown — no provider result.',brokerSnapshotUnavailable:'Broker Sandbox account data is unavailable. No values were substituted.',brokerLinked:'Linked Sandbox account',brokerSimulatedUSD:'simulated USD',brokerOwnerRead:'Owner-mapped provider read-through. Values are simulated Sandbox records, not YNXT or fiat custody.',brokerShares:'shares',brokerAvailable:'available',brokerAverage:'average',brokerNoPositions:'Provider returned no positions for this linked Sandbox account.',brokerNoOrders:'Provider returned no orders for this linked Sandbox account.',brokerNoLimitPrice:'No limit price',unknown:'Unknown',dateUnavailable:'Date unavailable',
      channelIndexed:'YNXT indexed portfolio',channelEVM:'YNX on-chain test markets',channelBroker:'Official broker sandbox',channelFuture:'Future live and mainnet products',environmentIndexed:'YNX Chain public testnet',environmentEVM:'chain 6423 test market',environmentBroker:'provider sandbox',environmentFuture:'not enabled',availabilityDisabled:'disabled',availabilityIndexed:'source-dependent',availabilityEVM:'owner-source-dependent',availabilityBroker:'credential-and-provider-dependent',
      riskIndexed:'Indexed testnet records are not fiat, a bank balance, or a mainnet asset.',riskEVM:'Only verified test assets and supported bounded contracts qualify; no mainnet BTC or generic EVM capability is implied.',riskBroker:'Simulated cash and shares are not real funds, securities ownership, or chain assets.',riskFuture:'No live brokerage, mainnet custody, lending, yield, or investment product is available.'
      ,testAssetDirectory:'Test-only asset directory',testMarketUnverified:'TEST-AAPL, tUSD and TestDvP are source/Hardhat QA only. No public 6423 deployment, balance or chain submission is verified.',testDraftQty:'TEST-AAPL quantity',testDraftPrice:'Your limit price in tUSD per share',testDraftPreview:'Preview test-only terms',testDraftInvalid:'Enter positive canonical decimals with at most six places. No order was created.',testDraftResult:'Local terms only. No market quote, fee, allowance, counterparty, Wallet approval, order, or chain transaction is verified.'
    },
    'zh-CN':{
      language:'语言',skip:'跳转到主要内容',markets:'市场与产品',overview:'总览',activity:'流水',planning:'规划',statements:'报表',ai:'AI 审阅',privacy:'隐私与安全',support:'帮助',brokerNav:'美股 · 沙盒',
      workbench:'金融工作台',choose:'选择你要办理的事项',intro:'无需登录即可浏览官方券商沙盒；连接钱包后可查看自己的测试网资产组合与跨产品证据。',guest:'访客可用',search:'搜索沙盒市场',connect:'连接钱包',signIn:'登录以查看预算和报表',loading:'正在加载可用金融产品',loadingDetail:'目录核验期间，不推断行情、余额或产品可用性。',catalogUnavailable:'产品目录暂不可用',catalogUnavailableDetail:'版本化目录不可用时，Finance 不合并或推断各产品余额。',
      portfolio:'连接后查看自己的组合',ownerEvidence:'连接后查看本人证据',searchAssets:'搜索官方沙盒资产',unavailable:'暂不可用',boundary:'证据与产品边界',unit:'计价单位',settlement:'结算方式',custody:'托管',noCapabilities:'没有已启用的功能',
      chain:'YNX Chain 公共测试网 · YNXT',pageTitle:'每笔资产都有可追溯证据',notConnected:'未连接',reconnect:'重新连接 YNX Chain',reconnecting:'正在重新连接',checkingSources:'正在检查数据来源',publicFinanceReachable:'Finance 服务可用 · 钱包未连接',privateFinanceReachable:'私人 Finance 服务可用',connectionUnavailable:'Finance 连接暂不可用',offlineRetry:'网络已断开 · 恢复后重新连接',sourcesLive:'Explorer 与 Pay 数据可用',explorerLivePayUnavailable:'Explorer 数据可用 · Pay 暂不可用',sourcesUnavailable:'数据来源暂不可用',walletSignIn:'连接 YNX Wallet',walletSignOut:'退出登录',connectYNX:'连接 YNX Wallet',connectMetaMask:'连接 MetaMask',downloadYNX:'下载 YNX Wallet',installMetaMask:'安装 MetaMask',verifyIdentity:'验证钱包身份',identityUnverified:'尚未通过 Finance 签名挑战验证钱包身份；这不授予私人 Finance 权限。',identityChecking:'等待钱包签名；私人 Finance 权限仍独立。',identityVerified:'钱包身份已验证；私人 Finance 仍需单独批准 Product Session。',identityRejected:'钱包身份未验证；标准钱包连接保持不变。',
      brokerHeading:'美股沙盒',brokerStatusMissing:'尚未配置。券商账户和行情连接均未验证。',brokerDisabled:'沙盒模块已禁用。券商连接未验证，提交订单已禁用。',brokerConfigured:'已提供配置，但官方沙盒、关联账户及交易权限仍未验证。',brokerDisconnected:'未配置或连接中断。订单提交已禁用，不会填入示例余额或成交。',brokerCheckUnavailable:'配置检查暂不可用。重试仅会读取数据，订单提交仍被禁用。',brokerAssetsUnavailable:'沙盒资产目录暂不可用。',brokerNoAssets:'没有匹配的可交易官方资产，不会替换为示例数据。',brokerActiveAsset:'沙盒中有效且可交易的资产',brokerSelect:'选择',brokerAddWatch:'加入关注列表',brokerSearchLabel:'代码或公司名称',brokerSearchButton:'搜索可用资产',brokerSearchIntro:'搜索由服务商提供的有效资产目录，无需输入资产 UUID。',brokerFind:'查找沙盒资产',brokerNoSearch:'尚未搜索服务商资产。',brokerPrivate:'登录后可读取归属于本人的沙盒账户。访客不会收到余额、持仓或订单。',brokerNotLinked:'未关联',brokerUnknownNotZero:'未知，并非零',brokerNoProviderResult:'未知：服务商尚未返回数据。',brokerSnapshotUnavailable:'券商沙盒账户数据不可用，未填入替代数值。',brokerLinked:'已关联的沙盒账户',brokerSimulatedUSD:'模拟美元',brokerOwnerRead:'按本人账户从服务商读取。数值为沙盒模拟记录，不是 YNXT 或法币托管资产。',brokerShares:'股',brokerAvailable:'可用',brokerAverage:'均价',brokerNoPositions:'服务商确认此沙盒账户没有持仓。',brokerNoOrders:'服务商确认此沙盒账户没有订单。',brokerNoLimitPrice:'无指定限价',unknown:'未知',dateUnavailable:'日期不可用',
      channelIndexed:'YNXT 索引资产组合',channelEVM:'YNX 链上测试市场',channelBroker:'官方券商沙盒',channelFuture:'未来的实盘与主网产品',environmentIndexed:'YNX Chain 公共测试网',environmentEVM:'6423 链测试市场',environmentBroker:'服务商沙盒',environmentFuture:'尚未启用',availabilityDisabled:'已禁用',availabilityIndexed:'取决于数据来源',availabilityEVM:'取决于产品方数据来源',availabilityBroker:'取决于凭据和服务商',
      riskIndexed:'索引的测试网记录不是法币、银行余额或主网资产。',riskEVM:'只展示经验证的测试资产和受支持的限定合约；不代表主网 BTC 或通用 EVM 交易能力。',riskBroker:'模拟现金与股份不是真实资金、证券所有权或链上资产。',riskFuture:'当前没有实盘券商、主网托管、借贷、收益或投资产品。'
      ,testAssetDirectory:'仅供测试的资产目录',testMarketUnverified:'TEST-AAPL、tUSD 与 TestDvP 目前仅有源码和本地 Hardhat QA；未验证公共 6423 部署、余额或链上提交。',testDraftQty:'TEST-AAPL 数量',testDraftPrice:'每股 tUSD 自定限价',testDraftPreview:'预览仅供测试的条件',testDraftInvalid:'请输入大于零、最多六位小数的规范数值；没有创建订单。',testDraftResult:'仅在本地预览条件。行情、费用、授权额度、对手方、钱包批准、订单与链上交易均未验证。'
    }
  };
  let current='en';
  try{if(localStorage.getItem('ynx-finance-locale')==='zh-CN')current='zh-CN'}catch{}
  function text(key){return messages[current][key]??messages.en[key]??key}
  function apply(){
    document.documentElement.lang=current;
    for(const element of document.querySelectorAll('[data-finance-i18n]'))element.textContent=text(element.dataset.financeI18n);
    const selector=document.querySelector('#finance-language');if(selector)selector.value=current;
    document.dispatchEvent(new CustomEvent('finance:localechange',{detail:{locale:current}}));
  }
  function set(locale){if(!Object.hasOwn(messages,locale))return false;current=locale;try{localStorage.setItem('ynx-finance-locale',locale)}catch{}apply();return true}
  window.YNXFinanceLocale=Object.freeze({get:()=>current,text,source:key=>messages.en[key],set});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{document.querySelector('#finance-language')?.addEventListener('change',event=>set(event.target.value));apply()},{once:true});
  else{document.querySelector('#finance-language')?.addEventListener('change',event=>set(event.target.value));apply()}
})();
