import {FaucetClient} from './client.js';
const $=id=>document.getElementById(id);
const strings={
 zh:{heading:'从这里开始，<br><span>探索 YNX。</span>',lead:'免费领取测试币，用于转账、连接应用和测试你的下一个想法。',network:'网络',token:'测试代币',testOnly:'仅限测试使用。YNXT 测试币没有真实货币价值。',faucet:'TESTNET FAUCET',claimTitle:'领取测试币',pasteCopy:'粘贴接收地址即可，无需签名或付款。',addressLabel:'接收地址',addressHint:'支持 YNX 地址与 EVM 地址。请确认地址属于你。',amount:'本次领取',refresh:'刷新服务状态',requestId:'请求编号',txHash:'交易哈希',newRequest:'继续领取到另一个地址',privacy:'水龙头只需要公开地址。切勿输入助记词或私钥。',howTitle:'接下来做什么？',walletTitle:'准备钱包 ↗',walletCopy:'使用 YNX Wallet，保存好你的接收地址。',explorerTitle:'查看链上记录 ↗',explorerCopy:'领取后通过交易哈希查看链上进度。',ecosystemTitle:'探索生态 ↗',ecosystemCopy:'将测试币用于 YNX Testnet 上的应用。',serviceStatus:'服务状态',checking:'检查服务中…',ready:'服务可用',unavailable:'服务暂不可用',claim:'领取测试币 →',retry:'重试原请求 →',sending:'正在提交…',accepted:'测试币已发放到接收地址。你可以复制交易哈希，在区块浏览器查看后续链上进度。',replayed:'已恢复原请求的发放回执，没有重复领取。',offline:'网络连接中断。请求已保存在此浏览器，恢复网络后请重试原请求。',legacyUncertain:'尚未收到发放结果。当前服务不支持安全重试，重复提交可能再次领取。请先检查钱包余额与链上记录；保留本页，不自动重新发送。',invalidAddress:'请输入完整的 YNX 地址或 0x 开头的 40 位 EVM 地址。',ipRate:'当前共享网络请求较多，请稍后重试原请求。接收地址的领取额度没有被扣除。',rate:'已达到领取频率限制。请稍后重试同一请求。',blocked:'请求与之前保存的记录不一致。请保留请求编号并检查链上记录。',storage:'浏览器无法保存请求记录。为防止重复领取，请允许本站本地存储后重试。',badReceipt:'服务器回执与本次请求不一致，尚不能确认发放结果。请保留原请求并稍后重试。',capability:'发放服务正在维护。你的请求不会被自动重复发送，请稍后刷新服务状态。',limit:(n,s)=>`每个接收地址每 ${Math.ceil(s/60)} 分钟最多领取 ${n} 次。`,prepared:'请求尚未被接纳，可以使用原编号重试。若先前遇到频率限制，请等额度恢复后再试。',pending:'请求已保存，正在核对发放结果。页面会自动查询，请勿新建重复请求。',done:'已发放',newBlocked:'请先确认上一次请求的结果。',networkWrong:'服务连接的网络不匹配，暂不能领取。'},
 en:{heading:'Your next idea.<br><span>Starts here.</span>',lead:'Get free test tokens to make transfers, explore apps, and build on YNX.',network:'NETWORK',token:'TEST TOKEN',testOnly:'For testing only. Test YNXT has no monetary value.',faucet:'TESTNET FAUCET',claimTitle:'Get test tokens',pasteCopy:'Paste a receiving address. No signature or payment required.',addressLabel:'Receiving address',addressHint:'Supports YNX and EVM addresses. Use an address you control.',amount:'You receive',refresh:'Refresh service status',requestId:'Request ID',txHash:'Transaction hash',newRequest:'Use another address',privacy:'Only your public address is needed. Never enter a recovery phrase or private key.',howTitle:'What comes next?',walletTitle:'Get your wallet ↗',walletCopy:'Use YNX Wallet and copy your receiving address.',explorerTitle:'View the transaction ↗',explorerCopy:'Use the transaction hash to follow its progress on-chain.',ecosystemTitle:'Explore the ecosystem ↗',ecosystemCopy:'Use your test tokens with apps on YNX Testnet.',serviceStatus:'Service status',checking:'Checking service…',ready:'Available',unavailable:'Unavailable',claim:'Get test tokens →',retry:'Retry original request →',sending:'Submitting…',accepted:'Test tokens were credited to the receiving address. Use the transaction hash to follow its progress on the explorer.',replayed:'Recovered the original receipt. No duplicate claim was created.',offline:'The network connection was interrupted. Your request is saved in this browser. Retry the original request when connected.',legacyUncertain:'No funding result was received. This service does not support safe retries yet; resubmitting may fund again. Check your wallet and on-chain history first. This page will not send again automatically.',invalidAddress:'Enter a complete YNX address or a 40-digit EVM address starting with 0x.',ipRate:'This shared network is busy. Retry the original request shortly; the address allowance was not charged.',rate:'The claim limit was reached. Retry the same request later.',blocked:'The request conflicts with its saved record. Keep the request ID and check on-chain history.',storage:'This browser could not save the request. Allow local storage for this site before requesting tokens.',badReceipt:'The receipt did not match your request. Funding is not confirmed; retain the original request.',capability:'Funding is under maintenance. Requests are never resent automatically. Refresh the service status later.',limit:(n,s)=>`Up to ${n} claim(s) per receiving address every ${Math.ceil(s/60)} minutes.`,prepared:'This request has not been admitted. Retry its original ID; if it was rate limited, wait for the allowance to recover.',pending:'Your request is saved. This page automatically checks the funding result. Do not create a duplicate request.',done:'Credited',newBlocked:'Confirm the previous request before creating another.',networkWrong:'The service network does not match YNX Testnet. Funding is unavailable.'}
};
let lang=navigator.language.toLowerCase().startsWith('zh')?'zh':'en',busy=false,lastError='',lastSuccess='';
let requestStorage;try{requestStorage=window.localStorage}catch{requestStorage={getItem(){throw Error()},setItem(){throw Error()}}}
const client=new FaucetClient({fetch:window.fetch.bind(window),storage:requestStorage,crypto:window.crypto});
const t=key=>strings[lang][key]||key;
function result(key,kind='error'){lastError=kind==='success'?'':key;lastSuccess=kind==='success'?key:'';$('result').hidden=false;$('result').className='result '+kind;$('result').textContent=t(key);}
function render(){document.documentElement.lang=lang==='zh'?'zh-CN':'en';document.title=lang==='zh'?'YNX Faucet · 测试网水龙头':'YNX Faucet · Get test tokens';for(const e of document.querySelectorAll('[data-i18n]')){const k=e.dataset.i18n;if(k==='heading')e.innerHTML=t(k);else e.textContent=t(k)}$('language').textContent=lang==='zh'?'English':'中文';const p=client.pending,c=client.config,done=p?.state==='accepted';$('amount').textContent=p?.amount??c?.defaultAmount??'—';$('address').disabled=busy||Boolean(p);if(p)$('address').value=p.address;$('claim').disabled=busy||!c?.ready||done||Boolean(p&&!p.durable&&p.state!=='prepared');$('claim').textContent=busy?t('sending'):done?t('done'):p?t('retry'):c?t('claim'):t('checking');$('availability').textContent=c?(c.ready?t('ready'):t('unavailable')):t('checking');$('availability').className='availability '+(c?.ready?'ready':c?'error':'');$('new-request').hidden=!done;$('receipt').hidden=!p; if(p){$('request-id').textContent=p.serviceRequestId||p.requestId||'—';$('tx-link').textContent=p.transactionHash||'—'; if(p.transactionHash)$('tx-link').href='https://explorer.ynxweb4.com/tx/'+encodeURIComponent(p.transactionHash);else $('tx-link').removeAttribute('href')}if(c?.rateLimitMax)$('rate-limit').textContent=strings[lang].limit(c.rateLimitMax,c.rateLimitWindowSeconds);else $('rate-limit').textContent=c?.rateLimit||'';if(lastError)$('result').textContent=t(lastError);if(lastSuccess)$('result').textContent=t(lastSuccess);}
async function refresh(){try{await client.loadConfig();if(client.pending?.state!=='accepted' ){try{if(await client.reconcile())result('replayed','success')}catch{ /* A failed read never unlocks or resends an uncertain claim. */ }}if(!client.config.ready)result(client.config.chainId!==6423?'networkWrong':'capability');else if(client.pending?.state==='accepted')result(client.pending.receipt?.replayed?'replayed':'accepted','success');else if(client.pending?.state==='sent'&&lastError==='capability')result(client.pending.durable?'pending':'legacyUncertain');else if(!client.pending&&!lastSuccess){lastError='';$('result').hidden=true}}catch{result('capability')}render()}
$('language').onclick=()=>{lang=lang==='zh'?'en':'zh';render()};$('refresh').onclick=refresh;
$('claim-form').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;render();try{const receipt=await client.claim($('address').value);result(receipt.replayed?'replayed':'accepted','success')}catch(e){result(e.code||'offline')}finally{busy=false;render()}};
$('new-request').onclick=()=>{try{client.newRequest();$('address').value='';lastError='';lastSuccess='';$('result').hidden=true;render();$('address').focus()}catch{result('newBlocked')}};
window.addEventListener('online',refresh);window.addEventListener('storage',e=>{if(e.key===client.key){client.restore();render()}});
try{client.restore();if(client.pending)result(client.pending.state==='accepted'?'accepted':client.pending.state==='prepared'?(client.pending.denial||'prepared'):client.pending.durable?'pending':'legacyUncertain',client.pending.state==='accepted'?'success':'error')}catch{result('storage')}render();refresh();
// Recovery only refreshes read-only availability; it never resubmits a claim.
setInterval(()=>{if(!busy&&document.visibilityState==='visible')refresh()},30000);
document.addEventListener('visibilitychange',()=>{if(!busy&&document.visibilityState==='visible')refresh()});

let reconciling=false;setInterval(async()=>{if(busy||reconciling||document.visibilityState!=='visible'||client.pending?.state!=='sent')return;reconciling=true;try{if(await client.reconcile()){result('replayed','success');render()}}catch{}finally{reconciling=false}},5000);
