import assert from "node:assert/strict";
import test from "node:test";
import { resolveExecutable } from "../../workspace-agent/src/sandbox.mjs";
import { runCppLanguageRequest } from "../src/cpp-lsp.mjs";

const clangd=await resolveExecutable(["clangd","clangd-18","clangd-17"]),files={"src/main.cpp":"int add(int left, int right) { return left + right; }\nint main() { return ad; }\n"};
test("clangd provides real C++ completion through the approved sandbox",{skip:!clangd},async()=>{const value=await runCppLanguageRequest({files,activePath:"src/main.cpp",operation:"completion",position:{line:1,character:22}}),items=Array.isArray(value.result)?value.result:value.result?.items||[];assert.equal(value.language,"cpp");assert.equal(value.sandbox.network,false);assert.ok(items.some(item=>String(item.label).trim()==="add"),JSON.stringify(items.slice(0,8)))});
test("clangd resolves definitions and publishes diagnostics",{skip:!clangd},async()=>{const valid={"src/main.cpp":"int add(int left, int right) { return left + right; }\nint main() { return add(1, 2); }\n"},definition=await runCppLanguageRequest({files:valid,activePath:"src/main.cpp",operation:"definition",position:{line:1,character:22}});assert.ok(Array.isArray(definition.result)?definition.result.length>0:Boolean(definition.result));const invalid={"src/main.cpp":"int main() { return missing_symbol; }\n"},diagnostics=await runCppLanguageRequest({files:invalid,activePath:"src/main.cpp",operation:"diagnostics"});assert.ok(diagnostics.result.some(item=>String(item.message).includes("missing_symbol")),JSON.stringify(diagnostics.result))});
test("clangd provides real C completion and diagnostics",{skip:!clangd},async()=>{const cFiles={"src/main.c":"int add(int left, int right) { return left + right; }\nint main(void) { return ad; }\n"},completion=await runCppLanguageRequest({files:cFiles,activePath:"src/main.c",operation:"completion",position:{line:1,character:26}}),items=Array.isArray(completion.result)?completion.result:completion.result?.items||[];assert.ok(items.some(item=>String(item.label).trim()==="add"),JSON.stringify(items.slice(0,8)));const invalid={"src/main.c":"int main(void) { return missing_symbol; }\n"},diagnostics=await runCppLanguageRequest({files:invalid,activePath:"src/main.c",operation:"diagnostics"});assert.ok(diagnostics.result.some(item=>String(item.message).includes("missing_symbol")),JSON.stringify(diagnostics.result))});
test("language requests reject traversal and unapproved operations",async()=>{await assert.rejects(()=>runCppLanguageRequest({files:{"../main.cpp":""},activePath:"../main.cpp",operation:"terminal",position:{line:0,character:0}}),error=>error.code==="invalid_language_request"||error.code==="invalid_language_workspace")});
