import SwiftUI
import CryptoKit
import Security
import UIKit

@main struct YNXMailApp: App {
 @AppStorage("locale") var locale = "system"
 var isRTL: Bool { locale == "ar" || (locale == "system" && Locale.autoupdatingCurrent.language.languageCode?.identifier == "ar") }
 var body: some Scene { WindowGroup { MailView().environment(\.locale, locale == "system" ? .autoupdatingCurrent : Locale(identifier: locale)).environment(\.layoutDirection, isRTL ? .rightToLeft : .leftToRight).onOpenURL(perform: WalletAuth.accept) } }
}

enum WalletAuth {
 static let callback="ynxmail://wallet-auth/callback", client="ynx-mail-v1", bundle="com.ynxweb4.mail"
 static func request(recovery: Bool)->URL? { let key=DeviceKey.publicKey(); let now=Date(), fmt=ISO8601DateFormatter();fmt.formatOptions=[.withInternetDateTime,.withFractionalSeconds];let bytes=(0..<32).map{_ in UInt8.random(in:0...255)};let nonce=Data(bytes).base64EncodedString().replacingOccurrences(of:"+",with:"-").replacingOccurrences(of:"/",with:"_").replacingOccurrences(of:"=",with:"");let value:[String:Any]=["version":"1","nonce":nonce,"chainId":"ynx_6423-1","requestingProduct":"mail","productClientId":client,"bundleId":bundle,"productDeviceAlgorithm":"p256-sha256","productDeviceKey":key,"callback":callback,"scopes":[recovery ? "mail:recover":"mail:account"],"purpose":recovery ? "Recover YNX Mail on this device":"Sign in to YNX Mail on this device","issuedAt":fmt.string(from:now),"expiresAt":fmt.string(from:now.addingTimeInterval(300))];guard let data=try? JSONSerialization.data(withJSONObject:value,options:[.sortedKeys]) else{return nil};UserDefaults.standard.set(String(data:data,encoding:.utf8),forKey:"pending_request");let q=data.base64EncodedString().replacingOccurrences(of:"+",with:"-").replacingOccurrences(of:"/",with:"_").replacingOccurrences(of:"=",with:"");return URL(string:"ynxwallet://authorize?request=\(q)") }
 static func accept(_ url:URL){let defaults=UserDefaults.standard;guard url.scheme=="ynxmail",url.host=="wallet-auth",url.path=="/callback",url.fragment==nil,let items=URLComponents(url:url,resolvingAgainstBaseURL:false)?.queryItems,items.count==1,items[0].name=="response",let encoded=items[0].value,let data=decode(encoded),let response=try? JSONSerialization.jsonObject(with:data) as? [String:Any],let pending=defaults.string(forKey:"pending_request"),let pendingData=pending.data(using:.utf8),let request=try? JSONSerialization.jsonObject(with:pendingData) as? [String:Any],let nonce=response["nonce"] as? String,!defaults.bool(forKey:"consumed.\(nonce)") else{defaults.set("rejected",forKey:"wallet_state");return};for key in ["version","nonce","chainId","requestingProduct","productClientId","bundleId","productDeviceAlgorithm","productDeviceKey","callback","purpose"]{guard String(describing:request[key] ?? "") == String(describing:response[key] ?? "") else{defaults.set("rejected",forKey:"wallet_state");return}};let expected=SHA256.hash(data:Data(("YNX_WALLET_AUTH_REQUEST_V1\n"+pending).utf8)).map{String(format:"%02x",$0)}.joined();guard (request["scopes"] as? [String]) == (response["scopes"] as? [String]),response["requestDigest"] as? String == expected else{defaults.set("rejected",forKey:"wallet_state");return};defaults.set(true,forKey:"consumed.\(nonce)");defaults.set(encoded,forKey:"wallet_response");defaults.set("gateway_required",forKey:"wallet_state")}
 static func decode(_ value:String)->Data?{var s=value.replacingOccurrences(of:"-",with:"+").replacingOccurrences(of:"_",with:"/");s+=String(repeating:"=",count:(4-s.count%4)%4);return Data(base64Encoded:s)}
}
enum DeviceKey {
 static let account="ynx.mail.product-device.v1"
 static func privateKey()->P256.Signing.PrivateKey { let query:[String:Any]=[kSecClass as String:kSecClassGenericPassword,kSecAttrAccount as String:account,kSecReturnData as String:true];var item:CFTypeRef?;if SecItemCopyMatching(query as CFDictionary,&item)==errSecSuccess,let data=item as? Data,let key=try? P256.Signing.PrivateKey(rawRepresentation:data){return key};let key=P256.Signing.PrivateKey();let add:[String:Any]=[kSecClass as String:kSecClassGenericPassword,kSecAttrAccount as String:account,kSecAttrAccessible as String:kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly,kSecValueData as String:key.rawRepresentation];SecItemAdd(add as CFDictionary,nil);return key }
 static func publicKey()->String { privateKey().publicKey.compressedRepresentation.base64EncodedString().replacingOccurrences(of:"+",with:"-").replacingOccurrences(of:"/",with:"_").replacingOccurrences(of:"=",with:"") }
}

struct MailView: View {
 @AppStorage("locale") var locale="system";@AppStorage("aiLanguage") var aiLanguage="en";@AppStorage("draft") var draft="";@State var compose=false;let langs=["system","en","zh-Hans","zh-Hant","ja","ko","es","fr","de","pt","ru","ar","id"]
 var body: some View { NavigationStack { ScrollView { VStack(alignment:.leading,spacing:16){Text("YNX / MAIL").font(.caption.bold()).foregroundStyle(Color(red:0,green:0.184,blue:0.655));Text(String(localized:"inbox")).font(.largeTitle.bold());Picker("Language",selection:$locale){ForEach(langs,id:\.self){Text($0)}}.accessibilityLabel("Language / 语言");TextField(String(localized:"search"),text:.constant("")).textFieldStyle(.roundedBorder);HStack{Button(String(localized:"compose")){compose=true}.buttonStyle(.borderedProminent);Button(String(localized:"sign_in")){if let u=WalletAuth.request(recovery:false){UIApplication.shared.open(u)}}};if !draft.isEmpty{Text(String(localized:"drafts")).font(.title2.bold());Text(draft)}else{ContentUnavailableView(String(localized:"empty"),systemImage:"envelope")};Text(String(localized:"archive")+" • "+String(localized:"spam"));Text(String(localized:"thread")).font(.headline);HStack{Button(String(localized:"block_sender")){};Button(String(localized:"report_trust")){}};Button(String(localized:"appeal")){};Divider();Text(String(localized:"ai")).font(.title2.bold());Text(String(localized:"privacy"));Picker(String(localized:"ai_language"),selection:$aiLanguage){ForEach(langs.dropFirst(),id:\.self){Text($0)}};Button(String(localized:"approve")){};Text(String(localized:"security")).font(.footnote);Button(String(localized:"recover")){if let u=WalletAuth.request(recovery:true){UIApplication.shared.open(u)}}}.padding() } }.sheet(isPresented:$compose){NavigationStack{Form{TextField("@recipient",text:.constant(""));TextEditor(text:$draft).frame(minHeight:180);Text(String(localized:"attachment"));Button(String(localized:"send_preview")){compose=false}}.navigationTitle(String(localized:"compose"))}} }
}
