export type ProductBinding = Readonly<{requestingProduct:string;bundleId:string;callbacks:readonly string[];scopes:readonly string[];maxScopes?:number}>;
export type ProductDeviceAlgorithm = "p256-sha256";
export type AuthorizationRequest = Readonly<{version:"1";nonce:string;chainId:"ynx_6423-1";requestingProduct:string;productClientId:string;bundleId:string;productDeviceAlgorithm:ProductDeviceAlgorithm;productDeviceKey:string;callback:string;scopes:readonly string[];purpose:string;issuedAt:string;expiresAt:string}>;
export type AuthorizationResponse = Readonly<{version:"1";requestDigest:string;nonce:string;chainId:"ynx_6423-1";requestingProduct:string;productClientId:string;bundleId:string;productDeviceAlgorithm:ProductDeviceAlgorithm;productDeviceKey:string;callback:string;account:string;accountPublicKey:string;grantedScopes:readonly string[];purpose:string;issuedAt:string;expiresAt:string;walletSignature:string}>;
export type AuthorizationRejection = Readonly<{version:"1";decision:"rejected";requestDigest:string;nonce:string;chainId:"ynx_6423-1";requestingProduct:string;productClientId:string;bundleId:string;callback:string;decisionCode:"USER_REJECTED";rejectedAt:string;authorityGranted:false;grantedScopes:readonly []}>;
export type GatewayChallenge = Readonly<{version:"1";challenge:string;requestDigest:string;productClientId:string;bundleId:string;productDeviceAlgorithm:ProductDeviceAlgorithm;productDeviceKey:string;account:string;scopes:readonly string[];issuedAt:string;expiresAt:string}>;
export type GatewayCompletion = Readonly<{challenge:GatewayChallenge;deviceSignature:string}>;
export type CentralRegistryEntryV1 = Readonly<{schemaVersion:1;productClientId:string;requestingProduct:string;bundleId:string;callback:string;scopes:readonly string[];maxScopes:number}>;
export type CentralRegistryEntry = Readonly<{schemaVersion:2;productClientId:string;requestingProduct:string;bundleId:string;callbacks:readonly string[];scopes:readonly string[];maxScopes:number;productDeviceAlgorithms:readonly ProductDeviceAlgorithm[]}>;
export type CentralReviewState = "approved"|"pending-review"|"disabled";
export type CentralProductRegistration = Readonly<Omit<CentralRegistryEntry,"schemaVersion"> & {schemaVersion:3;productId:string;displayName:string;reviewState:CentralReviewState;enabled:boolean;sessionDurationSeconds:number;revocationPolicy:Readonly<{session:true;approval:true;device:true;accountAllDevices:true}>}>;
export type CentralRegistryDocument = Readonly<{registryVersion:2;chainId:"ynx_6423-1";products:readonly CentralProductRegistration[]}>;
export type CentralWalletSession = Readonly<{verifierVersion:"wallet-auth-v1";sessionBinding:string;chainId:"ynx_6423-1";requestingProduct:string;productClientId:string;bundleId:string;callback:string;productDeviceAlgorithm:ProductDeviceAlgorithm;productDeviceKey:string;deviceBinding:string;account:string;scopes:readonly string[];nonce:string;purpose:string;requestDigest:string;approvalDigest:string;issuedAt:string;expiresAt:string}>;
export type CentralRevocationState = Readonly<{revokedSessionBindings:readonly string[];revokedApprovalDigests:readonly string[];revokedDeviceBindings:readonly string[];accountLogoutRecords:readonly Readonly<{account:string;before:string}>[]}>;
export type CentralWalletStoreSnapshot = Readonly<{schemaVersion:1;consumedNonces:readonly string[];consumedRequestDigests:readonly string[];consumedChallenges:readonly string[];sessions:readonly CentralWalletSession[];revokedSessionBindings:readonly string[];revokedApprovalDigests:readonly string[];revokedDeviceBindings:readonly string[];accountLogoutRecords:readonly Readonly<{account:string;before:string}>[];audit:readonly Readonly<{sequence:number;type:string;subject:string;at:string;previousHash:string|null;hash:string}>[]}>;
export type CentralWalletSessionInactiveReason="issued-in-future"|"expired"|"session-revoked"|"approval-revoked"|"device-revoked"|"account-logout";
export type CentralWalletSessionInventoryItem=Readonly<Pick<CentralWalletSession,"sessionBinding"|"requestingProduct"|"productClientId"|"bundleId"|"callback"|"productDeviceAlgorithm"|"productDeviceKey"|"deviceBinding"|"approvalDigest"|"scopes"|"purpose"|"issuedAt"|"expiresAt">&{active:boolean;inactiveReasons:readonly CentralWalletSessionInactiveReason[]}>;
export type CentralWalletConnectedApp=Readonly<{requestingProduct:string;productClientId:string;bundleId:string;sessionBindings:readonly string[];activeSessionBindings:readonly string[];approvalDigests:readonly string[];deviceBindings:readonly string[];active:boolean}>;
export type CentralWalletApprovalInventoryItem=Readonly<{approvalDigest:string;requestingProduct:string;productClientId:string;bundleId:string;sessionBindings:readonly string[];activeSessionBindings:readonly string[];revoked:boolean}>;
export type CentralWalletDeviceInventoryItem=Readonly<{deviceBinding:string;requestingProduct:string;productClientId:string;bundleId:string;productDeviceAlgorithm:ProductDeviceAlgorithm;productDeviceKey:string;sessionBindings:readonly string[];activeSessionBindings:readonly string[];revoked:boolean}>;
export type CentralWalletSessionInventory=Readonly<{schemaVersion:1;account:string;asOf:string;connectedApps:readonly CentralWalletConnectedApp[];approvals:readonly CentralWalletApprovalInventoryItem[];devices:readonly CentralWalletDeviceInventoryItem[];sessions:readonly CentralWalletSessionInventoryItem[]}>;
export type SignedNativeTransfer=Readonly<{version:1;chainId:6423;type:"transfer";from:string;to:string;amount:number;fee:1;nonce:number;publicKey:string;signature:string}>;
export declare const WALLET_AUTH_VERSION:"1";
export declare const YNX_NATIVE_CHAIN_ID:"ynx_6423-1";
export declare const YNX_EVM_CHAIN_ID:6423;
export declare const PRODUCT_DEVICE_ALGORITHM:"p256-sha256";
export declare const CENTRAL_REGISTRY_SCHEMA_VERSION:2;
export declare const CENTRAL_VERIFIER_VERSION:"wallet-auth-v1";
export declare const CENTRAL_REGISTRY_DOCUMENT_VERSION:2;
export declare const CENTRAL_REGISTRY_PRODUCT_COUNT:26;
export declare const CENTRAL_PRODUCT_SCHEMA_VERSION:3;
export declare const CENTRAL_WALLET_SESSION_INVENTORY_SCHEMA_VERSION:1;
export declare const NATIVE_TRANSACTION_DOMAIN:"YNX_NATIVE_TX_V1";
export declare const NATIVE_TRANSACTION_CHAIN_ID:6423;
export declare const NATIVE_TRANSACTION_FEE_YNXT:1;
export declare class WalletAuthError extends Error {readonly code:string}
export declare function canonicalJSON(value:unknown):string;
export declare function digestHex(domain:string,value:unknown):string;
export declare function parseAuthorizationRequest(input:string|unknown,options:{now?:Date;registry:Record<string,ProductBinding>}):AuthorizationRequest;
export declare function requestDigest(request:AuthorizationRequest):string;
export declare function createAuthorizationRejection(request:AuthorizationRequest,input:{decisionCode:"USER_REJECTED";rejectedAt:string}):AuthorizationRejection;
export declare function parseAuthorizationRejection(input:string|unknown):AuthorizationRejection;
export declare function verifyAuthorizationRejection(input:string|unknown,request:AuthorizationRequest,at?:Date):AuthorizationRejection;
export declare function walletIdentity(secretHex:string):Readonly<{account:string;accountPublicKey:string}>;
export declare function walletIdentityFromPublicKey(publicKeyHex:string):string;
export declare function evmAddressFromYNX(account:string):string;
export declare function ynxAddressFromEVM(address:string):string;
export declare function signAuthorization(request:AuthorizationRequest,input:{accountSecret:string;account?:string;issuedAt:string}):AuthorizationResponse;
export declare function verifyAuthorization(response:unknown,expected:AuthorizationRequest&{requestDigest:string;now:Date}):AuthorizationResponse;
export declare const WALLET_AUTHORIZE_ROUTE:"ynxwallet://authorize";
export declare const WALLET_AUTHORIZE_REQUEST_PARAMETER:"request";
export declare const WALLET_CALLBACK_RESPONSE_PARAMETER:"response";
export declare function encodeRequestDeepLink(request:AuthorizationRequest):string;
export declare function parseWalletDeepLink(url:string,platform:"android"|"ios",options:{now?:Date;registry:Record<string,ProductBinding>}):Readonly<{platform:string;request:AuthorizationRequest}>;
export declare function createCallbackURL(response:Record<string,unknown>&{callback:string}):string;
export declare function parseCallbackURL(url:string,expectedCallback:string):unknown;
export declare function parseAuthorizationCallbackURL(url:string,request:AuthorizationRequest,at?:Date):AuthorizationResponse|AuthorizationRejection;
export declare const OFFICIAL_YNX_WALLET_DOWNLOAD_URL:"https://www.ynxweb4.com/dapp/download";
export declare const STANDARD_METAMASK_DOWNLOAD_URL:"https://metamask.io/download/";
export declare const AUTHORIZATION_LAUNCH_PLATFORM_MATRIX:Readonly<Record<"android"|"ios"|"macos"|"windows"|"web"|"extension",Readonly<{strategy:"native-resolver"|"standard-provider-discovery";requiresPreflight:true}>>>;
export declare type AuthorizationLaunchStatus="installed"|"provider-ready"|"unsupported";
export declare type AuthorizationLaunchResult=Readonly<{status:AuthorizationLaunchStatus;detail:string;transport:"native-custom-scheme"|"eip-1193"|null;uri:string|null;providerCandidate:WalletProviderCandidate|null;fallbackActions:readonly Readonly<{id:"official-ynx-wallet-download"|"standard-metamask";label:string;url:string}>[]} >;
export declare function createCanonicalAuthorizeLaunch(request:AuthorizationRequest):Readonly<{uri:string;fallbackActions:AuthorizationLaunchResult["fallbackActions"]}>;
export declare function launchWebAuthorization(request:AuthorizationRequest,options?:{scope?:unknown;waitMs?:number}):Promise<AuthorizationLaunchResult>;
export declare function launchNativeAuthorization(request:AuthorizationRequest,platform:"android"|"ios"|"macos"|"windows",resolver?:((uri:string)=>boolean|Promise<boolean>)):Promise<AuthorizationLaunchResult>;
export declare function launchCanonicalAuthorization(request:AuthorizationRequest,options:{platform:"android"|"ios"|"macos"|"windows"|"web"|"extension";resolver?:((uri:string)=>boolean|Promise<boolean>);scope?:unknown;waitMs?:number}):Promise<AuthorizationLaunchResult>;
export declare class OneTimeNonceStore {constructor(records?:readonly [string,string][]);consume(request:AuthorizationRequest,at?:Date):void;snapshot():readonly [string,string][]}
export declare function createGatewayChallenge(approval:AuthorizationResponse,input:{challenge:string;expiresAt:string},at?:Date):GatewayChallenge;
export declare function parseGatewayChallenge(input:unknown):GatewayChallenge;
export declare function gatewayChallengeSignBytes(challenge:GatewayChallenge):string;
export declare function signGatewayChallenge(challenge:GatewayChallenge,productDeviceSecret:string):GatewayCompletion;
export declare function verifyGatewayCompletion(completion:GatewayCompletion,expected:AuthorizationResponse,at?:Date):Readonly<{sessionBinding:string;productClientId:string;bundleId:string;productDeviceAlgorithm:ProductDeviceAlgorithm;account:string;scopes:readonly string[];expiresAt:string}>;
export declare function migrateCentralRegistryEntry(input:CentralRegistryEntryV1|CentralRegistryEntry):CentralRegistryEntry;
export declare function parseCentralRegistryEntry(input:unknown):CentralRegistryEntry;
export declare function registryParserBinding(input:CentralRegistryEntry):Readonly<Record<string,ProductBinding>>;
export declare function verifyCentralWalletSession(input:Readonly<{registryEntry:CentralRegistryEntry;authorizationRequest:AuthorizationRequest;walletApproval:AuthorizationResponse;gatewayCompletion:GatewayCompletion}>,at?:Date):CentralWalletSession;
export declare function parseCentralWalletSession(input:unknown):CentralWalletSession;
export declare function centralApprovalDigest(approval:AuthorizationResponse):string;
export declare function centralDeviceBinding(requestOrSession:Pick<CentralWalletSession,"chainId"|"requestingProduct"|"productClientId"|"bundleId"|"callback"|"productDeviceAlgorithm"|"productDeviceKey">,account:string):string;
export declare function assertCentralWalletSessionActive(session:CentralWalletSession,input:CentralRevocationState,at?:Date):CentralWalletSession;
export declare function parseCentralRegistryDocument(input:unknown):CentralRegistryDocument;
export declare function migrateCentralRegistryDocumentV1(input:unknown):CentralRegistryDocument;
export declare function parseCentralProductRegistration(input:unknown):CentralProductRegistration;
export declare function centralProtocolEntry(registration:CentralProductRegistration,options?:{requireEnabled?:boolean}):CentralRegistryEntry;
export declare function centralRegistrationByProduct(document:CentralRegistryDocument,productId:string,options?:{requireEnabled?:boolean}):CentralProductRegistration;
export declare class CentralWalletSessionStore {
  constructor(snapshot?:CentralWalletStoreSnapshot);
  complete(input:Readonly<{registryEntry:CentralRegistryEntry;authorizationRequest:AuthorizationRequest;walletApproval:AuthorizationResponse;gatewayCompletion:GatewayCompletion}>,at?:Date):CentralWalletSession;
  introspect(sessionBinding:string,context:Readonly<{productClientId:string;bundleId:string;productDeviceKey:string;requiredScopes:readonly string[]}>,at?:Date):Readonly<{active:true;session:CentralWalletSession}>;
  inventory(account:string,at?:Date):CentralWalletSessionInventory;
  revokeSession(sessionBinding:string,at?:Date):string;
  revokeApproval(approvalDigest:string,at?:Date):string;
  revokeDevice(deviceBinding:string,at?:Date):string;
  logoutAllDevices(account:string,at?:Date):Readonly<{account:string;before:string}>;
  revocationState():CentralRevocationState;
  snapshot():CentralWalletStoreSnapshot;
}
export declare function parseCentralWalletStoreSnapshot(input:unknown):CentralWalletStoreSnapshot;
export declare function createSignedNativeTransfer(input:Readonly<{accountSecret:string;to:string;amount:number;nonce:number}>):Readonly<{transaction:SignedNativeTransfer;payload:string;hash:string}>;
export declare function parseSignedNativeTransfer(input:string|unknown):SignedNativeTransfer;
export declare function nativeTransferSignJSON(transaction:Omit<SignedNativeTransfer,"signature">|SignedNativeTransfer):string;
export declare function nativeTransferHash(payload:string):string;
export type SmartAccountCall=Readonly<{target:string;selector:string;value:number;dataDigest:string}>;
export type UserOperationEnvelope=Readonly<{schemaVersion:1;chainId:6423;entryPoint:string;sender:string;nonceKey:string;nonceSequence:number;calls:readonly SmartAccountCall[];callGasLimit:number;verificationGasLimit:number;preVerificationGas:number;maxFeePerGas:number;maxPriorityFeePerGas:number;validAfter:string;validUntil:string}>;
export type SponsorshipPolicy=Readonly<{schemaVersion:1;policyId:string;enabled:boolean;sponsorType:"first-action"|"product"|"merchant"|"developer-testnet";productClientId:string;paymaster:string;entryPoint:string;allowedTargets:readonly string[];allowedSelectors:readonly string[];maxCalls:number;maxCostPerOperation:number;maxCostPerSubjectDay:number;maxCostPerSponsorDay:number;requiresFirstAction:boolean;validAfter:string;validUntil:string;provider:string;fees:string;risk:string;revocation:string;source:string;asOf:string;version:string}>;
export type SponsorshipRequest=Readonly<{schemaVersion:1;policyId:string;sponsorType:SponsorshipPolicy["sponsorType"];productClientId:string;sessionBinding:string;account:string;userOperationDigest:string;antiSybilBinding:string;requestedCost:number;subjectDailyUsed:number;sponsorDailyUsed:number;firstAction:boolean;source:string;asOf:string;version:string}>;
export declare const SMART_ACCOUNT_SCHEMA_VERSION:1;
export declare const SMART_ACCOUNT_CHAIN_ID:6423;
export declare function parseUserOperationEnvelope(input:unknown):UserOperationEnvelope;
export declare function userOperationDigest(input:unknown):string;
export declare function parseSponsorshipPolicy(input:unknown):SponsorshipPolicy;
export declare function parseSponsorshipRequest(input:unknown):SponsorshipRequest;
export declare function evaluateSponsorship(operation:unknown,request:unknown,policy:unknown,at?:Date):Readonly<{eligible:boolean;reasons:readonly string[];policyId:string;userOperationDigest:string;paymaster:string;approvedCost:number;remainingSubjectBudget:number;remainingSponsorBudget:number}>;
export type PackedUserOperation=Readonly<{sender:string;nonce:string;initCode:string;callData:string;accountGasLimits:string;preVerificationGas:string;gasFees:string;paymasterAndData:string;signature:string}>;
export declare const ERC_7769_VERSION:"ERC-7769";
export declare const YNX_TESTNET_CHAIN_QUANTITY:"0x1917";
export declare function parsePackedUserOperation(input:unknown):PackedUserOperation;
export declare class ERC7769BundlerClient{constructor(config:{endpoint:string;entryPoint:string;timeoutMs?:number;maxRequestsPerSecond?:number;authentication?:{header:"authorization"|"x-api-key";value:string}});health():Promise<Readonly<Record<string,unknown>>>;estimateUserOperationGas(operation:unknown):Promise<Readonly<Record<string,unknown>>>;sendUserOperation(operation:unknown):Promise<Readonly<Record<string,unknown>>>;getUserOperationByHash(hash:string):Promise<Readonly<Record<string,unknown>>>;getUserOperationReceipt(hash:string):Promise<Readonly<Record<string,unknown>>>;}
export declare const STRATEGY_MANDATE_SCHEMA_VERSION:2;
export declare const STRATEGY_ACTION_SCHEMA_VERSION:1;
export declare const STRATEGY_MANDATE_STORE_SCHEMA_VERSION:1;
export declare function parseStrategyMandate(input:unknown):Readonly<Record<string,unknown>>;
export declare function strategyMandateDigest(input:unknown):string;
export declare function parseStrategyAction(input:unknown):Readonly<Record<string,unknown>>;
export declare function authorizeStrategyAction(mandate:unknown,action:unknown,at?:Date):Readonly<{authorized:true;mandateId:string;mandateDigest:string;actionDigest:string;nonceDomain:string;nonce:string;at:string}>;
export declare function strategyActionNonceKey(nonceDomain:string,nonce:string):string;
export declare function parseStrategyMandateStoreSnapshot(input:unknown):Readonly<Record<string,unknown>>;
export declare class StrategyMandateStore{constructor(snapshot?:unknown);activate(mandate:unknown,at?:Date):Readonly<Record<string,unknown>>;authorize(mandateId:string,action:unknown,at?:Date):Readonly<{authorized:true;mandateId:string;mandateDigest:string;actionDigest:string;nonceDomain:string;nonce:string;at:string}>;revoke(mandateId:string,at?:Date):string;kill(mandateId:string,at?:Date):string;emergencyExit(mandateId:string,reason:string,at?:Date):Readonly<{mandateDigest:string;at:string;reason:string}>;inventory(account:string,at?:Date):readonly Readonly<{mandate:Readonly<Record<string,unknown>>;mandateDigest:string;status:"active"|"expired"|"revoked"|"killed"|"emergency-exit"}>[];snapshot():Readonly<Record<string,unknown>>;}
export declare function parseCapitalProductReview(input:unknown):Readonly<Record<string,unknown>>;
export declare function parseCredentialCandidate(input:unknown,at?:Date):Readonly<Record<string,unknown>>;
export declare function credentialCandidateDigest(input:unknown,at?:Date):string;

export type ProductSessionPlatform="android"|"ios"|"macos"|"web"|"windows";
export type ProductSessionV2=Readonly<{version:"2";sessionBinding:string;chainId:"ynx_6423-1";productId:string;clientId:string;platform:ProductSessionPlatform;applicationId:string;bundleId:string|null;packageId:string|null;origin:string;callback:string;account:string;deviceId:string;deviceAlgorithm:"p256-sha256";deviceKey:string;deviceBinding:string;nonce:string;state:string;scopes:readonly string[];requestDigest:string;approvalDigest:string;issuedAt:string;expiresAt:string}>;
export declare const PRODUCT_SESSION_REGISTRY_VERSION:3;
export declare const PRODUCT_SESSION_PROTOCOL_VERSION:"2";
export declare const PRODUCT_SESSION_AUTHORITY_SCHEMA_VERSION:2;
export declare const PRODUCT_SESSION_PLATFORMS:readonly ProductSessionPlatform[];
export declare const WALLET_ROUTE_STATUS:Readonly<Record<string,string>>;
export declare const PRODUCT_SESSION_CLIENT_STATE:Readonly<Record<string,string>>;
export declare function parseProductSessionRegistry(input:unknown):Readonly<Record<string,unknown>>;
export declare function migrateProductSessionRegistryV1(input:unknown):Readonly<Record<string,unknown>>;
export declare function migrateProductSessionRegistryV2(input:unknown):Readonly<Record<string,unknown>>;
export declare function productPlatformBinding(registry:unknown,productId:string,platform:ProductSessionPlatform):Readonly<Record<string,unknown>>;
export type ProductPlatformStatus=Readonly<{status:"active";productId:string;clientId:string;displayName:string;platform:ProductSessionPlatform;actions:readonly []}|{status:"retired";code:"CLIENT_RETIRED";productId:string;clientId:string;displayName:string;platform:ProductSessionPlatform;applicationId:string;callback:string;retiredAt:string;lastSupportedVersion:string;replacementUrl:string;actions:readonly ["open-replacement","return-to-product"];authority:"none";productSession:false}>;
export declare function productPlatformStatus(registry:unknown,productId:string,platform:ProductSessionPlatform):ProductPlatformStatus;
export declare function migrateLegacyCallback(registry:unknown,legacyValue:string,context:{productId:string;platform:ProductSessionPlatform}):Readonly<Record<string,unknown>>;
export declare function migrateLegacyProductSessionRequest(registry:unknown,legacy:unknown,context:{productId:string;platform:ProductSessionPlatform;deviceId:string;state:string},at?:Date):Readonly<Record<string,unknown>>;
export declare function createProductSessionRequest(registry:unknown,input:Readonly<{productId:string;platform:ProductSessionPlatform;deviceId:string;deviceKey:string;scopes:readonly string[];purpose:string;nonce:string;state:string}>,at?:Date):Readonly<Record<string,unknown>>;
export declare function parseProductSessionRequest(registry:unknown,input:unknown,at?:Date):Readonly<Record<string,unknown>>;
export declare function productSessionRequestDigest(registry:unknown,request:unknown,at?:Date):string;
export declare function signProductSessionApproval(registry:unknown,request:unknown,input:{accountSecret:string;scopes:readonly string[];expiresAt:string},at?:Date):Readonly<Record<string,unknown>>;
export declare function parseProductSessionApproval(registry:unknown,request:unknown,input:unknown,at?:Date):Readonly<Record<string,unknown>>;
export declare function createProductSessionChallenge(registry:unknown,request:unknown,approval:unknown,input:{challenge:string},at?:Date):Readonly<Record<string,unknown>>;
export declare function parseProductSessionChallenge(input:unknown):Readonly<Record<string,unknown>>;
export declare function signProductSessionChallenge(challenge:unknown,deviceSecret:string):Readonly<Record<string,unknown>>;
export declare function signProductSessionChallengeWith(challenge:unknown,signer:(input:Readonly<{purpose:"challenge";algorithm:"p256-sha256";deviceKey:string;payload:string}>)=>string|Promise<string>):Promise<Readonly<Record<string,unknown>>>;
export declare function parseProductSession(input:unknown):ProductSessionV2;
export declare class ProductSessionAuthority{constructor(registry:unknown,snapshot?:unknown);issueChallenge(input:{request:unknown;approval:unknown;challenge:string},at?:Date):Readonly<Record<string,unknown>>;complete(input:{request:unknown;approval:unknown;completion:unknown},at?:Date):ProductSessionV2;introspect(sessionBinding:string,context:Readonly<Record<string,unknown>>,at?:Date):Readonly<{active:true;session:ProductSessionV2}>;revokeSession(sessionBinding:string):string;revokeDevice(deviceBinding:string):string;revokeAccount(account:string,at?:Date):Readonly<{account:string;before:string}>;snapshot():Readonly<Record<string,unknown>>;}
export declare function walletConnectionChoices(registry:unknown,productId:string,availability:{ynxWalletInstalled:boolean;metaMaskAvailable:boolean}):readonly Readonly<Record<string,unknown>>[];
export declare const METAMASK_EVM_CONNECTION_STATUS:Readonly<{CONNECTED:"connected-evm"}>;
export declare const METAMASK_EVM_CHAIN_ID:6423;
export declare const METAMASK_EVM_CHAIN_QUANTITY:"0x1917";
export declare const METAMASK_EVM_CHAIN:Readonly<{chainId:"0x1917";chainName:"YNX Testnet";nativeCurrency:Readonly<{name:"YNX Testnet";symbol:"YNXT";decimals:18}>;rpcUrls:readonly ["https://evm.ynxweb4.com"];blockExplorerUrls:readonly ["https://explorer.ynxweb4.com"]}>;
export type MetaMaskEvmConnection=Readonly<{status:"connected-evm";wallet:"metamask";connectionMode:"evm-only";authority:"eip-1193-provider-only";productId:string;chainId:6423;chainQuantity:"0x1917";address:string;ynxProductSession:false;productSession:null;limitations:readonly string[]}>;
export declare class MetaMaskEvmConnectionAdapter{constructor(config:Readonly<{registry:unknown;productId:string;provider:unknown}>);connect():Promise<MetaMaskEvmConnection>};
export declare const WALLET_PROVIDER_DISCOVERY_AUTHORITY:"unverified-injected-candidate";
export declare const WALLET_PROVIDER_KIND:Readonly<{YNX:"ynx-wallet";METAMASK:"metamask"}>;
export declare const WALLET_PROVIDER_DISCOVERY_STATUS:Readonly<{AVAILABLE:"available";NOT_INJECTED:"provider-not-injected";UNSUPPORTED:"unsupported-injected-provider";AMBIGUOUS:"ambiguous-provider";CONFLICTED:"conflicted-announcement"}>;
export declare const WALLET_PROVIDER_NOT_INJECTED_POSSIBLE_CAUSES:readonly ["extension-locked","site-access-denied","extension-disabled","extension-not-installed"];
export type WalletProviderCandidate=Readonly<{kind:"ynx-wallet"|"metamask";provider:Readonly<{request:(input:Readonly<Record<string,unknown>>)=>Promise<unknown>}>;source:"eip6963"|"legacy-injected";uuid:string|null;rdns:string|null;name:string|null;authority:"unverified-injected-candidate"}>;
export type WalletProviderDiscoveryDiagnostics=Readonly<{readyStateStart:"loading"|"interactive"|"complete"|"unavailable";readyStateEnd:"loading"|"interactive"|"complete"|"unavailable";eip6963RequestDispatches:number;domContentLoadedObserved:boolean;injectedRootObserved:boolean;injectedProvidersArrayObserved:boolean;injectedProviderCount:number;exactExtensionStateObservable:false}>;
export type WalletProviderDiscovery=Readonly<{ynx:WalletProviderCandidate|null;metamask:WalletProviderCandidate|null;candidates:readonly WalletProviderCandidate[];ambiguities:readonly ("ynx-wallet"|"metamask")[];conflictedAnnouncements:number;status:"available"|"provider-not-injected"|"unsupported-injected-provider"|"ambiguous-provider"|"conflicted-announcement";possibleCauses:readonly ("extension-locked"|"site-access-denied"|"extension-disabled"|"extension-not-installed")[];diagnostics:WalletProviderDiscoveryDiagnostics;authority:"unverified-injected-candidate"}>;
export declare function discoverInjectedWalletProviders(scope?:unknown):WalletProviderDiscovery;
export declare function discoverEip6963WalletProviders(scope?:unknown,waitMs?:number):Promise<WalletProviderDiscovery>;
export declare function discoverWalletProviders(scope?:unknown,waitMs?:number):Promise<WalletProviderDiscovery>;
export declare function selectWalletProviderCandidates(input:unknown[],conflictedAnnouncements?:number):WalletProviderDiscovery;
export declare function walletAvailabilityFromDiscovery(discovery:WalletProviderDiscovery):Readonly<{ynxWalletInstalled:boolean;metaMaskAvailable:boolean}>;
export declare const STANDARD_WALLET_CHAIN_ID:"0x1917";
export declare const STANDARD_WALLET_CONNECT_STATUS:Readonly<{IDLE:"idle";DISCOVERING:"discovering";AWAITING_ACCOUNT:"awaiting-account";SWITCHING_CHAIN:"switching-chain";CONNECTED:"connected";WRONG_CHAIN:"wrong-chain";DISCONNECTED:"disconnected";FAILED:"failed"}>;
export declare const STANDARD_WALLET_PRIVATE_SERVICE:Readonly<{NOT_REQUESTED:"not-requested";CONNECTING:"connecting";READY:"ready";DEGRADED:"degraded"}>;
export declare const STANDARD_WALLET_PUBLIC_HANDSHAKE_STATUS:Readonly<{READY:"ready";PROVIDER_UNAVAILABLE:"provider-unavailable";PROVIDER_AMBIGUOUS:"provider-ambiguous";WRONG_NETWORK:"wrong-network"}>;
export declare const STANDARD_WALLET_PUBLIC_HANDSHAKE_AUTHORITY:"discovery-and-chain-readback-only";
export declare function runStandardWalletPublicConsumerHandshake(config:Readonly<{scope:object;waitMs:number;sourceBinding:Readonly<{consumerId:string;sourceCommit:string;publicUrl:string}>;privateServiceStatus:"not-requested"|"degraded";onResult:(result:Readonly<Record<string,unknown>>)=>void|Promise<void>}>):Promise<Readonly<Record<string,unknown>>>;
export declare const STANDARD_WALLET_RPC_PROBE:Readonly<{NOT_RUN:"not-run";READY:"ready";DEGRADED:"degraded"}>;
export declare const STANDARD_WALLET_RPC_PROBE_TRANSPORT:"accepted-cors-safe";
export type StandardWalletConnectState=Readonly<{status:"idle"|"discovering"|"awaiting-account"|"switching-chain"|"connected"|"wrong-chain"|"disconnected"|"failed";chooserOpen:boolean;chooserMode:"closed"|"connect"|"connection-details"|"wrong-chain"|"error";chooserActions:readonly string[];pendingIntent:string|null;providerKind:"metamask"|"ynx-wallet"|"walletconnect"|null;account:string|null;chainId:string|null;privateService:"not-requested"|"connecting"|"ready"|"degraded";privateServiceCode:string|null;rpcProbe:"not-run"|"ready"|"degraded";rpcProbeCode:string|null;standardPermissions:readonly string[];productAccess:"guest-or-public-only"|"standard-wallet-connected";focusRestoreTarget:"wallet-connect-trigger"|null;errorCode:string|null;disconnectReason:string|null;authority:"standard-wallet-eip1193-state-only"}>;
export declare function createStandardWalletConnectState():StandardWalletConnectState;
export declare function reduceStandardWalletConnectState(current:StandardWalletConnectState,event:Readonly<Record<string,unknown>>):StandardWalletConnectState;
export declare const STANDARD_WALLET_CONFORMANCE_VERSION:"standardWalletConformance@1.0.0-p0.0";
export declare const STANDARD_WALLET_EVM_CHAIN_ID:6423;
export declare const STANDARD_WALLET_EIP1193_METHODS:readonly ["eth_chainId","eth_accounts","eth_requestAccounts","wallet_addEthereumChain","wallet_switchEthereumChain","personal_sign","eth_signTypedData_v4","eth_sendTransaction"];
export declare const STANDARD_WALLET_INTEROP_FIXTURE_VERSION:"standardWalletInteropFixture@1.0.0-p0.0";
export declare const STANDARD_WALLET_INTEROP_EVENT_SEQUENCE:readonly ["ACCOUNTS_CHANGED","CHAIN_CHANGED","CHAIN_CHANGED","ACCOUNTS_CHANGED","PROVIDER_DISCONNECT"];
export type StandardWalletConformanceProfile=Readonly<{id:"ynx-first-party"|"uniswap-interface-reference"|"opensea-reference"|"safe-reference"|"walletconnect-v2-reference";class:"first-party"|"external-reference"|"transport-reference";transport:"eip1193"|"walletconnect-eip1193";requires:readonly string[]}>;
export declare const STANDARD_WALLET_CONFORMANCE_PROFILES:readonly StandardWalletConformanceProfile[];
export declare function createStandardWalletSiweMessage(input:Readonly<{address:string;domain:string;issuedAt:string;nonce:string;statement:string;uri:string}>):string;
export declare function createStandardWalletTypedData(input:Readonly<{account:string;nonce:string;origin:string;purpose:string}>):Readonly<Record<string,unknown>>;
export declare function createStandardWalletTransactionRequest(input:Readonly<{from:string;to:string;value:string}>):Readonly<{from:string;to:string;value:string}>;
export declare function runStandardWalletConformance(input:Readonly<{profileId:StandardWalletConformanceProfile["id"];provider:Readonly<{request:(input:Readonly<Record<string,unknown>>)=>Promise<unknown>}>;testHarness:true;siwe:Readonly<{address:string;domain:string;issuedAt:string;nonce:string;statement:string;uri:string}>;typedData:Readonly<{account:string;nonce:string;origin:string;purpose:string}>;transaction:Readonly<{from:string;to:string;value:string}>}>):Promise<Readonly<Record<string,unknown>>>;
export declare function runStandardWalletInteropFixture(input:Readonly<{profileId:StandardWalletConformanceProfile["id"];provider:Readonly<{request:(input:Readonly<Record<string,unknown>>)=>Promise<unknown>}>;testHarness:true;driveEvents:(dispatch:(event:Readonly<Record<string,unknown>>)=>void)=>void|Promise<void>;siwe:Readonly<{address:string;domain:string;issuedAt:string;nonce:string;statement:string;uri:string}>;typedData:Readonly<{account:string;nonce:string;origin:string;purpose:string}>;transaction:Readonly<{from:string;to:string;value:string}>}>):Promise<Readonly<Record<string,unknown>>>;
export declare const PRODUCT_WALLET_MIGRATION_EVIDENCE_VERSION:1;
export declare const PRODUCT_WALLET_MIGRATION_SHARED_SOURCE:Readonly<{commit:"98c6d5d784d212df8981a53b17118a511e246ad2";tree:"51a60a362d4ad5dd748bcdefb101f71b1d9e0cee";evidenceCommit:"c3ab255c32bdeb9c8e056882c315f8ad43c29c7f"}>;
export declare const PRODUCT_WALLET_MIGRATION_PRODUCT_IDS:readonly ["calendar","card","creator-studio","developer","dex","exchange","finance","pay","quant","shop","social","video"];
export type ProductWalletMigrationEvidenceResult=Readonly<{schemaVersion:1;productId:string;sourceAccepted:boolean;publicRuntimeAccepted:boolean;standardWalletAccepted:boolean;callbackAccepted:boolean;productSessionAccepted:boolean;productsConnected:0|1;migratedV2:boolean;missing:readonly string[];authority:"evidence-evaluation-only"}>;
export declare function evaluateProductWalletMigrationEvidence(input:unknown):ProductWalletMigrationEvidenceResult;
export declare const INSTALLABLE_ARTIFACT_GATE_VERSION:"installableWalletArtifact@1.0.0-p0.0";
export declare const INSTALLABLE_ARTIFACT_PLATFORM:Readonly<{MACOS:"macos";WINDOWS:"windows";ANDROID:"android";WEB_PWA:"web-pwa"}>;
export declare function verifyInstallableArtifactReleaseManifest(input:unknown):Readonly<{version:"installableWalletArtifact@1.0.0-p0.0";entries:readonly Readonly<Record<string,unknown>>[];publishable:true}>;
export declare function encodeProductSessionWalletURL(registry:unknown,request:unknown,at?:Date):string;
export declare function parseProductSessionWalletURL(registry:unknown,url:string,at?:Date):Readonly<Record<string,unknown>>;
export declare function prepareWalletOpen(registry:unknown,request:unknown,environment:{networkAvailable:boolean;walletInstalled:boolean;schemeRegistered:boolean},at?:Date):Readonly<Record<string,unknown>>;
export declare function createProductSessionReturnURL(registry:unknown,request:unknown,result:Readonly<Record<string,unknown>>,at?:Date):string;
export declare function parseProductSessionReturnURL(registry:unknown,request:unknown,url:string,at?:Date):Readonly<Record<string,unknown>>;
export declare function canonicalReturnTarget(registry:unknown,productId:string,platform:ProductSessionPlatform):Readonly<Record<string,unknown>>;
export declare class RecoverableProductSessionClient{constructor(config:Readonly<Record<string,unknown>>);readonly current:Readonly<Record<string,unknown>>;readonly storageKey:string;readonly connectionBinding:Readonly<{productId:string;platform:ProductSessionPlatform;applicationId:string}>;detectWalletEnvironment():Promise<Readonly<{walletInstalled:boolean;schemeRegistered:boolean}>>;beginDetected(automatic?:boolean):Promise<Readonly<Record<string,unknown>>>;retryDetected():Promise<Readonly<Record<string,unknown>>>;restore(networkAvailable?:boolean):Promise<Readonly<Record<string,unknown>>>;begin(environment:{walletInstalled:boolean;schemeRegistered:boolean},automatic?:boolean):Promise<Readonly<Record<string,unknown>>>;handleReturn(url:string):Promise<Readonly<Record<string,unknown>>>;retry(environment:{walletInstalled:boolean;schemeRegistered:boolean}):Promise<Readonly<Record<string,unknown>>>;connectionChoices(availability:{ynxWalletInstalled:boolean;metaMaskAvailable:boolean}):readonly Readonly<Record<string,unknown>>[];setNetworkAvailable(available:boolean):Readonly<Record<string,unknown>>;enterGuest():Readonly<Record<string,unknown>>;disconnect():Promise<Readonly<Record<string,unknown>>>;}
export declare const WALLET_CONNECTION_COORDINATOR_STATUS:Readonly<{OPTIONS_READY:"options-ready";OPTIONS_UNAVAILABLE:"options-unavailable";SESSION_STATE:"session-state";WALLET_OPENED:"wallet-opened";WALLET_OPEN_FAILED:"wallet-open-failed";YNX_WALLET_PREFERRED:"ynx-wallet-preferred";EVM_CONNECTED:"evm-connected";EVM_UNAVAILABLE:"evm-unavailable"}>;
export declare class WalletConnectionCoordinator{constructor(config:Readonly<{registry:unknown;productId:string;sessionClient:RecoverableProductSessionClient;scope:unknown;discoveryWaitMs:number;openWallet:(input:Readonly<{url:string;request:Readonly<Record<string,unknown>>;requestId:string;automatic:boolean;productId:string;platform:ProductSessionPlatform}>)=>Readonly<{opened:true}|{opened:false;code:string}>|Promise<Readonly<{opened:true}|{opened:false;code:string}>>;openTimeoutMs:number}>);readonly current:Readonly<Record<string,unknown>>;readonly storageKey:string;readonly connectionBinding:Readonly<{productId:string;platform:ProductSessionPlatform;applicationId:string}>;options():Promise<Readonly<Record<string,unknown>>>;restore(networkAvailable?:boolean):Promise<Readonly<Record<string,unknown>>>;beginYNX():Promise<Readonly<Record<string,unknown>>>;beginLegacyYNX(legacyCallback:string):Promise<Readonly<Record<string,unknown>>>;retryYNX():Promise<Readonly<Record<string,unknown>>>;handleReturn(url:string):Promise<Readonly<Record<string,unknown>>>;connectMetaMask():Promise<Readonly<Record<string,unknown>>>;setNetworkAvailable(available:boolean):Readonly<Record<string,unknown>>;enterGuest():Readonly<Record<string,unknown>>;disconnect():Promise<Readonly<Record<string,unknown>>>;}
export type WalletErrorDefinition=Readonly<{httpStatus:number;retryable:boolean;safeMessage:string;developerMessage:string;monitoringClass:string;userAction:string;providerCode:number|null}>;
export type WalletErrorDescriptor=Readonly<WalletErrorDefinition&{code:string}>;
export declare const WALLET_ERROR_CONTRACT:Readonly<Record<string,WalletErrorDefinition>>;
export declare const WALLET_PROVIDER_ERROR_CODES:Readonly<Record<number,string>>;
export declare function walletErrorDescriptor(input:unknown):WalletErrorDescriptor;
export declare function walletErrorResponse(input:unknown,correlation?:Readonly<{requestId?:string;traceId?:string;errorId?:string}>):Readonly<{status:number;body:Readonly<{code:string;retryable:boolean;safeMessage:string;monitoringClass:string;userAction:string;requestId?:string;traceId?:string;errorId?:string}>}>;
export declare const PRODUCT_SESSION_PUBLIC_GATEWAY_ORIGIN:"https://wallet-auth.ynxweb4.com";
export declare function createProductWalletConnection(config:Readonly<{registry:unknown;productId:string;platform:ProductSessionPlatform;walletInstalled:()=>boolean|Promise<boolean>;schemeRegistered:()=>boolean|Promise<boolean>;gatewayTimeoutMs:number;storage:Readonly<Record<string,unknown>>;device:Readonly<{id:string;key:string;sign:(input:Readonly<{purpose:"challenge"|"http-proof";algorithm:"p256-sha256";deviceKey:string;payload:string}>)=>string|Promise<string>;scopes:readonly string[];purpose:string}>;scope:unknown;discoveryWaitMs:number;openWallet:(input:Readonly<{url:string;request:Readonly<Record<string,unknown>>;requestId:string;automatic:boolean;productId:string;platform:ProductSessionPlatform}>)=>Readonly<{opened:true}|{opened:false;code:string}>|Promise<Readonly<{opened:true}|{opened:false;code:string}>>;openTimeoutMs:number}>):WalletConnectionCoordinator;
export declare function createProductSessionProofV2(session:ProductSessionV2,input:Readonly<{method:string;path:string;bodyDigest:string;nonce:string;issuedAt:string;expiresAt:string}>,deviceSecret:string):Readonly<Record<string,unknown>>;
export declare function createProductSessionProofV2With(session:ProductSessionV2,input:Readonly<{method:string;path:string;bodyDigest:string;nonce:string;issuedAt:string;expiresAt:string}>,signer:(input:Readonly<{purpose:"http-proof";algorithm:"p256-sha256";deviceKey:string;payload:string}>)=>string|Promise<string>):Promise<Readonly<Record<string,unknown>>>;
export declare function parseProductSessionProofV2(input:unknown):Readonly<Record<string,unknown>>;
export declare function verifyProductSessionProofV2(proof:unknown,session:ProductSessionV2,request:Readonly<{method:string;path:string;bodyDigest:string}>,at?:Date):Readonly<Record<string,unknown>>;
export declare function productSessionProofV2SignBytes(input:unknown):string;
export declare function productSessionProofV2Digest(input:unknown):string;
export declare const PRODUCT_SESSION_GATEWAY_SCHEMA_VERSION:2;
export declare class ProductSessionGatewayKernel{constructor(registry:unknown,tokenFactory:()=>string,snapshot?:unknown);dispatch(input:Readonly<{requestId:string;method:string;path:string;body:Readonly<Record<string,unknown>>;proof:Readonly<Record<string,unknown>>|null;networkAvailable:boolean}>,at?:Date):Readonly<{status:number;headers:Readonly<Record<string,string>>;body:string}>;snapshot():Readonly<Record<string,unknown>>;}
export declare function parseProductSessionGatewaySnapshot(input:unknown):Readonly<Record<string,unknown>>;
export declare function migrateProductSessionGatewaySnapshotV1(input:unknown):Readonly<Record<string,unknown>>;
export declare const PRODUCT_SESSION_GATEWAY_PROOF_HEADER_V2:"x-ynx-product-session-proof-v2";
export declare class ProductSessionGatewayFetchAdapter{constructor(config:Readonly<{endpoint:string;fetch:(url:string,init:Readonly<Record<string,unknown>>)=>Promise<unknown>;walletInstalled:()=>boolean|Promise<boolean>;schemeRegistered:()=>boolean|Promise<boolean>;timeoutMs:number}>);walletInstalled():Promise<boolean>;schemeRegistered():Promise<boolean>;challenge(input:Readonly<Record<string,unknown>>):Promise<Readonly<Record<string,unknown>>>;complete(input:Readonly<Record<string,unknown>>):Promise<Readonly<Record<string,unknown>>>;introspect(input:Readonly<Record<string,unknown>>):Promise<Readonly<Record<string,unknown>>>;revoke(input:Readonly<Record<string,unknown>>):Promise<Readonly<Record<string,unknown>>>;}
export declare function decodeProductSessionGatewayProofHeaderV2(value:unknown):Readonly<Record<string,unknown>>;
export declare function encodeProductSessionGatewayProofHeaderV2(value:unknown):string;
export declare const PRODUCT_SESSION_GATEWAY_HTTP_MAX_BODY_BYTES:1048576;
export declare class ProductSessionGatewayHttpHandler{constructor(registry:unknown,tokenFactory:()=>string,snapshot?:unknown);handle(input:Readonly<{requestId:string;method:string;path:string;contentType:string;body:string;proofHeader:string|null;networkAvailable:boolean}>,at?:Date):Readonly<{status:number;headers:Readonly<Record<string,string>>;body:string}>;snapshot():Readonly<Record<string,unknown>>;}
export declare function createSignedIntent(input:Readonly<Record<string,unknown>&{accountSecret:string}>):Readonly<Record<string,unknown>>;
export declare function parseSignedIntent(input:unknown):Readonly<Record<string,unknown>>;
export declare function signedIntentDigest(input:unknown):string;
export declare function exportSignedIntent(input:unknown):string;
export declare function assertSignedIntentActive(input:unknown,context:Readonly<Record<string,unknown>>,at?:Date):Readonly<Record<string,unknown>>;
export declare function createProductSessionProof(session:CentralWalletSession,input:Readonly<{method:string;path:string;bodyDigest:string;nonce:string;issuedAt:string;expiresAt:string}>,productDeviceSecret:string):Readonly<Record<string,unknown>>;
export declare function parseProductSessionProof(input:unknown):Readonly<Record<string,unknown>>;
export declare function productSessionProofSignBytes(input:unknown):string;
export declare function productSessionProofDigest(input:unknown):string;
export declare function httpBodyDigest(body:string|Uint8Array):string;
export declare function verifyProductSessionProof(proof:unknown,session:CentralWalletSession,expected:Readonly<{method:string;path:string;bodyDigest:string}>,at?:Date):Readonly<Record<string,unknown>>;
export declare const CANONICAL_GATEWAY_ADAPTER_SCHEMA_VERSION:2;
export declare class CanonicalWalletGatewayAdapter{constructor(registry:unknown,snapshot?:unknown);complete(input:Readonly<Record<string,unknown>>,at?:Date):CentralWalletSession;rejectAuthorization(input:Readonly<Record<string,unknown>>,at?:Date):never;introspect(input:Readonly<Record<string,unknown>>,request:Readonly<Record<string,unknown>>,at?:Date):Readonly<{active:true;session:CentralWalletSession}>;sessionInventory(input:Readonly<Record<string,unknown>>,request:Readonly<Record<string,unknown>>,at?:Date):CentralWalletSessionInventory;revokeSession(input:Readonly<Record<string,unknown>>,request:Readonly<Record<string,unknown>>,at?:Date):string;revokeApproval(input:Readonly<Record<string,unknown>>,request:Readonly<Record<string,unknown>>,at?:Date):string;revokeDevice(input:Readonly<Record<string,unknown>>,request:Readonly<Record<string,unknown>>,at?:Date):string;logoutAllDevices(input:Readonly<Record<string,unknown>>,request:Readonly<Record<string,unknown>>,at?:Date):Readonly<{account:string;before:string}>;activateMandate(input:Readonly<Record<string,unknown>>,request:Readonly<Record<string,unknown>>,at?:Date):Readonly<Record<string,unknown>>;authorizeMandateAction(input:Readonly<Record<string,unknown>>,request:Readonly<Record<string,unknown>>,at?:Date):Readonly<Record<string,unknown>>;mandateInventory(input:Readonly<Record<string,unknown>>,request:Readonly<Record<string,unknown>>,at?:Date):readonly Readonly<Record<string,unknown>>[];revokeMandate(input:Readonly<Record<string,unknown>>,request:Readonly<Record<string,unknown>>,at?:Date):string;killMandate(input:Readonly<Record<string,unknown>>,request:Readonly<Record<string,unknown>>,at?:Date):string;emergencyExitMandate(input:Readonly<Record<string,unknown>>,request:Readonly<Record<string,unknown>>,at?:Date):Readonly<Record<string,unknown>>;snapshot():Readonly<Record<string,unknown>>}
export declare function parseGatewayAdapterSnapshot(input:unknown,registryVersion:number):Readonly<Record<string,unknown>>;
export declare const CANONICAL_GATEWAY_HTTP_SCHEMA_VERSION:1;
export declare const CANONICAL_GATEWAY_HTTP_MAX_BODY_BYTES:1048576;
export type CanonicalGatewayHttpInput=Readonly<{method:string;path:string;contentType:string;body:string;proof:Readonly<Record<string,unknown>>|null}>;
export type CanonicalGatewayHttpResponse=Readonly<{status:number;headers:Readonly<Record<string,string>>;body:string;mutated:boolean}>;
export declare class CanonicalWalletGatewayHttpKernel{constructor(registry:unknown,snapshot?:unknown);dispatch(input:CanonicalGatewayHttpInput,at?:Date):CanonicalGatewayHttpResponse;snapshot():Readonly<Record<string,unknown>>;}
export declare function gatewayStateDigest(snapshot:unknown):string;
