import {createHash} from "node:crypto";
import {DatabaseSync} from "node:sqlite";
const PROTOCOL="ynx-code-memory/v1",MAX_BODY=64*1024;
export function createProjectMemory({filename,ownerForRequest,workspaceStore,embed=createOllamaEmbedder()}){
 const db=new DatabaseSync(filename);db.exec("PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL; PRAGMA busy_timeout=5000; CREATE TABLE IF NOT EXISTS memory_chunks(owner_id TEXT NOT NULL,project_id TEXT NOT NULL,revision INTEGER NOT NULL,path TEXT NOT NULL,chunk_index INTEGER NOT NULL,digest TEXT NOT NULL,content TEXT NOT NULL,vector TEXT NOT NULL,dimensions INTEGER NOT NULL,indexed_at TEXT NOT NULL,PRIMARY KEY(owner_id,project_id,path,chunk_index)); CREATE INDEX IF NOT EXISTS memory_scope ON memory_chunks(owner_id,project_id,revision);");
 const remove=db.prepare("DELETE FROM memory_chunks WHERE owner_id=? AND project_id=?"),insert=db.prepare("INSERT INTO memory_chunks(owner_id,project_id,revision,path,chunk_index,digest,content,vector,dimensions,indexed_at) VALUES(?,?,?,?,?,?,?,?,?,?)"),read=db.prepare("SELECT revision,path,chunk_index,digest,content,vector,dimensions,indexed_at FROM memory_chunks WHERE owner_id=? AND project_id=?"),count=db.prepare("SELECT COUNT(*) count,MAX(revision) revision,MAX(indexed_at) indexed_at FROM memory_chunks WHERE owner_id=? AND project_id=?");
 async function index(owner,projectId,expectedRevision){const workspace=workspaceStore.get(owner,projectId);if(!workspace)throw fault("Workspace not found.","workspace_not_found",404);if(workspace.revision!==expectedRevision)throw fault("Workspace revision changed before memory indexing.","revision_conflict",409);const chunks=chunkWorkspace(workspace.files),vectors=chunks.length?await embed(chunks.map(chunk=>chunk.content)):[];if(vectors.length!==chunks.length||vectors.some(vector=>!validVector(vector)))throw fault("Embedding service returned invalid vectors.","invalid_embedding_result",502);const now=new Date().toISOString();db.exec("BEGIN IMMEDIATE");try{remove.run(owner,projectId);chunks.forEach((chunk,index)=>insert.run(owner,projectId,workspace.revision,chunk.path,chunk.index,sha(chunk.content),chunk.content,JSON.stringify(vectors[index]),vectors[index].length,now));db.exec("COMMIT")}catch(error){try{db.exec("ROLLBACK")}catch{}throw error}return{protocolVersion:PROTOCOL,projectId,revision:workspace.revision,chunks:chunks.length,dimensions:vectors[0]?.length||0,indexedAt:now,embeddingModel:"nomic-embed-text"};}
 async function search(owner,projectId,query,limit=8,allowedPaths){query=text(query,2,1000,"query");limit=Math.max(1,Math.min(Number(limit)||8,20));const allow=Array.isArray(allowedPaths)?new Set(allowedPaths):null,rows=read.all(owner,projectId).filter(row=>!allow||allow.has(row.path));if(!rows.length)return{protocolVersion:PROTOCOL,projectId,results:[],indexedRevision:null};const [needle]=await embed([query]);if(!validVector(needle))throw fault("Embedding service returned an invalid query vector.","invalid_embedding_result",502);const results=rows.filter(row=>row.dimensions===needle.length).map(row=>({path:row.path,chunkIndex:Number(row.chunk_index),digest:row.digest,content:row.content,score:cosine(needle,JSON.parse(row.vector)),revision:Number(row.revision)})).sort((a,b)=>b.score-a.score).slice(0,limit);return{protocolVersion:PROTOCOL,projectId,indexedRevision:Number(rows[0].revision),embeddingModel:"nomic-embed-text",results};}
 async function handler(request,response){const url=new URL(request.url,`http://${request.headers.host||"127.0.0.1"}`);if(!url.pathname.startsWith("/runtime/memory/"))return false;const owner=ownerForRequest(request);if(!owner)return json(response,401,{error:"A signed workspace session is required.",code:"workspace_session_required"}),true;try{const projectId=validId(url.pathname.split("/")[3]);if(request.method==="GET"){const query=url.searchParams.get("q");if(query){json(response,200,await search(owner,projectId,query,url.searchParams.get("limit")));return true}const value=count.get(owner,projectId);json(response,200,{protocolVersion:PROTOCOL,projectId,chunks:Number(value.count),revision:value.revision==null?null:Number(value.revision),indexedAt:value.indexed_at||null});return true}if(request.method==="POST"){const body=JSON.parse((await readBody(request)).toString("utf8"));if(body.protocolVersion!==PROTOCOL)throw fault("Memory protocol version is required.","protocol_mismatch",400);json(response,200,await index(owner,projectId,Number(body.expectedRevision)));return true}throw fault("Method not allowed.","method_not_allowed",405)}catch(error){json(response,error.status||400,{error:error.message||"Project memory operation failed.",code:error.code||"memory_operation_failed"});return true}}
 return{handler,index,search,close:()=>db.close()};
}
export function createOllamaEmbedder({baseURL=process.env.YNX_CODE_EMBEDDING_URL||"http://127.0.0.1:11434",model=process.env.YNX_CODE_EMBEDDING_MODEL||"nomic-embed-text",fetchImpl=globalThis.fetch}={}){if(!/^http:\/\/127\.0\.0\.1(?::\d+)?$/.test(baseURL))throw new Error("Embedding service must use the fixed loopback boundary.");return async inputs=>{if(!Array.isArray(inputs)||inputs.length<1||inputs.length>512)throw fault("Embedding batch is outside its boundary.","invalid_embedding_batch",400);const response=await fetchImpl(`${baseURL}/api/embed`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({model,input:inputs,truncate:true,keep_alive:"10m"}),signal:AbortSignal.timeout(120000)}).catch(()=>null);if(!response?.ok)throw fault("Embedding service is unavailable.","embedding_unavailable",503);const value=await response.json();return value.embeddings||[]};}
function chunkWorkspace(files){const chunks=[];for(const path of Object.keys(files).sort()){const content=files[path];if(!content.trim())continue;const lines=content.split("\n");for(let start=0,index=0;start<lines.length&&chunks.length<4096;start+=80,index++)chunks.push({path,index,content:`Path: ${path}\nLines ${start+1}-${Math.min(start+120,lines.length)}\n${lines.slice(start,start+120).join("\n")}`});}return chunks;}
function validVector(value){return Array.isArray(value)&&value.length>=64&&value.length<=4096&&value.every(number=>Number.isFinite(number));}function cosine(a,b){let dot=0,aa=0,bb=0;for(let i=0;i<a.length;i++){dot+=a[i]*b[i];aa+=a[i]*a[i];bb+=b[i]*b[i]}return aa&&bb?dot/Math.sqrt(aa*bb):0;}function sha(value){return createHash("sha256").update(value).digest("hex")}function validId(value){if(typeof value!=="string"||!/^[-A-Za-z0-9_]{1,160}$/.test(value))throw fault("Invalid project identifier.","invalid_project",400);return value}function text(value,min,max,label){const result=typeof value==="string"?value.trim():"";if(result.length<min||result.length>max)throw fault(`Invalid ${label}.`,`invalid_${label}`,400);return result}function fault(message,code,status){return Object.assign(new Error(message),{code,status})}async function readBody(request){const chunks=[];let size=0;for await(const chunk of request){size+=chunk.length;if(size>MAX_BODY)throw fault("Request too large.","request_too_large",413);chunks.push(chunk)}return Buffer.concat(chunks)}function json(response,status,value){response.writeHead(status,{"content-type":"application/json; charset=utf-8","cache-control":"no-store"});response.end(JSON.stringify(value))}
