import{applyLocale,erasureT,selectedLocale}from'./i18n.js';
import{authT,applyAuthLocale}from'./auth-i18n.js';
import{createCloudLogin,selectCloudWallet}from'./wallet-login.js';
import{createCloudPrivateSession}from'./cloud-private-session.js';
import{createCloudAPI}from'./cloud-api.js';
import{StandardWalletConnection}from'../../../packages/dapp-connect-sdk/src/provider.js';
import{discoverEIP6963}from'../../../packages/dapp-connect-sdk/src/discovery.js';
import{YNX_TESTNET}from'../../../packages/dapp-connect-sdk/src/constants.js';
const $ = (q) => document.querySelector(q);
const $$ = (q) => [...document.querySelectorAll(q)];
const state = { privateSession:null, erasureToken:'', authMode:'normal', standardWallet:null, objects: [], selected: new Set(), current: null, view: 'files', parentId: '' };
const apiBase=YNX_CLOUD_RUNTIME.apiBase;
let authKey='ready',authError=false,connectionCleanup=[],privateEpoch=0;
const locale=()=>document.documentElement.lang||selectedLocale();
function authMessage(key,error=false){authKey=key;authError=error;$('#auth-state').textContent=authT(locale(),key);$('#auth-state').classList.toggle('danger',error)}
function clearPrivateView(){privateEpoch+=1;loadRevision+=1;detailRevision+=1;state.erasureToken='';state.objects=[];state.selected.clear();state.current=null;state.parentId='';$('#files').replaceChildren();$('#empty').hidden=false;$('#details').hidden=true;$('#preview').textContent='';$('#detail-panel').replaceChildren();$('#grant-list').replaceChildren();$('#ai-result').textContent='';$('#ai-context').textContent='';$('#quota-used').textContent='—';$('#quota-bar').value=0;$('#quota-limit').textContent=' / —';$('#erase-submit').disabled=true;$('#erase-receipts').disabled=true;}
function walletLabel(){if(state.privateSession?.status==='connected'&&state.privateSession.session?.account){const account=state.privateSession.session.account;$('#wallet').dataset.connected='true';$('#wallet').textContent='YNX Cloud · '+account.slice(0,10)+'…'+account.slice(-6);return}const wallet=state.standardWallet;if(wallet?.account){$('#wallet').dataset.connected='true';$('#wallet').textContent=(wallet.cloudWalletKind==='metamask'?'MetaMask':'YNX Wallet')+' · '+wallet.account.slice(0,8)+'…'+wallet.account.slice(-6)}else{delete $('#wallet').dataset.connected;applyLocale(locale())}}
function acceptConnection(connection,result,kind){connection.cloudWalletKind=kind;connectionCleanup.forEach(off=>off());connectionCleanup=[];clearPrivateView();state.standardWallet=connection;walletLabel();status(authT(locale(),'privateUnavailable'));
 const reset=()=>{clearPrivateView();state.standardWallet=null;connectionCleanup.forEach(off=>off());connectionCleanup=[];walletLabel();authMessage('ready');status(authT(locale(),'guest'))};
 if(typeof connection.provider.on==='function'&&typeof connection.provider.removeListener==='function'){
  connectionCleanup.push(connection.on('accountsChanged',accounts=>{if(!Array.isArray(accounts)||!/^0x[0-9a-fA-F]{40}$/.test(accounts[0]||'')){reset();return}clearPrivateView();connection.account=accounts[0];walletLabel();status(authT(locale(),'privateUnavailable'))}));
  connectionCleanup.push(connection.on('chainChanged',chain=>{if(String(chain).toLowerCase()!=='0x1917')reset()}));
  connectionCleanup.push(connection.on('disconnect',reset));
 }
}
const login=createCloudLogin({discover:walletProviders,createConnection:provider=>new StandardWalletConnection(provider,{chain:YNX_TESTNET}),addChain:{chainId:'0x1917',chainName:'YNX Testnet',nativeCurrency:{name:'YNX Testnet',symbol:'YNXT',decimals:18},rpcUrls:[YNX_CLOUD_RUNTIME.evmRpc],blockExplorerUrls:[YNX_CLOUD_RUNTIME.explorer]},connected:acceptConnection,message:authMessage,busy:value=>{for(const id of ['auth-start','auth-metamask'])$('#'+id).disabled=value}});

function operationFailure(error){$('#auth-diagnostic').textContent=error.code||String(error.status||'CLOUD_REQUEST_FAILED');status(authT(locale(),error.code==='V2_ROUTE_NOT_ENABLED'?'actionUnavailable':error.status===401||['SESSION_EXPIRED','SESSION_INACTIVE','PROOF_EXPIRED'].includes(error.code)?'expired':error.code==='CLOUD_WRITE_UNCONFIRMED'?'writeUnconfirmed':'requestFailed'),true)}
function status(message, error=false){ $('#status').textContent=message; $('#status').classList.toggle('danger',error); }
function bytes(n){if(n<1024)return `${n} B`;if(n<1048576)return `${(n/1024).toFixed(1)} KB`;return `${(n/1048576).toFixed(1)} MB`}
const privateConnected=()=>state.privateSession?.status==='connected'&&!!state.privateSession.session?.account;
let selection=0,successfulClose=false,cancelledClose=false,providerCleanup=[],loadRevision=0,detailRevision=0;
const privateSession=createCloudPrivateSession({publish:result=>{const previous=state.privateSession;state.privateSession=result;if(previous?.session?.account!==result.session?.account||previous?.status!==result.status)clearPrivateView();walletLabel();$('#auth-disconnect').hidden=result.status!=='connected'&&!result.revocationPending;if(result.status==='connected')status(authT(locale(),'filesConnected'));else if(result.status==='expired')status(authT(locale(),'expired'),true);else if(result.revocationPending)status(authT(locale(),'revocationPending'),true)}});
const api=createCloudAPI({session:privateSession,base:apiBase,failed:code=>{$('#auth-diagnostic').textContent=code}});
function selectionStep(kind){$('#auth-choices').hidden=!!kind;$('#auth-step').hidden=!kind;$('#auth-selected').textContent=kind==='ynx'?'YNX Wallet':kind==='metamask'?'MetaMask':authT(locale(),kind);$('#auth-retry').hidden=!kind;for(const id of ['auth-start','auth-metamask','auth-hosted','auth-mobile'])$('#'+id).disabled=false;}
async function cancelSelection(){const epoch=++selection;login.cancel();selectionStep(null);try{await privateSession.cancel()}catch(error){if(epoch!==selection)return;$('#auth-diagnostic').textContent=error.code||'REVOCATION_PENDING';authMessage('revocationPending',true)}}
function watchPrivateProvider(provider){providerCleanup.forEach(off=>off());providerCleanup=[];if(typeof provider.on!=='function'||typeof provider.removeListener!=='function')return;for(const event of ['accountsChanged','chainChanged','disconnect']){const changed=()=>{++selection;clearPrivateView();void privateSession.disconnect().catch(error=>{$('#auth-diagnostic').textContent=error.code||'REVOCATION_PENDING'});};provider.on(event,changed);providerCleanup.push(()=>provider.removeListener(event,changed));}}
async function startPrivateWallet(){const epoch=++selection;selectionStep('ynx');authMessage('waiting');$('#auth-retry').disabled=true;try{const selected=selectCloudWallet(await walletProviders(),'ynx');if(epoch!==selection)return;if(!selected){authMessage('missingYNX',true);return}connectionCleanup.forEach(off=>off());connectionCleanup=[];state.standardWallet=null;watchPrivateProvider(selected.provider);const result=await privateSession.connect(selected.provider);if(epoch!==selection)return;if(result.status==='connected'){successfulClose=true;$('#auth-dialog').close();authMessage('filesConnected');await load()}else authMessage(result.status==='expired'?'expired':'failed',true)}catch(error){if(epoch!==selection)return;$('#auth-diagnostic').textContent=String(error.code||'CLOUD_SIGNIN_FAILED');authMessage(['4001','WALLET_USER_REJECTED'].includes(String(error.code))?'rejected':error.code==='REVOCATION_PENDING'?'revocationPending':'failed',true)}finally{if(epoch===selection)$('#auth-retry').disabled=false}}
async function restorePrivate(){try{const result=await privateSession.restore();if(result.status==='connected'){const selected=selectCloudWallet(await walletProviders(),'ynx');if(selected&&privateConnected())watchPrivateProvider(selected.provider)}await load()}catch(error){$('#auth-diagnostic').textContent=error.code||'CLOUD_RESTORE_FAILED';status(authT(locale(),'failed'),true)}}


async function signIn(mode='normal'){state.authMode=typeof mode==='string'?mode:'normal';if(state.authMode==='erasure'){status(authT(locale(),'actionUnavailable'),true);return}if(!$('#auth-dialog').open){selectionStep(null);authMessage('ready');$('#auth-dialog').showModal();}$('#auth-disconnect').hidden=!privateConnected()&&!state.privateSession?.revocationPending;}
async function walletProviders(){const providers=await discoverEIP6963(window,{timeoutMs:220});if(window.ethereum?.request&&!providers.some(entry=>entry.provider===window.ethereum))providers.push({info:{uuid:'legacy-injected'},provider:window.ethereum});return providers}
async function startWallet(metaMaskOnly=false){if(!metaMaskOnly)return startPrivateWallet();const epoch=++selection;selectionStep('metamask');$('#auth-retry').hidden=true;try{if(privateConnected()||state.privateSession?.revocationPending){await privateSession.disconnect();if(epoch!==selection)return;if(state.privateSession?.revocationPending){authMessage('revocationPending',true);return}}providerCleanup.forEach(off=>off());providerCleanup=[];if(epoch===selection)return login.start('metamask')}catch(error){if(epoch===selection)operationFailure(error)}}
async function load(){ if(!privateConnected()){status(authT(locale(),state.standardWallet?'privateUnavailable':'guest'));$('#empty').hidden=false;return} const read=++loadRevision;try{if(state.view==='audit'){const events=await api('/audit');renderAudit(events);await loadQuota();status(`${events.length} authorized audit events`);return}const query=new URLSearchParams({limit:'200'});if(state.parentId)query.set('parentId',state.parentId);if(state.view!=='files'&&state.view!=='shared')query.set('view',state.view);const q=$('#search').value.trim();if(q)query.set('q',q);const page=await api(`/objects?${query}`);if(read!==loadRevision)return;if(!page||!Array.isArray(page.items))throw new Error('Cloud file response was not recognized.');state.objects=page.items;render();walletLabel();status(`${state.objects.length} authorized item${state.objects.length===1?'':'s'}${page.nextCursor?' · More available through paged API':''} · Synced ${new Date().toLocaleTimeString()}`)}catch(e){if(e.status===401){clearPrivateView();walletLabel()}operationFailure(e)}}
function renderAudit(events){const root=$('#files');root.replaceChildren();$('#empty').hidden=events.length!==0;for(const e of events){const row=document.createElement('article');row.className='file';const title=document.createElement('strong');title.textContent=e.action;const meta=document.createElement('span');meta.className='file-meta';meta.textContent=`${new Date(e.at).toLocaleString()} · ${e.actor}${e.objectId?` · ${e.objectId}`:''}`;row.append(title,meta);root.append(row)}}
async function checkSharedIntent(){const token=new URLSearchParams(location.search).get('share');if(!token)return;try{const response=await fetch(`${apiBase}/shares/${encodeURIComponent(token)}`);const object=await response.json();if(!response.ok)throw new Error(object.error||'Share link unavailable');const root=$('#files');root.replaceChildren();$('#empty').hidden=true;const card=document.createElement('article');card.className='file';const title=document.createElement('strong');title.textContent=object.name;const meta=document.createElement('span');meta.className='file-meta';meta.textContent=`Time-bounded view link · ${object.kind} · v${object.version}`;const preview=document.createElement('button');preview.className='quiet';preview.textContent='Open shared preview';preview.onclick=()=>window.open(`${apiBase}/shares/${encodeURIComponent(token)}/content`,'_blank','noopener');const request=document.createElement('button');request.className='quiet';request.textContent='Request ongoing access';request.onclick=async()=>{if(!privateConnected())return signIn();try{await api(`/objects/${object.id}/access-requests`,{method:'POST',body:JSON.stringify({role:'viewer',message:'Requested from a time-bounded share link'})});status('Access request sent. The owner must approve it explicitly.')}catch(e){operationFailure(e)}};card.append(title,meta,preview,request);root.append(card);$('#view-title').textContent='Shared item';$('#view-subtitle').textContent='The link expires and can be revoked. Ongoing access requires owner approval.'}catch(e){operationFailure(e)}}
function render(){const root=$('#files');root.replaceChildren();$('#empty').hidden=state.objects.length!==0;for(const o of state.objects){const b=document.createElement('button');b.className='file'+(state.selected.has(o.id)?' selected':'');b.dataset.id=o.id;b.setAttribute('aria-pressed',state.selected.has(o.id));b.innerHTML=`<span class="file-name"></span><span class="file-kind">${o.kind}</span><span class="file-size">${o.kind==='folder'?'—':bytes(o.size)}</span><span class="file-meta">v${o.version||0} · ${new Date(o.updatedAt).toLocaleString()}${o.starred?' · Starred':''}</span>`;b.querySelector('.file-name').textContent=o.name;b.addEventListener('click',e=>{if(e.metaKey||e.ctrlKey){state.selected.has(o.id)?state.selected.delete(o.id):state.selected.add(o.id);render();updateAIContext()}else if(o.kind==='folder'){state.parentId=o.id;load()}else{openDetails(o)}});root.append(b)}}
async function loadQuota(){const q=await api('/quota');$('#quota-used').textContent=bytes(q.usedBytes);$('#quota-limit').textContent=` / ${bytes(q.limitBytes)}`;$('#quota-bar').value=Math.min(100,q.usedBytes/q.limitBytes*100)}
async function createFolder(){if(!privateConnected())return signIn();const name=prompt('Folder name');if(!name)return;try{await api('/objects',{method:'POST',body:JSON.stringify({kind:'folder',name,parentId:state.parentId,content:''})});await load()}catch(e){operationFailure(e)}}
function syncDB(){return new Promise((resolve,reject)=>{const request=indexedDB.open('ynx-cloud-sync',1);request.onupgradeneeded=()=>request.result.createObjectStore('uploads',{keyPath:'id'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function queueUpload(file){const account=state.privateSession.session.account,epoch=privateEpoch,parentId=state.parentId;const db=await syncDB();if(epoch!==privateEpoch){db.close();throw Object.assign(new Error('Cloud account changed.'),{code:'PRIVATE_CONTEXT_CHANGED'})}await new Promise((resolve,reject)=>{const tx=db.transaction('uploads','readwrite');tx.objectStore('uploads').put({id:crypto.randomUUID(),account,name:file.name,mime:file.type||'application/octet-stream',parentId,blob:file,queuedAt:new Date().toISOString()});tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close()}
async function uploadOne(file,parentId=state.parentId){const epoch=privateEpoch;const content=await file.arrayBuffer();if(epoch!==privateEpoch)throw Object.assign(new Error('Cloud account changed.'),{code:'PRIVATE_CONTEXT_CHANGED'});let binary='';const bytes=new Uint8Array(content);for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));await api('/objects',{method:'POST',body:JSON.stringify({kind:'file',name:file.name,mime:file.type||'application/octet-stream',parentId,content:btoa(binary),encryption:{clientSide:false}})})}
async function directUploadOne(file,parentId=state.parentId){const epoch=privateEpoch;const content=await file.arrayBuffer(),digest=new Uint8Array(await crypto.subtle.digest('SHA-256',content)),hash=[...digest].map(x=>x.toString(16).padStart(2,'0')).join('');if(epoch!==privateEpoch)throw Object.assign(new Error('Cloud account changed.'),{code:'PRIVATE_CONTEXT_CHANGED'});const initiated=await api('/direct-uploads',{method:'POST',body:JSON.stringify({name:file.name,mime:file.type||'application/octet-stream',parentId,expectedSize:file.size,expectedHash:hash,encryption:{clientSide:false}})}),id=initiated.upload.id,plan=initiated.plan;try{const response=await fetch(plan.url,{method:plan.method,headers:plan.headers,body:file});if(!response.ok)throw new Error(`object provider upload failed: ${response.status}`);await api(`/direct-uploads/${id}/complete`,{method:'POST'})}catch(e){try{await api(`/direct-uploads/${id}`,{method:'DELETE'})}catch{}throw e}}
async function upload(files){if(!privateConnected())return signIn();const epoch=privateEpoch;for(const file of files){if(epoch!==privateEpoch)break;if(file.size>67108864){status(`${file.name} exceeds this browser client's 64 MB verified-upload limit. Use the API/SDK after a production provider is configured.`,true);continue}try{if(!navigator.onLine){await queueUpload(file);status(`${file.name} queued locally for explicit sync.`)}else{file.size<=8388608?await uploadOne(file):await directUploadOne(file);status(`Uploaded ${file.name}`)}}catch(e){status(`${file.name}: ${e.message}`,true)}}if(navigator.onLine)await load()}
async function syncQueued(){if(!navigator.onLine||!privateConnected())return;const account=state.privateSession.session.account,epoch=privateEpoch;const db=await syncDB();const queued=await new Promise((resolve,reject)=>{const r=db.transaction('uploads').objectStore('uploads').getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});if(epoch!==privateEpoch){db.close();return}let synced=0;for(const item of queued){if(item.account!==account)continue;if(epoch!==privateEpoch)break;try{const file=new File([item.blob],item.name,{type:item.mime});file.size<=8388608?await uploadOne(file,item.parentId):await directUploadOne(file,item.parentId);if(epoch!==privateEpoch)break;synced++;await new Promise((resolve,reject)=>{const tx=db.transaction('uploads','readwrite');tx.objectStore('uploads').delete(item.id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}catch(e){status(`Sync paused at ${item.name}: ${e.message}`,true);break}}db.close();if(synced)await load()}
async function openDetails(o){const epoch=privateEpoch;detailRevision+=1;$('#detail-panel').replaceChildren();state.current=o;$('#details').hidden=false;$('#detail-name').textContent=o.name;$('#metadata').innerHTML=`<dt>Owner</dt><dd>${o.owner}</dd><dt>Version</dt><dd>${o.version}</dd><dt>Integrity</dt><dd>${o.hash||'folder metadata only'}</dd><dt>Encryption</dt><dd>${o.encryption.clientSide?'Client-side; server has no key':'Server-readable within explicit permissions'}</dd><dt>Scan</dt><dd>${o.scanStatus||'not applicable'}</dd>`;$('#star').textContent=o.starred?'Unstar':'Star';$('#trash').textContent=o.trashedAt?'Restore':'Move to trash';$('#delete').hidden=!o.trashedAt;$('#preview').textContent='Loading verified preview…';try{if(o.mime?.startsWith('text/')||o.mime?.includes('json')||o.kind==='doc'){const blob=await api(`/objects/${o.id}/content`);const text=await blob.text();if(epoch!==privateEpoch||state.current!==o)return;$('#preview').textContent=text.slice(0,6000)||'Empty file'}else{$('#preview').textContent='Preview is bounded to safe text in this client. Download verifies the content hash.'}}catch(e){if(epoch===privateEpoch&&state.current===o)$('#preview').textContent=authT(locale(),'failed')}}
async function permanentDelete(){if(!state.current?.trashedAt)return;const confirmation=prompt(`Type DELETE to permanently remove ${state.current.name}. This cannot be undone.`);if(confirmation!=='DELETE'){status('Permanent deletion canceled.');return}try{await api(`/objects/${state.current.id}`,{method:'DELETE',body:JSON.stringify({confirm:'DELETE'})});$('#details').hidden=true;status('Object deleted. Content-addressed blob retention follows the operator policy.');await load()}catch(e){operationFailure(e)}}
async function mutate(path,body){try{await api(path,{method:'POST',body:body?JSON.stringify(body):undefined});$('#details').hidden=true;await load()}catch(e){operationFailure(e)}}
async function download(){const o=state.current;if(!o)return;try{const blob=await api(`/objects/${o.id}/content`);const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=o.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){operationFailure(e)}}
async function exportData(){if(!privateConnected())return signIn();try{status('Building a verified portable export…');const blob=await api('/export');const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`ynx-cloud-export-${new Date().toISOString().slice(0,10)}.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('Portable export downloaded. Keep it private: it contains every owned version and permission metadata.')}catch(e){operationFailure(e)}}
function openErasure(){$('#erase-confirm').value='';$('#erase-submit').disabled=true;$('#erase-export').disabled=!privateConnected();$('#erase-result').textContent='';$('#erase-receipts').disabled=!state.erasureToken;$('#erase-dialog').showModal()}
async function eraseData(){if($('#erase-confirm').value!=='DELETE CLOUD DATA'||!state.erasureToken)return;try{const receipt=await api('/account-data',{token:state.erasureToken,method:'DELETE',body:JSON.stringify({confirm:'DELETE CLOUD DATA'})});state.erasureToken='';state.objects=[];state.selected.clear();render();walletLabel();$('#erase-submit').disabled=true;$('#erase-receipts').disabled=true;$('#erase-result').textContent=`${receipt.pendingBlobs?erasureT(selectedLocale(),'pending'):erasureT(selectedLocale(),'complete')} ${receipt.id}`;}catch(e){$('#erase-result').textContent=e.message}}
async function recoverErasureReceipts(){if(!state.erasureToken)return signIn('erasure');try{const receipts=await api('/account-data/erasures',{token:state.erasureToken});$('#erase-result').textContent=receipts.length?receipts.map(x=>`${x.id} · ${x.pendingBlobs?erasureT(selectedLocale(),'pending'):erasureT(selectedLocale(),'complete')}`).join('\n'):'—'}catch(e){$('#erase-result').textContent=e.message}}
async function showVersions(){const object=state.current,epoch=privateEpoch,revision=++detailRevision;if(!object)return;const live=()=>epoch===privateEpoch&&revision===detailRevision&&state.current===object&&!$('#details').hidden;try{const list=await api(`/objects/${object.id}/versions`);if(!live())return;if(!Array.isArray(list)||list.some(v=>!Number.isInteger(v.number)||v.number<1))throw Object.assign(new Error('Invalid version response.'),{code:'CLOUD_RESPONSE_INVALID'});const root=$('#detail-panel');root.replaceChildren();const heading=document.createElement('h3');heading.textContent='Version history';root.append(heading);for(const version of list){const row=document.createElement('div');row.className='grant-row';const label=document.createElement('p');label.textContent=`v${version.number} · ${bytes(version.size)} · ${new Date(version.createdAt).toLocaleString()}`;const restore=document.createElement('button');restore.className='quiet';restore.textContent='Restore as new version';restore.onclick=async()=>{if(!live())return;restore.disabled=true;try{await api(`/objects/${object.id}/versions/${version.number}/restore`,{method:'POST'});if(!live())return;$('#details').hidden=true;await load()}catch(error){if(live()){restore.disabled=false;operationFailure(error)}}};row.append(label,restore);root.append(row)}}catch(error){if(live())operationFailure(error)}}
async function showShare(){if(!state.current)return;$('#share-dialog').showModal();try{const [grants,links]=await Promise.all([api(`/objects/${state.current.id}/grants`),api(`/objects/${state.current.id}/links`)]);$('#grant-list').innerHTML=grants.map(g=>`<div class="grant-row">${g.principal}<br>${g.role}${g.expiresAt?` · expires ${new Date(g.expiresAt).toLocaleString()}`:''}${g.revokedAt?' · revoked':` <button data-revoke="${g.id}">Revoke</button>`}</div>`).join('')+links.map(l=>`<div class="grant-row">View link · expires ${new Date(l.expiresAt).toLocaleString()}${l.revokedAt?' · revoked':` <button data-link-revoke="${l.id}">Revoke link</button>`}</div>`).join('')||'<p class="callout">No additional grants or links.</p>';$$('[data-revoke]').forEach(b=>b.onclick=async()=>{await api(`/objects/${state.current.id}/grants/${b.dataset.revoke}`,{method:'DELETE'});showShare()});$$('[data-link-revoke]').forEach(b=>b.onclick=async()=>{await api(`/objects/${state.current.id}/links/${b.dataset.linkRevoke}`,{method:'DELETE'});showShare()})}catch(e){$('#grant-list').textContent=e.message}}
async function grant(){try{const expires=$('#share-expiry').value?new Date($('#share-expiry').value).toISOString():null;await api(`/objects/${state.current.id}/grants`,{method:'POST',body:JSON.stringify({principal:$('#share-account').value,role:$('#share-role').value,expiresAt:expires})});showShare()}catch(e){operationFailure(e)}}
async function createLink(){try{const r=await api(`/objects/${state.current.id}/links`,{method:'POST',body:JSON.stringify({role:'viewer',expiresAt:new Date(Date.now()+86400000).toISOString()})});await navigator.clipboard?.writeText(`${location.origin}${apiBase}/shares/${r.token}`);status('A 24-hour view link was created and copied. It can be revoked from the API audit surface.')}catch(e){operationFailure(e)}}
function updateAIContext(){const chosen=state.objects.filter(o=>state.selected.has(o.id)&&o.kind!=='folder');$('#ai-context').textContent=chosen.length?chosen.map(o=>`${o.name} · ${o.id}@v${o.version}`).join('\n'):'No files selected.'}
async function runAI(){const chosen=state.objects.filter(o=>state.selected.has(o.id)&&o.kind!=='folder');if(!$('#ai-consent').checked){$('#ai-result').textContent='Explicit selected-context consent is required.';return}try{const provider=await api('/ai/status');$('#ai-result').textContent=`Provider: ${provider.provider} / ${provider.model}. ${provider.available?'Queued with cancel control…':'Unavailable; no canned answer will be substituted.'}`;let job=await api('/ai/jobs',{method:'POST',body:JSON.stringify({mode:$('#ai-mode').value,instruction:$('#ai-instruction').value,objectIds:chosen.map(x=>x.id),versions:chosen.map(x=>x.version),consent:true})});const cancel=document.createElement('button');cancel.className='quiet';cancel.textContent='Cancel generation';cancel.onclick=()=>api(`/ai/jobs/${job.id}/cancel`,{method:'POST'});$('#ai-result').append(document.createElement('br'),cancel);while(job.status==='queued'||job.status==='running'){await new Promise(r=>setTimeout(r,250));job=await api(`/ai/jobs/${job.id}`);$('#ai-result').firstChild.textContent=`${job.status} · estimated ${job.estimatedUnits} resource units`;}$('#ai-result').replaceChildren(document.createTextNode(job.status==='review'?`${job.result}\n\nCitations: ${job.citations.join(', ')}`:`${job.status}: ${job.error}`));if(job.status==='review'){for(const decision of ['applied','rejected']){const b=document.createElement('button');b.className='quiet';b.textContent=decision==='applied'?'Accept result':'Reject result';b.onclick=async()=>{job=await api(`/ai/jobs/${job.id}/review`,{method:'POST',body:JSON.stringify({decision})});$('#ai-result').textContent=`Result ${job.status}; source files were unchanged.`};$('#ai-result').append(document.createElement('br'),b)}}}catch(e){$('#ai-result').textContent=e.message}}
function setView(view,button){detailRevision+=1;state.view=view;state.parentId='';state.objects=[];state.selected.clear();state.current=null;$('#details').hidden=true;render();$$('[data-view]').forEach(x=>x.removeAttribute('aria-current'));button.setAttribute('aria-current','page');$('#view-title').textContent=button.textContent;load()}
function changeLocale(value){applyLocale(value);applyAuthLocale(value);authMessage(authKey,authError);if(!privateConnected())status(authT(value,state.standardWallet?'privateUnavailable':'guest'))}
changeLocale(selectedLocale());$('#locale').onchange=e=>changeLocale(e.target.value);
const cancelBeforeClose=()=>{cancelledClose=true;void cancelSelection()};
$('#auth-dialog').addEventListener('submit',cancelBeforeClose);$('#auth-dialog').addEventListener('cancel',cancelBeforeClose);
$('#auth-dialog').addEventListener('close',()=>{if(successfulClose){successfulClose=false;return}if(cancelledClose){cancelledClose=false;return}void cancelSelection()});
$('#auth-back').onclick=()=>void cancelSelection();$('#auth-retry').onclick=startPrivateWallet;$('#auth-disconnect').onclick=async()=>{const epoch=++selection;try{await privateSession.disconnect();if(epoch!==selection)return;selectionStep(null);authMessage(state.privateSession?.revocationPending?'revocationPending':'guest')}catch(error){if(epoch===selection){authMessage('revocationPending',true);$('#auth-diagnostic').textContent=error.code||'REVOCATION_PENDING'}}};
for(const kind of ['hosted','mobile'])$('#auth-'+kind).onclick=()=>{selectionStep(kind);$('#auth-retry').hidden=true;authMessage('transportUnavailable',true)};
$('#erase-open').onclick=openErasure;$('#erase-export').onclick=exportData;$('#erase-authorize').onclick=()=>{$('#erase-dialog').close();signIn('erasure')};$('#erase-confirm').oninput=e=>$('#erase-submit').disabled=e.target.value!=='DELETE CLOUD DATA'||!state.erasureToken;$('#erase-submit').onclick=eraseData;$('#erase-receipts').onclick=recoverErasureReceipts;
$('#wallet').onclick=signIn;$('#auth-start').onclick=startWallet;$('#new-folder').onclick=createFolder;$('#upload').onchange=e=>upload(e.target.files);$('#export-data').onclick=exportData;$('#search').oninput=()=>{clearTimeout(window.searchTimer);window.searchTimer=setTimeout(load,250)};$$('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view,b));$('#sync').onclick=syncQueued;$('#details-close').onclick=()=>{detailRevision+=1;$('#details').hidden=true;$('#detail-panel').replaceChildren()};$('#download').onclick=download;$('#star').onclick=()=>mutate(`/objects/${state.current.id}/star`,{starred:!state.current.starred});$('#trash').onclick=()=>mutate(`/objects/${state.current.id}/${state.current.trashedAt?'restore':'trash'}`);$('#delete').onclick=permanentDelete;$('#versions').onclick=showVersions;$('#share').onclick=showShare;$('#share-save').onclick=grant;$('#link-create').onclick=createLink;$('#ai-open').onclick=()=>{$('#ai-panel').hidden=false;updateAIContext()};$('#ai-close').onclick=()=>$('#ai-panel').hidden=true;$('#ai-run').onclick=runAI;window.addEventListener('offline',()=>$('#offline').hidden=false);window.addEventListener('online',()=>{$('#offline').hidden=true});document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();$('#search').focus()}});restorePrivate().then(checkSharedIntent);
$('#auth-start').onclick=()=>startWallet(false);$('#auth-metamask').onclick=()=>startWallet(true);

window.addEventListener('pagehide',()=>privateSession.close());
window.addEventListener('pageshow',event=>{if(event.persisted)void restorePrivate()});
