import SwiftUI
import AVFoundation
import MediaPlayer
import CryptoKit
import Security
import UniformTypeIdentifiers

struct CatalogFile: Decodable { let version: Int; let locales: [String]; let catalog: [String:[String:String]] }
@MainActor final class I18n: ObservableObject {
    static let shared = I18n(); @Published var tag: String; @Published var aiLanguage: String
    private var file = CatalogFile(version: 1, locales: ["en"], catalog: ["en":[:]])
    private init(){ tag=UserDefaults.standard.string(forKey:"locale") ?? "system"; aiLanguage=UserDefaults.standard.string(forKey:"aiLanguage") ?? "system"; if let u=Bundle.main.url(forResource:"i18n",withExtension:"json"),let d=try? Data(contentsOf:u),let v=try? JSONDecoder().decode(CatalogFile.self,from:d){file=v} }
    var resolved:String { if tag != "system" { return tag }; let id=Locale.current.identifier.replacingOccurrences(of:"_",with:"-"); return file.locales.first(where:{id.hasPrefix($0)}) ?? "en" }
    var rtl:Bool { resolved == "ar" }
    func t(_ key:String)->String { file.catalog[resolved]?[key] ?? file.catalog["en"]?[key] ?? "[\(key)]" }
    func set(_ value:String){tag=value;UserDefaults.standard.set(value,forKey:"locale")}
    func setAI(_ value:String){aiLanguage=value;UserDefaults.standard.set(value,forKey:"aiLanguage")}
    func number(_ value:Int)->String { let f=NumberFormatter();f.locale=Locale(identifier:resolved);f.numberStyle = .decimal;return f.string(from:NSNumber(value:value)) ?? "\(value)" }
    func date(_ value:Date)->String { value.formatted(.dateTime.locale(Locale(identifier:resolved)).year().month().day().hour().minute()) }
}

struct Track: Codable, Identifiable { let id,title,artistName:String; var album:String?; var explicit:Bool; var durationMillis:Int; var rights:Rights; var provenance:[String:String] }
struct Rights:Codable { let basis,evidenceRef:String;let territories:[String] }
struct Snapshot:Codable { var catalog:[Track]=[];var usage:[Usage]=[] }
struct Usage:Codable,Identifiable{let id,trackId:String;let listenedMillis:Int}
struct LocalState:Codable { var favorites:[String]=[];var queue:[String]=[];var downloads:[String:String]=[:];var trackId="";var position:Double=0;var aiEnabled=true }

actor MusicAPI {
    let base=URL(string:UserDefaults.standard.string(forKey:"api") ?? "http://127.0.0.1:6436")!
    func request(_ path:String,method:String="GET",body:Data?=nil,contentType:String="application/json")async throws->Data{var r=URLRequest(url:base.appending(path:path));r.httpMethod=method;r.httpBody=body;r.setValue(contentType,forHTTPHeaderField:"Content-Type");if let token=Keychain.get("session"){r.setValue("Bearer \(token)",forHTTPHeaderField:"Authorization")};r.setValue("ynx-music-ios",forHTTPHeaderField:"X-YNX-Device-ID");let(d,response)=try await URLSession.shared.data(for:r);guard let h=response as? HTTPURLResponse,(200..<300).contains(h.statusCode)else{throw URLError(.badServerResponse)};return d}
    func snapshot()async throws->Snapshot{try JSONDecoder().decode(SnapshotEnvelope.self,from:try await request("api/me")).snapshot}
    func download(_ id:String)async throws->URL{let data=try await request("api/tracks/\(id)/media");guard data.count>44,String(data:data.prefix(4),encoding:.ascii)=="RIFF" else{throw URLError(.cannotDecodeContentData)};let dir=try FileManager.default.url(for:.applicationSupportDirectory,in:.userDomainMask,appropriateFor:nil,create:true).appending(path:"Offline",directoryHint:.isDirectory);try FileManager.default.createDirectory(at:dir,withIntermediateDirectories:true);let tmp=dir.appending(path:"\(id).tmp"),out=dir.appending(path:"\(id).wav");try data.write(to:tmp,options:.atomic);try? FileManager.default.removeItem(at:out);try FileManager.default.moveItem(at:tmp,to:out);return out}
    func walletSession(response:String,nonce:String)async throws{let body=try JSONSerialization.data(withJSONObject:["response":response,"expectedNonce":nonce,"productClientId":"ynx-music-v1","bundleId":"com.ynxweb4.music"]);let d=try await request("api/auth/wallet-v1/session",method:"POST",body:body);let o=try JSONSerialization.jsonObject(with:d) as! [String:Any];guard let token=o["token"] as? String else{throw URLError(.userAuthenticationRequired)};Keychain.set("session",token)}
    func createPlaylist(name:String,ids:[String])async throws{let body=try JSONSerialization.data(withJSONObject:["name":name,"description":"Created from selected real library records","trackIDs":ids]);_ = try await request("api/playlists",method:"POST",body:body)}
    func createAI(ids:[String],language:String)async throws->String{let body=try JSONSerialization.data(withJSONObject:["kind":"playlist","intent":"Explain and organize my selected real library without inventing tracks","provider":"ynx-ai-gateway","model":"operator-selected","trackIDs":ids,"permission":true,"outputLanguage":language,"explanationRequired":true]);let d=try await request("api/ai/proposals",method:"POST",body:body);let o=try JSONSerialization.jsonObject(with:d) as? [String:Any];return "YNX AI Gateway · operator-selected · \(o?["status"] ?? "unavailable") · \(o?["estimatedUnits"] ?? 0) units"}
    func uploadOwnedWAV(_ url:URL,title:String,artist:String,evidence:String,provenance:String)async throws{let boundary="YNXMusic\(UUID().uuidString)";var data=Data();func field(_ name:String,_ value:String){data.append("--\(boundary)\r\nContent-Disposition: form-data; name=\"\(name)\"\r\n\r\n\(value)\r\n".data(using:.utf8)!)};field("title",title);field("artistName",artist);field("rightsBasis","owned");field("territories","WORLDWIDE");field("evidenceRef",evidence);field("audioProvenance",provenance);field("explicit","false");data.append("--\(boundary)\r\nContent-Disposition: form-data; name=\"audio\"; filename=\"owned.wav\"\r\nContent-Type: audio/wav\r\n\r\n".data(using:.utf8)!);data.append(try Data(contentsOf:url));data.append("\r\n--\(boundary)--\r\n".data(using:.utf8)!);_ = try await request("api/creator/tracks",method:"POST",body:data,contentType:"multipart/form-data; boundary=\(boundary)")}
    func reportPosition(id:String,session:String,position:Double,completed:Bool)async throws{let body=try JSONSerialization.data(withJSONObject:["sessionRef":session,"positionMillis":Int(position*1000),"completed":completed]);_ = try await request("api/playback/\(id)/position",method:"POST",body:body)}
    func saveLibrary(favorites:[String],queue:[String],downloads:[String:String])async throws{let body=try JSONSerialization.data(withJSONObject:["favorites":favorites,"queue":queue,"downloads":downloads]);_ = try await request("api/library",method:"PUT",body:body)}
    private struct SnapshotEnvelope:Decodable{let catalog:[Track];let usage:[Usage];var snapshot:Snapshot{Snapshot(catalog:catalog,usage:usage)}}
}

enum Keychain { static func set(_ key:String,_ value:String){let d=Data(value.utf8);SecItemDelete([kSecClass:kSecClassGenericPassword,kSecAttrAccount:key] as CFDictionary);SecItemAdd([kSecClass:kSecClassGenericPassword,kSecAttrAccount:key,kSecValueData:d,kSecAttrAccessible:kSecAttrAccessibleWhenUnlockedThisDeviceOnly] as CFDictionary,nil)};static func get(_ key:String)->String?{var out:AnyObject?;let q=[kSecClass:kSecClassGenericPassword,kSecAttrAccount:key,kSecReturnData:true] as CFDictionary;guard SecItemCopyMatching(q,&out)==errSecSuccess,let d=out as? Data else{return nil};return String(data:d,encoding:.utf8)};static func clear(){SecItemDelete([kSecClass:kSecClassGenericPassword] as CFDictionary)} }

enum WalletLink {
    static func make()throws->URL{let key:P256.Signing.PrivateKey;if let raw=Keychain.get("device-p256"),let d=Data(base64Encoded:raw),let k=try? P256.Signing.PrivateKey(rawRepresentation:d){key=k}else{key=P256.Signing.PrivateKey();Keychain.set("device-p256",key.rawRepresentation.base64EncodedString())};let nonce=random();let now=Date();UserDefaults.standard.set(nonce,forKey:"walletNonce");UserDefaults.standard.set(now.addingTimeInterval(300).timeIntervalSince1970,forKey:"walletExpires");let iso=ISO8601DateFormatter();iso.formatOptions=[.withInternetDateTime,.withFractionalSeconds];let pub=key.publicKey.compressedRepresentation.base64EncodedString().replacingOccurrences(of:"+",with:"-").replacingOccurrences(of:"/",with:"_").replacingOccurrences(of:"=",with:"");let request:[String:Any]=["version":"1","nonce":nonce,"chainId":"ynx_6423-1","requestingProduct":"music","productClientId":"ynx-music-v1","bundleId":"com.ynxweb4.music","productDeviceAlgorithm":"p256-sha256","productDeviceKey":pub,"callback":"ynxmusic://auth/callback","scopes":["music.creator","music.library","music.playback","music.profile"],"purpose":"Sign in to YNX Music without sharing Wallet recovery material","issuedAt":iso.string(from:now),"expiresAt":iso.string(from:now.addingTimeInterval(300))];let data=try JSONSerialization.data(withJSONObject:request,options:.sortedKeys);let encoded=data.base64EncodedString().replacingOccurrences(of:"+",with:"-").replacingOccurrences(of:"/",with:"_").replacingOccurrences(of:"=",with:"");guard let url=URL(string:"ynxwallet://authorize?request=\(encoded)")else{throw URLError(.badURL)};return url}
    private static func random()->String{var b=[UInt8](repeating:0,count:24);_ = SecRandomCopyBytes(kSecRandomDefault,b.count,&b);return Data(b).base64EncodedString().replacingOccurrences(of:"+",with:"-").replacingOccurrences(of:"/",with:"_").replacingOccurrences(of:"=",with:"")}
}

@MainActor final class MusicModel:ObservableObject {
    @Published var snapshot=Snapshot();@Published var state=LocalState();@Published var status="loading";@Published var query="";let api=MusicAPI();let player=NativePlayer()
    init(){loadLocal();Task{await refresh()};player.onPosition={ [weak self] id,pos in guard let self else{return};self.state.trackId=id;self.state.position=pos;self.saveLocal();let ref=self.session(id);Task{try? await self.api.reportPosition(id:id,session:ref,position:pos,completed:false)}};player.onComplete={ [weak self] id,pos in guard let self else{return};let ref=self.session(id);Task{try? await self.api.reportPosition(id:id,session:ref,position:pos,completed:true)};UserDefaults.standard.removeObject(forKey:"playback-session-\(id)");if let at=self.state.queue.firstIndex(of:id),at+1<self.state.queue.count,let next=self.snapshot.catalog.first(where:{$0.id==self.state.queue[at+1]}){self.state.position=0;self.play(next)}}}
    var filtered:[Track]{query.isEmpty ? snapshot.catalog:snapshot.catalog.filter{($0.title+" "+$0.artistName+" "+($0.album ?? "")).localizedCaseInsensitiveContains(query)}}
    func refresh()async{status="loading";do{snapshot=try await api.snapshot();status="ready"}catch{status="offline_mode"}}
    func play(_ track:Track){let offline=offlineURL(track.id),url=FileManager.default.fileExists(atPath:offline.path) ? offline:api.base.appending(path:"api/tracks/\(track.id)/media");player.play(track:track,url:url,position:state.trackId==track.id ? state.position:0,token:Keychain.get("session"))}
    func favorite(_ id:String){state.favorites.contains(id) ? state.favorites.removeAll{$0==id}:state.favorites.append(id);saveLocal();syncLibrary()}
    func enqueue(_ id:String){if !state.queue.contains(id){state.queue.append(id);saveLocal();syncLibrary()}}
    func download(_ id:String){status="downloading";Task{do{_ = try await api.download(id);state.downloads[id]="available";saveLocal();try await api.saveLibrary(favorites:state.favorites,queue:state.queue,downloads:state.downloads);status="download_ready"}catch{status="download_failed"}}}
    func setAI(_ on:Bool){state.aiEnabled=on;saveLocal()}
    private func offlineURL(_ id:String)->URL{(try? FileManager.default.url(for:.applicationSupportDirectory,in:.userDomainMask,appropriateFor:nil,create:true))!.appending(path:"Offline/\(id).wav")}
    private var stateURL:URL{try! FileManager.default.url(for:.applicationSupportDirectory,in:.userDomainMask,appropriateFor:nil,create:true).appending(path:"music-state.json")}
    private func loadLocal(){if let d=try? Data(contentsOf:stateURL),let s=try? JSONDecoder().decode(LocalState.self,from:d){state=s}}
    private func saveLocal(){if let d=try? JSONEncoder().encode(state){try? d.write(to:stateURL,options:.atomic)}}
    private func syncLibrary(){let favorites=state.favorites,queue=state.queue,downloads=state.downloads;Task{try? await api.saveLibrary(favorites:favorites,queue:queue,downloads:downloads)}}
    private func session(_ id:String)->String{let key="playback-session-\(id)";if let value=UserDefaults.standard.string(forKey:key){return value};let value=UUID().uuidString;UserDefaults.standard.set(value,forKey:key);return value}
}

@MainActor final class NativePlayer {
    private var player:AVPlayer?;private var observer:Any?;private var completion:Any?;var onPosition:((String,Double)->Void)?;var onComplete:((String,Double)->Void)?;private var id=""
    init(){try? AVAudioSession.sharedInstance().setCategory(.playback,mode:.default,options:[]);try? AVAudioSession.sharedInstance().setActive(true);MPRemoteCommandCenter.shared().playCommand.addTarget{[weak self]_ in self?.player?.play();return .success};MPRemoteCommandCenter.shared().pauseCommand.addTarget{[weak self]_ in self?.player?.pause();return .success}}
    func play(track:Track,url:URL,position:Double,token:String?){id=track.id;if let observer,let player{player.removeTimeObserver(observer)};if let completion{NotificationCenter.default.removeObserver(completion)};var headers:[String:String]=[:];if let token{headers["Authorization"]="Bearer \(token)";headers["X-YNX-Device-ID"]="ynx-music-ios"};let asset=AVURLAsset(url:url,options:["AVURLAssetHTTPHeaderFieldsKey":headers]);let item=AVPlayerItem(asset:asset);player=AVPlayer(playerItem:item);if position>0{player?.seek(to:CMTime(seconds:position,preferredTimescale:1000))};player?.play();MPNowPlayingInfoCenter.default().nowPlayingInfo=[MPMediaItemPropertyTitle:track.title,MPMediaItemPropertyArtist:track.artistName,MPMediaItemPropertyPlaybackDuration:Double(track.durationMillis)/1000];observer=player?.addPeriodicTimeObserver(forInterval:CMTime(seconds:5,preferredTimescale:1),queue:.main){[weak self] t in guard let self else{return};self.onPosition?(self.id,t.seconds)};completion=NotificationCenter.default.addObserver(forName:.AVPlayerItemDidPlayToEndTime,object:item,queue:.main){[weak self]_ in guard let self else{return};self.onComplete?(self.id,Double(track.durationMillis)/1000)}}
}

struct TrackRow:View { @EnvironmentObject var m:MusicModel;let t:Track;@EnvironmentObject var l:I18n;var body:some View{VStack(alignment:.leading,spacing:8){Text(t.title).font(.headline);Text("\(t.artistName) · \(l.t("rights")): \(t.rights.basis) · \(l.t("provenance")): \(t.provenance["audio"] ?? "")").font(.caption).foregroundStyle(.secondary);HStack{Button(l.t("play")){m.play(t)};Button(l.t("favorite")){m.favorite(t.id)};Button(l.t("add_queue")){m.enqueue(t.id)};Button(l.t("download")){m.download(t.id)}}}.accessibilityElement(children:.contain).padding(.vertical,6)}}
struct HomeView:View{@EnvironmentObject var m:MusicModel;@EnvironmentObject var l:I18n;@Environment(\.openURL)var openURL;var body:some View{NavigationStack{List{if m.filtered.isEmpty{ContentUnavailableView(l.t("empty_catalog"),systemImage:"music.note",description:Text(l.t("retry")))}else{ForEach(m.filtered){TrackRow(t:$0)}}}.searchable(text:$m.query,prompt:l.t("search_hint")).navigationTitle(l.t("app_name")).toolbar{Button(l.t("sign_in_wallet")){if let u=try? WalletLink.make(){openURL(u)}}}.refreshable{await m.refresh()}}}}
struct LibraryView:View{@EnvironmentObject var m:MusicModel;@EnvironmentObject var l:I18n;@State var playlistName="";var body:some View{NavigationStack{List{Section(l.t("favorites")){ForEach(m.state.favorites,id:\.self){Text($0)}};Section(l.t("queue")){ForEach(m.state.queue,id:\.self){Text($0)}};Section(l.t("library")){TextField(l.t("library"),text:$playlistName);Button(l.t("upload")){Task{try? await m.api.createPlaylist(name:playlistName,ids:m.state.favorites)}}.disabled(playlistName.isEmpty||m.state.favorites.isEmpty)}}.navigationTitle(l.t("library"))}}}
struct CreatorView:View{@EnvironmentObject var m:MusicModel;@EnvironmentObject var l:I18n;@State var importing=false;@State var title="";@State var artist="";@State var evidence="";@State var provenance="";@State var aiStatus="";var body:some View{NavigationStack{Form{Text(l.t("creator_truth"));TextField(l.t("track_title"),text:$title);TextField(l.t("artist_name"),text:$artist);TextField(l.t("rights_evidence"),text:$evidence);TextField(l.t("provenance"),text:$provenance);Button(l.t("upload_owned_audio")){importing=true}.fileImporter(isPresented:$importing,allowedContentTypes:[.wav]){result in if case .success(let url)=result{Task{let access=url.startAccessingSecurityScopedResource();defer{if access{url.stopAccessingSecurityScopedResource()}};do{try await m.api.uploadOwnedWAV(url,title:title,artist:artist,evidence:evidence,provenance:provenance);await m.refresh()}catch{m.status="upload_failed"}}}};Section(l.t("usage_records")){Text(l.number(m.snapshot.usage.count))};Text(l.t("revenue_truth")).font(.footnote);Button(l.t("ai_enabled")){guard m.state.aiEnabled else{return};Task{do{aiStatus=try await m.api.createAI(ids:m.state.favorites,language:l.aiLanguage)}catch{aiStatus=l.t("retry")}}}.disabled(!m.state.aiEnabled||m.state.favorites.isEmpty);Text(aiStatus.isEmpty ? l.t("ai_explanation"):aiStatus).font(.footnote)}.navigationTitle(l.t("creator"))}}}
struct SettingsView:View{@EnvironmentObject var m:MusicModel;@EnvironmentObject var l:I18n;var body:some View{NavigationStack{Form{Picker(l.t("language"),selection:Binding(get:{l.tag},set:l.set)){Text("System").tag("system");ForEach(["en","zh-Hans","zh-Hant","ja","ko","es","fr","de","pt","ru","ar","id"],id:\.self){Text($0).tag($0)}};Toggle(l.t("ai_enabled"),isOn:Binding(get:{m.state.aiEnabled},set:m.setAI));Picker("AI output",selection:Binding(get:{l.aiLanguage},set:l.setAI)){Text("System").tag("system");ForEach(["en","zh-Hans","zh-Hant","ja","ko","es","fr","de","pt","ru","ar","id"],id:\.self){Text($0).tag($0)}};Text(l.t("ai_explanation"));Button(l.t("clear_private_data"),role:.destructive){Keychain.clear()}}.navigationTitle(l.t("settings"))}}}

@main struct YNXMusicApp:App{@StateObject var model=MusicModel();@StateObject var l=I18n.shared;var body:some Scene{WindowGroup{TabView{HomeView().tabItem{Label(l.t("home"),systemImage:"music.note.house")};LibraryView().tabItem{Label(l.t("library"),systemImage:"books.vertical")};CreatorView().tabItem{Label(l.t("creator"),systemImage:"waveform")};SettingsView().tabItem{Label(l.t("settings"),systemImage:"gear")}}.environmentObject(model).environmentObject(l).environment(\.locale,Locale(identifier:l.resolved)).environment(\.layoutDirection,l.rtl ? .rightToLeft:.leftToRight).tint(Color(red:0,green:47/255,blue:167/255)).onOpenURL{url in guard url.scheme=="ynxmusic",Date().timeIntervalSince1970<UserDefaults.standard.double(forKey:"walletExpires"),let response=URLComponents(url:url,resolvingAgainstBaseURL:false)?.queryItems?.first(where:{$0.name=="response"})?.value,let nonce=UserDefaults.standard.string(forKey:"walletNonce") else{return};UserDefaults.standard.removeObject(forKey:"walletNonce");UserDefaults.standard.removeObject(forKey:"walletExpires");Task{try? await model.api.walletSession(response:response,nonce:nonce)}}}}}
