import {fileURLToPath} from 'node:url';import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {build} from '../node_modules/esbuild/lib/main.js';import {chromium} from '../node_modules/playwright/index.mjs';
const root=new URL('../',import.meta.url);
// Engineering protocol fixture, not an installed Wallet or real Auth acceptance.
const sdkFixture=`export class ProductSessionGatewayFetchAdapter{};export async function createBrowserProductSessionClient(){const read=()=>JSON.parse(localStorage.getItem('qa-cloud-fixture')||'{"status":"guest"}');return {client:{restore:async()=>read(),beginExplicit:async()=>({status:'connecting',request:{},route:{url:'ynxwallet://qa-fixture'}}),handleReturn:async()=>{const state={status:'connected',session:{account:'ynx1fixtureA'}};localStorage.setItem('qa-cloud-fixture',JSON.stringify(state));return state},disconnect:async()=>{localStorage.removeItem('qa-cloud-fixture');return {status:'disconnected'}}},createIntrospectionProof:async scopes=>{if(read().status!=='connected')throw Object.assign(new Error('inactive'),{code:'SESSION_INACTIVE'});return {proofHeader:'engineering-fixture:'+scopes.join(',')}}}}`;
const output=await build({absWorkingDir:fileURLToPath(new URL('../..',root)),entryPoints:[fileURLToPath(new URL('web/app.js',root))],bundle:true,write:false,format:'iife',platform:'browser',target:'es2022',plugins:[{name:'isolated-protocol-fixture',setup(b){b.onLoad({filter:/wallet-sdk-a7dad7ec\/product-session-browser\.mjs$/},()=>({contents:sdkFixture,loader:'js'}))}}]});
test('normal Cloud page chooser, approve, own file create, reload, unavailable action and signout at 360px',async()=>{
 const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:360,height:780}});const page=await context.newPage();const errors=[],requests=[],objects=[];page.on('pageerror',e=>errors.push(e.message));
 await context.addInitScript(()=>{const handlers=new Map();window.ethereum={isYNXWallet:true,request:async input=>{if(input.method!=='ynx_requestProductSessionV2')throw new Error('Unexpected method');window.qaRequests=(window.qaRequests||0)+1;if(window.qaHoldApproval)await new Promise(resolve=>window.qaReleaseApproval=resolve);return {version:2,returnUrl:'https://web4.ynxweb4.com/wallet-auth/callback?state=fixture'}},on(event,callback){handlers.set(event,callback)},removeListener(event){handlers.delete(event)}};window.qaAccountChange=()=>handlers.get('accountsChanged')?.(['changed']);});
 await context.route('**/*',async route=>{const request=route.request(),url=new URL(request.url());if(url.pathname.startsWith('/api/v1')){requests.push({path:url.pathname,method:request.method(),proof:request.headers()['x-ynx-product-session-proof-v2'],bearer:request.headers().authorization,key:request.headers()['idempotency-key']});if(request.method()==='POST'){const body=request.postDataJSON();objects.push({id:'folder1',kind:body.kind,name:body.name,size:0,version:1,updatedAt:new Date().toISOString()});await route.fulfill({contentType:'application/json',body:JSON.stringify(objects[0])});return}await route.fulfill({contentType:'application/json',body:JSON.stringify({items:objects})});return}
  if(url.pathname==='/cloud/app.bundle.js'){await route.fulfill({contentType:'application/javascript',body:output.outputFiles[0].text});return}
  const relative=url.pathname.replace(/^\/cloud\//,'web/');try{const body=await readFile(new URL(relative,root));await route.fulfill({contentType:relative.endsWith('.html')?'text/html':relative.endsWith('.css')?'text/css':relative.endsWith('.json')?'application/json':relative.endsWith('.png')?'image/png':'application/javascript',body})}catch{await route.fulfill({status:404,body:'missing'})}
 });
 try{
  await page.goto('https://web4.ynxweb4.com/cloud/index.html');await page.click('#wallet');assert.equal(await page.locator('#auth-choices').isVisible(),true);
  await page.click('#auth-hosted');assert.equal(await page.locator('#auth-choices').isVisible(),false);assert.match(await page.locator('#auth-state').textContent(),/not available/);await page.click('#auth-back');assert.equal(await page.locator('#auth-choices').isVisible(),true);
  await page.click('#auth-start');await page.waitForFunction(()=>!document.querySelector('#auth-dialog').open);assert.equal(await page.evaluate(()=>window.qaRequests),1);
  page.once('dialog',d=>d.accept('QA folder'));await page.click('#new-folder');await page.waitForFunction(()=>document.querySelector('#files').textContent.includes('QA folder'));
  assert.equal(requests.filter(r=>r.method==='POST').length,1);assert.ok(requests.every(r=>r.proof&&!r.bearer));assert.match(requests.find(r=>r.method==='POST').key,/^[A-Za-z0-9_-]{16,128}$/);
  await page.reload();await page.waitForFunction(()=>document.querySelector('#files').textContent.includes('QA folder'));assert.equal(await page.evaluate(()=>window.qaRequests||0),0);
  const before=requests.length;await page.click('#export-data');assert.match(await page.locator('#status').textContent(),/not yet available/);assert.equal(requests.length,before);
  await page.click('#wallet');await page.click('#auth-disconnect');await page.waitForFunction(()=>document.querySelector('#files').children.length===0);assert.equal(await page.evaluate(()=>localStorage.getItem('qa-cloud-fixture')),null);
  await page.click('#auth-dialog [value=cancel]');await page.evaluate(()=>window.qaHoldApproval=true);await page.click('#wallet');await page.click('#auth-start');await page.waitForFunction(()=>typeof window.qaReleaseApproval==='function');await page.click('#auth-dialog [value=cancel]');await page.evaluate(()=>{window.qaHoldApproval=false;window.qaReleaseApproval()});await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>localStorage.getItem('qa-cloud-fixture')),null);assert.equal(await page.locator('#auth-dialog').isVisible(),false);await page.click('#wallet');await page.click('#auth-start');await page.waitForFunction(()=>!document.querySelector('#auth-dialog').open);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(errors,[]);
 }finally{await browser.close()}
});
